...

diff --git a/mod/gh/lib/org/apply b/mod/gh/lib/org/apply
--- a/mod/gh/lib/org/apply
+++ b/mod/gh/lib/org/apply
@@ -19,11 +19,11 @@ ___x_cmd_gh_org_apply(){
                 *)              <"$filepath" x y2j ;;
             esac | {
                 x jo env . content=. org=.org  membership_admin=.membership.admin membership_member=.membership.member
-                [ -n "$org" ] || { gh_log error "Not found apply configure 'org' main key" >/dev/stderr; return 1; }
+                [ -n "$org" ] || { gh:error "Not found apply configure 'org' main key" >/dev/stderr; return 1; }
 
                 ___x_cmd_gh_org_apply__replace_args "$@"
                 printf "%s\n" "$content"
-                gh_log info "Getting org info ..."
+                gh:info "Getting org info ..."
                 ___x_cmd_gh_org_apply__org_info
                 ___x_cmd_gh_org_apply__membership_admin_info
                 ___x_cmd_gh_org_apply__membership_member_info
@@ -40,19 +40,19 @@ ___x_cmd_gh_org_apply(){
                 -f "$___X_CMD_ROOT_MOD/gh/lib/org/apply.awk"
         }
     )"; then
-        gh_log debug "apply code: $code"
+        gh:debug "apply code: $code"
         [ -n "$code" ] || {
-            printf "%s\n" ""; gh_log info "Org apply no changes required"
+            printf "%s\n" ""; gh:info "Org apply no changes required"
             return 0
         }
-        gh_log info "Handling Org by info ..."
+        gh:info "Handling Org by info ..."
         # if [ -n "$___X_CMD_GH_DRY_RUN" ]; then      printf "%s\n" "$code";
         # else                                        eval "$code";
         # fi
         echo "$code"
     else
         code=$?
-        gh_log error "Exit=$code. Fail to apply: $filepath" >/dev/stderr
+        gh:error "Exit=$code. Fail to apply: $filepath" >/dev/stderr
     fi
 }
 
diff --git a/mod/gh/lib/repo/apply/index b/mod/gh/lib/repo/apply/index
--- a/mod/gh/lib/repo/apply/index
+++ b/mod/gh/lib/repo/apply/index
@@ -16,12 +16,12 @@ ___x_cmd_gh_repo_apply(){
         {
             ___x_cmd_gh_repo_apply___parse_data | {
                 x jo env . content=. owner_repo=.repo  apply_collaborator=.collaborator
-                [ -n "$content" ]    || { gh_log error "Not found apply configure data"; printf "%s\n" "$_errexit"; return 1; }
-                [ -n "$owner_repo" ] || { gh_log error "Not found apply configure 'repo' main key"; printf "%s\n" "$_errexit"; return 1; }
+                [ -n "$content" ]    || { gh:error "Not found apply configure data"; printf "%s\n" "$_errexit"; return 1; }
+                [ -n "$owner_repo" ] || { gh:error "Not found apply configure 'repo' main key"; printf "%s\n" "$_errexit"; return 1; }
 
                 ___x_cmd_gh_repo_apply__replace "$@"
                 printf "%s\n" "$content"
-                gh_log info "Getting repo info ..."
+                gh:info "Getting repo info ..."
                 ___x_cmd_gh_repo_apply__collaborator_info
                 ___x_cmd_gh_repo_apply__repo_info
             }
@@ -38,19 +38,19 @@ ___x_cmd_gh_repo_apply(){
                 -f "$___X_CMD_ROOT_MOD/gh/lib/repo/apply/apply.awk"
         }
     )"; then
-        gh_log debug "apply code: $code"
+        gh:debug "apply code: $code"
         [ -n "$code" ] || {
-            printf "%s\n" ""; gh_log info "Repo apply no changes required"
+            printf "%s\n" ""; gh:info "Repo apply no changes required"
             return 0
         }
-        gh_log info "Handling repo by info ..."
+        gh:info "Handling repo by info ..."
         if [ -n "$___X_CMD_GH_DRY_RUN" ]; then      printf "%s\n" "$code";
         else                                        eval "$code";
         fi
         # echo "$code"
     else
         code=$?
-        gh_log error "Exit=$code. Fail to apply: $filepath" >/dev/stderr
+        gh:error "Exit=$code. Fail to apply: $filepath" >/dev/stderr
     fi
 }
 
