Updating main branch using x7 release -> 12963cc3e14c8b94e9edb8d2a729ec37286fe420

diff --git a/mod/apk/lib/__xmirror/_index b/mod/apk/lib/__xmirror/_index
--- a/mod/apk/lib/__xmirror/_index
+++ b/mod/apk/lib/__xmirror/_index
@@ -3,34 +3,63 @@
 # For alpine users
 # Reference: https://blog.csdn.net/qq_33657251/article/details/107526842
 
-
 ___x_cmd_apk___xmirror(){
-    [ "$#" -gt 0 ] ||   set -- --help
+    local ___X_CMD_APK_MIRROR_SOURCES='/etc/apk/repositories'
+    ___x_cmd_apk___xmirror___ensure || return $?
+
+    [ "$#" -gt 0 ] || { ___x_cmd_apk___xmirror___app ; return ; }
 
     local op="$1"; shift
     case "$op" in
         -h|--help)
-            x help -m mirror apk         "$@"
-            return   ;;
+                ___x_cmd help -m apk mirror                  "$@" ;;
+        ls|replace|current|rollback)
+                ___x_cmd_apk___xmirror_"${op}"               "$@" ;;
+        set)    ___x_cmd_apk___xmirror_replace               "$@" ;;
+        unset)  ___x_cmd_apk___xmirror_rollback              "$@" ;;
+        *)      N=apk M="subcommand not found."    log:ret:1      ;;
     esac
+}
 
-    x hascmd apk || N=mirror M="[command=apk] not found." log:ret:1
-    case "$op" in
-        ls|current|replace|unset)     ___x_cmd_apk___xmirror_"${op}"  "$@" ;;
-        set)                          ___x_cmd_apk___xmirror_replace  "$@" ;;
-        *)                            ___x_cmd_mirror___util_subcmd_invalid apk "$@" ;;
+___x_cmd_apk___xmirror___ensure(){
+    ___x_cmd_hascmd apk || N=apk M="[command=apk] not found." log:ret:1
+}
+
+___x_cmd_apk___xmirror___app(){
+    local _SELECT
+    ___x_cmd ui select "_SELECT" \
+        "Methods:" \
+            "Set apk mirror (default is ali)" \
+            "Get current apk mirror" \
+            "List all the apk mirror candidates" \
+            "Rollback the apk mirror to the original official"
+
+    case "$_SELECT" in
+        1)  ___x_cmd_apk___xmirror replace       ;;
+        2)  ___x_cmd_apk___xmirror current       ;;
+        3)  ___x_cmd_apk___xmirror ls            ;;
+        4)  ___x_cmd_apk___xmirror rollback      ;;
+        *)  apk:info "Canceled" ;        return 1 ;;
     esac
 }
 
 ___x_cmd_apk___xmirror_ls(){
     printf "%s\n" \
-        "Code          Url                             Name" \
-        "ustc          mirrors.ustc.edu.cn             ustc official" \
-        "official      dl-cdn.alpinelinux.org          Official"
+        "Code          Url                                  Name"              \
+        "official      dl-cdn.alpinelinux.org               官方源"             \
+        "ali           mirrors.aliyun.com                   阿里云镜像"          \
+        "huawei        mirrors.huaweicloud.com              华为镜像"            \
+        "tuna          mirrors.tuna.tsinghua.edu.cn         清华大学镜像"         \
+        "ustc          mirrors.ustc.edu.cn                  中国科学技术大学镜像"  \
+        "sjtu          mirrors.sjtug.sjtu.edu.cn            上海交通大学镜像"
+}
+
+___x_cmd_apk___xmirror_advise_ls(){
+    ___x_cmd_apk___xmirror_ls | ___x_cmd_cmds_awk 'NR >1 { print $1 }'
 }
 
 ___x_cmd_apk___xmirror_current(){
-    ___x_cmd_cmds_cat /etc/apk/repositories
+    ___x_cmd_cmds_cat "$___X_CMD_APK_MIRROR_SOURCES"
 }
 
 ___x_cmd_apk___xmirror___url(){
@@ -39,43 +68,45 @@ ___x_cmd_apk___xmirror___url(){
 }
 
 ___x_cmd_apk___xmirror_replace() {
-    [ "$#" -gt 0 ] ||   set -- ustc
+    [ "$#" -gt 0 ] ||   set -- ali
     case "$1" in
         -h|--help)
-            x help -m mirror apk replace "$@"
-            return   ;;
+            ___x_cmd help -m mirror apk replace "$@";    return ;;
     esac
 
     ___x_cmd_apk___xmirror_save || N=mirror M="Save apk original config failed." log:ret:1
 
     local url
     url="$(___x_cmd_apk___xmirror___url "${1}")" || return $?
+    if [ -z "$url" ]; then
+        apk:error "Invalid mirror name: $1"
+        return 1
+    fi
 
-    local src_path=/etc/apk/repositories
     # ___x_cmd_proxy___util_backup "$src_path" apk
 
     if [ "$(id -u)" -ne 0 ]; then
         mirror:warn "using sudo"
-        sudo sed -i "s|$(___x_cmd_apk___xmirror___url official)/alpine|$url/alpine|g" "$src_path"
-        apk update
+        ___x_cmd sudo sed -E -i "s|https://[^/]+/alpine/|https://$url/alpine/|g" "$___X_CMD_APK_MIRROR_SOURCES"
     else
-        sed -i "s|$(___x_cmd_apk___xmirror___url official)/alpine|${url}/alpine|g" "$src_path"
-        apk update
+        ___x_cmd_cmds sed -E -i "s|https://[^/]+/alpine/|https://$url/alpine/|g" "$___X_CMD_APK_MIRROR_SOURCES"
     fi
+
+    ___x_cmd apk update
 }
 
 ___x_cmd_apk___xmirror_save(){
-    ___x_cmd_mirror___util_save "/etc/apk/repositories" "apk"
+    ___x_cmd_mirror___util_save "$___X_CMD_APK_MIRROR_SOURCES" "apk"
 }
 
 ___x_cmd_apk___xmirror_unset(){
-    ___x_cmd_mirror___util_rollback_original "/etc/apk/repositories" "apk" || return $?
-    x rmrf "$___X_CMD_ROOT_DATA/mirror/apk"
+    ___x_cmd_mirror___util_rollback_original "$___X_CMD_APK_MIRROR_SOURCES" "apk" || return $?
+    ___x_cmd rmrf "$___X_CMD_ROOT_DATA/mirror/apk"
 
     if [ "$(id -u)" -ne 0 ]; then
-        x sudo apk update
+        ___x_cmd sudo apk update
     else
-               apk update
+        ___x_cmd_cmds apk update
     fi
 }
 
diff --git a/mod/dnf/lib/__xmirror/_index b/mod/dnf/lib/__xmirror/_index
--- a/mod/dnf/lib/__xmirror/_index
+++ b/mod/dnf/lib/__xmirror/_index
@@ -1,171 +1,161 @@
-# shellcheck shell=sh disable=SC3043
+# shellcheck shell=dash
+
 ___x_cmd_dnf___xmirror(){
-    [ $# -gt 0 ]    ||  set - --help
-    local op="$1";      shift
+    local ___X_CMD_DNF_MIRROR_SOURCES=
+    local ___X_CMD_DNF_MIRROR_UPDATES_SOURCES=
+    local ___X_CMD_OS_RELEASE=
+    ___x_cmd_dnf___xmirror___ensure || return $?
 
-    local O=dnf
-    case "$op" in
-        # TODO: maybe just use 'x yum --xmirror "$@"'
-
-        ls|set|current|unset)      ___x_cmd_mirror_dnf        "$op" "$@" ;;
-        -h|--help)                 x help -m dnf mirror             "$@" ;;
-    esac
-}
-
-# For centos users
-# Reference:
-#   https://mirrors.tuna.tsinghua.edu.cn/help/fedora/
-#   https://zhuanlan.zhihu.com/p/151425818
-#   https://www.cnblogs.com/wswind/p/11751829.html
-
-___x_cmd_mirror_dnf(){
-    [ "$#" -gt 0 ] || set -- --help
+    [ "$#" -gt 0 ] || { ___x_cmd_dnf___xmirror___app ; return ; }
 
     local op="$1"; shift
     case "$op" in
         -h|--help)
-            x help -m mirror dnf "$@"
-            return   ;;
-    esac
-    local ___X_CMD_OS_RELEASE="$(x os rname)"
-    x hascmd dnf || N=mirror M="[command=dnf] not found." log:ret:1
-    case "$op" in
-        ls|replace|current|unset)
-                ___x_cmd_mirror_dnf_"${op}"               "$@" ;;
-        set)    ___x_cmd_mirror_dnf_replace               "$@" ;;
-        *)      ___x_cmd_mirror___util_subcmd_invalid dnf "$@" ;;
+                ___x_cmd help -m dnf mirror                  "$@" ;;
+        ls|replace|current|rollback)
+                ___x_cmd_dnf___xmirror_"${op}"               "$@" ;;
+        set)    ___x_cmd_dnf___xmirror_replace               "$@" ;;
+        unset)  ___x_cmd_dnf___xmirror_rollback              "$@" ;;
+        *)      N=dnf M="subcommand not found."    log:ret:1      ;;
     esac
 }
 
-___x_cmd_mirror_dnf_ls(){
-    printf "%s\n" \
-        "Code       Url                                      Name" \
-        "ali        https://mirrors.aliyun.com               阿里云" \
-        "ustc       https://mirrors.ustc.edu.cn              中国科学技术大学开源镜像站" \
-        "tuna       https://mirrors.tuna.tsinghua.edu.cn     清华大学开源软件镜像站"
-}
+___x_cmd_dnf___xmirror___ensure(){
+    ___x_cmd_hascmd dnf || N=dnf M="[command=dnf] not found." log:ret:1
 
-# TODO: support more version
-___x_cmd_mirror_dnf_current(){
-    local src_file
+    ___X_CMD_OS_RELEASE="$(___x_cmd os release)"
     case "$___X_CMD_OS_RELEASE" in
-        *centos*)       src_file="$(___x_cmd_cmds ls -1 /etc/yum.repos.d/CentOS-*Base*.repo | head -n 1)" ;;
-        *fedora*)       src_file="/etc/yum.repos.d/fedora.repo" ;;
-        *)              mirror:error "Unsupported system: $___X_CMD_OS_RELEASE"
-                        return 1
-                        ;;
+        *Fedora*|*fedora*)
+            ___X_CMD_OS_RELEASE="fedora"
+            ___X_CMD_DNF_MIRROR_SOURCES="/etc/yum.repos.d/fedora.repo"
+            ___X_CMD_DNF_MIRROR_UPDATES_SOURCES="/etc/yum.repos.d/fedora-updates.repo"
+            ;;
+        # TODO: centos10, centos9, centos stream
+        # *CentOS*|*centos*)
+        #     ___X_CMD_OS_RELEASE="centos"
+        #     ___X_CMD_DNF_MIRROR_SOURCES="/etc/yum.repos.d/CentOS-Base.repo"
+        #     ___X_CMD_DNF_MIRROR_UPDATES_SOURCES=
+        #     ;;
+        *)
+            N=dnf M="Unsupported system: $___X_CMD_OS_RELEASE" log:ret:1
+            ;;
     esac
-    ___x_cmd_cmds_cat "$src_file"
 }
 
-xrc mirror
-___x_cmd_mirror_dnf___url(){
-    ___x_cmd_mirror_dnf_ls | \
+___x_cmd_dnf___xmirror___app(){
+    local _SELECT
+    ___x_cmd ui select "_SELECT" \
+        "Methods:" \
+            "Set dnf mirror (default is ali)" \
+            "Get current dnf mirror" \
+            "List all the dnf mirror candidates" \
+            "Rollback the dnf mirror to the original official"
+
+    case "$_SELECT" in
+        1)  ___x_cmd_dnf___xmirror replace       ;;
+        2)  ___x_cmd_dnf___xmirror current       ;;
+        3)  ___x_cmd_dnf___xmirror ls            ;;
+        4)  ___x_cmd_dnf___xmirror rollback      ;;
+        *)  dnf:info "Canceled" ;        return 1 ;;
+    esac
+}
+
+___x_cmd_dnf___xmirror_ls(){
+    printf "%s\n" \
+        "Code       Url                                      Name"                \
+        "ali        https://mirrors.aliyun.com               阿里云镜像"            \
+        "huawei     https://mirrors.huaweicloud.com          华为云镜像"            \
+        "tuna       https://mirrors.tuna.tsinghua.edu.cn     清华大学镜像"          \
+        "ustc       https://mirrors.ustc.edu.cn              中国科学技术大学镜像"    \
+        "bfsu       https://mirrors.bfsu.edu.cn              北京外国语大学镜像"
+}
+
+___x_cmd_dnf___xmirror_advise_ls(){
+    ___x_cmd_dnf___xmirror_ls | ___x_cmd_cmds_awk 'NR >1 { print $1 }'
+}
+
+___x_cmd_dnf___xmirror_current(){
+    ___x_cmd_cmds_cat "$___X_CMD_DNF_MIRROR_SOURCES"
+}
+
+___x_cmd_dnf___xmirror___url(){
+    ___x_cmd_dnf___xmirror_ls | \
         ___x_cmd_mirror___util_get_url_by_name "$1"
 }
 
-___x_cmd_mirror_dnf_replace(){
+___x_cmd_dnf___xmirror_replace(){
     [ "$#" -gt 0 ] ||   set -- ali
     case "$1" in
-        -h|--help)
-            x help -m mirror dnf replace "$@"
-            return   ;;
+        -h|--help) ___x_cmd help -m mirror dnf replace "$@";    return ;;
     esac
 
-    local src_dir
-    src_dir="/etc/yum.repos.d"
+    ___x_cmd_dnf___xmirror_save || N=dnf M="Save dnf original sources list failed." log:ret:1
+
     # ___x_cmd_proxy___util_backup $src_dir dnf
 
     local url
-    local src="$1"
-    url="$(___x_cmd_mirror_dnf___url "$src")" || return $?
-    mirror:info "Setting dnf mirror $url"
+    url="$(___x_cmd_dnf___xmirror___url "${1}")" || return $?
+    if [ -z "$url" ]; then
+        dnf:error "Invalid mirror name: $1"
+        return 1
+    fi
+    dnf:info "Setting dnf mirror $url"
 
     case "$___X_CMD_OS_RELEASE" in
-        *centos*)
-                    local version_id
-                    xrc os && ___x_cmd_os release __ version_id
-                    case "$version_id" in
-                        *7*)
-                            ___x_cmd_mirror_dnf_replace_exec \
-                                -e 's|^mirrorlist=|#mirrorlist=|g' \
-                                -e "s|^#baseurl=http://mirror.centos.org/centos|baseurl=${url}/centos|g" \
-                                -i.bak \
-                                ${src_dir}/CentOS-*.repo || return 1
-                                ___x_cmd_mirror_dnf_save
-                            ;;
-                        *8*)
-                            minorver=8.5.2111
-                            ___x_cmd_mirror_yum_replace_exec \
-                                -e 's|^mirrorlist=|#mirrorlist=|g' \
-                                -e "s|^#baseurl=http://mirror.centos.org/\$contentdir/\$releasever|baseurl=${url}/centos-vault/$minorver|g" \
-                                -i.bak \
-                                ${src_dir}/CentOS-*.repo || return 1
-                                ___x_cmd_mirror_yum_save
-                            ;;
-                        *)
-                            mirror:error "Unsupported version: $version_id"
-                            return 1
-                            ;;
-                    esac
+        *Fedora*|*fedora*)
+            ___x_cmd_dnf___xmirror_replace___fedora
             ;;
-        *fedora*)
-                    ___x_cmd_mirror_dnf_replace_exec \
-                        -e 's|^metalink=|#metalink=|g' \
-                        -e "s|^#baseurl=http://download.example/pub/fedora/linux|baseurl=${url}/fedora|g" \
-                        -i.bak \
-                        ${src_dir}/fedora.repo \
-                        ${src_dir}/fedora-updates.repo \
-                        ${src_dir}/fedora-modular.repo \
-                        ${src_dir}/fedora-updates-modular.repo 2>/dev/null || return 1
-                        ___x_cmd_mirror_dnf_save
-            ;;
-        *)          mirror:error "Unsupported system: $___X_CMD_OS_RELEASE"
-                    return 1
+        *)
+            N=dnf M="Unsupported system: $___X_CMD_OS_RELEASE" log:ret:1
             ;;
     esac
+}
 
-    mirror:info "Restarting dnf"
-    dnf clean all
+___x_cmd_dnf___xmirror_replace___fedora(){
     if [ "$(id -u)" -ne 0 ]; then
-        x sudo dnf makecache
+        dnf:warn "using sudo"
+        ___x_cmd sudo sed -i -e "s/^#baseurl/baseurl/g" -e "s/^metalink/#metalink/g" \
+            "$___X_CMD_DNF_MIRROR_SOURCES" "$___X_CMD_DNF_MIRROR_UPDATES_SOURCES"
+        ___x_cmd sudo sed -E -i "s|baseurl=http[^ ]*/Everything/|baseurl=$url/fedora/releases/\$releasever/Everything/|g" \
+            "$___X_CMD_DNF_MIRROR_SOURCES"
+        ___x_cmd sudo sed -E -i "s|baseurl=http[^ ]*/Everything/|baseurl=$url/fedora/updates/\$releasever/Everything/|g" \
+            "$___X_CMD_DNF_MIRROR_UPDATES_SOURCES"
+        ___x_cmd sudo dnf clean all
+        ___x_cmd sudo dnf makecache --refresh
     else
-        dnf makecache
+        ___x_cmd_cmds sed -i -e "s/^#baseurl/baseurl/g" -e "s/^metalink/#metalink/g" \
+            "$___X_CMD_DNF_MIRROR_SOURCES" "$___X_CMD_DNF_MIRROR_UPDATES_SOURCES"
+        ___x_cmd_cmds sed -E -i "s|baseurl=http[^ ]*/Everything/|baseurl=$url/fedora/releases/\$releasever/Everything/|g" \
+            "$___X_CMD_DNF_MIRROR_SOURCES"
+        ___x_cmd_cmds sed -E -i "s|baseurl=http[^ ]*/Everything/|baseurl=$url/fedora/updates/\$releasever/Everything/|g" \
+            "$___X_CMD_DNF_MIRROR_UPDATES_SOURCES"
+        ___x_cmd_cmds dnf clean all
+        ___x_cmd_cmds dnf makecache --refresh
     fi
 }
 
-___x_cmd_mirror_dnf_replace_exec(){
-    if [ "$(id -u)" -ne 0 ]; then
-        mirror:warn "using sudo"
-        sudo sed "$@"
-    else
-        ___x_cmd_cmds sed "$@"
+___x_cmd_dnf___xmirror_save(){
+    ___x_cmd_mirror___util_save "$___X_CMD_DNF_MIRROR_SOURCES" "dnf"
+    if [ -f "$___X_CMD_DNF_MIRROR_UPDATES_SOURCES" ]; then
+        ___x_cmd_mirror___util_save "$___X_CMD_DNF_MIRROR_UPDATES_SOURCES" "dnf.patch"
     fi
 }
 
-
-___x_cmd_mirror_dnf_save(){
-    local src_dir
-    src_dir="/etc/yum.repos.d"
-
-    local rollback_file_fp="$___X_CMD_ROOT_DATA/mirror/dnf/"
-
-    ___x_cmd_mirror___util_save___bak "$src_dir" "$rollback_file_fp"
-}
-
-___x_cmd_mirror_dnf_unset(){
-    local rollback_file_dir="$___X_CMD_ROOT_DATA/mirror/dnf/"
-
-    ___x_cmd_mirror___util_rollback_original___bak "/etc/yum.repos.d/" "$rollback_file_dir"
-
+___x_cmd_dnf___xmirror_rollback(){
+    ___x_cmd_mirror___util_rollback_original "$___X_CMD_DNF_MIRROR_SOURCES" "dnf" || return $?
+    if [ -f "$___X_CMD_DNF_MIRROR_UPDATES_SOURCES" ]; then
+        ___x_cmd_mirror___util_rollback_original "$___X_CMD_DNF_MIRROR_UPDATES_SOURCES" "dnf.patch" || return $?
+    fi
+    ___x_cmd rmrf "$___X_CMD_ROOT_DATA/mirror/dnf"
 
     if [ "$(id -u)" -ne 0 ]; then
-        x sudo dnf makecache
+        ___x_cmd sudo dnf clean all
+        ___x_cmd sudo dnf makecache --refresh
     else
-               dnf makecache
+        ___x_cmd_cmds dnf clean all
+        ___x_cmd_cmds dnf makecache --refresh
     fi
 }
-
 # EndSection
 
 
diff --git a/mod/pacman/lib/main b/mod/pacman/lib/main
--- a/mod/pacman/lib/main
+++ b/mod/pacman/lib/main
@@ -1,81 +1,67 @@
-# shellcheck shell=dash disable=SC2034,SC2016
+# shellcheck shell=dash
+___x_cmd log init pacman
+
+xrc mirror proxy
+xrc:mod:lib     pacman   __xmirror/_index __proxy ls install nv fz
+
 ___x_cmd_pacman___main(){
-    [ "$#" -gt 0 ] ||   set -- nv
+    [ "$#" -gt 0 ] ||   set -- fz
+
+    ___x_cmd_hascmd pacman   ||  {
+        pacman:warn "pacman is not found."
+        return 1
+    }
 
     local op="$1"; shift
     case "$op" in
-        install)            ___x_cmd_pacman___install           "$@"     ;;
-        ls)                 ___x_cmd_pacman_ls                  "$@"     ;;
-        la)                 ___x_cmd_pacman_la                  "$@"     ;;
-        nv)                 ___x_cmd_pacman___nv                "$@"     ;;
-        mirror|--xmirror)   ___x_cmd_pacman___xmirror           "$@"     ;;
-        proxy|--xproxy)     ___x_cmd_pacman___xproxy            "$@"     ;;
+        i|install)          ___x_cmd_pacman___install               "$@" ;;
+
+        ls)                 ___x_cmd_pacman_ls                      "$@" ;;
+        la)                 ___x_cmd_pacman_la                      "$@" ;;
+
+        nv)                 ___x_cmd_pacman___nv                    "$@" ;;
+        fz)                 ___x_cmd_pacman___fz                    "$@" ;;
+        --fzdata)           ___x_cmd_pacman_install___fz_data       "$@" ;;
+        --fzfpreview)       ___x_cmd_pacman_install___fzf_preview   "$@" ;;
+        mirror|--xmirror)   ___x_cmd_pacman___xmirror               "$@" ;;
+        proxy|--xproxy)     ___x_cmd_pacman___xproxy                "$@" ;;
+
         browse)             ___x_cmd_pacman___repo_browse                ;;
-        --help|-h)          ___x_cmd help -m pacman;       return ;;
-        *)                  ___x_cmd_cmds pacman       "$op" "$@" ;;
+        --help|-h)          ___x_cmd help -m pacman;              return ;;
+
+        --runmain|--)       ___x_cmd_cmds pacman                    "$@" ;;
+        *)                  ___x_cmd_cmds pacman              "$op" "$@" ;;
     esac
 }
 
-___x_cmd_pacman___nv(){
-    local X_help_cmd='x help -m pacman nv'
-    help:arg:parse
-    ___x_cmd_is_stdout2tty || {
-        ___x_cmd_pacman___lsraw
-        return 0
-    }
+___x_cmd_pacman___init(){
+    ___X_CMD_PACMAN_CACHE_PATH="$___X_CMD_ROOT_DATA/pacman/cache"
+    ___x_cmd mkdirp "$___X_CMD_PACMAN_CACHE_PATH"
+}
 
+___x_cmd_pacman___init
 
-    local x_=""
-    ___x_cmd_pacman___lsraw_ || return
-    local datafile="$x_"
-    x_=; ___x_cmd storeread_ x pick --width 40 --col 10  --datafile "$datafile" \
-        || {
-            pacman:info "Exit because no software is selected."
-            return 0
-        }
-    local software=$x_
-    [ -n "$software" ] || return 1
-    local id=
-    ___x_cmd ui select id "What to do NEXT"                        \
-        "Install $software"                                 \
-        "View $software's version"                          \
-        "EXIT"     || return
+___x_cmd_pacman___exec(){
+    if [ "$(id -u)" -ne 0 ]; then
+        ___x_cmd sudo pacman "$@"
+    else
+        ___x_cmd_cmds pacman "$@"
+    fi
+}
 
-    case "$id" in
-        1)      x sudo pacman --sync "$software"  ;;
-        2)      x sudo pacman --query "$software" ;;
-        3)      return 0 ;;
-    esac
+___x_cmd_pacman___repo_browse(){
+    ___x_cmd browse "https://wiki.archlinux.org/title/pacman"
 }
 
 ___x_cmd_pacman___lsraw(){
     ___x_cmd_cmds pacman -Sl | ___x_cmd_cmds awk '{print $2}'
 }
 
-___x_cmd_pacman___install(){
-    local X_help_cmd='x help -m pacman install'
-    help:arg:parse
-
-    if [ "$#" -eq 0 ]; then
-        ___x_cmd_pacman___nv
-        return 0
-    fi
-
-    # Using x sudo
-
-    x sudo pacman -S "$@"
-}
-
-
-___x_cmd_pacman___repo_browse(){
-    x browse "https://wiki.archlinux.org/title/pacman"
-}
-
 ___x_cmd_pacman___lsraw_(){
-    x_="$___X_CMD_PKG_CACHE_PATH/lsname"
+    x_="$___X_CMD_PACMAN_CACHE_PATH/lsname"
     [ "$x_" -nt "/var/lib/pacman/sync/core.db" ] || {
-        x rmrf "$x_"
-        x ensurefp "$x_"
+        ___x_cmd rmrf "$x_"
+        ___x_cmd ensurefp "$x_"
         ___x_cmd_pacman___lsraw > "$x_"
     }
     [ -f "$x_" ]
