Updating main branch using x7 release -> 286ee022ff176c635f0f02c3d5c07b2d96f6fa32

diff --git a/mod/fileage/lib/main b/mod/fileage/lib/main
--- a/mod/fileage/lib/main
+++ b/mod/fileage/lib/main
@@ -27,14 +27,14 @@ ___x_cmd_fileage___main(){
 ___x_cmd_fileage___in(){
     local current=""; current="$(date +%s)"
     local date="$1"
-    [ -n "$date" ] || { x log :fileage error -h 'x fileage --in <human_time_unit e.g 1d> <file_path>' "Provide human time unit"; return 64; }
+    [ -n "$date" ] || { ___x_cmd log :fileage error -h 'x fileage --in <human_time_unit e.g 1d> <file_path>' "Provide human time unit"; return 64; }
     shift 1
-    local x_="";   x humantime tosec_ "$date"
+    local x_="";   ___x_cmd humantime tosec_ "$date"
 
     local ts=""
     ___x_cmd_fileage_stat "$@" | while read -r ts; do
         [ -n "$ts" ] || {
-            x log :fileage error "Get fileage failure. Please check the file exists. TS=$ts"
+            ___x_cmd log :fileage error "Get fileage failure. Please check the file exists. TS=$ts"
             local IFS=" "; x log :fileage error "filelist ==> $*"
             return 1
         }
@@ -47,14 +47,14 @@ ___x_cmd_fileage___exec(){
     local human="";     [ "$1" != -H ] || { shift;  human=1; }
     ___x_cmd_fileage_stat "$@" | while read -r ts; do
         [ -n "$ts" ] || {
-            x log :fileage error "Get fileage failure. Please check the file exists. TS=$ts";
+            ___x_cmd log :fileage error "Get fileage failure. Please check the file exists. TS=$ts";
             local IFS=" "; x log :fileage error "filelist ==> $*"
             return 1
         }
         if [ -z "$human" ]; then
             printf "%s\n" "$((current - ts))"
         else
-            local x_="";   x humantime sec_ "$((current - ts))"
+            local x_="";   ___x_cmd humantime sec_ "$((current - ts))"
             printf "%s\n" "$x_"
         fi
     done
