Updating main branch using x7 release -> 4ef65bf5cbf7015d2e2384c66c4c1b6ff37defba

diff --git a/mod/gemini/lib/cli/_index b/mod/gemini/lib/cli/_index
--- a/mod/gemini/lib/cli/_index
+++ b/mod/gemini/lib/cli/_index
@@ -10,6 +10,8 @@ ___x_cmd_gemini_cli(){
         skill)          ___x_cmd_gemini_cli_skill           "$@" ;;
         --|--runmain)   ___x_cmd_gemini_cli___runmain       "$@" ;;
         --runcmd)       ___x_cmd_gemini_cli___runcmd        "$@" ;;
+        --unit_get_agentfile_)
+                        ___x_cmd_gemini_cli___"${op#--}"    "$@" ;;
         *)              ___x_cmd_gemini_cli___runmain "$op" "$@" ;;
     esac
 }
@@ -34,4 +36,19 @@ ___x_cmd_gemini_cli___runcmd(){
             ___x_cmd snap --run gemini "$@"
         }
     fi && ___x_cmd_gemini_cli___runcmd "$@"
+}
+
+___x_cmd_gemini_cli___unit_get_agentfile_(){
+    local dir="${1:-$PWD}"
+    local config_file="$HOME/.gemini/config.toml"
+    local filename=""
+    [ ! -f "$config_file" ] || {
+        read -r filename <<A
+$( < "$config_file" ___x_cmd jo env '.context.fileName.*' fname=. -- 'printf "%s\n" "$fname"' )
+A
+    }
+    x_=""; ___x_cmd skill --unit_find_up_ "$dir" GEMINI.md ${filename} || {
+        gemini:error "Failed to retrieve existing context files — Not found GEMINI.md"
+        return 1
+    }
 }
