...

diff --git a/mod/hub/lib/share b/mod/hub/lib/share
--- a/mod/hub/lib/share
+++ b/mod/hub/lib/share
@@ -10,24 +10,24 @@ ___x_cmd_hub_share(){
     esac
 }
 
-___x_cmd_hub_share_ls(){
-    local json
-    case "$1" in
-        --json|-j)    json=true; shift ;;
-        --help|-h)    ___x_cmd_hub___help share ls ; return 1 ;;
-    esac
+# ___x_cmd_hub_share_ls(){
+#     local json
+#     case "$1" in
+#         --json|-j)    json=true; shift ;;
+#         --help|-h)    ___x_cmd_hub___help share ls ; return 1 ;;
+#     esac
 
-    local res
-    if ! res="$(___x_cmd_hub___util_curl_v2 get /api/v0/share)" ; then
-        ___x_cmd_hub___util_handle_resp false "$res" "Failed to list shares : "
-        return 1
-    fi
+#     local res
+#     if ! res="$(___x_cmd_hub___util_curl_v2 get /api/v0/share)" ; then
+#         ___x_cmd_hub___util_handle_resp false "$res" "Failed to list shares : "
+#         return 1
+#     fi
 
-    printf "%s" "$res" | \
-        x jo 2c                .path  .isPublic .userList  .createdAt | \
-        x csv header --add     PATH   IS_PUBLIC USER_LIST  CREATE_AT  | \
-        ___x_cmd_hub___util_st_tab  -      10    100%
-}
+#     printf "%s" "$res" | \
+#         x jo 2c                .path  .isPublic .userList  .createdAt | \
+#         x csv header --add     PATH   IS_PUBLIC USER_LIST  CREATE_AT  | \
+#         ___x_cmd_hub___util_st_tab  -      10    100%
+# }
 
 ___x_cmd_hub_share_set(){
     ___x_cmd_hub_share___set "$@"
@@ -40,7 +40,7 @@ ___x_cmd_hub_share___set(){
         case "$1" in
             --public)       public=true; shift ;;
             --user)         user="$2"; shift 2 ;;
-            --help|-h)      ___x_cmd_hub___help share add >&2 ; return 1 ;;
+            --help|-h)      ___x_cmd_hub___help share set >&2 ; return 1 ;;
             *) break ;;
         esac
     done
@@ -58,12 +58,12 @@ ___x_cmd_hub_share___set(){
     fi
 
     local res; res="$(___x_cmd_hub___util_curl_v2 put /api/v0/share "res=$respath" "isPublic=${public:-false}" username="$user")" || {
-        ___x_cmd_hub___util_handle_resp false "$res" "Failed to add share:"
+        ___x_cmd_hub___util_handle_resp false "$res" "Failed to set share:"
         return 1
     }
 
     [ -z "$json" ] || { printf "%s\n" "$res" ; return 0 ; }
-    ___x_cmd_hub___util_handle_resp true "" "Success to add share for $respath"
+    ___x_cmd_hub___util_handle_resp true "" "Success to set share for $respath"
 }
 
 ___x_cmd_hub_share___handle_filekey(){
