...

diff --git a/mod/cosmo/lib/binlist b/mod/cosmo/lib/binlist
--- a/mod/cosmo/lib/binlist
+++ b/mod/cosmo/lib/binlist
@@ -5,7 +5,7 @@ ___x_cmd_cosmo___binlist_(){
         x_="$___X_CMD_COSMO_BINLIST"
         return
     }
-    x rat_ "$___X_CMD_ROOT_MOD/cosmo/lib/data/bin"
+    ___x_cmd_rat_ "$___X_CMD_ROOT_MOD/cosmo/lib/data/bin"
     x_="${___X_CMD_UNSEENCHAR_NEWLINE}${x_}${___X_CMD_UNSEENCHAR_NEWLINE}"
     ___X_CMD_COSMO_BINLIST="$x_"
 }
@@ -25,9 +25,36 @@ ___x_cmd_cosmo___ls_raw(){
 }
 
 ___x_cmd_cosmo___ls(){
-    if ___x_cmd_is_interactive; then
-        ___x_cmd_cosmo___ls_raw | x pick --col 8
-    else
+    if [ -t 1 ] && ! ___x_cmd_is_interactive; then
         ___x_cmd_cosmo___ls_raw
+    else
+        ___x_cmd_cosmo___ls_raw | x pick --col 8
     fi
+}
+
+___x_cmd_cosmo___ll(){
+    ___x_cmd_cosmo___ls_raw
+}
+
+___x_cmd_cosmo___which_(){
+    x_=
+    local bin="$1"; shift
+    [ -f "$___X_CMD_ROOT_DATA/cosmo/bin/$bin" ] || (
+        trap 'printf "\r\n"; cosmo:error "Download interrupted"; x rmrf "$___X_CMD_ROOT_DATA/cosmo/bin/$bin"; return 130;' INT
+        cosmo:debug "x curl -o $___X_CMD_ROOT_DATA/cosmo/bin/$bin https://cosmo.zip/pub/cosmos/bin/$bin"
+        x curl -o "$___X_CMD_ROOT_DATA/cosmo/bin/$bin" https://cosmo.zip/pub/cosmos/bin/"$bin" || {
+            cosmo:error "Fail to install $bin"
+            x rmrf "$___X_CMD_ROOT_DATA/cosmo/bin/$bin"
+            return 1
+        }
+        chmod +x "$___X_CMD_ROOT_DATA/cosmo/bin/$bin"
+    ) || return
+
+    x_="$___X_CMD_ROOT_DATA/cosmo/bin/$bin"
+}
+
+___x_cmd_cosmo___which(){
+    local x_
+    ___x_cmd_cosmo___which_ "$@" || return
+    printf "%s\n" "$x_"
 }
diff --git a/mod/fslock/lib/acquire b/mod/fslock/lib/acquire
--- a/mod/fslock/lib/acquire
+++ b/mod/fslock/lib/acquire
@@ -10,34 +10,144 @@ ___x_cmd_fslock_acquire(){
     local fslock_name="$1"
 
     local x_=;  ___x_cmd_pidofsubshell_
+    local SPID="$x_"
 
     x mkdirp "$___X_CMD_FSLOCK_ROOT"
     local fslock_fp="${___X_CMD_FSLOCK_ROOT}/${fslock_name}.fslock.x-cmd.X"
-    local fslock_fp_pid="${___X_CMD_FSLOCK_ROOT}/${fslock_name}.fslock.x-cmd.$x_"
+    local fslock_fp_pid="${___X_CMD_FSLOCK_ROOT}/${fslock_name}.fslock.x-cmd.$SPID"
 
-    fslock:info "acquire [fslock=$fslock_name] in [process=$x_]"
+    fslock:debug "[SPID=$SPID] Try to acquire [fslock=$fslock_name]"
 
-    {
-        printf "%s\n" "$x_"
-        x ps fingerprint get "$x_"
-        printf "%s\n" "$fslock_name"
-    } >"${fslock_fp_pid}" 2>/dev/null || {
-        [ ! -f "$fslock_fp_pid" ] || ___x_cmd_cmds_rm "${fslock_fp_pid}"
+    local content
+    content="$SPID
+$(x ps fingerprint get "$SPID")
+$fslock_name"
+
+    printf "%s\n" "$content" >"${fslock_fp_pid}" || {
+        fslock:warn "[SPID=$SPID] Fail to write $fslock_fp_pid"
+        [ ! -f "$fslock_fp_pid" ] || ___x_cmd_cmds_rm "${fslock_fp_pid}" 2>/dev/null
+        # Notice: We DONOT need to remove with best effort because it is NOT soft ln to X lock file.
         return 1
     }
 
-    ___x_cmd_cmds sync
-
-    ___x_cmd_cmds_ln -s "${fslock_fp_pid}" "${fslock_fp}" 2>/dev/null || {
-        [ ! -f "$fslock_fp_pid" ] || ___x_cmd_cmds_rm "${fslock_fp_pid}"
+    # ___x_cmd_cmds sync        # This MUST be disabled because it will affect the next sync. The file IO workload is an issue and be observed in WSL2.
+    ___x_cmd_fslock_acquire___link || {
+        ___x_cmd_fslock_acquire___besteffortrm "link competition failure";
         return 1
     }
 
     local pidline="";
-    read -r pidline <"$fslock_fp"
-    [ "$pidline" = "$x_" ] || {
-        fslock:warn --spid "$x_" "This should be bug in MSYS. fslock[$fslock_name] is acquired by other process[$pidline]"
-        [ ! -f "$fslock_fp_pid" ] || ___x_cmd_cmds_rm "${fslock_fp_pid}"
+    ___x_cmd_fslock_acquire___readpid_ "$fslock_fp" || {
+        fslock:warn "[SPID=$SPID] fslock[$fslock_name] [file=$fslock_fp] is NOT sync to disk. This is very RARE case and resulting a recovery process."
+        ___x_cmd_fslock_acquire___besteffortrm "verify by reading the lock content";
         return 1
     }
+
+    pidline="$x_"
+
+    [ -n "$pidline" ] || {
+        fslock:error "[SPID=$SPID] [SHOULD NEVER HAPPEN] fslock[$fslock_name] file has NO content."
+        ___x_cmd_fslock_acquire___besteffortrm "content empty";
+        return 1
+    }
+
+    [ "$pidline" = "$SPID" ] || {
+        fslock:warn "[SPID=$SPID] This should be bug of ln in MSYS. fslock[$fslock_name] is actually acquired by other process[$pidline]"
+        ___x_cmd_fslock_acquire___besteffortrm ;     return 1
+    }
+
+    fslock:info "[SPID=$SPID] Lock acquired [fslock=$fslock_name]"
+
+    ___x_cmd_fslock_cleanup___reserve_x_and_pid "$fslock_name" "$SPID"
+}
+
+___x_cmd_fslock_acquire___link(){
+    if ___x_cmd_cmds_ln -s "${fslock_fp_pid}" "${fslock_fp}" 2>/dev/null; then
+        return 0
+    fi
+
+    if [ -z "$___X_CMD_FSLOCK_ACQUIRE_TRY_RELEASE" ]; then
+        [ -f "$fslock_fp_pid" ] || \
+            fslock:debug "[SPID=$SPID] After link failed. BUG in ZSH. fslock[$fslock_name] file NOT sync to disk."
+        return 1
+    fi
+
+    # We bet that ${fslock_fp}.X can always be deleted successfully...
+    (
+        trap '___x_cmd_cmds_rm -rf "${fslock_fp}.X";' EXIT
+        ___x_cmd_cmds_ln -s "${fslock_fp_pid}" "${fslock_fp}.X" 2>/dev/null || return 1
+
+        if [ ! -e "$fslock_fp" ]; then
+            ___x_cmd_cmds_rm -rf "$fslock_fp"
+            return 0
+        fi
+        {
+            read -r pidline
+            read -r fingerprint
+        } <"$fslock_fp"
+        if [ -z "$pidline" ]; then
+            ___x_cmd_cmds_rm -rf "$fslock_fp"
+            return 0
+        fi
+        if ! ___x_cmd_ps_fingerprint_check "$pidline" "$fingerprint"; then
+            ___x_cmd_cmds_rm -rf "$fslock_fp"        # ___x_cmd_fslock_available___clear "$fslock_name"
+            return 0
+        fi
+    ) || return 1
+
+    # try again
+    ___x_cmd_cmds_ln -s "${fslock_fp_pid}" "${fslock_fp}" 2>/dev/null
+}
+
+___x_cmd_fslock_acquire___readpid2_(){
+    local fp="$1"
+    # ___x_cmd_cmds sync -f "${fp}" # Out of concern of performance, we donot sync here. We will sync only when reading empty file.
+    x_=""
+    {
+        # read -r x_ <"$fp"
+        read -r x_ <<A
+$(___x_cmd_cmds_cat "$fp")
+A
+    } 2>/dev/null
+    # fslock:info "primitive reading from [fp=$fp] [data=$x_]"
+}
+
+___x_cmd_fslock_acquire___readpid_(){
+    local fp="$1"
+    x_=""
+
+    {
+        read -r x_ <"$fp"
+    } 2>/dev/null
+    fslock:debug "primitive reading from [fp=$fp] [data=$x_]"
+    [ -z "$x_" ] || return 0
+
+    ___x_cmd_cmds sync -f "$fp" 2>/dev/null
+
+    local count=1
+    while [ "$count" -lt 5 ]; do
+        count=$((count + 1))
+        fslock:info "[SPID=$SPID] try [count=$count]"
+
+        read -r x_ <<A
+$(___x_cmd_cmds cat "$fp" 2>/dev/null)
+A
+
+        [ -z "$x_" ] || return 0
+        ___x_cmd_cmds sleep 0.$count || return 130
+    done
+
+    return 1
+}
+
+___x_cmd_fslock_acquire___besteffortrm(){
+    fslock:debug "[SPID=$SPID] FAIL AT $1"
+    [ -f "$fslock_fp_pid" ] || \
+        fslock:warn "[SPID=$SPID] besteffortrm BUG in ZSH. fslock[$fslock_name] file NOT sync to disk."
+
+    fslock:debug "[SPID=$SPID] Best effort to remove [fp=$fslock_fp_pid]"
+
+    # printf "\n\n" >"${fslock_fp_pid}"       # clear the file to 1000% make sure the lock is not required by this process
+    # ___x_cmd_cmds sync "${fslock_fp_pid}"
+    ___x_cmd_cmds_rm "${fslock_fp_pid}" 2>/dev/null     # The empty file strategy make this rm actually redundant.
 }
diff --git a/mod/open/lib/linux b/mod/open/lib/linux
--- a/mod/open/lib/linux
+++ b/mod/open/lib/linux
@@ -8,13 +8,13 @@
 # open a.json --> Using
 
 ___x_cmd_open___main(){
-    for i in "$@"; do
-        case "$i" in
-            -f|-i|-n|-v)    continue ;;
-            -*)             continue ;;
-            # /|/bin)        printf "Abort because trying to remove key file." >&2 || return 1 ;;
-        esac
-    done
+    # for i in "$@"; do
+    #     case "$i" in
+    #         -f|-i|-n|-v)    continue ;;
+    #         -*)             continue ;;
+    #         # /|/bin)        printf "Abort because trying to remove key file." >&2 || return 1 ;;
+    #     esac
+    # done
 
     local p="${1:-$HOME}"
 
@@ -23,6 +23,39 @@ ___x_cmd_open___main(){
         [ "$HOME" = "$___X_CMD_BOX_INNER_HOME" ]    ||  \
         [ "${p#"${___X_CMD_BOX_INNER_HOME}"}" = "$p" ] || p="${HOME}${p#"$___X_CMD_BOX_INNER_HOME"}"
     }
-
-    command xdg-open "$@"
+    local wsl=
+    read -r wsl </proc/version
+    case "$wsl" in
+        *WSL2*)  ___x_cmd_open_linux_wsl "$p"
+            ;;
+        *)      ___x_cmd_cmds xdg-open "$p"  # command not found on wsl
+            ;;
+    esac
 }
+
+___x_cmd_open_linux_wsl(){
+    if [ -d "$1" ]; then
+        (
+            ___x_cmd_cmds cd "$1"    # explorer.exe has a problem, absolute paths only navigate to the Documents directory (this happens with both Unix and Windows paths)
+            ___x_cmd_cmds explorer.exe .
+        )
+    elif [ -f "$1" ]; then
+        local p="${1%/*}"
+        if [ "$1" = "$p" ]; then
+            (
+                ___x_cmd_cmds explorer.exe "$1"
+            )
+        else
+            local file="${1##*/}"
+            (
+                ___x_cmd_cmds cd "$p"
+                ___x_cmd_cmds explorer.exe "$file"
+            )
+        fi
+    else
+        x browse "$1"
+    fi
+}
+
+
+
diff --git a/mod/theme/lib/util b/mod/theme/lib/util
--- a/mod/theme/lib/util
+++ b/mod/theme/lib/util
@@ -22,9 +22,12 @@ ___x_cmd_theme_control_font() {
         local cache="${___X_CMD_THEME_PKG_PATH}/nerdfont.tgz"
         ___x_cmd_theme___pkg_unzip font "font/nerdfont.tgz" "$cache" "$_font_dir" || return
 
-        if command -v fc-cache >/dev/null 2>&1; then
+        if x hascmd fc-cache; then
             theme:info "Resetting font cache, this may take a moment..."
             command fc-cache -f "$_font_dir"
+        else
+            theme:warn "The fc-cache command not found, the font is in the [directory=$_font_dir]"
+            return 0
         fi
     fi
 }
@@ -102,7 +105,7 @@ ___x_cmd_theme___pkg_unzip_unit(){
 
     { [ -z "$isupdate" ] && [ -f "$cache" ] ; } || ___x_cmd_theme___pkg_download "$suburl" "$cache" || return
     x rmrf "$extract_path"
-    x uz "$cache" "$extract_path" || {
+    ___X_CMD_ZUZ_QUIET=1 x uz "$cache" "$extract_path" || {
         theme:error "Fail to extract $cache"
         x rmrf "$cache" "$extract_path"
         return 1
diff --git a/mod/x-cmd/lib/main b/mod/x-cmd/lib/main
--- a/mod/x-cmd/lib/main
+++ b/mod/x-cmd/lib/main
@@ -1,7 +1,7 @@
 # shellcheck    shell=dash
 
-xrc:mod cama/latest     # Preload module
-xrc:mod:lib     x-cmd           eclist ldev pwd meta concurrent cond whichbin util engine/index hashsum while_read ymljson while_read vareq bgsingleton fskv
+xrc:mod cama/latest cosmo/latest    # Preload module
+xrc:mod:lib     x-cmd           eclist ldev pwd meta concurrent cond whichbin util engine/index hashsum while_read ymljson while_read vareq bgsingleton fskv shengine/_index
 xrc alias
 
 ___X_CMD_ENGINE_SUBCMD_NAME=__enginerun
@@ -38,16 +38,24 @@ ___x_cmd_main_otherwise(){
         ___x_cmd_main_otherwise_code=$?
         x:debug "Resource Executed: [type=$___X_CMD_WHICH_ONE_RESOURCE_TYPE] [file=$___X_CMD_WHICH_ONE_RESULT] [code=$___x_cmd_main_otherwise_code]"
         return "$___x_cmd_main_otherwise_code"
-    else
-        # TODO: If we fail to introduct from xbin. Please provide the interface, ask user for what he/she wants and whether set the alias for that module globally.
-        ___x_cmd_main_otherwise_code=$?
-        if x pkg xbin init "$subcmd"; then
-            "___x_cmd_${___X_CMD_STR___DASH2UNDERLINE}" "$@"
-        else
-            x:error "___x_cmd_main_otherwise(): ___x_cmd_which_one fail [code: ${___x_cmd_main_otherwise_code}]"
-            return 1
-        fi
     fi
+
+    # TODO: If we fail to introduct from xbin. Please provide the interface, ask user for what he/she wants and whether set the alias for that module globally.
+    ___x_cmd_main_otherwise_code=$?
+    if x pkg xbin init "$subcmd"; then
+        "___x_cmd_${___X_CMD_STR___DASH2UNDERLINE}" "$@"
+        return
+    fi
+
+    # Only llama file, or other file
+    if ___x_cmd_cosmo___hasbin "$subcmd"; then
+        x:warn "Using cosmo equivalent ==> $subcmd"
+        ___x_cmd_cosmo___run "$subcmd" "$@"
+        return
+    fi
+
+    x:error "___x_cmd_main_otherwise(): ___x_cmd_which_one fail [code: ${___x_cmd_main_otherwise_code}]"
+    return 1
 }
 
 ___x_cmd_alias_init ___x_cmd
@@ -77,7 +85,7 @@ ___x_cmd_main(){        # x:trace x     # TODO: will effect x log
         py)                                     shift;  xrc python ; ___x_cmd_python "$@"    ;;
         python=*|py=*)                          shift;  xrc python ; ___X_CMD_PKG_XBIN_DEFAULT_python="${subcmd#*=}" ___x_cmd_python "$@"    ;;
 
-        sh|bash|zsh|ksh|dash|ash)               shift;  ___x_cmd_shell_exec "$subcmd" "$@" ;;
+        sh|bash|zsh|ksh|dash|ash)               shift;  ___x_cmd_shellengine "$subcmd" "$@" ;;
         run)                                    shift;  ___x_cmd_engine_run "$@"       ;;
 
         login)                                  shift;  xrc hub/latest && ___x_cmd_hub login "$@" ;;
