Updating main branch using x7 release -> 1f190983f3a2e78cc918c6ccaea60b6d16c7eca6

diff --git a/mod/version/lib/ls b/mod/version/lib/ls
--- a/mod/version/lib/ls
+++ b/mod/version/lib/ls
@@ -30,17 +30,34 @@ ___x_cmd_version_ls_yml(){
 }
 
 ___x_cmd_version___get_info_file_(){
-    x_="$___X_CMD_PKG_ROOT_PATH/metadata/$___X_CMD_PKG_VERSION/release/version.index.jso"
-    if [ ! -f "$x_" ]; then
-        ___x_cmd pkg update || return $?
-    else
-        case "$___X_CMD_VERSION0" in
-            latest|beta|alpha|v*)
-                [ "$x_" -nt "${___X_CMD_ROOT_METADATA}/version_sum" ] || {
-                    x:debug -c "x pkg update" "The version information file may be outdated, please try updating the PKG resource package."
-                }
-            ;;
-        esac
-    fi
-    [ -f "$x_" ] || N=x M="Not found version information file" log:ret:1
+    local version_index_jso_file="$___X_CMD_ROOT_DATA/version/index.jso"
+    local version_index_yml_file="$___X_CMD_ROOT_DATA/version/index.yml"
+
+    [ -f "$version_index_jso_file" ] || {
+        local url=
+        if ! ___x_cmd websrc is cn; then
+            url="https://raw.githubusercontent.com/x-cmd/release/main"
+        else
+            url="https://oss.resource.x-cmd.com/x-cmd/release"
+        fi
+        url="$url/index.yml"
+        x:info "Download version index from $url"
+        ___x_cmd ensurefp "$version_index_yml_file"
+        ___x_cmd curl -L "$url" --output "$version_index_yml_file"  || {
+            ___x_cmd rmrf "$version_index_yml_file"
+            x:error "Fail to download from $url"
+            return 1
+        }
+
+        < "$version_index_yml_file" ___x_cmd y2j | ___x_cmd jo > "$version_index_jso_file"
+        [ "$( < "$version_index_jso_file" command wc -l)" -gt 1000 ] || {
+            x:error "version index file data amiss"
+            return 1
+        }
+    }
+    x_="$version_index_jso_file"
+    [ -f "$x_" ] || {
+        x:error "Not found version index file"
+        return 1
+    }
 }
