...

diff --git a/mod/apt/lib/main b/mod/apt/lib/main
--- a/mod/apt/lib/main
+++ b/mod/apt/lib/main
@@ -6,6 +6,11 @@ xrc:mod:lib apt     __xmirror __xproxy __repo install nv
 ___x_cmd_apt___main(){
     [ "$#" -gt 0 ] ||       set -- nv
 
+    x hascmd apt   ||  {
+        apt:warn "apt is not found."
+        return 1
+    }
+
     local op="$1";          shift
     case "$op" in
         nv)                 ___x_cmd_apt___nv               "$@" ;;
@@ -19,8 +24,8 @@ ___x_cmd_apt___main(){
         |edit-sources|satisfy)
                             ___x_cmd_apt___exec     "$op"   "$@" ;;
 
-        -h|--help)          x help -m apt "$@"; return                             ;;
-        *)                  N=apt M="Not found command - 'x apt $op'" log:ret:64   ;;
+        -h|--help)          x help -m apt "$@"; return           ;;
+        *)                  ___x_cmd_cmds apt       "$op"   "$@" ;;
     esac
 }
 
@@ -54,4 +59,13 @@ ___x_cmd_apt___exec(){
     apt:info "running command  →  x sudo apt $*"
 
     x sudo apt "$@"
+}
+
+___x_cmd_apt___lsraw(){
+    # TODO: Remove ccmd
+    local aptfp=; aptfp="$(x ccmd which ___x_cmd_apt___repo_lsname)"
+    [ "$aptfp" -nt "/var/lib/apt/lists/partial" ] || {
+        x rmrf "$aptfp"
+    }
+    x ccmd 3d -- ___x_cmd_apt___repo_lsname
 }
diff --git a/mod/dnf/lib/main b/mod/dnf/lib/main
--- a/mod/dnf/lib/main
+++ b/mod/dnf/lib/main
@@ -1,61 +1,36 @@
 # shellcheck shell=dash disable=SC2034,SC2016
+xrc proxy
 x log init dnf
+xrc:mod:lib dnf     __xmirror __xproxy __repo install nv
 
 ___x_cmd_dnf___main(){
     [ "$#" -gt 0 ] ||   set -- nv
 
-    local op="$1"; shift
-    case "$op" in
-        install)        ___x_cmd_dnf___install  "$@" ;;
-        nv)             ___x_cmd_dnf___nv       "$@" ;;
-        --help|-h)      x help -m dnf;        return ;;
-        *)              ___x_cmd_cmds dnf "$op" "$@" ;;
-    esac
-}
-
-___x_cmd_dnf___nv(){
-    local X_help_cmd='x help -m dnf nv'
-    help:arg:parse
-
-    { [ -t 1 ] && ___x_cmd_is_interactive; } \
-        || {
-            x ccmd 1d -- ___x_cmd_dnf___lsraw
-            return 0
-        }
-
-    local software
-    software="$(x ccmd 1d -- ___x_cmd_dnf___lsraw | x pick --width 40 --col 10)"
-    [ -n "$software" ] || {
-        dnf:info "Exit because no software is selected."
-        return 0
+    x hascmd dnf   ||  {
+        dnf:warn "dnf command not found."
+        return 1
     }
 
-    local id
-    x ui select id "What to do NEXT"                        \
-        "x dnf install $software"                           \
-        "EXIT"     || return
+    local op="$1"; shift
+    case "$op" in
+        nv)                 ___x_cmd_dnf___nv       "$@" ;;
+        install)            ___x_cmd_dnf___install  "$@" ;;
+        proxy|--xproxy)     ___x_cmd_dnf___xproxy   "$@" ;;
+        mirror|--xmirror)   ___x_cmd_dnf___xmirror  "$@" ;;
 
-    case "$id" in
-        1)      x dnf install "$software" ;;
-        2)      return 0 ;;
+        autoremove|shell     \
+        |distro-sync|remove  \
+        |reinstall|update    \
+        |upgrade|downgrade   \
+        |upgrade-minimal)
+                            ___x_cmd_dnf___exec     "$op"   "$@" ;;
+
+        --help|-h)          x help -m dnf;          return       ;;
+        *)                  ___x_cmd_cmds dnf       "$op"   "$@" ;;
     esac
 }
 
-___x_cmd_dnf___lsraw(){
-    ___x_cmd_cmds dnf list | ___x_cmd_cmds awk 'NR>2{
-        print $1
-    }'
-}
-
-___x_cmd_dnf___install(){
-    local X_help_cmd='x help -m dnf nv'
-    help:arg:parse
-
-    if [ $# -eq 0 ]; then
-        ___x_cmd_dnf___nv
-        return 0
-    fi
-
-    # Using x sudo
-    x sudo dnf install "$@"
+___x_cmd_dnf___exec(){
+    dnf:info "running command  →  x sudo dnf $*"
+    ___x_cmd_dnf___xproxy run x sudo dnf "$@"
 }
diff --git a/mod/pkg/lib/info/ls b/mod/pkg/lib/info/ls
--- a/mod/pkg/lib/info/ls
+++ b/mod/pkg/lib/info/ls
@@ -86,8 +86,8 @@ ___x_cmd_pkg_ls_all(){
 
     # TODO: avoid to use find and subshell
     local json_path
-    if ! json_path="$(find "$___X_CMD_PKG_METADATA_PATH"/*/"$pkg_name/version.tt.json")"; then
-        pkg:error "Can not find $pkg_name 's version.tt.json"
+    if ! json_path="$(___x_cmd_cmds find "$___X_CMD_PKG_METADATA_PATH"/*/"$pkg_name/version.tt.json")" 2>/dev/null; then
+        pkg:error "Not found version.tt.json of [pkg=$pkg_name]"
         return 1
     fi
     ___x_cmd_pkg_ls___all_version "$json_path" "$osarch"
@@ -103,6 +103,8 @@ ___x_cmd_pkg_ls___all_version(){
 
 ___x_cmd_pkg_ls___all_candidate()(
     # TODO: Need to be removed in the future
+    local op="$1"
+    local suffix="$2"
     ___x_cmd_pkg_update___check || return
 
     ___x_cmd_cmds_cd "$___X_CMD_PKG_METADATA_PATH" 2>/dev/null || {
@@ -110,15 +112,14 @@ ___x_cmd_pkg_ls___all_candidate()(
         return 1
     }
     for dir in *; do
-        case "$dir" in
-            binmod*)   continue ;;
-        esac
-        ___x_cmd_cmds_cd "$___X_CMD_PKG_METADATA_PATH/$dir" 2>/dev/null || continue
+        dir="$___X_CMD_PKG_METADATA_PATH/$dir"
+        [ -d "$dir" ] || continue
+        ___x_cmd_cmds_cd "$dir" 2>/dev/null || continue
         for candidate in *; do
             case "$candidate" in
-                bash-preexec) continue ;;
+                bash-preexec)   continue ;;
+                "$op"*)        printf "%s\n" "${candidate}${suffix}" ;;
             esac
-            printf "%s\n" $candidate
         done
     done 2>/dev/null
 )
