...

diff --git a/mod/ollama/lib/util b/mod/ollama/lib/util
--- a/mod/ollama/lib/util
+++ b/mod/ollama/lib/util
@@ -14,8 +14,13 @@ A
 }
 
 ___x_cmd_ollama_is_installed(){
-    if ! x hasbin ollama; then
-        ___x_cmd_ui_yesno "You have to install an ollama firstly, Do you want to download ?" || return
-        x install ollama
+    if ! ___x_cmd hasbin ollama; then
+        if ___x_cmd_is_interactive; then
+            ___x_cmd ui yesno "You need to install ollama first. Do you want to download it?" || return
+            ___x_cmd install ollama
+        else
+            ollama:warn "Ollama not found. Use \`x install ollama\` to download."
+            return 1
+        fi
     fi
 }
