...

diff --git a/mod/api/lib/provider/ali b/mod/api/lib/provider/ali
--- a/mod/api/lib/provider/ali
+++ b/mod/api/lib/provider/ali
@@ -1,15 +1,16 @@
 # shellcheck shell=sh
-# shellcheck disable=SC3043,2034
+# shellcheck disable=SC3043,2034,2294,2154
 ___x_cmd_api_ali(){
     local ali_header="${___x_api_ali_header:-"${___X_CMD_API_TMP}/.____x_cmd_ali_curl_header"}"
-    local op="$1"; shift
+    local op="${1}"
+    local method
+    method="$( printf "%s" "${2}" | tr '[:lower:]' '[:upper:]')"
+    shift 2
     case "${op}" in
-        oss)
-            ___x_cmd_api_ali_oss "$@"
-            ;;
-        ecs|mongodb|vpc)
-            ___x_cmd_api_ali_ecs "${op}" "$@"
-            ;;
+        oss)    ___x_cmd_api_ali_oss    "${method}" "$@";;
+        lambda) ___x_cmd_api_ali_lambda "${method}" "$@";;
+        ecs|mongodb|vpc|alidns|actiontrail|redis|resourcecenter)
+            ___x_cmd_api_ali_ecs "${op}" "${method}" "$@";;
         *)
             _____x_cmd_api_help ali
             return 1
@@ -17,94 +18,119 @@ ___x_cmd_api_ali(){
     esac
 }
 
-___x_cmd_api_ali_oss(){
-    local op="$1"; shift
-    case "${op}" in
-        get)
-            ___x_cmd_api_ali_oss_req GET "$@"
-        ;;
-        post)
-            ___x_cmd_api_ali_oss_req POST "$@"
-        ;;
-        put)
-            ___x_cmd_api_ali_oss_req PUT "$@"
-        ;;
-        del)
-            ___x_cmd_api_ali_oss_req DELETE "$@"
-        ;;
-        head)
-            ___x_cmd_api_ali_oss_req HEAD "$@"
-        ;;
-        ""|-h|--help)
-            _____x_cmd_api_help ali
-            return 1
-            ;;
-    esac
-}
-
-___x_cmd_api_ali_oss_req(){
-    local url
-    local param
-    local method="$1"; shift
-    ___x_cmd_ali_oss_url_gen "${method}" "$@"  || {
-        api:error "ali oss ${method} sing fail"
-        return 1
-    }
-    api:debug   "x curl -D  ${ali_header}  -X  ${method}  -s  $url   ${param}"
-    eval         x curl -D "${ali_header}" -X "${method}" -s "$url" "${param}"
-}
-
+# Section ecs req
 ___x_cmd_api_ali_ecs(){
     local version
     local host
-    case "${1}" in
-        ecs)
-            version="2014-05-26"
-            host="${___x_api_ali_host:-"https://ecs.aliyuncs.com"}"
-        ;;
-        mongodb)
-            version="2015-12-01"
-            host="${___x_api_ali_host:-"https://mongodb.aliyuncs.com"}"
-        ;;
-        vpc)
-            version="2016-04-28"
-            host="${___x_api_ali_host:-"https://vpc.aliyuncs.com"}"
-        ;;
-    esac
+    local method="${2}"
 
-    local op="$2"
-    shift 2
+    local url=
+    local _x_post_param=
+    ___x_cmd_api_ali_ecs_util_ "$@" || return 1
+    ___x_cmd_api_ali_ecs_req "${method}"
+}
+
+___x_cmd_api_ali_ecs_util_(){
+    local op="${1}"; shift
     case "${op}" in
-        get)
-            ___x_cmd_api_ali_ecs_req GET "$@"
-        ;;
-        post)
-            ___x_cmd_api_ali_ecs_req POST "$@"
-        ;;
-        ""|-h|--help)
+        ecs) version="2014-05-26" ;;
+        mongodb) version="2015-12-01" ;;
+        vpc) version="2016-04-28" ;;
+        alidns) version="2015-01-09" ;;
+        resourcecenter) version="2022-12-01" ;;
+        actiontrail)
+            version="2020-07-06"
+            op="actiontrail.${RegionId}"
+            ;;
+        redis)
+            version="2015-01-01"
+            op="r-kvstore"
+            ;;
+        *)
             _____x_cmd_api_help ali
             return 1
             ;;
     esac
+    host="${___x_api_ali_host:-"https://${op}.aliyuncs.com"}"
+
+    ____x_cmd_sign_ali ecs "$@" || {
+        api:error "ali ${op} ${method} sing fail"
+        return 1
+    }
 }
 
 ___x_cmd_api_ali_ecs_req(){
-    local url
-    local param
     local method="$1"; shift
-    ___x_cmd_ali_ecs_url_gen "${method}" "$@"  || {
-        api:error "ali oss ${method} sing fail"
-        return 1
-    }
-
     case "${method}" in
         POST)
-            api:debug  "x curl -D  ${ali_header}  -X POST -s -H  Content-Type:application/x-www-form-urlencoded   $param       $url "
-            eval        x curl -D "${ali_header}" -X POST -s -H "Content-Type:application/x-www-form-urlencoded" "${param}" "\"$url\""
+            api:debug  "x curl -D  ${ali_header}  -X POST -s -H  Content-Type:application/x-www-form-urlencoded   $_x_post_param       $_x_url "
+            eval        x curl -D "${ali_header}" -X POST -s -H "Content-Type:application/x-www-form-urlencoded" "${_x_post_param}" "\"$_x_url\""
         ;;
         GET)
-            api:debug   "x curl -D  ${ali_header}  -X GET -s  $url"
-                         x curl -D "${ali_header}" -X GET -s "$url"
+            api:debug   "x curl -D  ${ali_header}  -X GET -s  $_x_url"
+                         x curl -D "${ali_header}" -X GET -s "$_x_url"
         ;;
     esac
 }
+# EndSection
+
+# Section oss req
+___x_cmd_api_ali_oss(){
+    local url
+    local _x_post_param
+    local method="$1"
+    local resource="$2"
+    local host="${host:-"${bucket:+"${bucket}."}oss-${region_id:-"cn-hangzhou"}.aliyuncs.com"}"
+    shift 2
+    ____x_cmd_sign_ali oss "${method}" "${resource}" "$@"  || {
+        api:error "ali oss ${method} sing fail"
+        return 1
+    }
+    case "${method}" in
+        POST|PUT)
+            api:debug   \'x curl -D  "${ali_header}"  -X  "${method}"  -s   ${gen_ali_data:+"-d"}   ${gen_ali_data:+"\'${gen_ali_data}\'"}   "${_x_url}"\'
+            eval          x curl -D  "${ali_header}"  -X  "${method}"  -s  "${gen_ali_data:+"-d"}" "${gen_ali_data:+"\'${gen_ali_data}\'"}"  "${_x_url}"
+        ;;
+        GET|DELETE)
+            api:debug   \'x curl -D  "${ali_header}"  -X  "${method}"  -s -G "${gen_ali_json}"  "${_x_url}"\'
+            eval          x curl -D  "${ali_header}"  -X  "${method}"  -s -G "${gen_ali_json}"  "${_x_url}"
+        ;;
+        HEAD)
+            api:debug   \'x curl -D  "${ali_header}" --head -s -G "${gen_ali_json}"  "${_x_url}"\'
+            eval          x curl -D  "${ali_header}" --head -s -G "${gen_ali_json}"  "${_x_url}"
+        ;;
+    esac
+}
+# EndSection
+
+# Section lambda req
+___x_cmd_api_ali_lambda(){
+    local url
+    local _x_post_param
+    local account_id
+    local method="$1"; shift
+    local version="2021-04-06"
+    account_id="$(x ali --cfg get account_id 2>/dev/null)"
+    [ -n "${account_id}" ] || {
+        ali:error "Get account_id failed, please use 'x ali --cfg set --account_id <account_id>' to set up the configuration."
+        return 1
+    }
+    local host="${___x_api_ali_host:-"${account_id}.${RegionId}.fc.aliyuncs.com"}"
+    ____x_cmd_sign_ali lambda "${method}" "$@"  || {
+        api:error "ali lambda ${method} sing fail"
+        return 1
+    }
+
+    local _curl_header="$(x curl gencode "${lambda_headers}" Content-Type:application/json)"
+    case "${method}" in
+        POST|PUT)
+            api:debug  "x curl -D  ${ali_header}  -X  ${method}   ${_curl_header}   ${gen_ali_json:+"-d"}   ${gen_ali_json:+"\'${gen_ali_json}\'"}   $_x_url"
+            eval        x curl -D "${ali_header}" -X "${method}" "${_curl_header}" "${gen_ali_json:+"-d"}" "${gen_ali_json:+"\'${gen_ali_json}\'"}" "$_x_url"
+        ;;
+        GET|DELETE)
+            api:debug   "x curl -D  ${ali_header}  -X  ${method}  -s  $_x_url"
+            eval         x curl -D "${ali_header}" -X "${method}" -s "$_x_url"
+        ;;
+    esac
+}
+# EndSection
diff --git a/mod/bwh/lib/info b/mod/bwh/lib/info
--- a/mod/bwh/lib/info
+++ b/mod/bwh/lib/info
@@ -1,22 +1,20 @@
 # shellcheck    shell=dash
 ___x_cmd_bwh_info(){
-    [ "$#" -gt 0 ] || {
-        ___x_cmd_bwh_api getLiveServiceInfo
-        return 0
-    }
+    [ "$#" -gt 0 ] ||   set --  brief
 
     local op="$1"; shift
+    local ___X_CMD_BWH_API_CACHE=${___X_CMD_BWH_API_CACHE:-10s}
     case "$op" in
+        live)                       ___X_CMD_BWH_API_CACHE="" ___x_cmd_bwh_info___runapi "$op" "$1" getLiveServiceInfo     ;;
+
         get)                        ___x_cmd_bwh_info___runapi "$op" "$1" getServiceInfo         ;;
-        live)                       ___x_cmd_bwh_info___runapi "$op" "$1" getLiveServiceInfo     ;;
-        availableos)                ___x_cmd_bwh_info___runapi "$op" "$1" getAvailableOS         ;;
-        usagegraphs)                ___x_cmd_bwh_info___runapi "$op" "$1" getUsageGraphs         ;;
+        availableos)                ___x_cmd_bwh_info_availableos ;;
         auditlog)                   ___x_cmd_bwh_info___runapi "$op" "$1" getAuditLog            ;;
         ratelimit)                  ___x_cmd_bwh_info___runapi "$op" "$1" getRateLimitStatus     ;;
         rawusagestats)              ___x_cmd_bwh_info___runapi "$op" "$1" getRawUsageStats       ;;
         suspensiondetails)          ___x_cmd_bwh_info___runapi "$op" "$1" getSuspensionDetails   ;;
 
-        data)                       ___x_cmd_bwh_info___"$op" ;;
+        brief)                      ___x_cmd_bwh_info___"$op" ;;
 
         -h|--help)                  ___x_cmd_bwh_help info; return 1 ;;
         *)                          N=bwh M="Unknown subcmd ==> $op" log:ret:64
@@ -25,15 +23,82 @@ ___x_cmd_bwh_info(){
 
 ___x_cmd_bwh_info___runapi(){
     case "$2" in
-        --help|-h)  ___x_cmd_bwh_help info "$1" ;;
-        *)         ___x_cmd_bwh_api "$3"        ;;
+        --help|-h)
+            ___x_cmd_bwh_help info "$1";
+            return ;;
     esac
+
+    ccmd:init
+    ___x_cmd_bwh_api "$3" | {
+        tee /dev/stdout /dev/stderr | {
+            x jo env . .error
+            if [ "$error" != 0 ]; then
+                ccmd:invalidate
+                return 1
+            fi
+        }
+    } 2>/dev/stdout
 }
 
-___x_cmd_bwh_info___data(){
-    ___x_cmd_bwh_info___runapi live "" getLiveServiceInfo | {
-        x jo env . .data_counter .plan_monthly_data .data_next_reset
-        printf "usage: %s = %s / %s\n" "$(( data_counter * 100 / plan_monthly_data ))%" "$data_counter" "$plan_monthly_data"
-        printf "next-reset: %s" "$(x date ts "$data_next_reset")"
+___x_cmd_bwh_info___brief(){
+    {
+        ___X_CMD_BWH_API_CACHE=${___X_CMD_BWH_API_CACHE:-60s} ___x_cmd_bwh_info live
+    } | {
+
+        x jo env . \
+            .error  .message \
+            .data_counter   .plan_monthly_data      .data_next_reset        \
+            .ssh_port       .ve_used_disk_space_b   .ve_disk_quota_gb       \
+            .load_average   .swap_total_kb          .swap_available_kb      \
+            ip=.ip_addresses.1  \
+            .live_hostname
+
+        case "$error" in
+            ""|0)
+                ;;
+            *)
+                bwh:error --error "$error" --msg "$message" "Fail."
+                return 1
+        esac
+
+        [ -n "$data_counter" ] || return 1
+
+        printf "ip:      \t%s\n"                "$ip"
+        printf "hostname:\t%s\n"                "$live_hostname"
+        printf "load:     \t%5s\n"              "$load_average"
+        printf "swap(MB):\t%-5s =\t%s / %s\n"             \
+            "$(( swap_available_kb * 100 / swap_total_kb ))%" \
+            "$((swap_available_kb/1024))" "$((swap_total_kb / 1024))"
+
+        printf "disk(MB):\t%-5s =\t%s / %s\n"   \
+            "$(( ve_used_disk_space_b * 100 / ve_disk_quota_gb / 1024 / 1024 / 1024))%" \
+            "$((ve_used_disk_space_b/1024/1024))" "$((ve_disk_quota_gb * 1024))"
+
+        printf "usage(GB):\t%-5s = %s / %s\n" \
+            "$(( data_counter * 100 / plan_monthly_data ))%" \
+            "$((data_counter / 1024 / 1024 / 1024))" "$((plan_monthly_data / 1024 / 1024 / 1024))"
+        printf "next-reset:\t%s\n" "$(x date ts "$data_next_reset")"
+    }
+}
+
+___x_cmd_bwh_info_availableos(){
+    [ -t 1 ] || {
+        ___X_CMD_BWH_API_CACHE=${___X_CMD_BWH_API_CACHE:-24h} ___x_cmd_bwh_info___runapi availableos "" getAvailableOS
+        return
+    }
+
+    ___X_CMD_BWH_API_CACHE=${___X_CMD_BWH_API_CACHE:-""}       \
+    ___x_cmd_bwh_info___runapi availableos "" getAvailableOS | {
+        x jo env . .error .message .installed   .templates
+        case "$error" in
+            ""|0)       ;;
+            *)
+                bwh:error --error "$error" --msg "$message" "Fail."
+                return 1
+        esac
+        printf "%s:\t%s\n" installed "$installed"
+
+        # TODO: using x pick for this ...
+        printf "%s\n" "$templates" | x jo list2line | x pick
     }
 }
diff --git a/mod/env/lib/main b/mod/env/lib/main
--- a/mod/env/lib/main
+++ b/mod/env/lib/main
@@ -1,6 +1,6 @@
 # shellcheck    shell=sh            disable=SC3043      # xrc
-
-___x_cmd_env___pasre_pkg_version(){
+# Section: parse verion
+___x_cmd_env___pasre_pkg_version_set(){
     case "${1:?Please provide package and its version in form of <pkg>=<-|<version>>}" in
         *=-)
             ___X_CMD_ENV___PARSE_PKG="${1%=-}"
@@ -17,12 +17,32 @@ ___x_cmd_env___pasre_pkg_version(){
     esac
 }
 
+___x_cmd_env___pasre_pkg_version_unset(){
+    case "${1:?Please provide package and its version in form of <pkg>=<-|<version>>}" in
+        *=*)
+            ___X_CMD_ENV___PARSE_PKG="${1%=*}"
+            ___X_CMD_ENV___PARSE_VERSION="${1#*=}"
+            ;;
+        *)
+            ___X_CMD_ENV___PARSE_PKG="${1}"
+            ___X_CMD_ENV___PARSE_VERSION="$(___x_cmd_env_get_current_version "$1" )"
+            ;;
+    esac
+}
+
+# EndSection
+
+# Section: use
 # use = download + populate + link + linkenv + boot + save config
 ___x_cmd_env_use(){
     local dir_path
     case "$1" in
         --ws) shift; dir_path="${1}"; shift ;;
         -h|--help) ___x_cmd_env___help use;  return 1 ;;
+        */*)
+            ___x_cmd_env_appoint_candidate "USE" "$@"
+            return
+            ;;
     esac
 
     local ___X_CMD_ENV_LSENV_APP_CANDIDATE
@@ -36,7 +56,7 @@ ___x_cmd_env_use(){
 
     local code
     local i; for i in "$@"; do
-        ___x_cmd_env___pasre_pkg_version "$i"
+        ___x_cmd_env___pasre_pkg_version_set "$i"
         if [ -z "$___X_CMD_ENV___PARSE_VERSION" ]; then
             env:warn "Not found $___X_CMD_ENV___PARSE_PKG version"
             return 1
@@ -55,7 +75,7 @@ ___x_cmd_env_use(){
                 return 1
             fi
         fi
-        
+
         env:debug "Step 3/4: Linking $___X_CMD_ENV___PARSE_PKG $___X_CMD_ENV___PARSE_VERSION"
         if ! ___x_cmd_pkg link "$___X_CMD_ENV___PARSE_PKG" "$___X_CMD_ENV___PARSE_VERSION" "$dir_path" ; then
             env:error "Cannot link $___X_CMD_ENV___PARSE_PKG $___X_CMD_ENV___PARSE_VERSION"
@@ -73,14 +93,16 @@ ___x_cmd_env_use(){
 
     ___x_cmd_env_use___save_config "$@"
 }
+# EndSection
 
+# Section: env config
 ___x_cmd_env_use___save_config(){
     local ___X_CMD_ENV___PARSE_PKG
     local ___X_CMD_ENV___PARSE_VERSION
     local boot_script_path
     local code="___x_cmd_env___configstr_set_ \"\$(cat \"\$___X_CMD_ENV_VERSION_CONFIG_PATH\")\$___X_CMD_UNSEENCHAR_NEWLINE\""
     local i; for i in "$@"; do
-        ___x_cmd_env___pasre_pkg_version "$i"
+        ___x_cmd_env___pasre_pkg_version_set "$i"
         if [ -z "$___X_CMD_ENV___PARSE_VERSION" ]; then
             env:warn "Not found $___X_CMD_ENV___PARSE_PKG version."
             return 1
@@ -94,7 +116,9 @@ ___x_cmd_env_use___save_config(){
     local ___X_CMD_ENV___CONFIGSTR_SET_;    eval "$code"
     ___x_cmd_env_config___write "$___X_CMD_ENV___CONFIGSTR_SET_" ||  return 1
 }
+# EndSection
 
+# Section: unuse
 ___x_cmd_env_unuse(){
     local dir_path
     case "$1" in
@@ -102,12 +126,16 @@ ___x_cmd_env_unuse(){
         -h|--help) ___x_cmd_env___help unuse;  return 1 ;;
     esac
     x:trace env/unuse
+    ___X_CMD_ENV___PARSE_PKG=
+    ___X_CMD_ENV___PARSE_VERSION=
     local j; for j in "$@"; do
-    ___x_cmd_env___pasre_pkg_version "$j"
-    ___x_cmd_pkg_unlink "$___X_CMD_ENV___PARSE_PKG" "$___X_CMD_ENV___PARSE_VERSION" "$dir_path" || {
-        env:error "Cannot unuse $j"
-        return 1
-    }
+        ___x_cmd_env___pasre_pkg_version_unset "$j"
+        [ -n "$___X_CMD_ENV___PARSE_VERSION" ] || return 1
+        env:info "Unuse $___X_CMD_ENV___PARSE_PKG $___X_CMD_ENV___PARSE_VERSION"
+        ___x_cmd_pkg_unlink "$___X_CMD_ENV___PARSE_PKG" "$___X_CMD_ENV___PARSE_VERSION" "$dir_path" || {
+            env:error "Cannot unuse $j"
+            return 1
+        }
     done
 
     local unuse_tmp; unuse_tmp="$(cat "$___X_CMD_ENV_VERSION_CONFIG_PATH")$___X_CMD_UNSEENCHAR_NEWLINE"
@@ -120,20 +148,25 @@ ___x_cmd_env_unuse(){
         return 1
     }
 }
+# EndSection
 
-
+# Section: try
 # try = download + populate + linkenv + boot
 ___x_cmd_env_try(){
     local dir_path
     case "$1" in
         -h|--help) ___x_cmd_env___help try;  return 1 ;;
+        */*)
+            ___x_cmd_env_appoint_candidate "$@"
+            return
+            ;;
     esac
     local ___X_CMD_ENV___PARSE_PKG
     local ___X_CMD_ENV___PARSE_VERSION
 
     local code
     local i; for i in "$@"; do
-        ___x_cmd_env___pasre_pkg_version "$i"
+        ___x_cmd_env___pasre_pkg_version_set "$i"
         if [ -z "$___X_CMD_ENV___PARSE_VERSION" ]; then
             env:warn "Not found $___X_CMD_ENV___PARSE_PKG version"
             return 1
@@ -168,7 +201,9 @@ ___x_cmd_env_try(){
     env:info "Successfully set ${code# } in the current environment."
     ___X_CMD_ENV_VERSION_CONFIG="$___X_CMD_ENV___CONFIGSTR_SET_"
 }
+# EndSection
 
+# Section: untry
 ___x_cmd_env_untry(){
     case "$1" in
         -h|--help)
@@ -185,7 +220,7 @@ ___x_cmd_env_untry(){
     local code="___x_cmd_env___configstr_set_ \"\$___X_CMD_ENV_VERSION_CONFIG\""
 
     local i; for i in "$@"; do
-        ___x_cmd_env___pasre_pkg_version "$i"
+        ___x_cmd_env___pasre_pkg_version_set "$i"
         ___x_cmd_pkg rmpath "$___X_CMD_ENV___PARSE_PKG" "$___X_CMD_ENV___PARSE_VERSION"
         code="$code $___X_CMD_ENV___PARSE_PKG="
     done
@@ -194,3 +229,21 @@ ___x_cmd_env_untry(){
     env:info "Success to unset $* in this session "
     ___X_CMD_ENV_VERSION_CONFIG="$___X_CMD_ENV___CONFIGSTR_SET_"
 }
+
+# EndSection
+
+___x_cmd_env_appoint_candidate(){
+    case $1 in
+        USE) local pattern="USE"; shift ;;
+    esac
+    x pkg download "$@"
+    local name="${1##*/}"
+    local version
+    version="$(___x_cmd_pkg default_version "$name" 2>/dev/null)"
+    if [ "$pattern" = "USE" ]; then
+        x env use "$name=$version"
+    else
+        x env try "$name=$version"
+    fi
+}
+
diff --git a/mod/env/lib/util b/mod/env/lib/util
--- a/mod/env/lib/util
+++ b/mod/env/lib/util
@@ -40,3 +40,31 @@ ___x_cmd_env_which(){
         printf "%s\n" "${bin_path%/*}"
     done
 }
+
+___x_cmd_env_get_current_version(){
+    local name="$1"
+    local version_and_srcipt=
+    local version
+    [ -n "$name" ] || return
+
+    if [ ! -f "$___X_CMD_ENV_VERSION_CONFIG_PATH" ]; then
+        env:error "Config file is not exist"
+        return 1
+    fi
+
+    local line; while read -r line; do
+        [ -n "$line" ] || continue
+        [ ! "$line" = "${line#"$name"}" ] || continue
+
+        version_and_srcipt="${line#"$name"=}"
+        version="${version_and_srcipt%%=*}"
+        printf "%s" "$version"
+
+        return 0
+
+    done <"$___X_CMD_ENV_VERSION_CONFIG_PATH"
+
+    env:warn "Not found $name was used in your current environment"
+    return 1
+}
+
diff --git a/mod/hub/lib/account/bind b/mod/hub/lib/account/bind
--- a/mod/hub/lib/account/bind
+++ b/mod/hub/lib/account/bind
@@ -1,71 +1,71 @@
-# shellcheck shell=sh disable=SC3043
+# shellcheck shell=dash
 
 ___x_cmd_hub_account_bind(){
-    case "$1" in
-        wx|weixin)              ___x_cmd_hub_account_bind_weixin   "$@" ;;
-        email)                  ___x_cmd_hub_account_bind_email    "$@" ;;
-        tg|telegram)            ___x_cmd_hub_account_bind_telegram "$@" ;;
-        gh|github)              ___x_cmd_hub_account_bind_github   "$@" ;;
-        gt|gitee)               ___x_cmd_hub_account_bind_gitee    "$@" ;;
-        *)  ___x_cmd_hub___help account bind ; return 1 ;;
+    local X_help_cmd='___x_cmd_hub___help bind'
+    help:arg-null:parse
+
+    local op="$1"; [ $# -eq 0 ] || shift
+    case "$op" in
+        email)      ___x_cmd_hub_account_bind_email      "$@" ;;
+        *)          ___x_cmd_hub_u_subcmd_invalid bind   "$@" ;;
     esac
-
-    ___x_cmd_hub_account_bind_"$1" "$@"
 }
 
-___x_cmd_hub_account_bind_weixin(){
-    local token
-    token="$(___x_cmd_hub___util_get_token)"
+# TODO: avoid use subshell
+___x_cmd_hub_account_bind_email()(
+    local X_help_cmd='___x_cmd_hub___help bind email'
+    help:arg:parse
 
-    ___x_cmd_hub_qrcode "$(___x_cmd_hub_weixin_bind_url "${token}")"
-    printf "Please scan the QR code above, then press [Enter] to continue: "
-    ( trap - INT; read -r _  ) || return 1
-
-    # TODO: A way to confirm bind is successful.
-    ___x_cmd_hub_account_verify "$token"
-}
-
-___x_cmd_hub_account_bind_email_witharg(){
-    local email="${1:?Provide email}"
-
-    local res
-    if ! res="$(___x_cmd_hub___util_curl post /api/v0/account/email/bind -- "email=$email")" ; then
-        ___x_cmd_hub___util_handle_resp false "$res" "Failed to bind with email $email:"
+    local token ; token="$(___x_cmd_hub_cur --get token)"
+    if [ -z "$token" ]; then
+        ___x_cmd_ui_tf false "Please login first, use 'x hub login'"
         return 1
     fi
-    hub:debug "Login with email: $email, res: $res"
-    printf "%s" "Please check your email $email to approve, then press [Enter] to continue: " >&2
-    ( trap - INT; read -r _  ) || return 1
 
-    # TODO: A way to confirm bind is successful.
-    ___x_cmd_hub_account_verify "$token"
-}
-
-___x_cmd_hub_account_bind_email(){
-    local email="${1}"
+    local email="$1"
     if [ -z "$email" ]; then
-        printf "%s" "Email: "
-        read -r email
+        if ! ___x_cmd_is_interactive_tty || [ ! -t 1 ]; then
+            hub:error "Email required, but not in interactive tty"
+            return 1
+        fi
+
+        ___X_CMD_TUI_FORM_FINAL_COMMAND=""
+        x tui form email      "Email"           ""  '=~'  '^.*@.*$' || return 1
+        [ -n "$___X_CMD_TUI_FORM_FINAL_COMMAND" ] || {
+            hub:info "Canceled"
+            return 1
+        }
     fi
-    ___x_cmd_hub_account_bind_email_witharg "$email"
+    ___x_cmd_hub_account_bind_email___witharg "$email"
+)
+
+___x_cmd_hub_account_bind_email___witharg(){
+    local email="$1"
+    [ -n "$email" ] || M='Provide email' N=hub log:ret:64
+
+    # Send email
+    local resp
+    resp="$(___x_cmd_hub_u_curl post /api/v0/account/email/bind -- "email=$email")" || {
+        ___x_cmd_hub_u_handle_resp false "Failed to bind with email $email:"
+        return 1
+    }
+    hub:debug "Bind with $email, resp => $resp"
+    x ui yesno "Please check your email $email to approve, then press [Yes] to continue: " || return 1
+
+    # Check email is binded
+    ___x_cmd_hub_u_curl get /api/v0/account | {
+        local remote_email; local msg
+        x jo env . remote_email=.email .msg
+        [ -n "$remote_email" ] || {
+            ___x_cmd_hub_u_handle_resp false "Failed to get user info:"
+            return 1
+        }
+
+        if [ "$email" != "$remote_email" ]; then
+            ___x_cmd_hub_u_handle_resp false "$email" "Failed to bind with email $email:"
+            return 1
+        fi
+
+        ___x_cmd_hub_u_handle_resp true "Successfully bind with email $remote_email"
+    }
 }
-
-# TODO: telegram bind is not working, to use browser to login
-___x_cmd_hub_account_bind_telegram(){
-    local token
-    token="$(___x_cmd_hub___util_get_token)" || return
-
-    printf "Open the url in browser to login: https://hub.x-cmd.com/s/tb/%s\nthen press [Enter] to continue: " "${token}"
-    ( trap - INT; read -r _  ) || return 1
-
-    ___x_cmd_hub_account_verify "$token"
-}
-
-___x_cmd_hub_account_bind_github(){
-    : # TODO
-}
-
-___x_cmd_hub_account_bind_gitee(){
-    : # TODO
-}
-
diff --git a/mod/hub/lib/account/login b/mod/hub/lib/account/login
--- a/mod/hub/lib/account/login
+++ b/mod/hub/lib/account/login
@@ -1,6 +1,9 @@
-# shellcheck shell=sh disable=SC3043
+# shellcheck shell=dash
 
 ___x_cmd_hub_account_login(){
+    local X_help_cmd='___x_cmd_hub___help account login'
+    help:arg:parse
+
     if [ -n "$(___x_cmd_hub_cfg --get token)" ]; then
         if ! x ui yesno "You're already logged. Do you want to re-authenticate?" ; then
             hub:info "Cancelled"
@@ -9,102 +12,160 @@ ___x_cmd_hub_account_login(){
         ___x_cmd_hub_account_logout
     fi
 
-    local op="$1"
+    local login_type
+    local ___X_CMD_HUB_LOGIN_EXPIRE="30d"
+    local ___X_CMD_HUB_LOGIN_REGION=cn
+    while [ $# -gt 0 ]; do
+        case "$1" in
+            --expire)    ___X_CMD_HUB_LOGIN_EXPIRE="$2"  ; shift 2 ;;
+            --region)    ___X_CMD_HUB_LOGIN_REGION="$2"  ; shift 2 ;;
+            *) break ;;
+        esac
+    done
+
+    login_type="$1"
+
+    # ___X_CMD_TUI_FORM_FINAL_COMMAND=""
+    # x tui form \
+    #     login_type    "Login type"       wechat  =   wechat wechat_website github email  -- \
+    #     ___X_CMD_HUB_LOGIN_EXPIRE   "Expire time"      1h      =   1h 1d 1w 1m 1y -- \
+    #     ___X_CMD_HUB_LOGIN_REGION        "Region"           cn      =   cn world
+
+    # [ -n "$___X_CMD_TUI_FORM_FINAL_COMMAND" ] || {
+    #     hub:info "Canceled"
+    #     return 1
+    # }
+
     local _SELECT
-    case "$op" in
-        *@*)                    ___x_cmd_hub_account_login_email_witharg "$@" ;;
-        wx|weixin)              ___x_cmd_hub_account_login_weixin_qr     "$@" ;;
-        email)                  ___x_cmd_hub_account_login_email         "$@" ;;
-        tg|telegram)            ___x_cmd_hub_account_login_telegram_qr        ;;
-        "")
-                ___x_cmd_ui_select "_SELECT" \
-                    "Login Methods:" \
-                        "Open Browser to x-cmd.com, you can login via GitHub/Gitee/Weixin" \
-                        "Login With Weixin QR" \
-                        "Login With Email Verification"
+    if [ -z "$login_type" ]; then
+        ___x_cmd_ui_select "_SELECT" \
+            "Login Methods:" \
+                "Open Browser to hub.x-cmd.com, you can login via GitHub/WeChat" \
+                "Login With WeChat QR" \
+                "Login With WeChat via website" \
+                "Login With GitHub via website" \
+                "Login With Email Verification"
 
-                        #TODO: unstable
-                        # "Login With Telegram" \
-                        # "Login With OneTime Password"    # SMS, Telegram, Email, Weixin
+                #TODO: unstable
+                # "Login With Telegram" \
+                # "Login With OneTime Password"    # SMS, Telegram, Email, WeChat
 
-                case "$_SELECT" in
-                    1)          ___x_cmd_hub_account_login_official_site "$@" ;;
-                    2)          ___x_cmd_hub_account_login_weixin_qr     "$@" ;;
-                    3)          ___x_cmd_hub_account_login_email         "$@" ;;
-                    4)          ___x_cmd_hub_account_login_telegram      "$@" ;;
-                    *)          ;;
-                esac
-                ;;
-        *)  ___x_cmd_hub___help account login ;;
+        case "$_SELECT" in
+            1)  login_type=website ;;
+            2)  login_type=wxqr   ;;
+            3)  login_type=wechat ;;
+            4)  login_type=github ;;
+            5)  login_type=email  ;;
+            *)  hub:info "Canceled" ; return 1 ;;
+        esac
+    fi
+
+    case "$login_type" in
+        website)   ___x_cmd_hub_account_login_website    ""       ;;
+        wxqr)      ___x_cmd_hub_account_login_wechat_qr           ;;
+        wechat)    ___x_cmd_hub_account_login_website    wechat   ;;
+        github)    ___x_cmd_hub_account_login_website    github   ;;
+        email)     ___x_cmd_hub_account_login_email      "$@"     ;;
+        *)         hub:error "Unknown login type: $login_type" ;;
     esac
 }
 
-# TODO: move to website login
-___x_cmd_hub_account_login_telegram(){
+___x_cmd_hub_account_login_website(){
+    local login_type="$1"
     local ticket
-    ticket="$(___x_cmd_hub___util_token_generate)"
+    ticket="$(___x_cmd_hub_u_ticket_generate)"
 
-    printf "Open the url in browser to login: https://hub.x-cmd.com/s/tl/%s\nthen press [Enter] to continue: " "${ticket}"
-    ( trap - INT; read -r _  ) || return 1
-
-    ___x_cmd_hub_account_verify "$ticket"
-}
-
-___x_cmd_hub_account_login_weixin_qr(){
-    local ticket
-    ticket="$(___x_cmd_hub___util_token_generate)"
-
-    ___x_cmd_hub_qrcode "$(___x_cmd_hub_weixin_login_url "${ticket}")"
-    printf "Please scan the QR code above, then press [Enter] to continue: "
-    ( trap - INT; read -r _  ) || return 1
-
-    ___x_cmd_hub_account_verify "$ticket"
-}
-
-___x_cmd_hub_account_login_official_site(){
-
-    local ticket
-    ticket="$(___x_cmd_hub___util_token_generate)"
-
-    local url; url="https://hub.x-cmd.com/login?ticket=${ticket}"
+    local url; url="https://hub.x-cmd.com/login?ticket=${ticket}&type=${login_type}&expire=${___X_CMD_HUB_LOGIN_EXPIRE}&region=${___X_CMD_HUB_LOGIN_REGION}"
     hub:debug "Open url: $url"
 
-    # TODO: use tui
-    local res
-    if res=$(x open "$url" 2>&1) ; then
-        printf "Please login to hub.x-cmd.com, then press [Enter] to continue: " >&2
-        ( trap - INT; read -r _  ) || return 1
+    local msg
+    if msg=$(x open "$url" 2>&1) ; then
+        x ui yesno "Please login to hub.x-cmd.com, then press [Yes] to continue: " || return 1
     else
-        hub:warn "Failed to open url use browser ($res)"
-        printf "Open the url in browser to login: %s\nthen press [Enter] to continue: " "$url" >&2
-        ( trap - INT; read -r _  ) || return 1
+        hub:warn "Failed to open url use browser ($msg)"
+        x ui yesno "Open the url in browser to login: %s\nthen press [Yes] to continue: " "$url" || return 1
     fi
 
-    ___x_cmd_hub_account_verify "$ticket"
+    ___x_cmd_hub_account___verify "$ticket"
+}
+
+___x_cmd_hub_account_login_wechat_qr(){
+    local ticket; ticket="$(___x_cmd_hub_u_ticket_generate)" || return 1
+    ___x_cmd_hub_qrcode "$(___x_cmd_hub_wechat_url login "$ticket")"
+    x ui yesno "Please scan the QR code above, then press [Yes] to continue: " || return 1
+    ___x_cmd_hub_account___verify "$ticket"
 }
 
 ___x_cmd_hub_account_login_email_witharg(){
-    local email="${1:?Provide email}"
-    local ticket
-    ticket="$(___x_cmd_hub___util_token_generate)"
+    local email="$1"; [ -n "$email" ]  || M='Provide email'       N=hub log:ret:64
 
-    local res
-    if ! res="$(NO_AUTH=1 ___x_cmd_hub___util_curl post /api/v0/account/email/login -- "tokenToActivate=$ticket" "email=$email")" ; then
-        ___x_cmd_hub___util_handle_resp false "$res" "Failed to login with email $email:"
+    local resp
+    resp="$(NO_AUTH=1 ___x_cmd_hub_u_curl post /api/v0/account/email/login -- "email=$email")" || {
+        ___x_cmd_hub_u_handle_resp false "Failed to login with email $email:"
         return 1
-    fi
-    hub:debug "Login with email: $email, res: $res"
-    printf "%s" "Please check your email $email to approve, then press [Enter] to continue: " >&2
-    ( trap - INT; read -r _  ) || return 1
+    }
 
-    ___x_cmd_hub_account_verify "$ticket"
+    hub:debug "Login with email -> $email, resp -> $resp"
+    local ticket; ticket="$(printf "%s" "$resp" | x jo env . .ticket -- 'printf "%s" "$ticket"')"
+    x ui yesno "Please check your email $email to approve, then press [Yes] to continue: " || return 1
+
+    ___x_cmd_hub_account___verify "$ticket"
 }
 
 ___x_cmd_hub_account_login_email(){
-    local email="${1}"
+    local email="$1"
     if [ -z "$email" ]; then
-        printf "%s" "Email: "
-        read -r email
+        if ! ___x_cmd_is_interactive_tty || [ ! -t 1 ]; then
+            hub:error "Email required, but not in interactive tty"
+            return 1
+        fi
+
+        ___X_CMD_TUI_FORM_FINAL_COMMAND=""
+        x tui form email      "Email"           ""  '=~'  '^.*@.*$' || return 1
+        [ -n "$___X_CMD_TUI_FORM_FINAL_COMMAND" ] || {
+            hub:info "Canceled"
+            return 1
+        }
     fi
     ___x_cmd_hub_account_login_email_witharg "$email"
+}
+
+# TODO: refactor
+___x_cmd_hub_account___verify() {
+    local ticket="$1" ; [ -n "$ticket" ]     || M='Please provide ticket' N=hub log:ret:64
+
+    local endpoint
+    endpoint="$(NO_AUTH=1 ___x_cmd_hub_u_curl get /api/v0/account/ticket/endpoint ticket== | {
+        local msg; local resp
+        x jo env . resp=.endpoint .msg
+        if [ -z "$resp" ]; then
+            ___x_cmd_hub_u_handle_resp false "Failed to get endpoint:"
+            return 1
+        fi
+        printf "%s" "$resp"
+    })" || return 1
+
+    ___X_CMD_HUB_SERVICE_URL="$endpoint"
+    ___x_cmd_hub_cfg --set endpoint="$endpoint"
+
+    NO_AUTH=1 ___x_cmd_hub_u_curl get /api/v0/account/verify ticket== | {
+        local name ; local id; local plan ; local email ; local token; local msg
+        x jo env . .name .plan .email \
+            .region .token .endpoint \
+            .token .msg
+
+        [ -n "$token" ] || {
+            ___x_cmd_hub_u_handle_resp false "Failed to verify token:"
+            ___x_cmd_ui_tf false "Failed to login, please check your token" >&2
+            return 1
+        }
+
+        ___x_cmd_hub_u_handle_resp true "Account info:" \
+            "name: $name" \
+            "region: $___X_CMD_HUB_LOGIN_REGION" ${email:+"email: $email"}
+
+        ___x_cmd_hub_cfg token="${token}"
+    }
+
+    ___x_cmd_ui_tf true "Login success"
 }
diff --git a/mod/hub/lib/keypair/gen b/mod/hub/lib/keypair/gen
--- a/mod/hub/lib/keypair/gen
+++ b/mod/hub/lib/keypair/gen
@@ -1,35 +1,30 @@
 # shellcheck shell=dash
 
 ___x_cmd_hub_keypair_gen(){
-    local key_path; key_path="$(___x_cmd_hub___util_user_dir me keypair)" || return 1
-    while [ $# -gt 0 ]; do
-        case "$1" in
-            --help|-h|"")        ___x_cmd_hub___help key generate ; return 1 ;;
-            --key-path) shift ;  key_path="$1" ; shift;;
-            *) break ;;
-        esac
-    done
+    local X_help_cmd='___x_cmd_hub___help keypair gen'
+    help:arg:parse
 
-    local name="${1:-"$___X_CMD_HUB_KEYPAIR"}"
-    local private_key_path="$key_path/${name}_private.pem"
-    local public_key_path="$key_path/${name}_public.pem"
-    if [ -f "$private_key_path" ] || [ -f "$public_key_path" ] ; then
-        hub:error "Key already exists, $private_key_path or $public_key_path"
+    if [ -f "$___X_CMD_HUB_PRIVATE_KEY_PATH" ] || [ -f "$___X_CMD_HUB_PUBLIC_KEY_PATH" ] ; then
+        hub:error "Key already exists, $___X_CMD_HUB_PRIVATE_KEY_PATH or $___X_CMD_HUB_PUBLIC_KEY_PATH"
         return 1
     fi
 
-    if ! x openssl genrsa -out "$private_key_path" 2048 ; then
+    hub:debug "Step1 => Generated private key"
+    x openssl genrsa -out "$___X_CMD_HUB_PRIVATE_KEY_PATH" 2048 || {
         hub:error "Failed to generate private key"
         return 1
-    fi
-    hub:debug "Generated private key: $private_key_path"
+    }
 
-    if ! res="$(x openssl rsa -in "$private_key_path" -pubout -out "$public_key_path" 2>&1)" ; then
-        hub:error "Failed to generate public key => $res"
+    hub:debug "Step2 => Generated public key"
+    x openssl rsa -in "$___X_CMD_HUB_PRIVATE_KEY_PATH" -pubout -out "$___X_CMD_HUB_PUBLIC_KEY_PATH" >/dev/null || {
+        hub:error "Failed to generate public key"
         return 1
-    fi
-    hub:debug "Generated public key => $public_key_path"
+    }
 
-    hub:info "Key '$name' generated, and now saving..."
-    ___x_cmd_hub_keypair_save --key-path "$key_path" "$name"
+    hub:info "Key '$___X_CMD_HUB_KEYPAIR_NAME' generated, and now saving..."
+    ___x_cmd_hub_keypair_save "$___X_CMD_HUB_KEYPAIR_NAME" || {
+        hub:error "Failed to save key"
+        x rm "$___X_CMD_HUB_PRIVATE_KEY_PATH" "$___X_CMD_HUB_PUBLIC_KEY_PATH"
+        return 1
+    }
 }
diff --git a/mod/hub/lib/keypair/index b/mod/hub/lib/keypair/index
--- a/mod/hub/lib/keypair/index
+++ b/mod/hub/lib/keypair/index
@@ -3,50 +3,66 @@
 xrc:mod:lib hub keypair/ls keypair/rm keypair/save keypair/load keypair/gen
 
 ___x_cmd_hub_keypair(){
-    local op
-    while [ $# -gt 0 ] ; do
-        op="$1"; shift
-        case "$op" in
-            --help|-h|"")    ___x_cmd_hub___help key ; return 1 ;;
-            gen|save|load|ls|rm)
-                "___x_cmd_hub_keypair_$op" "$@" ; return ;;
-            *) ___x_cmd_hub___util_subcmd_invalid "key" "$@";  return ;;
-        esac
-    done
+    local X_help_cmd='___x_cmd_hub___help keypair'
+    help:arg-null:parse
+
+    local keydir; keydir="$(___x_cmd_hub_u_userdir me keypair)" || return 1
+    local ___X_CMD_HUB_PUBLIC_KEY_PATH="$keydir/${___X_CMD_HUB_KEYPAIR_NAME}_public.pem"
+    local ___X_CMD_HUB_PRIVATE_KEY_PATH="$keydir/${___X_CMD_HUB_KEYPAIR_NAME}_private.pem"
+    hub:debug "___X_CMD_HUB_PUBLIC_KEY_PATH=$___X_CMD_HUB_PUBLIC_KEY_PATH ___X_CMD_HUB_PRIVATE_KEY_PATH=$___X_CMD_HUB_PRIVATE_KEY_PATH"
+
+    local op="$1"; shift
+    case "$op" in
+        gen|save|load|ls|rm|get_key_path_)
+            "___x_cmd_hub_keypair_$op" "$@" ; return ;;
+        *) ___x_cmd_hub_u_subcmd_invalid "key" "$@";  return ;;
+    esac
 }
 
-___x_cmd_hub_keypair___ensure_key_(){
-    local keyname="${1:?keyname is required}"
-    # TODO: keytype encrypt type
-    local keytype="${2:?keytype is required}"
-    local username="${3:-me}"
+___x_cmd_hub_keypair_get_key_path_(){
+    local keyname="$1"; [ -n "$keyname" ] || M='Provide key name' N=hub log:ret:64
+    local keytype="$2"; [ -n "$keytype" ] || M='Provide key type' N=hub log:ret:64
 
-    local key_path; key_path="$(___x_cmd_hub___util_user_dir "$username" keypair)/${keyname}_${keytype}.pem"
-    [ "$username" = "me" ] || {
-        if ! ___x_cmd_hub___util_curl get "/api/v0/key/$keyname" type="$keytype" "username=$username" > "$key_path" ; then
-            ___x_cmd_hub___util_handle_resp false "$(cat "$key_path")" "Failed to get public key for $username"
-            x rmrf "$key_path"
-            return 1
-        fi
-        hub:debug "Downloaded public key for $key_path to $key_path"
-    }
+    x_="$(___x_cmd_hub_u_userdir me keypair)/${keyname}_${keytype}.pem"
+    [ -f "$x_" ] || ___x_cmd_hub_keypair___ensure "$keyname"
+}
 
-    x_="$key_path"
-    if [ -f "$x_" ] ; then
-        hub:debug "Found key=$key_path"
-        return 0
-    fi
+___x_cmd_hub_keypair___ensure(){
+    local keyname="$1"
+    [ -n "$keyname" ] || M='Provide key name' N=hub log:ret:64
 
     hub:info "No public key '$keyname', try to load from server"
-    ___x_cmd_hub_keypair_load "$keyname"
+    NO_LOG=1 ___x_cmd_hub_keypair_load "$keyname" || {
+        case "$(___x_cmd_hub_u_curl_resp_code)" in
+            404)
+                hub:info "No public key '$keyname' found at server, try to generate"
+                ___x_cmd_hub_keypair_gen "$keyname"
+                ;;
+            2*)  return 0 ;;
+            *)  hub:error "Failed to load public key"
+                return 1 ;;
+        esac
+    }
+}
 
-    case "$?" in
-        4)  ;; # no key found
-        0)  return 0 ;;
-        *)  hub:error "Failed to load public key"
-            return 1 ;;
-    esac
+___x_cmd_hub_keypair___download_pubkey_list(){
+    local user_list="$1"
+    [ -n "$user_list" ] || M='Provide user_list' N=hub log:ret:64
 
-    hub:info "No public key '$keyname' found at server, try to generate"
-    ___x_cmd_hub_keypair_gen "$keyname"
+    user_list="$(printf "%s" "{name:[${user_list}]}" | x jo fmt)"
+    ___x_cmd_hub_u_curl post /api/v0/key/get/pubkey/list user_list | (
+        x jo env .\* .msg .username .key -- '___x_cmd_hub_keypair___single_pubkey_to_file "${username}" "${key}"'
+        ___x_cmd_hub_u_curl_resp_http_check || {
+            ___x_cmd_hub_u_handle_resp false "Failed to get public key list"
+            return 1
+        }
+    )
+}
+
+___x_cmd_hub_keypair___single_pubkey_to_file(){
+    local username="$1"; [ -n "$username" ] || M='Provide username'   N=hub log:ret:64
+    local pubkey="$2";   [ -n "$pubkey" ]   || M='Provide pubkey'     N=hub log:ret:64
+
+    local key_path; key_path="$(___x_cmd_hub_u_userdir "$username" keypair)/default_public.pem"
+    printf "%s" "${pubkey}" > "${key_path}"
 }
diff --git a/mod/hub/lib/keypair/load b/mod/hub/lib/keypair/load
--- a/mod/hub/lib/keypair/load
+++ b/mod/hub/lib/keypair/load
@@ -1,36 +1,41 @@
 # shellcheck shell=dash
 
 ___x_cmd_hub_keypair_load(){
-    local key_path; key_path="$(___x_cmd_hub___util_user_dir me keypair)" || return 1
-    while [ $# -gt 0 ]; do
-        case "$1" in
-            --help|-h|"")    ___x_cmd_hub___help file put ; return 1 ;;
-            --key-path)      shift ;  key_path="$1" ; shift;;
-            *) break ;;
-        esac
-    done
+    local X_help_cmd='___x_cmd_hub___help keypair load'
+    help:arg:parse
 
-    local name="${1:-"$___X_CMD_HUB_KEYPAIR"}"
-    local public_key_path="$key_path/${name}_public.pem"
-    local private_key_path="$key_path/${name}_private.pem"
-    local private_key_enc_path="$key_path/${name}_private.enc.pem"
+    local ___X_CMD_HUB_PRIKEY_ENC_PATH="$___X_CMD_HUB_PRIVATE_KEY_PATH.enc"
+    ___x_cmd_hub_keypair___download || return 1
+    ___x_cmd_hub_keypair___decrypt_private_key "$___X_CMD_HUB_PRIKEY_ENC_PATH" "$___X_CMD_HUB_PRIVATE_KEY_PATH" || return 1
+}
 
-    # if [ -f "$public_key_path" ] || [ -f "$private_key_path" ] ; then
-    #     hub:error "Key already exists in local, $public_key_path or $private_key_path"
-    #     return 1
-    # fi
+# TODO: download once curl request
+___x_cmd_hub_keypair___download(){
+    # Download private key
+    local resp;
+    resp="$(___x_cmd_hub_u_curl get "/api/v0/key/$___X_CMD_HUB_KEYPAIR_NAME" type==private)" || {
+        [ -n "$NO_LOG" ] || ___x_cmd_hub_u_handle_resp false "Failed to get rsakey for $___X_CMD_HUB_KEYPAIR_NAME"
+        return 1
+    }
+    printf "%s" "$resp" | x openssl enc -d -A -base64 > "$___X_CMD_HUB_PRIKEY_ENC_PATH"
 
-    local res; local return_code=0
-    res="$(___x_cmd_hub___util_curl get "/api/v0/key/$name" type=private)" || return_code="$?"
-    if [ "$return_code" != 0 ]  ; then
-        ___x_cmd_hub___util_handle_resp false "$res" "Failed to get rsakey for $name"
-        return "$return_code"
-    fi
-    printf "%s" "$res" | x openssl enc -d -A -base64 > "$private_key_enc_path"
+    # Download public key
+    resp="$(___x_cmd_hub_u_curl get "/api/v0/key/$___X_CMD_HUB_KEYPAIR_NAME" type==public)" || {
+        [ -n "$NO_LOG" ] || ___x_cmd_hub_u_handle_resp false "Failed to get rsakey for $___X_CMD_HUB_KEYPAIR_NAME"
+        return 1
+    }
+    printf "%s" "$resp" > "$___X_CMD_HUB_PUBLIC_KEY_PATH"
+}
 
-    local password
+___x_cmd_hub_keypair___decrypt_private_key(){
     hub:info "Please input password for encrypt private key"
+    local password
     while true ; do
+        if ! ___x_cmd_is_interactive_tty || [ ! -t 1 ]; then
+            hub:error "Password required, but not in interactive tty"
+            return 1
+        fi
+
         ___X_CMD_TUI_FORM_FINAL_COMMAND=""
         x tui form password      "Password"           ""  '=~*'  '^.*$' || return 1
         [ -n "$___X_CMD_TUI_FORM_FINAL_COMMAND" ] || {
@@ -38,20 +43,10 @@ ___x_cmd_hub_keypair_load(){
             return 1
         }
 
-        hub:debug x openssl enc -d -aes-256-cbc -in "$private_key_enc_path" -out "$private_key_path" -pbkdf2 -pass pass:"$password"
-        x openssl enc -d -aes-256-cbc -in "$private_key_enc_path" -out "$private_key_path" -pbkdf2 -pass pass:"$password" || {
+        hub:debug "x openssl enc -d -aes-256-cbc -in $___X_CMD_HUB_PRIKEY_ENC_PATH -out $___X_CMD_HUB_PRIVATE_KEY_PATH -pbkdf2 -pass pass:$password"
+        x openssl enc -d -aes-256-cbc -in "$___X_CMD_HUB_PRIKEY_ENC_PATH" -out "$___X_CMD_HUB_PRIVATE_KEY_PATH" -pbkdf2 -pass "pass:$password" || {
             hub:error "Failed to decrypt private key, or password not match, please try again"
         }
         break
     done
-
-    hub:debug "Loaded private key => $private_key_path"
-
-    if ! res="$(___x_cmd_hub___util_curl get "/api/v0/key/$name" type=public)" ; then
-        ___x_cmd_hub___util_handle_resp false "$res" "Failed to get rsakey for $name"
-        return "$1"
-    fi
-    x mkdirp "$key_path"
-    printf "%s" "$res" > "$public_key_path"
-    hub:debug "Loaded public key => $public_key_path"
 }
diff --git a/mod/hub/lib/keypair/save b/mod/hub/lib/keypair/save
--- a/mod/hub/lib/keypair/save
+++ b/mod/hub/lib/keypair/save
@@ -1,28 +1,22 @@
 # shellcheck shell=dash
 
 ___x_cmd_hub_keypair_save(){
-    local key_path; key_path="$(___x_cmd_hub___util_user_dir me keypair)" || return 1
-    while [ $# -gt 0 ]; do
-        case "$1" in
-            --help|-h|"")    ___x_cmd_hub___help key generate ; return 1 ;;
-            --key-path)      shift ;  key_path="$1" ; shift;;
-            *) break ;;
-        esac
-    done
+    local X_help_cmd='___x_cmd_hub___help keypair save'
+    help:arg:parse
 
-    local name="${1:-"$___X_CMD_HUB_KEYPAIR"}"
-    local public_key_path="$key_path/${name}_public.pem"
-    local private_key_path="$key_path/${name}_private.pem"
-    hub:debug "public_key_path=$public_key_path private_key_path=$private_key_path"
-
-    if [ ! -f "$public_key_path" ] || [ ! -f "$private_key_path" ] ; then
-        hub:error "Key not exists, $public_key_path or $private_key_path"
+    if [ ! -f "$___X_CMD_HUB_PUBLIC_KEY_PATH" ] || [ ! -f "$___X_CMD_HUB_PRIVATE_KEY_PATH" ] ; then
+        hub:error "Key not exists, $___X_CMD_HUB_PUBLIC_KEY_PATH or $___X_CMD_HUB_PRIVATE_KEY_PATH"
         return 1
     fi
 
     hub:info "Please input password for encrypt private key"
     local password1; local password2
     while true ; do
+        if ! ___x_cmd_is_interactive_tty || [ ! -t 1 ]; then
+            hub:error "Password required, but not in interactive tty"
+            return 1
+        fi
+
         ___X_CMD_TUI_FORM_FINAL_COMMAND=""
         x tui form \
             password1      "Password"           ""  '=~*'  '^.*$' -- \
@@ -36,21 +30,21 @@ ___x_cmd_hub_keypair_save(){
     done
 
 
-    local private_key_enc_base64_path="$key_path/${name}_private.enc.base64"
-    x openssl enc -aes-256-cbc -salt -in "$private_key_path" -out - -pbkdf2 -pass pass:"$password1" |
-        x openssl enc -A -base64 > "$private_key_enc_base64_path"
+    local private_key_enc_base64_path="$___X_CMD_HUB_PRIVATE_KEY_PATH.enc.base64"
+    x openssl enc -aes-256-cbc -salt -in "$___X_CMD_HUB_PRIVATE_KEY_PATH" -out - -pbkdf2 -pass pass:"$password1" \
+        | x openssl enc -A -base64 > "$private_key_enc_base64_path"
     hub:debug "Encrypted private key => $private_key_enc_base64_path"
 
-    local res;
-    if ! res="$(___x_cmd_hub___util_curl post /api/v0/key -F "file=@$private_key_enc_base64_path" "type=private" "name=${name}")" ; then
-        ___x_cmd_hub___util_handle_resp false "$res" "Failed to put private key"
+    local resp;
+    resp="$(___x_cmd_hub_u_curl post "/api/v0/key?type=private&name=${___X_CMD_HUB_KEYPAIR_NAME}" -F "file=@$private_key_enc_base64_path" )" || {
+        ___x_cmd_hub_u_handle_resp false "Failed to put private key"
         return 1
-    fi
+    }
 
-    if ! res="$(___x_cmd_hub___util_curl post /api/v0/key -F "file=@$public_key_path" "type=public" "name=${name}")" ; then
-        ___x_cmd_hub___util_handle_resp false "$res" "Failed to put public key"
+    resp="$(___x_cmd_hub_u_curl post "/api/v0/key?type=public&name=${___X_CMD_HUB_KEYPAIR_NAME}" -F "file=@$___X_CMD_HUB_PUBLIC_KEY_PATH" )" || {
+        ___x_cmd_hub_u_handle_resp false "Failed to put public key"
         return 1
-    fi
+    }
 
     hub:info "Key saved"
 }
diff --git a/mod/hub/lib/util/index b/mod/hub/lib/util/index
--- a/mod/hub/lib/util/index
+++ b/mod/hub/lib/util/index
@@ -2,36 +2,54 @@
 
 xrc:mod:lib hub util/curl util/userdir util/token util/math
 
-___x_cmd_hub___util_handle_resp(){
-    local isSuccess="$1"; local resp="$2"; local msg="$3"; shift 3
-    local resp_msg; resp_msg="$(printf "%s" "$resp" | {
-        x jo env . resp_msg=.msg ; printf "%s\n" "$resp_msg" ;
-    })"
-
-    [ -z "$resp_msg" ] || {
-        ___x_cmd_ui_tf "$isSuccess" "$msg" "$resp_msg" >&2
-        return
-    }
-
-    if [ -n "$resp" ] ; then  ___x_cmd_ui_tf "$isSuccess" "$msg" "resp: $resp" "$@" >&2
-    else                      ___x_cmd_ui_tf "$isSuccess" "$msg"               "$@" >&2  ;fi
+___x_cmd_hub_u_printf_error_msg(){
+    if ! ___x_cmd_is_interactive_tty || [ ! -t 2 ] || [ -n "$NO_COLOR" ]; then
+        printf "  - ErrorMsg: %s\n" "$M" >&2
+    else
+        printf "  \033[31m-\033[0m \033[1mErrorMsg: \033[31m%s\033[0m\n" "$M" >&2
+    fi
 }
 
-___x_cmd_hub___util_subcmd_invalid(){
-    local subcmd="${1}"
-    local arg="${2}"
-    [ -z "$subcmd" ] || subcmd="$subcmd "
-    if [ -z "$arg" ]; then ___x_cmd_ui_tf false "Subcommand required. See 'x hub $subcmd--help|-h':" >&2
-    else                   ___x_cmd_ui_tf false "'$arg' is not a subcommand. See 'x hub $subcmd--help|-h':" >&2 ; fi
+___x_cmd_hub_u_printf_success_msg(){
+    if ! ___x_cmd_is_interactive_tty || [ ! -t 2 ] || [ -n "$NO_COLOR" ]; then
+        printf "  - Msg: %s\n" "$M"
+    else
+        printf "  \033[32m-\033[0m \033[1mMsg: \033[32m%s\033[0m\n" "$M"
+    fi
+}
+
+___x_cmd_hub_u_handle_resp(){
+    local is_success="$1" ; shift
+    local M=""
+
+    if [ -n "$msg" ]; then
+        M="$msg"
+    elif [ -n "$resp" ]; then
+        M="$(printf "%s" "$resp" | x jo env . .msg -- 'printf "%s" "${msg}"')"
+    fi
+
+    case "$is_success" in
+        true)   ___x_cmd_ui_tf "$is_success" "$@"
+                [ -z "$M" ] || ___x_cmd_hub_u_printf_success_msg  ;;
+        false)  ___x_cmd_ui_tf "$is_success" "$@" >&2
+                [ -z "$M" ] || ___x_cmd_hub_u_printf_error_msg >&2  ;;
+        *)  hub:err "Invalid is_success=$is_success" ;;
+    esac
+}
+
+___x_cmd_hub_u_subcmd_invalid(){
+    local subcmd="${1+"$1 "}"
+    local arg="$2"
+    if [ -z "$arg" ]; then ___x_cmd_ui_tf false "Subcommand required. See 'x hub ${subcmd}--help|-h':" >&2
+    else                   ___x_cmd_ui_tf false "'$arg' is not a subcommand. See 'x hub ${subcmd}--help|-h':" >&2 ; fi
     return 1
 }
 
 ___x_cmd_hub___help(){
-    x help -m hub "$@" >&2
-    return 1
+    x help -m hub "$@"
 }
 
-___x_cmd_hub___util_st_tab(){
+___x_cmd_hub_u_st_tab(){
     if ! ___x_cmd_is_interactive_tty || [ ! -t 1 ]; then
         x csv static_tab
     else
diff --git a/mod/pkg/lib/info/ls b/mod/pkg/lib/info/ls
--- a/mod/pkg/lib/info/ls
+++ b/mod/pkg/lib/info/ls
@@ -3,19 +3,38 @@
 # ls app, default app
 ___x_cmd_pkg_ls(){
     case "$1" in
-        i|installed)      shift;  ___x_cmd_pkg_ls_installed "$@" ;;
-        a|activated)      shift;  ___x_cmd_pkg_ls_activated "$@" ;;
+        p|populated)      shift;  ___x_cmd_pkg_ls_populated "$@" ;;
+        d|downloaded)     shift;  ___x_cmd_pkg_ls_downloaded "$@" ;;
         A|all)            shift;  ___x_cmd_pkg_ls_all "$@" ;;
         xbin)             shift;  ___x_cmd_pkg_ls_xbin "$@" ;;
         -h|--help)
-            ___x_cmd_pkg_help ls "$@"
-            return 1
+            M='pkg ls ' help:ret:0
             ;;
         *)                ___x_cmd_pkg_ls___installed "$@" ;;
     esac
 }
 
+___x_cmd_pkg_ls_downloaded(){
+    local X_help_cmd='___x_cmd_pkg_help ls d'
+    help:arg:parse
+    [ -d "$___X_CMD_PKG_DOWNLOAD_PATH" ] || return 0
+    [ "$(x ls "$___X_CMD_PKG_DOWNLOAD_PATH" | wc -l )" -gt 0 ] || return 0
+
+    if [ "$#" -gt 0 ]; then
+        [ -d "$___X_CMD_PKG_DOWNLOAD_PATH/$1" ] || {
+            pkg:error "Not found $1 in your download path"
+            return 1
+        }
+        x ls "$___X_CMD_PKG_DOWNLOAD_PATH/$1"
+    else
+        x ls "$___X_CMD_PKG_DOWNLOAD_PATH"
+    fi
+}
+
+
 ___x_cmd_pkg_ls_xbin(){
+    local X_help_cmd='___x_cmd_pkg_help ls xbin'
+    help:arg:parse
     <"$___X_CMD_PKG_RAW_PATH/binmod.txt" awk -v FS=":" '{ if($2 != ""){ print $2 }}'
 }
 
@@ -23,14 +42,17 @@ ___x_cmd_pkg_ls_xbin(){
 # TODO: efficiency defect
 ___x_cmd_pkg_ls___installed()(
     [ -d "$___X_CMD_PKG_POPULATE_PATH" ] || return 0
-    [ "$(ls "$___X_CMD_PKG_POPULATE_PATH" | wc -l )" -gt 0 ] || return 0
+    [ "$(x ls "$___X_CMD_PKG_POPULATE_PATH" | wc -l )" -gt 0 ] || return 0
     local osarch
     local locate_list
     osarch="$(___x_cmd_pkg_osarch)"
-    locate_list="$(___x_cmd_pkg_ll)"
+    locate_list="$(___x_cmd_pkg_ll_inner)"
     (
         x cd "$___X_CMD_PKG_POPULATE_PATH" || return
         for i in */*; do
+            case "$i" in
+                *bash-preexec*) continue;;
+            esac
             printf "%s\n" "$i";
         done
     ) | awk -v FS="/" \
@@ -45,7 +67,9 @@ ___x_cmd_pkg_ls___installed()(
         -f "$___X_CMD_ROOT_MOD/pkg/lib/awk/pkg.ls.awk"
 )
 
-___x_cmd_pkg_ls_installed(){
+___x_cmd_pkg_ls_populated(){
+    local X_help_cmd='___x_cmd_pkg_help ls i'
+    help:arg:parse
     local name="$1"
     if  [ -n "$name" ]; then
         ___x_cmd_pkg_ls___installed | awk -v name="$name" '
@@ -61,28 +85,31 @@ ___x_cmd_pkg_ls_installed(){
 }
 
 # Invoked pkg ls activated: check environment variable...
-___x_cmd_pkg_ls_activated(){
-    [ -n "$___X_CMD_PKG_ACTIVATE___LIST" ] || return
-    local _line
-    local osarch
-    local locate_list
-    osarch="$(___x_cmd_pkg_osarch)"
-    locate_list="$(___x_cmd_pkg_ll)"
-    awk -v FS="=" \
-        -v OSARCH="$osarch" \
-        -v LOCAL_LIST="$locate_list" \
-        -v PKG_RAWPATH="$___X_CMD_PKG_RAW_PATH" \
-        -v TH_THEME_COLOR="\\033[${___X_CMD_THEME_COLOR_CODE}m" \
-        -f "$___X_CMD_ROOT_MOD/awk/lib/core.awk" \
-        -f "$___X_CMD_ROOT_MOD/awk/lib/j/json.awk" \
-        -f "$___X_CMD_ROOT_MOD/awk/lib/j/jqparse.awk" \
-        -f "$___X_CMD_ROOT_MOD/pkg/lib/awk/util.awk" \
-        -f "$___X_CMD_ROOT_MOD/pkg/lib/awk/pkg.ls.awk" <<A
-${___X_CMD_PKG_ACTIVATE___LIST}
-A
-}
+# ___x_cmd_pkg_ls_activated(){
+#     [ -n "$___X_CMD_PKG_ACTIVATE___LIST" ] || return
+#     local _line
+#     local osarch
+#     local locate_list
+#     osarch="$(___x_cmd_pkg_osarch)"
+#     locate_list="$(___x_cmd_pkg_ll)"
+#     command awk -v FS="=" \
+#         -v OSARCH="$osarch" \
+#         -v LOCAL_LIST="$locate_list" \
+#         -v PKG_RAWPATH="$___X_CMD_PKG_RAW_PATH" \
+#         -v TH_THEME_COLOR="\\033[${___X_CMD_THEME_COLOR_CODE}m" \
+#         -f "$___X_CMD_ROOT_MOD/awk/lib/core.awk" \
+#         -f "$___X_CMD_ROOT_MOD/awk/lib/j/json.awk" \
+#         -f "$___X_CMD_ROOT_MOD/awk/lib/j/jqparse.awk" \
+#         -f "$___X_CMD_ROOT_MOD/pkg/lib/awk/util.awk" \
+#         -f "$___X_CMD_ROOT_MOD/pkg/lib/awk/pkg.ls.awk" <<A
+# ${___X_CMD_PKG_ACTIVATE___LIST}
+# A
+# }
 
 ___x_cmd_pkg_ls_all(){
+    local X_help_cmd='___x_cmd_pkg_help ls all'
+    help:arg:parse
+
     if ! [ -d "$___X_CMD_PKG_RAW_PATH" ]; then return 0; fi
     local pkg_name="${1:?Provide package name}"
     local osarch="${___X_CMD_PKG_OSARCH:-$(___x_cmd_pkg_osarch)}"
@@ -117,6 +144,9 @@ ___x_cmd_pkg_ls___all_candidate()(
         esac
         x cd "$___X_CMD_PKG_RAW_PATH/$dir" || continue
         for candidate in *; do
+            case "$candidate" in
+                bash-preexec) continue ;;
+            esac
             printf "%s\n" $candidate
         done
     done
diff --git a/mod/pkg/lib/main b/mod/pkg/lib/main
--- a/mod/pkg/lib/main
+++ b/mod/pkg/lib/main
@@ -24,51 +24,60 @@
 # }
 
 ___x_cmd_pkg___which_p7zip()(
-    ___x_cmd_mkdirp "$___X_CMD_PKG_RAW_PATH"
     local file_path="$___X_CMD_PKG_BASE_PATH/$___X_CMD_PKG_VERSION.tar.gz"
     local file_hash_path="$___X_CMD_PKG_BASE_PATH/${___X_CMD_PKG_VERSION}_hash.txt"
-    ___x_cmd_httpget_gitx x-cmd pkg main "dist/${___X_CMD_PKG_VERSION}_hash.txt" "$file_hash_path" "${1:-86400}" || {
+    local tmp_file_path="$___X_CMD_PKG_SHARED/$___X_CMD_PKG_VERSION.tar.gz"
+    local tmp_file_hash_path="$___X_CMD_PKG_SHARED/${___X_CMD_PKG_VERSION}_hash.txt"
+    ___x_cmd_httpget_gitx x-cmd pkg main "dist/${___X_CMD_PKG_VERSION}_hash.txt" "$tmp_file_hash_path" "-" || {
         pkg:warn "Please check your network status; Or use 'x websrc set cn' and open a new session to run 'x pkg update'"
         return 1
     }
-    if ! ___x_cmd_httpget_gitx x-cmd pkg main "dist/$___X_CMD_PKG_VERSION.tar.gz" "$file_path" "${1:-86400}"; then # 1-day
-        if [ ! -f "$file_path" ]; then
-            pkg:error "Unaviable $___X_CMD_PKG_VERSION.tar.gz. Unable to fetch $___X_CMD_PKG_VERSION.tar.gz."
-            return 1
-        fi
-        local hash_value
-        hash_value="$( < "$file_hash_path"  awk '{print $1}')"
-        local file_hash
-        file_hash="$(sha512sum "$file_path")"
+    ___x_cmd_httpget_gitx x-cmd pkg main "dist/$___X_CMD_PKG_VERSION.tar.gz" "$tmp_file_path" || { # 1-day
+        pkg:error "Download $___X_CMD_PKG_VERSION.tar.gz failed"
+        return 1
+    }
 
-        [ "$hash_value" = "$file_hash" ] || {
-            pkg:warn "File corrupted; Please check your network status; Or use 'x websrc set cn' and open a new session to run 'x pkg update' "
-        }
+
+    local hash_value
+    local file_hash
+    hash_value="$( < "$tmp_file_hash_path"  command awk '{print $1}')"
+    file_hash="$(x sha512 "$tmp_file_path")"
+
+
+    [ "$hash_value" = "$file_hash" ] || {
+        pkg:error "File corrupted; Please check your network status; Or use 'x websrc set cn' and open a new session to run 'x pkg update' "
+        x rmrf "$tmp_file_path" "$tmp_file_hash_path"
+        return 1
+    }
+
+
+    x rmrf "$___X_CMD_PKG_BASE_PATH/$___X_CMD_PKG_VERSION.tar.gz" && x rmrf "$___X_CMD_PKG_RAW_PATH" && x rmrf "$file_hash_path"
+
+    x cp "$tmp_file_path" "$___X_CMD_PKG_BASE_PATH/$___X_CMD_PKG_VERSION.tar.gz" && x rmrf "$tmp_file_path"
+    x cp "$tmp_file_hash_path" "$file_hash_path" && x rmrf "$tmp_file_path" "$tmp_file_hash_path"
+
+    ___x_cmd_mkdirp "$___X_CMD_PKG_RAW_PATH"
+    pkg:debug "Deflate the $___X_CMD_PKG_VERSION.tar.gz"
+    if ! ( x cd "${file_path%/*}" && x cp "$___X_CMD_PKG_VERSION.tar.gz" raw/"$___X_CMD_PKG_VERSION.tar.gz" && x cd raw && x uz "$___X_CMD_PKG_VERSION.tar.gz" 1>/dev/null && x rmrf "$___X_CMD_PKG_VERSION.tar.gz" ); then
+        pkg:error "Deflation failure."
+        return 1
     fi
-
-    if [ "$___X_CMD_HTTPGET_AGE" = 0 ]; then
-        ___x_cmd_mkdirp "$___X_CMD_PKG_RAW_PATH"
-        pkg:debug "Deflate the $___X_CMD_PKG_VERSION.tar.gz"
-        if ! ( x cd "${file_path%/*}" && x cp "$___X_CMD_PKG_VERSION.tar.gz" raw/"$___X_CMD_PKG_VERSION.tar.gz" && x cd raw && x uz "$___X_CMD_PKG_VERSION.tar.gz" 1>/dev/null && x rmrf "$___X_CMD_PKG_VERSION.tar.gz" ); then
-            pkg:error "Deflation failure."
-            x rmrf "$file_path"
-        fi
-    fi
-
 )
 
 
 ___x_cmd_pkg_update(){
     case "$1" in
         -h|--help)
-            ___x_cmd_pkg_help update #"$@"
-            return 1
+            M='pkg update' help:ret:0
             ;;
     esac
     local file_hash_path="$___X_CMD_PKG_BASE_PATH/${___X_CMD_PKG_VERSION}_hash.txt"
-    x rmrf "$___X_CMD_PKG_BASE_PATH/$___X_CMD_PKG_VERSION.tar.gz" && x rmrf "$___X_CMD_PKG_RAW_PATH" && x rmrf "$file_hash_path"
-    ___x_cmd_pkg___which_p7zip - || return # Force Update
-    pkg:info "Update the $___X_CMD_PKG_VERSION.tar.gz"
+    # x rmrf "$___X_CMD_PKG_BASE_PATH/$___X_CMD_PKG_VERSION.tar.gz" && x rmrf "$___X_CMD_PKG_RAW_PATH" && x rmrf "$file_hash_path"
+    ___x_cmd_pkg___which_p7zip || {
+        pkg:error "Update the $___X_CMD_PKG_VERSION.tar.gz failed"
+        return 1 # Force Update
+    }
+    pkg:info "Update the $___X_CMD_PKG_VERSION.tar.gz success"
 }
 
 ___x_cmd_pkg_help(){
diff --git a/mod/pkg/lib/mutate/download b/mod/pkg/lib/mutate/download
--- a/mod/pkg/lib/mutate/download
+++ b/mod/pkg/lib/mutate/download
@@ -1,37 +1,30 @@
-# shellcheck    shell=dash
+# shellcheck    shell=dash disable=SC2034
 
 # TODO: Multiple thread
 # TODO: Download Manager and more strategy
 # TODO: Maybe using a P2P share connection for mirror downloading.
-
 ___x_cmd_pkg_download(){
     x:trace pkg/download
+    local X_help_cmd='___x_cmd_pkg_help download'
+    help:arg:parse
     case "$1" in
-        -h|--help) ___x_cmd_pkg_help download; return 1 ;;
+        */*)
+            ___x_cmd_pkg___appoint "$@"
+            return
+            ;;
     esac
 
     local name="${1:?Provide pkg name}"
     local osarch="${3:-$(___x_cmd_pkg_osarch)}"
     local version="${2:-$(___x_cmd_pkg_default_version "$name" "$osarch")}" || return
     [ -n "$version" ] || {
-        pkg:error "Not found candidate => $name"
-        pkg:error "Please use 'x pkg ll' or 'x pkg ls all <candidate>' to check available candidate and version"
+        pkg:warn "Not found candidate => $name"
+        pkg:warn "Please use 'x pkg update' and 'x pkg ll' to check available candidate"
         return 1
     }
 
-    local url_list; url_list="$(___x_cmd_pkg___list "$name" "$version" "$osarch" "url.${___X_CMD_WEBSRC_REGION:-internet}" )" || return
-
-    if [ -z "$url_list" ]; then
-        pkg:error "Not found url for $name $version"
-        pkg:error "Please use 'x pkg ll' or 'x pkg ls all <candidate>' to check available candidate and version"
-        return 1
-    fi
-
-
     local download_file_ext; local md5 ; local sha1 ; local sha256; local sha512 ; local unpack
     ___x_cmd_pkg___attr "$name" "$version" "$osarch" "md5,sha1,sha256,sha512,download_file_ext,unpack"
-    local url
-    local head
     local os="${osarch%/*}";  local arch="${osarch#*/}"
     if [ "$unpack" = "none" ] && [ -z "$download_file_ext" ]; then
         local ball="$___X_CMD_PKG_DOWNLOAD_PATH/$name/$name.${os}.${arch}"
@@ -39,44 +32,60 @@ ___x_cmd_pkg_download(){
         local ball="$___X_CMD_PKG_DOWNLOAD_PATH/$name/${version}_${os}_${arch}.$download_file_ext"
     fi
 
-    mkdir -p "$___X_CMD_PKG_DOWNLOAD_PATH/$name" || {
+    x mkdirp "$___X_CMD_PKG_DOWNLOAD_PATH/$name" || {
         pkg:error "Create $___X_CMD_PKG_DOWNLOAD_PATH/$name failed" ; return 1
     }
-    pkg:debug --Download name "$name" --version "$version" --url_list "$url_list" --ball "$ball"
 
+    ( bgsingleton_name="${name}_${version}_${os}_${arch}" x bgsingleton run --wait ___x_cmd_pkg_download___inner_ )
+    [ -f "$ball" ]
+}
+
+___x_cmd_pkg_download___inner_(){
+    pkg:debug --Download name "$name" --version "$version" --url_list "$url_list" --ball "$ball"
     if [ -f "$ball" ]; then
         if ___x_cmd_pkg_download___check_hashsum "$ball" "$md5" "$sha1" "$sha256" "$sha512"; then
-            pkg:debug "File already downloaded: $ball"
+            pkg:info "File already downloaded: $ball"
             return 0
         fi
 
         pkg:warn "File corrupted. Download the $ball again."
         x rmrf "$ball"
     fi
+
+    local url_list; url_list="$(___x_cmd_pkg___list "$name" "$version" "$osarch" "url.${___X_CMD_WEBSRC_REGION:-internet}" )" || return
+    if [ -z "$url_list" ]; then
+        pkg:error "Not found url for $name $version"
+        pkg:error "Please use 'x pkg ll' or 'x pkg ls all <candidate>' to check available candidate and version"
+        return 1
+    fi
+
     (
     while read -r url; do
-        # TODO: ___x_cmd_httpget support 302
-        # ___x_cmd_httpget "$url" "$ball" || {
         pkg:info \
             -m "download $name=$version, thanks to the courtesy of ${url%/"${url#*//*/}"}" \
-            --url "$url" --dest "$ball" --name "$name" --version "$version"
-        # pkg:info "Download $name $version from $url to $ball"
+            --url "$url" --destination "$ball" --name "$name" --version "$version"
         # TODO: x curl
-        trap 'x pkg remove $name $version 2>/dev/null; printf "\r\n";  pkg:error "Download interrupted"; return 1;' INT
-        head=$(curl -I "$url" | awk 'NR==1{ print $2}' )
-        if [ "$head" -eq "200" ] || [ "$head" -eq "304" ] || [ "$head" -eq "302" ] || [ "$head" -eq "301" ]; then
-            if ! curl --progress-bar --location --retry-max-time 10 --retry 0 "$url" --output "$ball"; then
-                pkg:warn "Fail to download from $url"
-                x rmrf "$ball"
-                return 1
-            fi
-        else
-            pkg:error "resource invalid: $url "
-            return 1
-        fi
+        curl -I "$url" | {
+            trap 'x pkg remove $name $version 2>/dev/null; printf "\r\n";  pkg:error "Download interrupted"; return 1;' INT
+            read -r head;
+            head="${head#* }"; head="${head%% *}"
+            case "$head" in
+                2??|3??)
+                    if ! curl --progress-bar --location --retry-max-time 10 --retry 0 "$url" --output "$ball"; then
+                        pkg:warn "Fail to download from $url"
+                        x rmrf "$ball"
+                        return 1
+                    fi
+                    ;;
+                *)
+                    pkg:error "resource invalid: $url "
+                    return 1
+                    ;;
+            esac
+        }
 
         ! ___x_cmd_pkg_download___check_hashsum "$ball" "$md5" "$sha1" "$sha256" "$sha512" || return 0
-        pkg:warn "File corrupted."
+        pkg:error "File corrupted."
         x rmrf "$ball"
         return 1
     done <<A
@@ -98,4 +107,45 @@ ___x_cmd_pkg_download___check_hashsum(){
         return 1
     }
     return 0
+}
+
+
+___x_cmd_pkg___appoint(){
+    local yml_file="${1:?Provide a folder path}"
+    local meta_input="$yml_file/meta.yml"; local meta_output="$yml_file/meta.tt.json"
+    local version_intput="$yml_file/version.yml"; local version_output="$yml_file/version.tt.json"
+    local name="${yml_file##*/}"
+
+    x ccmd --convert "$meta_input" "$meta_output" eval  "___x_cmd_pkg___appoint_handle_data \"\$meta_input\" \"\$meta_output\""
+    x ccmd --convert "$version_intput" "$version_output" eval  "___x_cmd_pkg___appoint_handle_data \"\$version_intput\" \"\$version_output\""
+
+    ___x_cmd_pkg___tmp_move "$yml_file" "$meta_output" "$version_output"
+
+    ___x_cmd_pkg_download "$name" || return
+    ___x_cmd_pkg_populate "$name" || return
+    pkg:info "Download and populate $name successfully"
+}
+
+___x_cmd_pkg___appoint_handle_data(){
+    local input="${1:? Provide a file path}"
+    local output="${2:? Provide a file path}"
+    pkg:debug INPUT_PATH="$input" OUTPUT_PATH="$output"
+
+    < "$input"  x y2j | x ja t "\t" > "$output"
+}
+
+
+___x_cmd_pkg___tmp_move(){
+    local yml_file="$1"
+    local name="${yml_file##*/}"
+    local meta_j_path="$2"
+    local version_j_path="$3"
+    x mkdirp "$___X_CMD_PKG_RAW_PATH/tmp/$name"
+    x cp "$meta_j_path" "$___X_CMD_PKG_RAW_PATH/tmp/$name"
+    x cp "$version_j_path" "$___X_CMD_PKG_RAW_PATH/tmp/$name"
+
+    x mkdirp "$___X_CMD_PKG_RAW_PATH/tmp/$name/.x-cmd"
+    ! [ -d "$yml_file/.x-cmd" ] || x cp "$yml_file/.x-cmd/"* "$___X_CMD_PKG_RAW_PATH/tmp/$name/.x-cmd"
+    x rmrf "$meta_j_path" "$version_j_path"
+
 }
diff --git a/mod/pkg/lib/mutate/populate b/mod/pkg/lib/mutate/populate
--- a/mod/pkg/lib/mutate/populate
+++ b/mod/pkg/lib/mutate/populate
@@ -1,4 +1,4 @@
-# shellcheck shell=dash #xrc
+# shellcheck shell=dash disable=SC2034,1090 #xrc
 
 # This is default
 ___x_cmd_pkg_populate___unzip(){
@@ -15,7 +15,7 @@ ___x_cmd_pkg_populate___unzip(){
         local ball="$___X_CMD_PKG_DOWNLOAD_PATH/$name/${version}_${os}_${arch}.${download_file_ext}"
     fi
     [ -f "$ball" ] || {
-        pkg:error "Cant found zip package: $name $version"
+        pkg:error "Can't found zip package: $name $version"
         return 1
     }
 
@@ -28,13 +28,13 @@ ___x_cmd_pkg_populate___unzip(){
             pkg:error "Fail to unzip $ball" ; return 1
         }
         x rmrf "$tgt"
-        mkdir -p "$tgt"
+        x mkdirp "$tgt"
         pkg:debug "Moving $unpack_dir to $tgt"
         x mv -f "$unpack_dir"/*/* "$tgt"
         x rmrf "$unpack_dir"
     elif [ "$unpack" = "none" ]; then
         local ball="$___X_CMD_PKG_DOWNLOAD_PATH/$name"
-        mkdir -p "$tgt"
+        x mkdirp "$tgt"
         pkg:debug "Moving $ball to $tgt"
         x mv -f "$ball"/* "$tgt"
     elif [ "$unpack" = "file" ]; then
@@ -50,10 +50,8 @@ ___x_cmd_pkg_populate___unzip(){
 }
 
 ___x_cmd_pkg_populate(){
-
-    case "$1" in
-        -h|--help) ___x_cmd_pkg_help populate; return 1 ;;
-    esac
+    local X_help_cmd='___x_cmd_pkg_help populate'
+    help:arg:parse
 
     local name="${1:?Provide pkg name}"
     local osarch="${3:-$(___x_cmd_pkg_osarch)}"
@@ -66,40 +64,45 @@ ___x_cmd_pkg_populate(){
         return 1
     }
 
+    local os="${osarch%/*}";  local arch="${osarch#*/}"
+    ( bgsingleton_name="${name}_${version}_${os}_${arch}" x bgsingleton run --wait ___x_cmd_pkg_populate___inner_ )
+    [ -d "$tgt" ]
+}
+___x_cmd_pkg_populate___inner_(){
     ___x_cmd_pkg_populate___unzip "$name" "$version" "$osarch" "$tgt" || {
         pkg:error "unzip $name $version $osarch failed"
+        x rmrf "$tgt"
         return 1
     }
 
     local script_path
     if ! script_path="$(___x_cmd_pkg___get_script_path "$name" "$version" "$osarch" populate)"; then
-        pkg:error "Cant not get script path"
+        pkg:error "Can't get script path"
+        x rmrf "$tgt"
         return 1
     fi
 
-    if [ -z "$script_path" ]; then
-        ___x_cmd_pkg_populate___chmod "$name" "$version" "$osarch" "$tgt"
-        return
+    if [ -n "$script_path" ]; then
+        pkg:info "Running $script_path"
+        pkg:debug --name "$name"  --version "$version"  --osarch "$osarch" --script_path "$script_path"
+
+        local ___X_CMD_PKG___META_NAME="$name"
+        local ___X_CMD_PKG___META_VERSION="$version"
+        local ___X_CMD_PKG___META_OS="${osarch%%/*}"
+        local ___X_CMD_PKG___META_ARCH="${osarch##*/}"
+        local ___X_CMD_PKG___META_TGT="$tgt"
+        {
+            {
+                trap 'printf "\r\n"; pkg:error "populate interrupted script"; return 130' INT
+                . "$script_path"
+            } || {
+                x rmrf "$tgt"
+                pkg:error "Source $script_path failed"
+                return 1
+            }
+        }
     fi
 
-    pkg:info "Running $script_path"
-    pkg:debug --name "$name"  --version "$version"  --osarch "$osarch" --script_path "$script_path"
-
-    local ___X_CMD_PKG___META_NAME="$name"
-    local ___X_CMD_PKG___META_VERSION="$version"
-    local ___X_CMD_PKG___META_OS="${osarch%%/*}"
-    local ___X_CMD_PKG___META_ARCH="${osarch##*/}"
-    local ___X_CMD_PKG___META_TGT="$tgt"
-    {
-        (
-            trap 'printf "\r\n"; pkg:error "populate interrupted"; return' INT
-            . "$script_path"
-        ) || {
-            x rmrf "$tgt"
-            pkg:error "Source $script_path failed"
-            return 1
-        }
-    }
     ___x_cmd_pkg_populate___chmod "$name" "$version" "$osarch" "$tgt" || return 1
 }
 
@@ -108,18 +111,21 @@ ___x_cmd_pkg_populate___chmod(){
     local version="${2:?Provide version}"
     local osarch="${3:-$(___x_cmd_pkg_osarch)}"
     local tgt="${4:-"$___X_CMD_PKG_POPULATE_PATH/$name/$version"}"
-    local xbin_list; xbin_list="$( < "$___X_CMD_PKG_RAW_PATH/binmod.txt" awk -v name=$name '{if($0 ~ ".*:"name"$"){print $0}}' )"
+    local bin_path
 
-    printf "%s\n" "$xbin_list" | while read -r xbin_name; do
+    local xbin_name; while read -r xbin_name; do
         [ -n "$xbin_name" ] || continue
-        xbin_name="${xbin_name#:*}"
+        [ "${xbin_name##*:}" = "$name" ] || continue
+        xbin_name="${xbin_name#*:}"
         xbin_name="${xbin_name%:*}"
+
         bin_path="$(___x_cmd_pkg_xbin_path "$xbin_name" "$version" "$osarch")"
         if  [ -f "$bin_path" ]; then
             chmod +x "$bin_path" || {
                 pkg:error "Can't use chmod on $bin_path"
+                x rmrf "$tgt"
                 return 1
             }
         fi
-    done
+    done < "$___X_CMD_PKG_RAW_PATH/binmod.txt"
 }
diff --git a/mod/pkg/lib/mutate/unlink b/mod/pkg/lib/mutate/unlink
--- a/mod/pkg/lib/mutate/unlink
+++ b/mod/pkg/lib/mutate/unlink
@@ -1,8 +1,7 @@
-# shellcheck    shell=dash
+# shellcheck    shell=dash disable=SC2034
 ___x_cmd_pkg_unlink(){
-    case "$1" in
-        -h|--help) ___x_cmd_pkg_help link; return 1 ;;
-    esac
+    local X_help_cmd='___x_cmd_pkg_help unlink'
+    help:arg:parse
 
     local name="${1:?Provide pkg name}"
     local version="${2:-$(___x_cmd_pkg_default_version "$name")}"
@@ -19,14 +18,18 @@ ___x_cmd_pkg_unlink(){
             pkg:info "Don't need to unlink"
             return 0
         fi
-
+        local source
+        local binlink
         while read -r binlink; do
             if [ -z "$binlink" ];then
                 continue
             fi
 
-            bin_name_list="$(ls "${tgt}/$binlink")"
-
+            bin_name_list="$(x ls "${tgt}/$binlink" 2>/dev/null )"
+            [ -n "$bin_name_list" ] || {
+                pkg:error "Cannot unlink $name $version"
+                return 1
+            }
             printf "%s\n" "$bin_name_list" | while read -r source; do
                 soft_bin_path="$dir_path/${source}"
                 if ! [ -f "$soft_bin_path" ] ; then
@@ -47,6 +50,7 @@ A
             pkg:debug "Unlink bin is not exist"
             return 0
         fi
+        local binlink_dir ; local binlink
         while read -r binlink_dir; do
             if [ -z "$binlink_dir" ];then
                 continue
@@ -57,7 +61,7 @@ A
                 pkg:error "Not found bin link($abs_bin_path) for $name $version"
                 return 1
             fi
-            binary_name=$(ls "$abs_bin_path")
+            binary_name=$(x ls "$abs_bin_path")
             while read -r binlink; do
 
                 x rmrf "$dir_path/$binlink" 2>/dev/null || {
diff --git a/mod/tldr/lib/download b/mod/tldr/lib/download
--- a/mod/tldr/lib/download
+++ b/mod/tldr/lib/download
@@ -1,80 +1,89 @@
-# shellcheck shell=dash
+# shellcheck shell=dash disable=2120
 
-# Section: current and download
+## Section: version、update and download
 
-___x_cmd_tldr_current_or_update_(){
-    x_tldr_version="${___X_CMD_TLDR_VERSION:-"$(___x_cmd_tldr_version)"}"
-    if [ -n "$x_tldr_version" ]; then
-        ___X_CMD_TLDR_VERSION="$x_tldr_version"
-    elif ___x_cmd_tldr_update; then
-        x_tldr_version="$___X_CMD_TLDR_VERSION"
-    else
-        ___X_CMD_TLDR_VERSION=
-        tldr:error "Fail to show version for tldr pages"
-        return 1
-    fi
-}
-
-___x_cmd_tldr_current_or_update(){
-    local x_tldr_version
-    ___x_cmd_tldr_current_or_update_
-    [ -n "$x_tldr_version" ] || return 1
-    printf "%s\n" "$x_tldr_version"
-}
-
-___x_cmd_tldr_version___from_yml(){
-    arg:init tldr
-    [ -f "$1" ] || M="Please provide the tldr version index yml" arg:ret:64
-    < "$1" awk '
-($2 !~ /v[0-9]+\.[0-9]+(\.[0-9])?/) { exit(1); }
-{print($2); exit(0);}
-'
-}
-
+___X_CMD_TLDR_LANG_VERSION="v0.0.1"
 ___x_cmd_tldr_version(){
-    local index="$___X_CMD_TLDR_TMP_DATA/index.yml"
-    [ -f "$index" ] || return 1
+    ___x_cmd_tldr_version_pages_ "$@" || return
+    printf "paegs:\t%s\n" "$___X_CMD_TLDR_PAGES_VERSION"
+    printf "lang:\t%s\n" "$___X_CMD_TLDR_LANG_VERSION"
+}
 
-    ___x_cmd_tldr_version___from_yml "$index" || {
-        tldr:error --version "$(awk '{print $2; exit(1); }' <"$index")" "Latest version in index.yml is invalid"
+___x_cmd_tldr_version_pages_(){
+    [ -n "$___X_CMD_TLDR_PAGES_VERSION" ] || {
+        local x_;   ___x_cmd_tldr_version_pages___from_yml_ || return
+        ___X_CMD_TLDR_PAGES_VERSION="$x_"
+    }
+}
+
+___x_cmd_tldr_version_pages___from_yml_(){
+    local index="$___X_CMD_TLDR_TMP_DATA/index.yml"
+    { [ -f "$index" ] && [ "$1" != --update ]; } || \
+        bgsingleton_name="bg.tldr.index" x bgsingleton run --wait ___x_cmd_tldr_download index.yml "$index" || return
+    read -r x_ < "$index"
+    x_="${x_#* }"
+    [ -n "$x_" ] || {
+        tldr:error "Latest version in index.yml is invalid"
         return 1
     }
 }
 
 ___x_cmd_tldr_update(){
-    ___x_cmd___tldr_download index.yml "$___X_CMD_TLDR_TMP_DATA/index.yml" - || return
-    ___X_CMD_TLDR_VERSION="$(___x_cmd_tldr_version)"
-    ___x_cmd___tldr_download_pages "$___X_CMD_TLDR_VERSION" pages
+    local lang="${1:-$___X_CMD_TLDR_LANG_PREFERED}"
+    local x_;   ___x_cmd_tldr_version_pages___from_yml_ --update    || return
+    ___x_cmd_tldr_download_unzip_pages "$x_" "$lang" --update       || return
+    ___x_cmd_tldr_download_unzip_lang "$___X_CMD_TLDR_LANG_VERSION" --update
 }
 
-___x_cmd___tldr_download_pages(){
-    arg:init tldr
-    [ -n "$1" ] || M="Please provide the tldr version" arg:ret:64
-    [ -n "$2" ] || M="Please provide the tldr pages" arg:ret:64
+___x_cmd_tldr_lang_perpare(){
+    [ -d "${___X_CMD_TLDR_TMP_DATA}/lang/${___X_CMD_TLDR_LANG_VERSION}" ] || \
+        bgsingleton_name="bg.tldr.lang" x bgsingleton run --wait ___x_cmd_tldr_download_unzip_lang "$___X_CMD_TLDR_LANG_VERSION" || return
+}
 
+___x_cmd_tldr_pages_prepare(){
+    local lang="${1:-en}"
+    ___x_cmd_tldr_version_pages_ || return
+    [ -d "${___X_CMD_TLDR_TMP_DATA}/${___X_CMD_TLDR_PAGES_VERSION}/pages.${lang}" ] || \
+        bgsingleton_name="bg.tldr.pages.${lang}" x bgsingleton run --wait ___x_cmd_tldr_download_unzip_pages "$___X_CMD_TLDR_PAGES_VERSION" "$lang" || return
+}
+
+___x_cmd_tldr_download_unzip_lang(){
     local version="$1"
-    local page_lang="$2"
-    local data_path="$___X_CMD_TLDR_TMP_DATA/$version/$page_lang"
-    local tgz_path="$___X_CMD_TLDR_TMP_CACHE/$version/$page_lang.tgz"
-    x mkdirp "$data_path"
-
-    ___x_cmd___tldr_download "$version/$page_lang.tgz" "$tgz_path" "0" || {
-        x rmrf "$data_path"
-        return 1
+    local tgz_path="${___X_CMD_TLDR_TMP_CACHE}/lang/${version}.tar.xz"
+    { [ -f "$tgz_path" ] && [ "$2" != --update ]; } || {
+        ___x_cmd_tldr_download "lang/${version}.tar.xz" "$tgz_path" || return
     }
-    ! x uz "$tgz_path" "$data_path" || tldr:info "Version already UPDATED to $version"
+
+    local data_path="${___X_CMD_TLDR_TMP_DATA}/lang/${version}"
+    x rmrf "$data_path";    x mkdirp "$data_path"
+    ! x uz "$tgz_path" "$data_path" || tldr:info "The lang/${version} already UPDATED"
 }
 
-___x_cmd___tldr_download(){
+___x_cmd_tldr_download_unzip_pages(){
+    local version="$1";     local lang="$2"
+    local tgz_path="${___X_CMD_TLDR_TMP_CACHE}/${version}/pages.${lang}.tgz"
+
+    { [ -f "$tgz_path" ] && [ "$3" != --update ]; } || {
+        local page_lang="pages"; [ "$lang" = en ] || page_lang="pages.${lang}"
+        ___x_cmd_tldr_download "$version/$page_lang.tgz" "$tgz_path" || return
+    }
+
+    local data_path="${___X_CMD_TLDR_TMP_DATA}/${version}/pages.${lang}"
+    x rmrf "$data_path";    x mkdirp "$data_path"
+    ! x uz "$tgz_path" "$data_path" || tldr:info "The pages.${lang} version already UPDATED to $version"
+}
+
+___x_cmd_tldr_download(){
     arg:1:nonempty
-    local src="$1"
-    local dst="${2:-$1}"
-    local expiration="${3:-"1"}"
+    local src="$1";     local dst="${2:-$1}"
     tldr:info "Download tldr $src from x-cmd/tldr"
-    ___x_cmd_httpget_gitx x-cmd tldr main "dist/$src" "$dst" "$expiration" || {
+    ___x_cmd_httpget_gitx x-cmd tldr main "dist/$src" "${dst}.tmp" - || {
         tldr:error "Fail to download $src from x-cmd/tldr"
+        x rmrf "${dst}.tmp"
         return 1
     }
+    x rmrf "${dst}"
+    x mv "${dst}.tmp" "${dst}"
 }
 
 ## EndSection
