...

diff --git a/mod/solo/lib/parse b/mod/solo/lib/parse
--- a/mod/solo/lib/parse
+++ b/mod/solo/lib/parse
@@ -2,20 +2,25 @@
 
 # x-cmd.engine:
 # x-cmd.setup:
+# x-cmd.mode:
 # x-cmd.end:
 
 ___x_cmd_solo___parse(){
     local x_engine
     local x_setup
+    local x_mode
 
-    ___x_cmd_solo___parse_ "$1"
+    ___x_cmd_solo___parse_ "$1" || return
     printf "engine: %s\n" "$x_engine"
     printf "setup: %s\n"  "$x_setup"
+    printf "mode: %s\n"   "$x_mode"
 }
 
 ___x_cmd_solo___parse_(){
     x_engine=
     x_setup=
+    x_mode=
+    x_dependency=
     local filepath="$1"; shift
 
     local line; local i=0;
@@ -23,7 +28,7 @@ ___x_cmd_solo___parse_(){
         i=$((i+1)); [ "$i" -lt 10 ] || break
         case "$line" in
             *x-cmd.*:*)
-                ___x_cmd_solo___parse_main_  <<A
+                { ___x_cmd_solo___parse_main_ || return ;} <<A
 $line
 $(cat)
 A
@@ -43,27 +48,29 @@ ___x_cmd_solo___parse_main_(){
             *x-cmd.engine:*)
                 x_engine=${line##*:*" "}
                 x_engine=${x_engine%%" "*}
-                solo:debug "engine=$x_engine"
                 case "${x_engine}" in
                     python|node|ts-node|java|kotlin|groovy|r|julia|ruby|perl)
                         ;;
                     *)
-                        x:error "Engine not found ==> $x_engine"
+                        solo:error "Engine not found ==> $x_engine"
                         return 1
                 esac
                 ;;
             *x-cmd.mode*:*)
-                case "${line#*:}" in
+                x_mode=${line#*:*" "}
+                x_mode=${x_mode%%" "*}
+                case "${x_mode}" in
                     inplace|ws)
                         ;;
                     *)
-                        x:error "Mode not found ==> ${line#*:}"
+                        solo:error "Mode not found ==> ${x_mode}"
                         return 1
                 esac
                 ;;
             *x-cmd.setup*:*)
                 line="${line#*:}"
                 x_setup="${x_setup}${line}${___X_CMD_UNSEENCHAR_NEWLINE}"
+
                 solo:debug "setup=$line"
                 # Put the code into a seperate directory
                 ;;
