...

diff --git a/mod/hub/lib/util/curl b/mod/hub/lib/util/curl
--- a/mod/hub/lib/util/curl
+++ b/mod/hub/lib/util/curl
@@ -1,7 +1,7 @@
 # shellcheck shell=dash
 
 ___X_CMD_HUB_SERVICE_URL="https://hub.x-cmd.com"
-___x_cmd_hub___util_curl() (
+___x_cmd_hub___util_curl_v0()(
     local method="${1:?Provide method}"
     local url_path="${2:?Provide url_path}"; shift 2
 
@@ -26,7 +26,7 @@ ___x_cmd_hub___util_curl() (
     }
 )
 
-___x_cmd_hub___util_curl_v2()(
+___x_cmd_hub___util_curl()(
     local method="${1:?Provide method}"
     local url_path="${2:?Provide url_path}"; shift 2
     local resp_path="$___X_CMD_HUB_TMP/resp.$$.out"
@@ -148,5 +148,29 @@ ___x_cmd_hub___util_send_file() {
     case "$http_code" in
         2*) return 0 ;;
         *)  hub:error "Failed to upload file=${key_path}, http_code=$http_code" ; return 1 ;;
+    esac
+}
+
+___x_cmd_hub___util_send_enc_file() {
+    local localfp="${1:?Provide local file}"
+    local respath="${2:?Provide respath}"
+    local filekey_enc_path="${3:?Provide filekey_enc_path}"
+    local force="${4}"
+
+    local token; token="$(___x_cmd_hub___util_get_token)" || return 1
+    local cmd; cmd="x curl -sS \
+        -H 'Encryption-filekey-base64: $(< "$filekey_enc_path" base64)' \
+        -X PUT -o '$___X_CMD_HUB_TMP/resp.$$.out' -w '%{http_code}' \
+        -F 'file=@$localfp' \
+        '$___X_CMD_HUB_SERVICE_URL/api/v0/file/enc?token=${token}&res=${respath}&${force}'"
+
+    hub:debug "Exec cmd: $cmd"
+    local http_code; http_code="$(eval "$cmd")" || return 1
+    command cat "$___X_CMD_HUB_TMP/resp.$$.out"
+
+    case "$http_code" in
+        2*) return 0 ;;
+        *)  #hub:error "Failed to upload file, http_code=$http_code" ;
+            return 1 ;;
     esac
 }
