...

diff --git a/mod/hub/lib/util/index b/mod/hub/lib/util/index
--- a/mod/hub/lib/util/index
+++ b/mod/hub/lib/util/index
@@ -38,6 +38,24 @@ ___x_cmd_hub___help(){
     return 1
 }
 
+___x_cmd_hub___util_st_tab(){
+    if ! ___x_cmd_is_interative_tty || [ ! -t 1 ]; then
+        x csv static_tab
+    else
+        x csv static_tab "$@"
+    fi
+}
+
+___x_cmd_hub___util_read_password_(){
+    local password
+    printf "%s" "$1"
+    stty -echo
+    read -r password
+    stty echo
+    printf "\n"
+    x_="$password"
+}
+
 # Section: encrypt
 
 # from aaa.sh to aaa.sh.enc
@@ -71,13 +89,12 @@ ___x_cmd_hub___util_decrypt(){
 # Section: curl
 
 ___X_CMD_HUB_SERVICE_URL="https://hub.x-cmd.com"
-___x_cmd_hub___util_curl() {
+___x_cmd_hub___util_curl() (
     local method="${1:?Provide method}"
     local url_path="${2:?Provide url_path}"; shift 2
 
     [ -n "$NO_AUTH" ] || {
-        # TODO: use cfgy to get token
-        local token; ___x_cmd_hub_current token:=
+        local token; ___x_cmd_hub_cur token:=
         [ -n "$token" ] || return 1
         ___x_cmd_http header put Authorization "$token"
     }
@@ -96,6 +113,90 @@ ___x_cmd_hub___util_curl() {
         printf "%s\n" "$(___x_cmd_http resp body)"
         return 1
     }
+)
+
+# ___x_cmd_hub___util_curl_v2 get "/api/v0/key/default" type=public
+___x_cmd_hub___util_curl_v2()(
+    local method="${1:?Provide method}"
+    local url_path="${2:?Provide url_path}"; shift 2
+    local resp_path="$___X_CMD_HUB_TMP/resp.$$.out"
+    x rmrf "$resp_path"
+
+    local header=""
+    [ -n "$NO_AUTH" ] || {
+        local token; ___x_cmd_hub_cur token:=
+        [ -n "$token" ] || return 1
+        header='-H "Authorization: '"$token"'"'
+    }
+
+    hub:debug "Command " "$url_path" "$@"
+    local cmd
+    case "$method" in
+        get)
+            local x_; ___x_cmd_hub___util_curl_handle_query_ "$@"
+            local query; query="$x_"
+            cmd="x curl -sS -X GET -o '$resp_path' -w '%{http_code}' \
+                $header \
+                '$___X_CMD_HUB_SERVICE_URL$url_path$query'" ;;
+        put)
+            local x_; ___x_cmd_hub___util_curl_handle_body_ "$@"
+            local body; body="$x_"
+            cmd="x curl -sS -X PUT -o '$resp_path' -w '%{http_code}' \
+                $header \
+                -H 'Content-Type: application/json' \
+                -d '$body' \
+                '$___X_CMD_HUB_SERVICE_URL$url_path'" ;;
+        *)      hub:error "Unknown method: $method" ;;
+    esac
+
+    hub:debug "Exec cmd: $cmd"
+    local http_code; http_code="$(eval "$cmd")" || return 1
+    command cat "$resp_path"
+
+    case "$http_code" in
+        2*)  return 0 ;;
+        404) return 4 ;;
+        *)   return 1 ;;
+    esac
+)
+
+# "$@" is type=public aa=nnn dd=eee
+___x_cmd_hub___util_curl_handle_query_(){
+    x_=""
+    for arg in "$@"; do
+        x_="${x_}&$arg"
+    done
+    [ -z "$x_" ] || x_="?${x_#&}"
+}
+
+# "$@" is type=public aa=nnn dd=eee
+___x_cmd_hub___util_curl_handle_body_(){
+    x_=""
+    for arg in "$@"; do
+        x_="${x_},\"${arg%%=*}\":\"${arg#*=}\""
+    done
+    [ -z "$x_" ] || x_="{${x_#?}}"
+}
+
+___x_cmd_hub___util_send_reskey() {
+    local key_path="${1:?key_path is required}"
+    local type="${2:?type is required}"
+    local name="${3:?name is required}"
+
+    local token; token="$(___x_cmd_hub___util_get_token)" || return 1
+    local cmd; cmd="x curl -sS \
+        -X POST -o '$___X_CMD_HUB_TMP/resp.$$.out' -w '%{http_code}' \
+        -F 'file=@$key_path' \
+        '$___X_CMD_HUB_SERVICE_URL/api/v0/key?token=${token}&type=${type}&name=${name}'"
+
+    hub:debug "Exec cmd: $cmd"
+    local http_code; http_code="$(eval "$cmd")" || return 1
+    command cat "$___X_CMD_HUB_TMP/resp.$$.out"
+
+    case "$http_code" in
+        2*) return 0 ;;
+        *)  hub:error "Failed to upload file=${key_path}, http_code=$http_code" ; return 1 ;;
+    esac
 }
 
 ___x_cmd_hub___util_send_file() {
@@ -103,19 +204,20 @@ ___x_cmd_hub___util_send_file() {
     local respath="${2:?Provide respath}"
 
     local token; token="$(___x_cmd_hub___util_get_token)" || return 1
-    local cmd; cmd="curl -sS -X PUT -F 'file=@$localfp' '$___X_CMD_HUB_SERVICE_URL/api/v0/file?token=${token}&res=${respath}'"
+    local cmd; cmd="curl -sS -X PUT \
+        -X PUT -o '$___X_CMD_HUB_TMP/resp.$$.out' -w '%{http_code}' \
+        -F 'file=@$localfp' \
+        '$___X_CMD_HUB_SERVICE_URL/api/v0/file?token=${token}&res=${respath}'"
     # TODO: when http return error code, curl will not return error code
-    eval "$cmd" || {  hub:debug "Exec cmd: $cmd" ; return 1 ;}
-}
 
-___x_cmd_hub___util_send_archive() {
-    local localfp="${1:?Provide local file}"
-    local respath="${2:?Provide respath}"
+    hub:debug "Exec cmd: $cmd"
+    local http_code; http_code="$(eval "$cmd")" || return 1
+    command cat "$___X_CMD_HUB_TMP/resp.$$.out"
 
-    local token; token="$(___x_cmd_hub___util_get_token)" || return 1
-    local cmd; cmd="curl -sS -X PUT -F 'file=@$localfp' '$___X_CMD_HUB_SERVICE_URL/api/v0/file/archive?token=${token}&res=${respath}'"
-    # TODO: when http return error code, curl will not return error code
-    eval "$cmd" || {  hub:debug "Exec cmd: $cmd" ; return 1 ;}
+    case "$http_code" in
+        2*) return 0 ;;
+        *)  hub:error "Failed to upload file=${key_path}, http_code=$http_code" ; return 1 ;;
+    esac
 }
 
 #EndSection
@@ -167,7 +269,7 @@ ___x_cmd_hub___util_percent(){
 # Section: token_generate
 
 ___x_cmd_hub___util_get_token(){
-    local token; token=$(___x_cmd_hub_cfg get token)
+    local token; token=$(___x_cmd_hub_cfg --get token)
     if [ ! "$token" ]; then
         ___x_cmd_ui_tf false "Token is empty, please 'x hub login' first:" >&2
         return 1
@@ -178,8 +280,14 @@ ___x_cmd_hub___util_get_token(){
 ___x_cmd_hub___util_save_token_with_ui(){
     local token="${1}"
     if ___x_cmd_hub_get_userinfo_by_token "${token}" ; then
+        if [ -n "$(___x_cmd_hub_cfg --get token)" ]; then
+            hub:info "You have already login, will logout first"
+            ___x_cmd_hub_account_logout
+        fi
         ___x_cmd_hub_cfg token="${token}"
         ___x_cmd_hub___util_handle_resp true "" "Save token to config file"
+        local x_; ___x_cmd_hub_key___ensure_key_ default private || return 1
+        hub:info "Login success"
     else
         ___x_cmd_ui_tf false "Failed" >&2
         return 1
