Updating main branch using x7 release -> be03713e530f1ec1fd1443c4d0e32ef2280e765c

diff --git a/mod/docker/lib/ext/refit b/mod/docker/lib/ext/refit
--- a/mod/docker/lib/ext/refit
+++ b/mod/docker/lib/ext/refit
@@ -8,15 +8,130 @@
 
 # x docker refit ubuntu ubuntu-x dev.init.sh
 
-___x_cmd_docker_refit(){
-    local baseimage="$1"
-    local newimage="$2"
-    local script="$3"
+# x docker refit --code
+#    RUN \
+#    --mount=target=/var/lib/apt/lists,type=cache,sharing=locked \
+#    --mount=target=/var/cache/apt,type=cache,sharing=locked \
+#    rm -f /etc/apt/apt.conf.d/docker-clean \
+#    && apt-get update \
+#    && apt-get -y --no-install-recommends install \
+#        ruby ruby-dev gcc
 
-    case "$script" in
-        --)     shift 3 ;;
-        *)      [ -f "$script" ] || N=docker M="Unexisted script -> $script" log:ret:64 ;;
+# x docker refit --apk 'gcc'
+# x docker refit --apt
+# x docker refit --dnf
+
+___x_cmd_docker_refit_dockerfile(){
+    :
+}
+
+___x_cmd_docker_refit_new(){
+
+
+    local dockerfile_content=$(
+        ___x_cmd_docker_refit_dockerfile ""
+    )
+
+    local dockerfile_fp=""
+    printf "%s\n" "dockerfile_content" >"$dockerfile_fp"
+
+    (
+        cd ""
+        docker build -t ...
+    )
+
+
+}
+
+# x docker refit --from <newimage> --to <newimage>
+# x docker refit --from <newimage> --to <newimage> --cmd apk add
+
+# x docker refit --from <newimage> file
+
+# <newimage> -> default is alpine or ubuntu or kali
+# <toimage>  -> default is x-alpine-apk
+
+___x_cmd_docker_refit(){
+    [ "$#" -gt 0 ] || set - --help
+    case "$1" in
+        -h|--help)  ___x_cmd help -m docker refit; return ;;
     esac
+
+    local debug=""
+
+    local baseimage=""
+    local newimage=""
+
+    local apk=""
+    local apt=""
+    local yum=""
+    local dnf=""
+    local nix=""
+    local pacman=""
+
+    local go=""
+    local cargo=""
+    local zig=""
+
+    local npm=""
+    local deno=""
+    local bun=""
+
+    local pip=""
+    local pixi=""
+    local xenv=""
+
+    local ep=""
+    local cmd=""
+    local workdir=""
+
+    local userabc=""
+    local script=""
+
+    arg:init docker
+    while [ $# -gt 0 ]; do
+        case "$1" in
+            --debug)    debug=1;        shift 1 ;;
+
+            --from)     baseimage="$2"; arg:2:shift  ;;
+            --to)       newimage="$2";  arg:2:shift  ;;
+
+            --apk)      apk="$2";       arg:2:shift  ;;
+            --apt)      apt="$2";       arg:2:shift  ;;
+            --yum)      yum="$2";       arg:2:shift  ;;
+            --dnf)      dnf="$2";       arg:2:shift  ;;
+
+            --pacman)   pacman="$2";    arg:2:shift  ;;
+
+            --go)       go="$2";        arg:2:shift  ;;
+            --cargo)    cargo="$2";     arg:2:shift  ;;
+            --zig)      zig="$2";       arg:2:shift  ;;
+
+            --npm)      npm="$2";       arg:2:shift  ;;
+            --deno)     deno="$2";      arg:2:shift  ;;
+            --bun)      bun="$2";       arg:2:shift  ;;
+
+            --pip)      pip="$2";       arg:2:shift  ;;
+
+            --pixi)     pixi="$2";      arg:2:shift  ;;
+            --xenv)     xenv="$2";      arg:2:shift  ;;
+            # --pkgx)     pkgx="$2";      arg:2:shift  ;;  # TODO
+            # --xenv)     xenv="$2";      arg:2:shift  ;;  # TODO
+
+            --userabc)  userabc=1;      shift ;;
+            --workdir)  workdir="$2";   arg:2:shift  ;;
+
+            --ep)       ep="$2";        arg:2:shift  ;;
+            --cmd)      cmd="$2";       arg:2:shift  ;;
+
+            --script)   script="$2";    arg:2:shift  ;;
+
+            *)          break ;;
+        esac
+    done
+
+    [ -n "$baseimage" ] || baseimage="alpine:latest"
+    [ -n "$newimage" ]  || N=docker M="Please from the name of new image after --to" log:ret:64
 
     ___x_cmd_docker mirror pull --noupdate "$baseimage" || {
         local errcode="$?"
@@ -26,23 +141,104 @@ ___x_cmd_docker_refit(){
         esac
     }
 
+    ___x_cmd docker cmdinfo update "$baseimage"
+            [ -z "$bun" ]           || xenv="$xenv bun"
+
+            if ___x_cmd docker cmdinfo hascmd "$baseimage" apk; then
+                [ -z "$go" ]        || apk="$apk go"
+                [ -z "$cargo" ]     || apk="$apk cargo"
+
+                [ -z "$npm" ]       || apk="$apk npm"
+                [ -z "$deno" ]      || apk="$apk deno"
+
+                [ -z "$pip" ]       || apk="$apk py3-pip"
+                # [ -z "$pixi" ]      || apk="$apk python3"
+            elif ___x_cmd docker cmdinfo hascmd "$baseimage" apt; then
+                [ -z "$go" ]        || apt="$apt go"
+                [ -z "$cargo" ]     || apt="$apt cargo"
+
+                [ -z "$npm" ]       || apt="$apt npm"
+                [ -z "$deno" ]      || apt="$apt deno"
+
+                [ -z "$pip" ]       || apt="$apt python3"
+                # [ -z "$pixi" ]      || apk="$apk python3"
+            elif ___x_cmd docker cmdinfo hascmd "$baseimage" dnf; then
+                [ -z "$go" ]        || dnf="$dnf go"
+                [ -z "$cargo" ]     || dnf="$dnf cargo"
+
+                [ -z "$npm" ]       || dnf="$dnf npm"
+                [ -z "$deno" ]      || apk="$dnf deno"
+
+                [ -z "$pip" ]       || dnf="$dnf python3"
+                # [ -z "$pixi" ]      || apk="$apk python3"
+            fi
+
+
     local dir="$PWD/.x-cmd.docker.refit.ws.$$"
     ___x_cmd mkdirp "$dir"
     (
         ___x_cmd_cmds_cd "$dir"
+        ___x_cmd_cmds cp "$___X_CMD_ROOT_MOD/docker/lib/refit"/* ./
+
         {
-            printf "FROM %s\n" "$baseimage"
-            if [ "$script" != -- ]; then
+            ___x_cmd_docker_refit_code_from             "$baseimage"
+
+            ___x_cmd_docker_refit_code_user_workdir     root    /root
+            local USHO=/root
+
+            # Using x-cmd injection ...
+            printf "RUN %s\n" "sh -c '[ -d /root/.x-cmd.root ] || eval \"\$(wget -O- https://get.x-cmd.com)\"'"
+
+            [ -z "$userabc" ]       || ___x_cmd_docker_refit_code_adduser   abc abc     1000
+
+            local xcmd="/root/.x-cmd.root/bin/___x_cmdexe"
+
+            [ -z "$apk" ]   ||        ___x_cmd_docker_refit_code_run_apk    "$USHO" "$apk"
+            [ -z "$apt" ]   ||        ___x_cmd_docker_refit_code_run_apt    "$USHO" "$apt"
+            [ -z "$dnf" ]   ||        ___x_cmd_docker_refit_code_run      "--mount=type=cache,target=/var/cache/dnf dnf install -y $dnf"
+            [ -z "$yum" ]   ||        ___x_cmd_docker_refit_code_run      "--mount=type=cache,target=/var/cache/yum yum install -y $yum"
+
+            ___x_cmd_docker_refit_code_addexe       ./xbin.sh                   /bin/xbin.sh
+            ___x_cmd_docker_refit_code_addexe       ./foreversleep.sh           /bin/foreversleep.sh
+
+            [ -n "$ep" ]    ||  ep="[ \"/bin/xbin.sh\" ]"
+
+            if [ -n "$script" ]; then
                 ___x_cmd_cmds cp "$script" "$dir"
-                printf "ADD %s /refit/script\n" "${script##*/}"
-                printf "RUN /bin/sh -i /refit/script\n"
-            else
-                printf "RUN %s\n" "$@"
+                ___x_cmd_docker_refit_code_add      /refit/script               "${script##*/}"
+                ___x_cmd_docker_refit_code_run      '/bin/sh -i /refit/script'
             fi
-        } > Dockerfile
+
+            [ -z "$userabc" ]       || {
+                ___x_cmd_docker_refit_code_user_workdir     abc     /home/abc
+                USHO=/home/abc
+                ___x_cmd_docker_refit_code_run  "sh -c '[ -d ${USHO}/.x-cmd.root ] || eval \"\$(wget -O- https://get.x-cmd.com)\"'"
+            }
+
+            [ -z "$xenv" ]      ||          ___x_cmd_docker_refit_code_run_xenv     "$USHO"     "$xenv"
+            [ -z "$pixi" ]      ||          ___x_cmd_docker_refit_code_run_pixi     "$USHO"     "$pip"
+
+            # Consider introducing go image
+            [ -z "$go" ]        ||          ___x_cmd_docker_refit_code_run_go       "$USHO"     "$go"
+            [ -z "$cargo" ]     ||          ___x_cmd_docker_refit_code_run_cargo    "$USHO"     "$cargo"
+            # [ -z "$zig" ]   ||          ___x_cmd_docker_refit_code_run_npm      "$USHO"     "$zig"
+
+            [ -z "$npm" ]       ||          ___x_cmd_docker_refit_code_run_npm      "$USHO"     "$npm"
+            [ -z "$deno" ]      ||          ___x_cmd_docker_refit_code_run_deno     "$USHO"     "$deno"
+            [ -z "$bun" ]       ||          ___x_cmd_docker_refit_code_run_bun      "$USHO"     "$bun"
+
+            [ -z "$pip" ]       ||          ___x_cmd_docker_refit_code_run_pip      "$USHO"     "$pip"
+
+            [ -z "$workdir" ]   ||          ___x_cmd_docker_refit_code_workdir   "$workdir"
+            [ $# -eq 0 ]        ||          {   local IFS=' ';  ___x_cmd_docker_refit_code_run "$*";    }
+
+            [ -z "$ep"  ]       ||          printf "ENTRYPOINT %s\n" "$ep"
+            [ -z "$cmd" ]       ||          printf "CMD %s\n" "$cmd"
+        } >Dockerfile
 
         # TODO: because docker build doesn't rec 130, so we have to trap sigint
 
+        docker:info "Refitting image -> $newimage"
         ___x_cmd docker build -t "$newimage" . || {
             local errcode="$?"
             case "$errcode" in
@@ -51,13 +247,215 @@ ___x_cmd_docker_refit(){
             esac
 
             # TODO: add --dev to preserve the directory
-            docker:info "[ERR=$errcode] Removing temporary workspace directory -> $dir"
-            ___x_cmd rmrf "$dir"
+            ___x_cmd_docker_refit_cleanup "$dir"
             return "$errcode"
         }
-    )
 
-    docker:info "[ERR=0] Removing temporary workspace directory -> $dir"
-    ___x_cmd rmrf "$dir"
+        docker:info "Generate cmdinfo for image -> $newimage"
+        ___x_cmd docker cmdinfo update "$newimage" || docker:warn "Fail to generate cmdinfo -> $newimage"
+        return 0
+    ) ||    return $?
+
+    ___x_cmd_docker_refit_cleanup "$dir"
 }
 
+___x_cmd_docker_refit_cleanup(){
+    local dir="$1"
+
+    if [ -n "$debug" ]; then
+        docker:warn "In debug mode, temporary workspace directory is preserved for futher diagnostics."
+    else
+        docker:info "[ERR=0] Removing temporary workspace directory -> $dir"
+        ___x_cmd rmrf "$dir"
+    fi
+}
+
+# Generate the dockerfile content to stdin ...
+___x_cmd_docker_refit_dockerfile(){
+    :
+}
+
+
+___x_cmd_docker_refit_code_from(){
+    printf "FROM %s\n" "$1"
+}
+
+
+___x_cmd_docker_refit_code_adduser(){
+    local group="$1"
+    local user="$2"
+    local uid="$3"
+    if ___x_cmd docker cmdinfo hascmd "$baseimage" adduser; then
+        ___x_cmd_docker_refit_code_run  "[ -d /home/$user ] || adduser -D -u $uid $user"
+    else
+        ___x_cmd_docker_refit_code_run  "[ -d /home/$user ] || useradd -r -u $uid -g $group $user"
+    fi
+}
+
+___x_cmd_docker_refit_code_user_workdir(){
+    ___x_cmd_docker_refit_code_user     "$1"
+    ___x_cmd_docker_refit_code_workdir  "$2"
+}
+
+___x_cmd_docker_refit_code_user(){
+    printf "USER %s\n" "$1"
+}
+
+___x_cmd_docker_refit_code_workdir(){
+    printf "WORKDIR %s\n" "$1"
+}
+
+___x_cmd_docker_refit_code_add(){
+    printf "%s\n" "ADD $1 $2"
+}
+
+___x_cmd_docker_refit_code_addexe(){
+    # printf "%s\n%s\n" "ADD ./xbin.sh            /bin/xbin.sh"           "RUN chmod +x /bin/xbin.sh"
+    printf "%s\n" "ADD $1 $2" "RUN chmod +x $2"
+}
+
+___x_cmd_docker_refit_code_run(){
+    printf "RUN %s\n" "$@"
+}
+
+___x_cmd_docker_refit_code_run_apk(){
+    local USHO="$1"
+    local apk="$2"
+
+    local xcmd="${USHO}/.x-cmd.root/bin/___x_cmdexe"
+
+    ___x_cmd_docker_refit_code_run      "if $xcmd websrc is cn; then $xcmd apk mirror set ustc; else $xcmd apk mirror set official; fi"
+    printf "RUN %s\n%s\n" \
+        "--mount=type=cache,target=/etc/apk/cache,sharing=locked \\"    \
+        "apk add $apk"
+}
+
+___x_cmd_docker_refit_code_run_apt(){
+    local USHO="$1"
+    local apt="$2"
+
+    local xcmd="${USHO}/.x-cmd.root/bin/___x_cmdexe"
+
+    ___x_cmd_docker_refit_code_run      'rm -f /etc/apt/apt.conf.d/docker-clean; echo '\''Binary::apt::APT::Keep-Downloaded-Packages "true";'\'' > /etc/apt/apt.conf.d/keep-cache'
+
+    # Consider judge whether need to apt update -- in 30 minutes, no update needed ... Or may be we should using mirror cache ...
+    printf "RUN %s\n%s\n%s\n" \
+        "--mount=type=cache,target=/var/cache/apt,sharing=locked \\"    \
+        "--mount=type=cache,target=/var/lib/apt,sharing=locked \\"      \
+        "apt update && apt --no-install-recommends install --yes $apt"
+}
+
+___x_cmd_docker_refit_code_run_yum(){
+    :
+}
+
+___x_cmd_docker_refit_code_run_dnf(){
+    :
+}
+
+___x_cmd_docker_refit_code_run_go(){
+    local USHO="$1"
+    local go="$2"
+
+    local xcmd="${USHO}/.x-cmd.root/bin/___x_cmdexe"
+
+    ___x_cmd_docker_refit_code_run  "if $xcmd websrc is cn; then $xcmd go proxy set; else $xcmd go proxy unset; fi || true"
+
+    printf "%s\n" \
+        "RUN --mount=type=cache,target=${USHO}/.cache/go-build,uid=1000,gid=1000 \\"    \
+        "go install $go"
+}
+
+___x_cmd_docker_refit_code_run_cargo(){
+    local USHO="$1"
+    local cargo="$2"
+
+    local xcmd="${USHO}/.x-cmd.root/bin/___x_cmdexe"
+
+    ___x_cmd_docker_refit_code_run  "mkdir -p ${USHO}/.cargo" # If we don't do this, it will fail with os-permission
+
+    printf "%s\n" \
+        "RUN --mount=type=cache,target=${USHO}/.cargo/registry,uid=1000,gid=1000 \\"    \
+        "cargo install $cargo"
+}
+
+___x_cmd_docker_refit_code_run_zig(){
+    local USHO="$1"
+    local zig="$2"
+
+    local xcmd="${USHO}/.x-cmd.root/bin/___x_cmdexe"
+
+    printf "%s\n" \
+        "RUN --mount=type=cache,target=${USHO}/.cache/zig,uid=1000,gid=1000 \\"    \
+        "zig fetch $zig"
+}
+
+___x_cmd_docker_refit_code_run_pip(){
+    local USHO="$1"
+    local pip="$2"
+
+    local xcmd="${USHO}/.x-cmd.root/bin/___x_cmdexe"
+
+    ___x_cmd_docker_refit_code_run      "if $xcmd websrc is cn; then $xcmd mirror pip set ali; else $xcmd mirror pip unset; fi || true"
+    printf "%s\n" \
+        "RUN --mount=type=cache,target=${USHO}/.cache/pip,uid=1000,gid=1000 \\"    \
+        "python3 -m venv p && . p/bin/activate && pip3 install $pip"
+}
+
+___x_cmd_docker_refit_code_run_pixi(){
+    local USHO="$1"
+    local pixi="$2"
+
+    local xcmd="${USHO}/.x-cmd.root/bin/___x_cmdexe"
+
+    ___x_cmd_docker_refit_code_run      "if $xcmd websrc is cn; then $xcmd mirror pip set ali; else $xcmd mirror pip unset; fi || true"
+    ___x_cmd_docker_refit_code_run      "[ -d $USHO/.pixi ] || $xcmd pixi --install"
+
+    # "RUN --mount=type=cache,target=${USHO}/.cache/rattler/cache,uid=1000,gid=1000 \\"    \
+    ___x_cmd_docker_refit_code_run      "$xcmd pixi global install $pixi"
+}
+
+___x_cmd_docker_refit_code_run_xenv(){
+    local USHO="$1"
+    local pixi="$2"
+
+    local xcmd="${USHO}/.x-cmd.root/bin/___x_cmdexe"
+
+    # "RUN --mount=type=cache,target=${USHO}/.cache/rattler/cache,uid=1000,gid=1000 \\"    \
+    ___x_cmd_docker_refit_code_run      "$xcmd env use $xenv"
+}
+
+
+___x_cmd_docker_refit_code_run_npm(){
+    local USHO="$1"
+    local npm="$2"
+
+    local xcmd="${USHO}/.x-cmd.root/bin/___x_cmdexe"
+
+    ___x_cmd_docker_refit_code_run  "if $xcmd websrc is cn; then $xcmd mirror npm set npmmirror; else $xcmd mirror npm unset; fi || true"
+    printf "%s\n" \
+        "RUN --mount=type=cache,target=${USHO}/.npm,uid=1000,gid=1000 \\"    \
+        "npm install $npm"
+}
+
+___x_cmd_docker_refit_code_run_deno(){
+    local USHO="$1"
+    local deno="$2"
+
+    local xcmd="${USHO}/.x-cmd.root/bin/___x_cmdexe"
+
+    # TODO: When installing globally, permission parameters need to be added.
+                    # "RUN --mount=type=cache,target=${USHO}/.cache/deno,uid=1000,gid=1000 \\"    \
+    ___x_cmd_docker_refit_code_run  "deno install -g -A $deno"
+}
+
+___x_cmd_docker_refit_code_run_bun(){
+    local USHO="$1"
+    local bun="$2"
+
+    local xcmd="${USHO}/.x-cmd.root/bin/___x_cmdexe"
+
+    printf "%s\n" \
+            "RUN --mount=type=cache,target=${USHO}/.bun/install/cache,uid=1000,gid=1000 \\"    \
+            "bun install -g $bun"
+}
diff --git a/mod/pixi/lib/__install b/mod/pixi/lib/__install
--- a/mod/pixi/lib/__install
+++ b/mod/pixi/lib/__install
@@ -2,28 +2,69 @@
 
 ___x_cmd_pixi___install(){
     if [ -f "$___X_CMD_PIXI_BIN_PATH/$___X_CMD_PIXI_BIN" ]; then
-        pixi:info "pixi is already installed."
+        pixi:info "Pixi is already installed."
     else
-        ___x_cmd_pixi___download_inner "$@" || return
+        ___x_cmd_pixi___download_inner "$@" || return $?
     fi
 
     ___x_cmd_pixi___activate_auto
 }
 
+# TODO: introducing environment variable ... ASSUME_REMOVE_PIXI_HOME
 ___x_cmd_pixi___uninstall(){
+    local ASSUME_REMOVE_PIXI_HOME="${ASSUME_REMOVE_PIXI_HOME}"
+
+    while [ $# -gt 0 ]; do
+        case "$1" in
+            --assume-remove-data)
+                case "$2" in
+                    yes|no)     ASSUME_REMOVE_PIXI_HOME="$2"; shift 2 ;;
+                    *)          N=pixi M="Only accept yes or no following --assume-remove-data" log:ret:64 ;;
+                esac
+                ;;
+
+            *)
+                N=pixi M="Unsupported option -> $1" log:ret:64 ;;
+        esac
+    done
+
+    if ___x_cmd_hascmd pixi; then
+        # pixi cache: https://pixi.sh/latest/features/environment/#caching-packages
+        ___x_cmd pixi clean cache --yes || return $?
+        pixi:info "Pixi caching packages were successfully purged."
+    fi
+
     {
         ___x_cmd_pixi___deactivate
         ___x_cmd rmrf "$___X_CMD_ROOT_BOOT/pixi.disable" "$___X_CMD_PIXI_BIN_PATH/$___X_CMD_PIXI_BIN"
-    } || return
+    } || return $?
 
-    pixi:info "Deleted 'pixi' binary, pixi uninstall successfully!"
+    pixi:info "'pixi' binary is removed."
 
+    case "$ASSUME_REMOVE_PIXI_HOME" in
+        yes)        ___x_cmd_pixi___uninstall___rm; return ;;
+        no)         ;;
+        *)
+                    if ___x_cmd_runmode_allow_manual; then
+                        if ___x_cmd ui yesno "Do you want to remove ~/.pixi directory, which contains globally installed packages data ?"; then
+                            ! ___x_cmd_pixi___uninstall___rm || return 0
+                        fi
+                    fi
+    esac
 
+    pixi:info \
+        --cmd "rm -rf ~/.pixi"  \
+        "Pixi data can be manually removed by executing the following command."
+}
+
+___x_cmd_pixi___uninstall___rm(){
     local pixi_home="$HOME/.pixi"
-    if [ -t 1 ] && ___x_cmd_is_interactive; then
-        ___x_cmd ui yesno "Delete $pixi_home directory?"  || return 0
-        ___x_cmd rmrf "$pixi_home"
-        pixi:info "Deleted $pixi_home directory."
+    if ___x_cmd rmrf "${pixi_home}"; then
+        pixi:info "Directory removed -> ${pixi_home}"
+        return 0
+    else
+        pixi:error "Fail to remove directory -> ${pixi_home}"
+        return 1
     fi
 }
 
@@ -39,12 +80,12 @@ ___x_cmd_pixi___get_latest_version_(){
 
 ___x_cmd_pixi___upgrade(){
     [ -f "$___X_CMD_PIXI_BIN_PATH/$___X_CMD_PIXI_BIN" ] || {
-        pixi:error "pixi is not installed."
+        pixi:error "Pixi is not installed."
         return 1
     }
 
     local version=
-    version="$(___x_cmd_pixi___cmd --version)"
+    version="$(___x_cmd_pixi___runmain --version)"
     version="${version#* }"
 
     local x_=
@@ -58,6 +99,6 @@ ___x_cmd_pixi___upgrade(){
     }
 
     pixi:info "Pixi will be updated from $version to $latest_version"
-    ___x_cmd_pixi___download || return
+    ___x_cmd_pixi___download || return $?
     pixi:info "Pixi has been updated to version $latest_version."
 }
diff --git a/mod/pkg/lib/sphere/gc/remove b/mod/pkg/lib/sphere/gc/remove
--- a/mod/pkg/lib/sphere/gc/remove
+++ b/mod/pkg/lib/sphere/gc/remove
@@ -11,10 +11,10 @@
 #     pkg:info "Removing $name $version"
 
 #     x fslock run "pkg_sphere_${sphere_name}_${name}_${version}_${osarch}" \
-#         ___x_cmd_pkg_sphere_gc_remove___populate "$name" "$version" "$osarch" || return
+#         ___x_cmd_pkg_sphere_gc_remove___populate "$name" "$version" "$osarch" || return $?
 
 #     x fslock run "pkg_${name}_${version}_${osarch}" \
-#         ___x_cmd_pkg_sphere_gc_remove___ball "$name" "$version" "$osarch" || return
+#         ___x_cmd_pkg_sphere_gc_remove___ball "$name" "$version" "$osarch" || return $?
 
 # }
 ___x_cmd_pkg_sphere_gc_remove(){
@@ -29,25 +29,32 @@ ___x_cmd_pkg_sphere_gc_remove(){
 ___x_cmd_pkg_sphere_gc_remove___populate(){
     pkg:sphere:parse:args
 
-    local x_treename=; ___x_cmd_pkg_treename_ "$name" "$version" "$osarch" || return
+    local x_treename=; ___x_cmd_pkg_treename_ "$name" "$version" "$osarch" || return $?
     local tgt="$___X_CMD_PKG_ROOT_SPHERE/$sphere_name/$x_treename/$name/$version"
     [ -d "$tgt" ] || {
-        ___x_cmd_pkg_treename_get_form_tree_ "$osarch" || return
-        tgt="$___X_CMD_PKG_ROOT_SPHERE/$sphere_name/$x_treename/$name/$version"
+        x_treename=
+        for tgt in "$___X_CMD_PKG_ROOT_SPHERE/$sphere_name/"*"/$name/$version"; do
+            [ -d "$tgt" ] || continue
+            x_treename="${tgt#"$___X_CMD_PKG_ROOT_SPHERE/$sphere_name/"}"
+            x_treename="${x_treename%%"/$name/$version"}"
+            pkg:debug "Attempting to remove pkg [name=$name] [version=$version] under [x_treename=$x_treename]"
+            break
+        done
     }
 
     pkg:debug "Attempting to remove $x_treename $name $version"
-    ___x_cmd_pkg_sphere_depend file rm      --sphere "$sphere_name" --sphereroot "$___X_CMD_PKG_ROOT_SPHERE" --osarch "$osarch" "$name" "$version" || return
+    ___x_cmd_pkg_sphere_depend file rm      --sphere "$sphere_name" --sphereroot "$___X_CMD_PKG_ROOT_SPHERE" --osarch "$osarch" "$name" "$version" || return $?
     if ! [ -d "$tgt" ];then
-        pkg:warn "This $name $version is no exist in local."
+        pkg:warn "Not found the path of pkg [name=$name] [version=$version] folder"
         return 1
     else
         ___x_cmd_cmds chmod -R 700 "$tgt" >/dev/null 2>&1
-        ___x_cmd_pkg_sphere_xbin remove_cache   --sphere "$sphere_name" --sphereroot "$___X_CMD_PKG_ROOT_SPHERE" --osarch "$osarch" "$name" "$version" || return
+        ___x_cmd_pkg_sphere_xbin remove_cache   --sphere "$sphere_name" --sphereroot "$___X_CMD_PKG_ROOT_SPHERE" --osarch "$osarch" "$name" "$version" || return $?
+        ___x_cmd_pkg_sphere_snap remove_cache   --sphere "$sphere_name" --sphereroot "$___X_CMD_PKG_ROOT_SPHERE" --osarch "$osarch" "$name" "$version" || return $?
         # x:warn x rmrf "$tgt"
         ___x_cmd rmrf "$tgt"
 
-        # ___x_cmd_pkg_sphere_depend remove       --sphere "$sphere_name" --sphereroot "$___X_CMD_PKG_ROOT_SPHERE" --osarch "$osarch" "$name" "$version" || return
+        # ___x_cmd_pkg_sphere_depend remove       --sphere "$sphere_name" --sphereroot "$___X_CMD_PKG_ROOT_SPHERE" --osarch "$osarch" "$name" "$version" || return $?
 
         local tgt_folder=${tgt%/*}
         [ ! -d "$tgt_folder" ] || ! ___x_cmd fsiter --dirempty --folder "$tgt_folder" || ___x_cmd rmrf "$tgt_folder"
@@ -62,7 +69,7 @@ ___x_cmd_pkg_sphere_gc_remove___ball(){
 
     local download_file_ext=
     local os="${osarch%/*}";  local arch="${osarch#*/}";    local tree=
-    ___x_cmd_pkg___attr "$name" "$version" "$osarch" "download_file_ext,tree" || return
+    ___x_cmd_pkg___attr "$name" "$version" "$osarch" "download_file_ext,tree" || return $?
     local dir="$___X_CMD_PKG_DOWNLOAD_PATH/$name"
     local ball="$dir/${version}.${tree}.${download_file_ext}"
     pkg:debug "Attempting to remove $ball"
@@ -101,7 +108,7 @@ ___x_cmd_pkg_sphere_gc_remove___silent(){
             [ -n "$name" ]      || N=pkg M="Provide a package name"     log:ret:1
     local version="$2";
             [ -n "$version" ]   || {
-            x_=; ___x_cmd_pkg_default_version_ "$name" "$osarch"            || return
+            x_=; ___x_cmd_pkg_default_version_ "$name" "$osarch"            || return $?
             version="$x_";
     }
 
@@ -111,11 +118,11 @@ ___x_cmd_pkg_sphere_gc_remove___silent(){
     # Noitce: you should never
     local fslock_name="$___X_CMD_PKG_ROOT_SPHERE/$sphere_name/$osarch/$name/$version"
     (
-        ___x_cmd fslock wait_acquire "$fslock_name" || return
+        ___x_cmd fslock wait_acquire "$fslock_name" || return $?
 
         x_=; ___x_cmd_pkg_sphere_lastaddts get_ \
             --sphere "$sphere_name" --sphereroot "$___X_CMD_PKG_ROOT_SPHERE"                \
-            --osarch "$osarch" "$name" "$version" || return
+            --osarch "$osarch" "$name" "$version" || return $?
         if [ -f "$x_" ]; then
             [ "$gcfp" -nt "$x_" ] || {
                 pkg:info "The last added time of [osarch=$osarch] [name=$name] [version=$version] is newer than gc start time"
@@ -152,7 +159,7 @@ ___x_cmd_pkg_sphere_gc_remove___silent(){
         ___x_cmd_pkg_sphere_gc_remove___populate    \
                 --sphere "$sphere_name"                     \
                 --sphereroot "$___X_CMD_PKG_ROOT_SPHERE"    \
-                --osarch "$osarch" "$name" "$version" || return
+                --osarch "$osarch" "$name" "$version" || return $?
 
         ___x_cmd fslock release "$fslock_name"
     ) || {
diff --git a/mod/xrc/latest b/mod/xrc/latest
--- a/mod/xrc/latest
+++ b/mod/xrc/latest
@@ -23,7 +23,7 @@ fi
 ___x_cmd_readlink_recursive_(){
     if [ -L "${1:?Provide link}" ]; then
         local next_link
-        next_link="$(readlink "${1}")" || return
+        next_link="$(readlink "${1}")" || return $?
         if [ "${next_link#/}" = "$next_link" ]; then
             next_link="$(dirname "${1}")/$next_link"
         fi
@@ -192,7 +192,7 @@ alias xrc:mod=___x_cmd_source_inner
 ___x_cmd_source_inner_lib(){
     local mod="${1:?Provide module name}"; shift
     while [ $# -gt 0 ]; do
-        . "$___X_CMD_ROOT_MOD/$mod/lib/$1" || return
+        . "$___X_CMD_ROOT_MOD/$mod/lib/$1" || return $?
         shift
     done
 }
@@ -211,6 +211,8 @@ ___X_CMD_UNSEENCHAR_003=""
 ___X_CMD_UNSEENCHAR_004=""
 ___X_CMD_UNSEENCHAR_005=""
 
+___X_CMD_UNSEENCHAR_HT="	"
+___X_CMD_UNSEENCHAR_009="	"
 ___X_CMD_UNSEENCHAR_010=""
 ___X_CMD_UNSEENCHAR_011="	"
 ___X_CMD_UNSEENCHAR_015="
@@ -228,13 +230,13 @@ ___X_CMD_UNSEENCHAR_NEWLINE="
 
 ___x_cmd_followlink(){
     local x_
-    ___x_cmd_followlink_ "$@" || return
+    ___x_cmd_followlink_ "$@" || return $?
     printf "%s\n" "$x_"
 }
 
 ___x_cmd_followlink_(){
     x_=""
-    ___x_cmd_readlink_recursive_ "$@" || return
+    ___x_cmd_readlink_recursive_ "$@" || return $?
     x_="$___X_CMD_READLINK_RECURSIVE_"
 }
 # EndSection
@@ -254,8 +256,8 @@ alias @return='___x_cmd_log_envmsg && return'
 alias panic:return='eval "___x_cmd_panic___loginner && return"'
 alias panic:exit='eval "___x_cmd_panic___loginner && exit"'
 
-___x_cmd_panic___loginner(){ x log ":${N:-x}" "${L:-error}" "$M"; }
-xrc:mod:lib xrc    functor first line inner/index inner/whichbin cmds/_index lazy util ldict/posix shgen shcode batcode exitcode which
+___x_cmd_panic___loginner(){ ___x_cmd log ":${N:-x}" "${L:-error}" "$M"; }
+xrc:mod:lib xrc    runmode functor first inner/index inner/whichbin cmds/_index lazy util ldict/posix shgen shcode batcode exitcode which compat/_index
 
 ___x_cmd_mkdirp(){
     if [ "$#" -eq 0 ]; then
@@ -346,7 +348,7 @@ ___x_cmd_xrc_source_file_main_define_by_setmain(){
             \"$___X_CMD_XRC_SET_MAIN\" \"\$@\"
         }"
 
-        if ___x_cmd_is_suitable_advise_env && [ -n "$___X_CMD_XRC_SET_MAIN" ] && [ -n "$___X_CMD_WHICH_ONE_NAMING" ] ; then
+        if ___x_cmd_is_suitable_advise_repl && [ -n "$___X_CMD_XRC_SET_MAIN" ] && [ -n "$___X_CMD_WHICH_ONE_NAMING" ] ; then
             ___x_cmd_advise init "$___X_CMD_WHICH_ONE_NAMING"
         fi
     fi
@@ -376,7 +378,7 @@ ___x_cmd_xrc_source_file_main_(){
 
 ___x_cmd_xrc_source_file_main_import(){
     ___X_CMD_XRC_SOURCE_FILE_MAIN_USING_IMPORT=
-    ___x_cmd_xrc_source_file_main_ "$@" || return
+    ___x_cmd_xrc_source_file_main_ "$@" || return $?
     [ -n "$___X_CMD_XRC_SOURCE_FILE_MAIN_" ] || return 0
     ___X_CMD_XRC_SET_MAIN="$___X_CMD_XRC_SOURCE_FILE_MAIN_" ___x_cmd_xrc_source_file_main_define_by_setmain
 }
@@ -426,14 +428,14 @@ xrc(){
             ___x_cmd_cmds_cat "$___X_CMD_ROOT_MOD/xrc/lib/help/which.txt" >&2
             return 1
             ;;
-        "")                     x help -m xrc >&2; return 64 ;;
-        help|-h|--help)         x help -m xrc ;;
+        "")                     ___x_cmd help -m xrc >&2; return 64 ;;
+        help|-h|--help)         ___x_cmd help -m xrc ;;
         root)                   printf "%s" "$___X_CMD_ROOT" ;;
         --ls)                   ___x_cmd_cmds_ls "$___X_CMD_ROOT_MOD" ;;                      # If tar.gz, using tar ls. If folder, ls $folder
         setmain)                ___x_cmd_xrc_set_main "$@" ;;
         reload)                 xrc:mod xrc/lib/reload && ___x_cmd_reload "$@" ;;
         reset)                  ___x_cmd_xrc_reset ;;
-        *)                      ___x_cmd_xrc_source_file "$subcmd" "$@";    return
+        *)                      ___x_cmd_xrc_source_file "$subcmd" "$@";    return $?
     esac
 }
 # EndSection
@@ -450,7 +452,6 @@ ___x_cmd_path_down_or_push "$___X_CMD_ROOT_DATA/triarii/bin"
 # This is dangerous
 xrc httpget
 xrc:mod x-cmd/latest
-xrc:mod args/latest     # TODO: args is not necessary
 
 xrc websrc; ___x_cmd_websrc load
 
@@ -479,7 +480,8 @@ ___x_cmd_bootrc_run(){
     done
 }
 
-if ___x_cmd_is_interactive; then
+if ___x_cmd_is_repl; then
+    ___X_CMD_RUNMODE="${___X_CMD_RUNMODE:-"$___X_CMD_RUNMODE_CHATTY"}"
 
     # Adding theme boot code here ...
     xrc:mod theme/lib/boot/theme.load
@@ -503,7 +505,7 @@ if ___x_cmd_is_interactive; then
 fi
 
 if [ -n "$ZSH_VERSION" ]; then
-    if ___x_cmd_is_interactive; then
+    if ___x_cmd_is_repl; then
         trap '
         case "$0" in
             zsh)        return 130 ;;
