...

diff --git a/mod/xrc/latest b/mod/xrc/latest
--- a/mod/xrc/latest
+++ b/mod/xrc/latest
@@ -11,6 +11,14 @@
     return 0
 }
 
+if alias x >/dev/null 2>&1; then
+    printf "%s\n" "- I|x: Sorry, we unalias the origin x alias to ensure the x-cmd works properly. In the future we will provide a way to choose the short name for ___x_cmd."
+    unalias x || {
+        printf "%s\n" "- E|x: Unable to remove alias 'x'. Booting of 'x-cmd' aborted."
+        return 1
+    }
+fi
+
 # Section 0: get ___X_CMD_SHELL and TMPDIR
 ___x_cmd_readlink_recursive_(){
     if [ -L "${1:?Provide link}" ]; then
@@ -46,11 +54,12 @@ elif [ -n "$KSH_VERSION" ]; then
             # This is the ksh that can run x-bash
             ;;
         *)
-            x(){
-                :
-            }
+            # x(){
+            #     :
+            # }
             # Only support the xbin, not x-cmd
-            return
+            printf "%s\n" "- E|x: Unsupported this shell"
+            return 1
             ;;
     esac
     # ___X_CMD_SHELL=ksh
