Updating main branch using x7 release -> 58c39378780f2f454a596624c4430800910d73ab

diff --git a/mod/claw/lib/service b/mod/claw/lib/service
--- a/mod/claw/lib/service
+++ b/mod/claw/lib/service
@@ -19,9 +19,6 @@
 # x claw service start --name 0
 # x qywx bot connect
 
-___X_CMD_CLAW_TMP="$___X_CMD_ROOT_TMP/claw"
-___x_cmd mkdirp "${___X_CMD_CLAW_TMP}"
-
 ___x_cmd_claw_service(){
     [ $# -gt 0 ]    ||      set -- --help
 
@@ -35,48 +32,89 @@ ___x_cmd_claw_service(){
 }
 
 ___x_cmd_claw_service_start(){
+    [ "$#" -gt 0 ] ||   set -- --help
+
+    local im=;
     local op="$1";          shift
     case "$op" in
-        -h|--help)          ___x_cmd help -m claw service start "$@" ; return 0 ;;
+        -h|--help)
+                    ___x_cmd help -m claw service start "$@" ; return 0 ;;
+        feishu|weixin|telegram)
+                    im="$op" ;;
+        *)          claw:error "Unsupported IM platform: $op"
+                    return 1
+                    ;;
     esac
 
-    local im="${1:-"weixin"}"
+    claw:info "Ensuring $im listener is ready"
+    ___x_cmd_claw_run___ensure "$im" || {
+        claw:error "Failed to start $im listener, claw service startup interrupted"
+        return 1
+    }
+
     claw:info "Starting claw service"
     ___x_cmd service start      x-claw-service  --  x-cmd claw service run "$@"
 
-    ___x_cmd_cmds sleep 3
-    ___x_cmd service isalive "x-$im-listener" || {
-        claw:warn "Failed to start $im message listener, retrying"
-        ___x_cmd_cmds sleep 8
-
-        ___x_cmd service isalive "x-$im-listener" || {
-            claw:error "Failed to start service: $im listener failed"
-            ___x_cmd service log tail "x-$im-listener"
-            return 1
-        }
-    }
-
+    ___x_cmd sleep 2
     ___x_cmd service isalive x-claw-service || {
-        claw:error "Fial to start claw service"
+        claw:error "Failed to start claw service"
         ___x_cmd service log tail x-claw-service
         return 1
     }
 
     printf "%s " "status: "; ___x_cmd_claw_service_status
-    printf "%s\n" "$im" > "${___X_CMD_CLAW_TMP}/listener"
 }
 
 ___x_cmd_claw_service_stop(){
-    local im
-    read -r im < "${___X_CMD_CLAW_TMP}/listener"
+    [ "$#" -gt 0 ] ||   set -- --help
 
-    ___x_cmd service stop       "x-$im-listener"
-    ___x_cmd service stop       x-claw-service
-    ___x_cmd_cmds pkill -f "claw service run"
+    local im="$1"; shift
+    case "$im" in
+        -h|--help)
+            ___x_cmd help -m claw service stop "$@" ; return 0 ;;
+        feishu|weixin|telegram)
+            ;;
+        *)      claw:error "Unsupported IM platform: $im"
+            return 1
+            ;;
+    esac
+
+    if ___x_cmd service isalive x-claw-service; then
+        if ___x_cmd service isalive "x-$im-listener"; then
+            claw:info "Stopping $im listener"
+            ___x_cmd service stop       "x-$im-listener"
+        fi
+
+        claw:info "Stopping claw service"
+        ___x_cmd service stop       x-claw-service
+        ___x_cmd_cmds pkill -f "claw service run"
+    else
+        claw:warn "claw service is not running"
+    fi
 }
 
 ___x_cmd_claw_service_restart(){
-    ___x_cmd service restart    x-claw-service
+    [ "$#" -gt 0 ] ||   set -- --help
+
+    local im="$1"; shift
+    case "$im" in
+        -h|--help)
+                    ___x_cmd help -m claw service restart "$@" ; return 0 ;;
+        feishu|weixin|telegram)
+                    ;;
+        *)          claw:error "Unsupported IM platform: $im"
+                    return 1
+                    ;;
+    esac
+
+    if ___x_cmd service isalive x-claw-service; then
+        ___x_cmd_claw_service_stop "$im" || {
+            claw:warn "Claw service is not stopped. Please try 'x service stop --force x-claw-service'"
+            return 1
+        }
+    fi
+
+    ___x_cmd_claw_service_start "$im"
 }
 
 ___x_cmd_claw_service_status(){
diff --git a/mod/feishu/lib/listen b/mod/feishu/lib/listen
--- a/mod/feishu/lib/listen
+++ b/mod/feishu/lib/listen
@@ -11,7 +11,7 @@ ___x_cmd_feishu_listen(){
             -h|--help)      ___x_cmd help -m feishu listen "$@" ; return 0 ;;
             --fp)           fp=1 ;          shift ;;
             --json)         format="json";  shift ;;
-            *)              break ;;
+            *)              N=feishu M="Unknown op -> $1" log:ret:64   ;;
         esac
     done
 
@@ -19,46 +19,57 @@ ___x_cmd_feishu_listen(){
     local cur_token
     ____x_cmd_tenant_token ; cur_token="$x_"
 
-        # TODO:
+
+    local sync_buf_file="${___X_CMD_FEISHU_TMP}/sync_buf"
+
+    # TODO:
     local chats=
     chats="$(___x_cmd feishu group ls --json | ___x_cmd jq -r '.data.items[].chat_id')"
+    [ -n "$chats" ] || N=feishu M="Failed to get group list" log:ret:64
+
+    local date=;
+    ___x_cmd date timestamp_ ; date="$x_"
+    printf "%s" "$date" > "$sync_buf_file"
+    sleep 1
 
     local chatid
     while true; do
-        local date=;
         local resp=;
-        ___x_cmd date timestamp_ ; date="$x_"
+        [ ! -f "$sync_buf_file" ] || read -r date <"$sync_buf_file"
+        while IFS= read -r chatid; do
+            resp="$(___x_cmd_feishu_getmessages "$chatid" "$date")" || {
+                feishu:error "Failed to get updates: $resp"
+                ___x_cmd sleep 1s
+                return 1
+            }
 
+            local msg="" sender="" chatid="" last_msg_time=""
+            ___x_cmd jo env .data.items msg=.1 sender=.1.sender.sender_type chatid=.1.chat_id last_msg_time=.1.create_time<<A
+$resp
+A
+            [ "$msg" != "[]" ]     || continue
+            [ "$sender" = "user" ] || continue
+            date="$(( (last_msg_time / 1000) + 1 ))"
+            printf "%s" "$date" > "$sync_buf_file"
 
-        while [ -z "$resp" ]; do
-            while IFS= read -r chatid; do
-                resp="$(___x_cmd_feishu_getmessages "$chatid" "$date" | ___x_cmd_feishu_parsemsg)" || {
-                    feishu:error "Failed to get updates: $resp"
-                    ___x_cmd sleep 1s
-                    return 1
+            if [ -n "$fp" ]; then
+                [ -n "$chatid" ] || {
+                    feishu:error "Failed to get chat id, cannot save data to file"
+                    continue
                 }
-            done <<A
+                ___X_CMD_FEISHU_BOT_DATA="${___X_CMD_FEISHU_BOT_PATH}/data_${chatid}.tsv"
+                ___x_cmd ensurefp "$___X_CMD_FEISHU_BOT_DATA"
+                printf "%s\n" "$msg"  >> "$___X_CMD_FEISHU_BOT_DATA"
+                ___x_cmd tailer pub "$___X_CMD_ROOT_DATA/feishu/sub" "feishu:${chatid}"
+            elif [ "$format" = "json" ]; then
+                printf "%s\n" "$msg"
+            else
+                printf "%s\n" "$msg"
+            fi
+        done <<A
 $chats
 A
-        done
 
-        if [ -n "$fp" ]; then
-            case "$resp" in
-                *"chat"*)
-                        # Extract chat_id using pure shell string manipulation
-                        chatid="${resp##*\"chat_id\" : \"}"
-                        chatid="${chatid%%\"*}"
-                        ___X_CMD_FEISHU_BOT_DATA="${___X_CMD_FEISHU_BOT_PATH}/data_${chatid}.tsv"
-                        ___x_cmd ensurefp "$___X_CMD_FEISHU_BOT_DATA"
-                        printf "%s\n" "$resp"  >> "$___X_CMD_FEISHU_BOT_DATA"
-                        ___x_cmd tailer pub "$___X_CMD_ROOT_DATA/feishu/sub" "feishu:${chatid}"
-                        ;;
-            esac
-        elif [ "$format" = "json" ]; then
-            printf "%s\n%s" "$resp" ""
-        else
-            printf "%s\n%s" "$resp" ""
-        fi
     done
 }
 
@@ -69,18 +80,18 @@ ___x_cmd_feishu_getmessages(){
                   -H "Authorization: Bearer $cur_token"
 }
 
-___x_cmd_feishu_parsemsg(){
-    ___x_cmd awk0 -m j/json -m j/jiter '
-{ jiparse_after_tokenize(o, $0); }
-END{
-    kp = SUBSEP "\"1\"" SUBSEP "\"data\"" SUBSEP "\"items\""
-    l = o[ kp L ]
-    for (i=1; i<=l; ++i){
-        kp_i = kp SUBSEP "\""i"\""
-        kp_sender_type = kp_i SUBSEP "\"sender\"" SUBSEP "\"sender_type\""
-        if (o[ kp_sender_type ] == "\"user\""){
-            print jstr0(o, kp_i, " ")
-        }
-    }
-}'
-}
+# ___x_cmd_feishu_parsemsg(){
+#     ___x_cmd awk0 -m j/json -m j/jiter '
+# { jiparse_after_tokenize(o, $0); }
+# END{
+#     kp = SUBSEP "\"1\"" SUBSEP "\"data\"" SUBSEP "\"items\""
+#     l = o[ kp L ]
+#     for (i=1; i<=l; ++i){
+#         kp_i = kp SUBSEP "\""i"\""
+#         kp_sender_type = kp_i SUBSEP "\"sender\"" SUBSEP "\"sender_type\""
+#         if (o[ kp_sender_type ] == "\"user\""){
+#             print jstr0(o, kp_i, " ")
+#         }
+#     }
+# }'
+# }
