...

diff --git a/mod/docker/lib/origin/images b/mod/docker/lib/origin/images
--- a/mod/docker/lib/origin/images
+++ b/mod/docker/lib/origin/images
@@ -1,53 +1,70 @@
 # shellcheck shell=dash
 
 ___x_cmd_docker_images(){
-    local op="$1";  [ "$#" -eq 0 ] || shift
+    [ $# -gt 0 ] || set -- app
+
+    local op="$1"; shift
     case "$op" in
-        app|"")     ___x_cmd_docker_images_app "$@" ;;
-        *)          ___x_cmd_docker_images_main "$op" "$@"
+        -h|--help)  ___x_cmd help -m docker images          ;;
+        app|"")     ___x_cmd_docker_images_app              ;;
+
+        *)          ___x_cmd_docker_images_main "$op" "$@"  ;;
     esac
 }
 
 ___x_cmd_docker_images_app(){
-    ___x_cmd_docker_images_main --csv | \
-        x csv tab - 6,9,5,3,11 | command sed -e 's/\\u003c/</g' -e 's/\\u003e/>/g' | x csv app
+    if [ -t 1 ] && ___x_cmd_is_interactive; then
+        ___x_cmd_docker_images_app_
+    else
+        ___x_cmd_docker_images_main
+    fi
 }
 
-___x_cmd_docker_images_main(){
-    local format=""
+# TODO: export image, rm image, info image, push image
+___x_cmd_docker_images_app_(){
+    local image_id=
+    ___X_CMD_CSV_APP_SHBIN_CODE="xrc docker; " \
+        ___x_cmd csv app --return var ___x_cmd_docker_images_main --csv || return 1
+    image_id="$___X_CMD_CSV_APP_DATA_IMAGE_ID"
 
-    local IMAGE_OPTS=""
+    [ -n "$image_id" ] || return 0
+
+    local id=
+    local cmd=
+    ___x_cmd ui select id,cmd \
+        "Next for image: $___X_CMD_CSV_APP_DATA_REPOSITORY"     \
+        "x docker rmi $image_id"                                \
+        "x docker rmi -f $image_id"                             \
+        "x docker inspect $image_id"                            \
+        "return 1"                                              || return 1
+    docker:debug "run command -> $cmd"
+    eval "$cmd"
+}
+
+
+___x_cmd_docker_images_main(){
+    local IMAGE_OPTS=
     while [ $# -gt 0 ]; do
         case "$1" in
             -j|--json)
-                x cmdstr IMAGE_OPTS --format '{{json .}}'
+                ___x_cmd cmdstr IMAGE_OPTS --format '{{json .}}'
                 shift ;;
             --csv)
-                format=csv
-                shift
-                ;;
-            -a|--all|--digests|--no-trunc|--quiet)
-                x cmdstr IMAGE_OPTS "$1"
+                ___x_cmd cmdstr IMAGE_OPTS --format 'table {{.Repository}},{{.Tag}},{{.ID}},{{.CreatedSince}},{{.Size}},{{.Containers}},{{.CreatedAt}},{{.Digest}},{{.SharedSize}},{{.UniqueSize}}'
+                shift ;;
+            -a|--all|--digests|--no-trunc|-q|--quiet)
+                ___x_cmd cmdstr IMAGE_OPTS "$1"
                 shift ;;
             -f|--filter|--format)
-                x cmdstr IMAGE_OPTS "$1" "$2"
+                [ -n "$2" ] || {
+                    docker:error "The '$1' parameter cannot be empty."
+                    return 1
+                }
+                ___x_cmd cmdstr IMAGE_OPTS "$1" "$2"
                 shift 2 ;;
-            -h|--help)
-                x help -m docker images;        return 0 ;;
-            "")
-                x help -m docker images 1>&2;   return 64 ;;
             *)
-                docker:error "Unkown options ==> $1";
-                return 64
-                ;;
+                docker:error "Unkown options ==> $1";  return 64 ;;
         esac
     done
-
-    case "$format" in
-        csv)    ___x_cmd___docker_origin image ls --format '{{json .}}' | \
-                    x ja jl2c .Containers .CreatedAt .CreatedSince .Digest .ID .Repository .SharedSize .Size .Tag .UniqueSize .VirtualSize | \
-                    x csv header --add Containers,CreatedAt,CreatedSince,Digest,ID,Repository,SharedSize,Size,Tag,UniqueSize,VirtualSize
-                ;;
-        *)      eval ___x_cmd___docker_origin image ls "$IMAGE_OPTS" ;;
-    esac
+    eval ___x_cmd___docker_origin image ls "$IMAGE_OPTS"
 }
diff --git a/mod/docker/lib/origin/info b/mod/docker/lib/origin/info
--- a/mod/docker/lib/origin/info
+++ b/mod/docker/lib/origin/info
@@ -8,14 +8,40 @@ ___x_cmd_docker_info(){
 
     local op="$1"; shift
     case "$op" in
-        app|"")     ___x_cmd_docker_info_app "$@" ;;
-        *)          ___x_cmd___docker_origin info "$op" "$@"
+        -h|--help)  ___x_cmd help -m docker info         ;;
+        app|"")     ___x_cmd_docker_info_app             ;;
+        *)          ___x_cmd_docker_info_main "$op" "$@" ;;
     esac
 }
 
 ___x_cmd_docker_info_app(){
-    # todo: using app to enhance
-    command docker info
-    # ___x_cmd___docker_origin info --format '{{json .}}' | x ja jl2c .ID .Name .Driver .Scope \
-    # | x csv header "NETWORK ID" NAME DRIVER SCOPE | x csv app --width "10%,10%,10%,-"
+    if [ -t 1 ] && ___x_cmd_is_interactive; then
+        local ___X_CMD_JO_NAV_FINAL_COMMAND=
+        local ___X_CMD_JO_NAV_KP=
+        local ___X_CMD_JO_NAV_VALUE=
+        ___x_cmd jo nav -- ___x_cmd docker info --json
+    else
+        ___x_cmd_docker_info_main
+    fi
+}
+
+___x_cmd_docker_info_main(){
+    local IMAGE_OPTS=
+    while [ $# -gt 0 ]; do
+        case "$1" in
+            -j|--json)
+                ___x_cmd cmdstr IMAGE_OPTS --format json
+                shift ;;
+            -f|--format)
+                [ -n "$2" ] || {
+                    docker:error "The '$1' parameter cannot be empty."
+                    return 1
+                }
+                ___x_cmd cmdstr IMAGE_OPTS "$1" "$2"
+                shift 2 ;;
+            *)
+                docker:error "Unkown options ==> $1";  return 64 ;;
+        esac
+    done
+    eval ___x_cmd___docker_origin info "$IMAGE_OPTS"
 }
diff --git a/mod/docker/lib/origin/network b/mod/docker/lib/origin/network
--- a/mod/docker/lib/origin/network
+++ b/mod/docker/lib/origin/network
@@ -1,18 +1,79 @@
 # shellcheck shell=dash
 ___x_cmd_docker_network(){
+    [ $# -gt 0 ] || set -- app
+
+    local op="$1"; shift
+    case "$op" in
+        -h|--help)  ___x_cmd help -m docker network              ;;
+        app|"")     ___x_cmd_docker_network_app             "$@" ;;
+        ls)         ___x_cmd_docker_network_ls              "$@" ;;
+
+        *)          ___x_cmd___docker_origin network "$op"  "$@" ;;
+    esac
+}
+
+___x_cmd_docker_network_ls(){
     [ $# -gt 0 ] || {
         ___x_cmd_docker_network_app
         return
     }
 
-    local op="$1"; shift
-    case "$op" in
-        app|"")     ___x_cmd_docker_network_app "$@" ;;
-        *)          ___x_cmd___docker_origin network "$op" "$@"
-    esac
+    ___x_cmd_docker_network_ls_main "$@"
 }
 
 ___x_cmd_docker_network_app(){
-    ___x_cmd___docker_origin network ls --format '{{json .}}' | x ja jl2c .ID .Name .Driver .Scope \
-    | x csv app --width "10%,10%,10%,-" --header 'NETWORK ID,NAME,DRIVER,SCOPE'
+    if [ -t 1 ] && ___x_cmd_is_interactive; then
+        ___x_cmd_docker_network_app_
+    else
+        ___x_cmd_docker_network_ls_main
+    fi
 }
+
+___x_cmd_docker_network_app_(){
+    local network_id=
+    ___X_CMD_CSV_APP_SHBIN_CODE="xrc docker; " \
+        ___x_cmd csv app --return var ___x_cmd_docker_network_ls_main --csv || return 1
+    network_id="$___X_CMD_CSV_APP_DATA_NETWORK_ID"
+
+    [ -n "$network_id" ] || return 0
+
+    local id=
+    local cmd=
+    ___x_cmd ui select id,cmd \
+        "Next for network: $___X_CMD_CSV_APP_DATA_NAME"     \
+        "x docker network rm $network_id"                       \
+        "x docker network rm -f $network_id"                    \
+        "x docker network inspect $network_id"                  \
+        "return 1"                                              || return 1
+    docker:debug "run command -> $cmd"
+    eval "$cmd"
+}
+
+___x_cmd_docker_network_ls_main(){
+    local IMAGE_OPTS=
+    while [ $# -gt 0 ]; do
+        case "$1" in
+            -j|--json)
+                ___x_cmd cmdstr IMAGE_OPTS --format '{{json .}}'
+                shift ;;
+            --csv)
+                ___x_cmd cmdstr IMAGE_OPTS --format 'table {{.ID}},{{.Name}},{{.Driver}},{{.Scope}},{{.IPv6}},{{.Internal}},{{.Labels}},{{.CreatedAt}}'
+                shift ;;
+            --no-trunc|-q|--quiet)
+                ___x_cmd cmdstr IMAGE_OPTS "$1"
+                shift ;;
+            -f|--filter|--format)
+                [ -n "$2" ] || {
+                    docker:error "The '$1' parameter cannot be empty."
+                    return 1
+                }
+                ___x_cmd cmdstr IMAGE_OPTS "$1" "$2"
+                shift 2 ;;
+            *)
+                docker:error "Unkown options ==> $1";  return 64 ;;
+        esac
+    done
+    eval ___x_cmd___docker_origin network ls "$IMAGE_OPTS"
+}
+
+# TODO: info, rm, rename, ...
diff --git a/mod/docker/lib/origin/ps b/mod/docker/lib/origin/ps
--- a/mod/docker/lib/origin/ps
+++ b/mod/docker/lib/origin/ps
@@ -1,14 +1,74 @@
 # shellcheck shell=dash
 
 ___x_cmd_docker_ps(){
-    local op="$1";  [ $# -eq 0 ] || shift
+    [ $# -gt 0 ] || set -- app
+
+    local op="$1"; shift
     case "$op" in
-        app|"")     ___x_cmd_docker_ps_app "$@" ;;
-        *)          ___x_cmd___docker_origin ps "$op" "$@"
+        -h|--help)  ___x_cmd help -m docker ps          ;;
+        app|"")     ___x_cmd_docker_ps_app "$@"         ;;
+
+        *)          ___x_cmd_docker_ps_main "$op" "$@"  ;;
     esac
 }
 
+# TODO: rm, stop, exec, logs ...
 ___x_cmd_docker_ps_app(){
-    ___x_cmd___docker_origin ps --format '{{json .}}' | x ja jl2c .ID .Image .Command .RunningFor .Status .Ports .Names \
-    | x csv app --header 'CONTAINER ID,IMAGE,COMMAND,CREATED,STATUS,PORTS,NAMES' --width "10%,10%,10%,10%,10%,10%,-"
+    if [ -t 1 ] && ___x_cmd_is_interactive; then
+        ___x_cmd_docker_ps_app_
+    else
+        ___x_cmd_docker_ps_main
+    fi
+}
+
+___x_cmd_docker_ps_app_(){
+    local container_id=
+    ___X_CMD_CSV_APP_SHBIN_CODE="xrc docker; " \
+        ___x_cmd csv app --return var ___x_cmd_docker_ps_main --csv || return 1
+    container_id="$___X_CMD_CSV_APP_DATA_CONTAINER_ID"
+
+    [ -n "$container_id" ] || return 0
+
+    local id=
+    local cmd=
+    ___x_cmd ui select id,cmd \
+        "Next for container: $___X_CMD_CSV_APP_DATA_REPOSITORY"     \
+        "x docker container stats   $container_id"                  \
+        "x docker container start   $container_id"                  \
+        "x docker container restart $container_id"                  \
+        "x docker container pause   $container_id"                  \
+        "x docker container stop    $container_id"                  \
+        "x docker container rm      $container_id"                  \
+        "x docker container rm -f   $container_id"                  \
+        "x docker container inspect $container_id"                  \
+        "return 1"                                              || return 1
+    docker:debug "run command -> $cmd"
+    eval "$cmd"
+}
+
+___x_cmd_docker_ps_main(){
+    local IMAGE_OPTS=
+    while [ $# -gt 0 ]; do
+        case "$1" in
+            -j|--json)
+                ___x_cmd cmdstr IMAGE_OPTS --format '{{json .}}'
+                shift ;;
+            --csv)
+                ___x_cmd cmdstr IMAGE_OPTS --format 'table {{.ID}},{{.Image}},{{.Command}},{{.RunningFor}},{{.Status}},{{.Ports}},{{.Names}},{{.Size}},{{.State}},{{.LocalVolumes}},{{.Labels}},{{.CreatedAt}},{{.Mounts}}'
+                shift ;;
+            -s|--size|-l|--latest|-a|--all|--no-trunc|-q|--quiet)
+                ___x_cmd cmdstr IMAGE_OPTS "$1"
+                shift ;;
+            -f|--filter|--format|-n|--last)
+                [ -n "$2" ] || {
+                    docker:error "The '$1' parameter cannot be empty."
+                    return 1
+                }
+                ___x_cmd cmdstr IMAGE_OPTS "$1" "$2"
+                shift 2 ;;
+            *)
+                docker:error "Unkown options ==> $1";  return 64 ;;
+        esac
+    done
+    eval ___x_cmd___docker_origin ps "$IMAGE_OPTS"
 }
