...

diff --git a/mod/ws/lib/execfile b/mod/ws/lib/execfile
--- a/mod/ws/lib/execfile
+++ b/mod/ws/lib/execfile
@@ -1,14 +1,25 @@
 
-___x_cmd_ws_execfile(){
-    local RESOURCE_NAME="$1"; shift
-
-    local ___X_CMD_SEARCH_PATH_RESULT
-    if ___x_cmd_search_path_ . ".x-cmd/$RESOURCE_NAME"; then
-        ___x_cmd_ws___exe_workspace "$___X_CMD_SEARCH_PATH_RESULT/.x-cmd/$RESOURCE_NAME" "$@"
-        return
+___x_cmd_ws___searchpath_(){
+    if ___X_CMD_SEARCH_PATH_TYPE=-d ___x_cmd_search_path_ . "$1" && [ "$___X_CMD_SEARCH_PATH_RESULT" != "$HOME" ]; then
+        ___X_CMD_WS___SEARCHPATH_=$___X_CMD_SEARCH_PATH_RESULT
     else
-        printf "Workspace Resource Not found: %s\n" "$RESOURCE_NAME" >&2
+        ___X_CMD_WS___SEARCHPATH_=
+    fi
+}
+
+___x_cmd_ws_execfile(){
+    local ___X_CMD_SEARCH_PATH_RESULT
+    ___x_cmd_ws___searchpath_ . ".x-cmd" || {
+        printf "Workspace .x-cmd fodler Not found: %s\n" "$PWD" >&2
         return 1
+    }
+
+    if [ $# -ge 1 ] && [ -f  "$___X_CMD_WS___SEARCHPATH_/.x-cmd/$1" ]; then
+        ___x_cmd_ws___exe_workspace "$___X_CMD_WS___SEARCHPATH_/.x-cmd/$1" "$@"
+    elif [ -f  "$___X_CMD_WS___SEARCHPATH_/.x-cmd/X" ]; then
+        ___x_cmd_ws___exe_workspace "$___X_CMD_WS___SEARCHPATH_/.x-cmd/X" "$@"
+    else
+        ws:error "[Resource Name=$1] or X file Not found in the workspace: $___X_CMD_WS___SEARCHPATH_/.x-cmd"
     fi
 }
 
