...

diff --git a/mod/bwh/lib/shell b/mod/bwh/lib/shell
--- a/mod/bwh/lib/shell
+++ b/mod/bwh/lib/shell
@@ -4,43 +4,56 @@
 # x bwh sh 'eval "$(curl https://get.x-cmd.com)"'
 
 ___x_cmd_bwh_sh(){
-    case "$1" in
-        --cd)       shift; ___x_cmd_bwh_sh___cd "$@"    ;;
-        --exec)     shift; ___x_cmd_bwh_sh___exec "$@"  ;;
+    [ $# -gt 0 ]   ||   set -- -h
 
-        -h|--help)  ___x_cmd_bwh_help sh;   return 1    ;;
-        *)          ___x_cmd_bwh_sh___main "$@"
+    local op="$1";  shift
+    case "$op" in
+        --cd)       ___x_cmd_bwh_sh___cd            "$@" ;;
+        --cmd)      ___x_cmd_bwh_sh___cmd           "$@" ;;
+        --script)   ___x_cmd_bwh_sh___script        "$@" ;;
+
+        # --exec)     ___x_cmd_bwh_sh___exec          "$@" ;;
+
+        -h|--help)  ___x_cmd_bwh_help sh;   return 1     ;;
+        *)          ___x_cmd_bwh_sh___cmd "$op"     "$@" ;;
     esac
-}
-
-# shellcheck disable=SC2120
-___x_cmd_bwh_sh___exec(){
-    if [ "$1" = --script ]; then
-        shift
-        [ $# -eq 1 ] || N=bwh M="Require 1 argument as <script>" log:ret:64
-        ___x_cmd_bwh_api shellScript/exec "script=$1"
-    else
-        [ $# -ge 1 ] || N=bwh M="Require at least 1 argument as <command>" log:ret:64
-        local IFS=" "
-        ___x_cmd_bwh_api basicShell/exec "command=$*"
-    fi
-}
-
-___x_cmd_bwh_sh___main(){
-    local data; data=$(___x_cmd_bwh_sh___exec "$@") || {
-        bwh:error "Fail to execute command and receive no data. cmd ==> $*"
-        return 1
-    }
-
-    local error; local message
-    printf "%s\n" "$data" | (
-        x jo env . .error .message
-        printf "%s" "$message"
-        return "$error"
-    )
 }
 
 ___x_cmd_bwh_sh___cd(){
     [ $# -eq 2 ] || N=bwh M="Require 2 argument as <currentDir> and <newDir>" log:ret:64
     ___x_cmd_bwh_api basicShell/cd "currentDir=$1" "newDir=$2"
 }
+
+___x_cmd_bwh_sh___script(){
+    [ $# -eq 1 ] || N=bwh M="Require 1 argument as <script>" log:ret:64
+    ___x_cmd_bwh_api shellScript/exec "script=$1"
+}
+
+___x_cmd_bwh_sh___cmd(){
+    [ $# -ge 1 ] || N=bwh M="Require at least 1 argument as <command>" log:ret:64
+    local IFS=" "
+    ___x_cmd_bwh_api basicShell/exec "command=$*"
+}
+
+# # shellcheck disable=SC2120
+# ___x_cmd_bwh_sh___exec(){
+#     if [ "$1" = --script ]; then
+#         shift;  ___x_cmd_bwh_sh___script    "$@"
+#     else
+#                 ___x_cmd_bwh_sh___cmd       "$@"
+#     fi
+# }
+
+# ___x_cmd_bwh_sh___main(){
+#     local data; data=$(___x_cmd_bwh_sh___exec "$@") || {
+#         bwh:error "Fail to execute command and receive no data. cmd ==> $*"
+#         return 1
+#     }
+
+#     local error; local message
+#     printf "%s\n" "$data" | (
+#         x jo env . .error .message
+#         printf "%s" "$message"
+#         return "$error"
+#     )
+# }
diff --git a/mod/shodan/lib/util b/mod/shodan/lib/util
--- a/mod/shodan/lib/util
+++ b/mod/shodan/lib/util
@@ -1,6 +1,6 @@
-# shellcheck shell=bash
+# shellcheck shell=bash disable=SC2142,SC2154
 
-alias shodan:data:ret='{ ___x_cmd_pipevar data x j2y >&2; return 1; }'
+alias shodan:data:ret='{ [ -z "$data" ] || ___x_cmd_pipevar data x j2y >&2; return 1; }'
 
 
 # Section: Interactive judge
@@ -30,17 +30,47 @@ ___x_cmd_shodan_qstr_(){
 }
 
 
-___x_cmd_shodan___lsarg_handle(){
-    case "$1" in
-        --tsv)      shift; "${XSHODAN_LSARG_FUNC}___tsv"    "$@"; return ;;
-        --csv)      shift; "${XSHODAN_LSARG_FUNC}___csv"    "$@"; return ;;
-        --raw)      shift; "${XSHODAN_LSARG_FUNC}___raw"    "$@"; return ;;
-        -j|--json)  shift; "${XSHODAN_LSARG_FUNC}___json"   "$@"; return ;;
-    esac
+___x_cmd_shodan_linecount_(){
+    local line
+    x_=0
 
-    if  ! ___x_cmd_shodan_is_interactive_env; then
-        "${XSHODAN_LSARG_FUNC}___csv" "$@"
+    if [ $# -eq 0 ]; then
+        while read -r line; do
+            [ -n "$line" ] || break
+            x_="$((x_+1))"
+        done
+
     else
-        "${XSHODAN_LSARG_FUNC}___app" "$@"
+        printf "%s\n" "$@" | while read -r line; do
+            [ -n "$line" ] || break
+            x_="$((x_+1))"
+        done
     fi
+}
+
+___x_cmd_shodan___getip_(){
+    shodan:info "Fetching the IP of the [host=$ip]"
+
+    local ips=
+    ips="$(x ip query "$ip")" || {
+        shodan:warn "Abort because of no IP found."
+        return 1
+    }
+
+    local x_
+    ___x_cmd_shodan_linecount_ "$ips"
+
+    case "$x_" in
+        0)      x_=""
+                shodan:warn "Abort because of no IP found for [host=$ip]." ;;
+        1)      x_="$ips" ;;
+        *)
+                shodan:info "[Total=$x_] IP found for [host=$ip]. Please pick one to check."
+                x_=""
+                x_="$(printf "%s\n" "$ips" | x pick)" || return
+    esac
+}
+
+___x_cmd_shodan___j2y2pick(){
+    x j2y | x pick
 }
diff --git a/mod/theme/lib/util b/mod/theme/lib/util
--- a/mod/theme/lib/util
+++ b/mod/theme/lib/util
@@ -4,6 +4,7 @@ ___X_CMD_THEME_PKG_VERSION="v0.0.3"
 ___X_CMD_THEME_PKG_PATH="${___X_CMD_ROOT_SHARED}/theme"
 ___X_CMD_THEME_PKG_TAR_NAME="${___X_CMD_THEME_PKG_VERSION}.tar.xz"
 ___X_CMD_THEME_DATA_PATH="${___X_CMD_ROOT_SHARED}/theme/ext/${___X_CMD_THEME_PKG_VERSION}"
+___X_CMD_THEME_FONT_PATH="${___X_CMD_ROOT_SHARED}/theme/font"
 ___X_CMD_THEME_EXT_ROOT="${___X_CMD_THEME_DATA_PATH}/src"
 
 # Section: font
@@ -17,16 +18,19 @@ ___x_cmd_theme_control_font() {
         _font_dir="$HOME/.local/share/fonts"
     fi
     if [ -f "$_font_dir/$_font_name" ]; then
-        theme:info "Font already installed to $_font_dir"
+        theme:info "Font [name=$_font_name] already installed to $_font_dir"
     else
+        local font_cache="$___X_CMD_THEME_FONT_PATH/nerdfont"
         local cache="${___X_CMD_THEME_PKG_PATH}/nerdfont.tgz"
-        ___x_cmd_theme___pkg_unzip font "font/nerdfont.tgz" "$cache" "$_font_dir" || return
+        ___x_cmd_theme___pkg_unzip font "font/nerdfont.tgz" "$cache" "$font_cache" || return
 
         if x hascmd fc-cache; then
             theme:info "Resetting font cache, this may take a moment..."
+            [ -d "$_font_dir" ] || x mkdirp "$_font_dir"
+            x cp "$font_cache"/* "$_font_dir"
             command fc-cache -f "$_font_dir"
         else
-            theme:warn "The fc-cache command not found, the font is in the [directory=$_font_dir]"
+            theme:warn "The fc-cache command not found, the font is in the [directory=$font_cache]"
             return 0
         fi
     fi
@@ -104,7 +108,7 @@ ___x_cmd_theme___pkg_unzip_unit(){
     local suburl="$1";  local cache="$2";   local extract_path="$3"
 
     { [ -z "$isupdate" ] && [ -f "$cache" ] ; } || ___x_cmd_theme___pkg_download "$suburl" "$cache" || return
-    x rmrf "$extract_path"
+    x rmrf "$extract_path" || return
     ___X_CMD_ZUZ_QUIET=1 x uz "$cache" "$extract_path" || {
         theme:error "Fail to extract $cache"
         x rmrf "$cache" "$extract_path"
