...

diff --git a/mod/bwh/lib/shell b/mod/bwh/lib/shell
--- a/mod/bwh/lib/shell
+++ b/mod/bwh/lib/shell
@@ -1,28 +1,46 @@
 # shellcheck    shell=dash
+
+# TODO: add support to run x-cmd
+# x bwh sh 'eval "$(curl https://get.x-cmd.com)"'
+
 ___x_cmd_bwh_sh(){
     case "$1" in
-        cd|script|exec)
-            local op="$1"; shift
-            ___x_cmd_bwh_sh_"$op" "$@"
-            ;;
-        "")
-            ___x_cmd_bwh_sh_exec "$@"
+        --cd)       shift; ___x_cmd_bwh_sh___cd "$@"    ;;
+        --exec)     shift; ___x_cmd_bwh_sh___exec "$@"  ;;
+
+        -h|--help)  ___x_cmd_bwh_help sh;   return 1    ;;
+        *)          ___x_cmd_bwh_sh___main "$@"
     esac
 }
 
-___x_cmd_bwh_sh_exec(){
-    [ $# -eq 1 ] || N=bwh M="Require 1 argument as <command>" log:ret:64
-    local IFS=" "
-    ___x_cmd_bwh_api basicShell/exec "command=$*"
-    # "command=$*"
+# shellcheck disable=SC2120
+___x_cmd_bwh_sh___exec(){
+    if [ "$1" = --script ]; then
+        shift
+        [ $# -eq 1 ] || N=bwh M="Require 1 argument as <script>" log:ret:64
+        ___x_cmd_bwh_api shellScript/exec "script=$1"
+    else
+        [ $# -ge 1 ] || N=bwh M="Require at least 1 argument as <command>" log:ret:64
+        local IFS=" "
+        ___x_cmd_bwh_api basicShell/exec "command=$*"
+    fi
 }
 
-___x_cmd_bwh_sh_script(){
-    [ $# -eq 1 ] || N=bwh M="Require 1 argument as <script>" log:ret:64
-    ___x_cmd_bwh_api shellScript/exec "script=$1"
+___x_cmd_bwh_sh___main(){
+    local data; data=$(___x_cmd_bwh_sh___exec "$@") || {
+        bwh:error "Fail to execute command and receive no data. cmd ==> $*"
+        return 1
+    }
+
+    local error; local message
+    printf "%s\n" "$data" | (
+        x jo env . .error .message
+        printf "%s" "$message"
+        return "$error"
+    )
 }
 
-___x_cmd_bwh_sh_cd(){
+___x_cmd_bwh_sh___cd(){
     [ $# -eq 2 ] || N=bwh M="Require 2 argument as <currentDir> and <newDir>" log:ret:64
     ___x_cmd_bwh_api basicShell/cd "currentDir=$1" "newDir=$2"
 }
diff --git a/mod/codi/lib/stat b/mod/codi/lib/stat
--- a/mod/codi/lib/stat
+++ b/mod/codi/lib/stat
@@ -14,52 +14,96 @@ ___x_cmd_codi_stat_cal(){
 
 }
 
-___X_CMD_CODI_FILELANG_LIST="awk
+___X_CMD_CODI_FILELANG_LIST="
+nil
+
+awk
 c
 cpp
 go
 rust
+
 java
 jar
+
+lua
+
 js
 ts
+
 python
 perl
 ruby
 julia
 r
+
 yml
 json
 jso
 toml
 xml
 html
+
 markdown
+
 graphml
+
 text
+
 sh
 bash
 zsh
 fish
+
+LICENSE
+DOCKER
+make
+git
 "
 
+# TODO: first classify using the file extension, then use the file content to classify for the file with no extension
+# file without exensions: LICENSE, README, Makefile, .gitignore, .gitmodules
+# TODO: provide --merge, like --merge sh=zsh,bash,csh
+# TODO: provide db to cache the result
 ___x_cmd_codi_stat(){
+    local output_format=""
+    while [ $# -gt 0 ]; do
+        case "$1" in
+            --csv)  output_format=csv;      shift ;;
+            --json) output_format=json;     shift ;;
+            *)      break ;;
+        esac
+    done
+
     case "$#" in
         0)      folder=. ;;        # Notice: cannot replace . with $PWD just in case the current folder path is inside a hidden folder
         *)      folder=$1; shift ;;
     esac
 
+    case "$output_format" in
+        csv)    ___x_cmd_codi_stat_main | x csv convert --col 6; return ;;
+        json)   ___x_cmd_codi_stat_main | x csv convert --col 6; return ;;  # csv convert to json
+    esac
 
-    if [ "$#" -gt 0 ]; then
-        ___x_cmd_codi_stat_main
+    # TODO: Using --csv to convert the output to csv format
+    # TODO: Using --json to convert the output to json format
+    if [ -t 1 ] && ___x_cmd_is_interative_tty; then
+        ___x_cmd_codi_stat_main | x csv convert --col 6 | x csv app
     else
-        ___x_cmd_codi_stat_main | ___x_cmd_codi_stat_merge "$@"
+        ___x_cmd_codi_stat_main
     fi
 }
 
-___x_cmd_codi_stat_main()(
+___x_cmd_codi_stat_main(){(
     command find "$folder" -type f -not -path '*/.*' | ___x_cmd_codi_stat_pipe
-)
+
+    # using other flag to indicate output format
+    # if [ "$#" -gt 0 ]; then
+    #     :
+    # else
+    #     ___x_cmd_codi_stat_main | ___x_cmd_codi_stat_merge "$@"
+    # fi
+)}
 
 # calculate function number, global variable number
 # search function
@@ -72,7 +116,7 @@ ___x_cmd_codi_stat_main()(
 # TODO: Using wc to calculate all of stat of the files
 # TODO: Display the files of the type.
 # TODO: Make it to yuhang's first level test.
-___x_cmd_codi_stat_pipe()(
+___x_cmd_codi_stat_pipe(){(
     local x_
     local fp; while read -r fp; do
         ___x_cmd_codi_filelang_ "$fp"
@@ -81,19 +125,23 @@ ___x_cmd_codi_stat_pipe()(
 
     printf "%-12s\t%s\t%s\t%s\t%s\t%s\n" lang file line lavg word char
     local type; printf "%s\n" "$___X_CMD_CODI_FILELANG_LIST" | while read -r type; do
+        [ -n "$type" ] || continue  # x drop --empty
+
         eval filenum="\"\${fsc_$type:-0}\""
         [ "$filenum" -gt 0 ] || continue
 
+        # xargs cat -- fail to handle the file with space in the name
+        # | x args 128 'cat "$@"' 2>/dev/null \ # -0 is said to work. But it is not working on my mac.
         eval "$(
-            eval printf "\"%s\n\"" "\"\$fs_$type\""  \
-                | xargs cat \
+            eval printf "\"%s\"" "\"\$fs_$type\""  \
+                | x args 'cat "$@"'  \
                 | command wc \
                 | command awk '{ printf("line=%d;word=%d;char=%d\n", $1, $2, $3); }'
         )"
         printf "%-12s\t%d\t%d\t%d\t%d\t%d\n" "$type" "$filenum" "$line" "$((line/filenum))" "$word" "$char"
     done | sort -k 2 -n -r
 
-)
+)}
 
 # sh=sh,bash,zsh
 ___x_cmd_codi_stat_merge(){
diff --git a/mod/fileage/lib/main b/mod/fileage/lib/main
--- a/mod/fileage/lib/main
+++ b/mod/fileage/lib/main
@@ -6,8 +6,9 @@
 # x fileage --in 1d -m LICENSE == x humantime in 1d "$(x fileage -m LICENSE)"
 # x fileage
 ___x_cmd_fileage___main(){
-    if [ "$1" = "--help" ] || [ "$1" = "-h" ]; then x advise gen_help "$___X_CMD_ROOT_MOD/fileage/res/advise.jso"; return ;
+    if [ "$1" = "--help" ] || [ "$1" = "-h" ]; then x help -m fileage; return ;
     fi
+
 
     local current=""; current="$(date +%s)"
 
@@ -19,7 +20,11 @@ ___x_cmd_fileage___main(){
         x humantime tosec_ "$date"
 
         ___x_cmd_fileage_stat "$@" | while read -r ts; do
-            [ -n "$ts" ] || { x log :fileage error "Get fileage failure. Please check the file exists"; return 1; }
+            [ -n "$ts" ] || {
+                x log :fileage error "Get fileage failure. Please check the file exists. TS=$ts"
+                local IFS=" "; x log :fileage error "filelist ==> $*"
+                return 1
+            }
             if [ "$((current - ts))" -ge "$___X_CMD_HUMANTIME_TOSEC_" ]; then
                 return 1
             fi
@@ -33,7 +38,11 @@ ___x_cmd_fileage___main(){
     fi
 
     ___x_cmd_fileage_stat "$@" | while read -r ts; do
-        [ -n "$ts" ] || { x log :fileage error "Get fileage failure. Please check the file exists"; return 1; }
+        [ -n "$ts" ] || {
+            x log :fileage error "Get fileage failure. Please check the file exists. TS=$ts";
+            local IFS=" "; x log :fileage error "filelist ==> $*"
+            return 1
+        }
         if [ -z "$human" ]; then  printf "%s\n" "$((current - ts))"
         else
             local ___X_CMD_HUMANTIME_SEC_
diff --git a/mod/job/lib/run b/mod/job/lib/run
--- a/mod/job/lib/run
+++ b/mod/job/lib/run
@@ -36,14 +36,10 @@ ___x_cmd_job_failfast_run(){
             ;;
     esac
 
-    if [ -z "$1" ]; then
-        job:error "Fail to start job_failfast_run() ==> Please provide function name or executable arg list"
-        return 1
-    fi
+    [ "$1" != -- ] || shift
 
-    local runner="${1:?Please provide function}"
-    [ "$runner" = -- ] || x hascmd "$runner" || {
-        job:error "Fail to start job_failfast_run() ==> $runner is not executable"
+    [ -n "$1" ] || {
+        job:error "Fail to start job_failfast_run() ==> Please provide function name or executable arg list"
         return 1
     }
 
@@ -51,9 +47,7 @@ ___x_cmd_job_failfast_run(){
 
     (
         x job failfast init "$concurrency" "$description"
-        if [ "$runner" = -- ]; then     shift; "$@"
-        else                            "$runner"
-        fi # 2>"${___X_CMD_JOB_OFFER_LOG_DISPATCHER}"
+        "$@"
     ) | (
         # TODO: Make sure it disable the flatlog
         x job failfast fini
diff --git a/mod/pkg/lib/mutate/activate b/mod/pkg/lib/mutate/activate
--- a/mod/pkg/lib/mutate/activate
+++ b/mod/pkg/lib/mutate/activate
@@ -7,7 +7,10 @@ ___x_cmd_pkg_activate(){
 ___x_cmd_pkg_activate___min(){
     local name="${1:?Provide pkg name}"
     local version="${2:-$(___x_cmd_pkg_default_version "$name")}"
+    [ -n "$version" ] || return
     local tmp="${___X_CMD_PKG_ACTIVATE___LIST#*"$name=$version"}"
+    local osarch="${4:-${___X_CMD_PKG_OSARCH:-$(___x_cmd_pkg_osarch)}}"
+    local os="${osarch%/*}";  local arch="${osarch#*/}"
 
     if ! [ "$tmp" = "$___X_CMD_PKG_ACTIVATE___LIST" ]; then
         pkg:debug "$name had been activated"
@@ -51,10 +54,12 @@ ___x_cmd_pkg_activate___min_default(){
         return 0
     fi
 
-    bin_path="${bin_path%/*}"
     pkg:debug "path add_existed_folder $bin_path"
-    ___x_cmd_path_unshift "$bin_path" || {
-        pkg:error "Path unshift failed"
-        return 1
-    }
+
+    if ! [ -f "$___X_CMD_PKG_BIN_PATH/$name" ]; then
+        chmod +x "$bin_path" && command ln -s "$bin_path"  "$___X_CMD_PKG_BIN_PATH/$name" 2>/dev/null || {
+            pkg:error "Path unshift failed"
+            return 1
+        }
+    fi
 }
diff --git a/mod/scotty/lib/mod/build b/mod/scotty/lib/mod/build
--- a/mod/scotty/lib/mod/build
+++ b/mod/scotty/lib/mod/build
@@ -1,8 +1,15 @@
 # shellcheck shell=sh disable=SC3043,2097,2012,2098,2181
 
 # In the future. We should use docker to build.
-___x_cmd_scotty_mod_build()(
+___x_cmd_scotty_mod_build(){(
     param:void
+
+    local build_advise=1
+    local build_demo=1
+    case "$1" in
+        --advise)   build_demo=;    shift ;;
+        --demo)     build_advise=;  shift ;;
+    esac
 
     local mod="$1"
     [ -n "$mod" ] || mod="$(___x_cmd_scotty_mod_name)" || {
@@ -12,50 +19,51 @@ ___x_cmd_scotty_mod_build()(
 
     log:sub:init -i "build-$mod" scotty "building mod=$mod"
 
-    ___x_cmd_scotty_mod_build___advise "$mod"
-    ___x_cmd_scotty_mod_build___demo "$mod"
-)
+    [ -z "$build_advise" ]  || ___x_cmd_scotty_mod_build___advise "$mod"
+    [ -z "$build_demo" ]    || ___x_cmd_scotty_mod_build___demo "$mod"
+)}
 
 xrc advise/latest
 
-___x_cmd_scotty_mod_build___advise()(
+___x_cmd_scotty_mod_build___advise(){(
     local mod="${1:?Provide module name}"
     scotty:info "generate advise.jso for ${mod}"
-    if ___x_cmd_advise_gen_advise "$mod" "$PWD"; then
+    ___x_cmd_advise_gen_advise "$mod" "$PWD"
+    if [ "$?" = 0 ]; then
         scotty:info "advise.jso is generated"
     else
         local code="$?"
         scotty:error "Fail to generate jso for ${mod}. Exit Code is $code"
         # TODO: exit 1 in the future
         # x:info "Finish scotty build."
-        if [ ! -f "res/advise.jso" ]; then
-            scotty:error "Finish scotty build but res/advise.jso NOT found. Please contact the module owner."
+        if [ ! -f "$___X_CMD_ROOT_ADV/$mod/advise.jso" ]; then
+            scotty:error "Finish scotty build but \$___X_CMD_ROOT_ADV/$mod/advise.jso NOT found. Please contact the module owner."
             # TODO: Will removed in the future.
-            x touch res/advise.jso
-            printf "%s\n%s\n" "{" "}" > res/advise.jso
+            x mkdirp "$___X_CMD_ROOT_ADV/$mod"
+            printf "%s\n%s\n" "{" "}" > "$___X_CMD_ROOT_ADV/$mod/advise.jso"
             # exit 1
         fi
     fi
-)
+)}
 
-___x_cmd_scotty_mod_build___demo()(
+___x_cmd_scotty_mod_build___demo(){(
     local mod="${1:?Provide module name}"
     local p=adv/demo
+    local demo_dir="${___X_CMD_ROOT_CODE}/$mod/.demo"
     [ -d "$p" ] || {
         scotty:info "return 0 but demo folder not found. "
         return 0
     }
 
-    [ -z "$___X_CMD_SCOTTY_MOD_BUILD_DEMO_FORCE" ] || {  x rmrf ".demo"; x mkdirp ".demo";   }
+    x rmrf "$demo_dir"; x mkdirp "$demo_dir"
     local i; for i in "${p}"/*.yml; do
         name="${i##*/}"
         name="${name%.yml}"
-        scotty:info "x rmrf .demo/${name}.speg; x script apply $i .demo/${name}.speg 2>/dev/null"
-        [ -n "$___X_CMD_SCOTTY_MOD_BUILD_DEMO_FORCE" ] || continue
-        x rmrf ".demo/${name}.speg"
-        x script apply "$i" ".demo/${name}.speg" 2>/dev/null || N="scotty" M="fail to generate demo for $mod" log:ret:1
+        scotty:info "x script apply $i $demo_dir/${name}.speg 2>/dev/null"
+        x rmrf "$demo_dir/${name}.speg"
+        x script apply "$i" "$demo_dir/${name}.speg" 2>/dev/null || N="scotty" M="fail to generate demo for $mod" log:ret:1
     done
 
     scotty:info "all demo are generated"
-)
+)}
 
diff --git a/mod/xrc/lib/first b/mod/xrc/lib/first
--- a/mod/xrc/lib/first
+++ b/mod/xrc/lib/first
@@ -24,26 +24,33 @@ ___x_cmd_first(){
 }
 
 # shellcheck disable=SC2016
+
 ___x_cmd_first_(){
     local op="$1";  shift
     case "$op" in
-        file)       op='[ -f "$1" ]'    ___x_cmd_first___exec   "$@"    ;;
-        folder)     op='[ -d "$1" ]'    ___x_cmd_first___exec   "$@"    ;;
-        existed)    op='[ -e "$1" ]'    ___x_cmd_first___exec   "$@"    ;;
-        *)                              ___x_cmd_first___exec   "$@"    ;;
+        -f|file)        op=-f   ___x_cmd_first___exec   "$@"    ;;
+        -d|folder)      op=-d   ___x_cmd_first___exec   "$@"    ;;
+        -e|existed)     op=-e   ___x_cmd_first___exec   "$@"    ;;
+        *)                      ___x_cmd_first___exec   "$@"    ;;
     esac
 }
 
 ___x_cmd_first___exec(){
+    if [ $# -eq 0 ]; then
+        while read -r x_; do
+            ! test "$op" "$x_" || {
+                return 0        # I doubt it may result in pipe fail in some occassion. It happened in gitb.
+            }
+        done
+    else
+        while [ $# -gt 0 ]; do
+            ! test "$op" "$1" || {
+                x_="$1"
+                return 0
+            }
+            shift
+        done
+    fi
     x_=
-    while [ $# -gt 0 ]; do
-        ! eval "$op" || {
-            x_="$1"
-            return 0
-        }
-        shift
-    done
     return 1
 }
-
-
