...

diff --git a/mod/ddgo/lib/dump b/mod/ddgo/lib/dump
--- a/mod/ddgo/lib/dump
+++ b/mod/ddgo/lib/dump
@@ -34,7 +34,12 @@ ___x_cmd_ddgo___dump_app(){
 }
 
 ___x_cmd_ddgo___dump_yml(){
-    ___x_cmd_ddgo___dump_raw "$@" | ___x_cmd_ddgo___parse_yml
+    local data
+    data="$(___x_cmd_ddgo___dump_raw "$@")"
+    [ -n "$data" ] || return 1
+    ___x_cmd_ddgo___parse_yml <<A
+$data
+A
 }
 
 ___x_cmd_ddgo___dump_json(){
@@ -48,7 +53,22 @@ ___x_cmd_ddgo___dump_raw(){
     local x_
     ___x_cmd_ddgo___url_ "$@"
 
-    ___x_cmd_ddgo___execlink dump "$x_"
+    # 2 second ...
+    ___x_cmd_ddgo___execlink dump -receive-timeout 2 "$x_" || {
+        ddgo:error "Failed to fetch data from ddgo"
+        if ___x_cmd_ddgo___isproxyset; then
+            ddgo:error "Timeout when visiting duckduckgo.com."
+            ddgo:info "You have set proxy, check your proxy settings."
+            ddgo:info "[TIPS] You can set proxy for ddgo -> x ddgo init"
+            ddgo:info "[TIPS] You can set proxy in this shell session -> x proxy set <proxy>"
+            return 1
+        else
+            ddgo:error "Timeout when visiting duckduckgo.com."
+            ddgo:info "[TIPS] You can set proxy for ddgo -> x ddgo init"
+            ddgo:info "[TIPS] You can set proxy in this shell session -> x proxy set <proxy>"
+            return 1
+        fi
+    }
 }
 
 ___x_cmd_ddgo___top(){
@@ -67,13 +87,14 @@ ___x_cmd_ddgo_dump___view_app___(){
 
     local ___X_CMD_CSV_APP_SHBIN_CODE="xrc ddgo; "
         ___x_cmd_ddgo___dump_yml "$@" | x y2j |                        \
-            x ja 2c .short .update .long .url | {                        \
-            x csv --app --header  Title,Update,Msg,Url                   \
-                        --return var                                     \
-                        --action o Open 'Open on website'                \
-                        --action c Copy 'Copy URL'                       \
-                        --processor '___x_cmd_ddgo_dump___view_app_open' \
-                        --preview Msg,Url
+            x ja 2c .short .update .long .url | {                           \
+            x csv --app --header  Title,Update,Msg,Url                      \
+                        --return var                                        \
+                        --action o Open 'Open on website'                   \
+                        --action c Copy 'Copy URL'                          \
+                        --processor '___x_cmd_ddgo_dump___view_app_open'    \
+                        --table-view Title,Update                           \
+                        --preview Title,Msg,Url
 
             [ -n "$___X_CMD_CSV_APP_DATA_Msg" ] || return 0
             local id=
