...

diff --git a/mod/p7zip/lib/main b/mod/p7zip/lib/main
--- a/mod/p7zip/lib/main
+++ b/mod/p7zip/lib/main
@@ -31,15 +31,15 @@ _7zd_which(){
             exe=7zd.${osname}.${arch}  
         ;;
         *)
-            p7zd_log error "Unsupported [arch=$arch] [os=$osname]!" >&2; 
+            p7zd:error "Unsupported [arch=$arch] [os=$osname]!" >&2; 
             return 1 
         ;;
     esac
-    p7zd_log debug "Downloading: p7zip/main/bin/$exe"
+    p7zd:debug "Downloading: p7zip/main/bin/$exe"
     if CACHE="$target/$exe" ___x_cmd_httpget_gitx static-build "p7zip" main "7zd/19.00/$exe" "$target/$exe"; then
         chmod +x "$target/$exe" && printf "%s" "$target/$exe"
     else
-        p7zd_log error "Fail to download: p7zip/main/bin/$exe"
+        p7zd:error "Fail to download: p7zip/main/bin/$exe"
         return 1
     fi
 }
