...

diff --git a/mod/whisper/lib/model/download b/mod/whisper/lib/model/download
--- a/mod/whisper/lib/model/download
+++ b/mod/whisper/lib/model/download
@@ -1,7 +1,8 @@
+# shellcheck shell=dash
 
 ___x_cmd_whisper_model_download(){
     local x_=""
-    ___x_cmd_whisper_model_download_ "${modelName}" || return 1
+    ___x_cmd_whisper_model_download_ "$@" || return 1
     printf "%s" "${x_}"
 }
 
@@ -10,9 +11,26 @@ ___x_cmd_whisper_model_download_(){
     local url="ggerganov/whisper.cpp/resolve/main"
     [ -n "$modelName" ] || N=whisper M="modelName is empty" log:ret:1
 
-    [ -f "$___X_CMD_ROOT_DATA/model/${modelName}.bin" ] || {
-        x huggingface --publicdownload "${url}"/"ggml-${modelName}.bin" "${modelName}.bin" || N=whisper M="download model ${1} failed" log:ret:1
-    }
+    local tmpfp="$___X_CMD_ROOT_TMP/model/${modelName}.bin"
+    x ensurefp "$tmpfp"
 
-    x_="$___X_CMD_ROOT_DATA/model/${modelName}.bin"
+    local tgtfp="$___X_CMD_ROOT_DATA/model/${modelName}.bin"
+
+    [ -f "$tgtfp" ] || (
+        x huggingface --publicdownload "${url}"/"ggml-${modelName}.bin" "$tmpfp" || {
+            ___x_cmd_whisper_model_download___clean
+            return
+        }
+    )
+
+    # TODO: in the future, check the hash
+
+    x mv "$tmpfp" "$tgtfp"
+    x_="$tgtfp"
+}
+
+___x_cmd_whisper_model_download___clean(){
+    x rmrf "$tmpfp"
+    whisper:error "download model $modelName failed"
+    return 1
 }
