...

diff --git a/mod/fjo/lib/repo/release/attachment/rm b/mod/fjo/lib/repo/release/attachment/rm
--- a/mod/fjo/lib/repo/release/attachment/rm
+++ b/mod/fjo/lib/repo/release/attachment/rm
@@ -1,14 +1,25 @@
-# shellcheck shell=bash disable=SC2034,SC2154 disable=SC2154
+# shellcheck shell=dash disable=SC2034,SC2154
 # https://gitea.com/api/swagger#/repository/repoDeleteReleaseAttachment
 ___x_cmd_fjo_repo_release_attachment_rm() {
-
-
     param:scope     ___x_cmd_fjo
     param:dsl    '
 options:
-    #1        "Release ID"                <>:number
+    #1              "Release Attachment ID"                     <>:Number
+    --repo|-r       "<owner_path>/<repo_path>"                  <>:RepoName
+    --release_id    "Release ID"                                <>:Number
+    --yes|-y        "Ignore remove prompt interception"
 '
     param:run
-    local release="${1:?release id must be specified}"
-    ___x_cmd_fjo_repo_release_init_owner_repo_and_release
+    ___x_cmd_fjo_param_init_owner_repo
+    [ "$yes" = "true" ] || ___x_cmd_ui_yesno "Are you sure you want to remove release attachment $(___x_cmd_ui bold red "$1") on $owner_repo repo ?" || return
+    ___x_cmd_fjo_curl del "/repos/${owner_repo}/releases/${release_id}/assets/${1##*/}" | (
+            x jo env . fjo_resp_err=.message
+            if ___x_cmd_fjo_http_error; then
+                ___x_cmd_ui_tf  true "Remove ${owner_repo} ${1##*/} release attachment successfully"
+            else
+                ___x_cmd_ui_tf false "Remove ${owner_repo} ${1##*/} release attachment failure" >&2
+                ___x_cmd_fjo____handle_resp
+                return 1
+            fi
+        )
 }
diff --git a/mod/fjo/lib/utils b/mod/fjo/lib/utils
--- a/mod/fjo/lib/utils
+++ b/mod/fjo/lib/utils
@@ -61,6 +61,9 @@ ___x_cmd_fjo_curl(){
     local ___X_CMD_API_TEA_TOKEN=""
     local ___X_CMD_API_TEA_ENDPOINT=""
     ___x_cmd_fjo_cur   ___X_CMD_API_TEA_TOKEN:=token ___X_CMD_API_TEA_ENDPOINT:=endpoint 2>/dev/null
+    if [ -z "$___X_CMD_API_TEA_ENDPOINT" ]; then
+        ___X_CMD_API_TEA_ENDPOINT="$(___x_cmd_fjo___get_web_endpoint)/api/v1" || return 1
+    fi
 
     local ___X_CMD_FJO_SHOW_HTTP_CODE=1
     case "$op" in
@@ -74,6 +77,19 @@ ___x_cmd_fjo_curl(){
             ;;
         post|put|patch|del)
             ___x_cmd_api_tea "$op" "$_api_url" "$(x curl gencode "$@")"
+            ___x_cmd_fjo_http_error
+            ;;
+        upload)
+            [ -n "$1" ] || M='Please provide upload filepath' arg:ret:64
+            local __file_path="$1"; shift;
+            local __file_type="\"Content-Type: ${file_type:-"multipart/form-data"}\""
+            ___X_CMD_API_TEA_HEADER="-L -# -D \"$___X_CMD_FJO_TMP/.____x_cmd_fjo_curl_header.$$\" -H \"accept: application/json\" -H ${__file_type}"
+            [ -f "$__file_path" ] || {
+                fjo:error "Upload Failure. Not found target file. Please check [file=$__file_path] exist"
+                return 1
+            }
+            fjo:info "Uploading file $1..."
+            ___x_cmd_api_tea "${___X_CMD_FJO_UPLOAD_REQ_METHOD:-"post"}" "$_api_url" -F "attachment=@\"$__file_path\""
             ___x_cmd_fjo_http_error
             ;;
     esac
