...

diff --git a/mod/env/lib/config b/mod/env/lib/config
--- a/mod/env/lib/config
+++ b/mod/env/lib/config
@@ -17,7 +17,11 @@ ___x_cmd_env_config_load(){
         local script_path="${version_and_srcipt#"$version"}"
         script_path="${script_path#=}"
 
-        ___x_cmd_env boot  "${name}=${version}"
+        if [ -n "$script_path" ];then
+            . "$script_path" || {
+                env:error "Source $script_path failed" ; return 1
+            }
+        fi
 
     done <"$___X_CMD_ENV_VERSION_CONFIG_PATH"
 }
diff --git a/mod/pkg/lib/mutate/addpath b/mod/pkg/lib/mutate/addpath
--- a/mod/pkg/lib/mutate/addpath
+++ b/mod/pkg/lib/mutate/addpath
@@ -1,8 +1,8 @@
 # shellcheck    shell=sh            disable=SC3043,SC1090,SC2155     # xrc
 
-___x_cmd_pkg_pathenv(){
+___x_cmd_pkg_addpath(){
     case "$1" in
-        -h|--help) ___x_cmd_pkg_help pathenv ; return 1 ;;
+        -h|--help) ___x_cmd_pkg_help addpath ; return 1 ;;
     esac
 
     local name="${1:?Provide pkg name}"
@@ -16,8 +16,8 @@ ___x_cmd_pkg_pathenv(){
         return 0
     fi
 
-    if ! ___x_cmd_pkg_pathenv___min_default "$name" "$version" "$path_dir"; then
-        pkg:error "Use default pathenv  failed for $name $version"
+    if ! ___x_cmd_pkg_addpath___min_default "$name" "$version" "$path_dir"; then
+        pkg:error "Use default add path  failed for $name $version"
         return 1
     fi
 
@@ -27,7 +27,7 @@ $name=$version
 "
 }
 
-___x_cmd_pkg_pathenv___min_default(){
+___x_cmd_pkg_addpath___min_default(){
     local name="${1:?Provide pkg name}"
     local version="${2:?Provide version}"
     local path_dir="${3:-"bin"}"
@@ -61,5 +61,5 @@ ___x_cmd_pkg_pathenv___min_default(){
     done <<A
 $mutiple_bin_path
 A
-
+    pkg:info "Add PATH of $name successfully"
 }
diff --git a/mod/pkg/lib/mutate/rmpath b/mod/pkg/lib/mutate/rmpath
--- a/mod/pkg/lib/mutate/rmpath
+++ b/mod/pkg/lib/mutate/rmpath
@@ -1,18 +1,18 @@
 # shellcheck    shell=dash           disable=SC3043,SC1090      # xrc
 
-___x_cmd_pkg_deactivate(){
+___x_cmd_pkg_rmpath(){
 
     case "$1" in
         -h|--help)
-            ___x_cmd_pkg_help deactivate "$1"
+            ___x_cmd_pkg_help rmpath "$1"
             return 1
             ;;
     esac
 
-    ___x_cmd_pkg_deactivate___min "$@"
+    ___x_cmd_pkg_rmpath___min "$@"
 }
 
-___x_cmd_pkg_deactivate___min(){
+___x_cmd_pkg_rmpath___min(){
     local name="${1:?Provide pkg name}"
     local version
     local _line
@@ -23,19 +23,16 @@ ___x_cmd_pkg_deactivate___min(){
         fi
     done <<A
 $___X_CMD_PKG_ACTIVATE___LIST
-
 A
 
     if [ -z "$version" ]; then
-        pkg:warn "$name had been deactivated"
+        pkg:warn "PATH of $name had been removed "
         # TODO: What should I return ?
         return 0
     fi
 
-    local osarch="${3:-${___X_CMD_PKG_OSARCH:-$(___x_cmd_pkg_osarch)}}"
-
-    ___x_cmd_pkg_deactivate___min_default "$name" "$version" || {
-        pkg:error "Deactivate $name $version failed"
+    ___x_cmd_pkg_rmpath___min_default "$name" "$version" || {
+        pkg:error "Removed PATH failed : $name $version"
         return 1
     }
 
@@ -51,14 +48,14 @@ A
     fi
 }
 
-___x_cmd_pkg_deactivate___min_default(){
+___x_cmd_pkg_rmpath___min_default(){
     local name="${1:?Provide pkg name}"
     local version="${2:-$(___x_cmd_pkg_default_version "$name")}"
     local path_dir="${3:-"bin"}"
     local tgt="$___X_CMD_PKG_POPULATE_PATH/$name/$version"
     local mutiple_bin_path
 
-    if ! mutiple_bin_path="$(___x_cmd_pkg___link "$name" "$version" "x" "path.${path_dir}" )" ; then
+    if ! mutiple_bin_path="$(___x_cmd_pkg___link "$name" "$version" "" "path.${path_dir}" )" ; then
         pkg:error "Get bin path failed for $name $version"
         return 1
     fi
@@ -76,4 +73,5 @@ ___x_cmd_pkg_deactivate___min_default(){
     done <<A
 $mutiple_bin_path
 A
+    pkg:info "Remove PATH of $name successfully"
 }
