...

diff --git a/mod/env/lib/main b/mod/env/lib/main
--- a/mod/env/lib/main
+++ b/mod/env/lib/main
@@ -17,80 +17,20 @@ ___x_cmd_env___pasre_pkg_version(){
     esac
 }
 
-# use = try + save-config
+# use = download + populate + link + linkenv + boot + save config
 ___x_cmd_env_use(){
+    local dir_path
     case "$1" in
-        -h|--help)
-            ___x_cmd_env___help use
-            return 1
-            ;;
+        --ws) shift; dir_path="${1}"; shift ;;
+        -h|--help) ___x_cmd_env___help use;  return 1 ;;
     esac
 
-    local ___X_CMD_ENV___PARSE_VERSION
-    local ___X_CMD_ENV___PARSE_PKG
     local ___X_CMD_ENV_LSENV_APP_CANDIDATE
     [ $# -gt 0 ] || ___x_cmd_env_lsenv_app || return 1
     [ -z "$___X_CMD_ENV_LSENV_APP_CANDIDATE" ] || set -- "$___X_CMD_ENV_LSENV_APP_CANDIDATE"
 
     x:trace env/use
-    if ! ___x_cmd_env_try "$@" ; then
-        env:error "Failed to use $*"
-        return 1
-    fi
 
-    local script_path
-    local code="___x_cmd_env___configstr_set_ \"\$(cat \"\$___X_CMD_ENV_VERSION_CONFIG_PATH\")\$___X_CMD_UNSEENCHAR_NEWLINE\""
-    local i; for i in "$@"; do
-        ___x_cmd_env___pasre_pkg_version "$i"
-        if [ -z "$___X_CMD_ENV___PARSE_VERSION" ]; then
-            env:warn "Not found $___X_CMD_ENV___PARSE_PKG version."
-            return 1
-        fi
-
-        script_path="$(___x_cmd_pkg___get_script_path "$___X_CMD_ENV___PARSE_PKG" "$___X_CMD_ENV___PARSE_VERSION" "" activate)"
-        env:debug "{ script_path: ""$script_path", "___X_CMD_ENV___PARSE_PKG: " "$___X_CMD_ENV___PARSE_PKG", "___X_CMD_ENV___PARSE_VERSION: " "$___X_CMD_ENV___PARSE_VERSION }"
-        code="$code $___X_CMD_ENV___PARSE_PKG=$___X_CMD_ENV___PARSE_VERSION=$script_path"
-    done
-
-    local ___X_CMD_ENV___CONFIGSTR_SET_;    eval "$code"
-    ___x_cmd_env_config___write "$___X_CMD_ENV___CONFIGSTR_SET_" ||  return 1
-}
-
-___x_cmd_env_unuse(){
-    case "$1" in
-        -h|--help)
-            ___x_cmd_env___help unuse
-            return 1
-            ;;
-    esac
-
-    x:trace env/unuse
-    ___x_cmd_env_untry "$@" || {
-        env:error "Cannot untry $@"
-        return 1
-    }
-
-    local unuse_tmp; unuse_tmp="$(cat "$___X_CMD_ENV_VERSION_CONFIG_PATH")$___X_CMD_UNSEENCHAR_NEWLINE"
-    local i; for i in "$@"; do
-        ___x_cmd_env___sdict rm unuse_tmp "${i%%=*}"
-    done
-
-    ___x_cmd_env_config___write "$unuse_tmp" "$___X_CMD_ENV_VERSION_CONFIG_PATH" || {
-        env:error "Cant't write "
-        return 1
-    }
-}
-
-# try = install + activate
-___x_cmd_env_try(){
-    case "$1" in
-        -h|--help)
-            ___x_cmd_env___help try
-            return 1
-            ;;
-    esac
-
-    x:trace env/try
     local ___X_CMD_ENV___PARSE_PKG
     local ___X_CMD_ENV___PARSE_VERSION
 
@@ -102,28 +42,121 @@ ___x_cmd_env_try(){
             return 1
         fi
 
-        env:debug "Prepare $___X_CMD_ENV___PARSE_PKG $___X_CMD_ENV___PARSE_VERSION"
-        if ! ___x_cmd_pkg install "$___X_CMD_ENV___PARSE_PKG" "$___X_CMD_ENV___PARSE_VERSION"; then
-            env:error "Cannot install package - '$___X_CMD_ENV___PARSE_PKG $___X_CMD_ENV___PARSE_VERSION'"
+        env:debug "Step 1/4: Downloading $___X_CMD_ENV___PARSE_PKG $___X_CMD_ENV___PARSE_VERSION"
+        if ! ___x_cmd_pkg download "$___X_CMD_ENV___PARSE_PKG" "$___X_CMD_ENV___PARSE_VERSION"; then
+            env:error "Cannot download package - '$___X_CMD_ENV___PARSE_PKG $___X_CMD_ENV___PARSE_VERSION'"
             return 1
         fi
 
-        if ! ___x_cmd_env___store_prev "$___X_CMD_ENV___PARSE_PKG" ; then
-            env:error "Cannot store previous version of $___X_CMD_ENV___PARSE_PKG"
+        env:debug "Step 2/4: Populating $___X_CMD_ENV___PARSE_PKG $___X_CMD_ENV___PARSE_VERSION"
+        if ! ___x_cmd_pkg populate "$___X_CMD_ENV___PARSE_PKG" "$___X_CMD_ENV___PARSE_VERSION" ; then
+            env:error "Cannot populate package - '$___X_CMD_ENV___PARSE_PKG $___X_CMD_ENV___PARSE_VERSION'"
             return 1
         fi
 
-        ___x_cmd_pkg deactivate "$___X_CMD_ENV___PARSE_PKG" 2>/dev/null || true
-        if ! ___x_cmd_pkg activate "$___X_CMD_ENV___PARSE_PKG" "$___X_CMD_ENV___PARSE_VERSION" ; then
-            env:error "Cannot activate $___X_CMD_ENV___PARSE_PKG $___X_CMD_ENV___PARSE_VERSION"
+        env:debug "Step 3/4: Linking $___X_CMD_ENV___PARSE_PKG $___X_CMD_ENV___PARSE_VERSION"
+        ___x_cmd_pkg link "$___X_CMD_ENV___PARSE_PKG" "$___X_CMD_ENV___PARSE_VERSION" "$dir_path"  || {
+            env:error "Cannot link $___X_CMD_ENV___PARSE_PKG $___X_CMD_ENV___PARSE_VERSION"
+            return 1
+        }
+
+        env:debug "Step 4/4: Booting $___X_CMD_ENV___PARSE_PKG $___X_CMD_ENV___PARSE_VERSION"
+        ___x_cmd_env_boot "--tip" "${___X_CMD_ENV___PARSE_PKG}=${___X_CMD_ENV___PARSE_VERSION}"
+        code="$code $___X_CMD_ENV___PARSE_PKG=$___X_CMD_ENV___PARSE_VERSION"
+    done
+
+    local ___X_CMD_ENV___CONFIGSTR_SET_;    eval "___x_cmd_env___configstr_set_ \"\$___X_CMD_ENV_VERSION_CONFIG\" $code"
+    env:info "Successfully set ${code# } in the current environment."
+    ___X_CMD_ENV_VERSION_CONFIG="$___X_CMD_ENV___CONFIGSTR_SET_"
+
+    ___x_cmd_env_use___save_config "$@"
+}
+
+___x_cmd_env_use___save_config(){
+    local ___X_CMD_ENV___PARSE_PKG
+    local ___X_CMD_ENV___PARSE_VERSION
+    local boot_script_path
+    local code="___x_cmd_env___configstr_set_ \"\$(cat \"\$___X_CMD_ENV_VERSION_CONFIG_PATH\")\$___X_CMD_UNSEENCHAR_NEWLINE\""
+    local i; for i in "$@"; do
+        ___x_cmd_env___pasre_pkg_version "$i"
+        if [ -z "$___X_CMD_ENV___PARSE_VERSION" ]; then
+            env:warn "Not found $___X_CMD_ENV___PARSE_PKG version."
             return 1
         fi
 
-        if ! ___x_cmd_env___store_current "$___X_CMD_ENV___PARSE_PKG" "$___X_CMD_ENV___PARSE_VERSION" ; then
-            env:error "Cannot store current version of $___X_CMD_ENV___PARSE_PKG"
+        boot_script_path="$(___x_cmd_pkg___get_script_path "$___X_CMD_ENV___PARSE_PKG" "$___X_CMD_ENV___PARSE_VERSION" "" boot)"
+        env:debug "{ boot_script_path: ""$boot_script_path", "___X_CMD_ENV___PARSE_PKG: " "$___X_CMD_ENV___PARSE_PKG", "___X_CMD_ENV___PARSE_VERSION: " "$___X_CMD_ENV___PARSE_VERSION }"
+        code="$code $___X_CMD_ENV___PARSE_PKG=$___X_CMD_ENV___PARSE_VERSION=$boot_script_path"
+    done
+
+    local ___X_CMD_ENV___CONFIGSTR_SET_;    eval "$code"
+    ___x_cmd_env_config___write "$___X_CMD_ENV___CONFIGSTR_SET_" ||  return 1
+}
+
+___x_cmd_env_unuse(){
+    local dir_path
+    case "$1" in
+        --ws) shift; dir_path="${1}"; shift ;;
+        -h|--help) ___x_cmd_env___help unuse;  return 1 ;;
+    esac
+    x:trace env/unuse
+    local j; for j in "$@"; do
+    ___x_cmd_env___pasre_pkg_version "$j"
+    ___x_cmd_pkg_unlink "$___X_CMD_ENV___PARSE_PKG" "$___X_CMD_ENV___PARSE_VERSION" "$dir_path" || {
+        env:error "Cannot unuse $j"
+        return 1
+    }
+    done
+
+    local unuse_tmp; unuse_tmp="$(cat "$___X_CMD_ENV_VERSION_CONFIG_PATH")$___X_CMD_UNSEENCHAR_NEWLINE"
+
+    local i; for i in "$@"; do
+        ___x_cmd_env___sdict rm unuse_tmp "${i%%=*}"
+    done
+    ___x_cmd_env_config___write "$unuse_tmp" "$___X_CMD_ENV_VERSION_CONFIG_PATH" || {
+        env:error "Can't write into env config "
+        return 1
+    }
+}
+
+
+# try = download + populate + linkenv + boot
+___x_cmd_env_try(){
+    local dir_path
+    case "$1" in
+        -h|--help) ___x_cmd_env___help try;  return 1 ;;
+    esac
+    local ___X_CMD_ENV___PARSE_PKG
+    local ___X_CMD_ENV___PARSE_VERSION
+
+    local code
+    local i; for i in "$@"; do
+        ___x_cmd_env___pasre_pkg_version "$i"
+        if [ -z "$___X_CMD_ENV___PARSE_VERSION" ]; then
+            env:warn "Not found $___X_CMD_ENV___PARSE_PKG version"
             return 1
         fi
 
+        env:debug "Step 1/4: Downloading $___X_CMD_ENV___PARSE_PKG $___X_CMD_ENV___PARSE_VERSION"
+        if ! ___x_cmd_pkg download "$___X_CMD_ENV___PARSE_PKG" "$___X_CMD_ENV___PARSE_VERSION" "" "$dir_path"; then
+            env:error "Cannot download package - '$___X_CMD_ENV___PARSE_PKG $___X_CMD_ENV___PARSE_VERSION'"
+            return 1
+        fi
+
+        env:debug "Step 2/4: Populating $___X_CMD_ENV___PARSE_PKG $___X_CMD_ENV___PARSE_VERSION"
+        if ! ___x_cmd_pkg populate "$___X_CMD_ENV___PARSE_PKG" "$___X_CMD_ENV___PARSE_VERSION" "" "$dir_path"; then
+            env:error "Cannot populate package - '$___X_CMD_ENV___PARSE_PKG $___X_CMD_ENV___PARSE_VERSION'"
+            return 1
+        fi
+
+        env:debug "Step 3/4: Add PATH $___X_CMD_ENV___PARSE_PKG $___X_CMD_ENV___PARSE_VERSION"
+        ___x_cmd_pkg pathenv "$___X_CMD_ENV___PARSE_PKG" "$___X_CMD_ENV___PARSE_VERSION" || {
+            env:error "Cannot add path into env: $___X_CMD_ENV___PARSE_PKG $___X_CMD_ENV___PARSE_VERSION"
+            return 1
+        }
+
+        env:debug "Step 4/4: Booting $___X_CMD_ENV___PARSE_PKG $___X_CMD_ENV___PARSE_VERSION"
+        ___x_cmd_env_boot "--tip" "${___X_CMD_ENV___PARSE_PKG}=${___X_CMD_ENV___PARSE_VERSION}"
         code="$code $___X_CMD_ENV___PARSE_PKG=$___X_CMD_ENV___PARSE_VERSION"
     done
 
@@ -132,8 +165,6 @@ ___x_cmd_env_try(){
     ___X_CMD_ENV_VERSION_CONFIG="$___X_CMD_ENV___CONFIGSTR_SET_"
 }
 
-
-# TODO
 ___x_cmd_env_untry(){
     case "$1" in
         -h|--help)
@@ -143,16 +174,16 @@ ___x_cmd_env_untry(){
     esac
 
     x:trace env/untry
-    local pkg_name
-    local version     #TODO: Where to use it?
+    local ___X_CMD_ENV___PARSE_PKG
+    local ___X_CMD_ENV___PARSE_VERSION
     local ___X_CMD_ENV_PREV
 
     local code="___x_cmd_env___configstr_set_ \"\$___X_CMD_ENV_VERSION_CONFIG\""
 
     local i; for i in "$@"; do
-        pkg_name="${i%=*}"
-        ___x_cmd_pkg deactivate "$pkg_name"
-        code="$code $pkg_name="
+        ___x_cmd_env___pasre_pkg_version "$i"
+        ___x_cmd_pkg deactivate "$___X_CMD_ENV___PARSE_PKG" "$___X_CMD_ENV___PARSE_VERSION"
+        code="$code $___X_CMD_ENV___PARSE_PKG="
     done
 
     local ___X_CMD_ENV___CONFIGSTR_SET_;    eval "$code"
diff --git a/mod/pkg/lib/main b/mod/pkg/lib/main
--- a/mod/pkg/lib/main
+++ b/mod/pkg/lib/main
@@ -1,4 +1,4 @@
-# shellcheck    shell=sh            disable=SC3043      # xrc
+# shellcheck    shell=dash
 
 
 # # Rely on ll or ls
@@ -25,22 +25,21 @@
 
 ___x_cmd_pkg___which_p7zip()(
     ___x_cmd_mkdirp "$___X_CMD_PKG_RAW_PATH"
-    local p7zip="$___X_CMD_PKG_BASE_PATH/all.7z"
-    if ! ___x_cmd_httpget_gitx x-cmd pkg main "dist/all.7z" "$p7zip" "${1:-86400}"; then # 1-day
-        if [ ! -f "$p7zip" ]; then
-            pkg:error "Unaviable all.7z. Unable to fetch all.7z."
+    local file_path="$___X_CMD_PKG_BASE_PATH/$___X_CMD_PKG_VERSION.tar.xz"
+    if ! ___x_cmd_httpget_gitx x-cmd pkg main "dist/$___X_CMD_PKG_VERSION.tar.xz" "$file_path" ""; then # 1-day
+        if [ ! -f "$file_path" ]; then
+            pkg:error "Unaviable $___X_CMD_PKG_VERSION.tar.xz. Unable to fetch $___X_CMD_PKG_VERSION.tar.xz."
             return 1
         fi
     fi
 
     if [ "$___X_CMD_HTTPGET_AGE" = 0 ]; then
-        xrc p7zip
         x rmrf "$___X_CMD_PKG_RAW_PATH"
         ___x_cmd_mkdirp "$___X_CMD_PKG_RAW_PATH"
-        pkg:debug "Deflate the all.7z"
-        if ! ( cd "${p7zip%/*}" && cp all.7z raw/all.7z && cd raw && p7zd x all.7z -y 1>/dev/null && x rmrf all.7z ); then
+        pkg:debug "Deflate the $___X_CMD_PKG_VERSION.tar.xz"
+        if ! ( cd "${file_path%/*}" && cp "$___X_CMD_PKG_VERSION.tar.xz" raw/"$___X_CMD_PKG_VERSION.tar.xz" && cd raw && x uz "$___X_CMD_PKG_VERSION.tar.xz" 1>/dev/null && x rmrf "$___X_CMD_PKG_VERSION.tar.xz" ); then
             pkg:error "Deflation failure."
-            x rmrf "$p7zip"
+            x rmrf "$file_path"
         fi
     fi
 )
@@ -53,8 +52,8 @@ ___x_cmd_pkg_update(){
             return 1
             ;;
     esac
+    pkg:info "Update the $___X_CMD_PKG_VERSION.tar.xz"
     ___x_cmd_pkg___which_p7zip - || return # Force Update
-    pkg:info "Update the all.7z"
 }
 
 ___x_cmd_pkg_help(){
diff --git a/mod/pkg/lib/mutate/activate b/mod/pkg/lib/mutate/activate
--- a/mod/pkg/lib/mutate/activate
+++ b/mod/pkg/lib/mutate/activate
@@ -1,99 +1,65 @@
 # shellcheck    shell=sh            disable=SC3043,SC1090,SC2155     # xrc
 
-___x_cmd_pkg_activate(){
-
+___x_cmd_pkg_pathenv(){
     case "$1" in
-        -h|--help)
-            ___x_cmd_pkg_help activate
-            return 1
-            ;;
+        -h|--help) ___x_cmd_pkg_help pathenv ; return 1 ;;
     esac
 
-    ___x_cmd_pkg_activate___min "$@"
-}
-
-___x_cmd_pkg_activate___min(){
     local name="${1:?Provide pkg name}"
     local version="${2:-$(___x_cmd_pkg_default_version "$name")}"
+    local path_dir="${3:-"bin"}"
     [ -n "$version" ] || return
     local tmp="${___X_CMD_PKG_ACTIVATE___LIST#*"$name=$version"}"
-    local osarch="${4:-${___X_CMD_PKG_OSARCH:-$(___x_cmd_pkg_osarch)}}"
-    local os="${osarch%/*}";  local arch="${osarch#*/}"
 
     if ! [ "$tmp" = "$___X_CMD_PKG_ACTIVATE___LIST" ]; then
-        pkg:debug "$name had been activated"
-        # TODO: What should I return ?
+        pkg:debug "$name had been add into path"
         return 0
     fi
 
-    local script_path="$3"
-
-    if [ -z "$script_path" ] && \
-            ! script_path="$(___x_cmd_pkg___get_script_path "$name" "$version" "${___X_CMD_PKG_OSARCH:-$(___x_cmd_pkg_osarch)}" activate)"; then
-
-        if ! ___x_cmd_pkg_activate___min_default "$name" "$version" ; then
-            pkg:error "Use default activate script failed for $name"
-            return 1
-        fi
-    else
-        pkg:debug "Activate running $script_path for $name $version"
-        if ! . "${script_path}" ; then
-            pkg:error "Source $script_path failed"
-            return 1
-        fi
+    if ! ___x_cmd_pkg_pathenv___min_default "$name" "$version" "$path_dir"; then
+        pkg:error "Use default pathenv  failed for $name $version"
+        return 1
     fi
+
 
     ___X_CMD_PKG_ACTIVATE___LIST="$___X_CMD_PKG_ACTIVATE___LIST
 $name=$version
 "
 }
 
-#NOTE:
-# 1. nickname name is a many-to-one relationship, there is only one name
-# 2. name must have a nickname with the same name
-___x_cmd_pkg_activate___min_default(){
+___x_cmd_pkg_pathenv___min_default(){
     local name="${1:?Provide pkg name}"
     local version="${2:?Provide version}"
-
+    local path_dir="${3:-"bin"}"
+    local osarch="$(___x_cmd_pkg_osarch)"
+    local tgt="$___X_CMD_PKG_POPULATE_PATH/$name/$version"
     local bin_path
-    if ! bin_path="$(___x_cmd_pkg_xbin_path "$name" "$version")" ; then
+    local mutiple_bin_path
+
+    if ! mutiple_bin_path="$(___x_cmd_pkg___link "$name" "$version" "$osarch" "path.${path_dir}" )" ; then
         pkg:error "Get bin path failed for $name $version"
         return 1
     fi
+    local file_path
+    while read -r bin_path; do
+            if [ -z "$bin_path" ];then
+                continue
+            fi
 
-    if [ -z "$bin_path" ] ; then
-        pkg:debug "have no bin path for $name $version"
-        return 0
-    fi
+        file_path="$tgt/$bin_path"
+        if ! [ -d "$file_path" ] ; then
+            pkg:error "No a bin folder($file_path) for $name $version"
+            return 1
+        fi
 
-    if ! [ -f "$bin_path" ] ; then
-        pkg:error "No bin path($bin_path) for $name $version"
-        return 1
-    fi
+        pkg:debug "path add_existed_folder $file_path"
+        ___x_cmd_path_unshift "$file_path" || {
+            pkg:error "Path unshift failed"
+            return 1
+        }
 
-    local soft_bin_path="$___X_CMD_PKG_INSTALL_PATH/$name/.${version}_bin"
-    x mkdirp "$soft_bin_path"
-    if  [ -x "$soft_bin_path/$name" ]; then
-        ___x_cmd_path_unshift "$soft_bin_path"
-    else
-        local nickname_name_list="$(command cat "$___X_CMD_PKG_RAW_PATH/binmod.txt" | command grep "$name")"
-        while read -r nickname_name; do
-            nickname="${nickname_name%:"$name"*}"
-            nickname=${nickname#*:}
-
-            chmod +x "$bin_path" || {
-                pkg:error "chmod - Operation not permitted bin_path=$bin_path"
-                return 1
-            }
-
-            ln -s "$bin_path"  "$soft_bin_path/$nickname" 2>/dev/null || {
-                pkg:error "ln - Operation failure "
-                return 1
-            }
-        done <<A
-$nickname_name_list
+    done <<A
+$mutiple_bin_path
 A
-        pkg:debug "path add_existed_folder $soft_bin_path"
-        ___x_cmd_path_unshift "$soft_bin_path"
-    fi
+
 }
diff --git a/mod/pkg/lib/mutate/deactivate b/mod/pkg/lib/mutate/deactivate
--- a/mod/pkg/lib/mutate/deactivate
+++ b/mod/pkg/lib/mutate/deactivate
@@ -1,4 +1,4 @@
-# shellcheck    shell=sh            disable=SC3043,SC1090      # xrc
+# shellcheck    shell=dash           disable=SC3043,SC1090      # xrc
 
 ___x_cmd_pkg_deactivate(){
 
@@ -33,18 +33,12 @@ A
     fi
 
     local osarch="${3:-${___X_CMD_PKG_OSARCH:-$(___x_cmd_pkg_osarch)}}"
-    local script_path
-    if script_path="$(___x_cmd_pkg___get_script_path "$name" "$version" "$osarch" deactivate)"; then
-        pkg:debug "Deactivate running $script_path for $name $version"
-        . "${script_path}" || {
-             pkg:error "Source $script_path failed" ; return 1
-        }
-    else
-        ___x_cmd_pkg_deactivate___min_default "$name" "$version" || {
+
+    ___x_cmd_pkg_deactivate___min_default "$name" "$version" || {
         pkg:error "Deactivate $name $version failed"
         return 1
     }
-    fi
+
 
     local tmp="${___X_CMD_PKG_ACTIVATE___LIST#*
 "${name}"=*
@@ -58,10 +52,28 @@ A
 }
 
 ___x_cmd_pkg_deactivate___min_default(){
-    local pkg="${1:?Provide pkg name}"
-    local version="${2:?Provide version}"
-    if ! x path rm "$___X_CMD_PKG_INSTALL_PATH/$name/${version}_binary/bin" ; then
-        pkg:error "Remove bin path failed for $pkg $version"
+    local name="${1:?Provide pkg name}"
+    local version="${2:-$(___x_cmd_pkg_default_version "$name")}"
+    local path_dir="${3:-"bin"}"
+    local tgt="$___X_CMD_PKG_POPULATE_PATH/$name/$version"
+    local mutiple_bin_path
+
+    if ! mutiple_bin_path="$(___x_cmd_pkg___link "$name" "$version" "x" "path.${path_dir}" )" ; then
+        pkg:error "Get bin path failed for $name $version"
         return 1
     fi
+
+    local file_path
+    while read -r bin_path; do
+            if [ -z "$bin_path" ];then
+                continue
+            fi
+        file_path="$tgt/$bin_path"
+        if ! x path rm "$file_path" ; then
+            pkg:error "Remove bin path failed for $pkg $version"
+            return 1
+        fi
+    done <<A
+$mutiple_bin_path
+A
 }
diff --git a/mod/pkg/lib/mutate/download b/mod/pkg/lib/mutate/download
--- a/mod/pkg/lib/mutate/download
+++ b/mod/pkg/lib/mutate/download
@@ -16,7 +16,7 @@ ___x_cmd_pkg_download(){
 
     local name="${1:?Provide pkg name}"
     local version="${2:-$(___x_cmd_pkg_default_version "$name")}"
-    local osarch="${3:-${___X_CMD_PKG_OSARCH:-$(___x_cmd_pkg_osarch)}}"
+    local osarch="${3:-$(___x_cmd_pkg_osarch)}"
     [ -n "$version" ] || return
 
     local url_list
@@ -27,17 +27,17 @@ ___x_cmd_pkg_download(){
         return 1
     fi
 
-    local file_suffix md5 sha1 sha256 sha512
-    ___x_cmd_pkg___attr "$name" "$version" "$osarch" "md5,sha1,sha256,sha512,file_suffix"
+    local download_file_ext md5 sha1 sha256 sha512
+    ___x_cmd_pkg___attr "$name" "$version" "$osarch" "md5,sha1,sha256,sha512,download_file_ext"
     local url
     local head
 
-    ___x_cmd_pkg___attr "$name" "$version" "$osarch" "unpack_way"
-    if [ "$unpack_way" = "non_unpack" ]; then
+    ___x_cmd_pkg___attr "$name" "$version" "$osarch" "unpack"
+    if [ "$unpack" = "none" ] && ! [ -n "$download_file_ext" ]; then
         local os="${osarch%/*}";  local arch="${osarch#*/}"
         local ball="$___X_CMD_PKG_DOWNLOAD_PATH/$name/$name.$os.$arch"
     else
-        local ball="$___X_CMD_PKG_DOWNLOAD_PATH/$name/$version.$file_suffix"
+        local ball="$___X_CMD_PKG_DOWNLOAD_PATH/$name/$version.$download_file_ext"
     fi
 
     mkdir -p "$___X_CMD_PKG_DOWNLOAD_PATH/$name" || {
@@ -58,7 +58,7 @@ ___x_cmd_pkg_download(){
         # ___x_cmd_httpget "$url" "$ball" || {
         pkg:info "Download $name $version from $url to $ball"
         # TODO: x curl
-        trap 'x pkg uninstall $name $version 2>/dev/null; printf "\r\n";  pkg:error "Download interrupted"; return 1;' INT
+        trap 'x pkg remove $name $version 2>/dev/null; printf "\r\n";  pkg:error "Download interrupted"; return 1;' INT
         head=$(curl -I "$url" | awk 'NR==1{ print $2}' )
         if [ "$head" -eq "200" ] || [ "$head" -eq "304" ] || [ "$head" -eq "302" ] || [ "$head" -eq "301" ]; then
             curl --progress-bar --location --retry-max-time 10 --retry 0 "$url" --output "$ball"
diff --git a/mod/pkg/lib/mutate/link b/mod/pkg/lib/mutate/link
--- a/mod/pkg/lib/mutate/link
+++ b/mod/pkg/lib/mutate/link
@@ -1,3 +1,131 @@
+# shellcheck    shell=sh    disable=SC3043,SC2154 # xrc
 ___x_cmd_pkg_link(){
-    :
+    local name="${1:?Provide pkg name}"
+    local version="${2:-$(___x_cmd_pkg_default_version "$name")}"
+    local osarch="${___X_CMD_PKG_OSARCH:-$(___x_cmd_pkg_osarch)}"
+    local dir_path="${3:-$___X_CMD_PKG_BASE_PATH/bin}"
+    local link_dir="${4:-bin}"
+    local tgt="$___X_CMD_PKG_POPULATE_PATH/$name/$version"
+
+    local binlink_list
+    x mkdirp "$___X_CMD_PKG_BIN_PATH"
+    if binlink_list="$(___x_cmd_pkg___link "$name" "$version" "$osarch" "link.${link_dir}")"; then
+        if [ -z "$binlink_list" ]; then
+            pkg:error "link bin is not exist"
+            return 1
+        fi
+
+        local abs_bin_path
+        local binlink_name
+        local binary_name
+        while read -r binlink; do
+            if [ -z "$binlink" ];then
+                continue
+            fi
+            abs_bin_path="${tgt}/${binlink}"
+            binlink_name=${binlink##*/}
+            if ! [ -d "$abs_bin_path" ] ; then
+                pkg:error "No bin link($abs_bin_path) for $name $version"
+                return 1
+            fi
+
+            chmod +x "$abs_bin_path" || {
+                pkg:error "chmod - Operation not permitted binlink address=$abs_bin_path"
+                return 1
+            }
+            binary_name=$(ls "$abs_bin_path")
+            if ! [ -x "$dir_path/${binlink_name}" ]; then
+                ln -s -f "$abs_bin_path/$binary_name"  "$dir_path/$binary_name" 2>/dev/null || {
+                    pkg:error "ln - Operation failure source=$abs_bin_path target=$dir_path/${binlink_name}"
+                    return 1
+                }
+            else
+                pkg:info "${binlink_name} has existed in $dir_path"
+                return 0
+            fi
+
+        done <<A
+$binlink_list
+A
+        ___x_cmd_pkg_linkenv "$name" "$version" "$dir_path"
+        pkg:debug "Set link from link bin. binlink_list=$binlink_list"
+        pkg:info  "Successfully set link from link bin "
+
+    else
+
+        local abs_bin_path; local binary_name
+        binlink_list="$(___x_cmd_pkg___link "$name" "$version" "$osarch" "path.bin")"
+        if [ -z "$binlink_list" ]; then
+            pkg:error "link bin is not exist"
+            return 1
+        fi
+        while read -r binlink_dir; do
+            if [ -z "$binlink_dir" ];then
+                continue
+            fi
+            abs_bin_path="$tgt/$binlink_dir"
+            if ! [ -d "$abs_bin_path" ] ; then
+                pkg:error "No bin link($abs_bin_path) for $name $version"
+                return 1
+            fi
+            binary_name=$(ls "$abs_bin_path")
+            while read -r binlink; do
+                ! [ -f "$dir_path/$binlink"  ] || continue
+                if [ -x "$abs_bin_path/$binlink" ]; then
+                    chmod +x "$abs_bin_path/$binlink"
+                    ln -s "$abs_bin_path/$binlink"  "$dir_path/$binlink" 2>/dev/null || {
+                        pkg:error "ln - Operation failure "
+                        return 1
+                    }
+                fi
+            done <<A
+            $binary_name
+A
+        done <<A
+    $binlink_list
+A
+        ___x_cmd_pkg_linkenv "$name" "$version" "$dir_path"
+        pkg:debug "Set link from path. binary_name=$binary_name"
+        pkg:info "Successfully set link from path "
+    fi
+}
+
+___x_cmd_pkg_linkenv(){
+    xrc path
+    local name="${1:?Provide pkg name}"
+    local version="${2:-$(___x_cmd_pkg_default_version "$name")}"
+    local dir_path="${3}"
+    local osarch="${___X_CMD_PKG_OSARCH:-$(___x_cmd_pkg_osarch)}"
+    local abs_bin_path
+    ___x_cmd_path_unshift "$dir_path"
+    ! [ "$dir_path" = "$___X_CMD_PKG_BASE_PATH/bin" ] || return
+
+    local link_dir; local abs_bin_path; local link_path
+    link_dir="$(___x_cmd_pkg___link_content "$name" "$version" "$osarch" "path")"
+
+    while read -r dir; do
+        case "$dir" in
+            bin|"") continue ;;
+        esac
+        ! [ -d "$dir_path" ] || return
+        if [ "$dir" = "man" ]; then
+            link_path="$(___x_cmd_pkg___link "$name" "$version" "$osarch" "path.$dir" )"
+            abs_bin_path="$___X_CMD_PKG_POPULATE_PATH/$name/$version/$link_path"
+            ln -s "$abs_bin_path" "$dir_path" || return 1
+        fi
+
+        if [ "$dir" = "lib" ]; then
+            link_path="$(___x_cmd_pkg___link "$name" "$version" "$osarch" "path.$dir" )"
+            abs_bin_path="$___X_CMD_PKG_POPULATE_PATH/$name/$version/$link_path"
+            ln -s "$abs_bin_path" "$dir_path" || return 1
+        fi
+
+        if [ "$dir" = "include" ]; then
+            link_path="$(___x_cmd_pkg___link "$name" "$version" "$osarch" "path.$dir" )"
+            abs_bin_path="$___X_CMD_PKG_POPULATE_PATH/$name/$version/$link_path"
+            ln -s "$abs_bin_path" "$dir_path" || return 1
+        fi
+    done <<A
+$link_dir
+A
 }
diff --git a/mod/pkg/lib/xbin b/mod/pkg/lib/xbin
--- a/mod/pkg/lib/xbin
+++ b/mod/pkg/lib/xbin
@@ -18,7 +18,7 @@ ___x_cmd_pkg_xbin_path(){
 
     local version="${2:-$(___x_cmd_pkg_default_version "${pkg_name}")}"
     local osarch="${3:-$(___x_cmd_pkg_osarch)}"
-    local tgt="${4:-"$___X_CMD_PKG_INSTALL_PATH/$pkg_name/$version"}"
+    local tgt="${4:-"$___X_CMD_PKG_POPULATE_PATH/$pkg_name/$version"}"
     [ -n "$version" ] || return
 
     pkg:debug "{ INSTALL_PATH: $tgt }"
@@ -43,13 +43,20 @@ ___x_cmd_pkg_xbin_init(){
     local version="${2:-$(___x_cmd_pkg_default_version "${pkg_name}")}"
     [ -n "$version" ] || return
     local bin_path
-    local install_path="$___X_CMD_PKG_INSTALL_PATH/$pkg_name/$version"
+    local install_path="$___X_CMD_PKG_POPULATE_PATH/$pkg_name/$version"
     bin_path="$(___x_cmd_pkg_xbin_path "$pkg_name" "$version")"
     pkg:debug --bin_mod_name "$bin_mod_name" --package "$pkg_name" --version "$version" --binpath "$bin_path" xbin_init
 
     [ -f "$bin_path" ] || {
         [ ! -d "$install_path" ] || x rmrf "$install_path"
-        ___x_cmd_pkg_install "$pkg_name" "$version"
+        x pkg download "$pkg_name" "$version" || {
+            pkg:error Download "$pkg_name" "$version" failure
+            return 1
+        }
+        x pkg populate "$pkg_name" "$version" || {
+            pkg:error populate "$pkg_name" "$version" failure
+            return 1
+        }
     }
     if [ ! -x "$bin_path" ]; then
         if ! chmod +x "$bin_path"; then
