...

diff --git a/mod/hn/lib/app b/mod/hn/lib/app
--- a/mod/hn/lib/app
+++ b/mod/hn/lib/app
@@ -58,7 +58,10 @@ ___x_cmd_hn___app_datarequest(){
     page=$(( (signal-1)/per_page  + 1 ))
     start=$(( (page-1)*per_page  + 1 ))
     end=$((start + per_page - 1))
-    local data=; data="$(___x_cmd_hn___live_data "$type" "${start},${end}")" || return
+    local data=; data="$(___x_cmd_hn___live_data "$type" "${start},${end}")" || {
+        printf "%s\n" "errexit:Error exit"
+        return 1
+    }
     if [ -n "$data" ]; then
         printf "%s\n%s\n" "data:start:${start}" "$data"
     else
