...

diff --git a/mod/gd/lib/choose b/mod/gd/lib/choose
--- a/mod/gd/lib/choose
+++ b/mod/gd/lib/choose
@@ -1,38 +1,37 @@
-# shellcheck shell=dash
+# shellcheck shell=dash disable=SC2034
 
-# Section: choose
-
-# TODO: better ui
-___x_cmd_gd_choose_data(){
-    printf "%s\n" "Select an option to change directory:"
-    printf "%s\n" "$*"
-    printf "%s\n" "---
----"
+# ___X_CMD_GD_INTERACTIVE_TOOL
+___x_cmd_gd_interactive(){
+    local X_help_cmd="x help -m gd -i"
+    case "$1" in
+        pick)       ___X_CMD_GD_INTERACTIVE_TOOL=pick ;;
+        fzf)        ___X_CMD_GD_INTERACTIVE_TOOL=fzf  ;;
+        --help|-h)  help:show:ret:0  ;;
+        *)          help:show:ret:64 ;;
+    esac
 }
-
-xrc ui/lib/gridselect
 
 ___x_cmd_gd_choose(){
+    local ___X_CMD_PICK_DATA=; ___X_CMD_PICK_DATA="$( "$@" 2>/dev/null )"
+    [ -n "$___X_CMD_PICK_DATA" ] || M="Not found directory path" N=gd log:ret:1
 
-    # If no interactive, return false
-    if [ "$1" = "" ] || [ "${-#*i}${___X_CMD_FS_DEBUG}" = "$-" ]; then
-        printf "%s\n" "gd: no such directory: $p " >&2
-        return 1
+    local dir=;
+    if ___x_cmd_is_interactive; then
+        dir="$(
+            case "$___X_CMD_GD_INTERACTIVE_TOOL" in
+                fzf)    printf "%s\n" "$___X_CMD_PICK_DATA" | x fzf --layout=reverse --height=30% ;;
+                *)      x tty update
+                        x pick --width "$COLUMNS" ;;
+            esac
+        )" || return 1
+    else
+        dir="$( printf "%s\n" "$___X_CMD_PICK_DATA" | ___x_cmd_gd___util_head 1 )" || return
     fi
-    local ___X_CMD_UI_GRIDSELECT_CURRENT_ITEM
-    local ___X_CMD_UI_GRIDSELECT_FINAL_COMMAND
-    ___x_cmd_ui_gridselect num ___x_cmd_gd_choose_data "$@"
-    [ "$___X_CMD_UI_GRIDSELECT_FINAL_COMMAND" = "q" ] && return 0
-    ___x_cmd_gd_origin "$___X_CMD_UI_GRIDSELECT_CURRENT_ITEM"
-}
 
-___x_cmd_gd_choose2(){
-    local dir; dir=$("$@" | x fzf) || return 1
     [ -d "$dir" ] || {
-        x:error "Invalide directory path ==> $dir"
+        gd:error "Invalide directory path ==> $dir"
         return 1
     }
-    x cd "$dir"
+    ___x_cmd_gd_origin "$dir"
 }
 
-## EndSection
diff --git a/mod/hub/lib/util/userdir b/mod/hub/lib/util/userdir
--- a/mod/hub/lib/util/userdir
+++ b/mod/hub/lib/util/userdir
@@ -1,58 +1,38 @@
 # shellcheck shell=dash
 
 ___x_cmd_hub___util_user_id(){
-    local res;    res="$(NO_AUTH=1 x ccmd -- ___x_cmd_hub___util_curl get "/api/v0/account/id" "username=$1")"
-    local userId; userId="$(printf "%s" "$res" | { x jo env . id=.id ; printf "%s\n" "$id";})"
-    if [ -z "${userId}" ] ; then
-        ___x_cmd_hub___util_handle_resp false "$res" "Failed to get user id for $1"
-        x ccmd invalidate ___x_cmd_hub___util_curl get "/api/v0/account/id" "username=$1"
+    local res; local user_id;
+
+    res="$(NO_AUTH=1 x ccmd -- \
+        ___x_cmd_hub___util_curl get "/api/v0/account/id" "username=$1" \
+        PROFILE="$___X_CMD_HUB_LOCAL_PROFILE" \
+        CONFIG="$___X_CMD_HUB_LOCAL_CONFIG"
+    )" || {
+        hub:error "Response => $res"
         return 1
-    fi
-    printf "%s" "$userId"
+    }
+
+    user_id="$(printf "%s" "$res" | { x jo env . id=.id ; printf "%s\n" "$id";})"
+    [ -n "${user_id}" ] || {
+        hub:error "Failed to get user_id from response => $res"
+        return 1
+    }
+    printf "%s" "$user_id"
 }
 
-___x_cmd_hub___util_user_name(){
-    local token;  token="$(___x_cmd_hub_cur get token)" # 50ms
-    local res;    res="$(NO_AUTH=1 x ccmd -- ___x_cmd_hub___util_curl get "/api/v0/account" "token=$token")" # 20ms
-    local username; username="$(printf "%s" "$res" | { x jo env . username=.name ; printf "%s\n" "$username" ;})" # 20ms
-    if [ -z "${name}" ] ; then
-        ___x_cmd_hub___util_handle_resp false "$res" "Failed to get user id"
-        x ccmd invalidate ___x_cmd_hub___util_curl get "/api/v0/account" "token=$token"
-        return 1
-    fi
-    x_="$name"
-}
-
-___x_cmd_hub___util_userid(){
-    local x_; ___x_cmd_hub___util_ensure_userid_; printf "%s" "$x_"
-}
-
-___x_cmd_hub___util_ensure_userid_(){
-    local token;  token="$(___x_cmd_hub_cur get token)"
-    local res;    res="$(NO_AUTH=1 x ccmd -- ___x_cmd_hub___util_curl get "/api/v0/account" "token=$token")"
-    local userId; userId="$(printf "%s" "$res" | { x jo env . id=.id ; printf "%s\n" "$id";})"
-    if [ -z "${userId}" ] ; then
-        ___x_cmd_hub___util_handle_resp false "$res" "Failed to get user id"
-        x ccmd invalidate ___x_cmd_hub___util_curl get "/api/v0/account" "token=$token"
-        return 1
-    fi
-    x_="$userId"
+___x_cmd_hub___util_cache_invalidate(){
+    x ccmd invalidate ___x_cmd_hub___util_curl get "/api/v0/account/id" "username=me" \
+        PROFILE="$___X_CMD_HUB_LOCAL_PROFILE" \
+        CONFIG="$___X_CMD_HUB_LOCAL_CONFIG"
 }
 
 ___x_cmd_hub___util_user_dir(){
     local username="${1:?username required}"
     local p="${2}"
-
-    case "$username" in
-        -|me)
-            local x_
-            ___x_cmd_hub___util_ensure_userid_ || return
-            res="$___X_CMD_HUB_DATA/$x_/$p" ;;
-        *)  res="$___X_CMD_HUB_DATA/$(___x_cmd_hub___util_user_id "$username")/$p" || return ;;
-    esac
-
-    x mkdirp "$res"
-    printf "%s" "$res"
+    local dir; dir="$___X_CMD_HUB_DATA/$(___x_cmd_hub___util_user_id "$username")/$p" || return
+    hub:debug "user_dir => $* dir=$dir"
+    x mkdirp "$dir"
+    printf "%s" "$dir"
 }
 
 # <username>:<respath> data        => <user_id>/data/<respath>
