...

diff --git a/mod/gd/lib/relm b/mod/gd/lib/relm
--- a/mod/gd/lib/relm
+++ b/mod/gd/lib/relm
@@ -38,9 +38,41 @@ ___x_cmd_gd_relm___magic(){
         :git|:git/) ___x_cmd_gd_relm___goto_git                             ;;
         :git/*)     ___x_cmd_gd_relm___goto_git "${p#*":git/"}"             ;;
 
-        :*/*)       ___x_cmd_gd_relm___goto_inner "${p#:}"                  ;;
-        :*)         shift; ___x_cmd_gd_relm___goto_or_set "${p#:}" "$@"     ;;
+        # :*/*)       ___x_cmd_gd_relm___goto_inner "${p#:}"                  ;;
+        # :*)         shift; ___x_cmd_gd_relm___goto_or_set "${p#:}" "$@"     ;;
+
+        :*)         ___x_cmd_gd_relm___magic0 "$@" ;;
+
     esac
+}
+
+___x_cmd_gd_relm___magic0(){
+    local count="$((count + 1))"
+    [ "$count" -lt 3 ] || N=gd M="recursive more than 3" log:ret:1
+
+    case "$1" in
+        :*/*)
+            local p0="${1%%/*}"
+            local p1="${1#*/}"
+            local x=; ___x_cmd_gd_util___dict_get_ relm "${p0#:}" || {
+                gd:error "RELM NOT found ==> $p0"
+                return 1
+            }
+            ___x_cmd_gd_relm___magic0 "$x_/$p1"
+            ;;
+        :*)
+            local x=; ___x_cmd_gd_util___dict_get_ relm "${1#:}" || {
+                gd:error "RELM NOT found ==> $1"
+                return 1
+            }
+            ___x_cmd_gd_relm___magic0 "$x_"
+            ;;
+        *)
+            ___x_cmd_gd_origin "$1"
+            ;;
+    esac
+
+
 }
 
 ___x_cmd_gd_relm___ls(){
@@ -75,7 +107,7 @@ ___x_cmd_gd_relm___goto_inner(){
 
 ___x_cmd_gd_relm___goto(){
     local x=; ___x_cmd_gd_util___dict_get_ relm "$1"
-    [ -d "$x_" ] || return
+    # [ -d "$x_" ] || return
     ___x_cmd_gd_origin "$x_"
 }
 
@@ -104,8 +136,15 @@ ___x_cmd_gd_relm___abs_dir_path(){
 }
 
 ___x_cmd_gd_relm___init_put(){
-    local x_=; ___x_cmd_gd_relm___abs_dir_path "$2" || return
-    ___x_cmd_gd_util___dict_inner put relm "${1#:}" "$x_"
+    case "$2" in
+        *://*)
+            ___x_cmd_gd_util___dict_inner put relm "${1#:}" "$2"
+            ;;
+        *)
+            local x_=; ___x_cmd_gd_relm___abs_dir_path "$2" || return
+            ___x_cmd_gd_util___dict_inner put relm "${1#:}" "$x_"
+            ;;
+    esac
 }
 
 ___x_cmd_gd_relm___init(){
@@ -116,16 +155,28 @@ ___x_cmd_gd_relm___init(){
         return
     fi
 
-    ___x_cmd_gd_relm___init_put x                "$___X_CMD_ROOT_V_VERSION"
-    ___x_cmd_gd_relm___init_put xr               "$HOME/.x-cmd.root"
-    ___x_cmd_gd_relm___init_put xrg              "$HOME/.x-cmd.root/global"
-    ___x_cmd_gd_relm___init_put xrl              "$HOME/.x-cmd.root/local"
+    ___x_cmd_gd_relm___init_put x               "$___X_CMD_ROOT_V_VERSION"
+    ___x_cmd_gd_relm___init_put xr              "$HOME/.x-cmd.root"
+    ___x_cmd_gd_relm___init_put xrg             "$HOME/.x-cmd.root/global"
+    ___x_cmd_gd_relm___init_put xrl             "$HOME/.x-cmd.root/local"
+
+    ___x_cmd_gd_relm___init_put gh              "gh://"
+    ___x_cmd_gd_relm___init_put gt              "gt://"
+    ___x_cmd_gd_relm___init_put gl              "gl://"
+    ___x_cmd_gd_relm___init_put gcode           "gcode://"
+
+
+    ___x_cmd_gd_relm___init_put xbash           "gh://x-bash"
+    ___x_cmd_gd_relm___init_put xcmd            "gh://x-cmd"
+    ___x_cmd_gd_relm___init_put xpkg            "gh://x-cmd-pkg"
+    ___x_cmd_gd_relm___init_put xtheme          "gh://x-cmd-theme"
+
     # gd :xrl/cfg
 
     # module
-    ___x_cmd_gd_relm___init_put gita             "${___X_CMD_GITA_CACHE:-"$___X_CMD_ROOT_SHARED/gita/DEFAULT/cache"}"
-    ___x_cmd_gd_relm___init_put gitb             "${___X_CMD_GITB_CACHE:-"$___X_CMD_ROOT_SHARED/gitb/DEFAULT/cache"}"
-    ___x_cmd_gd_relm___init_put gitc             "${___X_CMD_GITA_CACHE:-"$___X_CMD_ROOT_SHARED/gitc/DEFAULT/cache"}"
+    ___x_cmd_gd_relm___init_put gita            "${___X_CMD_GITA_CACHE:-"$___X_CMD_ROOT_SHARED/gita/DEFAULT/cache"}"
+    ___x_cmd_gd_relm___init_put gitb            "${___X_CMD_GITB_CACHE:-"$___X_CMD_ROOT_SHARED/gitb/DEFAULT/cache"}"
+    ___x_cmd_gd_relm___init_put gitc            "${___X_CMD_GITA_CACHE:-"$___X_CMD_ROOT_SHARED/gitc/DEFAULT/cache"}"
 
     [ -z "$TMPDIR" ] || ___x_cmd_gd_relm___init_put "tmp" "$TMPDIR"
 
