...

diff --git a/mod/install/lib/mutate/run b/mod/install/lib/mutate/run
--- a/mod/install/lib/mutate/run
+++ b/mod/install/lib/mutate/run
@@ -1,4 +1,4 @@
-# shellcheck shell=dash disable=2154
+# shellcheck shell=dash disable=2034
 xrc ui
 ___x_cmd_install_run(){
     local X_help_cmd='x help -m install run';   help:arg-null:parse
@@ -6,6 +6,65 @@ ___x_cmd_install_run(){
     local i; for i in "$@"; do
         ___x_cmd_install_run___inner "$i" || return
     done
+}
+
+___x_cmd_install_run___app_(){
+    [ "$#" -gt 0 ]  ||      N=install M="Please provide sofotware" log:ret:64
+
+    local software="$1";    shift "$#"
+    local data; data="$(___x_cmd_install___showcandidate "$software")"
+
+    ! x env --xinstall has "$software" || data=" \"x env use ${software}\" ${data}"
+
+    [ -n "$data" ] || return
+    local cmd="";
+    eval x ui select id,cmd "\"Choose the code you want to execute:\"" "$data" || return
+
+    [ -n "$cmd" ] || return
+    x_="$cmd"
+}
+
+___x_cmd_install___showcandidate(){
+    ___X_CMD_INSTALL_IS_RUN=1 ___x_cmd_install_cat "$1"
+}
+
+___x_cmd_install_run___inner(){
+    local software="$1"
+    local x_=; ___x_cmd_install_run___app_ "$software" || return
+    x ui yesno "Whether to execute the following code: ${___X_CMD_UNSEENCHAR_NEWLINE}$(___x_cmd_ui bold cyan "$x_")" || return
+    install:info --code "$x_" "Running the code"
+    eval "$x_" || {
+        install:error "Execute failed"
+        # x_=; ___x_cmd_install___update_installer_
+        # install:warn "Perhaps you need to use \`$(___x_cmd_ui bold cyan "$x_")\` firstly"
+        return 1
+    }
+    # install:info "Download software[$software] successfully"
+}
+
+___x_cmd_install_run___update_installer_(){
+    local cmd="$1"
+    x_=""
+    case "$cmd" in
+        apt)    if x hascmd apt; then
+                    x_="x install run apt"
+                else
+                    x_="sudo apt update"
+                fi
+                ;;
+        pacman) if x hascmd pacman; then
+                    x_="x install run pacman"
+                else
+                    x_="sudo pacman -Sy"
+                fi
+                ;;
+        brew)   if x hascmd brew; then
+                    x_="x install run brew"
+                fi
+                ;;
+        dnf)    x_="sudo dnf check-update" ;;
+        yum)    x_="sudo yum check-update" ;;
+    esac
 }
 
 ___x_cmd_install___update_installer_(){
@@ -25,47 +84,4 @@ ___x_cmd_install___update_installer_(){
     else
         x_="Update your installer"
     fi
-
 }
-
-___x_cmd_install_run___inner(){
-    local software="$1"
-    local cmd=; local num=0
-    local l; while read -r l; do
-        [ "$l" != "$___X_CMD_UNSEENCHAR_003" ] || {
-            [ -z "$cmd" ] || {
-                eval "local cmd_$num=\$cmd"
-                printf "%s\n" "$cmd"
-            }
-            num=$(( num + 1 ))
-            cmd=
-            printf "\033[33m%s\033[0m:" "$num"
-            continue
-        }
-        cmd="${cmd}${___X_CMD_UNSEENCHAR_NEWLINE}  ${l}"
-    done << A
-$(___X_CMD_INSTALL_IS_RUN=1 ___x_cmd_install_cat "$software")
-A
-    [ "$num" -gt 0 ] || N=install M="Not found software[$software]" log:ret:1
-    eval "local cmd_$num=\$cmd"
-    printf "%s\n" "$cmd"
-
-    local item_num=1
-    if [ "$num" -gt 1 ]; then
-        printf "\033[33m%s\033[0m" "Input item num: " >&2
-        < /dev/tty read -r item_num || return
-    fi
-
-    eval "local item_cmd=\"\$cmd_$item_num\""
-    install:debug --item_num "$item_num" -c "$item_cmd"
-    [ -n "$item_cmd" ] || N=install M="Please provide a correct number" log:ret:1
-    x ui yesno "Whether to execute the following code: $(___x_cmd_ui bold cyan "$item_cmd" )" || return
-    eval "$item_cmd" || {
-        install:error "Execute failed"
-        local x_=; ___x_cmd_install___update_installer_
-        install:warn "Perhaps you need to use \`$(___x_cmd_ui bold cyan "$x_")\` firstly"
-        return 1
-    }
-    # install:info "Download software[$software] successfully"
-}
-
