...

diff --git a/mod/theme/latest b/mod/theme/latest
--- a/mod/theme/latest
+++ b/mod/theme/latest
@@ -80,7 +80,7 @@ ___x_cmd_theme_control_use(){
 
     x ensurefp "${___X_CMD_ROOT_CFG}/theme/default"
     ___x_cmd_theme_control_try_inner "$name" "$*" && \
-        printf "%s\n" "___x_cmd_theme_control_try_inner $name $*" >"${___X_CMD_ROOT_CFG}/theme/default" && \
+        printf "%s\n" "___x_cmd_theme_control_try_inner $___X_CMD_THEME_NAME $*" >"${___X_CMD_ROOT_CFG}/theme/default" && \
         x boot rc add "x-theme" "xrc theme && ___x_cmd_theme_control_use_default"
 }
 # EndSection
@@ -99,11 +99,22 @@ ___x_cmd_theme_control_try_inner(){
     local name="${1}"
     [ "$name" != "random" ] || local _XCMD_THEME_RANDOM="$2"
     case "$name" in
-        ys|"")          ___x_cmd_theme_load_format "$___X_CMD_ROOT_MOD/theme/lib/ys" ;;
-        */*)            ___x_cmd_theme_load_format "$(xrc which "$name")" ;;
-        *)              local filepath; ___x_cmd_theme___which___filepath "style/$name" && \
-                            ___x_cmd_theme_load_format "$filepath" || return 1
-                        ;;
+        ys|"")  ___x_cmd_theme_load_format "$___X_CMD_ROOT_MOD/theme/lib/ys"  ;;
+        */*)
+                local ___X_CMD_WHICH_ONE_RESULT=""
+                if ___x_cmd_which_one "$name"; then
+                    name="$___X_CMD_WHICH_ONE_RESULT"
+                    ___x_cmd_theme_load_format "$name"
+                else
+                    x log :theme error "Not found theme file ==> $name"
+                    return 1
+                fi
+                ;;
+        *)
+                local filepath=""
+                ___x_cmd_theme___which___filepath "style/$name"
+                ___x_cmd_theme_load_format "$filepath" || return 1
+                ;;
     esac
     ___X_CMD_THEME_NAME="$name"
     ! command -v _____x_cmd_theme_register_hook >/dev/null || _____x_cmd_theme_register_hook
