...

diff --git a/mod/cd/lib/relm/getset b/mod/cd/lib/relm/getset
--- a/mod/cd/lib/relm/getset
+++ b/mod/cd/lib/relm/getset
@@ -2,30 +2,49 @@
 
 ___x_cmd_cd_relm___get_(){
     x_=""
-    local ___X_CMD_LDICT_GET_=
-    ___x_cmd_cd_util___dict_inner get_ relm_init "$1" || {
-        ___x_cmd_cd_util___dict_get_ relm_custom "$1"
-        return
-    }
-    x_="$___X_CMD_LDICT_GET_"
+    local name="${1#:}"
+    case "$name" in
+        ws)     ___x_cmd wsroot_ ;;
+        git)    ___x_cmd_locatefolder_ "$PWD" ".git"            || return
+                x_="$x_/.git"
+                ;;
+        nm)     ___x_cmd_locatefolder_ "$PWD" ".node_modules"   || return
+                x_="$x_/.node_modules"
+                ;;
+        lm)     ___x_cmd_locatefolder_ "$PWD" ".lua_modules"    || return
+                x_="$x_/.lua_modules"
+                ;;
+        *)
+                ___x_cmd_cd_util___dict_get_ relm_custom "$name" || \
+                    ___x_cmd_cd_util___dict_get_inner_ relm_init "$name"
+                ;;
+    esac
 }
 
 ___x_cmd_cd_relm___get(){
-    local x_=; ___x_cmd_cd_relm___get_ "$@" || return
+    local name="${1#:}"
+    [ -n "$name" ] || N=cd M="Please provide relm name" log:ret:64
+    local x_=; ___x_cmd_cd_relm___get_ "$name" || {
+        cd:warn "RELM NOT found ==> $name"
+        return 1
+    }
     printf "%s\n" "$x_"
 }
 
 ___x_cmd_cd_relm___set(){
     local name="${1#:}"
     case "$name" in
-        ws|git) cd:warn "The [relm=$name] is already occupied"; return 1 ;;
+        "")     N=cd M="Please provide relm name" log:ret:64 ;;
+        ws|git|nm|lm)
+                cd:warn "The relm [name=$name] is predefined and already occupied"; return 1 ;;
         *)
                 if ___x_cmd_cd_util___dict_inner has relm_init "$name"; then
-                    cd:warn "The [relm=$name] is already occupied"
+                    cd:warn "The relm [name=$name] is predefined and already occupied"
                     return 1
                 fi
                 ;;
     esac
+    [ -n "$2" ] || N=cd M="Please provide the relm [name=$name] directory path" log:ret:64
 
     local x_=; ___x_cmd_cd_relm___abs_dir_path "$2" || {
         cd:error "Failed to set relm, no such [directory=$2]"
@@ -35,11 +54,24 @@ ___x_cmd_cd_relm___set(){
     ___x_cmd_cd_util___dict_set relm_custom "$name" "$x_"
 }
 
-# ___x_cmd_cd_relm___set_or_true(){
-#     ___x_cmd_cd_relm___set "$@" || true
-# }
-
 ___x_cmd_cd_relm___rm(){
-    ___x_cmd_cd_util___dict_rm relm_custom "$1"
+    local name="${1#:}"
+    case "$name" in
+        "")     N=cd M="Please provide relm name" log:ret:64 ;;
+        ws|git|nm|lm)
+                cd:warn "The relm [name=$name] is predefined and cannot be removed"; return 1 ;;
+        *)
+                if ___x_cmd_cd_util___dict_inner has relm_init "$name"; then
+                    cd:warn "The relm [name=$name] removed only in current environment"
+                    ___x_cmd_cd_util___dict_rm relm_init "$name"
+                    return
+                fi
+                ;;
+    esac
+    ___x_cmd_cd_util___dict_rm relm_custom "$name" || {
+        cd:warn "Remove the relm [name=$name] failed"
+        return 1
+    }
+    cd:info "Removed the relm [name=$name] successfully"
 }
 
diff --git a/mod/user/lib/current b/mod/user/lib/current
--- a/mod/user/lib/current
+++ b/mod/user/lib/current
@@ -1,18 +1,58 @@
+# shellcheck shell=dash
+___X_CMD_USER_ID=
+___X_CMD_USER_NAME=
 
-___x_cmd_user_current(){
-    local x_
-    ___x_cmd_user_current_ || return
-    printf "%s" "$x_"
+___x_cmd_user_id_(){
+    x_=""
+    [ -n "$___X_CMD_USER_ID" ] || {
+        if [ -n "$UID" ]; then
+            ___X_CMD_USER_ID="$UID"
+        else
+            ___X_CMD_USER_ID="$(___x_cmd_cmds id -u)" || N=user M="Unexpected error ==> [command=id -u] fail" log:ret:1
+            [ -n "$___X_CMD_USER_ID" ] || return 1
+        fi
+    }
+    x_="${___X_CMD_USER_ID}"
 }
 
-___x_cmd_user_current_(){
-    x_="$USER"
-    [ -n "$x_" ] || return 0
+___x_cmd_user_name_(){
+    x_=""
+    [ -n "$___X_CMD_USER_NAME" ] || {
+        if [ -n "$USER" ]; then
+            ___X_CMD_USER_NAME="$USER"
+        elif x hascmd id; then
+            ___X_CMD_USER_NAME="$( ___x_cmd_cmds id -un )"  || N=user M="Unexpected error ==> [command=id -un] fail" log:ret:1
+        elif x hascmd whoami; then
+            ___X_CMD_USER_NAME="$( ___x_cmd_cmds whoami )"  || N=user M="Unexpected error ==> [command=whoami] fail" log:ret:1
+        elif x hascmd users; then
+            ___X_CMD_USER_NAME="$( ___x_cmd_cmds users )"   || N=user M="Unexpected error ==> [command=users] fail" log:ret:1
+        fi
 
-    if x runnable users; then
-        x_="$USER"
-    else
-        x:error "Variable USER and command user NOT FOUND."
-    fi
-    USER="$x_"
+        [ -n "$___X_CMD_USER_NAME" ] || return 1
+    }
+
+    x_="$___X_CMD_USER_NAME"
+
+    # if x runnable users; then
+    #     x_="$USER"
+    # else
+    #     x:error "Variable USER and command user NOT FOUND."
+    # fi
+    # USER="$x_"
+}
+
+___x_cmd_user_id(){
+    local x_=; ___x_cmd_user_id_ || return
+    printf "%s\n" "$x_"
+}
+
+ # Optimization: UID GROUPS [ -w / ]
+___x_cmd_user_isroot(){
+    local x_=; ___x_cmd_user_id_ || return
+    [ "$x_" -eq 0 ]
+}
+
+___x_cmd_user_name(){
+    local x_=; ___x_cmd_user_name_ || return
+    printf "%s\n" "$x_"
 }
diff --git a/mod/user/lib/main b/mod/user/lib/main
--- a/mod/user/lib/main
+++ b/mod/user/lib/main
@@ -1,55 +1,27 @@
 # shellcheck shell=dash
 
+x log init user
 xrc:mod:lib     user        add ls current passwd
 
 ___x_cmd_user___main(){
     [ "$#" -gt 0 ] || {
-        ___x_cmd_user_current
+        ___x_cmd_user_name
         return
     }
 
     local op="$1"; shift
     case "$op" in
-        add|ls|rm|current|passwd|isroot|id|in)
+        add|ls|rm|name|passwd|isroot|id|in)
             ___x_cmd_user_"$op" "$@" ;;
         -h|--help)
             x help -m user ;;
     esac
 }
 
-
-___X_CMD_USER_ID=
-
-___x_cmd_user_id_(){
-    x_=
-    [ -n "$___X_CMD_USER_ID" ] || {
-        if [ -n "$UID" ]; then
-            ___X_CMD_USER_ID="$UID"
-        else
-            ___X_CMD_USER_ID="$(___x_cmd_cmds id -u)" || N=user M="Unexpected error ==> [command=id -u] fail" log:ret:1
-            [ -n "$___X_CMD_USER_ID" ] || return 1
-        fi
-    }
-    x_="${___X_CMD_USER_ID}"
-}
-
-___x_cmd_user_id(){
-    local x_
-    ___x_cmd_user_id_ || return
-    printf "%s\n" "$x_"
-}
-
- # Optimization: UID GROUPS [ -w / ]
-___x_cmd_user_isroot(){
-    local x_
-    ___x_cmd_user_id_ || return
-    [ "$x_" -eq 0 ]
-}
-
 # TODO: in --one-of
 ___x_cmd_user_in(){
-    local a; a=" $(id -Gn) " || {
-        sudo:error "fail to judge current user is sudo user" --user "$USER" --cmd "id -Gn"
+    local a; a=" $(___x_cmd_cmds id -Gn) " || {
+        user:error "fail to judge current user is sudo user" --user "$USER" --cmd "id -Gn"
         return 2
     }
 
@@ -58,7 +30,7 @@ ___x_cmd_user_in(){
     while [ $# -gt 0 ]; do
         # work only in linux. in macos, the sudo group name is admin. This can also be redefined.
         case " $a " in
-            *" $1 "*)     continue      ;;
+            *" $1 "*)     shift; continue      ;;
             *)            return 1      ;;
         esac
     done
diff --git a/mod/yum/lib/main b/mod/yum/lib/main
--- a/mod/yum/lib/main
+++ b/mod/yum/lib/main
@@ -1,69 +1,55 @@
 # shellcheck shell=dash disable=SC2034,SC2016
 x log init yum
 
+xrc:mod:lib  yum   __xmirror/_index  __repo __xproxy install nv
+
 ___x_cmd_yum___main(){
     [ "$#" -gt 0 ] ||   set -- nv
-
     local op="$1"; shift
     case "$op" in
-        install)            ___x_cmd_yum___install          "$@" ;;
+        -h|--help)
+            x help -m yum "$@"; return   ;;
+    esac
+
+    x hascmd yum || {
+        yum:warn "yum command not found."
+        return 1
+    }
+
+    case "$op" in
+        install)            ___x_cmd_yum_install            "$@" ;;
         nv)                 ___x_cmd_yum___nv               "$@" ;;
 
         proxy|--xproxy)     ___x_cmd_yum___xproxy           "$@" ;;
         mirror|--xmirror)   ___x_cmd_yum___xmirror          "$@" ;;
 
 
-        --help|-h)           x help -m yum;        return        ;;
         # proxy)            ___x_cmd_yum___proxy    "$@"         ;;
         *)                  ___x_cmd_cmds yum "$op" "$@"         ;;
     esac
 }
 
-___x_cmd_yum___nv(){
-    local X_help_cmd='x help -m yum nv'
-    help:arg:parse
-    { [ -t 1 ] && ___x_cmd_is_interactive; } \
-        || {
-            x ccmd 1d -- ___x_cmd_yum___lsraw
-            return 0
-        }
-
-    local x_=""
-    ___X_CMD_PICK_SHBIN_CODE="xrc yum" \
-    ___x_cmd_storeread_ x pick --width 40 --col 10 x ccmd 1d -- ___x_cmd_yum___lsraw
-    local software=$x_
-
-    [ -n "$software" ] ||  {
-        yum:info "Exit because no software is selected."
-        return 0
-    }
-
-    local id
-    x ui select id "What to do NEXT"                        \
-        "x yum install $software"                        \
-        "EXIT"     || return
-
-    case "$id" in
-        1)      x yum install "$software" ;;
-        2)      return 0 ;;
-
-    esac
+___x_cmd_yum___exec(){
+    yum:info "running command  →  x sudo yum $*"
+    ___x_cmd_yum___xproxy run x sudo yum "$@"
 }
 
 ___x_cmd_yum___lsraw(){
-    ___x_cmd_cmds yum list | ___x_cmd_cmds awk 'NR>2{
-        print $1
-    }'
+    local x_=; ___x_cmd_yum___lsraw_ || return 1
+    ___x_cmd_cmds_cat "$x_"
 }
 
-___x_cmd_yum___install(){
-    local X_help_cmd='x help -m yum nv'
-    help:arg:parse
-    if [ $# -eq 0 ]; then
-        ___x_cmd_yum___nv
-        return 0
-    fi
+___x_cmd_yum___lsraw_(){
+    local cachefp=; cachefp="$___X_CMD_ROOT_DATA/yum/cache/lsname"
+    x ensurefp "$cachefp"
+    local l=;
+    <"$cachefp" read -r l
 
-    # Using x sudo
-    x sudo yum install "$@"
+    [ -n "$l" ] || {
+        x rmrf "$cachefp"
+        yum:error "list software fail, please try again."
+        return 1
+    }
+    x_="$cachefp"
 }
+
