...

diff --git a/mod/cd/lib/relm/getset b/mod/cd/lib/relm/getset
--- a/mod/cd/lib/relm/getset
+++ b/mod/cd/lib/relm/getset
@@ -27,7 +27,10 @@ ___x_cmd_cd_relm___set(){
                 ;;
     esac
 
-    local x_=; ___x_cmd_cd_relm___abs_dir_path "$2" || return
+    local x_=; ___x_cmd_cd_relm___abs_dir_path "$2" || {
+        cd:error "Failed to set relm, no such [directory=$2]"
+        return 1
+    }
     cd:info "Setup relm → [$name = $x_]"
     ___x_cmd_cd_util___dict_set relm_custom "$name" "$x_"
 }
@@ -40,8 +43,3 @@ ___x_cmd_cd_relm___rm(){
     ___x_cmd_cd_util___dict_rm relm_custom "$1"
 }
 
-___x_cmd_cd_relm___abs_dir_path(){
-    [ -d "$1" ] || return
-    x_=;    x abspath_ "$1"
-    [ -d "$x_" ] || return
-}
diff --git a/mod/cd/lib/search b/mod/cd/lib/search
--- a/mod/cd/lib/search
+++ b/mod/cd/lib/search
@@ -24,8 +24,35 @@ ___x_cmd_cd_search___path(){
 }
 
 ___x_cmd_cd_goto___pickfromfind(){
-    local x_=; ___x_cmd_cd_pick_ ___x_cmd_cmds find "$1" -path "*$2*" -type d -print || return
+    local startpath="$1"
+    local pattern="$2"
     shift 2
+
+    local x_=;
+    local maxdepth=3     # default depth
+
+    ___x_cmd_cd_pick_ ___x_cmd_cmds find "$startpath" -maxdepth "$maxdepth" -path "*$pattern*" -type d -print
+    local errcode=$?
+
+    case "$errcode" in
+        130)        return 130 ;;
+        0)          ;;
+        *)
+                    cd:warn "Cannot find folder -> $pattern"
+                    maxdepth=6
+                    local id
+                    x ui select id  "Next"  \
+                        "Search deeper with maxdepth=$maxdepth"  \
+                        "Search deeper without maxdepth limit"  \
+                        "ABORRT"
+
+                    case "$id" in
+                        1)  ___x_cmd_cd_pick_ ___x_cmd_cmds find "$startpath" -maxdepth "$maxdepth" -path "*$pattern*" -type d -print || return ;;
+                        2)  ___x_cmd_cd_pick_ ___x_cmd_cmds find "$startpath" -path "*$pattern*" -type d -print || return ;;
+                        *)  return ;;
+                    esac
+    esac
+
     ___x_cmd_cd_origin "$x_" "$@"
 }
 
diff --git a/mod/pkg/lib/util b/mod/pkg/lib/util
--- a/mod/pkg/lib/util
+++ b/mod/pkg/lib/util
@@ -29,7 +29,12 @@ ___x_cmd_pkg___attr_code_inner(){
     local QUERY="$4";   local envfp="$5"
     x ensurefp "$envfp"
     {
-        ___x_cmd_pkg___all_info "$name" "$version" "$osarch" |
+        local datalist; datalist="$( ___x_cmd_pkg___all_info "$name" "$version" "$osarch" )" || {
+            printf "\n%s\n" "pkg:error \"Not found pkg [name=$name] [version=$version] information data\"; false;"
+            return 1
+        }
+
+        printf "%s\n" "$datalist" | \
         LC_ALL="$___X_CMD_AWK_LANGUAGE" ___x_cmd_cmds_awk \
             -v QUERY="$QUERY" \
             -f "$___X_CMD_ROOT_MOD/awk/lib/core.awk" \
@@ -39,7 +44,7 @@ ___x_cmd_pkg___attr_code_inner(){
             -f "$___X_CMD_ROOT_MOD/pkg/lib/awk/util.awk" \
             -f "$___X_CMD_ROOT_MOD/pkg/lib/awk/pkg._.awk" \
             -f "$___X_CMD_ROOT_MOD/pkg/lib/awk/pkg.attr.awk" \
-            || printf "\n%s\n" "pkg:error \"Not found $name package data\"; false;"
+            || printf "\n%s\n" "pkg:error \"Not found pkg [name=$name] [version=$version] information data\"; false;"
     } > "$envfp"
 }
 
@@ -50,7 +55,8 @@ ___x_cmd_pkg___attr_code_inner(){
 ___x_cmd_pkg___get_script_path(){
     local script="${4:?Provide sciprt}"
 
-    ___x_cmd_pkg___all_info --non-version "$@" | LC_ALL="$___X_CMD_AWK_LANGUAGE" ___x_cmd_awk___inner \
+    local datalist; datalist="$( ___x_cmd_pkg___all_info --non-version "$@" )" || return
+    printf "%s\n\n" "$datalist" | LC_ALL="$___X_CMD_AWK_LANGUAGE" ___x_cmd_awk___inner \
         -v SCRIPT="$script" \
         -f "$___X_CMD_ROOT_MOD/awk/lib/core.awk" \
         -f "$___X_CMD_ROOT_MOD/awk/lib/j/json.awk"   \
@@ -128,17 +134,17 @@ ___x_cmd_pkg___all_info(){
         name="$CUSTOMIZE_PKG_PATH"
     else
         name="$(___x_cmd_pkg_locate "$name")" || return
-        [ -n "$name" ] || N=pkg M="Not found pkg [$1] meta information" log:ret:1
+        [ -n "$name" ] || N=pkg M="Not found pkg [name=$1] meta information" log:ret:1
     fi
 
     # pkg:debug --name "$name"  --version "$version" --osarch "$osarch"  --___X_CMD_PKG_METADATA_PATH "$___X_CMD_PKG_METADATA_PATH" --___X_CMD_WEBSRC_REGION "$___X_CMD_WEBSRC_REGION" "all info"
     printf "%s\n%s\n%s\n%s\n%s\n" "$name" "$version" "$osarch" "$___X_CMD_PKG_METADATA_PATH" "$___X_CMD_WEBSRC_REGION"
 
-    ___x_cmd_cmds_cat "$___X_CMD_PKG_METADATA_PATH/$name/meta.tt.json" 2>/dev/null || N=pkg M="Not found pkg [$name] meta information" log:ret:1
+    ___x_cmd_cmds_cat "$___X_CMD_PKG_METADATA_PATH/$name/meta.tt.json" 2>/dev/null || N=pkg M="Not found pkg [name=$name] meta information" log:ret:1
     printf "\n"
 
     if [ -z "$version_json" ]; then
-        ___x_cmd_cmds_cat "$___X_CMD_PKG_METADATA_PATH/$name/version.tt.json" 2>/dev/null || N=pkg M="Not found pkg [$name] version information" log:ret:1
+        ___x_cmd_cmds_cat "$___X_CMD_PKG_METADATA_PATH/$name/version.tt.json" 2>/dev/null || N=pkg M="Not found pkg [name=$name] version information" log:ret:1
     else
         printf "\n"
     fi
@@ -148,7 +154,8 @@ ___x_cmd_pkg___all_info(){
 ___x_cmd_pkg___list(){
     local expr="${4:?Provide EXPR, like bin, url.cn}"
 
-    ___x_cmd_pkg___all_info "$@" | LC_ALL="$___X_CMD_AWK_LANGUAGE" ___x_cmd_awk___inner \
+    local datalist; datalist="$( ___x_cmd_pkg___all_info "$@" )" || return
+    printf "%s\n" "$datalist" | LC_ALL="$___X_CMD_AWK_LANGUAGE" ___x_cmd_awk___inner \
         -v EXPR="$expr" \
         -f "$___X_CMD_ROOT_MOD/awk/lib/core.awk" \
         -f "$___X_CMD_ROOT_MOD/awk/lib/j/json.awk"   \
@@ -184,7 +191,8 @@ ___x_cmd_pkg_default_version___inner(){
     local name="$1";    local osarch="$2";  local envfp="$3"
 
     x ensurefp "$envfp"
-    ___x_cmd_pkg___all_info --non-version "$name" "" "$osarch" | LC_ALL="$___X_CMD_AWK_LANGUAGE" ___x_cmd_awk___inner \
+    local datalist; datalist="$( ___x_cmd_pkg___all_info --non-version "$name" "" "$osarch" )" || return
+    printf "%s\n\n" "$datalist" | LC_ALL="$___X_CMD_AWK_LANGUAGE" ___x_cmd_awk___inner \
         -f "$___X_CMD_ROOT_MOD/awk/lib/core.awk" \
         -f "$___X_CMD_ROOT_MOD/awk/lib/j/json.awk"   \
         -f "$___X_CMD_ROOT_MOD/awk/lib/j/jqparse.awk" \
@@ -197,7 +205,8 @@ ___x_cmd_pkg_default_version___inner(){
 ___x_cmd_pkg___get_dep_name(){
     local expr="${4:?Provide EXPR, like path}"
 
-    ___x_cmd_pkg___all_info --non-version "$@" | LC_ALL="$___X_CMD_AWK_LANGUAGE" ___x_cmd_awk___inner \
+    local datalist; datalist="$( ___x_cmd_pkg___all_info --non-version "$@" )" || return
+    printf "%s\n\n" "$datalist" | LC_ALL="$___X_CMD_AWK_LANGUAGE" ___x_cmd_awk___inner \
         -v EXPR="$expr" \
         -f "$___X_CMD_ROOT_MOD/awk/lib/core.awk" \
         -f "$___X_CMD_ROOT_MOD/awk/lib/j/json.awk"   \
