Updating main branch using x7 release -> 6ec9e5b9ea8dadb483c6598a29ce23401ca14b2e

diff --git a/mod/install/lib/util b/mod/install/lib/util
--- a/mod/install/lib/util
+++ b/mod/install/lib/util
@@ -9,7 +9,11 @@ ___x_cmd_install_locate(){
 ___x_cmd_install_get___info(){
     local name="${1}"
     [ -n "$name" ] || return $?
-    name="$(___x_cmd_install_locate "$name")" || M="Can not found classify[$1]" N=install log:ret:1
+    name="$(___x_cmd_install_locate "$name")" || {
+        install:error "Installation recipe not found -> $1"
+        install:info --tip "x pkg update" "The index may be out of date. You can trigger an index update and try again."
+        return 1
+    }
 
     local _file="$___X_CMD_INSTALL_DATA/${name}.json"
     [ -f "$_file" ] || M="Can not found json file[$_file]" N=install log:ret:1
diff --git a/mod/ip/lib/addr/_index b/mod/ip/lib/addr/_index
--- a/mod/ip/lib/addr/_index
+++ b/mod/ip/lib/addr/_index
@@ -1,9 +1,68 @@
 
-# ...
+
 ___x_cmd_ip_addr(){
-    :
+
+    ___x_cmd_ip_addr___check || return $?
+
+    local format=auto
+    while [ $# -gt 0 ]; do
+        case "$1" in
+            -h|--help)      ___x_cmd help -m ip addr "$@" ;;
+            --app)          format=app  ;;
+            --tsv)          format=tsv  ;;
+            --csv)          format=csv  ;;
+            --raw)          format=raw  ;;
+            -r|--colr)      format=colr ;;
+            --auto)         format=auto ;;
+            *)              break ;;
+        esac
+        shift
+    done
+
+    ___x_cmd_ip_addr___"$format" "$@"
 }
 
-___x_cmd_ifconfig_colr_ipaddr(){
-     ___x_cmd_cmds awk -f "$___X_CMD_ROOT_MOD/ip/config/lib/config/awk/ipaddr.colr.awk"
+___x_cmd_ip_addr___check(){
+    ! ___x_cmd_hascmd ip    || return 0
+    ___x_cmd os is linux    || {
+        ip:error "Command not found -> ip"
+        ip:warn "ip command is not avaiable on non-linux platform. Try using 'x ip config' or 'x ifconfig' as alternatives."
+        return 1
+    }
+}
+
+___x_cmd_ip_addr___auto(){
+    if ___x_cmd_is_stdout2tty; then     ___x_cmd_ip_addr___app    "$@"
+    else                                ___x_cmd_ip_addr___tsv    "$@"
+    fi
+}
+
+___x_cmd_ip_addr___colrpipe(){
+    ___x_cmd_cmds awk -f "$___X_CMD_ROOT_MOD/ip/lib/addr/awk/ipaddr.colr.awk"
+}
+
+___x_cmd_ip_addr___colr(){
+    ___x_cmd_ip_addr___raw | ___x_cmd_ip_addr___colrpipe
+}
+
+___x_cmd_ip_addr___raw(){
+    if ___x_cmd_hascmd ip; then
+        ___x_cmd_cmds ip addr
+    else
+        ___x_cmd busybox ip addr
+    fi
+}
+
+___x_cmd_ip_addr___tsv(){
+    ___x_cmd_ip_addr___raw | \
+        ___x_cmd_cmds awk -f \
+            "$___X_CMD_ROOT_MOD/ip/lib/addr/awk/ip.gnu.awk"
+}
+
+___x_cmd_ip_addr___csv(){
+    ___x_cmd_ip_addr___tsv | ___x_cmd tsv tocsv
+}
+
+___x_cmd_ip_addr___app(){
+    ___x_cmd_ip_addr___csv | ___x_cmd csv app
 }
diff --git a/mod/x-cmd/lib/__otherwise b/mod/x-cmd/lib/__otherwise
--- a/mod/x-cmd/lib/__otherwise
+++ b/mod/x-cmd/lib/__otherwise
@@ -78,7 +78,59 @@ ___x_cmd_main___otherwise_other(){
         return
     fi
 
-    x:error "___x_cmd_which_one fail [code=${___x_cmd_main_otherwise_code}]"
-    return 1
+    ___x_cmd_main___otherwise_other___app "$op" "$@"
 }
 
+___x_cmd_main___otherwise_other___app(){
+    local kw="$1"
+    { ___x_cmd_is_stdout2tty && ___x_cmd_runmode_allow_manual ; } || {
+        # local str
+        # str="$(___x_cmd_main___otherwise_other___app "$kw" | ___x_cmd_cmds awk '(NF<10){ printf("%s, ", $0); }; END{ printf("...[total %s]\n", NF); }')"
+        x:error "___x_cmd_which_one fail [code=${___x_cmd_main_otherwise_code}]"
+        return 1
+    }
+
+    local candidate
+    candidate="$(___x_cmd_main___otherwise_other___app___list | ___x_cmd_main___otherwise_other___app___grep "$kw" "")"
+    [ -n "$candidate" ] || N=x M="No candidate found -> $kw" log:ret:64
+
+    local mod
+    mod="$(___x_cmd pick <<A
+$candidate
+A
+)" || return $?
+
+    [ -n "$mod" ] || return 1       # TODO: The SIGINT return 0, instead of 130.
+    mod="${mod%% *}"
+    mod="${mod%%"$___X_CMD_UNSEENCHAR_011"*}"
+
+    local id
+    ___x_cmd ui select id "next"        \
+        "Execute -> x $mod"             \
+        "Execute -> x $mod --help"      \
+        "Nothing"
+
+    case "$id" in
+        1)      ___x_cmd "$mod" ;;
+        2)      ___x_cmd "$mod" --help ;;
+        *)      return 1
+    esac
+}
+
+___x_cmd_main___otherwise_other___app___list(){
+    # list all xbin, lightweightmod ...
+    # we can consider using csv app ...
+    ___x_cmd fsiter "$___X_CMD_ROOT_MOD"
+    ___x_cmd pkg ls --xbin-desc "\t-- [pkg]:"
+}
+
+___x_cmd_main___otherwise_other___app___grep(){
+    ___x_cmd_cmds awk -v kw="$1" '
+        BEGIN{ kw = tolower(kw); }
+        {
+            name = tolower($0)
+            if (match(name, "[ \t\v]")) name = substr(name, 1, RSTART - 1)
+            if (index(name, kw)) print $0
+        }
+'
+}
