...

diff --git a/mod/gcode/lib/token b/mod/gcode/lib/token
--- a/mod/gcode/lib/token
+++ b/mod/gcode/lib/token
@@ -12,41 +12,43 @@ options:
     '
     param:run
 
-    [ -z "$profile" ] || local ___X_CMD_GCODE_CURRENT_profile="$profile"
-    [ -z "$config"  ] || local ___X_CMD_GCODE_CURRENT_config="$config"
+    (
+        # NOTE: using subshell to change current
+        [ -z "$config" ]  || ___x_cmd_gcode_config current set config  "$config"
+        [ -z "$profile" ] || ___x_cmd_gcode_config current set profile "$profile"
 
-    if [ -z "$1" ]; then
-        ___x_cmd_gcode_config_get token 2>/dev/null || {
-            gcode:error "Can't find any token"
-            gcode:warn -m "Please check your token.$(_____x_cmd_gcode_help__token_setting)"
-            return 1
-        }
-        return 0
-    else
-        [ $# -lt 2 ] || gcode:warn "Multiple tokens cannot be set at the same time, Set only the first token"
-        local tmp_token=
-        local tmp_host=
-        ___x_cmd_gcode_config___var    tmp_token=token tmp_host=host 2>/dev/null
-        if [ "$1" = "$tmp_token" ]; then
-            gcode:info "Consistent with the last recorded token"
-            ! ___x_cmd_gcode_config_get owner 1>/dev/null 2>&1 || \
-                [ "$tmp_host" != "$host" ]                     || \
-                return 0
-        fi
+        if [ -z "$1" ]; then
+            ___x_cmd_gcode_config_get token 2>/dev/null || {
+                gcode:error "Can't find any token"
+                gcode:warn -m "Please check your token.$(_____x_cmd_gcode_help__token_setting)"
+                return 1
+            }
+            return 0
+        else
+            [ $# -lt 2 ] || gcode:warn "Multiple tokens cannot be set at the same time, Set only the first token"
+            local tmp_token=""; local tmp_host=""
+            ___x_cmd_gcode_config___var    tmp_token=token tmp_host=host 2>/dev/null
+            if [ "$1" = "$tmp_token" ]; then
+                gcode:info "Consistent with the last recorded token"
+                ! ___x_cmd_gcode_config_get owner 1>/dev/null 2>&1 || \
+                    [ "$tmp_host" != "$host" ]                     || \
+                    return 0
+            fi
 
-        ___x_cmd_gcode_config_set "$1" "" "$host"
-        local ___X_CMD_GCODE_CURRENT_owner=
-        x jo env . ___X_CMD_GCODE_CURRENT_owner=.username <<A
-            $(___x_cmd_gcode_curl get "/user")
+            ___x_cmd_gcode_config_set "$1" "" "$host"
+            local tmp_owner=
+            x jo env . tmp_owner=.username <<A
+                $(___x_cmd_gcode_curl get "/user")
 A
-        if [ -z "$___X_CMD_GCODE_CURRENT_owner" ]; then
-            # reback
-            [ -z "$tmp_token" ] || ___x_cmd_gcode_config_set "$tmp_token" "" "$tmp_host" 2>/dev/null
-            gcode:error "Fail to update current owner with this token"
-            return 1
+            if [ -z "$tmp_owner" ]; then
+                # reback
+                [ -z "$tmp_token" ] || ___x_cmd_gcode_config_set "$tmp_token" "" "$tmp_host" 2>/dev/null
+                gcode:error "Fail to update current owner with this token"
+                return 1
+            fi
+            ___x_cmd_gcode_config_set "$1" "$tmp_owner" "$host"
+            ___x_cmd_ui_tf true "[Success]: Setup token successfully, The owner is $tmp_owner"
+            return 0
         fi
-        ___x_cmd_gcode_config_set "$1" "$___X_CMD_GCODE_CURRENT_owner" "$host"
-        ___x_cmd_ui_tf true "[Success]: Setup token successfully, The owner is $___X_CMD_GCODE_CURRENT_owner"
-        return 0
-    fi
+    )
 }
