...

diff --git a/mod/gcode/lib/utils b/mod/gcode/lib/utils
--- a/mod/gcode/lib/utils
+++ b/mod/gcode/lib/utils
@@ -45,9 +45,9 @@ ___x_cmd_gcode_curl(){
             if [ -n "$NO_CACHE" ]; then
                 ___x_cmd_api_gl get "$_api_url" $(eval "printf '%s ' $(x curl gencode $(___x_cmd_gcode_curl___use_query_data "$@"))")
             else
-                x ccmd 10s --           eval "___X_CMD_API_GL_HOST=$___X_CMD_API_GL_HOST ___X_CMD_API_GL_TOKEN=$___X_CMD_API_GL_TOKEN ___x_cmd_api_gl get $_api_url $(eval "printf '%s ' $(x curl gencode $(___x_cmd_gcode_curl___use_query_data "$@"))")"
+                x ccmd 10s --           eval "___X_CMD_API_GL_HOST=$___X_CMD_API_GL_HOST ___X_CMD_API_GL_TOKEN=$___X_CMD_API_GL_TOKEN ___x_cmd_api_gl get \"$_api_url\" $(eval "printf '%s ' $(x curl gencode $(___x_cmd_gcode_curl___use_query_data "$@"))")"
             fi
-            ___x_cmd_gcode_http_error   eval "___X_CMD_API_GL_HOST=$___X_CMD_API_GL_HOST ___X_CMD_API_GL_TOKEN=$___X_CMD_API_GL_TOKEN ___x_cmd_api_gl get $_api_url $(eval "printf '%s ' $(x curl gencode $(___x_cmd_gcode_curl___use_query_data "$@"))")"
+            ___x_cmd_gcode_http_error   eval "___X_CMD_API_GL_HOST=$___X_CMD_API_GL_HOST ___X_CMD_API_GL_TOKEN=$___X_CMD_API_GL_TOKEN ___x_cmd_api_gl get \"$_api_url\" $(eval "printf '%s ' $(x curl gencode $(___x_cmd_gcode_curl___use_query_data "$@"))")"
             ;;
         post|put|patch|del)
             ___x_cmd_api_gl "$op" "$_api_url" "$(x curl gencode "$@")"
@@ -57,7 +57,7 @@ ___x_cmd_gcode_curl(){
             [ -n "$1" ] || M='Please provide upload filepath' arg:ret:64
             local __file_path="$1";  shift;
             [ -f "$__file_path" ] || {
-                gcode:error "Upload Failure: Not found target file. Please check file exist: $__file_path"
+                gcode:error "Upload Failure. Not found target file. Please check file exist $__file_path"
                 return 1
             }
             ___X_CMD_API_GL_HEADER="-L -# -D \"$___X_CMD_GCODE_TMP/.____x_cmd_gcode_curl_header\""
@@ -109,6 +109,7 @@ ___x_cmd_gcode____printf_error(){
 }
 ___x_cmd_gcode____handle_resp(){
     [ -z "$gcode_resp_err" ] || ___x_cmd_gcode____printf_error "$gcode_resp_err"
+    [ -z "$gcode_resp_msg" ] || ___x_cmd_gcode____printf_error "$gcode_resp_msg"
 }
 # EndSection
 
@@ -157,7 +158,7 @@ ___x_cmd_gcode_get_multi___ui_table(){
 
 ___x_cmd_gcode_get_multi___json_prt(){
     local tmp
-    tmp=$(mktemp)
+    tmp=$(command mktemp)
     ___x_cmd_gcode_curl get "$@" page per_page > "$tmp"
     printf "\n" >> "$tmp"
 
@@ -221,21 +222,21 @@ ___x_cmd_gcode_param_normalize_repo(){
             owner_repo="$op"
             ;;
         "")
-            if [ -n "$___X_CMD_GCODE_CURRENT_repo" ]; then
-                if [ "${___X_CMD_GCODE_CURRENT_repo##*/}" != "${___X_CMD_GCODE_CURRENT_repo}" ]; then
-                    owner_repo="$___X_CMD_GCODE_CURRENT_repo"
-                elif [ -n "$___X_CMD_GCODE_CURRENT_owner" ]; then
-                    owner_repo="${___X_CMD_GCODE_CURRENT_owner}/${___X_CMD_GCODE_CURRENT_repo}"
-                else
-                    if ! owner_repo="$(___x_cmd_gcode_config_get owner)/${___X_CMD_GCODE_CURRENT_repo}"; then
-                        gcode:error "No owner provided. Default owner not set."
-                        gcode:warn -h "$(x str ml wrap "$(_____x_cmd_gcode_help__token_setting)" '    ')" -m "Can retry setup token to update owner.${___X_CMD_UNSEENCHAR_NEWLINE}Or check your current token setting."
-                        return 1
+            case "$___X_CMD_GCODE_CURRENT_repo" in
+                */*) owner_repo="$___X_CMD_GCODE_CURRENT_repo"  ;;
+                "")  owner_repo="$(_____x_cmd_git_repo)"     ;;
+                *)
+                    if [ -n "$___X_CMD_GCODE_CURRENT_owner" ]; then
+                        owner_repo="${___X_CMD_GCODE_CURRENT_owner}/${___X_CMD_GCODE_CURRENT_repo}"
+                    else
+                        owner_repo="$(___x_cmd_gcode_config_get owner)/${___X_CMD_GCODE_CURRENT_repo}" || {
+                            gcode:error "No owner provided. Default owner not set."
+                            gcode:warn -h "$(x str ml wrap "$(_____x_cmd_gcode_help__token_setting)" '    ')" -m "Can retry setup token to update owner.${___X_CMD_UNSEENCHAR_NEWLINE}Or check your current token setting."
+                            return 1
+                        }
                     fi
-                fi
-            else
-                owner_repo="$(_____x_cmd_git_repo)"
-            fi
+                ;;
+            esac
             ;;
         *)
             if [ -z "$___X_CMD_GCODE_CURRENT_owner" ]; then
