Updating main branch using x7 release -> de5f07fec940f1f876cf28aca84fde3ce947fd93

diff --git a/mod/docker/lib/simg/prepare b/mod/docker/lib/simg/prepare
--- a/mod/docker/lib/simg/prepare
+++ b/mod/docker/lib/simg/prepare
@@ -38,7 +38,13 @@ ___x_cmd_docker_simg_prepare_(){
 
     [ -z "$mode" ] || { ___x_cmd_docker_simg_prepare___"$mode"; return $?;  }
 
-    x_="";  ___x_cmd_docker_simg_prepare___base_ || return $?
+    local errcode=0
+
+    x_="";  ___x_cmd_docker_simg_prepare___base_ || {
+        errcode=$?
+        docker:warn "Fail to prepare base image."
+        return $errcode
+    }
     local baseimg="$x_"
 
     ! ___x_cmd_docker cmdinfo hascmd "$baseimg" "$REFIT_CMD" || return 0
@@ -65,6 +71,7 @@ ___x_cmd_docker_simg_prepare___base_(){
         alpine)
             ___x_cmd_docker_simg_download --if0 --imagetype alpine        || return $?
             ___x_cmd docker refit               \
+                --epxbin                        \
                 --from alpine                   \
                 --to "$x_"                      \
                 --userabc                       \
@@ -74,6 +81,7 @@ ___x_cmd_docker_simg_prepare___base_(){
         debian|ubuntu)
             ___x_cmd_docker_simg_download --if0 --imagetype "$imgtype"    || return $?
             ___x_cmd docker refit               \
+                --epxbin                        \
                 --from "$imgtype"               \
                 --to "$x_"                      \
                 --userabc                       \
@@ -83,6 +91,7 @@ ___x_cmd_docker_simg_prepare___base_(){
         kali)
             ___x_cmd_docker_simg_download --if0 --imagetype "$imgtype"    || return $?
             ___x_cmd docker refit               \
+                --epxbin                        \
                 --from kalilinux/kali-rolling   \
                 --to "$x_"                      \
                 --userabc                       \
@@ -92,6 +101,7 @@ ___x_cmd_docker_simg_prepare___base_(){
         fedora)
             ___x_cmd_docker_simg_download --if0 --imagetype "$imgtype" || return $?
             ___x_cmd docker refit               \
+                --epxbin                        \
                 --from fedora                   \
                 --to "$x_"                      \
                 --userabc                       \
@@ -101,6 +111,7 @@ ___x_cmd_docker_simg_prepare___base_(){
         arch)
             ___x_cmd_docker_simg_download --if0 --imagetype "$imgtype" || return $?
             ___x_cmd docker refit               \
+                --epxbin                        \
                 --from archlinux --to "$x_"     \
                 --userabc                       \
                 --pacman 'curl fzf jq yq sqlite3'
@@ -109,6 +120,7 @@ ___x_cmd_docker_simg_prepare___base_(){
         nixos)
             ___x_cmd_docker_simg_download --if0 --imagetype "$imgtype" || return $?
             ___x_cmd docker refit               \
+                --epxbin                        \
                 --from nixos/nix --to "$x_"     \
                 --userabc                       \
                 --nix 'curl fzf jq yq sqlite3'
@@ -132,6 +144,7 @@ ___x_cmd_docker_simg_prepare___refit_(){
     docker:info "now refitting image -> $x_"
 
     ___x_cmd docker refit                   \
+        --epxbin                            \
         --from "$baseimg" --to "$x_"        \
         --userabc                           \
         --"$REFIT_SYS" "$REFIT_PKG"         || return $?
@@ -158,7 +171,7 @@ ___x_cmd_docker_simg_prepare___imgname_(){
             gsub("github.com",      "gh", n)
             gsub("gitlab.com",      "gl", n)
             gsub("codeberg.org",    "cb", n)
-            gsub("[=:\\/-@.]", "_", n);
+            gsub("[=:\\/-@.\\[\\]]", "_", n);
             n = tolower(n);
 
             gsub( "(^[_]+)|([_]+$)", "", n )
diff --git a/mod/gh/lib/model/ls b/mod/gh/lib/model/ls
--- a/mod/gh/lib/model/ls
+++ b/mod/gh/lib/model/ls
@@ -1,15 +1,16 @@
 # shellcheck shell=dash
 
-
+# https://docs.github.com/en/github-models
+# https://docs.github.com/en/rest/models
 ___x_cmd_gh_model_ls(){
     local op="$1"
     case "$op" in
         -h|--help)
             ___x_cmd help -m gh model ls ;;
-        --csv|--app)
+        --csv|--app|--json)
             shift; ___x_cmd_gh_model_ls___"${op#--}" "$@" ;;
-        --advise)
-            shift; ___x_cmd_gh_model_ls___advise "$@" ;;
+        --advise|--update)
+            shift; ___x_cmd_gh_model_ls___"${op#--}" "$@" ;;
         *)
             if ___x_cmd_is_stdout2tty && ___x_cmd_runmode_allow_chatty ; then
                 ___x_cmd_gh_model_ls___app
@@ -21,13 +22,27 @@ ___x_cmd_gh_model_ls(){
 
 ___x_cmd_gh_model_ls___csv(){
     local x_; ___x_cmd_gh_model_ls___which_ || return
-    < "$x_" ___x_cmd ja 2c .name .task .publisher .summary .tags .license .id | \
-        ___x_cmd csv header --add Name,Task,Publisher,Summary,Tags,Lincense,Id
+    < "$x_" ___x_cmd ja 2c .id .name .publisher .summary .rate_limit_tier .supported_input_modalities .supported_output_modalities .registry .version .capabilities .limits.max_input_tokens .limits.max_output_tokens .html_url | \
+        ___x_cmd csv header --add Id,Name,Publisher,Summary,RateLimitTier,InputModalities,OutputModalities,Registry,Version,Capabilities,MaxInputTokens,MaxOutputTokens,Url
+}
+
+___x_cmd_gh_model_ls___json(){
+    local x_; ___x_cmd_gh_model_ls___which_ || return
+    ___x_cmd_cmds cat "$x_"
 }
 
 ___x_cmd_gh_model_ls___advise(){
     local x_; ___x_cmd_gh_model_ls___which_ || return
-    < "$x_" ___x_cmd ja 2c .name
+    < "$x_" ___x_cmd ja 2c .id
+}
+
+___x_cmd_gh_model_ls___app(){
+    local cur_model=
+    ___x_cmd_gh_cur cur_model:=ai_model 2>/dev/null
+    gh:info "Set the default Github model, currently using [model=${cur_model:-"$___X_CMD_GH_MODEL_DEFAULT_NAME"}]"
+    local x_=; ___x_cmd_gh_model_ls___app_inner || return
+    gh:info "Setting the default [model=$x_]"
+    ___x_cmd_gh_cfg set ai_model="$x_"
 }
 
 ___x_cmd_gh_model_ls___app_inner(){
@@ -40,24 +55,19 @@ A
     [ -n "$x_" ]
 }
 
-___x_cmd_gh_model_ls___app(){
-    local cur_model=
-    ___x_cmd_gh_cur cur_model:=ai_model 2>/dev/null
-    gh:info "Set the default Github model, currently using [model=${cur_model:-"$___X_CMD_GH_MODEL_DEFAULT_NAME"}]"
-    local x_=; ___x_cmd_gh_model_ls___app_inner || return
-    gh:info "Setting the default [model=$x_]"
-    ___x_cmd_gh_cfg set ai_model="$x_"
+___x_cmd_gh_model_ls___which_(){
+    ___x_cmd ccmd 7d -- ___x_cmd_gh_model_ls___update || return $?
+    local file="$___X_CMD_ROOT_DATA/gh/model/data.json"
+    [ -f "$file" ] || return
+    x_="$file"
 }
 
-___x_cmd_gh_model_ls___which_(){
-    x_=""
+___x_cmd_gh_model_ls___update(){
     local file="$___X_CMD_ROOT_DATA/gh/model/data.json"
     local tmpfile="${file}.tmp"
-    [ -f "$file" ] || {
-        ___x_cmd_gh_repo_file download --repo x-cmd/gh --ref main --yes data/model.yml "$tmpfile" || return
-        < "$tmpfile" ___x_cmd y2j > "$file"
-        [ -f "$file" ] || return
-        ___x_cmd rmrf "$tmpfile"
+    ___x_cmd_gh_repo_file download --repo x-cmd/gh --ref main --yes data/model.json "$tmpfile" || return $?
+    ___x_cmd mv -f "$tmpfile" "$file" || {
+        gh:error "Failed to update the Github model data file"
+        return 1
     }
-    x_="$file"
 }
diff --git a/mod/pb/lib/main b/mod/pb/lib/main
--- a/mod/pb/lib/main
+++ b/mod/pb/lib/main
@@ -13,6 +13,9 @@ ___x_cmd_pb___main(){
     case "$op" in
         c|cp|copy|-c|--cp)  ___x_cmd_pb_copy    "$@" ;;
         p|paste|-p|--paste) ___x_cmd_pb_paste   "$@" ;;
+
+        o|osc52cp)          ___x_cmd_pb_osc52cp   "$@" ;;
+
         -h|--help)          ___x_cmd help -m pb ; return  ;;
         *)                  N=x M="Unknown subcmd for pb ==> $op" log:ret:64
     esac
@@ -29,17 +32,25 @@ ___x_cmd_pb_copy(){
 ___x_cmd_pb_copy___pipe(){
     if ___x_cmd_is_termux; then
         ___x_cmd_cmds timeout 3s termux-clipboard-set
-        return
+        return $?
+    fi
+
+    # default using osc52 in SSH
+    if [ -n "$SSH_TTY" ]; then
+        ___x_cmd_pb_osc52cp
+        return $?
     fi
 
     local x_;       ___x_cmd os name_;
     case "$x_" in
         darwin)     if      ___x_cmd_hasbin pbcopy;     then ___x_cmd_cmds pbcopy
-                    else    N=pb M="command not found -> pbcopy" log:ret:1
+                    # else    N=pb M="command not found -> pbcopy" log:ret:1
+                    else                                     ___x_cmd_pb_osc52cp
                     fi ;;
 
         win)        if      ___x_cmd_hasbin clip;       then ___x_cmd_cmds clip
-                    else    N=pb M="command not found -> clip" log:ret:1
+                    # else    N=pb M="command not found -> clip" log:ret:1
+                    else                                     ___x_cmd_pb_osc52cp
                     fi ;;
 
         # Out of concerns in security, the pasteboad inside WSL is the preference.
@@ -47,7 +58,8 @@ ___x_cmd_pb_copy___pipe(){
                     elif    ___x_cmd_hasbin xsel;       then ___x_cmd_cmds xsel -ib
                     elif    ___x_cmd_hasbin wl-copy;    then ___x_cmd_cmds wl-copy
                     elif    ___x_cmd_hasbin clip.exe;   then ___x_cmd_cmds clip.exe
-                    else    N=pb M="command not found -> xclip, xsel, wl-copy or clip.exe" log:ret:1
+                   # else    N=pb M="command not found -> xclip, xsel, wl-copy or clip.exe" log:ret:1
+                    else                                     ___x_cmd_pb_osc52cp
                     fi ;;
 
         *)          N=pb M="unsupport os -> $x_" log:ret:1
@@ -77,4 +89,34 @@ ___x_cmd_pb_paste(){
 
         *)          N=pb M="unsupport os -> $x_" log:ret:1
     esac
+}
+
+___x_cmd_pb_osc52cp(){
+    case "$1" in
+        -h|--help)      ___x_cmd help -m pb osc52; return 0     ;;
+    esac
+
+    local content
+
+    if [ $# -eq 0 ]; then
+        content="$(___x_cmd_cmds head -c 100001)"
+    else
+        content="$1"
+    fi
+
+    local size="${#content}"
+
+    [ "${size}" -lt 100000 ] || N=cl M="OSC52 buffer is limited to 100000 bytes" log:ret:64
+
+    content="$(printf "%s" "$content" | ___x_cmd_cmds base64)"
+
+    pb:info "Content is writing to clipboard using OSC52. Size -> $size"
+
+    # printf "Fail to clip. %s" "The terminal doesn't support OSC52 features.              " >&2
+
+    printf "\x1b]52;c;"
+    printf "%s" "$content"
+    printf "\x07"
+
+    # printf "\r                                                                  \n" >&2
 }
