Updating main branch using x7 release -> e79ecb54b53f3d8cc330bc9b63f23b8b40fa4cc0

diff --git a/mod/pacman/lib/__xmirror/_index b/mod/pacman/lib/__xmirror/_index
--- a/mod/pacman/lib/__xmirror/_index
+++ b/mod/pacman/lib/__xmirror/_index
@@ -1,109 +1,111 @@
-# shellcheck shell=sh disable=SC3043
+# shellcheck shell=sh disable=SC3043,SC2016
 ___x_cmd_pacman___xmirror(){
-    [ $# -gt 0 ]    ||  set - --help
+    local ___X_CMD_PACMAN_mirror_sources='/etc/pacman.d/mirrorlist'
+    ___x_cmd_pacman___xmirror___ensure || return
+
+    [ "$#" -gt 0 ] || { ___x_cmd_pacman___xmirror___app ; return ; }
+
     local op="$1";      shift
     case "$op" in
-        ls|set|\
-        current|unset)      ___x_cmd_mirror_pacman "$op" "$@" ;;  # In the future, we will put the mirror code here ...
-
-        -h|--help)          x help -m pacman mirror             "$@"    ;;
-        *)                  ___x_cmd_pacman_mirror___exec "$op" "$@"    ;;
-    esac
-}
-
-# Refer: https://mirrors.tuna.tsinghua.edu.cn/help/archlinux/
-
-___x_cmd_mirror_pacman(){
-    [ "$#" -gt 0 ] || set -- --help
-
-    local op="$1"; shift
-    case "$op" in
         -h|--help)
-            x help -m mirror pacman "$@"
-            return   ;;
-    esac
-
-    x hascmd pacman || N=mirror M="[command=pacman] not found." log:ret:1
-    case "$op" in
-        ls|replace|current|unset)
-                ___x_cmd_mirror_pacman_"${op}"               "$@" ;;
-        set)    ___x_cmd_mirror_pacman_replace               "$@" ;;
-        *)      ___x_cmd_mirror___util_subcmd_invalid pacman "$@" ;;
+                ___x_cmd help -m pacman mirror                  "$@" ;;
+        ls|replace|current|rollback)
+                ___x_cmd_pacman___xmirror_"${op}"              "$@" ;;
+        set)    ___x_cmd_pacman___xmirror_replace              "$@" ;;
+        unset)  ___x_cmd_pacman___xmirror_rollback             "$@" ;;
+        *)      N=pacman M="subcommand not found."   log:ret:1       ;;
     esac
 }
 
-___x_cmd_mirror_pacman_ls(){
+___x_cmd_pacman___xmirror___ensure(){
+    ___x_cmd_hascmd pacman || N=pacman M="[command=pacman] not found." log:ret:1
+}
+
+___x_cmd_pacman___xmirror___app(){
+    local _SELECT
+    ___x_cmd ui select "_SELECT" \
+        "Methods:" \
+            "Set pacman mirror (default is ali)" \
+            "Get current pacman mirror" \
+            "List all the pacman mirror candidates" \
+            "Rollback the pacman mirror to the original official"
+
+    case "$_SELECT" in
+        1)  ___x_cmd_pacman___xmirror replace       ;;
+        2)  ___x_cmd_pacman___xmirror current       ;;
+        3)  ___x_cmd_pacman___xmirror ls            ;;
+        4)  ___x_cmd_pacman___xmirror rollback      ;;
+        *)  pacman:info "Canceled" ;        return 1 ;;
+    esac
+}
+
+___x_cmd_pacman___xmirror_ls(){
     printf "%s\n" \
-        "Code   Url                                              Name" \
-        "tuna   https://mirrors.tuna.tsinghua.edu.cn/archlinux   清华大学开源软件镜像站" \
-        "ustc   https://mirrors.ustc.edu.cn/archlinux            中国科学技术大学开源镜像站" \
-        "ali    https://mirrors.aliyun.com/archlinux             阿里云" \
-        "bfsu   https://mirrors.bfsu.edu.cn/archlinux            北京外国语大学开源软件镜像站"
+        "Code   Url                                              Name"          \
+        "tuna   https://mirrors.tuna.tsinghua.edu.cn   清华大学开源软件镜像站"      \
+        "ustc   https://mirrors.ustc.edu.cn            中国科学技术大学开源镜像站"  \
+        "ali    https://mirrors.aliyun.com             阿里云"                   \
+        "bfsu   https://mirrors.bfsu.edu.cn            北京外国语大学开源软件镜像站"
 }
 
-___x_cmd_mirror_pacman_current(){
-    ___x_cmd_cmds_cat /etc/pacman.d/mirrorlist
+___x_cmd_pacman___xmirror_advise_ls(){
+    ___x_cmd_pacman___xmirror_ls | ___x_cmd_cmds_awk 'NR >1 { print $1 }'
 }
 
-___x_cmd_mirror_pacman___url(){
-    ___x_cmd_mirror_pacman_ls | \
+___x_cmd_pacman___xmirror_current(){
+    ___x_cmd_cmds_cat "$___X_CMD_PACMAN_mirror_sources"
+}
+
+___x_cmd_pacman___xmirror___url(){
+    ___x_cmd_pacman___xmirror_ls | \
         ___x_cmd_mirror___util_get_url_by_name "$1"
 }
 
-___x_cmd_mirror_pacman_replace(){
+___x_cmd_pacman___xmirror_replace(){
     [ "$#" -gt 0 ] ||   set -- tuna
     case "$1" in
-        -h|--help)
-            x help -m mirror pacman replace "$@"
-            return   ;;
+        -h|--help)  ___x_cmd help -m mirror pacman replace "$@";    return ;;
     esac
 
-    ___x_cmd_mirror_pacman_save || N=mirror M="Save pacman original config failed." log:ret:1
+    ___x_cmd_pacman___xmirror_save || N=mirror M="Save pacman original config failed." log:ret:1
 
     local url
-    url="$(___x_cmd_mirror_pacman___url "${1}")" || return
-    mirror:info "Setting pacman mirror $url"
+    url="$(___x_cmd_pacman___xmirror___url "${1}")" || return
+    if [ -z "$url" ]; then
+        pacman:error "Invalid mirror name: $1"
+        return 1
+    fi
+    pacman:info "Setting pacman mirror $url"
 
-    local src_path
-    src_path="/etc/pacman.d/mirrorlist"
-    # ___x_cmd_proxy___util_backup /etc/pacman.d/mirrorlist pacman
+    # ___x_cmd_proxy___util_backup "$___X_CMD_PACMAN_mirror_sources" pacman
 
-    local tmp
-    tmp="$(___x_cmd_cmds_cat $src_path)"
+    ___x_cmd os arch_
+    local repo_arch='archlinux/$repo/os/$arch'
+    [ "$___X_CMD_OS_ARCH_" = "x64" ] || repo_arch='archlinuxarm/$arch/$repo'
+
 
     if [ "$(id -u)" -ne 0 ]; then
-        mirror:warn "using sudo"
-        printf "%s" "$tmp" | ___x_cmd_cmds_awk -v url="$url" '
-                                                            BEGIN { url="Server = "url "/$repo/os/$arch"; THE_REST=0}
-                                                            THE_REST==0{ if($0 ~ "^#.*"){print $0} else{ if(url != $0){printf("\n%s\n", url)} else {print $0}; THE_REST=1}}
-                                                            THE_REST==1{if(($0 != "")&&($0 != "# "url)){if($0 ~ "^#.*"){print $0} else { print "# " $0 }}}
-                                                              ' | x sudo tee "$src_path"
-        sudo pacman -Syy
+        pacman:warn "using sudo"
+        printf "Server = %s\n" "${url}/${repo_arch}" | ___x_cmd sudo tee "$___X_CMD_PACMAN_mirror_sources" > /dev/null
+        yes Y | ___x_cmd sudo pacman -Syyu
     else
-        printf "%s" "" | ___x_cmd_cmds_awk -v url="$url" '
-                                                            BEGIN { url="Server = "url "/$repo/os/$arch"; THE_REST=0}
-                                                            THE_REST==0{ if($0 ~ "^#.*"){print $0} else{ if(url != $0){printf("\n%s\n", url)} else {print $0}; THE_REST=1}}
-                                                            THE_REST==1{if(($0 != "")&&($0 != "# "url)){if($0 ~ "^#.*"){print $0} else { print "# " $0 }}}
-                                                              ' | x sudo tee "$src_path"
-        pacman -Syy
+        printf "Server = %s\n" "${url}/${repo_arch}" > "$___X_CMD_PACMAN_mirror_sources"
+        yes Y | command pacman -Syyu
     fi
 }
 
-
-___x_cmd_mirror_pacman_save(){
-    ___x_cmd_mirror___util_save "/etc/pacman.d/mirrorlist" "pacman"
+___x_cmd_pacman___xmirror_save(){
+    ___x_cmd_mirror___util_save "$___X_CMD_PACMAN_mirror_sources" "pacman"
 }
 
-
-___x_cmd_mirror_pacman_unset(){
-    ___x_cmd_mirror___util_rollback_original "/etc/pacman.d/mirrorlist" "pacman" || return
-    x rmrf "$___X_CMD_ROOT_DATA/mirror/pacman"
-
+___x_cmd_pacman___xmirror_rollback(){
+    ___x_cmd_mirror___util_rollback_original "$___X_CMD_PACMAN_mirror_sources" "pacman" || return
+    ___x_cmd rmrf "$___X_CMD_ROOT_DATA/mirror/pacman"
 
     if [ "$(id -u)" -ne 0 ]; then
-        x sudo pacman -Syy
+        yes Y | ___x_cmd sudo pacman -Syyu
     else
-             pacman -Syy
+        yes Y | command pacman -Syyu
     fi
 }
 
