...

diff --git a/mod/gh/lib/action/artifact b/mod/gh/lib/action/artifact
--- a/mod/gh/lib/action/artifact
+++ b/mod/gh/lib/action/artifact
@@ -1,10 +1,10 @@
 # shellcheck shell=sh disable=SC2039,3043,SC2154
 ___x_cmd_gh_action_artifact() {
-    param:subcmd  ___x_cmd_gh_action_artifact                  \
-        "ls|l"       "lists the workflows in a repository"       \
-        "info|i"     "View the summary of a workflow"            \
-        "rm"         "log"                                       \
-        "download"   "download"
+    param:subcmd  ___x_cmd_gh_action_artifact              \
+        "ls|l"               "List artifacts for a repository"          \
+        "info|i"             "Get workflow run artifacts info"          \
+        "rm"                 "Delete an artifact"                       \
+        "download|install"   "Download an artifact"
     param:subcmd:try
     param:run
     ___x_cmd_gh_action_artifact _param_help_doc
@@ -13,33 +13,122 @@ ___x_cmd_gh_action_artifact() {
 
 # Section: List
 # https://docs.github.com/en/rest/actions/artifacts#list-artifacts-for-a-repository
+# shellcheck disable=2154,2034
 ___x_cmd_gh_action_artifact_ls(){
-    param:void
-    :
-    gh:warn TODO
+    param:scope ___x_cmd_github
+    param:dsl <<A
+options:
+    --repo      "Provide owner name and repo name.(default:the current user repo)"      <>:RepoName
+
+    --name      "Filters artifacts by exact match on their name field"                  <>=""
+    --page      "Page number of the results to fetch."                                  <>:Numbers="1"
+    --per_page  "Results per page (max 100)"                                            <>:Per_page="30"
+    --json|-j   "output json data"
+A
+    param:run
+    ___x_cmd_gh_param_init_owner_repo
+    local NO_CACHE=1
+    local ___ls_tmp="___x_cmd_gh_curl get /repos/${owner_repo}/actions/artifacts name per_page page"
+
+    if [ -n "$json" ] || [ -n "$ENFORCE_JSON" ] ; then
+        eval "$___ls_tmp"
+    else
+        ___X_CMD_UI_STATIC=1 ___ui_table_json Artifact_ID=.id name=.name Size=.size_in_bytes Expired=.expired Created=.created_at -- \
+            "$___ls_tmp | x jo q0 .artifacts | ___x_cmd_resp___handle_table_pipe_data"
+    fi
 }
+
 # EndSection
 
 # Section: Info
 # https://docs.github.com/en/rest/actions/artifacts#get-an-artifact
 ___x_cmd_gh_action_artifact_info(){
-    :
-    gh:warn TODO
+    param:scope ___x_cmd_github
+    param:dsl <<A
+options:
+    #1          "artifact id"                                                           <>:Number
+    --repo      "Provide owner name and repo name.(default:the current user repo)"      <>:RepoName
+    --json|-j   "output json data"
+A
+    param:run
+    ___x_cmd_gh_param_init_owner_repo
+    ___x_cmd_gh_curl get "/repos/${owner_repo}/actions/artifacts/${1##*/}" | ___x_cmd_gh_action_artifact_info_status_handler "${owner_repo}" "${1##*/}"
+
 }
+
+___x_cmd_gh_action_artifact_info_status_handler(){
+    if [ -n "$json" ] || [ -n "$ENFORCE_JSON" ]; then
+        cat
+        ___x_cmd_gh_http_error
+        return
+    fi
+    (
+        x jo env . id=.id name=.name size_in_bytes=.size_in_bytes expired=.expired created_at=.created_at expires_at=.expires_at gh_resp_err=.message
+        if [ -n "$name" ]; then
+            ___x_cmd_ui_tf true  "Get $1 $id artifact info successfully" "Name: $name" "Size_Bytes: $size_in_bytes" "Expired: $expired" \
+                "Created_At: $created_at" "Expires_At: $expires_at"
+        else
+            ___x_cmd_ui_tf false "Couldn't find any data by $*"
+            ___x_cmd_gh____handle_resp
+            return 1
+        fi
+    )
+}
+
 # EndSection
 
 # Section: Remove
 # https://docs.github.com/en/rest/actions/artifacts#delete-an-artifact
 ___x_cmd_gh_action_artifact_rm(){
-    :
-    gh:warn TODO
+    param:scope     ___x_cmd_github
+    param:dsl       <<A
+options:
+    #1          "artifact id"                                                           <>:Number
+    --repo      "Provide owner name and repo name.(default:the current user repo)"      <>:RepoName
+    --yes|-y    "Ignore remove prompt interception"
+A
+    param:run
+    ___x_cmd_gh_param_init_owner_repo
+    [ "$yes" = "true" ] || ___x_cmd_ui_yesno "Are you sure ${owner_repo} to remove artifact: $(___x_cmd_ui bold red "${1##*/}") ?" || return 1
+    ___x_cmd_gh_curl delete  "/repos/${owner_repo}/actions/artifacts/${1##*/}" | (
+            x jo env . gh_resp_err=.message
+            if ___x_cmd_gh_http_error; then
+                ___x_cmd_ui_tf true  "Remove ${owner_repo} ${1##*/} artifact successfully"
+            else
+                ___x_cmd_ui_tf false "Remove ${owner_repo} ${1##*/} artifact failure"
+                ___x_cmd_gh____handle_resp
+                return 1
+            fi
+        )
+
 }
 # EndSection
 
 # Section: Download
 # https://docs.github.com/en/rest/actions/artifacts#download-an-artifact
 ___x_cmd_gh_action_artifact_download(){
-    :
-    gh:warn TODO
+    param:scope ___x_cmd_github
+    param:dsl <<A
+options:
+    #1                      "artifact id"                                                           <>:Number
+    --repo                  "Provide owner name and repo name.(default:the current user repo)"      <>:RepoName
+    --output|-o             "Download to specified output folder"                                   <>=""
+A
+    param:run
+    ___x_cmd_gh_param_init_owner_repo
+    local gh_output_dir="${___X_CMD_GH_ART}/artifact/${owner_repo}"
+    [ -z "$output" ] || {
+        gh_output_dir="$output"
+    }
+    local gh_output="${gh_output_dir}/${1##*/}.zip"
+    x mkdirp "$gh_output_dir"
+
+    if ! ___x_cmd_gh_curl download "/repos/${owner_repo}/actions/artifacts/${1##*/}/ZIP" "${gh_output}"; then
+        [ "$(___x_cmd_gh_resp_code)" != 404 ] || gh:warn "Possible the artifact has been expired. please the $1 from \`x action artifact ls\`"
+        x rmrf "$gh_output"
+        return 1
+    else
+        ___x_cmd_ui_tf true  "Download ${owner_repo} ${1##*/} artifact successfully" "Path: $gh_output"
+    fi
 }
 # EndSection
diff --git a/mod/gh/lib/action/run b/mod/gh/lib/action/run
--- a/mod/gh/lib/action/run
+++ b/mod/gh/lib/action/run
@@ -2,10 +2,10 @@
 # shellcheck disable=SC2039,3043
 ___x_cmd_gh_action_run() {
     param:subcmd  ___x_cmd_gh_action_run                    \
+        "app"       "Interactive UI show repo by owner"     \
         "ls|l"      "lists the workflows in a repository."  \
-        view        "View the summary of a workflow"        \
-        log         "log"                                   \
-        download    "download"
+        "view|v"    "View the summary of a workflow"        \
+        log         "log"
     param:subcmd:try
     param:run
     ___x_cmd_gh_action_run _param_help_doc
@@ -14,6 +14,7 @@ ___x_cmd_gh_action_run() {
 
 # Section: List
 # https://docs.github.com/en/rest/actions/workflow-runs#list-workflow-runs-for-a-repository
+# shellcheck disable=SC2154
 ___x_cmd_gh_action_run_ls() {
     param:scope ___x_cmd_github
     param:dsl <<A
@@ -28,53 +29,108 @@ options:
     --sta|--status      "Returns workflow runs with the check run status."                      <>=""
     --created           "Returns workflow runs created within the given date-time range."       <>=""
     --check_suite_id    "Returns workflow runs with the check_suite_id that you specify."       <>=""
-    --exclude_pull_requests
+    --exclude_pull_requests  "Not pull requests are omitted from the response "
 
     --page              "Page number of the results to fetch."                                  <>="1"
     --per_page          "Results per page (max 100)"                                            <>="30"
     --json|-j           "output json data"
 A
     param:run
+    ___x_cmd_gh_param_init_owner_repo
+    local NO_CACHE=1
+    local ___run_ls_tmp="___x_cmd_gh_curl get /repos/$owner_repo/actions/runs actor branch event sta created check_suite_id exclude_pull_requests"
+
+    if [ -n "$json" ] || [ -n "$ENFORCE_JSON" ] ; then
+        eval "$___run_ls_tmp"
+    else
+        ___X_CMD_UI_STATIC=1 ___ui_table_json Run_ID=.id Name=.name Conclusion=.conclusion Event=.event Branch=.head_branch Created=.created_at -- \
+            "$___run_ls_tmp | x jo q0 .workflow_runs | ___x_cmd_resp___handle_table_pipe_data"
+    fi
+}
+# EndSection
+
+# Section: app
+___x_cmd_gh_action_run_app(){
+    param:scope ___x_cmd_github
+    param:dsl <<A
+type:
+    run_status = Success Failure
+options:
+    --repo              "Provide owner name and repo name.(default:the current user repo)"      <>:RepoName
+
+    --branch            "Returns workflow runs associated with a branch."                       <>=""
+    --actor             "returns someone workflow runs."                                        <>:Username=""
+    --event             "Returns workflow run triggered by the event you specify."              <>=""
+    --sta|--status      "Returns workflow runs with the check run status."                      <>=""
+    --created           "Returns workflow runs created within the given date-time range."       <>=""
+    --check_suite_id    "Returns workflow runs with the check_suite_id that you specify."       <>=""
+    --exclude_pull_requests  "Not pull requests are omitted from the response "
+
+    --page              "Page number of the results to fetch."                                  <>="1"
+    --per_page          "Results per page (max 100)"                                            <>="30"
+A
+    param:run
 
     ___x_cmd_gh_param_init_owner_repo
 
-    local ___run_ls_tmp="___x_cmd_gh_curl get /repos/$owner_repo/actions/runs actor branch event sta created check_suite_id exclude_pull_requests"
-    if [ -n "$json" ] || [ -n "$ENFORCE_JSON" ] ; then
-        ENFORCE_JSON=1 $___run_ls_tmp
-    else
-        ___X_CMD_UI_STATIC=1 ___ui_table_json Id=.id Name=.name Conclusion=.conclusion Event=.event Branch=.head_branch Created=.created_at -- \
-            "$___run_ls_tmp | x jo q0 .workflow_runs"
-    fi
+    local ___gh_error_msg="get githubaction info list fail"
+    local ___X_CMD_TUI_TABLE_FINAL_COMMAND
+    local ___X_CMD_TUI_TABLE_CUR_LINE
+    local ___X_CMD_TUI_TABLE_CUR_ITEM
+    local ___X_CMD_GH_TUI_TABLE_REQUSET_DATA='___x_cmd_gh_curl get /repos/$owner_repo/actions/runs actor branch event sta created check_suite_id exclude_pull_requests'
+    ___x_cmd_gh_tui_app "action.run.app.awk"
+
+    ___x_cmd_gh_action_run_app_status_handler
+}
+
+___x_cmd_gh_action_run_app_status_handler(){
+    local workflow_id
+    workflow_id="${___X_CMD_TUI_TABLE_CUR_LINE##*Id: }"
+    workflow_id=${workflow_id%%
+Name:*}
+    case "$___X_CMD_TUI_TABLE_FINAL_COMMAND" in
+            "ENTER")        printf "%s\n" "$___X_CMD_TUI_TABLE_FINAL_COMMAND"  ;;
+            "i")            ___x_cmd_gh_action_run_log              --repo "${owner_repo}"   $workflow_id             ;;
+            *)              return
+    esac
 }
 # EndSection
 
 # Section: View
 # https://docs.github.com/en/rest/actions/workflow-jobs#list-jobs-for-a-workflow-run
+# shellcheck disable=SC2034
 ___x_cmd_gh_action_run_view() {
     param:scope ___x_cmd_github
     param:dsl <<A
 type:
     Filters = latest all
 options:
+    #1          "Provide run_id"                                                        <>:Number
     --repo      "Provide owner name and repo name.(default:the current user repo)"      <>:RepoName
-    --run_id    "Provide run_id"                                                        <>:Number
-    --filter    "Filters jobs by their completed_at timestamp"                          <>:Filters="latest"
 
+    --filter    "Filters jobs by their completed_at timestamp"                          <>:Filters="latest"
     --page      "Page number of the results to fetch."                                  <>:Numbers="1"
     --per_page  "Results per page (max 100)"                                            <>:Per_page="30"
     --json|-j   "output json data"
 A
     param:run
     ___x_cmd_gh_param_init_owner_repo
+    local NO_CACHE=1
+    local ___run_view_tmp="___x_cmd_gh_curl get /repos/${owner_repo}/actions/runs/${1}/jobs filter per_page page"
 
-    local ___run_view_tmp="___x_cmd_gh_curl get /repos/${owner_repo}/actions/runs/${run_id}/jobs filter per_page page"
     if [ -n "$json" ] || [ -n "$ENFORCE_JSON" ]; then
-        ENFORCE_JSON=1 $___run_view_tmp
+        eval "$___run_view_tmp"
     else
-        eval "$( $___run_view_tmp | x ja -f "$___X_CMD_ROOT_MOD/gh/lib/awk/gh_job_ui.awk")"
+        local code; if code="$(eval "$___run_view_tmp" | x ja -f "$___X_CMD_ROOT_MOD/gh/lib/awk/gh_job_ui.awk")"; then
+            eval "$code"
+        else
+            ___x_cmd_gh_http_error
+            gh:error "Not found any data"
+            return 1
+        fi
     fi
 }
-
+# x gh action run v --repo x-cmd/theme 3787465408
 # EndSection
 
 # Section: Log
@@ -85,63 +141,35 @@ ___x_cmd_gh_action_run_log() {
 type:
     Filters = latest all
 options:
+    #1          "Provide run_id"                                                        <>:Number
     --repo      "Provide owner name and repo name.(default:the current user repo)"      <>:RepoName
-    --run_id    "Provide run_id"                                                        <>:RunID
-    --logall    ""
 A
     param:run
     ___x_cmd_gh_param_init_owner_repo
-    if ___x_cmd_gh_curl download "/repos/${owner_repo}/actions/runs/${run_id}/logs" "$___X_CMD_ROOT/.actions/$run_id/$run_id-log.zip"; then
-    x uz "$___X_CMD_ROOT/.actions/$run_id/$run_id-log.zip" "$___X_CMD_ROOT/.actions/$run_id"
-        cat "$___X_CMD_ROOT"/.actions/"$run_id"/*.txt | awk '{
-          date=substr($0, 3, 8)
-          time=substr($0, 12, 8)
-          idx=index($0, " ")
-          gsub("-", "/", date)
-          print "\033[90m" date "/" time "\033[0m" substr($0, idx)
-      }' | less -r
-        rm -rf "$___X_CMD_ROOT/.actions/$run_id"
-    fi
-}
+    # local gh_output_dir="${output:-"${___X_CMD_GH_CACHE}/log/action/${owner_repo}"}"
+    local gh_output_dir="${___X_CMD_GH_CACHE}/log/action/${owner_repo}"
+    local gh_output="${gh_output_dir}/${1##*/}"
 
-# EndSection
+    x mkdirp "$gh_output"
+    if [ ! -f "${gh_output_dir}/${1##*/}-log.zip" ]; then
+        if ! ___x_cmd_gh_curl download "/repos/${owner_repo}/actions/runs/${1##*/}/logs" \
+            "${gh_output_dir}/${1##*/}-log.zip"; then
 
-# TODO: remove
-# Section: Download
-___x_cmd_gh_action_run_download() {
-    param:scope ___x_cmd_github
-    param:dsl <<A
-options:
-    --repo      "Provide owner name and repo name.(default:the current user repo)"  <>:RepoName
-
-    --per_page  "Results per page (max 100)"                                        <>:Per_page="30"
-    --page      "Page number of the results to fetch."                              <>:Numbers="1"
-    --json|-j   "output json data"
-A
-    param:run
-
-    ___x_cmd_gh_param_init_owner_repo
-    local ___run_download_tmp=" ___x_cmd_gh_curl get /repos/$owner_repo/actions/artifacts per_page page"
-    if [ -n "$json" ] || [ -n "$ENFORCE_JSON" ]; then
-        ENFORCE_JSON=1 $___run_download_tmp
-    else
-        ___ui_table_json Id=.id Name=.name Bytes=.size_in_bytes -- "$___run_download_tmp | x jo q0 .artifacts"
-        if [ "$___X_CMD_UI_TABLE_FINAL_COMMAND" = "ENTER" ];then
-            ___x_cmd_ui_yesno "Make sure you need to download $___X_CMD_UI_TABLE_CUR_LINE ?" || return
-            ___x_cmd_gh_curl download "/repos/${owner_repo}/actions/artifacts/${___X_CMD_UI_TABLE_CUR_LINE%%*}/zip" "./${___X_CMD_UI_TABLE_CUR_LINE%%*}.zip"
-        elif [ "$___X_CMD_UI_TABLE_FINAL_COMMAND" = "d" ];then
-            ___x_cmd_ui_yesno "Sure you need to delete $___X_CMD_UI_TABLE_CUR_LINE?" || return
-            ___x_cmd_gh_curl delete "/repos/${owner_repo}/actions/artifacts/${___X_CMD_UI_TABLE_CUR_LINE%%*}"| (
-                x jo env . error=.
-                if ___x_cmd_gh_http_error; then
-                    ___x_cmd_ui_tf  true "delete artifacts $___X_CMD_UI_TABLE_CUR_LINE success"
-                else
-                    ___x_cmd_ui_tf false "delete artifacts $___X_CMD_UI_TABLE_CUR_LINE fail" "ErrorMsg:$error"
-                    return 1
-                fi
-            )
+            [ "$(___x_cmd_gh_resp_code)" != 404 ] || gh:warn "Possible the action state is still unfinished. please wait action finish to retry or check the run_id exist $1. \`x action run ls\`"
+            x rmrf "$gh_output" "${gh_output_dir}/${1##*/}-log.zip"
+            return 1
         fi
     fi
+
+    x uz "${gh_output_dir}/${1##*/}-log.zip" "$gh_output" 1>/dev/null 2>&1
+    command cat "$gh_output"/*.txt | command awk '{
+            date=substr($0, 3, 8)
+            time=substr($0, 12, 8)
+            idx=index($0, " ")
+            gsub("-", "/", date)
+            print "\033[90m" date "/" time "\033[0m" substr($0, idx)
+        }' | eval "${___X_CMD_GH_EDITOR:-"command less -r"}"
+    x rmrf "$gh_output"
 }
 
 # EndSection
diff --git a/mod/gh/lib/utils b/mod/gh/lib/utils
--- a/mod/gh/lib/utils
+++ b/mod/gh/lib/utils
@@ -2,71 +2,147 @@
 # shellcheck disable=SC2039,3043
 # shellcheck disable=SC2046
 
+# x curl -L -D  /Users/qbb/.x-cmd.root/tmp/h/qbbdeMBP/r/DEFAULT/gh/.____x_cmd_gh_curl_header   -X GET -H  "Accept:application/vnd.github.v3+json"  -H  "Authorization:token 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"   "https://api.github.com/repos/x-cmd/theme/actions/runs/3787465408/logs"
+
+# Section: Help
+_____x_cmd_gh_help__token_setting(){
+    printf "\n%s %s \n%s\n" \
+        "$(___x_cmd_ui yellow 'Run command to add|repleace token:')" \
+        "$(___x_cmd_ui bold cyan "\`x gh token <token>\`")"   \
+        "$(___x_cmd_ui 'https://github.com/settings/tokens')"
+}
+
+_____x_cmd_gh_help(){
+    command -v ___x_cmd_advise_gen_help >/dev/null || xrc:mod advise/lib/gen_help
+    ___x_cmd_advise_gen_help "$___X_CMD_ROOT_MOD/gh/res/advise.jso" "$@"
+}
+
+# EndSection
+
 # Section: HTTP header & body & request
 ___x_cmd_gh_resp_header() {
     cat "$___X_CMD_GH_TMP/.____x_cmd_gh_curl_header"
 }
 
-______x_cmd_gh_resp_header_code(){
+___x_cmd_gh_resp_code(){
     ___x_cmd_gh_resp_header  | awk '$1 ~/HTTP\/2$/ {print ($2+0);exit(0)}'
 }
 
 ___x_cmd_gh_curl(){
     local op="$1"
-    local url="\"https://api.github.com$2\""
+    local _curl_url="\"https://api.github.com$2\""
+    local _accept="\"Accept:application/vnd.github.v3+json\""
+    local _authorization
+    _authorization="\"Authorization:token $(___x_cmd_gh_token)\""
     local gh_header="$___X_CMD_GH_TMP/.____x_cmd_gh_curl_header"
-    local Accept="\"Accept:application/vnd.github.v3+json\""
-    local Authorization
-    Authorization="\"Authorization:token $(___x_cmd_gh_token)\""
     shift 2
     local req
     case "$op" in
         get)
-            gh:debug           "eval x curl -D  $gh_header   -X GET -s -H  $Accept  -H  $Authorization  $(eval "printf '%s ' $(x curl gencode -G $([ $# -eq 0 ] || printf "%s== " "$@"))")  $url"
-            x ccmd 3m --            eval x curl -D "$gh_header"  -X GET -s -H "$Accept" -H "$Authorization" $(eval "printf '%s ' $(x curl gencode -G $([ $# -eq 0 ] || printf "%s== " "$@"))") "$url"
-            ___x_cmd_gh_http_error  eval x curl -D "$gh_header"  -X GET -s -H "$Accept" -H "$Authorization" $(eval "printf '%s ' $(x curl gencode -G $([ $# -eq 0 ] || printf "%s== " "$@"))") "$url"
+            gh:debug  "x curl -D  $gh_header   -X GET -s -H  $_accept  -H  $_authorization  $(eval "printf '%s ' $(x curl gencode -G $([ $# -eq 0 ] || printf "%s== " "$@"))")  $_curl_url"
+            if [ -z "$NO_CACHE" ]; then
+                x ccmd 10s --            eval x curl -D "$gh_header"  -X GET -s -H "$_accept" -H "$_authorization" $(eval "printf '%s ' $(x curl gencode $(___x_cmd_gh_curl___use_query_data "$@"))") "$_curl_url"
+                ___x_cmd_gh_http_error   eval x curl -D "$gh_header"  -X GET -s -H "$_accept" -H "$_authorization" $(eval "printf '%s ' $(x curl gencode $(___x_cmd_gh_curl___use_query_data "$@"))") "$_curl_url"
+            else
+                eval x curl -D "$gh_header"  -X GET -s -H "$_accept" -H "$_authorization" $(eval "printf '%s ' $(x curl gencode $(___x_cmd_gh_curl___use_query_data "$@"))") "$_curl_url"
+            fi
             return
             ;;
-        post)
-            req="POST";;
-        put)
-            req="PUT";;
-        patch)
-            req="PATCH";;
-        delete)
-            req="DELETE";;
         download)
-            mkdir -p "${1%/*}"
-            gh:debug "x curl -L -D  $gh_header   -X GET -H  $Accept  -H  $Authorization    -o  $1   $url"
-                eval  x curl -L -D "$gh_header"  -X GET -H "$Accept" -H "$Authorization"   -o "$1" "$url"
-                if ! ___x_cmd_gh_http_error; then
-                    local error
-                    error="$(cat "$1")"
-                    ___x_cmd_ui_tf false "Download fail:$error"
-                    return 1
-                fi
+            local __out="${1?:"Please provide output dir"}"
+            x mkdirp "${__out%/*}"
+            gh:debug "x curl -L -D  $gh_header   -X GET -H  $_accept  -H  $_authorization    -o  $__out   $_curl_url"
+            eval      x curl -L -D "$gh_header"  -X GET -H "$_accept" -H "$_authorization"   -o "$__out" "$_curl_url"
+            if ! ___x_cmd_gh_http_error; then
+                local gh_resp_err
+                gh_resp_err="$(command cat "$__out" 2>/dev/null | x jo .message)"
+                ___x_cmd_ui_tf false "Download Failure"
+                ___x_cmd_gh____handle_resp
+                return 1
+            fi
             return
             ;;
+        post)           req="POST"      ;;
+        put)            req="PUT"       ;;
+        patch)          req="PATCH"     ;;
+        delete)         req="DELETE"    ;;
     esac
-    gh:debug "eval x curl -D $gh_header -X $req    -s -H $Accept -H $Authorization $(x curl gencode "$@") $url"
+    gh:debug "x curl -D  $gh_header  -X  $req   -s -H  $_accept  -H $_authorization    $(x curl gencode "$@")   $_curl_url"
+    eval      x curl -D "$gh_header" -X "$req"  -s -H "$_accept" -H "$_authorization" "$(x curl gencode "$@")" "$_curl_url"
+}
 
-    eval x curl -D "$gh_header" -X "$req"    -s -H "$Accept" -H "$Authorization" "$(x curl gencode "$@")" "$url"
+# shellcheck disable=SC2154
+___x_cmd_gh_curl___use_query_data(){
+    [ $# -gt 0 ] || return
+    local name
+    printf "%s " "-G"
+    for name in "$@";
+    do
+        if [ "$name" = "p" ];then  [ -z "$p" ] || printf "%s " "path==$p";
+        else                                      printf "%s " "$name==" ;
+        fi
+    done
 }
 
 ___x_cmd_gh_http_error(){
     local http_resp_code
-    http_resp_code=$(______x_cmd_gh_resp_header_code)
+    http_resp_code=$(___x_cmd_gh_resp_code)
     if [ -n "$http_resp_code" ] && [ "$http_resp_code" -ge 200 ] && [ "$http_resp_code" -le 303 ]; then
         return 0
     else
-        [ $# -eq 0 ] || x ccmd invalidate "$@" >/dev/null
-        gh:error "HTTP Code Is $http_resp_code"
+        [ $# -eq 0 ] || {
+            gh:debug "---! Cache Clear !---"
+            x ccmd invalidate "$@" 1>/dev/null 2>&1
+        }
+        gh:error "HTTP Code is $http_resp_code"
         return 1
     fi
 }
+
+___x_cmd_gh____handle_resp(){
+    if  [ -n "$gh_resp_body" ]; then
+        printf "%s\n" "$gh_resp_body" | x jo
+    elif [ -n "$gh_resp_err" ]; then
+        printf "  \033[31m-\033[0m \033[1mErrorMsg: \033[31m%s\033[0m\n" "$gh_resp_err"
+    fi
+}
+
+___x_cmd_resp___handle_table_pipe_data(){
+    if ___x_cmd_gh_http_error;then
+        printf "%s" "$(cat)"
+    fi
+    return
+}
+
+___x_cmd_gh____handle_no_content(){
+    x jo env . gh_resp=. gh_resp_err=.message
+
+    [ -z "$gh_resp" ] || {
+        gh:debug "gh_resp_body: $gh_resp"
+        ___x_cmd_gh____handle_resp
+        return 1
+    }
+    ___x_cmd_gh_http_error
+}
 # EndSection
 
-# Section: pagination
+# Section: Resolve pagination
+___gh_ui_mutual() {
+    local tmp="$1"
+    shift 1
+    if [ -n "$json" ] || [ -n "$ENFORCE_JSON" ] ; then
+        ENFORCE_JSON=1 "$@"
+    else
+        # run ui table
+        eval "$tmp"
+    fi
+    local ___gh_exit_code="$?"
+    [ "$___gh_exit_code" -eq 0 ] || {
+        ___x_cmd_ui_tf false "${___gh_error_msg:-"Couldn't find any data"}" ;
+        return "$___gh_exit_code"
+    }
+}
+
 ___x_cmd_gh_get_multi() {
     if [ -n "$page" ] || [ -n "$per_page" ]; then
         ___x_cmd_gh_curl get "$@" page per_page
@@ -106,7 +182,7 @@ ___x_cmd_gh_get_multi___json_prt(){
     _____x_cmd_gh_next_url
     if [ -z "$next_url" ]; then
         cat "$tmp"
-        rm "$tmp"
+        x rmrf "$tmp"
         return
     fi
 
@@ -124,7 +200,7 @@ ___x_cmd_gh_get_multi___json_prt(){
             if (($0 == "}") || ( $0 == "]")) aaa--
             print $0
         }'
-    rm "$tmp"
+    x rmrf "$tmp"
 }
 
 _____x_cmd_gh_next_url() {
@@ -140,12 +216,13 @@ _____x_cmd_gh_next_url() {
 
 # EndSection
 
-# Section 3: Parameter Utilities
+# Section: Default param util
 alias ___x_cmd_gh_param_init_owner_repo='
-    local owner_repo
+    local owner_repo=""
     ___x_cmd_gh_param_normalize_repo  || return
 '
 
+# shellcheck disable=SC2154,SC2034
 ___x_cmd_gh_param_normalize_repo() {
     local op="$repo"
     [ -z "$op" ] && op="$1"
@@ -159,7 +236,8 @@ ___x_cmd_gh_param_normalize_repo() {
     *)
         ___x_cmd_gh_current_owner 1>/dev/null 2>&1
         if [ -z "$___X_CMD_GITHUB_DEFAULT_OWNER" ]; then
-            printf "No owner provided. Default owner not set.\n" >&2
+            gh:error "No owner provided. Default owner not set."
+            gh:warn "Check your current token setting.$(_____x_cmd_gh_help__token_setting)"
             return 1
         fi
         owner_repo="$(printf "%s" "$___X_CMD_GITHUB_DEFAULT_OWNER/$op")"
@@ -179,22 +257,13 @@ _____x_cmd_git_repo() {
     repo="${repo%.*}"
     printf "%s" "$repo"
 }
+
 _____x_cmd_git_branch() {
     git symbolic-ref -q --short HEAD 2>/dev/null
 }
+# EndSection
 
-___gh_ui_mutual() {
-    local tmp="$1"
-    shift 1
-    if [ -n "$json" ] || [ -n "$ENFORCE_JSON" ] ; then
-        ENFORCE_JSON=1 "$@"
-    else
-        # run ui table
-        eval "$tmp"
-    fi
-    return
-}
-
+# Section: Advise
 _____x_cmd_gh_advise() {
     _____x_cmd_gh_advise_parse "$@" | x jo .\* .login | x ja '{printf("%s ", $0)}'
 }
diff --git a/mod/git/lib/meta b/mod/git/lib/meta
--- a/mod/git/lib/meta
+++ b/mod/git/lib/meta
@@ -3,7 +3,10 @@
 ___x_cmd_git_meta(){
     local op="$1"; shift
     case "$op" in
-        id|branch|tag|name|root|root_|config|sizetop)       "___x_cmd_git_meta_$op" "$@" ;
+        id|branch|tag|name|root|root_|config|sizetop|\
+        lastfetch|sincelastfetch|\
+        lastmodified|sincelastmodified)
+            "___x_cmd_git_meta_$op" "$@" ;
     esac
 }
 
@@ -54,6 +57,33 @@ ___x_cmd_git_meta_config(){
     cat "$___X_CMD_GIT_META_ROOT_/.git/config"
 }
 
+___x_cmd_git_meta_lastmodified(){
+    local ___X_CMD_GIT_META_ROOT_
+    ___x_cmd_git_meta_root_ "$PWD" || {
+        git:error "Cannot locate .git/index"
+        return 1
+    }
+
+    stat -f "%m" "${___X_CMD_GIT_META_ROOT_}/.git/index"
+}
+
+___x_cmd_git_meta_lastfetch(){
+    local ___X_CMD_GIT_META_ROOT_
+    ___x_cmd_git_meta_root_ "$PWD" || {
+        git:error "Cannot locate .git/index"
+        return 1
+    }
+
+    stat -f "%a" "${___X_CMD_GIT_META_ROOT_}/.git/index"
+}
+
+___x_cmd_git_meta_sincelastmodified(){
+    printf "%s\n" $(( $(date +%s) - $(___x_cmd_git_meta_lastmodified) ))
+}
+
+___x_cmd_git_meta_sincelastfetch(){
+    printf "%s\n" $(( $(date +%s) - $(___x_cmd_git_meta_lastfetch) ))
+}
 
 ___x_cmd_git_meta_sizetop(){
     local top="${1:-10}"
