...

diff --git a/mod/gh/lib/action/run b/mod/gh/lib/action/run
--- a/mod/gh/lib/action/run
+++ b/mod/gh/lib/action/run
@@ -150,9 +150,9 @@ A
             [ -z "$___X_CMD_GH_IN_TEST" ] || { command cat; return; }
             x jo env . gh_resp_msg=.message gh_resp_err=.errors
             if ___x_cmd_gh_http_error; then
-                ___x_cmd_ui_tf  true "[Success]: Cancel ${1##*/} runs:"
+                ___x_cmd_ui_tf  true "[Success]: Cancel ${owner_repo} ${1##*/} runs"
             else
-                ___x_cmd_ui_tf false "Cancel ${1##*/} runs failure:" >&2
+                ___x_cmd_ui_tf false "Cancel ${owner_repo} ${1##*/} runs failure:" >&2
                 ___x_cmd_gh____handle_resp
                 return 1
             fi
