...

diff --git a/mod/gh/lib/action/run b/mod/gh/lib/action/run
--- a/mod/gh/lib/action/run
+++ b/mod/gh/lib/action/run
@@ -1,12 +1,14 @@
 # shellcheck shell=sh
-# shellcheck disable=SC2039,3043
+# shellcheck disable=SC2039,3043,SC2034
 ___x_cmd_gh_action_run() {
     param:subcmd  ___x_cmd_gh_action_run                    \
         "app"       "Interactive UI show repo by owner"     \
-        "ls|l"      "lists the workflows in a repository."  \
+        "ls|l"      "Lists the workflows in a repository"   \
         "view|v"    "View the summary of a workflow"        \
-        "browse|b"  "Open browser for run"                 \
-        log         "log"
+        "browse|b"  "Open the action run in the browser"    \
+        cancel      "Cancel a workflow runs"                \
+        rerun       "Re-run a workflow runs"                \
+        log         "View workflow runs log"
     param:subcmd:try
     param:run
     ___x_cmd_gh_action_run _param_help_doc
@@ -61,7 +63,6 @@ Name:*}
 
 # Section: List
 # https://docs.github.com/en/rest/actions/workflow-runs#list-workflow-runs-for-a-repository
-# shellcheck disable=SC2154
 ___x_cmd_gh_action_run_ls() {
     param:scope ___x_cmd_github
     param:dsl <<A
@@ -83,22 +84,24 @@ options:
     --json|-j           "output json data"
 A
     param:run
-    ___x_cmd_gh_param_init_owner_repo
-    local NO_CACHE=1
-    local ___run_ls_tmp="___x_cmd_gh_curl get /repos/$owner_repo/actions/runs actor branch event sta created check_suite_id exclude_pull_requests page per_page"
 
+    local NO_CACHE=1
+    ___x_cmd_gh_param_init_owner_repo
     if [ -n "$json" ] || [ -n "$ENFORCE_JSON" ] ; then
-        eval "$___run_ls_tmp"
+        ___x_cmd_gh_get_multi "/repos/$owner_repo/actions/runs" actor branch event sta created check_suite_id exclude_pull_requests
     else
-        ___X_CMD_UI_STATIC=1 ___ui_table_json Run_ID=.id Name=.name Conclusion=.conclusion Event=.event Branch=.head_branch Created=.created_at -- \
-            "$___run_ls_tmp | x jo q0 .workflow_runs"
+        ___x_cmd_gh_get_multi "/repos/$owner_repo/actions/runs" actor branch event sta created check_suite_id exclude_pull_requests | \
+            x jo .workflow_runs | \
+            x jo 2c            .id    .name .conclusion .event .head_branch .created_at | \
+            x csv header --add Run_ID Name  Conclusion  Event  Branch       Created     | \
+            x csv static_tab
     fi
 }
 # EndSection
 
 # Section: View
 # https://docs.github.com/en/rest/actions/workflow-jobs#list-jobs-for-a-workflow-run
-# shellcheck disable=SC2034
+___x_cmd_gh_action_run_view___get_data(){ ___x_cmd_gh_get_multi "/repos/${owner_repo}/actions/runs/${1}/jobs" filter; }
 ___x_cmd_gh_action_run_view() {
     param:scope ___x_cmd_github
     param:dsl <<A
@@ -114,15 +117,14 @@ options:
     --json|-j   "output json data"
 A
     param:run
-    ___x_cmd_gh_param_init_owner_repo
-    local NO_CACHE=1
-    local ___run_view_tmp="___x_cmd_gh_curl get /repos/${owner_repo}/actions/runs/${1}/jobs filter per_page page"
 
+    local NO_CACHE=1
+    ___x_cmd_gh_param_init_owner_repo
     if [ -n "$json" ] || [ -n "$ENFORCE_JSON" ]; then
-        eval "$___run_view_tmp"
+        ___x_cmd_gh_action_run_view___get_data "$1"
     else
-        local code; if code="$(eval "$___run_view_tmp" | x ja -f "$___X_CMD_ROOT_MOD/gh/lib/awk/gh_job_ui.awk")"; then
-            eval "$code"
+        local _code; if _code="$(___x_cmd_gh_action_run_view___get_data "$1" | x ja -f "$___X_CMD_ROOT_MOD/gh/lib/awk/gh_job_ui.awk")"; then
+            eval "$_code"
         else
             ___x_cmd_gh_http_error
             gh:error "Not found any data"
@@ -130,7 +132,66 @@ A
         fi
     fi
 }
-# x gh action run v --repo x-cmd/theme 3787465408
+# EndSection
+
+# Section: Cancel
+# https://docs.github.com/en/rest/actions/workflow-runs#cancel-a-workflow-run
+___x_cmd_gh_action_run_cancel() {
+    param:scope ___x_cmd_github
+    param:dsl <<A
+options:
+    #1          "The unique identifier of the workflow run"                     <>:Number
+    --repo|-r   "<ownerPath>/<RepoPath> (default ownerPath: current user)"      <>:RepoName
+A
+    param:run
+    ___x_cmd_gh_param_init_owner_repo
+    [ -n "$owner_repo" ] || M='Please provide --repo <owner/repo>"' arg:ret:64
+
+    ___x_cmd_gh_curl post  "/repos/${owner_repo}/actions/runs/${1##*/}/cancel" | (
+            [ -z "$___X_CMD_GH_IN_TEST" ] || { command cat; return; }
+            x jo env . gh_resp_msg=.message gh_resp_err=.errors
+            if ___x_cmd_gh_http_error; then
+                ___x_cmd_ui_tf  true "[Success]: Cancel ${1##*/} runs:"
+            else
+                ___x_cmd_ui_tf false "Cancel ${1##*/} runs failure:" >&2
+                ___x_cmd_gh____handle_resp
+                return 1
+            fi
+        )
+}
+# EndSection
+
+# Section: ReRun
+# https://docs.github.com/en/rest/actions/workflow-runs#re-run-a-workflow
+___x_cmd_gh_action_run_rerun() {
+    param:scope ___x_cmd_github
+    param:dsl <<A
+options:
+    #1          "The unique identifier of the workflow run"                     <>:Number
+    --repo|-r   "<ownerPath>/<RepoPath> (default ownerPath: current user)"      <>:RepoName
+    --fail|-f   "Re-run failed jobs from a workflow run"
+A
+    param:run
+    ___x_cmd_gh_param_init_owner_repo
+    [ -n "$owner_repo" ] || M='Please provide --repo <owner/repo>"' arg:ret:64
+    {
+        if [ -n "$fail" ]; then
+            ___x_cmd_gh_curl post  "/repos/${owner_repo}/actions/runs/${1##*/}/rerun-failed-jobs"
+        else
+            ___x_cmd_gh_curl post  "/repos/${owner_repo}/actions/runs/${1##*/}/rerun"
+        fi
+    } | (
+            [ -z "$___X_CMD_GH_IN_TEST" ] || { command cat; return; }
+            x jo env . gh_resp_msg=.message gh_resp_err=.errors
+            if ___x_cmd_gh_http_error; then
+                ___x_cmd_ui_tf  true "[Success]: Re-run ${fail:+'failed '}${1##*/} workflow jobs"
+            else
+                ___x_cmd_ui_tf false "Re-run ${fail:+'failed '}${1##*/} workflow jobs failure:" >&2
+                ___x_cmd_gh____handle_resp
+                return 1
+            fi
+        )
+}
 # EndSection
 
 # Section: Log
@@ -152,8 +213,8 @@ A
     x mkdirp "$gh_output"
     if [ ! -f "${gh_output_dir}/${1##*/}-log.zip" ]; then
         if ! ___x_cmd_gh_curl download \
-            "/repos/${owner_repo}/actions/runs/${1##*/}/logs" \
-            "${gh_output_dir}/${1##*/}-log.zip"; then
+                "/repos/${owner_repo}/actions/runs/${1##*/}/logs" \
+                "${gh_output_dir}/${1##*/}-log.zip"; then
 
             [ "$(___x_cmd_gh_resp_code)" != 404 ] || gh:warn "Possible the action state is still unfinished. please wait action finish to retry or check the run_id exist $1. \`x action run ls\`"
             x rmrf "$gh_output" "${gh_output_dir}/${1##*/}-log.zip"
@@ -179,15 +240,14 @@ A
 ___x_cmd_gh_action_run_browse(){
     param:scope ___x_cmd_github
     param:dsl <<A
-type:
-    Filters = latest all
 options:
     #1          "Provide run_id"                                                <>:Number
-    --repo|-r   "<ownerPath>/<RepoPath> (default ownerPath: current user)"      <>:RepoName
+    --repo|-r   "<ownerPath>/<RepoPath> (default ownerPath: current user)"      <>:RepoName=""
 A
     param:run
     ___x_cmd_gh_param_init_owner_repo
-
-    x http browse "https://github.com/${owner_repo}/actions/runs/$1"
+    [ -n "$owner_repo" ] || M='accepts option --repo|-r (<owner>/<repo>), received empty' arg:ret:64
+    local _host=""; _host=$(___x_cmd_gh___get_web_host)
+    _____x_cmd_git_browse "${_host}/${owner_repo}/actions/runs/$1"
 }
 # EndSection
diff --git a/mod/gh/lib/action/workflow b/mod/gh/lib/action/workflow
--- a/mod/gh/lib/action/workflow
+++ b/mod/gh/lib/action/workflow
@@ -31,13 +31,14 @@ options:
 A
     param:run
     ___x_cmd_gh_param_init_owner_repo
-    local ___workflow_ls_tmp="___x_cmd_gh_curl get /repos/${owner_repo}/actions/workflows per_page page"
 
     if [ -n "$json" ] || [ -n "$ENFORCE_JSON" ] ; then
-        eval "$___workflow_ls_tmp"
+        ___x_cmd_gh_get_multi "/repos/${owner_repo}/actions/workflows"
     else
-        ___X_CMD_UI_STATIC=1 ___ui_table_json Workflow_ID=.id name=.name path=.path state=.state -- \
-            "$___workflow_ls_tmp | x jo q0 .workflows"
+        ___x_cmd_gh_get_multi "/repos/${owner_repo}/actions/workflows" name | x jo .workflows | \
+            x jo 2c            .id          .name .path .state | \
+            x csv header --add  Workflow_ID  Name  Path  State | \
+            x csv static_tab
     fi
 }
 # EndSection
@@ -110,17 +111,16 @@ A
 
     ___x_cmd_gh_param_init_owner_repo
     local NO_CACHE=1
-    local ___workflow_view_tmp="___x_cmd_gh_curl get /repos/$owner_repo/actions/workflows/${1##*/}/runs \
-        actor branch event sta per_page page created check_suite_id exclude_pull_requests"
-
     if [ -n "$json" ] || [ -n "$ENFORCE_JSON" ] ; then
-        eval "$___workflow_view_tmp"
+        ___x_cmd_gh_curl get "/repos/$owner_repo/actions/workflows/${1##*/}/runs" actor branch event sta created check_suite_id exclude_pull_requests
     else
-        ___X_CMD_UI_STATIC=1 ___ui_table_json Runs_ID=.id commit=.head_commit.message name=.name conclusion=.conclusion branch=.head_branch -- \
-            "$___workflow_view_tmp | x jo q0 .workflow_runs"
+        ___x_cmd_gh_curl get "/repos/$owner_repo/actions/workflows/${1##*/}/runs" actor branch event sta created check_suite_id exclude_pull_requests | \
+            x jo .workflow_runs | \
+            x jo 2c            .id     .name .conclusion .head_branch .head_commit.message  | \
+            x csv header --add Runs_ID  Name  Conclusion  Branch       Commit               | \
+            ___x_cmd_gh_st_tab
     fi
 }
-
 # EndSection
 
 # Section: Disbale
@@ -135,13 +135,14 @@ A
     param:run
 
     ___x_cmd_gh_param_init_owner_repo
+    [ -n "$owner_repo" ] || M='Please provide --repo <owner/repo>"' arg:ret:64
     ___x_cmd_gh_curl put  "/repos/${owner_repo}/actions/workflows/${1##*/}/disable" | (
             [ -z "$___X_CMD_GH_IN_TEST" ] || { command cat; return; }
             x jo env . gh_resp_msg=.message gh_resp_err=.errors
             if ___x_cmd_gh_http_error; then
-                ___x_cmd_ui_tf  true "Disabled ${1##*/} successfully:"
+                ___x_cmd_ui_tf  true "[Success]: Disabled ${1##*/} workflow"
             else
-                ___x_cmd_ui_tf  false "Disabled ${1##*/} failure:" >&2
+                ___x_cmd_ui_tf  false "Disabled ${1##*/} workflow failure:" >&2
                 ___x_cmd_gh____handle_resp
                 return 1
             fi
@@ -160,14 +161,14 @@ options:
 A
     param:run
     ___x_cmd_gh_param_init_owner_repo
-
+    [ -n "$owner_repo" ] || M='Please provide --repo <owner/repo>"' arg:ret:64
     ___x_cmd_gh_curl put  "/repos/${owner_repo}/actions/workflows/${1##*/}/enable" | (
             [ -z "$___X_CMD_GH_IN_TEST" ] || { command cat; return; }
             x jo env . gh_resp_msg=.message gh_resp_err=.errors
             if ___x_cmd_gh_http_error; then
-                ___x_cmd_ui_tf  true "Enable ${1##*/} successfully:"
+                ___x_cmd_ui_tf  true "[Success]: Enable ${1##*/} workflow"
             else
-                ___x_cmd_ui_tf false "Enable ${1##*/} failure:" >&2
+                ___x_cmd_ui_tf false "Enable ${1##*/} workflow failure:" >&2
                 ___x_cmd_gh____handle_resp
                 return 1
             fi
@@ -197,7 +198,7 @@ A
             [ -z "$___X_CMD_GH_IN_TEST" ] || { command cat; return; }
             x jo env . gh_resp_msg=.message gh_resp_err=.errors
             if ___x_cmd_gh_http_error; then
-                ___x_cmd_ui_tf  true "Created workflow_dispatch event for ${1##*/} at ${ref}:"
+                ___x_cmd_ui_tf  true "[Success]: Created workflow_dispatch event for ${1##*/} at ${ref}"
             else
                 ___x_cmd_ui_tf false "Created workflow_dispatch event failure:" >&2
                 ___x_cmd_gh____handle_resp
diff --git a/mod/gh/lib/utils b/mod/gh/lib/utils
--- a/mod/gh/lib/utils
+++ b/mod/gh/lib/utils
@@ -45,9 +45,9 @@ ___x_cmd_gh_curl(){
             if [ -n "$NO_CACHE" ]; then
                 ___x_cmd_api_gh get "$_api_url" $(eval "printf '%s ' $(x curl gencode $(___x_cmd_gh_curl___use_query_data "$@"))")
             else
-                x ccmd 10s --        eval "___X_CMD_API_GH_HOST=$___X_CMD_API_GH_HOST ___X_CMD_API_GH_TOKEN=$___X_CMD_API_GH_TOKEN ___x_cmd_api_gh get $_api_url $(eval "printf '%s ' $(x curl gencode $(___x_cmd_gh_curl___use_query_data "$@"))")"
+                x ccmd 10s --        eval "___X_CMD_API_GH_HOST=$___X_CMD_API_GH_HOST ___X_CMD_API_GH_TOKEN=$___X_CMD_API_GH_TOKEN ___x_cmd_api_gh get \"$_api_url\" $(eval "printf '%s ' $(x curl gencode $(___x_cmd_gh_curl___use_query_data "$@"))")"
             fi
-            ___x_cmd_gh_http_error   eval "___X_CMD_API_GH_HOST=$___X_CMD_API_GH_HOST ___X_CMD_API_GH_TOKEN=$___X_CMD_API_GH_TOKEN ___x_cmd_api_gh get $_api_url $(eval "printf '%s ' $(x curl gencode $(___x_cmd_gh_curl___use_query_data "$@"))")"
+            ___x_cmd_gh_http_error   eval "___X_CMD_API_GH_HOST=$___X_CMD_API_GH_HOST ___X_CMD_API_GH_TOKEN=$___X_CMD_API_GH_TOKEN ___x_cmd_api_gh get \"$_api_url\" $(eval "printf '%s ' $(x curl gencode $(___x_cmd_gh_curl___use_query_data "$@"))")"
             ;;
         post|put|patch|del)
             ___x_cmd_api_gh "$op" "$_api_url" "$(x curl gencode "$@")"
@@ -62,7 +62,7 @@ ___x_cmd_gh_curl(){
             if ! ___x_cmd_gh_http_error; then
                 (
                     command cat "$__out" 2>/dev/null | x jo env . gh_resp_msg=.message gh_resp_err=.errors
-                    ___x_cmd_ui_tf false "Download Failure" >&2
+                    ___x_cmd_ui_tf false "Download failure:" >&2
                     ___x_cmd_gh____handle_resp
                     return 1
                 )
@@ -74,7 +74,7 @@ ___x_cmd_gh_curl(){
             local __file_type="\"Content-Type: ${file_type:-"octet-stream"}\""
             ___X_CMD_API_GH_HEADER="-L -# -H \"Accept:application/vnd.github.v3+json\" -D \"$___X_CMD_GH_TMP/.____x_cmd_gh_curl_header\" -H ${__file_type}"
             [ -f "$__file_path" ] || {
-                gh:error "Upload Failure: Not found target file. Please check file exist: $__file_path"
+                gh:error "Upload Failure. Not found target file. Please check file exist $__file_path"
                 return 1
             }
             gh:info "Uploading file..."
@@ -87,8 +87,8 @@ ___x_cmd_gh_curl(){
 # shellcheck disable=SC2154
 ___x_cmd_gh_curl___use_query_data(){
     [ $# -gt 0 ] || return
-    local name=""
     printf "%s " "-G"
+    local name=""
     for name in "$@";
     do
         if [ "$name" = "p" ];then  [ -z "$p" ] || printf "%s " "path==$p";
@@ -131,20 +131,13 @@ ___x_cmd_gh____handle_resp(){
 # EndSection
 
 # Section: Resolve pagination
-___gh_ui_mutual() {
-    local tmp="$1"
-    shift 1
-    if [ -n "$json" ] || [ -n "$ENFORCE_JSON" ] ; then
-        ENFORCE_JSON=1 "$@"
+
+___x_cmd_gh_st_tab(){
+    if ! ___x_cmd_is_interative_tty || [ ! -t 1 ]; then
+        x csv static_tab
     else
-        # run ui table
-        eval "$tmp"
+        x csv static_tab "$@"
     fi
-    local ___gh_exit_code="$?"
-    [ "$___gh_exit_code" -eq 0 ] || {
-        ___x_cmd_ui_tf false "${___gh_error_msg:-"Couldn't find any data"}:" >&2
-        return "$___gh_exit_code"
-    }
 }
 
 ___x_cmd_gh_get_multi() {
@@ -155,6 +148,7 @@ ___x_cmd_gh_get_multi() {
 
     local page=1
     local per_page=100
+    local NO_CACHE=1
     if [ -n "$json" ] || [ -n "$ENFORCE_JSON" ]; then
         ___x_cmd_gh_get_multi___json_prt "$@"
     else
@@ -170,7 +164,7 @@ ___x_cmd_gh_get_multi___ui_table(){
     [ -n "$next_url" ] || return
 
     while [ -n "$next_url" ]; do
-        ___x_cmd_gh_curl get "$next_url"
+        ___x_cmd_gh_curl get "$next_url" || return
         printf "\n"
         _____x_cmd_gh_next_url
     done
@@ -178,7 +172,7 @@ ___x_cmd_gh_get_multi___ui_table(){
 
 ___x_cmd_gh_get_multi___json_prt(){
     local tmp=""
-    tmp=$(mktemp)
+    tmp=$(command mktemp)
     ___x_cmd_gh_curl get "$@" page per_page > "$tmp"
     printf "\n" >> "$tmp"
 
@@ -191,7 +185,7 @@ ___x_cmd_gh_get_multi___json_prt(){
     fi
 
     while [ -n "$next_url" ]; do
-        ___x_cmd_gh_curl get "$next_url" >> "$tmp"
+        { ___x_cmd_gh_curl get "$next_url" >> "$tmp"; } || return
         printf "\n" >> "$tmp"
         _____x_cmd_gh_next_url
     done
@@ -284,5 +278,17 @@ _____x_cmd_gh_advise_parse() {
     case "$op" in
         orgls) x ccmd 1d -- x gh org ls 2>/dev/null;;
     esac
+}
+# EndSection
+
+# Section: gh util
+# NOTE: remove prefix: _host_tmp="${_host_tmp#*'://'}";
+___x_cmd_gh___get_web_host(){
+    local _host_tmp=""
+    if _host_tmp="$(___x_cmd_gh_config_get web_host 2>/dev/null)"; then
+        printf "%s" "$_host_tmp"
+    else
+        printf "%s" "https://github.com"
+    fi
 }
 # EndSection
