...

diff --git a/mod/pkg/lib/mutate/download b/mod/pkg/lib/mutate/download
--- a/mod/pkg/lib/mutate/download
+++ b/mod/pkg/lib/mutate/download
@@ -1,4 +1,4 @@
-# shellcheck    shell=sh            disable=SC2016,SC3043      # xrc
+# shellcheck    shell=dash
 
 # TODO: Multiple thread
 # TODO: Download Manager and more strategy
@@ -6,12 +6,8 @@
 
 ___x_cmd_pkg_download(){
     x:trace pkg/download
-
     case "$1" in
-        -h|--help)
-            ___x_cmd_pkg_help download
-            return 1
-            ;;
+        -h|--help) ___x_cmd_pkg_help download; return 1 ;;
     esac
 
     local name="${1:?Provide pkg name}"
@@ -19,12 +15,11 @@ ___x_cmd_pkg_download(){
     local osarch="${3:-$(___x_cmd_pkg_osarch)}"
     [ -n "$version" ] || {
         pkg:error "Not found candidate: $name;"
-        pkg:error "Please use ' x pkg ll' or ' x pkg ls all <candidate> ' to check available candidate and version"
+        pkg:error "Please use 'x pkg ll' or 'x pkg ls all <candidate>' to check available candidate and version"
         return 1
     }
 
-    local url_list
-    url_list="$(___x_cmd_pkg___list "$name" "$version" "$osarch" "url.${___X_CMD_WEBSRC_REGION:-internet}" )" || return
+    local url_list; url_list="$(___x_cmd_pkg___list "$name" "$version" "$osarch" "url.${___X_CMD_WEBSRC_REGION:-internet}" )" || return
 
     if [ -z "$url_list" ]; then
         pkg:error "Not found url for $name $version"
@@ -32,27 +27,28 @@ ___x_cmd_pkg_download(){
         return 1
     fi
 
-    local download_file_ext md5 sha1 sha256 sha512
-    ___x_cmd_pkg___attr "$name" "$version" "$osarch" "md5,sha1,sha256,sha512,download_file_ext"
+
+    local download_file_ext; local md5 ; local sha1 ; local sha256; local sha512 ; local unpack
+    ___x_cmd_pkg___attr "$name" "$version" "$osarch" "md5,sha1,sha256,sha512,download_file_ext,unpack"
     local url
     local head
-
-    ___x_cmd_pkg___attr "$name" "$version" "$osarch" "unpack"
-    if [ "$unpack" = "none" ] && ! [ -n "$download_file_ext" ]; then
-        local os="${osarch%/*}";  local arch="${osarch#*/}"
-        local ball="$___X_CMD_PKG_DOWNLOAD_PATH/$name/$name.$os.$arch"
+    local os="${osarch%/*}";  local arch="${osarch#*/}"
+    if [ "$unpack" = "none" ] && [ -z "$download_file_ext" ]; then
+        local ball="$___X_CMD_PKG_DOWNLOAD_PATH/$name/$name.${os}.${arch}"
     else
-        local ball="$___X_CMD_PKG_DOWNLOAD_PATH/$name/$version.$download_file_ext"
+        local ball="$___X_CMD_PKG_DOWNLOAD_PATH/$name/${version}_${os}_${arch}.$download_file_ext"
     fi
 
     mkdir -p "$___X_CMD_PKG_DOWNLOAD_PATH/$name" || {
-            pkg:error "Create $___X_CMD_PKG_DOWNLOAD_PATH/$name failed" ; return 1
-        }
+        pkg:error "Create $___X_CMD_PKG_DOWNLOAD_PATH/$name failed" ; return 1
+    }
     pkg:debug --Download name "$name" --version "$version" --url_list "$url_list" --ball "$ball"
 
-
     if [ -f "$ball" ]; then
-        ! ___x_cmd_pkg_download___check_hashsum "$ball" "$md5" "$sha1" "$sha256" "$sha512" || return 0
+        if ___x_cmd_pkg_download___check_hashsum "$ball" "$md5" "$sha1" "$sha256" "$sha512"; then
+            pkg:debug "File already downloaded: $ball"
+            return 0
+        fi
 
         pkg:warn "File corrupted. Download the $ball again."
         x rmrf "$ball"
@@ -69,17 +65,14 @@ ___x_cmd_pkg_download(){
         trap 'x pkg remove $name $version 2>/dev/null; printf "\r\n";  pkg:error "Download interrupted"; return 1;' INT
         head=$(curl -I "$url" | awk 'NR==1{ print $2}' )
         if [ "$head" -eq "200" ] || [ "$head" -eq "304" ] || [ "$head" -eq "302" ] || [ "$head" -eq "301" ]; then
-            curl --progress-bar --location --retry-max-time 10 --retry 0 "$url" --output "$ball"
-            if [ "$?" != 0 ]; then
+            if ! curl --progress-bar --location --retry-max-time 10 --retry 0 "$url" --output "$ball"; then
                 pkg:warn "Fail to download from $url"
                 x rmrf "$ball"
                 return 1
-                continue
             fi
         else
             pkg:error "resource invalid: $url "
             return 1
-            continue
         fi
 
         ! ___x_cmd_pkg_download___check_hashsum "$ball" "$md5" "$sha1" "$sha256" "$sha512" || return 0
