...

diff --git a/mod/pkg/lib/mutate/download b/mod/pkg/lib/mutate/download
--- a/mod/pkg/lib/mutate/download
+++ b/mod/pkg/lib/mutate/download
@@ -17,13 +17,18 @@ ___x_cmd_pkg_download(){
     local name="${1:?Provide pkg name}"
     local version="${2:-$(___x_cmd_pkg_default_version "$name")}"
     local osarch="${3:-$(___x_cmd_pkg_osarch)}"
-    [ -n "$version" ] || return
+    [ -n "$version" ] || {
+        pkg:error "Not found candidate: $name;"
+        pkg:error "Please use ' x pkg ll' or ' x pkg ls all <candidate> ' to check available candidate and version"
+        return 1
+    }
 
     local url_list
     url_list="$(___x_cmd_pkg___list "$name" "$version" "$osarch" "url.${___X_CMD_WEBSRC_REGION:-internet}" )" || return
 
     if [ -z "$url_list" ]; then
-        pkg:error "Not found url"
+        pkg:error "Not found url for $name $version"
+        pkg:error "Please use ' x pkg ll' or ' x pkg ls all <candidate> ' to check available candidate and version"
         return 1
     fi
 
@@ -83,7 +88,6 @@ $url_list
 A
     )
 }
-
 
 ___x_cmd_pkg_download___check_hashsum(){
     local filepath="${1:?Please priovide filepath}"
diff --git a/mod/pkg/lib/mutate/populate b/mod/pkg/lib/mutate/populate
--- a/mod/pkg/lib/mutate/populate
+++ b/mod/pkg/lib/mutate/populate
@@ -60,11 +60,14 @@ ___x_cmd_pkg_populate___unzip(){
         mkdir -p "$tgt"
         pkg:debug "Moving $ball to $tgt"
         mv -f "$ball"/* "$tgt"
-    else
+    elif [ "$unpack" = "file" ]; then
         pkg:info "Unpack - '$ball to $tgt'"
         x uz "$ball" "$tgt"  || {
             pkg:error "Fail to unzip $ball"; return 1
         }
+    else
+        pkg:error "Yml of $name lacks of unpack key"
+        return 1
     fi
 
     pkg:info "Finish unpack $name $version to $tgt"
@@ -76,8 +79,15 @@ ___x_cmd_pkg_populate(){
     local osarch="${3:-$(___x_cmd_pkg_osarch)}"
     local tgt="${4:-"$___X_CMD_PKG_POPULATE_PATH/$name/$version"}"
 
+    [ -n "$version" ] || {
+        pkg:error "Not found candidate: $name or version;"
+        pkg:error "Please use ' x pkg ll' or ' x pkg ls all <candidate> ' to check available candidate and version"
+        return 1
+    }
+
     local bin_path
     bin_path="$(___x_cmd_pkg_xbin_path "$name" "$version" "$osarch" "$tgt")"
+    
     [ ! -x "$bin_path" ] || return 0
 
     ___x_cmd_pkg_populate___unzip "$name" "$version" "$osarch" "$tgt" || {
