...

diff --git a/mod/pkg/lib/mutate/populate b/mod/pkg/lib/mutate/populate
--- a/mod/pkg/lib/mutate/populate
+++ b/mod/pkg/lib/mutate/populate
@@ -61,13 +61,13 @@ ___x_cmd_pkg_populate___unzip(){
         x rmrf "$tgt"
         mkdir -p "$tgt"
         pkg:debug "Moving $unpack_dir to $tgt"
-        mv -f "$unpack_dir"/*/* "$tgt"
+        x mv -f "$unpack_dir"/*/* "$tgt"
         x rmrf "$unpack_dir"
     elif [ "$unpack" = "none" ]; then
         local ball="$___X_CMD_PKG_DOWNLOAD_PATH/$name"
         mkdir -p "$tgt"
         pkg:debug "Moving $ball to $tgt"
-        mv -f "$ball"/* "$tgt"
+        x mv -f "$ball"/* "$tgt"
     elif [ "$unpack" = "file" ]; then
         pkg:info "Unpack - '$ball to $tgt'"
         x uz "$ball" "$tgt"  || {
@@ -87,10 +87,9 @@ ___x_cmd_pkg_populate(){
     local osarch="${3:-$(___x_cmd_pkg_osarch)}"
     local tgt="${4:-"$___X_CMD_PKG_POPULATE_PATH/$name/$version"}"
 
-
     [ -n "$version" ] || {
         pkg:error "Not found candidate: $name or version;"
-        pkg:error "Please use ' x pkg ll' or ' x pkg ls all <candidate> ' to check available candidate and version"
+        pkg:error "Please use 'x pkg ll' or 'x pkg ls all <candidate>' to check available candidate and version"
         return 1
     }
 
@@ -117,7 +116,10 @@ ___x_cmd_pkg_populate(){
     local ___X_CMD_PKG___META_OS="${osarch%%/*}"
     local ___X_CMD_PKG___META_ARCH="${osarch##*/}"
     local ___X_CMD_PKG___META_TGT="$tgt"
-    . "$script_path" || {
-        pkg:error "Source $script_path failed" ; return 1
+    {
+        trap 'x rmrf $tgt; printf "\r\n";  pkg:error "pxopulate interrupted"; return 1;' INT
+        . "$script_path" || {
+            pkg:error "Source $script_path failed" ; return 1
+        }
     }
 }
