...

diff --git a/mod/gcode/lib/repo/apply/index b/mod/gcode/lib/repo/apply/index
--- a/mod/gcode/lib/repo/apply/index
+++ b/mod/gcode/lib/repo/apply/index
@@ -1,13 +1,12 @@
 # shellcheck shell=sh disable=SC3043,2002,SC2154
 
-# x gcode project apply a.yml lijunhao=edwinjhlee zhengyuhang=mnnna
-# x gcode project apply .x-cmd/apply/gitcode-project.yml  lijunhao=edwinjhlee
-# http://localhost:4000/13.7/ee/api/projects.html
-___x_cmd_gcode_project_apply(){
+# x gcode repo apply a.yml lijunhao=edwinjhlee zhengyuhang=mnnna
+# x gcode repo apply .x-cmd/apply/gitcode-repo.yml  lijunhao=edwinjhlee
+___x_cmd_gcode_repo_apply(){
     param:void
-    if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then { ___x_cmd_gcode_project_apply__help; return 0; }
+    if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then { ___x_cmd_gcode_repo_apply__help; return 0; }
     fi
-    ___x_cmd_gcode_current_owner 1>/dev/null || return 1
+    ___x_cmd_gcode_config_get owner 1>/dev/null || return 1
 
     local filepath="${1:?Provide filepath}"; shift
 
@@ -19,13 +18,13 @@ ___x_cmd_gcode_project_apply(){
                 *)              <"$filepath" x y2j ;;
             esac' |
              {
-                x jo env . content=. owner_project=.project  apply_member=.member
-                [ -n "$owner_project" ] || { gcode:error "Not found apply configure project main key" >/dev/stderr; return 1; }
-                ___x_cmd_gcode_project_apply__replace "$@"
+                x jo env . content=. owner_repo=.repo  apply_member=.member
+                [ -n "$owner_repo" ] || { gcode:error "Not found apply configure repo main key" >/dev/stderr; return 1; }
+                ___x_cmd_gcode_repo_apply__replace "$@"
                 printf "%s\n" "$content"
-                gcode:info "Getting project info ..."
-                ___x_cmd_gcode_project_apply__member_info
-                ___x_cmd_gcode_project_apply__project_info
+                gcode:info "Getting repo info ..."
+                ___x_cmd_gcode_repo_apply__member_info
+                ___x_cmd_gcode_repo_apply__repo_info
             }
         } | {
             awk -f "$___X_CMD_ROOT_MOD/awk/lib/default.awk" \
@@ -33,10 +32,10 @@ ___x_cmd_gcode_project_apply(){
                 -f "$___X_CMD_ROOT_MOD/awk/lib/sh.awk" \
                 -f "$___X_CMD_ROOT_MOD/awk/lib/j/json.awk" \
                 -f "$___X_CMD_ROOT_MOD/awk/lib/j/jiter.awk" \
-                -f "$___X_CMD_ROOT_MOD/gcode/lib/awk/project/member.awk"  \
-                -f "$___X_CMD_ROOT_MOD/gcode/lib/awk/project.awk" \
+                -f "$___X_CMD_ROOT_MOD/gcode/lib/awk/repo/member.awk"  \
+                -f "$___X_CMD_ROOT_MOD/gcode/lib/awk/repo.awk" \
                 -f "$___X_CMD_ROOT_MOD/gcode/lib/awk/replace.awk" \
-                -f "$___X_CMD_ROOT_MOD/gcode/lib/project/apply/apply.awk"
+                -f "$___X_CMD_ROOT_MOD/gcode/lib/repo/apply/apply.awk"
         }
     )"; then
         # gcode:debug "apply code: $code"
@@ -44,7 +43,7 @@ ___x_cmd_gcode_project_apply(){
         #     printf "%s\n" ""; gcode:info "Repo apply no changes required"
         #     return 0
         # }
-        # gcode:info "Handling project by info ..."
+        # gcode:info "Handling repo by info ..."
         # if [ -n "$___X_CMD_GH_DRY_RUN" ]; then      printf "%s\n" "$code";
         # else                                        eval "$code";
         # fi
@@ -57,20 +56,20 @@ ___x_cmd_gcode_project_apply(){
 
 # shellcheck disable=SC2154
 # http://localhost:4000/13.7/ee/api/members.html#get-a-member-of-a-group-or-project
-___x_cmd_gcode_project_apply__member_info(){
+___x_cmd_gcode_repo_apply__member_info(){
     [ -n "$apply_member" ] || { printf "\n"; return 0; }
 
-    NO_CACHE=1 x gcode project member ls --json --project "$owner_project" | x ja t "\t" ; printf "\n"
-    # cat "$(x wsroot)"/.x-cmd/project_member.json | x ja t "\t" ; printf "\n"
+    NO_CACHE=1 x gcode repo member ls --json --repo "$owner_repo" | x ja t "\t" ; printf "\n"
+    # cat "$(x wsroot)"/.x-cmd/repo_member.json | x ja t "\t" ; printf "\n"
 }
 
 # http://localhost:4000/13.7/ee/api/projects.html#get-single-project
-___x_cmd_gcode_project_apply__project_info(){
-    NO_CACHE=1  x gcode project info --json "$owner_project" | x ja t "\t" ; printf "\n"
-    # cat "$(x wsroot)"/.x-cmd/project_info.json | x ja t "\t" ; printf "\n"
+___x_cmd_gcode_repo_apply__repo_info(){
+    NO_CACHE=1  x gcode repo info --json "$owner_repo" | x ja t "\t" ; printf "\n"
+    # cat "$(x wsroot)"/.x-cmd/repo_info.json | x ja t "\t" ; printf "\n"
 }
 
-___x_cmd_gcode_project_apply__replace(){
+___x_cmd_gcode_repo_apply__replace(){
     if [ $# -gt 0 ]; then
         local IFS=","; printf "replace:%s\n" "$*"
         return
@@ -80,15 +79,15 @@ ___x_cmd_gcode_project_apply__replace(){
     # cat "$(x wsroot)"/.x-cmd/lteam-member.yml | x y2j | x ja t "\t" ; printf "\n"
 }
 
-___x_cmd_gcode_project_apply__help(){
+___x_cmd_gcode_repo_apply__help(){
     printf "\033[1m%s\033[0m\n\n\033[33m%s\033[0m\n    \033[36m%s\033[0m\n    \033[36m%s\033[0m\n" \
-        "x gcode project apply <filepath | '-' config from stdin> <...alias name list>" \
+        "x gcode repo apply <filepath | '-' config from stdin> <...alias name list>" \
         "Example" \
-        "x gcode project apply project.yml bot=x-cmd-bot" \
-        "cat ./project.yml | x gcode project apply - bot=x-cmd-bot"
+        "x gcode repo apply repo.yml bot=x-cmd-bot" \
+        "cat ./repo.yml | x gcode repo apply - bot=x-cmd-bot"
 }
 
-# cat .x-cmd/gitcode-project.yml | x gcode project apply -  \
+# cat .x-cmd/gitcode-repo.yml | x gcode repo apply -  \
 #     "lijunhao=edwinjhlee"  \
 #     "hejiajie=jerry8hero" \
 #     "litinghui=padparadsayc" \
diff --git a/mod/gcode/lib/token b/mod/gcode/lib/token
--- a/mod/gcode/lib/token
+++ b/mod/gcode/lib/token
@@ -1,33 +1,50 @@
 # shellcheck shell=sh
-# shellcheck disable=SC2039,3043
-# shellcheck disable=SC2120
+# shellcheck disable=SC2039,3043,SC2154
 
 ___x_cmd_gcode_token(){
-    param:void
-    if [ "$1" = "--help" ] || [ "$1" = "-h" ]; then _____x_cmd_gcode_help token; return 0
-    fi
+    param:scope     ___x_cmd_gcode
+    param:dsl       '
+options:
+    #1          "access token. empty output current token"     <>=""
+    --host      "config request host"                          <>="https://gitcode.net/api/v4"
+    --profile   "config profile name. empty use default"       <>=""
+    --config    "config file path. empty use default"          <>=""
+    '
+    param:run
+
+    [ -z "$profile" ] || local ___X_CMD_GCODE_CURRENT_profile="$profile"
+    [ -z "$config"  ] || local ___X_CMD_GCODE_CURRENT_config="$config"
 
     if [ -z "$1" ]; then
-        ___x_cmd_gcode_config_get "oauth_token"  || return 1
+        ___x_cmd_gcode_config_get token 2>/dev/null || {
+            gcode:error "Can't find any token"
+            gcode:warn -m "Please check your token.$(_____x_cmd_gcode_help__token_setting)"
+            return 1
+        }
         return 0
     else
-        [ $# -lt 2 ] || gcode:warn "Multiple tokens cannot be set at the same time,Set only the first token"
-        local tmp_token
-        tmp_token="$(___x_cmd_gcode_config_get "oauth_token")"
-
+        [ $# -lt 2 ] || gcode:warn "Multiple tokens cannot be set at the same time, Set only the first token"
+        local tmp_token=
+        local tmp_host=
+        ___x_cmd_gcode_config___var    tmp_token=token tmp_host=host 2>/dev/null
         if [ "$1" = "$tmp_token" ]; then
             gcode:info "Consistent with the last recorded token"
-            return 0
+            ! ___x_cmd_gcode_config_get owner 1>/dev/null 2>&1 || return 0
         fi
 
-        ___x_cmd_gcode_config_set "oauth_token" "$1" 1>/dev/null
-        ___X_CMD_GCODE_DEFAULT_OWNER=
-        if ! ___x_cmd_gcode_current_owner 1>/dev/null 2>&1; then
-            [ -z "$tmp_token" ] || ___x_cmd_gcode_config_set "oauth_token" "$tmp_token" 1>/dev/null
+        ___x_cmd_gcode_config_set "$1" "" "$host"
+        local ___X_CMD_GCODE_CURRENT_owner=
+        x jo env . ___X_CMD_GCODE_CURRENT_owner=.username <<A
+            $(___x_cmd_gcode_curl get "/user")
+A
+        if [ -z "$___X_CMD_GCODE_CURRENT_owner" ]; then
+            # reback
+            [ -z "$tmp_token" ] || ___x_cmd_gcode_config_set "$tmp_token" "" "$tmp_host" 2>/dev/null
             gcode:error "Fail to update current owner with this token"
             return 1
         fi
-        ___x_cmd_ui_tf true "Set default token successfully, The default user is $___X_CMD_GCODE_DEFAULT_OWNER"
+        ___x_cmd_gcode_config_set "" "$___X_CMD_GCODE_CURRENT_owner" "$host"
+        ___x_cmd_ui_tf true "Setup token successfully, The owner is $___X_CMD_GCODE_CURRENT_owner:"
         return 0
     fi
 }
diff --git a/mod/gcode/lib/utils b/mod/gcode/lib/utils
--- a/mod/gcode/lib/utils
+++ b/mod/gcode/lib/utils
@@ -22,68 +22,49 @@ ___x_cmd_gcode_resp_header(){
 }
 
 ___x_cmd_gcode_resp_code(){
-    ___x_cmd_gcode_resp_header  | awk '$1 ~/HTTP\/1.1$/ {print ($2+0);exit(0)}'
+    ___x_cmd_gcode_resp_header  | awk '($1 ~ "HTTP/(1.*|2)$" && $3 != "Connection" && $4 != "established") {
+        print  int($2);
+        exit(0)
+    }'
 }
 
 ___x_cmd_gcode_curl(){
     local op="$1"
-    local _curl_url="\"${___X_CMD_GCODE_DOMAIN:-"https://gitcode.net"}/api/v4${2}\""
-    local _content_type="\"Content-Type: application/json\""
-    local _authorization
-    _authorization="\"PRIVATE-TOKEN: $(___x_cmd_gcode_token)\""
-    local gcode_header="$___X_CMD_GCODE_TMP/.____x_cmd_gcode_curl_header"
-    local ___X_CMD_GCODE_SHOW_HTTP_CODE=1
+    local _api_url="$2"
     shift 2
-    local req
+    local ___X_CMD_API_GL_HEADER="-s -H \"Content-Type: application/json\" -D \"$___X_CMD_GCODE_TMP/.____x_cmd_gcode_curl_header\""
+
+    local _curl_host_tmp=""
+    local ___X_CMD_API_GL_TOKEN=""
+    ___x_cmd_gcode_config___var  ___X_CMD_API_GL_TOKEN=token _curl_host_tmp=host 2>/dev/null
+    local ___X_CMD_API_GL_HOST="${___X_CMD_API_GODE_HOST:-"$_curl_host_tmp"}"
+
+    local ___X_CMD_GCODE_SHOW_HTTP_CODE=1
     case "$op" in
         get)
-            gcode:debug   "x curl -D  $gcode_header   -X GET -s -H  $_content_type  -H  $_authorization  $(eval "printf '%s ' $(x curl gencode $(___x_cmd_gcode_curl___use_query_data "$@"))")  $_curl_url"
             if [ -n "$NO_CACHE" ]; then
-                eval       x curl -D "$gcode_header"  -X GET -s -H "$_content_type" -H "$_authorization" $(eval "printf '%s ' $(x curl gencode $(___x_cmd_gcode_curl___use_query_data "$@"))") "$_curl_url"
+                ___x_cmd_api_gl get "$_api_url" $(eval "printf '%s ' $(x curl gencode $(___x_cmd_gcode_curl___use_query_data "$@"))")
             else
-                x ccmd 10s --         eval x curl -D "$gcode_header"  -X GET -s -H "$_content_type" -H "$_authorization" $(eval "printf '%s ' $(x curl gencode $(___x_cmd_gcode_curl___use_query_data "$@"))") "$_curl_url"
+                x ccmd 10s --           eval "___X_CMD_API_GL_HOST=$___X_CMD_API_GL_HOST ___X_CMD_API_GL_TOKEN=$___X_CMD_API_GL_TOKEN ___x_cmd_api_gl get $_api_url $(eval "printf '%s ' $(x curl gencode $(___x_cmd_gcode_curl___use_query_data "$@"))")"
             fi
-            ___x_cmd_gcode_http_error eval x curl -D "$gcode_header"  -X GET -s -H "$_content_type" -H "$_authorization" $(eval "printf '%s ' $(x curl gencode $(___x_cmd_gcode_curl___use_query_data "$@"))") "$_curl_url"
-            return
+            ___x_cmd_gcode_http_error   eval "___X_CMD_API_GL_HOST=$___X_CMD_API_GL_HOST ___X_CMD_API_GL_TOKEN=$___X_CMD_API_GL_TOKEN ___x_cmd_api_gl get $_api_url $(eval "printf '%s ' $(x curl gencode $(___x_cmd_gcode_curl___use_query_data "$@"))")"
+            ;;
+        post|put|patch|del)
+            ___x_cmd_api_gl "$op" "$_api_url" "$(x curl gencode "$@")"
+            ___x_cmd_gcode_http_error
             ;;
         upload)
-            local __file_path="${1?:"Please provide upload filepath"}"; shift;
+            [ -n "$1" ] || M='Please provide upload filepath' arg:ret:64
+            local __file_path="$1";  shift;
             [ -f "$__file_path" ] || {
                 gcode:error "Upload Failure: Not found target file. Please check file exist: $__file_path"
                 return 1
             }
-            gcode:debug "x curl --progress-bar -D  $gcode_header   -X  ${___X_CMD_GCODE_UPLOAD_REQ_METHOD:-"POST"}  -H  $_authorization  --form  file=@${__file_path}    $(x curl gencode "$@")   $_curl_url"
-            eval         x curl --progress-bar -D "$gcode_header"  -X "${___X_CMD_GCODE_UPLOAD_REQ_METHOD:-"POST"}" -H "$_authorization" --form  file=@"${__file_path}" "$(x curl gencode "$@")" "$_curl_url"
-            ___x_cmd_gcode_http_error; return
+            ___X_CMD_API_GL_HEADER="-L -# -D \"$___X_CMD_GCODE_TMP/.____x_cmd_gcode_curl_header\""
+            ___x_cmd_api_gl "${___X_CMD_GCODE_UPLOAD_REQ_METHOD:-"post"}" "$_api_url" --form file=@\""${__file_path}"\" "$(x curl gencode "$@")"
+            ___x_cmd_gcode_http_error
         ;;
-        post)           req="POST"      ;;
-        put)            req="PUT"       ;;
-        patch)          req="PATCH"     ;;
-        delete)         req="DELETE"    ;;
     esac
-    gcode:debug "x curl -D  $gcode_header  -X  $req  -s -H  $_content_type  -H  $_authorization   $(x curl gencode "$@")   $_curl_url"
-    eval         x curl -D "$gcode_header" -X "$req" -s -H "$_content_type" -H "$_authorization" "$(x curl gencode "$@")" "$_curl_url"
-    ___x_cmd_gcode_http_error
-}
-
-___x_cmd_gcode_http_error(){
-    local http_resp_code
-    http_resp_code=$(___x_cmd_gcode_resp_code)
-    if [ -n "$http_resp_code" ] && [ "$http_resp_code" -ge 100 ] && [ "$http_resp_code" -le 303 ]; then
-        return 0
-    else
-        [ $# -eq 0 ] || {
-            gcode:debug "---! Cache Clear !---"
-            x ccmd invalidate "$@" 1>/dev/null 2>&1
-        }
-        [ -z "$___X_CMD_GCODE_SHOW_HTTP_CODE" ] || {
-            gcode:error "HTTP Code is $http_resp_code"
-            if command -v unset 1>/dev/null; then
-                unset ___X_CMD_GCODE_SHOW_HTTP_CODE
-            fi
-        }
-        return 1
-    fi
 }
 
 # shellcheck disable=SC2154
@@ -99,9 +80,35 @@ ___x_cmd_gcode_curl___use_query_data(){
     done
 }
 
+___x_cmd_gcode_http_error(){
+    local http_resp_code=""
+    http_resp_code=$(___x_cmd_gcode_resp_code)
+    if [ -n "$http_resp_code" ] && [ "$http_resp_code" -ge 100 ] && [ "$http_resp_code" -le 303 ]; then
+        return 0
+    else
+        [ $# -eq 0 ] || {
+            gcode:debug "Cache Clear"
+            x ccmd invalidate "$@" 1>/dev/null 2>&1
+        }
+        [ -z "$___X_CMD_GCODE_SHOW_HTTP_CODE" ] || {
+            gcode:error "HTTP Code is $http_resp_code"
+            if command -v unset 1>/dev/null; then
+                unset ___X_CMD_GCODE_SHOW_HTTP_CODE
+            fi
+        }
+        return 1
+    fi
+}
+
+___x_cmd_gcode____printf_error(){
+    if ! ___x_cmd_is_interative_tty || [ ! -t 2 ] || [ -n "$NO_COLOR" ]; then
+        printf "  - ErrorMsg: %s\n" "$1" >&2
+    else
+        printf "  \033[31m-\033[0m \033[1mErrorMsg: \033[31m%s\033[0m\n" "$1" >&2
+    fi
+}
 ___x_cmd_gcode____handle_resp(){
-    [ -z "$gcode_resp_body" ] || printf "%s" "$gcode_resp_body"
-    [ -z "$gcode_resp_err" ]  || printf "  \033[31m-\033[0m \033[1mErrorMsg: \033[31m%s\033[0m\n" "$gcode_resp_err" >&2
+    [ -z "$gcode_resp_err" ] || ___x_cmd_gcode____printf_error "$gcode_resp_err"
 }
 # EndSection
 
@@ -192,33 +199,57 @@ _____x_cmd_gcode_next_url(){
 # EndSection
 
 # Section: Parameter Utilities
-alias ___x_cmd_gcode_param_init_owner_project='
-    local owner_project=""
+alias ___x_cmd_gcode_param_init_owner_repo='
+    local owner_repo=""
     ___x_cmd_gcode_param_normalize_repo  || return
 '
 
 # shellcheck disable=SC2154,SC2034
 ___x_cmd_gcode_param_normalize_repo(){
-    local op="$project"
-    [ -z "$op" ] && op="$1"
+    local op="$repo"
+    [ -n "$op" ] || op="$1"
     case "$op" in
-    */*)
-        owner_project="$(printf "%s" "$op")"
-        ;;
-    "")
-        owner_project="$(_____x_cmd_git_repo)"
-        ;;
-    *)
-        ___x_cmd_gcode_current_owner 1>/dev/null
-        if [ -z "$___X_CMD_GCODE_DEFAULT_OWNER" ]; then
-            gcode:error "No owner provided. Default owner not set."
-            gcode:warn "Check your current token setting.$(_____x_cmd_gcode_help__token_setting)"
+        .id=*/*)
+            gcode:error "No support .id=<owner_id>/<repo_name>. Please use .id=<repo_id>"
             return 1
-        fi
-        owner_project="$(printf "%s" "$___X_CMD_GCODE_DEFAULT_OWNER/$op")"
-        ;;
+            ;;
+        .id=*)
+            owner_repo="${op#*'.id='}"
+            return 0
+            ;;
+        */*)
+            owner_repo="$op"
+            ;;
+        "")
+            if [ -n "$___X_CMD_GCODE_CURRENT_repo" ]; then
+                if [ "${___X_CMD_GCODE_CURRENT_repo##*/}" != "${___X_CMD_GCODE_CURRENT_repo}" ]; then
+                    owner_repo="$___X_CMD_GCODE_CURRENT_repo"
+                elif [ -n "$___X_CMD_GCODE_CURRENT_owner" ]; then
+                    owner_repo="${___X_CMD_GCODE_CURRENT_owner}/${___X_CMD_GCODE_CURRENT_repo}"
+                else
+                    if ! owner_repo="$(___x_cmd_gcode_config_get owner)/${___X_CMD_GCODE_CURRENT_repo}"; then
+                        gcode:error "No owner provided. Default owner not set."
+                        gcode:warn -h "$(x str ml wrap "$(_____x_cmd_gcode_help__token_setting)" '    ')" -m "Can retry setup token to update owner.${___X_CMD_UNSEENCHAR_NEWLINE}Or check your current token setting."
+                        return 1
+                    fi
+                fi
+            else
+                owner_repo="$(_____x_cmd_git_repo)"
+            fi
+            ;;
+        *)
+            if [ -z "$___X_CMD_GCODE_CURRENT_owner" ]; then
+                local ___X_CMD_GCODE_CURRENT_owner=""
+                if ! ___X_CMD_GCODE_CURRENT_owner="$(___x_cmd_gcode_config_get owner)"; then
+                    gcode:error "No owner provided. Default owner not set."
+                    gcode:warn -h "$(x str ml wrap "$(_____x_cmd_gcode_help__token_setting)" '    ')" -m "Can retry setup token to update owner.${___X_CMD_UNSEENCHAR_NEWLINE}Or check your current token setting."
+                    return 1
+                fi
+            fi
+            owner_repo="${___X_CMD_GCODE_CURRENT_owner}/${op}"
+            ;;
     esac
-    owner_project="$(printf "%s" "$owner_project" | sed s:'/':'%2F':g)"
+    owner_repo="$(printf "%s" "$owner_repo" | ___x_cmd_gcode___url_path_encode)"
 }
 
 _____x_cmd_git_repo(){
@@ -231,8 +262,8 @@ _____x_cmd_git_repo(){
 }
 # EndSection
 
-# Section: Resolve gitcode member access
-_____x_cmd_gcode_member_util(){
+# Section: gitcode utils
+___x_cmd_gcode___transform_member_access(){
     case $access_level in
         owner)
             access_level=50;;
@@ -245,5 +276,19 @@ _____x_cmd_gcode_member_util(){
         guest)
             access_level=10;;
     esac
+}
+
+# shellcheck disable=2016
+___x_cmd_gcode___url_encode(){
+    [ -n "$1" ] || M='accepts 1 arg(target str), received empty' arg:ret:64
+    printf "%s\n" "$1" |  x cawk  \
+        -f "$___X_CMD_ROOT_MOD/awk/lib/ord.awk" \
+        -f "$___X_CMD_ROOT_MOD/awk/lib/url.awk" \
+        -f "$___X_CMD_ROOT_MOD/awk/lib/sh.awk"  \
+        '{ print urlencode( $0 ) }'
+}
+
+___x_cmd_gcode___url_path_encode(){
+    sed s:'/':'%2F':g
 }
 # EndSection
diff --git a/mod/pkg/lib/mutate/download b/mod/pkg/lib/mutate/download
--- a/mod/pkg/lib/mutate/download
+++ b/mod/pkg/lib/mutate/download
@@ -33,6 +33,7 @@ ___x_cmd_pkg_download(){
     local file_suffix md5 sha1 sha256 sha512
     ___x_cmd_pkg___attr "$name" "$version" "$osarch" "md5,sha1,sha256,sha512,file_suffix"
     local url
+    local head
 
     ___x_cmd_pkg___attr "$name" "$version" "$osarch" "unpack_way"
     if [ "$unpack_way" = "non_unpack" ]; then
@@ -59,9 +60,16 @@ ___x_cmd_pkg_download(){
         # ___x_cmd_httpget "$url" "$ball" || {
         pkg:info "Download $name $version from $url to $ball"
         # TODO: x curl
-        if ! curl --progress-bar --location --retry-max-time 10 --retry 0 "$url" --output "$ball" ; then
-            pkg:warn "Fail to download from $url"
-            x rmrf $ball
+        head=$(curl -I "$url" | awk 'NR==1{ print $2}' )
+        if [ "$head" -eq "200" ] || [ "$head" -eq "304" ] || [ "$head" -eq "302" ] || [ "$head" -eq "301" ]; then
+            if ! curl --progress-bar --location --retry-max-time 10 --retry 0 "$url" --output "$ball" ; then
+                pkg:warn "Fail to download from $url"
+                x rmrf "$ball"
+                return 1
+                continue
+            fi
+        else
+            pkg:error "resource invalid: $url "
             return 1
             continue
         fi
diff --git a/mod/tldr/lib/cat b/mod/tldr/lib/cat
--- a/mod/tldr/lib/cat
+++ b/mod/tldr/lib/cat
@@ -3,32 +3,43 @@
 # Section: cat
 ___x_cmd_tldr_cat(){
     local pages="pages"
-    [ "$______X_CMD_TLDR_LANG_PREFERED" = "en" ] || pages="pages.$______X_CMD_TLDR_LANG_PREFERED"
+    [ "$___X_CMD_TLDR_LANG_PREFERED" = "en" ] || pages="pages.$___X_CMD_TLDR_LANG_PREFERED"
     arg:init tldr 'x tldr -h'
     [ -n "$1" ] || M="Please provide the correct candidate value" arg:ret:64
 
-    local cand;     cand="$( ___x_cmd_tldr_exact "$1" "$pages" )"
-    local number;   number="$(printf "%s" "$cand" | awk 'END{ print NR; }')"
-    case $number in
-        0)
-            [ "$______X_CMD_TLDR_LANG_PREFERED" = "en" ] || {
-                ______X_CMD_TLDR_LANG_PREFERED="en" ___x_cmd_tldr_cat "$@"
-                return
-            }
+    local IFS="$___X_CMD_UNSEENCHAR_NEWLINE"
+    local cand;     cand="$( ___x_cmd_tldr_exact "${1%.md*}.md" "$pages" )"
+    if [ -z "$cand" ]; then
+        [ "$___X_CMD_TLDR_LANG_PREFERED" = "en" ] || {
+            ___X_CMD_TLDR_LANG_PREFERED="en" ___x_cmd_tldr_cat "$@"
+            return
+        }
 
-            tldr:error "Not found $1";
-            ___x_cmd_tldr_list "$@" >&2
-            return 1 ;;
-        1)  ___x_cmd_tldr_cat_awk "$(___x_cmd___tldr_getfile "$cand")" ;;
-        *) ___x_cmd_tldr_app_ "$cand" ;;
-    esac
+        local IFS="$___X_CMD_UNSEENCHAR_NEWLINE"
+        local ___X_CMD_TLDR_APP_DATA=; ___X_CMD_TLDR_APP_DATA="$( ___x_cmd_tldr_exact "$1" pages )"
+        [ -n "$___X_CMD_TLDR_APP_DATA" ] || {
+            tldr:error "Not found $1"
+            return 1
+        }
+
+        tldr:warn "Here are some similar commands of $1"
+        ___x_cmd_tldr_app_
+
+    elif [ "$cand" = "${cand#*"${___X_CMD_UNSEENCHAR_NEWLINE}"}" ]; then
+        local x_; ___x_cmd___tldr_getfile_ "$cand"
+        [ -f "$x_" ] || return
+        ___x_cmd_tldr_cat_awk "$x_"
+    else
+        ___x_cmd_tldr_app_ "$cand"
+    fi
 }
 
+
 ___x_cmd_tldr_cat_awk(){
-    local filepath="$1"
     arg:init tldr 'x tldr -h'
     arg:1:nonempty
 
+    local filepath="$1"
     tldr:debug "filepath=$filepath"
     x tty update
     command awk \
diff --git a/mod/tldr/lib/download b/mod/tldr/lib/download
--- a/mod/tldr/lib/download
+++ b/mod/tldr/lib/download
@@ -2,14 +2,24 @@
 
 # Section: current and download
 
-___x_cmd_tldr_current_or_update(){
-    local version
-    version="$(___x_cmd_tldr_version)" && printf "%s\n" "$version" && return 0
-    if ! ___x_cmd_tldr_update; then
-        tldr:error "Fail to show version for tldr pages unexisted"
+___x_cmd_tldr_current_or_update_(){
+    x_tldr_version="${___X_CMD_TLDR_VERSION:-"$(___x_cmd_tldr_version)"}"
+    if [ -n "$x_tldr_version" ]; then
+        ___X_CMD_TLDR_VERSION="$x_tldr_version"
+    elif ___x_cmd_tldr_update; then
+        x_tldr_version="$___X_CMD_TLDR_VERSION"
+    else
+        ___X_CMD_TLDR_VERSION=
+        tldr:error "Fail to show version for tldr pages"
         return 1
     fi
-    ___x_cmd_tldr_version
+}
+
+___x_cmd_tldr_current_or_update(){
+    local x_tldr_version
+    ___x_cmd_tldr_current_or_update_
+    [ -n "$x_tldr_version" ] || return 1
+    printf "%s\n" "$x_tldr_version"
 }
 
 ___x_cmd_tldr_version___from_yml(){
@@ -25,25 +35,19 @@ ___x_cmd_tldr_version(){
     local index="$___X_CMD_TLDR_TMP_DATA/index.yml"
     [ -f "$index" ] || return 1
 
-    ! ___x_cmd_tldr_version___from_yml "$index" || return 0
-    tldr:error -m "Latest version in index.yml is NOT valid
-version: $(awk '{print $2; exit(1); }' <"$index")"
-    return 1
+    ___x_cmd_tldr_version___from_yml "$index" || {
+        tldr:error --version "$(awk '{print $2; exit(1); }' <"$index")" "Latest version in index.yml is invalid"
+        return 1
+    }
 }
 
-___x_cmd_tldr_update()(
-    if ! ___x_cmd___tldr_download index.yml "$___X_CMD_TLDR_TMP_DATA/index.yml" -; then
-        tldr:warn "Fail to update index.yml"
-        return 1
-    fi
+___x_cmd_tldr_update(){
+    ___x_cmd___tldr_download index.yml "$___X_CMD_TLDR_TMP_DATA/index.yml" - || return
+    ___X_CMD_TLDR_VERSION="$(___x_cmd_tldr_version)"
+    ___x_cmd___tldr_download_pages "$___X_CMD_TLDR_VERSION" pages
+}
 
-    local version
-    version="$(___x_cmd_tldr_version)"
-
-    ___x_cmd___tldr_download_pages "$version" pages
-)
-
-___x_cmd___tldr_download_pages()(
+___x_cmd___tldr_download_pages(){
     arg:init tldr
     [ -n "$1" ] || M="Please provide the tldr version" arg:ret:64
     [ -n "$2" ] || M="Please provide the tldr pages" arg:ret:64
@@ -54,22 +58,23 @@ ___x_cmd___tldr_download_pages()(
     local tgz_path="$___X_CMD_TLDR_TMP_CACHE/$version/$page_lang.tgz"
     x mkdirp "$data_path"
 
-    if ! ___x_cmd___tldr_download "$version/$page_lang.tgz" "$tgz_path" "0"; then
-        tldr:error "Fail to update $page_lang"
+    ___x_cmd___tldr_download "$version/$page_lang.tgz" "$tgz_path" "0" || {
         x rmrf "$data_path"
         return 1
-    fi
-    if cd "$data_path" && tar xvf "$tgz_path" 2>/dev/null 1>&2; then
-        tldr:info "Version already UPDATED to $version"
-    fi
-)
+    }
+    ! x uz "$tgz_path" "$data_path" || tldr:info "Version already UPDATED to $version"
+}
 
 ___x_cmd___tldr_download(){
     arg:1:nonempty
     local src="$1"
     local dst="${2:-$1}"
     local expiration="${3:-"1"}"
-    ___x_cmd_httpget_gitx x-cmd tldr main "dist/$src" "$dst" "$expiration"
+    tldr:info "Download tldr $src from x-cmd/tldr"
+    ___x_cmd_httpget_gitx x-cmd tldr main "dist/$src" "$dst" "$expiration" || {
+        tldr:error "Fail to download $src from x-cmd/tldr"
+        return 1
+    }
 }
 
 ## EndSection
