...

diff --git a/mod/pkg/lib/main b/mod/pkg/lib/main
--- a/mod/pkg/lib/main
+++ b/mod/pkg/lib/main
@@ -25,15 +25,15 @@
 
 ___x_cmd_pkg___which_p7zip()(
     ___x_cmd_mkdirp "$___X_CMD_PKG_RAW_PATH"
-    local file_path="$___X_CMD_PKG_BASE_PATH/$___X_CMD_PKG_VERSION.tar.xz"
+    local file_path="$___X_CMD_PKG_BASE_PATH/$___X_CMD_PKG_VERSION.tar.gz"
     local file_hash_path="$___X_CMD_PKG_BASE_PATH/${___X_CMD_PKG_VERSION}_hash.txt"
     ___x_cmd_httpget_gitx x-cmd pkg main "dist/${___X_CMD_PKG_VERSION}_hash.txt" "$file_hash_path" "${1:-86400}" || {
         pkg:warn "Please check your network status; Or use 'x websrc set cn' and open a new session to run 'x pkg update'"
         return 1
     }
-    if ! ___x_cmd_httpget_gitx x-cmd pkg main "dist/$___X_CMD_PKG_VERSION.tar.xz" "$file_path" "${1:-86400}"; then # 1-day
+    if ! ___x_cmd_httpget_gitx x-cmd pkg main "dist/$___X_CMD_PKG_VERSION.tar.gz" "$file_path" "${1:-86400}"; then # 1-day
         if [ ! -f "$file_path" ]; then
-            pkg:error "Unaviable $___X_CMD_PKG_VERSION.tar.xz. Unable to fetch $___X_CMD_PKG_VERSION.tar.xz."
+            pkg:error "Unaviable $___X_CMD_PKG_VERSION.tar.gz. Unable to fetch $___X_CMD_PKG_VERSION.tar.gz."
             return 1
         fi
         local hash_value
@@ -48,8 +48,8 @@ ___x_cmd_pkg___which_p7zip()(
 
     if [ "$___X_CMD_HTTPGET_AGE" = 0 ]; then
         ___x_cmd_mkdirp "$___X_CMD_PKG_RAW_PATH"
-        pkg:debug "Deflate the $___X_CMD_PKG_VERSION.tar.xz"
-        if ! ( x cd "${file_path%/*}" && x cp "$___X_CMD_PKG_VERSION.tar.xz" raw/"$___X_CMD_PKG_VERSION.tar.xz" && x cd raw && x uz "$___X_CMD_PKG_VERSION.tar.xz" 1>/dev/null && x rmrf "$___X_CMD_PKG_VERSION.tar.xz" ); then
+        pkg:debug "Deflate the $___X_CMD_PKG_VERSION.tar.gz"
+        if ! ( x cd "${file_path%/*}" && x cp "$___X_CMD_PKG_VERSION.tar.gz" raw/"$___X_CMD_PKG_VERSION.tar.gz" && x cd raw && x uz "$___X_CMD_PKG_VERSION.tar.gz" 1>/dev/null && x rmrf "$___X_CMD_PKG_VERSION.tar.gz" ); then
             pkg:error "Deflation failure."
             x rmrf "$file_path"
         fi
@@ -66,9 +66,9 @@ ___x_cmd_pkg_update(){
             ;;
     esac
     local file_hash_path="$___X_CMD_PKG_BASE_PATH/${___X_CMD_PKG_VERSION}_hash.txt"
-    x rmrf "$___X_CMD_PKG_BASE_PATH/$___X_CMD_PKG_VERSION.tar.xz" && x rmrf "$___X_CMD_PKG_RAW_PATH" && x rmrf "$file_hash_path"
+    x rmrf "$___X_CMD_PKG_BASE_PATH/$___X_CMD_PKG_VERSION.tar.gz" && x rmrf "$___X_CMD_PKG_RAW_PATH" && x rmrf "$file_hash_path"
     ___x_cmd_pkg___which_p7zip - || return # Force Update
-    pkg:info "Update the $___X_CMD_PKG_VERSION.tar.xz"
+    pkg:info "Update the $___X_CMD_PKG_VERSION.tar.gz"
 }
 
 ___x_cmd_pkg_help(){
