...

diff --git a/mod/pkg/lib/main b/mod/pkg/lib/main
--- a/mod/pkg/lib/main
+++ b/mod/pkg/lib/main
@@ -1,5 +1,95 @@
 # shellcheck    shell=dash disable=SC2034,SC1090
 
+x log init pkg
+
+xrc:mod:lib     pkg \
+    util                sphere/_index\
+    info/ls             info/ll
+
+___x_cmd_lazysrc    "$___X_CMD_ROOT_MOD/pkg/lib/inner/_ls_urls"     ___x_cmd_pkg__ls_urls   ___x_cmd_pkg__head_test_urls
+___x_cmd_lazysrc    "$___X_CMD_ROOT_MOD/pkg/lib/info/which"         ___x_cmd_pkg_which      ___x_cmd_pkg_which_
+___x_cmd_lazyfun    "$___X_CMD_ROOT_MOD/pkg/lib/inner/_smoke"       ___x_cmd_pkg__smoke     \
+                    "$___X_CMD_ROOT_MOD/pkg/lib/info/info"          ___x_cmd_pkg_info       \
+                    "$___X_CMD_ROOT_MOD/pkg/lib/mutate/download"    ___x_cmd_pkg_download   \
+                    "$___X_CMD_ROOT_MOD/pkg/lib/websrc"             ___x_cmd_pkg_websrc
+
+
+if ___x_cmd_is_suitable_advise_env; then
+    ___x_cmd_lazyfun    "$___X_CMD_ROOT_MOD/pkg/lib/advise"         ___x_cmd_pkg___advise
+fi
+
+___x_cmd_pkg___main(){
+    # ___x_cmd_pkg_update___inner || return
+    [ "$#" -gt 0 ] || set -- --help
+    local op="$1"; shift
+    case "$op" in
+        ls)                     ___x_cmd_pkg_ls                     "$@" ;;      # add filter, remote, installed, ...
+        ll)                     ___x_cmd_pkg_ll                     "$@" ;;
+        info)                   ___x_cmd_pkg_info                   "$@" ;;
+        which)                  ___x_cmd_pkg_which                  "$@" ;;
+        default_version)        ___x_cmd_pkg_default_version        "$@" ;;
+
+        # x pkg download             node=v12
+        # download)               ___x_cmd_pkg_download               "$@" ;;
+        # populate)               ___x_cmd_pkg_sphere_populate        "$@" ;;
+        # x pkg activate/deactivate  node=v12
+        # addpath)                ___x_cmd_pkg_sphere_path add        "$@" ;;
+        # rmpath)                 ___x_cmd_pkg_sphere_path rm         "$@" ;;
+        # unlink)                 ___x_cmd_pkg_sphere_link rm         "$@" ;;
+
+        sphere)                 ___x_cmd_pkg_sphere                 "$@" ;;
+        add)                    ___x_cmd_pkg_sphere_add             "$@" ;;
+        sociality)              ___x_cmd_pkg_sphere_sociality       "$@" ;;
+        path)                   ___x_cmd_pkg_sphere_path            "$@" ;;
+        link)                   ___x_cmd_pkg_sphere_link            "$@" ;;
+        try)                    ___x_cmd_pkg_sphere_try             "$@" ;;
+        use)                    ___x_cmd_pkg_sphere_use             "$@" ;;
+        boot)                   ___x_cmd_pkg_sphere_boot            "$@" ;;
+        unboot)                 ___x_cmd_pkg_sphere_unboot          "$@" ;;
+        xbin)                   ___x_cmd_pkg_sphere_xbin            "$@" ;;
+        gc)                     ___x_cmd_pkg_sphere_gc              "$@" ;;
+
+        websrc)                 ___x_cmd_pkg_websrc                 "$@" ;;
+        update)                 ___x_cmd_pkg_update                 "$@" ;;
+
+        _smoke)                 ___x_cmd_pkg__smoke                 "$@" ;;
+        _ls_urls)               ___x_cmd_pkg__ls_urls               "$@" ;;
+        _head_test_urls)        ___x_cmd_pkg__head_test_urls        "$@" ;;
+
+        --help|-h)              x help -m pkg;                      return ;;
+
+        *)                      pkg:error "Not found command - 'x pkg $op'"; return 1
+    esac
+}
+
+___x_cmd_pkg___init(){
+    ___X_CMD_PKG_VERSION="v0.0.8"
+    ___X_CMD_PKG_DOWNLOAD_SOURCE=npm
+    ___X_CMD_PKG_SHARED="$___X_CMD_ROOT_SHARED/pkg"                # cache
+
+    ___X_CMD_PKG_ROOT_PATH="$___X_CMD_ROOT_DATA/pkg"
+    ___X_CMD_PKG_ROOT_SPHERE="$___X_CMD_PKG_ROOT_PATH/sphere"
+    ___X_CMD_PKG_CACHE_PATH="$___X_CMD_PKG_ROOT_PATH/cache"        # cache
+    ___X_CMD_PKG_DOWNLOAD_PATH="$___X_CMD_PKG_ROOT_PATH/download"  # cache
+
+    ___X_CMD_METADATA_FOLDER="$___X_CMD_PKG_ROOT_PATH/metadata/$___X_CMD_PKG_VERSION"
+    ___X_CMD_PKG_METADATA_PATH="$___X_CMD_METADATA_FOLDER/pkg"
+    ___X_CMD_PKG_FP_UPDATED_DONE="$___X_CMD_METADATA_FOLDER/.x-cmd/timefile.$___X_CMD_PKG_VERSION"
+
+    x mkdirp "$___X_CMD_PKG_SHARED" "$___X_CMD_PKG_CACHE_PATH" "$___X_CMD_PKG_DOWNLOAD_PATH"
+
+    ___x_cmd_pkg_sphere_path --activate --sphere X --sphereroot "$___X_CMD_PKG_ROOT_SPHERE"
+}
+
+___x_cmd_pkg_update(){
+    local X_help_cmd='x help -m pkg update'; help:arg:parse
+    ___x_cmd_pkg_update___force || {
+        pkg:error "Update the $___X_CMD_PKG_VERSION.tar.gz failed"
+        return 1 # Force Update
+    }
+    pkg:info "Update the $___X_CMD_PKG_VERSION.tar.gz success"
+}
+
 ___x_cmd_pkg_update___inner()(
     local file_path="$___X_CMD_PKG_CACHE_PATH/${___X_CMD_PKG_VERSION}.tar.gz"
     local file_hash_path="$___X_CMD_PKG_CACHE_PATH/${___X_CMD_PKG_VERSION}_hash.txt"
@@ -77,16 +167,9 @@ ___x_cmd_pkg_update___check_inner(){
     [ -f "$___X_CMD_PKG_FP_UPDATED_DONE" ] || ___x_cmd_pkg_update___inner
 }
 
-___x_cmd_pkg_update(){
-    local X_help_cmd='x help -m pkg update'; help:arg:parse
-    ___x_cmd_pkg_update___force || {
-        pkg:error "Update the $___X_CMD_PKG_VERSION.tar.gz failed"
-        return 1 # Force Update
-    }
-    pkg:info "Update the $___X_CMD_PKG_VERSION.tar.gz success"
-}
-
 ___x_cmd_pkg_update___force(){
     [ ! -f "$___X_CMD_PKG_FP_UPDATED_DONE" ] || x rmrf "$___X_CMD_PKG_FP_UPDATED_DONE"
     ___x_cmd_pkg_update___check
 }
+
+___x_cmd_pkg___init
