...

diff --git a/mod/pkg/lib/main b/mod/pkg/lib/main
--- a/mod/pkg/lib/main
+++ b/mod/pkg/lib/main
@@ -1,46 +1,52 @@
 # shellcheck    shell=dash
 
-
-# # Rely on ll or ls
-# # Control the lsversion awk for better showing
-# ___x_cmd_pkg_version(){
-#     ___x_cmd_pkg___all_info "$@" | awk \
-#         -f "$___X_CMD_ROOT_MOD/awk/lib/core.awk" \
-#         -f "$___X_CMD_ROOT_MOD/awk/lib/jqparse.awk" \
-#         -f "$___X_CMD_ROOT_MOD/pkg/lib/awk/util.awk" \
-#         -f "$___X_CMD_ROOT_MOD/awk/pkg.lsversion.awk"
-# }
-
-# Rely on ll or ls
-# Control the lsversion awk for better showing
-# ___x_cmd_pkg_version(){
-#     local pkg_name="${1:?Provide pkg name}"
-#     local osarch="${2:?osarch as filter}"
-#     ___x_cmd_pkg___all_info "${pkg_name}" | awk \
-#         -f "$___X_CMD_ROOT_MOD/awk/lib/core.awk" \
-#         -f "$___X_CMD_ROOT_MOD/awk/lib/jqparse.awk" \
-#         -f "awk/util.awk" \
-#         -f "awk/pkg.lsversion.awk"
-# }
-
 ___x_cmd_pkg___which_p7zip()(
     local file_path="$___X_CMD_PKG_BASE_PATH/$___X_CMD_PKG_VERSION.tar.gz"
     local file_hash_path="$___X_CMD_PKG_BASE_PATH/${___X_CMD_PKG_VERSION}_hash.txt"
     local tmp_file_path="$___X_CMD_PKG_SHARED/$___X_CMD_PKG_VERSION.tar.gz"
     local tmp_file_hash_path="$___X_CMD_PKG_SHARED/${___X_CMD_PKG_VERSION}_hash.txt"
-    ___x_cmd_httpget_gitx x-cmd pkg main "dist/${___X_CMD_PKG_VERSION}_hash.txt" "$tmp_file_hash_path" "-" || {
+    local x_url_tar=
+    local x_url_hash=
+
+    if [ -n "$___X_CMD_PKG_DEV_MOD" ]; then
+        pkg:warn "update inner release ${___X_CMD_PKG_VERSION}.tar.gz"
+        x_url_tar="https://github.com/x-cmd-pkg/release/raw/main/dist/${___X_CMD_PKG_VERSION}.tar.gz"
+        x_url_hash="https://raw.githubusercontent.com/x-cmd-pkg/release/main/dist/${___X_CMD_PKG_VERSION}_hash.txt"
+    elif [ "$___X_CMD_WEBSRC_REGION" != cn ]; then
+        x_url_tar="https://github.com/x-cmd/pkg/raw/main/dist/${___X_CMD_PKG_VERSION}.tar.gz"
+        x_url_hash="https://raw.githubusercontent.com/x-cmd/pkg/main/dist/${___X_CMD_PKG_VERSION}_hash.txt"
+    else
+        x_url_tar="https://gitcode.net/x-cmd/pkg/-/raw/main/dist/${___X_CMD_PKG_VERSION}.tar.gz"
+        x_url_hash="https://gitcode.net/x-cmd/pkg/-/raw/main/dist/${___X_CMD_PKG_VERSION}_hash.txt"
+    fi
+
+
+    pkg:info --url "$x_url_tar" "Download ${___X_CMD_PKG_VERSION}.tar.gz"
+    x curl -L -sS --speed-time 5 --speed-limit 100 "$x_url_tar" --output "$tmp_file_path" || {
         pkg:warn "Please check your network status; Or use 'x websrc set cn' and open a new session to run 'x pkg update'"
         return 1
     }
-    ___x_cmd_httpget_gitx x-cmd pkg main "dist/$___X_CMD_PKG_VERSION.tar.gz" "$tmp_file_path" || { # 1-day
-        pkg:error "Download $___X_CMD_PKG_VERSION.tar.gz failed"
+
+    pkg:info --url "$x_url_hash" "Download ${___X_CMD_PKG_VERSION}_hash.txt"
+    x curl -L -sS --speed-time 5 --speed-limit 100 "$x_url_hash" --output "$tmp_file_hash_path" || {
+         pkg:error "Download $___X_CMD_PKG_VERSION.tar.gz failed"
         return 1
     }
+
+
+    # ___x_cmd_httpget_gitx x-cmd pkg main "dist/${___X_CMD_PKG_VERSION}_hash.txt" "$tmp_file_hash_path" "-" || {
+    #     pkg:warn "Please check your network status; Or use 'x websrc set cn' and open a new session to run 'x pkg update'"
+    #     return 1
+    # }
+    # ___x_cmd_httpget_gitx x-cmd pkg main "dist/$___X_CMD_PKG_VERSION.tar.gz" "$tmp_file_path" || { # 1-day
+    #     pkg:error "Download $___X_CMD_PKG_VERSION.tar.gz failed"
+    #     return 1
+    # }
 
 
     local hash_value
     local file_hash
-    hash_value="$( < "$tmp_file_hash_path"  ___x_cmd_awk_inner '{print $1}')"
+    hash_value="$( < "$tmp_file_hash_path" LC_ALL="$___X_CMD_AWK_LANGUAGE" ___x_cmd_awk___inner '{print $1}')"
     file_hash="$(x sha512 "$tmp_file_path")"
 
 
@@ -71,7 +77,7 @@ ___x_cmd_pkg_update(){
             M='pkg update' help:ret:0
             ;;
     esac
-    local file_hash_path="$___X_CMD_PKG_BASE_PATH/${___X_CMD_PKG_VERSION}_hash.txt"
+    # local file_hash_path="$___X_CMD_PKG_BASE_PATH/${___X_CMD_PKG_VERSION}_hash.txt"
     # x rmrf "$___X_CMD_PKG_BASE_PATH/$___X_CMD_PKG_VERSION.tar.gz" && x rmrf "$___X_CMD_PKG_METADATA_PATH" && x rmrf "$file_hash_path"
     ___x_cmd_pkg___which_p7zip || {
         pkg:error "Update the $___X_CMD_PKG_VERSION.tar.gz failed"
