...

diff --git a/mod/pkg/lib/util b/mod/pkg/lib/util
--- a/mod/pkg/lib/util
+++ b/mod/pkg/lib/util
@@ -170,6 +170,36 @@ ___x_cmd_pkg_default_version(){
     printf "%s\n" "$x_"
 }
 
+___x_cmd_pkg_default_version_set(){
+    local name="$1";    [ -n "$name" ]  || N=pkg M="Provide a package name" log:ret:64
+    ___x_cmd_pkg___is_support "$name"   || N=pkg M="Not support this package [name=$name]" log:ret:64
+
+    local version="$2";
+    [ -n "$version" ] || {
+        if ! ___x_cmd_is_interactive; then
+            N=pkg M="Provide the package version" log:ret:1
+        else
+            local versionlist;  versionlist="$( ___x_cmd_pkg_ls___all "$name")" || return
+            version="$( printf "%s\n" "$versionlist" | ___x_cmd pick --ask "Select default version" )"
+            [ -n "$version" ] || N=pkg M="Not found the package version" log:ret:1
+        fi
+    }
+
+    ___x_cmd_pkg___is_support_version "$name" "$version" || {
+        pkg:error "The current package [name=$name] does not support this [version=$version]"
+        return 1
+    }
+
+    local osarch="$3";  [ -n "$osarch" ] || { ___x_cmd_pkg_osarch_ || return 1; osarch="$___X_CMD_PKG_OSARCH"; } || N=pkg M="Not found osarch" log:ret:1
+
+    pkg:info "Set package name[$name] to default version[$version]"
+    local deffp="$___X_CMD_ROOT_TMP/pkg/custom_default_version/$osarch/$name"
+    ___x_cmd ensurefp "$deffp"
+    printf "%s\n" "$version" > "$deffp"
+
+    printf "%s\n" "" > "$___X_CMD_PKG_FP_UPDATED_DONE"
+}
+
 ___x_cmd_pkg_default_version_(){
     local X_help_cmd='x help -m pkg default_version'; help:arg:parse
     local name="$1";    [ -n "$name" ] || N=pkg M="Provide a package name" log:ret:1
@@ -189,8 +219,20 @@ ___x_cmd_pkg_default_version_(){
 
 ___x_cmd_pkg_default_version___inner(){
     local name="$1";    local osarch="$2";  local envfp="$3"
-
     ___x_cmd ensurefp "$envfp"
+
+    local deffp="$___X_CMD_ROOT_TMP/pkg/custom_default_version/$osarch/$name"
+    [ ! -f "$deffp" ] || {
+        local version; version="$( ___x_cmd_cmds_cat "$deffp" )"
+        pkg:debug "Get package name[$name] custom default version[$version]"
+        if ___x_cmd_pkg___is_support_version "$name" "$version"; then
+            printf "%s\n" "x_='$version'" > "$envfp"
+            return
+        else
+            pkg:warn "The current package [name$name] does not support custom default [version=$version]"
+        fi
+    }
+
     local datalist; datalist="$( ___x_cmd_pkg___all_info --non-version "$name" "" "$osarch" )" || return
     printf "%s\n\n" "$datalist" | LC_ALL="$___X_CMD_AWK_LANGUAGE" ___x_cmd_cmds_awk \
         -f "$___X_CMD_ROOT_MOD/awk/lib/core.awk" \
@@ -224,6 +266,30 @@ ___x_cmd_pkg___is_support(){
     return 1
 }
 
+___x_cmd_pkg___is_support_version(){
+    local name="$1";        [ -n "$name" ] || N=pkg M="Provide a package name" log:ret:64
+    local version="$2";     [ -n "$version" ] || N=pkg M="Provide the package version" log:ret:64
+    local jsonfp
+
+    case "$name" in
+        */*)    jsonfp="$___X_CMD_PKG_METADATA_PATH/$name/version.tt.json" ;;
+        *)      jsonfp="$(___x_cmd_cmds find "$___X_CMD_PKG_METADATA_PATH"/*/"$name/version.tt.json")" 2>/dev/null ;;
+    esac
+
+    [ -f "$jsonfp" ] || {
+        pkg:error "Not found version.tt.json of [pkg=$name]"
+        return 1
+    }
+
+    local l=""
+    ___x_cmd_pkg_ls___all_version "$jsonfp" | {
+        while read -r l; do
+            [ "$l" = "$version" ] || continue
+            return 0
+        done
+        return 1
+    }
+}
 
 ___x_cmd_pkg___recorrect_name(){
     local name="$1"
