...

diff --git a/mod/python/lib/load b/mod/python/lib/load
--- a/mod/python/lib/load
+++ b/mod/python/lib/load
@@ -18,7 +18,7 @@ ___x_cmd_python_load(){
     fi
 
     ___x_cmd_python_load_checkenv || {
-        x:debug "Cannot find python installed in this current environment"
+        python:debug "Cannot find python installed in this current environment"
         ___x_cmd_python_load_env
         return
     }
@@ -27,7 +27,7 @@ ___x_cmd_python_load(){
         ___X_CMD_PYTHON_LOADED=1
     else
         ___x_cmd_python_load_checkinstallable || {
-            x:warn "Current env is not installable"
+            python:warn "Current env is not installable"
             ___x_cmd_python_load_env
             return
         }
@@ -37,16 +37,28 @@ ___x_cmd_python_load(){
     # TODO: In the future, we need to check the current version is good enough.
 }
 
+___X_CMD_PYTHON_SHIMAPP_PATH=
 ___x_cmd_python_load_env(){
-    # TODO: add quiet
-    x:debug "Loading python in this shell env using 'x env try python'"
-    x env try python
+    if [ -n "$___X_CMD_PYTHON_SHIMAPP_PATH" ]; then
+        return 0
+    fi
+
+    local x_=""
+    ___x_cmd_pkg_sphere_getbinpath_  --sphere X --sphereroot "$___X_CMD_PKG_ROOT_SPHERE"  "python" "Miniconda3-py310_23.9.0-0" "shim_bin" || return 
+    ___X_CMD_PYTHON_SHIMAPP_PATH="$x_"
+
 
     ___X_CMD_PYTHON_LOADED=installable
+    # # TODO: add quiet
+    # python:debug "Loading python in this shell env using 'x env try python'"
+    # x env try python 2>/dev/null || {
+    #     python:error -c 'x env try python' "install python failed"
+    #     return 1
+    # }
 
-    ___x_cmd_python___cmd(){
-        command "$@"
-    }
+    # ___x_cmd_python___cmd(){
+    #     command "$@"
+    # }
 }
 
 # TODO: Add yes and quiet in the future
@@ -56,4 +68,5 @@ ___x_cmd_python_load_checkenv(){
 
 ___x_cmd_python_load_checkinstallable(){
     [ -w "$(command -v python3)" ]
+    # [ -w "$___X_CMD_PYTHON_SHIMAPP_PATH" ]
 }
