...

diff --git a/mod/docker/lib/setup b/mod/docker/lib/setup
--- a/mod/docker/lib/setup
+++ b/mod/docker/lib/setup
@@ -1,4 +1,4 @@
-# shellcheck shell=dash
+# shellcheck shell=dash disable=SC2016
 
 # x docker setup --user el <container-name>
 
@@ -6,6 +6,14 @@
 # x docker start --name bscratch -d scratch
 # x docker setup bscratch
 # x docker exec -it bscratach sh
+
+# How to setup
+# 1. create a readonly volume for /var/x-cmd/global, include bin/curl, bin/busybox
+# 2. volume /bin/x get the source from /var/cmd/global
+# 3. [optional] /etc/bashrc => if [ -f "$HOME/.x-cmd.root/X" ]; then . "$HOME/.x-cmd.root/X"; else eval "$(x init)"; fi
+
+___X_CMD_DOCKER_CACHE="$___X_CMD_ROOT_CACHE/docker"
+# ___X_CMD_DOCKER_TMP="$___X_CMD_ROOT_TMP/docker"
 
 ___x_cmd_docker_setup(){
     local user
@@ -21,45 +29,33 @@ ___x_cmd_docker_setup(){
         esac
     done
 
+    local container
     while [ $# -gt 0 ]; do
-        ___x_cmd_docker_setup_cp "$1"
-
-        local IFS=,
-        if [ -z "$user" ]; then
-            x:info "Login any user, then try eval \`x install)\`"
-            x:info "If you using scratch image, try we have inject busybox into environment. try running x:"
+        container="$1"; shift
+        if ! command docker start "$container" >/dev/null 2>&1; then
+            docker:error "Container '$container' does not exist"
+            return 1
         fi
-        for e in $user; do
-            [ -n "$e" ] || return
-            ___x_cmd_docker_setup_init "$1" "$e"
-        done
 
-        shift
+        # TODO: get id
+        # TODO: then using cache to hint this container already setup
+
+        if ! ___x_cmd_docker_setup_prepare___exec "$container"; then
+            docker:error "Failed to setup container '$container'"
+            return 1
+        fi
+
+        # TODO: setup user
+        # local IFS=,
+        # if [ -z "$user" ]; then
+        #     x:info "Login any user, then try eval \`x install\`"
+        #     x:info "If you using scratch image, try we have inject busybox into environment. try running x:"
+        # fi
+        # for e in $user; do
+        #     [ -n "$e" ] || return
+        #     ___x_cmd_docker_setup_init "$container" "$e"
+        # done
     done
-}
-
-___x_cmd_docker___container_cpif(){
-    local localpath
-    local containerpath
-
-    if ! docker cp "$containerpath" ___x_cmd_docker___container_cpif_file_$$; then
-        docker cp "$localpath" "$containerpath"
-    fi
-    x rmrf ___x_cmd_docker___container_cpif_file_$$
-}
-
-___x_cmd_docker_setup_cp(){
-    # TODO: using pkg to download the specifc busybox and curl
-    ___x_cmd_docker___container_cpif busybox                                "$1:/bin/busybox"
-    ___x_cmd_docker___container_cpif curl                                   "$1:/bin/curl"
-    ___x_cmd_docker___container_cpif "$___X_CMD_ROOT_MOD/x-cmd/lib/bin/xxx" "$1:/bin/x"
-}
-
-___x_cmd_docker_setup_init(){
-    local container=$1
-    local user="$1"
-
-    docker exec --user "$user" -it "$container" bash -c 'eval "$(x install)"'
 }
 
 
@@ -84,3 +80,102 @@ ___x_cmd_docker_setup_init(){
 
 # }
 
+# prepare environment ==> download curl, busybox
+___x_cmd_docker_setup_prepare(){
+    case "$1" in
+        run)    shift; ___x_cmd_docker_setup_prepare___run "$@" ;;
+        exec)   shift; ___x_cmd_docker_setup_prepare___exec "$@" ;;
+        *) ;;
+    esac
+}
+
+___x_cmd_docker_setup_prepare___exec(){
+    local container="$1"
+    local need_setup=; local x_osname=; local x_arch=; local need_busybox=; local need_curl=; local need_x=
+    ___x_cmd_docker_setup_prepare___get_info_form_container_ "$container" || return
+
+    [ -n "$need_setup" ] || {
+        docker:info "Container has already been setup"
+        return 0
+    }
+
+    local x_=
+    if [ -n "$need_busybox" ]; then
+        docker:info "Try to inject ==> busybox"
+        ___x_cmd_docker_setup_prepare___get_pkg_path_ busybox "$x_osname/$x_arch" || return
+        command docker cp "$x_" "$container:/bin/busybox"
+    fi
+
+    if [ -n "$need_curl" ]; then
+        docker:info "Try to inject ==> curl"
+        ___x_cmd_docker_setup_prepare___get_pkg_path_ curl "$x_osname/$x_arch" || return
+        command docker cp "$x_" "$container:/bin/curl" || return 1
+
+        docker:info "Try to inject ==> ca-certificates"
+        x cacert which_
+        command docker cp "$x_" "$container:/etc/ssl/certs/ca-certificates.crt" || return
+    fi
+
+    if [ -n "$need_x" ]; then
+        docker:info "Try to inject ==> x"
+        command docker cp "$___X_CMD_ROOT/v/$___X_CMD_VERSION"   "$container:/var/x-cmd/v/global"
+        command docker cp "$___X_CMD_ROOT_MOD/x-cmd/lib/bin/xxx" "$container:/bin/x"
+    fi
+
+    ___x_cmd_docker_setup_prepare___set_startup_in_container_ "$container"
+}
+
+___x_cmd_docker_setup_prepare___run(){
+    local image="$1"
+    local container; container="$( command docker run -it -d "$image" )" || return
+
+    local need_setup=; local x_osname=; local x_arch=; local need_busybox=; local need_curl=; local need_x=
+    ___x_cmd_docker_setup_prepare___get_info_form_container_ "$container" || return
+    command docker container rm -f "$container" >/dev/null
+
+    local x_=
+    if [ -n "$need_budybox" ]; then
+        docker:info "Bind mount a volume ==> /bin/busybox"
+        ___x_cmd_docker_setup_prepare___get_pkg_path_ busybox "$x_osname/$x_arch"   || return
+        x cmdstr ___X_CMD_DOCKER_RUN_OPTS -v "$x_:/bin/busybox"
+    fi
+
+    if [ -n "$need_curl" ]; then
+        docker:info "Bind mount a volume ==> bin/curl"
+        ___x_cmd_docker_setup_prepare___get_pkg_path_ curl "$x_osname/$x_arch"      || return
+        x cmdstr ___X_CMD_DOCKER_RUN_OPTS -v "$x_:/bin/curl"
+
+        x cacert which_ || return
+        x cmdstr ___X_CMD_DOCKER_RUN_OPTS -v "$x_:/etc/ssl/certs/ca-certificates.crt:ro"
+    fi
+
+    docker:info "Bind mount a volume ==> /bin/x"
+    x cmdstr ___X_CMD_DOCKER_RUN_OPTS                                   \
+        -e ___X_CMD_WEBSRC_REGION="$___X_CMD_WEBSRC_REGION"             \
+        -v "$___X_CMD_ROOT_MOD/x-cmd/lib/bin/xxx:/bin/x"                \
+        -v "$___X_CMD_ROOT/v/$___X_CMD_VERSION:/var/x-cmd/v/global:ro"
+}
+
+___x_cmd_docker_setup_prepare___get_info_form_container_(){
+    local container="$1"
+    docker:debug "Get container information ==> $container"
+    need_setup=; x_osname=; x_arch=; need_busybox=; need_curl=; need_x=
+
+    local setup_script; setup_script="$( cat "$___X_CMD_ROOT_MOD/docker/lib/data/setup.sh" )"
+    eval "$( command docker exec "$container" sh -c "${setup_script}; ___x_cmd_docker_setup___getinfo" || printf "return 1\n" )" || return 1
+}
+
+___x_cmd_docker_setup_prepare___set_startup_in_container_(){
+    local container="$1"
+    local setup_script; setup_script="$( cat "$___X_CMD_ROOT_MOD/docker/lib/data/setup.sh" )"
+    docker:info "Set start up file in container"
+    command docker exec -e ___X_CMD_WEBSRC_REGION="$___X_CMD_WEBSRC_REGION" "$container" sh -c "${setup_script}; ___x_cmd_docker_setup___set_startup"
+}
+
+___x_cmd_docker_setup_prepare___get_pkg_path_(){
+    x_=; local name="$1"; local os_arch="$2"
+    docker:debug "Prepare $os_arch $name"
+    x pkg download "$name" "" "$os_arch" "$___X_CMD_DOCKER_CACHE/$name" || return
+    x pkg populate "$name" "" "$os_arch" "$___X_CMD_DOCKER_CACHE/$name" || return
+    x_="$(x pkg xbin path "$name" "" "$os_arch" "$___X_CMD_DOCKER_CACHE/$name")" || return
+}
diff --git a/mod/env/lib/config b/mod/env/lib/config
--- a/mod/env/lib/config
+++ b/mod/env/lib/config
@@ -19,12 +19,14 @@ ___x_cmd_env_config_load(){
         local ___X_CMD_PKG___META_NAME="${name}"
         local ___X_CMD_PKG___META_VERSION="${version}"
 
-        if [ -n "$script_path" ];then
-            . "$script_path" || {
-                env:error "Source $script_path failed" ; return 1
-            }
-        fi
+        { [ -n "$script_path" ] && [ -f "$script_path" ]; } || {
+            env:debug "Script file not found ==> $script_path"
+            continue
+        }
 
+        . "$script_path" || {
+            env:error "Source $script_path failed" ; return 1
+        }
     done <"$___X_CMD_ENV_VERSION_CONFIG_PATH"
 }
 
diff --git a/mod/fileage/lib/main b/mod/fileage/lib/main
--- a/mod/fileage/lib/main
+++ b/mod/fileage/lib/main
@@ -1,4 +1,4 @@
-# shellcheck shell=dash
+# shellcheck shell=dash disable=SC2030,SC2031
 
 # Default: modifiled
 # Cannot work for folder: The modified time attribute of folder keep updating.
@@ -11,100 +11,58 @@
 # x fileage -lt lm -m LICENSE
 
 ___x_cmd_fileage___main(){
-    if [ "$1" = "--help" ] || [ "$1" = "-h" ]; then x help -m fileage; return ;
-    fi
+    case "$1" in
+        --help|-h)              x help -m fileage;             return 1;;
+        --stat)         shift;  ___x_cmd_fileage_stat "$@";    return  ;;
+        --in)           shift;  ___x_cmd_fileage___in "$@";    return  ;;
+    esac
 
+    ___x_cmd_fileage___exec "$@"
+}
 
+___x_cmd_fileage___in(){
     local current=""; current="$(date +%s)"
+    local date="$1"
+    [ -n "$date" ] || { x log :fileage error -h 'x fileage --in <human_time_unit e.g 1d> <file_path>' "Provide human time unit"; return 64; }
+    shift 1
+    local x_="";   x humantime tosec_ "$date"
 
-    if [ "$1" = --in ]; then
-        local date="$2"
-        [ -n "$date" ] || { x log :fileage error -h 'x fileage --in <human_time_unit e.g 1d> <file_path>' "Provide human time unit"; return 64; }
-        shift 2
-        local ___X_CMD_HUMANTIME_TOSEC_
-        x humantime tosec_ "$date"
+    local ts=""
+    ___x_cmd_fileage_stat "$@" | while read -r ts; do
+        [ -n "$ts" ] || {
+            x log :fileage error "Get fileage failure. Please check the file exists. TS=$ts"
+            local IFS=" "; x log :fileage error "filelist ==> $*"
+            return 1
+        }
+        [ "$((current - ts))" -le "$x_" ] || return 1
+    done
+}
 
-        ___x_cmd_fileage_stat "$@" | while read -r ts; do
-            [ -n "$ts" ] || {
-                x log :fileage error "Get fileage failure. Please check the file exists. TS=$ts"
-                local IFS=" "; x log :fileage error "filelist ==> $*"
-                return 1
-            }
-            if [ "$((current - ts))" -ge "$___X_CMD_HUMANTIME_TOSEC_" ]; then
-                return 1
-            fi
-        done
-        return 0
-    fi
-
-    local human=""
-    if [ "$1" = -H ]; then
-        shift; human=1
-    fi
-
+___x_cmd_fileage___exec(){
+    local current="";   current="$(date +%s)"
+    local human="";     [ "$1" != -H ] || { shift;  human=1; }
     ___x_cmd_fileage_stat "$@" | while read -r ts; do
         [ -n "$ts" ] || {
             x log :fileage error "Get fileage failure. Please check the file exists. TS=$ts";
             local IFS=" "; x log :fileage error "filelist ==> $*"
             return 1
         }
-        if [ -z "$human" ]; then  printf "%s\n" "$((current - ts))"
+        if [ -z "$human" ]; then
+            printf "%s\n" "$((current - ts))"
         else
-            local ___X_CMD_HUMANTIME_SEC_
-            x humantime sec_ "$((current - ts))"
-            printf "%s\n" "$___X_CMD_HUMANTIME_SEC_"
+            local x_="";   x humantime sec_ "$((current - ts))"
+            printf "%s\n" "$x_"
         fi
     done
 }
 
+# deprecated
 ___x_cmd_fileage_(){
     if ___x_cmd_fileage_stat_ "$@"; then
         local current; current="$(date +%s)"
-        ___X_CMD_FILEAGE_="$((current - ___X_CMD_FILEAGE_STAT_))"
+        x_="$((current - x_))"
     else
-        ___X_CMD_FILEAGE_=
+        x_=
         return 1
     fi
-}
-
-___x_cmd_fileage_stat_(){
-    # Reference: https://linux.die.net/man/1/stat
-    if stat -c "%Y" /bin/sh 2>/dev/null 1>&2; then
-        ___x_cmd_fileage_stat_(){
-            local param="%Y"
-            case "$1" in
-                -m) shift ;;
-                # https://unix.stackexchange.com/questions/24441/get-file-created-creation-time
-                -c) param="%Y"; shift ;;  # created time using modified time
-                -a) param="%X"; shift ;;
-            esac
-
-            ___X_CMD_FILEAGE_STAT_=
-            [ -f "$1" ] || return 1
-            ___X_CMD_FILEAGE_STAT_="$(stat -c "$param" "$@")"
-        }
-    elif stat -f "%m" /bin/sh 2>/dev/null 1>&2; then
-        ___x_cmd_fileage_stat_(){
-            local param="%m"
-            case "$1" in
-                -m) shift ;;
-                -c) param="%c"; shift ;;
-                -a) param="%a"; shift ;;
-            esac
-
-            ___X_CMD_FILEAGE_STAT_=
-            [ -f "$1" ] || return 1
-            ___X_CMD_FILEAGE_STAT_="$(stat -f "$param" "$@")"
-        }
-    else
-        return 1
-    fi
-
-    ___x_cmd_fileage_stat_ "$@"
-}
-
-___x_cmd_fileage_stat(){
-    local ___X_CMD_FILEAGE_STAT_
-    ___x_cmd_fileage_stat_ "$@"
-    printf "%s\n" "$___X_CMD_FILEAGE_STAT_"
 }
diff --git a/mod/hub/lib/account/user b/mod/hub/lib/account/user
--- a/mod/hub/lib/account/user
+++ b/mod/hub/lib/account/user
@@ -35,6 +35,28 @@ ___x_cmd_hub_account_rename(){
     ___x_cmd_hub___util_handle_resp true "$res" "Rename successfully:"
 }
 
+___x_cmd_hub_account_delete(){
+    local X_help_cmd='___x_cmd_hub___help account delete'
+    help:arg:parse
+
+    x ui yesno "Are you sure to delete your account? This operation is irreversible" || return 1
+
+    local res
+    if ! res="$(___x_cmd_hub___util_curl delete /api/v0/account)" ; then
+        ___x_cmd_hub___util_handle_resp false "$res" "Failed to delete account:"
+        return 1
+    fi
+
+    ___x_cmd_hub___util_cache_invalidate
+    x rmrf "$(___x_cmd_hub___util_user_dir me)"
+    if ! ___x_cmd_hub_cfg --unset token ; then
+        ___x_cmd_ui_tf false "Failed to unset token use cfgy"
+        return 1
+    fi
+
+    ___x_cmd_hub___util_handle_resp true "$res" "Delete successfully"
+}
+
 ___x_cmd_hub_get_userinfo_by_token(){
     local token="${1}"
     if [ -z "$token" ]; then
@@ -50,10 +72,53 @@ ___x_cmd_hub_get_userinfo_by_token(){
 
     [ -z "$json" ] || { printf "%s\n" "$res" ; return 0; }
     printf "%s" "$res" | (
-        x jo env . name=.name id=.id plan=.plan email=.email
+        x jo env . name=.name id=.id plan=.plan email=.email region=.region
+        ___x_cmd_hub___util_handle_resp true "" "Account info:" "id: $id" "name: $name" "region: $region" # "plan: $plan" "email: $email"
+    )
+}
+
+___x_cmd_hub_account_verify(){
+    local ticket="${1}"
+    local res; local return_code
+    res="$(NO_AUTH=1 ___x_cmd_hub___util_curl get /api/v0/account/verify "ticket=$ticket")"; return_code=$?
+    case "$return_code" in
+        0) ;;
+        4)
+            x ui yesno "Your account is not registered, do you want to register it?" || return 1
+            #TODO: register
+            hub:warn "Not implemented yet, please use 'x hub register' to register"
+            return 1
+            # if ! res="$(NO_AUTH=1 ___x_cmd_hub___util_curl get /api/v0/account/activate "ticket=$ticket")" ; then
+            #     ___x_cmd_hub___util_handle_resp false "$res" "Failed to activate account"
+            #     return 1
+            # fi
+            ;;
+        *)
+            ___x_cmd_hub___util_handle_resp false "$res" "Failed to verify token:"
+            ___x_cmd_hub___util_handle_resp false ""     "Failed to login, please check your token"
+            return 1
+            ;;
+    esac
+
+    printf "%s" "$res" | (
+        x jo env . name=.name id=.id plan=.plan email=.email \
+            region=.region token=.token endpoint=.endpoint \
+            token=.token
         if [ "${name#user_}" != "$name" ] && [ "${#name}" -gt 16 ]; then
             hub:warn "Your account name is not set, please use 'x hub account rename <username>' to set it"
         fi
-        ___x_cmd_hub___util_handle_resp true "" "Account info:" "id: $id" "name: $name" "plan: $plan" "email: $email"
+        ___x_cmd_hub___util_handle_resp true "" "Account info:" \
+            "id: $id" "name: $name"  \
+            "region: $region" # "plan: $plan" "email: $email"
+
+        hub:debug "endpoint => $endpoint"
+        [ "$endpoint" = "$___X_CMD_HUB_SERVICE_URL" ] || {
+            hub:warn "Change endpoint $___X_CMD_HUB_SERVICE_URL => $endpoint"
+            ___x_cmd_hub_cfg --set endpoint="$endpoint"
+        }
+
+        ___x_cmd_hub_cfg token="${token}"
     )
+
+    ___x_cmd_ui_tf true "Login success"
 }
diff --git a/mod/pkg/lib/mutate/download b/mod/pkg/lib/mutate/download
--- a/mod/pkg/lib/mutate/download
+++ b/mod/pkg/lib/mutate/download
@@ -11,10 +11,10 @@ ___x_cmd_pkg_download(){
     esac
 
     local name="${1:?Provide pkg name}"
-    local version="${2:-$(___x_cmd_pkg_default_version "$name")}"
     local osarch="${3:-$(___x_cmd_pkg_osarch)}"
+    local version="${2:-$(___x_cmd_pkg_default_version "$name" "$osarch")}" || return
     [ -n "$version" ] || {
-        pkg:error "Not found candidate: $name;"
+        pkg:error "Not found candidate => $name"
         pkg:error "Please use 'x pkg ll' or 'x pkg ls all <candidate>' to check available candidate and version"
         return 1
     }
@@ -23,7 +23,7 @@ ___x_cmd_pkg_download(){
 
     if [ -z "$url_list" ]; then
         pkg:error "Not found url for $name $version"
-        pkg:error "Please use ' x pkg ll' or ' x pkg ls all <candidate> ' to check available candidate and version"
+        pkg:error "Please use 'x pkg ll' or 'x pkg ls all <candidate>' to check available candidate and version"
         return 1
     fi
 
diff --git a/mod/pkg/lib/mutate/populate b/mod/pkg/lib/mutate/populate
--- a/mod/pkg/lib/mutate/populate
+++ b/mod/pkg/lib/mutate/populate
@@ -56,8 +56,8 @@ ___x_cmd_pkg_populate(){
     esac
 
     local name="${1:?Provide pkg name}"
-    local version="${2:-$(___x_cmd_pkg_default_version "$name")}"
     local osarch="${3:-$(___x_cmd_pkg_osarch)}"
+    local version="${2:-$(___x_cmd_pkg_default_version "$name" "$osarch")}"
     local tgt="${4:-"$___X_CMD_PKG_POPULATE_PATH/$name/$version"}"
 
     [ -n "$version" ] || {
@@ -91,9 +91,13 @@ ___x_cmd_pkg_populate(){
     local ___X_CMD_PKG___META_ARCH="${osarch##*/}"
     local ___X_CMD_PKG___META_TGT="$tgt"
     {
-        trap 'x rmrf $tgt; printf "\r\n";  pkg:error "populate interrupted"; return 1;' INT
-        . "$script_path" || {
-            pkg:error "Source $script_path failed" ; return 1
+        (
+            trap 'printf "\r\n"; pkg:error "populate interrupted"; return' INT
+            . "$script_path"
+        ) || {
+            x rmrf "$tgt"
+            pkg:error "Source $script_path failed"
+            return 1
         }
     }
     ___x_cmd_pkg_populate___chmod "$name" "$version" "$osarch" "$tgt" || return 1
@@ -110,7 +114,7 @@ ___x_cmd_pkg_populate___chmod(){
         [ -n "$xbin_name" ] || continue
         xbin_name="${xbin_name#:*}"
         xbin_name="${xbin_name%:*}"
-        bin_path="$(___x_cmd_pkg_xbin_path "$xbin_name" "$version")"
+        bin_path="$(___x_cmd_pkg_xbin_path "$xbin_name" "$version" "$osarch")"
         if  [ -f "$bin_path" ]; then
             chmod +x "$bin_path" || {
                 pkg:error "Can't use chmod on $bin_path"
diff --git a/mod/xrc/latest b/mod/xrc/latest
--- a/mod/xrc/latest
+++ b/mod/xrc/latest
@@ -1,18 +1,18 @@
 # Author:       Li Junhao       l@x-cmd.com
 # shellcheck    shell=sh        disable=SC2039,SC1090,SC3043,SC2263,SC2142
 
-# license:      GPLv3
+# license:      AGPLv3
 
 # Section 0: Prepare source 0
 
 ___x_cmd_help_ret(){
-    eval x help -m "${M}" >&2
+    eval x help -m "${M}"
     return 1
 }
 
-alias help:ret:0='___x_cmd_help_ret || return 0 2>/dev/null || exit 0'
-alias help:ret:1='___x_cmd_help_ret || return 1 2>/dev/null || exit 1'
-alias help:ret:64='___x_cmd_help_ret || return 64 2>/dev/null || exit 64'
+alias help:ret:0='___x_cmd_help_ret      || return 0 2>/dev/null || exit 0'
+alias help:ret:1='___x_cmd_help_ret >&2  || return 1 2>/dev/null || exit 1'
+alias help:ret:64='___x_cmd_help_ret >&2 || return 64 2>/dev/null || exit 64'
 
 
 # TODO: figure out whether the following are deprecated
@@ -221,7 +221,7 @@ else
         elif /bin/sh --help 2>&1 | grep BusyBox >/dev/null; then
             printf "%s" ash
         else
-            printf "WARNING: %s\n" "Unknown shell." >&2
+            printf "%s\n" "- W|x: Unknown shell." >&2
         fi
     )"
 fi
@@ -247,7 +247,7 @@ alias panic:return='eval "___x_cmd_panic___loginner && return"'
 alias panic:exit='eval "___x_cmd_panic___loginner && exit"'
 
 ___x_cmd_panic___loginner(){ x log ":${N:-x}" "${L:-error}" "$M"; }
-xrc:mod:lib xrc    functor first line util ldict/posix inner/index shgen
+xrc:mod:lib xrc    functor first line util ldict/posix inner/index shgen exitcode
 # EndSection
 
 # Section 3: main entrance helper: xrc_set_main, which_one, which_one_with_naming
@@ -323,8 +323,8 @@ ___x_cmd_which_one(){
             x:debug "Resource recognized as local file with relative path: $RESOURCE_NAME"
 
             [ -f "$RESOURCE_NAME" ] || {
-                x:warn "Local file not exists: $RESOURCE_NAME"
-                return 1
+                x:warn "Local file not exists ==> $RESOURCE_NAME"
+                return "$x_EX_FILENOTFOUND"
             }
 
             local x_; ___x_cmd_abspath_ "$RESOURCE_NAME" || return  # TODO: Why there must be abspath ?
@@ -363,8 +363,8 @@ ___x_cmd_which_one(){
                 ___X_CMD_WHICH_ONE_RESULT="$TGT"
                 return 0
             fi
-            x:debug "Module not found: $module"
-            return 1
+            x:error --tgt "$TGT" --mod "$module" "Module not found in ___x_cmd_which_one()"
+            return "$x_EX_FILENOTFOUND"
 
             # x:info "Downloading resource=$RESOURCE_NAME to local cache: $TGT"
             # if ___x_cmd_httpget_gitx_official "mod/$module" "$TGT"; then
@@ -404,11 +404,11 @@ ___x_cmd_xrc_source_file(){
     while [ $# -ne 0 ]; do
         ___X_CMD_LOCAL_XRCPATH="$1";   shift
 
-        if ! ___X_CMD_NO_LOCAL=1 ___x_cmd_which_one_with_naming "$___X_CMD_LOCAL_XRCPATH"; then
-            printf "ERROR: Interrupted because resource not found. %s \n" "$___X_CMD_LOCAL_XRCPATH" >&2
-            printf "%s\n" "return 1"
-            return 1
-        fi
+        ___X_CMD_NO_LOCAL=1 ___x_cmd_which_one_with_naming "$___X_CMD_LOCAL_XRCPATH" || {
+            local code=$?
+            x:error "resource not found. ___x_cmd_xrc_source_file() abort ==> $___X_CMD_LOCAL_XRCPATH"
+            return "$code"
+        }
 
         # Ask whether using http or outside resource.
         if [ "$___X_CMD_WHICH_ONE_RESOURCE_TYPE" = http ] && [ -z "$NOWARN" ]; then
@@ -545,8 +545,15 @@ xrc httpget
 xrc:mod x-cmd/latest
 xrc:mod args/latest     # TODO: args is not necessary
 
+
+alias xd="x docker"     # xdk is x-box command, xdo is also occupied ... so we can only use xd
+# alias xdx="x docker x"     # xdk is x-box command, xdo is also occupied ... so we can only use xd
+alias xdb="x dbox"
+
 alias xws="x ws"
-alias s="x ws"
+alias ws="x ws"
+alias s=""      # occupied
+alias xgi="x git"
 
 if [ -n "$ZSH_VERSION" ]; then
     alias -- +=___x_cmd_xrc_import
@@ -560,6 +567,10 @@ if ___x_cmd_is_suitable_advise_env; then
     x:debug "Using module advise for completion."
     command -v ___x_cmd_advise >/dev/null || xrc advise/latest
     ___x_cmd_advise init xrc
+    ___x_cmd_advise init xws "$___X_CMD_ROOT_ADV/ws/advise.jso" s
+    ___x_cmd_advise init xd  "$___X_CMD_ROOT_ADV/docker/advise.jso"
+    ___x_cmd_advise init xdb "$___X_CMD_ROOT_ADV/dbox/advise.jso"
+    ___x_cmd_advise init xgi "$___X_CMD_ROOT_ADV/git/advise.jso"
 fi
 
 # EndSection
@@ -580,6 +591,22 @@ if ___x_cmd_is_interactive_tty; then
     xrc:mod boot/latest
     ___x_cmd_boot_rc  load
     ___x_cmd_boot_mod load
+fi
+
+if [ -n "$ZSH_VERSION" ]; then
+    if ___x_cmd_is_interactive; then
+        trap '
+        case "$0" in
+            zsh)        return 130 ;;
+            -zsh)       return 130 ;;
+            _zsh*)      return 130 ;;
+            */zsh)      return 130 ;;
+            */zsh.exe)  return 130 ;;
+        esac
+        ' INT              # Experimental, change the zsh default behavior.
+    else
+        trap -- ':' INT
+    fi
 fi
 
 alias ,='x chat'
