...

diff --git a/mod/docker/lib/setup b/mod/docker/lib/setup
--- a/mod/docker/lib/setup
+++ b/mod/docker/lib/setup
@@ -92,7 +92,7 @@ ___x_cmd_docker_setup_prepare(){
 ___x_cmd_docker_setup_prepare___exec(){
     local container="$1"
     local need_setup=; local x_osname=; local x_arch=; local need_busybox=; local need_curl=; local need_x=
-    ___x_cmd_docker_setup_prepare___get_info_form_container_ "$container" || return
+    ___x_cmd_docker_setup_prepare___get_info_form_container_ "$container"                           || return
 
     [ -n "$need_setup" ] || {
         docker:info "Container has already been setup"
@@ -102,25 +102,25 @@ ___x_cmd_docker_setup_prepare___exec(){
     local x_=
     if [ -n "$need_busybox" ]; then
         docker:info "Try to inject ==> busybox"
-        ___x_cmd_docker_setup_prepare___get_pkg_path_ busybox "$x_osname/$x_arch" || return
-        command docker cp "$x_" "$container:/bin/busybox"
+        ___x_cmd_docker_setup_prepare___get_pkg_path_ busybox "$x_osname/$x_arch"                   || return
+        command docker cp "$x_" "$container:/bin/busybox"                                           || return
     fi
 
     if [ -n "$need_curl" ]; then
         docker:info "Try to inject ==> curl"
-        ___x_cmd_docker_setup_prepare___get_pkg_path_ curl "$x_osname/$x_arch" || return
-        command docker cp "$x_" "$container:/bin/curl" || return 1
+        ___x_cmd_docker_setup_prepare___get_pkg_path_ curl "$x_osname/$x_arch"                      || return
+        command docker cp "$x_" "$container:/bin/curl"                                              || return
 
         docker:info "Try to inject ==> ca-certificates"
         x cacert which_
-        command docker cp -L "$x_" "$container:/etc/ssl/certs/ca-certificates.crt" || return
+        command docker cp -L "$x_" "$container:/etc/ssl/certs/ca-certificates.crt" 2>/dev/null      || return
     fi
 
     if [ -n "$need_x" ]; then
         docker:info "Try to inject ==> x"
-        command docker cp "$___X_CMD_ROOT_GLOBAL"                "$container:/var/x-cmd/global"
-        command docker cp "$___X_CMD_ROOT/v/$___X_CMD_VERSION"   "$container:/var/x-cmd/v/global"
-        command docker cp "$___X_CMD_ROOT_MOD/x-cmd/lib/bin/xxx" "$container:/bin/x"
+        command docker cp "$___X_CMD_ROOT_GLOBAL"                "$container:/var/x-cmd/global"     || return
+        command docker cp "$___X_CMD_ROOT/v/$___X_CMD_VERSION"   "$container:/var/x-cmd/v/global"   || return
+        command docker cp "$___X_CMD_ROOT_MOD/x-cmd/lib/bin/xxx" "$container:/bin/x"                || return
     fi
 
     ___x_cmd_docker_setup_prepare___set_startup_in_container_ "$container"
@@ -128,10 +128,10 @@ ___x_cmd_docker_setup_prepare___exec(){
 
 ___x_cmd_docker_setup_prepare___run(){
     local image="$1"
-    local container; container="$( command docker run -it -d "$image" )" || return
+    local container; container="$( command docker run -it -d "$image" )"            || return
 
     local need_setup=; local x_osname=; local x_arch=; local need_busybox=; local need_curl=; local need_x=
-    ___x_cmd_docker_setup_prepare___get_info_form_container_ "$container" || return
+    ___x_cmd_docker_setup_prepare___get_info_form_container_ "$container"           || return
     command docker container rm -f "$container" >/dev/null
 
     local x_=
@@ -165,21 +165,27 @@ ___x_cmd_docker_setup_prepare___get_info_form_container_(){
     docker:debug "Get container information ==> $container"
     need_setup=; x_osname=; x_arch=; need_busybox=; need_curl=; need_x=
 
-    local setup_script; setup_script="$( cat "$___X_CMD_ROOT_MOD/docker/lib/data/setup.sh" )"
+    local setup_script; setup_script="$( ___x_cmd_cmds_cat "$___X_CMD_ROOT_MOD/docker/lib/data/setup.sh" )"
     eval "$( command docker exec "$container" sh -c "${setup_script}; ___x_cmd_docker_setup___getinfo" || printf "return 1\n" )" || return 1
 }
 
 ___x_cmd_docker_setup_prepare___set_startup_in_container_(){
     local container="$1"
-    local setup_script; setup_script="$( cat "$___X_CMD_ROOT_MOD/docker/lib/data/setup.sh" )"
+    local setup_script; setup_script="$( ___x_cmd_cmds_cat "$___X_CMD_ROOT_MOD/docker/lib/data/setup.sh" )"
     docker:info "Set start up file in container"
     command docker exec -e ___X_CMD_WEBSRC_REGION="$___X_CMD_WEBSRC_REGION" "$container" sh -c "${setup_script}; ___x_cmd_docker_setup___init"
 }
 
 ___x_cmd_docker_setup_prepare___get_pkg_path_(){
-    x_=; local name="$1"; local os_arch="$2"
-    docker:debug "Prepare $os_arch $name"
-    x pkg download "$name" "" "$os_arch" "$___X_CMD_DOCKER_CACHE/$name" || return
-    x pkg populate "$name" "" "$os_arch" "$___X_CMD_DOCKER_CACHE/$name" || return
-    x_="$(x pkg xbin path "$name" "" "$os_arch" "$___X_CMD_DOCKER_CACHE/$name")" || return
+    x_=; local name="$1"; local osarch="$2"
+    docker:debug "Prepare $name $osarch to $___X_CMD_DOCKER_CACHE"
+    x pkg sphere add --sphere X --sphereroot "$___X_CMD_DOCKER_CACHE" "$name" "" "$osarch" || {
+        docker:error "Fail to prepare $name $osarch"
+        return 1
+    }
+    docker:debug "Get $name $osarch xbin path"
+    x_="$(x pkg xbin path --sphere X --sphereroot "$___X_CMD_DOCKER_CACHE" "$name" "" "$osarch" X "$___X_CMD_DOCKER_CACHE")" || {
+        docker:error "Fail to get $name $osarch bin path"
+        return 1
+    }
 }
diff --git a/mod/hub/lib/keypair/index b/mod/hub/lib/keypair/index
--- a/mod/hub/lib/keypair/index
+++ b/mod/hub/lib/keypair/index
@@ -6,18 +6,11 @@ ___x_cmd_hub_keypair(){
     local X_help_cmd='___x_cmd_hub___help keypair'
     help:arg-null:parse
 
-    x_=; ___x_cmd_hub_u_userdir_ me || return 1
-    local keydir; keydir="$x_/keypair" || return 1
-    x mkdirp "$keydir"
-    local ___X_CMD_HUB_PUBLIC_KEY_PATH="$keydir/${___X_CMD_HUB_KEYPAIR_NAME}_public.pem"
-    local ___X_CMD_HUB_PRIVATE_KEY_PATH="$keydir/${___X_CMD_HUB_KEYPAIR_NAME}_private.pem"
-    hub:debug "___X_CMD_HUB_PUBLIC_KEY_PATH=$___X_CMD_HUB_PUBLIC_KEY_PATH ___X_CMD_HUB_PRIVATE_KEY_PATH=$___X_CMD_HUB_PRIVATE_KEY_PATH"
-
     local op="$1"; shift
     case "$op" in
-        gen|save|load|ls|rm|get_key_path_)
+        gen|save|load|ls|rm)
             "___x_cmd_hub_keypair_$op" "$@" ; return ;;
-        *) ___x_cmd_hub_u_subcmd_invalid key "$@";  return ;;
+        *) ___x_cmd_hub_u_subcmd_invalid keypair "$@";  return ;;
     esac
 }
 
@@ -25,28 +18,44 @@ ___x_cmd_hub_keypair_get_key_path_(){
     local keyname="$1"; [ -n "$keyname" ] || M='Provide key name' N=hub log:ret:64
     local keytype="$2"; [ -n "$keytype" ] || M='Provide key type' N=hub log:ret:64
 
-    x_=; ___x_cmd_hub_u_userdir_ me || return 1
-    x mkdirp "$x_/keypair/"
-    x_="$x_/keypair/${keyname}_${keytype}.pem"
-    [ -f "$x_" ] || ___x_cmd_hub_keypair___ensure "$keyname"
+    x_=; ___x_cmd_hub_keypair___keypath_ "$keyname" "$keytype" || return 1
+    x mkdirp "${x_%/*}"
+    [ -f "$x_" ] || {
+        hub:info "No $keytype key '$keyname', try to load from server"
+        NO_LOG=1 ___x_cmd_hub_keypair___download "$keyname" "$keytype" || {
+            case "$(___x_cmd_hub_u_curl_resp_code)" in
+                404)
+                    hub:info "No $keytype key '$keyname' found at server, try to generate"
+                    ___x_cmd_hub_keypair_gen "$keyname" || return 1
+                    ;;
+                *)  hub:error "Failed to load $keytype key"
+                    return 1 ;;
+            esac
+        }
+    }
 }
 
-___x_cmd_hub_keypair___ensure(){
-    local keyname="$1"
-    [ -n "$keyname" ] || M='Provide key name' N=hub log:ret:64
+___x_cmd_hub_keypair___download(){
+    local keyname="$1" ; [ -n "$keyname" ] || M='Provide key name' N=hub log:ret:64
+    local keytype="$2" ; [ -n "$keytype" ] || M='Provide key type' N=hub log:ret:64
 
-    hub:info "No public key '$keyname', try to load from server"
-    NO_LOG=1 ___x_cmd_hub_keypair_load "$keyname" || {
-        case "$(___x_cmd_hub_u_curl_resp_code)" in
-            404)
-                hub:info "No public key '$keyname' found at server, try to generate"
-                ___x_cmd_hub_keypair_gen "$keyname"
-                ;;
-            2*)  return 0 ;;
-            *)  hub:error "Failed to load public key"
-                return 1 ;;
-        esac
+    # Download key
+    local resp=
+    resp="$(___x_cmd_hub_u_curl get "/api/v0/key/$keyname" type=="$keytype")" || {
+        [ -n "$NO_LOG" ] || ___x_cmd_hub_u_handle_resp false "Failed to get rsakey for $___X_CMD_HUB_KEYPAIR_NAME"
+        return 1
     }
+
+    local x_ ; ___x_cmd_hub_keypair___keypath_ "$keyname" "$keytype" || return 1
+    if [ "$keytype" = "public" ]; then
+        printf "%s" "$resp" > "$x_"
+    elif [ "$keytype" = "private" ]; then
+        printf "%s" "$resp" | x openssl enc -d -A -base64 > "${x_}.enc"
+        ___x_cmd_hub_keypair___decrypt_private_key "$x_" || return 1
+    else
+        hub:error "Unknown key type '$keytype'"
+        return 1
+    fi
 }
 
 ___x_cmd_hub_keypair___download_pubkey_list(){
@@ -74,4 +83,40 @@ ___x_cmd_hub_keypair___single_pubkey_to_file(){
     x mkdirp "$x_/keypair"
     local key_path=; key_path="$x_/keypair/default_public.pem"
     printf "%s" "${pubkey}" > "${key_path}"
+}
+
+___x_cmd_hub_keypair___decrypt_private_key(){
+    local key_path="$1"; [ -n "$key_path" ] || M='Provide key_path' N=hub log:ret:64
+    local enc_path="${1}.enc"
+
+    hub:info "Please input password for encrypt private key"
+    local password=
+    while true ; do
+        if ! ___x_cmd_is_interactive_tty ; then
+            hub:error "Password required, but not in interactive tty"
+            return 1
+        fi
+
+        ___X_CMD_TUI_FORM_FINAL_COMMAND=""
+        x tui form password      "Password"           ""  '=~*'  '^.*$' || return 1
+        [ -n "$___X_CMD_TUI_FORM_FINAL_COMMAND" ] || {
+            hub:info "Canceled"
+            x rmrf "$enc_path"
+            return 1
+        }
+
+        hub:debug "x openssl enc -d -aes-256-cbc -in $enc_path -out $key_path -pbkdf2 -pass pass:$password"
+        x openssl enc -d -aes-256-cbc -in "$enc_path" -out "$key_path" -pbkdf2 -pass "pass:$password" 2>/dev/null || {
+            hub:error "Failed to decrypt private key, or password not match, please try again"
+            x rmrf "$key_path"
+            continue
+        }
+        break
+    done
+}
+
+___x_cmd_hub_keypair___keypath_(){
+    local keyname="$1"; [ -n "$keyname" ] || M='Provide key name' N=hub log:ret:64
+    local keytype="$2"; [ -n "$keytype" ] || M='Provide key type' N=hub log:ret:64
+    x_="$___X_CMD_HUB_DATA/me-${___X_CMD_HUB_LOCAL_PROFILE:-"X"}/keypair/${keyname}_${keytype}.pem"
 }
diff --git a/mod/pkg/lib/main b/mod/pkg/lib/main
--- a/mod/pkg/lib/main
+++ b/mod/pkg/lib/main
@@ -1,9 +1,9 @@
 # shellcheck    shell=dash disable=SC2034,SC1090
-___x_cmd_pkg___which_p7zip()(
-    local file_path="$___X_CMD_PKG_ROOT_PATH/$___X_CMD_PKG_VERSION.tar.gz"
-    local file_hash_path="$___X_CMD_PKG_ROOT_PATH/${___X_CMD_PKG_VERSION}_hash.txt"
-    local tmp_file_path="$___X_CMD_PKG_SHARED/$___X_CMD_PKG_VERSION.tar.gz"
-    local tmp_file_hash_path="$___X_CMD_PKG_SHARED/${___X_CMD_PKG_VERSION}_hash.txt"
+___x_cmd_pkg_update___inner()(
+    local file_path="$___X_CMD_PKG_CACHE_PATH/${___X_CMD_PKG_VERSION}.tar.gz"
+    local file_hash_path="$___X_CMD_PKG_CACHE_PATH/${___X_CMD_PKG_VERSION}_hash.txt"
+    local tmp_file_path="$___X_CMD_PKG_CACHE_PATH/${___X_CMD_PKG_VERSION}.tar.gz.tmp"
+    local tmp_file_hash_path="$___X_CMD_PKG_CACHE_PATH/${___X_CMD_PKG_VERSION}_hash.txt.tmp"
     local x_url_tar=
     local x_url_hash=
 
@@ -28,24 +28,13 @@ ___x_cmd_pkg___which_p7zip()(
 
     pkg:info --url "$x_url_hash" "Download ${___X_CMD_PKG_VERSION}_hash.txt"
     x curl -L -sS --speed-time 5 --speed-limit 100 "$x_url_hash" --output "$tmp_file_hash_path" || {
-         pkg:error "Download $___X_CMD_PKG_VERSION.tar.gz failed"
+        pkg:error "Download ${___X_CMD_PKG_VERSION}_hash.txt failed"
         return 1
     }
 
-
-    # ___x_cmd_httpget_gitx x-cmd pkg main "dist/${___X_CMD_PKG_VERSION}_hash.txt" "$tmp_file_hash_path" "-" || {
-    #     pkg:warn "Please check your network status; Or use 'x websrc set cn' and open a new session to run 'x pkg update'"
-    #     return 1
-    # }
-    # ___x_cmd_httpget_gitx x-cmd pkg main "dist/$___X_CMD_PKG_VERSION.tar.gz" "$tmp_file_path" || { # 1-day
-    #     pkg:error "Download $___X_CMD_PKG_VERSION.tar.gz failed"
-    #     return 1
-    # }
-
-
     local hash_value
     local file_hash
-    hash_value="$( < "$tmp_file_hash_path" LC_ALL="$___X_CMD_AWK_LANGUAGE" ___x_cmd_awk___inner '{print $1}')"
+    hash_value="$( < "$tmp_file_hash_path" ___x_cmd_awk___inner '{print $1}')"
     file_hash="$(x sha512 "$tmp_file_path")"
 
 
@@ -56,43 +45,39 @@ ___x_cmd_pkg___which_p7zip()(
     }
 
     ! [ -d "$___X_CMD_PKG_METADATA_PATH/tmp" ] || {
-        x rmrf "$___X_CMD_PKG_SHARED/tmp"
-        x mv "$___X_CMD_PKG_METADATA_PATH/tmp" "$___X_CMD_PKG_SHARED"
+        x rmrf "$___X_CMD_PKG_CACHE_PATH/tmp"
+        x mv "$___X_CMD_PKG_METADATA_PATH/tmp" "$___X_CMD_PKG_CACHE_PATH"
     }
 
-    x rmrf "$___X_CMD_PKG_ROOT_PATH/$___X_CMD_PKG_VERSION.tar.gz" && x rmrf "$___X_CMD_PKG_METADATA_PATH" && x rmrf "$file_hash_path"
+    x rmrf "$file_path" "$file_hash_path"
+    x mv "$tmp_file_path" "$file_path"
+    x mv "$tmp_file_hash_path" "$file_hash_path"
 
-    x cp "$tmp_file_path" "$___X_CMD_PKG_ROOT_PATH/$___X_CMD_PKG_VERSION.tar.gz" && x rmrf "$tmp_file_path"
-    x cp "$tmp_file_hash_path" "$file_hash_path" && x rmrf "$tmp_file_path" "$tmp_file_hash_path"
-
-    ___x_cmd_mkdirp "$___X_CMD_PKG_METADATA_PATH"
-    pkg:debug --tgt "$___X_CMD_PKG_METADATA_PATH"
-    pkg:debug "Deflate the $___X_CMD_PKG_VERSION.tar.gz"
-    if ! ( x cd "${file_path%/*}" && x cp "$___X_CMD_PKG_VERSION.tar.gz" metadata/"$___X_CMD_PKG_VERSION.tar.gz" && x cd metadata && x uz "$___X_CMD_PKG_VERSION.tar.gz" 1>/dev/null && x rmrf "$___X_CMD_PKG_VERSION.tar.gz" ); then
-        pkg:error "Deflation failure."
+    x rmrf "$___X_CMD_PKG_METADATA_PATH"
+    x mkdirp "$___X_CMD_PKG_METADATA_PATH"
+    pkg:debug --tgt "$___X_CMD_PKG_METADATA_PATH" "Deflate the $file_path"
+    ( ___x_cmd_inner_cd "$___X_CMD_PKG_METADATA_PATH" && x uz "$file_path" ) || {
+        pkg:error "Deflation $file_path failure."
         return 1
-    fi
+    }
 
-    ! [ -d "$___X_CMD_PKG_SHARED/tmp" ] || x mv "$___X_CMD_PKG_SHARED/tmp" "$___X_CMD_PKG_METADATA_PATH"
+    ! [ -d "$___X_CMD_PKG_CACHE_PATH/tmp" ] || x mv "$___X_CMD_PKG_CACHE_PATH/tmp" "$___X_CMD_PKG_METADATA_PATH"
 )
 
+# 86400
+___x_cmd_pkg_update___check(){
+    [ -d "$___X_CMD_PKG_METADATA_PATH" ] || x fslock run pkg_update_check ___x_cmd_pkg_update___check_inner
+}
+
+___x_cmd_pkg_update___check_inner(){
+    [ -d "$___X_CMD_PKG_METADATA_PATH" ] || ___x_cmd_pkg_update___inner
+}
 
 ___x_cmd_pkg_update(){
-    case "$1" in
-        -h|--help)
-            M='pkg update' help:ret:0
-            ;;
-    esac
-    # local file_hash_path="$___X_CMD_PKG_ROOT_PATH/${___X_CMD_PKG_VERSION}_hash.txt"
-    # x rmrf "$___X_CMD_PKG_ROOT_PATH/$___X_CMD_PKG_VERSION.tar.gz" && x rmrf "$___X_CMD_PKG_METADATA_PATH" && x rmrf "$file_hash_path"
-    ___x_cmd_pkg___which_p7zip || {
+    local X_help_cmd='x help -m pkg update'; help:arg:parse
+    ___x_cmd_pkg_update___inner || {
         pkg:error "Update the $___X_CMD_PKG_VERSION.tar.gz failed"
         return 1 # Force Update
     }
     pkg:info "Update the $___X_CMD_PKG_VERSION.tar.gz success"
-}
-
-___x_cmd_pkg_help(){
-    x help -m pkg "$@"  >&2
-    return 1
 }
diff --git a/mod/pkg/lib/mutate/download b/mod/pkg/lib/mutate/download
--- a/mod/pkg/lib/mutate/download
+++ b/mod/pkg/lib/mutate/download
@@ -5,7 +5,7 @@
 # TODO: Maybe using a P2P share connection for mirror downloading.
 ___x_cmd_pkg_download(){
     x:trace pkg/download
-    local X_help_cmd='___x_cmd_pkg_help download';   help:arg-null:parse
+    local X_help_cmd='x help -m pkg download';   help:arg-null:parse
 
     case "$1" in
         */*)
@@ -13,49 +13,24 @@ ___x_cmd_pkg_download(){
             return
             ;;
     esac
-    ___x_cmd_pkg_prepare "$@" || return
-    ___x_cmd_pkg___download "$@"
+    ___x_cmd_pkg_download___inner "$@"
 }
 
 
-___x_cmd_pkg___download(){
-
-    local name="${1}"
-    [ -n "$name" ] || M='Provide a package name' N=pkg log:ret:1
-    local osarch="${3:-$(___x_cmd_pkg_osarch)}"
-    local version="${2:-$(___x_cmd_pkg_default_version "$name" "$osarch")}" || return
+___x_cmd_pkg_download___inner(){
+    local name="$1";    [ -n "$name" ] || N=pkg M="Provide a package name" log:ret:1
+    local osarch="$3";  [ -n "$osarch" ] || { ___x_cmd_pkg_osarch_ || return 1; osarch="$___X_CMD_PKG_OSARCH"; } || N=pkg M="Not found osarch" log:ret:1
+    local version="$2"; [ -n "$version" ] || {
+        local x_=; ___x_cmd_pkg_default_version_ "$name" "$osarch";
+        version="$x_";
+    }
     [ -n "$version" ] || {
         pkg:warn "Not found candidate => $name"
         pkg:warn "Please use 'x pkg update' and 'x pkg ll' to check available candidate"
         return 1
     }
 
-    local download_file_ext=; local md5= ; local sha1= ; local sha256=; local sha512=;
-    local unpack=; local npm=; local npmurl_cn=; local npmurl_internet=; local url_cn=; local url_internet=
-    ___x_cmd_pkg___attr "$name" "$version" "$osarch" "md5,sha1,sha256,sha512,download_file_ext,unpack,npm,url.${___X_CMD_WEBSRC_REGION:-internet},npmurl.${___X_CMD_WEBSRC_REGION:-internet}" || return
-    [ -n "$unpack" ] || {
-        pkg:debug "Skip download"
-        return 0
-    }
-    local os="${osarch%/*}";  local arch="${osarch#*/}"
-    if [ "$unpack" = "none" ] && [ -z "$download_file_ext" ]; then
-        local ball="$___X_CMD_PKG_DOWNLOAD_PATH/$name/$name.${os}.${arch}"
-    else
-        if [ "$___X_CMD_WEBSRC_REGION" = "cn" ] && [ "$npm" = "yes" ];then
-            local ball="$___X_CMD_PKG_DOWNLOAD_PATH/$name/${version}_${os}_${arch}.tgz"
-        else
-            local ball="$___X_CMD_PKG_DOWNLOAD_PATH/$name/${version}_${os}_${arch}.$download_file_ext"
-        fi
-    fi
-
-
-    x mkdirp "$___X_CMD_PKG_DOWNLOAD_PATH/$name" || {
-        pkg:error "Create $___X_CMD_PKG_DOWNLOAD_PATH/$name failed" ; return 1
-    }
-
-    ( x fslock run "pkg_download_${name}_${version}_${os}_${arch}" ___x_cmd_pkg_download___inner_ "$name" "$version" "$osarch" "$ball" )
-
-    [ -f "$ball" ]
+    x fslock run "pkg_${name}_${version}_${osarch}" ___x_cmd_pkg_download___inner_ "$name" "$version" "$osarch"
 }
 
 # ___X_CMD_PKG_DOWNLOAD_SOURCE=
@@ -65,15 +40,34 @@ ___x_cmd_pkg___download(){
 # npm
 
 ___x_cmd_pkg_download___inner_(){
-    pkg:debug --Download name "$name" --version "$version" --ball "$ball"
+    local name="$1";    local version="$2";     local osarch="$3"
+    local download_file_ext=; local md5= ; local sha1= ; local sha256=; local sha512=;
+    local unpack=; local npm=; local npmurl_cn=; local npmurl_internet=; local url_cn=; local url_internet=
+    ___x_cmd_pkg___attr "$name" "$version" "$osarch" "md5,sha1,sha256,sha512,download_file_ext,unpack,npm,url.${___X_CMD_WEBSRC_REGION:-internet},npmurl.${___X_CMD_WEBSRC_REGION:-internet}" || return
+    [ -n "$unpack" ] || {
+        pkg:debug "Skip download"
+        return 0
+    }
+    local os="${osarch%/*}";  local arch="${osarch#*/}"; local ball
+    if [ "$unpack" = "none" ] && [ -z "$download_file_ext" ]; then
+        ball="$___X_CMD_PKG_DOWNLOAD_PATH/$name/$name.${os}.${arch}"
+    else
+        ball="$___X_CMD_PKG_DOWNLOAD_PATH/$name/${version}_${os}_${arch}.$download_file_ext"
+    fi
+
+
+    x mkdirp "$___X_CMD_PKG_DOWNLOAD_PATH/$name" || {
+        pkg:error "Create $___X_CMD_PKG_DOWNLOAD_PATH/$name failed" ; return 1
+    }
+
+    pkg:info "Trying download ==> '$name $version'"
     if [ -f "$ball" ]; then
         if ___x_cmd_pkg_download___check_hashsum "$ball" "$md5" "$sha1" "$sha256" "$sha512"; then
-            pkg:info "File already downloaded: $ball"
+            pkg:info "File already downloaded => $ball"
             return 0
         fi
 
-        pkg:warn "File corrupted. Download the $ball again."
-        x rmrf "$ball"
+        pkg:warn "Download the $ball again"
     fi
 
     local url_strategy=npm
@@ -89,6 +83,7 @@ ___x_cmd_pkg_download___inner_(){
 
     local url=
     if [ "$url_strategy" = npm ] && [ "$npm" = yes ]; then
+        ball="$___X_CMD_PKG_DOWNLOAD_PATH/$name/${version}_${os}_${arch}.tgz"
         eval url="\$npmurl_${___X_CMD_WEBSRC_REGION:-internet}"
     else
         eval url="\$url_${___X_CMD_WEBSRC_REGION:-internet}"
@@ -105,13 +100,13 @@ ___x_cmd_pkg_download___inner_(){
         --url "$url" --destination "$ball" --name "$name" --version "$version"
 
     x curl -I "$url" | {
-        trap 'x pkg remove $name $version 2>/dev/null; printf "\r\n";  pkg:error "Download interrupted"; return 1 || exit 1;' INT
+        trap 'printf "\r\n"; pkg:error "Download interrupted"; ___x_cmd_pkg_sphere_gc_remove___ball $name $version $osarch; return 130;' INT
         read -r head;
         head="${head#* }"; head="${head%% *}"
         case "$head" in
             2??|3??)
                 if ! x curl --progress-bar --location --retry-max-time 10 --retry 0 "$url" --output "$ball"; then
-                    pkg:warn "Fail to download from $url"
+                    pkg:error "Fail to download from $url"
                     x rmrf "$ball"
                     return 1
                 fi
@@ -122,21 +117,18 @@ ___x_cmd_pkg_download___inner_(){
                 return 1
                 ;;
         esac
-    }
+    } || return
 
     if [ "$url_strategy" = npm ] && [ "$npm" = yes ]; then
         local npm_package="$___X_CMD_PKG_DOWNLOAD_PATH/$name/package"
         x uz "$ball"  "$___X_CMD_PKG_DOWNLOAD_PATH/$name" || M='Unzip npm package failed' N=pkg log:ret:1
-        x mv "$npm_package/bin/"* "$___X_CMD_PKG_DOWNLOAD_PATH/$name/" ||  M='Move npm package failed' N=pkg log:ret:1
+        local x_=; x fsiter --file01_ "$npm_package/dist" || return
+        x mv "$npm_package/dist/$x_" "$___X_CMD_PKG_DOWNLOAD_PATH/$name" ||  M='Move npm package failed' N=pkg log:ret:1
         x rmrf "$ball" "$npm_package" || M='Remove npm package failed' N=pkg log:ret:1
         ball="$___X_CMD_PKG_DOWNLOAD_PATH/$name/${version}_${os}_${arch}.$download_file_ext"
     fi
 
-    ! ___x_cmd_pkg_download___check_hashsum "$ball" "$md5" "$sha1" "$sha256" "$sha512" || return 0
-    pkg:error "File corrupted."
-    x rmrf "$ball"
-    return 1
-
+    ___x_cmd_pkg_download___check_hashsum "$ball" "$md5" "$sha1" "$sha256" "$sha512"
 }
 
 ___x_cmd_pkg_download___check_hashsum(){
@@ -149,31 +141,40 @@ ___x_cmd_pkg_download___check_hashsum(){
     [ -z "$5" ]  ||   sha="$(___x_cmd_sha512    "$filepath")"
 
     [ "$sha" = "$2$3$4$5" ]  ||  {
-        pkg:warn "Except: " "$2$3$4$5"  " equal to "  "${sha%% *}"
+        pkg:warn "Except: [$2$3$4$5] equal to [${sha%% *}]"
+        pkg:error "File corrupted"
+        x rmrf "$filepath"
         return 1
     }
     return 0
 }
 
 
+# <name> <version>
+# <yml dir path> <name> <version>
 ___x_cmd_pkg___appoint(){
-    local yml_file="${1}"
-    [ -n "$yml_file" ] || M='Provide a folder path' N=pkg log:ret:1
-    local meta_input="$yml_file/meta.yml"; local meta_output="$yml_file/meta.tt.json"
-    local version_intput="$yml_file/version.yml"; local version_output="$yml_file/version.tt.json"
-    local name="${yml_file##*/}"
-    local CUSTOMIZE_PKG_PATH
-    local CUSTOMIZE_PKG_NAME
+    pkg:sphere:parse:option
+    sphere_name="${sphere_name:-"X"}"
 
-    CUSTOMIZE_PKG_NAME="$name"
-    CUSTOMIZE_PKG_PATH="tmp/$name"
+    local yml_dir="${1}"
+    [ -d "$yml_dir" ] || M='Provide a folder path' N=pkg log:ret:1
+    local meta_input="$yml_dir/meta.yml";           local meta_output="$yml_dir/meta.tt.json"
+    local version_intput="$yml_dir/version.yml";    local version_output="$yml_dir/version.tt.json"
+    local name="${yml_dir##*/}"
+    local CUSTOMIZE_PKG_NAME="$name"
+    local CUSTOMIZE_PKG_PATH="tmp/$name"
 
-    x ccmd --convert "$meta_input" "$meta_output" eval  "___x_cmd_pkg___appoint_handle_data \"\$meta_input\" \"\$meta_output\""
-    x ccmd --convert "$version_intput" "$version_output" eval  "___x_cmd_pkg___appoint_handle_data \"\$version_intput\" \"\$version_output\""
+    x ccmd --convert "$meta_input" "$meta_output"           eval "___x_cmd_pkg___appoint_handle_data \"\$meta_input\" \"\$meta_output\""
+    x ccmd --convert "$version_intput" "$version_output"    eval "___x_cmd_pkg___appoint_handle_data \"\$version_intput\" \"\$version_output\""
 
-    ___x_cmd_pkg___tmp_move "$yml_file" "$meta_output" "$version_output"
+    ___x_cmd_pkg___tmp_move "$yml_dir" "$meta_output" "$version_output"
+    # Use add
+    ___x_cmd_pkg_sphere_add --prebuild --protection use --reason "use,appoint"      \
+        --sphere "$sphere_name" --sphereroot "$___X_CMD_PKG_ROOT_SPHERE"    \
+        --osarch "$osarch" "$name" "$version"
+
     ___x_cmd_pkg___download "$name" || return
-    ___x_cmd_pkg_populate "$name" || return
+    ___x_cmd_pkg_sphere_populate_run "$name" || return
     pkg:info "Download and populate $name successfully"
 }
 
@@ -191,8 +192,8 @@ ___x_cmd_pkg___appoint_handle_data(){
 
 
 ___x_cmd_pkg___tmp_move(){
-    local yml_file="$1"
-    local name="${yml_file##*/}"
+    local yml_dir="$1"
+    local name="${yml_dir##*/}"
     local meta_j_path="$2"
     local version_j_path="$3"
     x mkdirp "$___X_CMD_PKG_METADATA_PATH/tmp/$name"
@@ -200,7 +201,7 @@ ___x_cmd_pkg___tmp_move(){
     x cp "$version_j_path" "$___X_CMD_PKG_METADATA_PATH/tmp/$name"
 
     x mkdirp "$___X_CMD_PKG_METADATA_PATH/tmp/$name/.x-cmd"
-    ! [ -d "$yml_file/.x-cmd" ] || x cp "$yml_file/.x-cmd/"* "$___X_CMD_PKG_METADATA_PATH/tmp/$name/.x-cmd"
+    ! [ -d "$yml_dir/.x-cmd" ] || x cp "$yml_dir/.x-cmd/"* "$___X_CMD_PKG_METADATA_PATH/tmp/$name/.x-cmd"
     x rmrf "$meta_j_path" "$version_j_path"
 
 }
diff --git a/mod/pkg/lib/sphere/link b/mod/pkg/lib/sphere/link
--- a/mod/pkg/lib/sphere/link
+++ b/mod/pkg/lib/sphere/link
@@ -2,78 +2,149 @@
 
 # add: link a package to sphere
 # rm:
-___x_cmd_pkg_link() {
-    local X_help_cmd='___x_cmd_pkg_help link';   help:arg-null:parse
-    sphere:parse:args
-    ___x_cmd_pkg_sphere_link --sphere "$sphere_name" --sphereroot "$___X_CMD_PKG_ROOT_SPHERE" add "$name" "$version" "$osarch"
-}
 
-___x_cmd_pkg_unlink(){
-    local X_help_cmd='___x_cmd_pkg_help unlink';   help:arg-null:parse
-    sphere:parse:args
-    ___x_cmd_pkg_sphere_link --sphere "$sphere_name" --sphereroot "$___X_CMD_PKG_ROOT_SPHERE" rm "$name" "$version" "$osarch"
-}
-
-
-# x pkg sphere link --name X rm <pkg> <version>
+# x pkg sphere link add --sphere X <pkg> <version>
 ___x_cmd_pkg_sphere_link(){
-    sphere:parse:option
-    sphere_name="${sphere_name:-"X"}"
-
-    local op="$1";  shift
+    local op="$1"
     case "$op" in
-        exist)      ___x_cmd_pkg_sphere_link_exist "$@"     ;;
-        rm|add)     x fslock run "pkg_sphere_link_${sphere_name}_${1}_${2}" \
-                        ___x_cmd_pkg_sphere_link_"$op" "$@" ;;
-        *)          N=pkg M="sphere link no such option '$op'" log:ret:1
-                    ;;
+        rm|add|exist|ls)
+                shift; ___x_cmd_pkg_sphere_link_"$op" "$@" ;;
+        *)      N=pkg M="sphere link no such option '$op'" log:ret:1
+                ;;
     esac
 }
 
-
+# Section: link add
 ___x_cmd_pkg_sphere_link_add(){
-    local name="$1";        [ -n "$name" ] || N=pkg M="Provide a package name" log:ret:1
-    local version="$2";     [ -n "$version" ] || N=pkg M="Not found $name version" log:ret:1
-    local osarch="$3";      [ -n "$osarch" ] || N=pkg M="Not found osarch value" log:ret:1
+    local sphere_name=; local osarch=; local sociality=
+    while [ "$#" -gt 0 ]; do
+        case "$1" in
+            --sphere)
+                    sphere_name="$2";
+                    [ -n "$sphere_name" ] || M="Provide a sphere name" N=pkg log:ret:1
+                    shift 2
+                    ;;
+            --sphereroot)
+                    local ___X_CMD_PKG_ROOT_SPHERE="$2"
+                    [ -n "$___X_CMD_PKG_ROOT_SPHERE" ] || M="Provide sphere root path" N=pkg log:ret:1
+                    shift 2
+                    ;;
+            --osarch)
+                    osarch="$2";    shift 2 ;;
+            --sociality)
+                    sociality="$2"; shift 2 ;;
+            *)      break ;;
+        esac
+    done
+    [ -n "$osarch" ] || { ___x_cmd_pkg_osarch_ || return 1; osarch="$___X_CMD_PKG_OSARCH"; } || N=pkg M="Not found osarch" log:ret:1
 
+    pkg:sphere:name-version
+    [ -n "$sociality" ] || {
+        local x_="" >/dev/null 2>&1; ___x_cmd_pkg_sphere_sociality___get_       \
+            --sphere "$sphere_name" --sphereroot "$___X_CMD_PKG_ROOT_SPHERE"    \
+            --osarch "$osarch" "$name" "$version" || return
+        sociality="$x_"
+    }
+
+    x fslock run "pkg_sphere_link_${sphere_name}_${name}_${version}" ___x_cmd_pkg_sphere_link_add___run
+
+    if [ "$sociality" = intrusive ] || [ "$sociality" = dev ]; then
+        pkg:info "Loading boot script file of $name $version"
+        ___x_cmd_pkg_sphere_boot    \
+            --sphere "$sphere_name" --sphereroot "$___X_CMD_PKG_ROOT_SPHERE"    \
+            --osarch "$osarch" "$name" "$version" || return
+    fi
+
+    pkg:info "Recording bootrc of $name $version"
+    ___x_cmd_pkg_sphere_bootrc add  \
+        --sphere "$sphere_name" --sphereroot "$___X_CMD_PKG_ROOT_SPHERE"    \
+        --osarch "$osarch" --sociality "$sociality" "$name" "$version"
+}
+
+___x_cmd_pkg_sphere_link_add___run(){
     local x_treename=; ___x_cmd_pkg_treename_ "$name" "$version" "$osarch" || return
-    pkg:debug --sphere_path "$___X_CMD_PKG_ROOT_SPHERE/$sphere_name" --pkg "$name" --version "$version" "link add"
-    local target_dir="$___X_CMD_PKG_ROOT_SPHERE/$sphere_name/l/j/h/bin"
+    local target_dir="$___X_CMD_PKG_ROOT_SPHERE/$sphere_name/l/j/h"
     local tgt="$___X_CMD_PKG_ROOT_SPHERE/$sphere_name/$x_treename/$name/$version"
-    local link_dir="$___X_CMD_PKG_ROOT_SPHERE/$sphere_name/.x-cmd/link_record"
-    local link_file="$link_dir/${name}_${version}"
-    [ ! -f "$link_file" ] || return 0
-    x ensurefp "$link_file"
+    local link_dir="$___X_CMD_PKG_ROOT_SPHERE/$sphere_name/.x-cmd/link/${name}_${version}"
 
-    local target=; local bin_file
-    ___x_cmd_pkg_sphere_link___list_all_bin_path "$name" "$version" "$osarch" "$tgt" | while read -r bin_file; do
-        [ -n "$bin_file" ] || continue
-        [ -f "$bin_file" ] || {
-            pkg:error "Not found $bin_file for $name $version bin link"
-            return 1
-        }
+    pkg:info --target_dir "$target_dir" "Trying to link $name $version of the bin/ lib/ man/ file"
 
-        target="$target_dir/${bin_file##*/}"
-        pkg:debug "linking source=$bin_file target=$target"
+    ___x_cmd_pkg_sphere_link_add___run_inner "$name" "$version" "$osarch" "$tgt" bin "$target_dir" "$link_dir" "$link_sociality" || return
+    ___x_cmd_pkg_sphere_link_add___run_inner "$name" "$version" "$osarch" "$tgt" lib "$target_dir" "$link_dir" "$link_sociality" || return
+    ___x_cmd_pkg_sphere_link_add___run_inner_man "$name" "$version" "$osarch" "$tgt" "$target_dir" "$link_dir" "$link_sociality" || return
 
-        command ln -s -f "$bin_file" "$target" || N=pkg M="ln - Operation failure source=$bin_file target=$target" log:ret:1
-        printf "%s\n" "$target" >> "$link_file"
-    done || return
-
-
-    ___x_cmd_path_add_existed_folder "$target_dir" || return
     pkg:info "Successfully set link from path"
 }
 
-___x_cmd_pkg_sphere_link_rm(){
-    local name="$1";    local version="$2";
-    shift 2
+___x_cmd_pkg_sphere_link_add___run_inner(){
+    local name="$1";    local version="$2";    local osarch="$3";   local tgt="$4";
+    local _path="${5:-bin}";    local target_dir="$6";   local link_dir="$7"; local sociality="$8"
+    local link_file="$link_dir/association"
+    [ ! -f "$link_file" ] || {
+        pkg:debug "$name $version has already linked"
+        return 0
+    }
+    x ensurefp "$link_file"
+    local file; local target;
+    ___x_cmd_pkg_sphere_link___list_all_path_expand "$name" "$version" "$osarch" "$tgt" "$_path" "$sociality" | while read -r file; do
+        [ -n "$file" ] || continue
+        [ -e "$file" ] || {
+            pkg:error "Not found $file to $name $version link $_path"
+            x rmrf "$link_file"
+            return 1
+        }
+        target="$target_dir/$_path/${file##*/}"
+        x ensurefp "$target"
+        pkg:debug "linking source=$file target=$target"
+        command ln -s -f "$file" "$target" || N=pkg M="ln - Operation failure source=$file target=$target" log:ret:1
+        printf "%s\n" "$target" >> "$link_file"
+    done
+}
 
-    pkg:debug --sphere_path "$___X_CMD_PKG_ROOT_SPHERE/$sphere_name" --pkg "$name" --version "$version" "link rm"
-    local link_dir="$___X_CMD_PKG_ROOT_SPHERE/$sphere_name/.x-cmd/link_record"
-    local link_file="$link_dir/${name}_${version}"
+___x_cmd_pkg_sphere_link_add___run_inner_man(){
+    local name="$1";    local version="$2";    local osarch="$3";   local tgt="$4";
+    local target_dir="$5";   local link_dir="$6";  local sociality="$7"
+    local link_file="$link_dir/association"
+    [ ! -f "$link_file" ] || {
+        pkg:debug "$name $version has already linked"
+        return 0
+    }
+    x ensurefp "$link_file"
+    local mandir; local target; local file; local filename
+    ___x_cmd_pkg_sphere_link___list_all_path_expand "$name" "$version" "$osarch" "$tgt" "man" "$sociality" | while read -r mandir; do
+        [ -n "$mandir" ] || continue
+        [ -d "$mandir" ] || {
+            pkg:warn "Invalid manpath[$mandir] for $name $version"
+            continue
+        }
+
+        x fsiter "$mandir" | while read -r filename; do
+            case "$filename" in
+                *.[1-9]|*.gz) target="$target_dir/man/${mandir##*/}/$filename" ;;
+                *) continue ;;
+            esac
+            file="$mandir/$filename"
+            x ensurefp "$target"
+            pkg:debug "linking source=$file target=$target"
+            command ln -s -f "$file" "$target" || N=pkg M="ln - Operation failure source=$file target=$target" log:ret:1
+            printf "%s\n" "$target" >> "$link_file"
+        done
+    done
+}
+
+# EndSection
+
+# Section: link rm
+___x_cmd_pkg_sphere_link_rm(){
+    pkg:sphere:parse:args
+    x fslock run "pkg_sphere_link_${sphere_name}_${name}_${version}" ___x_cmd_pkg_sphere_link_rm___run
+}
+___x_cmd_pkg_sphere_link_rm___run(){
+    local link_dir="$___X_CMD_PKG_ROOT_SPHERE/$sphere_name/.x-cmd/link/${name}_${version}"
+    local link_file="$link_dir/association"
     [ -f "$link_file" ] || return 0
 
+    pkg:info "Trying to unlink $name $version of the bin/ lib/ man/ file"
     local target
     while read -r target;do
         [ -f "$target" ] || continue
@@ -82,35 +153,74 @@ ___x_cmd_pkg_sphere_link_rm(){
     done < "$link_file"
 
     x rmrf "$link_file"
+
+    if [ "$sociality" = intrusive ] || [ "$sociality" = dev ]; then
+        pkg:info "Loading unboot script file of $name $version"
+        ___x_cmd_pkg_sphere_boot    \
+            --sphere "$sphere_name" --sphereroot "$___X_CMD_PKG_ROOT_SPHERE"    \
+            --osarch "$osarch" "$name" "$version" || return
+    fi
+
+    pkg:info "Removing bootrc of $name $version"
+    ___x_cmd_pkg_sphere_bootrc rm   \
+        --sphere "$sphere_name" --sphereroot "$___X_CMD_PKG_ROOT_SPHERE"    \
+        --osarch "$osarch" "$name"
 }
 
-___x_cmd_pkg_sphere_link_exist(){
-    local name="$1";    local version="$2";
-    shift 2
+# EndSection
 
-    local link_dir="$___X_CMD_PKG_ROOT_SPHERE/$sphere_name/.x-cmd/link_record"
-    local link_file="$link_dir/${name}_${version}"
+___x_cmd_pkg_sphere_link_exist(){
+    pkg:sphere:parse:args
+    local link_dir="$___X_CMD_PKG_ROOT_SPHERE/$sphere_name/.x-cmd/link/${name}_${version}"
+    local link_file="$link_dir/association"
     [ -f "$link_file" ]
 }
 
-___x_cmd_pkg_sphere_link___list_all_bin_path() {
-    local name="$1";    local version="$2";    local osarch="$3";   local tgt="$4"
-
-    # TIP: use default osarch
-    local bin_dir; local bin_name
-    ___x_cmd_pkg___list "$name" "$version" "$osarch" "path.bin" | while read -r bin_dir; do
-        [ -n "$bin_dir" ] || continue
-        bin_dir="$tgt/$bin_dir"
-
-        if [ -d "$bin_dir" ]; then
-            x fsiter "$bin_dir" | while read -r bin_name; do
-                [ -n "$bin_name" ] || continue
-                [ -f "$bin_dir/$bin_name" ] || continue
-                printf "%s\n" "$bin_dir/$bin_name"
-            done
-        else
-            printf "%s\n" "$bin_dir"
-        fi
+___x_cmd_pkg_sphere_link_ls(){
+    pkg:sphere:parse:option
+    sphere_name="${sphere_name:-"X"}"
+    local link_dir="$___X_CMD_PKG_ROOT_SPHERE/$sphere_name/.x-cmd/link"
+    [ -d "$link_dir" ] || return 0
+    local i; for i in "$link_dir"/*; do
+        [ ! -f "$i/association" ] || printf "%s\n" "$i"
     done
 }
 
+___x_cmd_pkg_sphere_link___list_all_path_dir(){
+    local name="$1";    local version="$2";    local osarch="$3";   local tgt="$4";
+    local _path="${5:-bin}";    local sociality="$6"
+    [ -n "$sociality" ] || {
+        local x_=; ___x_cmd_pkg_sphere_sociality get_ "$name" "$version" "$osarch" || return
+        sociality="$x_"
+    }
+
+    local path_dir
+    ___x_cmd_pkg___list "$name" "$version" "$osarch" "path.$_path" | while read -r path_dir; do
+        [ -n "$path_dir" ] || continue
+
+        case "$path_dir" in
+            shim_bin)
+                path_dir="$tgt/shim_bin"
+                [ ! -d "$tgt/adaptive_shim_bin" ] || { [ "$sociality" != adaptive ] && [ "$sociality" != dev ]; } || path_dir="$tgt/adaptive_shim_bin"
+                ;;
+            \.) path_dir="$tgt" ;;
+            *)  path_dir="$tgt/$path_dir";;
+        esac
+
+        printf "%s\n" "$path_dir"
+    done
+}
+
+___x_cmd_pkg_sphere_link___list_all_path_expand(){
+    local path_dir=; local filename=
+    ___x_cmd_pkg_sphere_link___list_all_path_dir "$@" | while read -r path_dir; do
+        [ -d "$path_dir" ] || {
+            pkg:warn "Not found $path_dir directory"
+            continue
+        }
+
+        x fsiter "$path_dir" | while read -r filename; do
+            [ -z "$filename" ] || printf "%s\n" "$path_dir/$filename"
+        done
+    done
+}
diff --git a/mod/pkg/lib/util b/mod/pkg/lib/util
--- a/mod/pkg/lib/util
+++ b/mod/pkg/lib/util
@@ -5,45 +5,44 @@
 
 # TODO: Using file caching data
 ___x_cmd_pkg___attr(){
-    local x_=; ___x_cmd_pkg___attr_code_getrc_ "$@" || return
-    . "$x_"
-}
-
-___x_cmd_pkg___attr_code_getrc_(){
     local name="$1";    [ -n "$name" ] || N=pkg M="Provide a package name" log:ret:1
-    local version="${2:-$(___x_cmd_pkg_default_version "$name" "$osarch")}"
+    local version="$2"; [ -n "$version" ] || {
+        local x_=; ___x_cmd_pkg_default_version_ "$name" "$osarch" || return
+        version="$x_"
+    }
     [ -n "$version" ] || N=pkg M="Not found $name version" log:ret:1
     local osarch="$3"
-    [ -n "$osarch" ] || {
-        ___x_cmd_pkg_osarch_ || return
-        osarch="$___X_CMD_PKG_OSARCH"
-    } || N=pkg M="Not found osarch" log:ret:1
+    [ -n "$osarch" ] || { ___x_cmd_pkg_osarch_ || return 1; osarch="$___X_CMD_PKG_OSARCH"; } || N=pkg M="Not found osarch" log:ret:1
     local QUERY="$4";   [ -n "$QUERY" ] || N=pkg M="Provide package attr" log:ret:1
 
     local metafp="$___X_CMD_PKG_METADATA_PATH/$name/meta.tt.json"
     local versionfp="$___X_CMD_PKG_METADATA_PATH/$name/version.tt.json"
     local str="$___X_CMD_PKG_METADATA_PATH/$osarch/$___X_CMD_WEBSRC_REGION/$name/$version/${QUERY}"
-    local envfp="${___X_CMD_ROOT_CACHE}/pkg/attr/$str"
+    local envfp="$___X_CMD_ROOT_TMP/pkg/attr$str"
     pkg:debug "attr envfp => $envfp"
-    { [ "$envfp" -nt "$metafp" ] && [ "$envfp" -nt "$versionfp" ]; } || {
-        x ensurefp "$envfp"
-        {
-            ___x_cmd_pkg___all_info "$name" "$version" "$osarch" |
-            LC_ALL="$___X_CMD_AWK_LANGUAGE" command awk \
-                -v QUERY="$QUERY" \
-                -f "$___X_CMD_ROOT_MOD/awk/lib/core.awk" \
-                -f "$___X_CMD_ROOT_MOD/awk/lib/sh.awk" \
-                -f "$___X_CMD_ROOT_MOD/awk/lib/j/json.awk"   \
-                -f "$___X_CMD_ROOT_MOD/awk/lib/j/jqparse.awk" \
-                -f "$___X_CMD_ROOT_MOD/pkg/lib/awk/util.awk" \
-                -f "$___X_CMD_ROOT_MOD/pkg/lib/awk/pkg._.awk" \
-                -f "$___X_CMD_ROOT_MOD/pkg/lib/awk/pkg.attr.awk" \
-                || printf "\n%s\n" "pkg:error \"Not found $name package data\"; false;"
-        } > "$envfp"
-    }
-
+    x depend run "$envfp" -- "$metafp" "$versionfp" -- ___x_cmd_pkg___attr_code_inner "$name" "$version" "$osarch" "$QUERY" "$envfp"
     [ -f "$envfp" ] || return
-    x_="$envfp"
+    . "$envfp"
+}
+
+# TODO: use depend mod
+___x_cmd_pkg___attr_code_inner(){
+    local name="$1";    local version="$2";     local osarch="$3";
+    local QUERY="$4";   local envfp="$5"
+    x ensurefp "$envfp"
+    {
+        ___x_cmd_pkg___all_info "$name" "$version" "$osarch" |
+        LC_ALL="$___X_CMD_AWK_LANGUAGE" ___x_cmd_cmds_awk \
+            -v QUERY="$QUERY" \
+            -f "$___X_CMD_ROOT_MOD/awk/lib/core.awk" \
+            -f "$___X_CMD_ROOT_MOD/awk/lib/sh.awk" \
+            -f "$___X_CMD_ROOT_MOD/awk/lib/j/json.awk"   \
+            -f "$___X_CMD_ROOT_MOD/awk/lib/j/jqparse.awk" \
+            -f "$___X_CMD_ROOT_MOD/pkg/lib/awk/util.awk" \
+            -f "$___X_CMD_ROOT_MOD/pkg/lib/awk/pkg._.awk" \
+            -f "$___X_CMD_ROOT_MOD/pkg/lib/awk/pkg.attr.awk" \
+            || printf "\n%s\n" "pkg:error \"Not found $name package data\"; false;"
+    } > "$envfp"
 }
 
 # EndSection
@@ -67,7 +66,8 @@ ___x_cmd_pkg___get_script_path(){
 # Section: osarch
 ___x_cmd_pkg_osarch_(){
     if [ -z "$___X_CMD_PKG_OSARCH" ]; then
-        ___X_CMD_PKG_OSARCH="$(___x_cmd_os name)/$(___x_cmd_os arch)" || return 1
+        x os name_ || return 1;     x os arch_ || return 1
+        ___X_CMD_PKG_OSARCH="${___X_CMD_OS_NAME_}/${___X_CMD_OS_ARCH_}"
         [ -n "$___X_CMD_PKG_OSARCH" ] || return 1
     fi
 }
@@ -82,10 +82,7 @@ ___x_cmd_pkg_osarch(){
 # Section: tree name
 ___x_cmd_pkg_treename_(){
     local name="$1";    local version="$2";     local osarch="$3"
-    [ -n "$osarch" ] || {
-        ___x_cmd_pkg_osarch_ || return
-        osarch="$___X_CMD_PKG_OSARCH"
-    } || N=pkg M="Not found osarch" log:ret:1
+    [ -n "$osarch" ] || { ___x_cmd_pkg_osarch_ || return 1; osarch="$___X_CMD_PKG_OSARCH"; } || N=pkg M="Not found osarch" log:ret:1
 
     local tree=; ___x_cmd_pkg___attr "$name" "$version" "$osarch" "tree" || return
     ___x_cmd_pkg_treename_get_form_tree_ "$osarch" "$tree"
@@ -99,10 +96,7 @@ ___x_cmd_pkg_treename_get_form_tree_(){
         return
     }
 
-    [ -n "$osarch" ] || {
-        ___x_cmd_pkg_osarch_ || return
-        osarch="$___X_CMD_PKG_OSARCH"
-    } || N=pkg M="Not found osarch" log:ret:1
+    [ -n "$osarch" ] || { ___x_cmd_pkg_osarch_ || return 1; osarch="$___X_CMD_PKG_OSARCH"; } || N=pkg M="Not found osarch" log:ret:1
 
     # default
     local os="${osarch%%/*}"
@@ -119,7 +113,7 @@ ___x_cmd_pkg_treename_get_form_tree_(){
 # Section: get raw text from all.7z
 ___x_cmd_pkg_locate(){
     local tgt="${1:?Provide name}"
-    ___x_cmd_pkg_ll_inner | command awk -v FS=/ -v RS="\t" -v tgt="$tgt" '$2==tgt{ TGT=1; print $0 } { if(TGT>0){exit(1)}} END{{exit(0)}}'
+    ___x_cmd_pkg_ll_inner | ___x_cmd_cmds_awk -v FS=/ -v RS="\t" -v tgt="$tgt" '$2==tgt{ TGT=1; print $0 } { if(TGT>0){exit(1)}} END{{exit(0)}}'
 }
 
 # Default, China
@@ -128,12 +122,8 @@ ___x_cmd_pkg___all_info(){
         --non-version) local version_json=--non-version; shift ;;
     esac
     local name="$1";    [ -n "$name" ] || N=pkg M="Provide a package name" log:ret:1
+    local osarch="$3";  [ -n "$osarch" ] || { ___x_cmd_pkg_osarch_ || return 1; osarch="$___X_CMD_PKG_OSARCH"; } || N=pkg M="Not found osarch" log:ret:1
     local version="${2:-""}"
-    local osarch="$3"
-    [ -n "$osarch" ] || {
-        ___x_cmd_pkg_osarch_ || return
-        osarch="$___X_CMD_PKG_OSARCH"
-    } || N=pkg M="Not found osarch" log:ret:1
 
     if [ "$name" = "$CUSTOMIZE_PKG_NAME" ]; then
         name="$CUSTOMIZE_PKG_PATH"
@@ -145,11 +135,11 @@ ___x_cmd_pkg___all_info(){
     # pkg:debug --name "$name"  --version "$version" --osarch "$osarch"  --___X_CMD_PKG_METADATA_PATH "$___X_CMD_PKG_METADATA_PATH" --___X_CMD_WEBSRC_REGION "$___X_CMD_WEBSRC_REGION" "all info"
     printf "%s\n%s\n%s\n%s\n%s\n" "$name" "$version" "$osarch" "$___X_CMD_PKG_METADATA_PATH" "$___X_CMD_WEBSRC_REGION"
 
-    cat "$___X_CMD_PKG_METADATA_PATH/$name/meta.tt.json" 2>/dev/null || N=pkg M="Not found $name meta.tt.json" log:ret:1
+    ___x_cmd_cmds_cat "$___X_CMD_PKG_METADATA_PATH/$name/meta.tt.json" 2>/dev/null || N=pkg M="Not found $name meta.tt.json" log:ret:1
     printf "\n"
 
     if [ -z "$version_json" ]; then
-        cat "$___X_CMD_PKG_METADATA_PATH/$name/version.tt.json" 2>/dev/null || N=pkg M="Not found $name version.tt.json" log:ret:1
+        ___x_cmd_cmds_cat "$___X_CMD_PKG_METADATA_PATH/$name/version.tt.json" 2>/dev/null || N=pkg M="Not found $name version.tt.json" log:ret:1
     else
         printf "\n"
     fi
@@ -169,29 +159,38 @@ ___x_cmd_pkg___list(){
         -f "$___X_CMD_ROOT_MOD/pkg/lib/awk/pkg.list.awk"
 }
 
-
 ___x_cmd_pkg_default_version(){
+    local x_=; ___x_cmd_pkg_default_version_ "$@" || return
+    printf "%s\n" "$x_"
+}
 
-    case "$1" in
-        -h|--help)
-            ___x_cmd_pkg_help default_version
-            return 1
-            ;;
-    esac
+___x_cmd_pkg_default_version_(){
+    local X_help_cmd='x help -m pkg default_version'; help:arg:parse
+    local name="$1";    [ -n "$name" ] || N=pkg M="Provide a package name" log:ret:1
+    local osarch="$2";  [ -n "$osarch" ] || { ___x_cmd_pkg_osarch_ || return 1; osarch="$___X_CMD_PKG_OSARCH"; } || N=pkg M="Not found osarch" log:ret:1
 
-    local name="${1}"
-    [ -n "$name" ] || M='Provide a package name' N=pkg log:ret:1
-    local osarch="${2:-$(___x_cmd_pkg_osarch)}"
+    local metafp="$___X_CMD_PKG_METADATA_PATH/$name/meta.tt.json"
+    local versionfp="$___X_CMD_PKG_METADATA_PATH/$name/version.tt.json"
+    local str="$___X_CMD_PKG_METADATA_PATH/$osarch/$name"
+    local envfp="$___X_CMD_ROOT_TMP/pkg/default_version_$str"
+    pkg:debug "default version envfp => $envfp"
+    x depend run "$envfp" -- "$metafp" "$versionfp" -- ___x_cmd_pkg_default_version___inner "$name" "$osarch" "$envfp" || return
+    [ -f "$envfp" ] || return
+    . "$envfp"
+}
 
-    # ___x_cmd_pkg___which_p7zip 86400 || return
-    [ -f "$___X_CMD_PKG_ROOT_PATH/$___X_CMD_PKG_VERSION.tar.gz" ] || ___x_cmd_pkg_update
+___x_cmd_pkg_default_version___inner(){
+    local name="$1";    local osarch="$2";  local envfp="$3"
+
+    ___x_cmd_pkg_update___check || return
+    x ensurefp "$envfp"
     ___x_cmd_pkg___all_info --non-version "$name" "" "$osarch" | LC_ALL="$___X_CMD_AWK_LANGUAGE" ___x_cmd_awk___inner \
         -f "$___X_CMD_ROOT_MOD/awk/lib/core.awk" \
         -f "$___X_CMD_ROOT_MOD/awk/lib/j/json.awk"   \
         -f "$___X_CMD_ROOT_MOD/awk/lib/j/jqparse.awk" \
         -f "$___X_CMD_ROOT_MOD/pkg/lib/awk/util.awk" \
         -f "$___X_CMD_ROOT_MOD/pkg/lib/awk/pkg._.awk" \
-        -f "$___X_CMD_ROOT_MOD/pkg/lib/awk/pkg.default_version.awk"
+        -f "$___X_CMD_ROOT_MOD/pkg/lib/awk/pkg.default_version.awk" > "$envfp"
 }
 
 
@@ -216,23 +215,3 @@ ___x_cmd_pkg___is_support(){
     return 1
 }
 
-___x_cmd_pkg_migrate(){
-    local add_safelist=
-    while [ "$#" -gt 0 ]; do
-        case "$1" in
-            --safelist)
-                    add_safelist=1
-                    shift
-                    ;;
-            *)      break ;;
-        esac
-    done
-
-    sphere:parse:args
-    ___x_cmd_pkg_download "$name" "$version" "$osarch" || return
-    ___x_cmd_pkg_populate "$name" "$version" "$osarch" "$sphere_name" "$___X_CMD_PKG_ROOT_SPHERE" || return
-    [ -z "$add_safelist" ] || ___x_cmd_pkg_safelist add "$name" "$version" "$osarch" "$sphere_name" "$___X_CMD_PKG_ROOT_SPHERE"
-}
-___x_cmd_pkg_install(){
-    ___x_cmd_pkg_migrate "$@"
-}
