...

diff --git a/mod/co/lib/exec b/mod/co/lib/exec
--- a/mod/co/lib/exec
+++ b/mod/co/lib/exec
@@ -1,16 +1,60 @@
 # shellcheck shell=dash
+
+
 ___x_cmd_co_exec(){
+    local data
+    data="$(___x_cmd_co_exec_ "$@")" || return
+
+    # Just preserve the json data which only asked
+    data="${data#*\{}"
+    data="${data%\}*}"
+    data="{$data}"
+    ___x_cmd_co_exec_app2 "$data"
+}
+
+___x_cmd_co_exec_(){
     local LOCALSHELL=
     local OS=
-    
+
     local x_=""
     x os name_
 
-    LOCALSHELL="$___X_CMD_SHELL" OS="$x_" x chat --request --type "co" --minion "$___X_CMD_ROOT_MOD/co/lib/minion/exec.yml" "$@"
+    LOCALSHELL="$___X_CMD_SHELL" OS="$x_" ___x_cmd chat --send --type "co" --minion "$___X_CMD_ROOT_MOD/co/lib/minion/multi.yml" "$@"
 }
 
-# SHELL="$___X_CMD_SHELL" OSNAME="$___X_CMD_OSNAME" x chat --request --minion co.minion.yml --with-type-prompt "co" "$prompt" "$@"
+___x_cmd_co_exec_app1(){
+    local data="$1"
+    data="$( printf "%s\n" "$data" | ___x_cmd jo .answer | ___x_cmd jo 2c .cmd .desc )"
+    [ -n "$data" ] || N=co M="Response data format error or empty" log:ret:1
+
+    local ___X_CMD_CSV_APP_DATA_Command=
+    local ___X_CMD_CSV_APP_DATA_Description=
+    ___x_cmd csv app --header Command,Description --return var <<A
+$data
+A
+    [ -n "$___X_CMD_CSV_APP_DATA_Command" ] || return
+    co:info --desc "$___X_CMD_CSV_APP_DATA_Description" --cmd "$___X_CMD_CSV_APP_DATA_Command"
+    ___x_cmd ui yesno "Do your want to execute the above command ?" || return
+    eval "$___X_CMD_CSV_APP_DATA_Command"
+}
+
+___x_cmd_co_exec_app2(){
+    local data="$1"
+    printf "%s\n" "$data" | ___x_cmd j2y >/dev/tty || N=co M="Response data format error or empty" log:ret:1
+
+    local _cmd=
+    local _selectcmd=
+    _selectcmd="$( ___x_cmd cawk -m j/json,j/jiter -f "$___X_CMD_ROOT_MOD/co/lib/awk/gen_exec_uiselect.awk" <<A
+$data
+A
+    )" || return
+    # printf "%s\n" ""
+    x ui sep
+    eval "$_selectcmd" || return
+    [ -n "$_cmd" ] || return
+    eval "$_cmd"
 
 
-
+    # printf "%s\n" "$data" | x jo .answer.\* .cmd | x pick
+}
 
diff --git a/mod/npm/lib/main b/mod/npm/lib/main
--- a/mod/npm/lib/main
+++ b/mod/npm/lib/main
@@ -16,13 +16,22 @@ ___x_cmd_npm___main(){
 }
 
 ___x_cmd_npm___cmd(){
-    if ___x_cmd_hasbin "$1"; then
-        "$@"
-        return
-    fi
+    ___x_cmd_hasbin "$1" || {
+        ___x_cmd_is_interactive || {
+            npm:error --tip1 'x env use' --tip2 'x env try' "Npm not found."
+            return 1
+        }
 
-    x node load || return
-    local bin="$1"; shift
-    "$___X_CMD_NODE_SHIMAPP_PATH/$bin" "$@"
+        npm:info "Npm not found."
+        local cmd=
+        x ui select ,cmd  "What's next:"    \
+            "x env use node"                \
+            "x env try node"                \
+            "x install node"                \
+            "return 1"                      || return 1
+        eval "$cmd"
+    }
+
+    "$@"
 }
 
diff --git a/mod/pip/lib/main b/mod/pip/lib/main
--- a/mod/pip/lib/main
+++ b/mod/pip/lib/main
@@ -7,12 +7,6 @@ xrc:mod:lib pip     nv
 ___x_cmd_pip___main(){
     [ "$#" -gt 0 ]  ||      set - --nv
 
-    x hascmd pip ||  {
-        # TODO: install pip with UI
-        pip:warn "pip is not found."
-        return 1
-    }
-
     local op="$1";  shift
     case "$op" in
         --nv)       ___x_cmd_pip___nv        "$@" ;;
@@ -23,5 +17,19 @@ ___x_cmd_pip___main(){
 }
 
 ___x_cmd_pip___exec(){
+    ___x_cmd_hasbin pip || {
+        ___x_cmd_is_interactive || {
+            pip:error --tip1 'x env use' --tip2 'x env try' "Pip not found."
+            return 1
+        }
+
+        pip:info "Pip not found."
+        local cmd=
+        x ui select ,cmd  "What's next:"    \
+            "x env use python"              \
+            "x env try python"              \
+            "return 1"                      || return 1
+        eval "$cmd"
+    }
     ___x_cmd_cmds pip "$@"
 }
