Updating main branch using x7 release -> 237002d10f1cdf9200b3b67a1dcca0541edbc8cc

diff --git a/mod/claw/lib/qywx/_index b/mod/claw/lib/qywx/_index
--- a/mod/claw/lib/qywx/_index
+++ b/mod/claw/lib/qywx/_index
@@ -1,4 +1,8 @@
 # ___x_cmd_claw_qywx -h
+# x claw qywx send --text --chatid <chatid> <xxxxxx>
+# x claw qywx send --image --chatid <chatid> <path>
+# x claw qywx send --file --chatid <chatid> <path>
+# x claw qywx get-sent --chatid <chatid>
 
 ___x_cmd_claw_qywx(){
     [ $# -gt 0 ]    ||  set -- --help
@@ -8,7 +12,9 @@ ___x_cmd_claw_qywx(){
         --help|-h)
             ___x_cmd help -m claw qywx ; return 0 ;;
         send)
-            ___x_cmd qywx abot send "$@" ;;
+            ___x_cmd_claw_qywx_send "$@" ;;
+        get-sent)
+            ___x_cmd_claw_qywx_get_sent "$@" ;;
         get-msg)
             ___x_cmd_claw_qywx_get_msg "$@" ;;
         get-unread)
@@ -23,6 +29,52 @@ ___x_cmd_claw_qywx(){
             ___x_cmd_claw_qywx_update_offset "$@" ;;
         *)  N=claw M="Unknown subcmd -> $op" log:ret:64 ;;
     esac
+}
+
+___x_cmd_claw_qywx_send(){
+    local chatid=""
+    local msg_type=""
+    local content=""
+
+    while [ $# -gt 0 ]; do
+        case "$1" in
+            --help|-h)  ___x_cmd help -m claw qywx "$@"; return 0 ;;
+            --chatid)   shift; chatid="$1"; shift; continue ;;
+            --text)     shift; msg_type="text";  content="$*"; break ;;
+            --image)    shift; msg_type="image"; content="$1"; shift; break ;;
+            --file)     shift; msg_type="file";  content="$1"; shift; break ;;
+            *)          break ;;
+        esac
+    done
+
+    [ -n "$chatid" ]    || N=claw M="send: must specify --chatid" log:ret:64
+    [ -n "$msg_type" ]  || N=claw M="send: must specify --text, --image, or --file" log:ret:64
+    [ -n "$content" ]   || N=claw M="send: missing ${msg_type} content" log:ret:64
+
+    ___x_cmd qywx abot send "--${msg_type}" --chatid "$chatid" "$content"
+
+    local x_; ___x_cmd date timestamp_
+    local send_time="$x_"
+
+    local sent_data_path="$___X_CMD_ROOT_DATA/qywx/abot/sent/data_${chatid}.tsv"
+
+    case "$msg_type" in
+        image|file)
+            local asset_dir="$___X_CMD_ROOT_DATA/qywx/abot/sent/asset"
+            ___x_cmd mkdirp "$asset_dir"
+            local target_path="${asset_dir}/${send_time}_${content##*/}"
+
+            ___x_cmd_cmds cp "$content" "$target_path" || {
+                qywx:warn "Failed to copy $msg_type to $target_path"
+            }
+            content="$target_path"
+            ;;
+    esac
+
+    ___x_cmd ensurefp "$sent_data_path"
+    printf '%s\t%s\t%s\n' "$send_time" "$msg_type" "$content" >> "$sent_data_path" || {
+        qywx:warn "Failed to save sent message to $sent_data_path"
+    }
 }
 
 ___x_cmd_claw_qywx_get_unread(){
diff --git a/mod/claw/lib/weixin/_index b/mod/claw/lib/weixin/_index
--- a/mod/claw/lib/weixin/_index
+++ b/mod/claw/lib/weixin/_index
@@ -1,4 +1,7 @@
 # ___x_cmd_claw_weixin -h
+# x claw weixin send --text <xxxxxx>
+# x claw weixin send --image <path>
+# x claw weixin get-sent
 
 ___x_cmd_claw_weixin(){
     [ $# -gt 0 ]    ||  set -- --help
@@ -8,7 +11,9 @@ ___x_cmd_claw_weixin(){
         --help|-h)
             ___x_cmd help -m claw weixin ; return 0 ;;
         send)
-            ___x_cmd weixin send "$@" ;;
+            ___x_cmd_claw_weixin_send "$@" ;;
+        get-sent)
+            ___x_cmd_claw_weixin_get_sent "$@" ;;
         get-msg)
             ___x_cmd_claw_weixin_get_msg "$@" ;;
         get-unread)
@@ -23,6 +28,49 @@ ___x_cmd_claw_weixin(){
             ___x_cmd_claw_weixin_update_offset "$@" ;;
         *)  N=claw M="Unknown subcmd -> $op" log:ret:64 ;;
     esac
+}
+
+___x_cmd_claw_weixin_send(){
+    local msg_type=""
+    local content=""
+
+    while [ $# -gt 0 ]; do
+        case "$1" in
+            --help|-h)  ___x_cmd help -m claw weixin "$@"; return 0 ;;
+            --text)     msg_type="text";  shift; content="$*"; break ;;
+            --image)    msg_type="image"; shift; content="$1"; shift; break ;;
+            --file)     msg_type="file";  shift; content="$1"; shift; break ;;
+            --video)    msg_type="video"; shift; content="$1"; shift; break ;;
+            *)          break ;;
+        esac
+    done
+
+    [ -n "$msg_type" ]   || N=claw M="send: must specify --text, --image, --file, or --video" log:ret:64
+    [ -n "$content" ]    || N=claw M="send: missing ${msg_type} content" log:ret:64
+
+    local x_; ___x_cmd date timestamp_
+    local send_time="$x_"
+
+    ___x_cmd weixin bot send "--${msg_type}"  "$content" || return "$?"
+
+    local sent_data_path="$___X_CMD_ROOT_DATA/weixin/bot/sent/data.tsv"
+    case "$msg_type" in
+        image|file|video)
+            local asset_dir="$___X_CMD_ROOT_DATA/weixin/bot/sent/asset"
+            ___x_cmd mkdirp "$asset_dir"
+            local target_path="${asset_dir}/${send_time}_${content##*/}"
+
+            ___x_cmd_cmds cp "$content" "$target_path" || {
+                weixin:warn "Failed to copy $msg_type to $target_path"
+            }
+            content="$target_path"
+            ;;
+    esac
+
+    ___x_cmd ensurefp "$sent_data_path"
+    printf '%s\t%s\t%s\n' "$send_time" "$msg_type" "$content" >> "$sent_data_path" || {
+        weixin:warn "Failed to save sent message to $sent_data_path"
+    }
 }
 
 ___x_cmd_claw_weixin_get_unread(){
diff --git a/mod/gt/lib/repo/release/attachment b/mod/gt/lib/repo/release/attachment
--- a/mod/gt/lib/repo/release/attachment
+++ b/mod/gt/lib/repo/release/attachment
@@ -8,7 +8,9 @@
 ___x_cmd_gt_repo_release_attachment(){
     param:subcmd ___x_cmd_gt_repo_release_attachment            \
         ls              "List release's attachment"             \
-        create          "Upload attachment"                     \
+        info            "Get attachment"                        \
+        upload          "Upload attachment"                     \
+        download        "Download attachment"                   \
         rm              "Remove attachment"
     param:subcmd:try
     param:run
@@ -17,40 +19,180 @@ ___x_cmd_gt_repo_release_attachment(){
     return 1
 }
 
-# Section: main
+# shellcheck disable=SC2154
+# https://gitee.com/api/v8/swagger#/getV8ReposOwnerRepoReleasesReleaseIdAttachments
 ___x_cmd_gt_repo_release_attachment_ls(){
     param:scope     ___x_cmd_gt
     param:dsl    '
 options:
-    #1|--release        "Release ID"                <>:NatureNumber
+    --repo|-r           "<owner_path>/<repo_path>"                                          <>:RepoPath
+    --release_id        "Release ID"                                                        <>:Number
+    --direction         "direction(asc,desc)"                                               <>:Direction="asc"
+
+    --per_page          "Results per page"                                                  <>="30"
+    --page              "Page number of the results to fetch."                              <>="1"
+
+    --json|-j           "output origin json data"
+    --csv               "output csv data"
+    --yml               "output yml data"
 '
     param:run
-
-    ______x_cmd_gt_repo_release_init_owner_repo_and_release
+    ___x_cmd_gt_param_init_owner_repo
+    [ -n "$owner_repo" ] || M='Please provide --repo <owner/repo>' arg:ret:64
+    if ___x_cmd_gx_output_is_format; then
+        ___x_cmd_gt_get_multi "/repos/${owner_repo}/releases/${release_id}/attach_files" direction | ___x_cmd_gx_output_format
+    else
+        ___x_cmd_gt_get_multi "/repos/${owner_repo}/releases/${release_id}/attach_files" direction | \
+            ___x_cmd jo 2c             .id   .name   .size   .browser_download_url  .created_at | \
+            ___x_cmd csv header --add   Id    Name    Size    Download_URL           Created_At | \
+            if [ -n "$csv" ]; then  ___x_cmd_cmds cat
+            else                    ___x_cmd csv static_tab
+            fi
+    fi
 }
 
-# Provide multiple files
-___x_cmd_gt_repo_release_attachment_create(){
+# https://gitee.com/api/v8/swagger#/getV8ReposOwnerRepoReleasesReleaseIdAttachmentsAttachmentId
+___x_cmd_gt_repo_release_attachment_info(){
     param:scope     ___x_cmd_gt
     param:dsl    '
 options:
-    #1|--release        "Release ID"                <>:NatureNumber
+    #1                  "Release Attachment ID"                     <>:Number
+    --repo|-r           "<owner_path>/<repo_path>"                  <>:RepoPath
+    --release_id        "Release ID"                                <>:Number
+    --json|-j           "output json data"
 '
     param:run
+    [ -n "$1" ] || M='accepts 1 arg(Release Attachment ID), received empty' arg:ret:64
+    local attachment_id="$1"
+    ___x_cmd_gt_param_init_owner_repo
 
-    ______x_cmd_gt_repo_release_init_owner_repo_and_release
+    ___x_cmd_gt_curl get "/repos/${owner_repo}/releases/${release_id}/attach_files/${attachment_id}" | \
+        ___x_cmd_gt_repo_release_attachment____ui_handler Info
 }
 
-# Delete the file in attachment list
+# https://gitee.com/api/v8/swagger#/postV8ReposOwnerRepoReleasesReleaseIdAttachments
+___x_cmd_gt_repo_release_attachment_upload(){
+    param:scope     ___x_cmd_gt
+    param:dsl    '
+options:
+    #1                  "target upload attachment file path"                            <>
+    --repo|-r           "<owner_path>/<repo_path>"                                      <>:RepoPath
+    --release_id        "Release ID"                                                    <>:Number
+    --json|-j           "output json data"
+'
+    param:run
+    [ -n "$1" ] || M='accepts 1 arg (target upload attachment file path), received empty' arg:ret:64
+    local _file_path="$1"
+    [ "$_file_path" != '-' ] || _file_path="$(___x_cmd_cmds_cat)"
+
+    ___x_cmd_gt_param_init_owner_repo
+
+    ___x_cmd_gt_curl upload "/repos/${owner_repo}/releases/${release_id}/attach_files" "$_file_path" | \
+        ___x_cmd_gt_repo_release_attachment____ui_handler Upload
+}
+
+# https://gitee.com/api/v8/swagger#/getV8ReposOwnerRepoReleasesReleaseIdAttachFilesAttachFileIdDownload
+___x_cmd_gt_repo_release_attachment_download(){
+    param:scope     ___x_cmd_gt
+    param:dsl    '
+options:
+    #1                  "Release Attachment ID"                     <>:Number
+    --repo|-r           "<owner_path>/<repo_path>"                  <>:RepoPath
+    --release_id        "Release ID"                                <>:Number
+    --dir|-d            "directory to save the downloaded file"    <>=""
+'
+    param:run
+    [ -n "$1" ] || M='accepts 1 arg(Release Attachment ID), received empty' arg:ret:64
+    local attachment_id="$1"
+    ___x_cmd_gt_param_init_owner_repo
+
+    # Look up the attachment name so the local file has a sensible basename
+    local name=
+    local resp
+    resp="$(___x_cmd_gt_curl get "/repos/${owner_repo}/releases/${release_id}/attach_files/${attachment_id}")"
+    ___x_cmd jo env . .name <<A
+$resp
+A
+    if [ -z "$name" ]; then
+        gt:error "Download failure: could not resolve attachment name for ${release_id}/${attachment_id} on ${owner_repo}"
+        return 1
+    fi
+
+    local targetfp
+    if [ -n "$dir" ]; then
+        targetfp="$dir/$name"
+        ___x_cmd mkdirp "$dir" 2>/dev/null
+    else
+        targetfp="./$name"
+    fi
+
+    gt:info "Downloading [attachment=$name] to [save_path=$targetfp]..."
+    if ! ___x_cmd_gt_curl download "/repos/${owner_repo}/releases/${release_id}/attach_files/${attachment_id}/download" "$targetfp"; then
+        gt:error "Download failure: failed to save ${targetfp}"
+        return 1
+    fi
+    gt:info "Downloaded to $targetfp"
+}
+
+# shellcheck disable=SC2154,SC2034
+# https://gitee.com/api/v8/swagger#/deleteV8ReposOwnerRepoReleasesReleaseIdAttachmentsAttachmentId
 ___x_cmd_gt_repo_release_attachment_rm(){
     param:scope     ___x_cmd_gt
     param:dsl    '
 options:
-    #1|--release        "Release ID"                <>:NatureNumber
+    #1                  "Release Attachment ID"                     <>:Number
+    --repo|-r           "<owner_path>/<repo_path>"                  <>:RepoPath
+    --release_id        "Release ID"                                <>:Number
+    --yes|-y            "Ignore remove prompt interception"
 '
     param:run
+    [ -n "$1" ] || M='accepts 1 arg(Release Attachment ID), received empty' arg:ret:64
+    local attachment_id="$1"
+    ___x_cmd_gt_param_init_owner_repo
+    [ "$yes" = "true" ] || ___x_cmd_ui_yesno "Are you sure you want to remove release attachment $(___x_cmd_ui bold red "$attachment_id") on $owner_repo release $release_id ?" || return
 
-    ______x_cmd_gt_repo_release_init_owner_repo_and_release
+    ___x_cmd_gt_curl del "/repos/${owner_repo}/releases/${release_id}/attach_files/${attachment_id}" | (
+            [ -z "$___X_CMD_GT_IN_TEST" ] || { ___x_cmd_cmds_cat; return; }
+            ___x_cmd jo env . gt_resp_err=.message gt_resp_err=.error
+            if ___x_cmd_gt_http_error; then
+                ___x_cmd_ui_tf true  "[Success]: Remove ${owner_repo} ${release_id}/${attachment_id} release attachment successfully"
+            else
+                ___x_cmd_ui_tf false "Remove ${owner_repo} ${release_id}/${attachment_id} release attachment failure" >&2
+                ___x_cmd_gt____handle_resp
+                return 1
+            fi
+        )
 }
 
-# EndSection
+
+___x_cmd_gt_repo_release_attachment____ui_handler(){
+    if [ -n "$ENFORCE_JSON" ] || [ -n "$json" ]; then
+        ___x_cmd_cmds_cat
+        ___x_cmd_gt_http_error
+        return
+    fi
+    (
+        case "$1" in
+            Upload)
+                _inf_msg="$1 repo release attachment successfully"
+                _err_msg="$1 repo release attachment failure"
+                ;;
+            Info)
+                _inf_msg="Get repo release attachment info successfully"
+                _err_msg="Get repo release attachment info failure"
+                ;;
+        esac
+
+        local _id=""
+        ___x_cmd jo env . _id=.id gt_resp_err=.message gt_resp_err=.error \
+            name=.name size=.size down_url=.browser_download_url created_at=.created_at
+        if [ -n "$_id" ]; then
+            ___x_cmd_ui_tf  true "${_inf_msg}:" "Release_Attachment_Id: $_id" ${name:+"Name: $name"} ${size:+"Size: $size"} \
+                ${down_url:+"Download_URL: $down_url"} ${created_at:+"Created_At: $created_at"}
+        else
+            ___x_cmd_ui_tf false "${_err_msg}:" >&2
+            ___x_cmd_gt____handle_resp
+            return 1
+        fi
+    )
+}
diff --git a/mod/gt/lib/utils b/mod/gt/lib/utils
--- a/mod/gt/lib/utils
+++ b/mod/gt/lib/utils
@@ -67,6 +67,33 @@ ___x_cmd_gt_curl(){
             ___x_cmd_api_gt "$op" "$_api_url" "$(x curl gencode "$@")"
             ___x_cmd_gt_http_error
         ;;
+        upload)
+            [ -n "$1" ] || M='Please provide upload filepath' arg:ret:64
+            local __file_path="$1"; shift;
+            # NOTE: -F sets Content-Type to multipart/form-data with a boundary
+            # automatically; do NOT pass our own Content-Type header or the
+            # multipart is broken.  The file_type DSL flag is still accepted
+            # for API symmetry with gh but is not forwarded.
+            ___X_CMD_API_GT_HEADER="-s -D \"$___X_CMD_GT_TMP/.____x_cmd_gt_curl_header.$$\""
+            [ -f "$__file_path" ] || {
+                gt:error "Upload Failure. Not found target file. Please check file exist $__file_path"
+                return 1
+            }
+            gt:info "Uploading file $__file_path..."
+            ___x_cmd_api_gt "${___X_CMD_GT_UPLOAD_REQ_METHOD:-"post"}" "$_api_url" -F "file=@\"$__file_path\""
+            ___x_cmd_gt_http_error
+        ;;
+        download)
+            [ -n "$1" ] || M='Please provide output file path' arg:ret:64
+            local __out="$1"
+            case "$__out" in
+                */*)   x mkdirp "${__out%/*}"  ;;
+                *)     __out="./${__out}"      ;;
+            esac
+            ___X_CMD_API_GT_HEADER="-L -# -D \"$___X_CMD_GT_TMP/.____x_cmd_gt_curl_header.$$\""
+            ___x_cmd_api_gt "${___X_CMD_GT_DOWNLOAD_REQ_METHOD:-"get"}" "$_api_url" -o "\"$__out\""
+            ___x_cmd_gt_http_error
+        ;;
     esac
 }
 
