...

diff --git a/mod/gx/lib/share b/mod/gx/lib/share
--- a/mod/gx/lib/share
+++ b/mod/gx/lib/share
@@ -88,6 +88,67 @@ ___x_cmd_gx_avatar_sdict_to_csv(){
 }
 # EndSection
 
+# Section: Export CSV
+___x_cmd_gx_tocsv(){
+x ja '
+BEGIN{
+    IS_LIST=0
+    IS_DICT=0
+    data = ""
+    pre_key=""
+}
+
+function handle_dict(keypath,key,           key_l, _key, j, _data){
+    # keypath = keypath SUBSEP key
+    # _data = data "."key
+    key_l = O[keypath L ]
+    pre_key = pre_key "."key
+    for(j=1; j<=key_l; ++j){
+        _key = juq(O[ keypath SUBSEP  "\""j"\"" ])
+        if (O[ keypath SUBSEP  "\""_key"\"" ] == "{"){
+            handle_dict(keypath SUBSEP "\""_key"\"", _key )
+            pre_key = pre_key "."key
+        }
+        else {
+            _data = pre_key"."_key " "
+            data = data _data
+        }
+        if( key_l == j)pre_key = ""
+    }
+}
+
+function list(              key, i, len, keypath){
+    len = O[kp("1", "1") L]
+    for(i=1; i<=len; ++i){
+        key = juq(O[kp("1", "1", i) ])
+        keypath = SUBSEP "\"1\"" SUBSEP "\"1\"" SUBSEP "\""key"\""
+        if (O[ keypath ] == "{") handle_dict(keypath, key)
+        else if (key != "")data = data "."key " "
+    }
+}
+function dict(        key, i, len, keypath){
+    len = O[kp("1") L]
+    for(i=1; i<=len; ++i){
+        key = juq(O[kp("1", i) ])
+        keypath = SUBSEP "\"1\""  SUBSEP "\""key"\""
+        if (O[ keypath ] == "{") handle_dict(keypath, key)
+        else if(key != "")data = data "."key " "
+    }
+}
+
+END{
+    if( O[kp("1")] == "[") IS_LIST = 1
+    else IS_DICT = 1
+
+    if (IS_LIST == 1) data = data "| x jo 2c "  ;   list()
+    if (IS_DICT == 1) data = data "| x ja jl2c ";   dict()
+
+    print data
+}
+'
+}
+# EndSection
+
 # Section: Merge Multi Page JSON Array
 ___x_cmd_gx_merge_multi_page_json_array(){
     command awk 'BEGIN{ print "["}
@@ -99,5 +160,23 @@ ___x_cmd_gx_merge_multi_page_json_array(){
             if (($0 == "}") || ( $0 == "]")) aaa--
             print $0
         }'
+}
+# EndSection
+
+# Section: Is No Color && Print Error Message
+___x_cmd_gx_stdout_is_no_color(){
+    [ ! -t 1 ] || ! ___x_cmd_is_interactive_tty || [ -n "$NO_COLOR" ]
+}
+
+___x_cmd_gx_stderr_is_no_color(){
+    [ ! -t 2 ] || ! ___x_cmd_is_interactive_tty || [ -n "$NO_COLOR" ]
+}
+
+___x_cmd_gx_printf_error(){
+    if ___x_cmd_gx_stderr_is_no_color; then
+        printf "  - ErrorMsg: '%s'\n" "$1" >&2
+    else
+        printf "  \033[31m-\033[0m \033[1mErrorMsg: \033[90m'\033[31m%s\033[90m'\033[0m\n" "$1" >&2
+    fi
 }
 # EndSection
