...

diff --git a/mod/npx/lib/main b/mod/npx/lib/main
--- a/mod/npx/lib/main
+++ b/mod/npx/lib/main
@@ -1,25 +1,42 @@
 # shellcheck shell=dash
+
+x log init npx
+
 ___x_cmd_npx___main(){
     [ "$#" -gt 0 ] || {
-        ( ___x_cmd_npx___cmd npx )
+        ___x_cmd_npx___help
         return
     }
 
-    ( ___x_cmd_npx___cmd npx "$@" )
-
-    # local op="$1"; shift
-    # case "$op" in
-
-    # esac
+    local op="$1";      shift
+    case "$op" in
+        *)              ___x_cmd_npx___cmd npx "$op"    "$@" ;;
+    esac
 }
 
 ___x_cmd_npx___cmd(){
-    if ___x_cmd_hasbin "$1"; then
-        "$@"
-        return
-    fi
+    ___x_cmd_hasbin "$1" || {
+        ___x_cmd_is_interactive || {
+            npx:error --tip1 'x env use node' --tip2 'x env try node' "Node not found."
+            return 1
+        }
 
-    x node load || return
-    local bin="$1"; shift
-    "$___X_CMD_NODE_SHIMAPP_PATH/$bin" "$@"
+        npx:info "Node not found."
+        local cmd=
+        x ui select ,cmd  "What's next:"    \
+            "x env use node"                \
+            "x env try node"                \
+            "x install node"                \
+            "return 1"                      || return 1
+        eval "$cmd"
+    }
+
+    "$@"
+}
+
+
+# shellcheck disable=SC2120
+___x_cmd_npx___help(){
+    x help -m npx "$@" 1>&2
+    return 1
 }
