...

diff --git a/mod/theme/lib/app/_index b/mod/theme/lib/app/_index
--- a/mod/theme/lib/app/_index
+++ b/mod/theme/lib/app/_index
@@ -2,13 +2,43 @@
 
 ___x_cmd_theme_control_app(){
     local x_file=
-    if ___x_cmd_theme_which___getfile_ classify.yml; then
-        local ___X_CMD_THEME_SCHEME=
-        ___x_cmd_theme_app "$x_file" || return
-        [ -n "$___X_CMD_THEME_SCHEME" ] || return
-        theme:info "x theme use $___X_CMD_THEME_SCHEME"
-        ___x_cmd_theme_control_use "$___X_CMD_THEME_SCHEME"
-    fi
+
+    ___x_cmd_theme_which___getfile_ classify.yml || {
+        theme:error "Fail to download theme resource -> classfiy.yml"
+        return 1
+    }
+
+    local ___X_CMD_THEME_SCHEME=
+    ___x_cmd_theme_app "$x_file" || return
+    [ -n "$___X_CMD_THEME_SCHEME" ] || return
+
+    local id
+    x ui select id "Next for theme -> $___X_CMD_THEME_SCHEME"                       \
+        "x theme use $___X_CMD_THEME_SCHEME     # Apply globally"                   \
+        "x theme try $___X_CMD_THEME_SCHEME     # Apply only in current shell env"  \
+        "x open https://x-cmd.com/theme/${___X_CMD_THEME_SCHEME%/*}"                \
+        "EXIT"
+
+    case "$id" in
+        1)
+            # TODO: In the future, we might provide use theme app to choose the specific scenario
+            theme:info "cmd -> x theme use $___X_CMD_THEME_SCHEME"
+            x theme use "$___X_CMD_THEME_SCHEME"
+            ;;
+        2)
+            theme:info "cmd -> x theme use $___X_CMD_THEME_SCHEME"
+            x theme try "$___X_CMD_THEME_SCHEME"
+            ;;
+        3)
+            theme:info "Open browser for more info about ${___X_CMD_THEME_SCHEME%/*}"
+            x open "https://x-cmd.com/theme/${___X_CMD_THEME_SCHEME%/*}"
+            ;;
+        4)
+            theme:info "exit the theme app"
+            return 0
+            ;;
+    esac
+
 }
 
 ___x_cmd_theme_app(){
