Updating main branch using x7 release -> 21153a96e2d6a02ddabdde4c9eec2e758e4c8679

diff --git a/mod/is/lib/main b/mod/is/lib/main
--- a/mod/is/lib/main
+++ b/mod/is/lib/main
@@ -7,7 +7,12 @@ ___x_cmd_is___main(){
 
     local op="$1";  shift
     case "$op" in
-        int|float|positive|negative|eq|within|newest|ip|minmax)
+        int|float|positive|negative|eq|within|newest|oldest|ip|minmax)
+                    ___x_cmd_is_"$op" "$@" ;;
+
+        interactive|interactive_tty|interactiveshell|repl|stdout2tty|\
+        wsl|cygwin|msys|gitbash|termux|ish|\
+        suitable_pkg|suitable_advise_env|suitable_advise_repl)
                     ___x_cmd_is_"$op" "$@" ;;
 
         in)         S=, L="$2" ___x_cmd_is___in "$1" ;;
@@ -19,8 +24,15 @@ ___x_cmd_is___main(){
 
         --app)      ___x_cmd_is___app "$@"      ;;
 
-        *)          ___x_cmd_is_"$op" "$@"      ;;
+        *)          ___x_cmd_is___error "$op" "$@"      ;;
     esac
+}
+
+___x_cmd_is___error(){
+    local op="$1"; shift
+    ___x_cmd_is___main --help
+    printf '\nError: Unknown operator: %s\n' "$op" >&2
+    return 1
 }
 
 ___x_cmd_is___app(){
