...

diff --git a/mod/cfgy/lib/obj/var b/mod/cfgy/lib/obj/var
--- a/mod/cfgy/lib/obj/var
+++ b/mod/cfgy/lib/obj/var
@@ -1,11 +1,11 @@
-
+# shellcheck shell=dash
 # TODO: Make it into import syntax <newvar>:=<var>
 ___x_cmd_cfgy_obj_var(){
     local X_help_cmd="${X_help_cmd:-x help -m cfgy obj var}"
     cfgy:arg:config-profile:all
 
     [ $# -ge 1 ] || {
-        cfgy:error "___x_cmd_cfgy_obj_var_() requires at least one varname"
+        cfgy:error "Invalid argument, requires at least one varname"
         return 64
     }
 
@@ -63,14 +63,21 @@ ___x_cmd_cfgy_obj_var___main(){
     while [ "$#" -gt 0 ]; do
         case "$1" in
         *=*)
-            envvar=${1%%=*}
-            cfgvar=${___X_CMD_CFGY_OBJ_PREFIX}_${x_}_${1#*=}
+            envvar="${1%%=*}"
+            cfgvar="${1#*=}"
             ;;
         *)
             envvar="$1"
-            cfgvar="${___X_CMD_CFGY_OBJ_PREFIX}_${x_}_${1}"
+            cfgvar="$1"
             ;;
         esac
+
+        ___x_cmd_cfgy_obj___hasvar "$cfgvar" || {
+            N=cfgy M="Unknown varname ==> $cfgvar" log:ret:64
+            return 1
+        }
+
+        cfgvar="${___X_CMD_CFGY_OBJ_PREFIX}_${x_}_${cfgvar}"
 
         code1="$code1
         [ \"\${${cfgvar}+1}\" = 1 ] || return"
