...

diff --git a/mod/chat/lib/minion/_index b/mod/chat/lib/minion/_index
--- a/mod/chat/lib/minion/_index
+++ b/mod/chat/lib/minion/_index
@@ -1,4 +1,4 @@
-
+# shellcheck shell=dash
 ___X_CMD_CHAT_MINION_DIR="$___X_CMD_ROOT_DATA/chat/data/minion"
 
 ___x_cmd_chat_minion(){
@@ -20,7 +20,29 @@ ___x_cmd_chat_minion_ls(){
 }
 
 ___x_cmd_chat_minion_which_(){
-    :
+    x_="$___X_CMD_ROOT_MOD/chat/lib/minions/$1.minion.yml"
+    [ -f "$x_" ]
+}
+
+___x_cmd_chat_minion_cache_json_(){
+    local json_cache=
+    local minion="$1"
+    if [ -f "$minion" ]; then
+        x_=; ___x_cmd_abspath_ "$minion" || return
+        json_cache="${___X_CMD_ROOT_CACHE}/chat/minion$x_"
+    elif ___x_cmd_chat_minion_which_ "$minion"; then
+        json_cache="${___X_CMD_ROOT_CACHE}/chat/minion$x_"
+        minion="$x_"
+    else
+        chat:error "Not found the minion file of $minion"
+        return 1
+    fi
+    x_=""
+    chat:debug "json_cache[$json_cache]"
+    x ensurefp "$json_cache"
+    < "$minion" x y2j > "$json_cache" || return
+    x_="$json_cache"
+    [ -f "$x_" ]
 }
 
 ___x_cmd_chat_minion_which(){
diff --git a/mod/pkg/lib/sphere/add/_index b/mod/pkg/lib/sphere/add/_index
--- a/mod/pkg/lib/sphere/add/_index
+++ b/mod/pkg/lib/sphere/add/_index
@@ -52,7 +52,7 @@ ___x_cmd_pkg_sphere_add___migrate(){
         if ___x_cmd_pkg_sphere_populate_done \
                 --sphere "$sphere_name" --sphereroot "$___X_CMD_PKG_ROOT_SPHERE" \
                 --osarch "$osarch" "$name" "$version"; then
-            ___x_cmd_pkg_sphere_add___protect
+            ___x_cmd_pkg_sphere_add___protect || return
             return 0
         fi
     fi
@@ -65,7 +65,6 @@ ___x_cmd_pkg_sphere_add___migrate(){
                 --sphere "$sphere_name" --sphereroot "$___X_CMD_PKG_ROOT_SPHERE" \
                 --osarch "$osarch" "$name" "$version"; then
 
-            # add DEPENDENCY file MUST be placed here ...
             ___x_cmd_pkg_sphere_depend_file add \
                 --sphere "$sphere_name" --sphereroot "$___X_CMD_PKG_ROOT_SPHERE" \
                 --osarch "$osarch" "$name" "$version"   || return
@@ -80,12 +79,18 @@ ___x_cmd_pkg_sphere_add___migrate(){
             ___x_cmd_pkg_sphere_populate_run    \
                 --sphere "$sphere_name" --sphereroot "$___X_CMD_PKG_ROOT_SPHERE" \
                 --osarch "$osarch" "$name" "$version"   || return
-            # add DONE file ...
-
         fi
+
         ___x_cmd_pkg_sphere_add___protect || return
         x fslock release "$fslock_name"
-    ) || x fslock release "$fslock_name"
+    ) || {
+        pkg:error "Failed to add $osarch '$name $version'"
+        x fslock release "$fslock_name"
+        ___x_cmd_pkg_sphere_depend_file rm \
+            --sphere "$sphere_name" --sphereroot "$___X_CMD_PKG_ROOT_SPHERE" \
+            --osarch "$osarch" "$name" "$version"
+        return 1
+    }
 }
 
 ___x_cmd_pkg_sphere_add___protect(){
