...

diff --git a/mod/apk/lib/main b/mod/apk/lib/main
--- a/mod/apk/lib/main
+++ b/mod/apk/lib/main
@@ -1,60 +1,42 @@
 # shellcheck shell=dash disable=SC2034,SC2016
 x log init apk
 
+xrc:mod:lib apk     __xmirror __xproxy __repo install nv ls
+
 ___x_cmd_apk___main(){
     [ "$#" -gt 0 ] ||   set -- nv
 
+    x hascmd apk   ||  {
+        apk:warn "apk command not found."
+        return 1
+    }
+
     local op="$1"; shift
     case "$op" in
-        i|install)      ___x_cmd_apk___install  "$@" ;;
-        nv)             ___x_cmd_apk___nv       "$@" ;;
-        --help|-h)      x help -m apk;        return ;;
-        # proxy)          ___x_cmd_apk___proxy    "$@" ;;
-        *)              ___x_cmd_cmds apk "$op" "$@" ;;
+        nv)                 ___x_cmd_apk___nv           "$@" ;;
+        i|install)          ___x_cmd_apk___install      "$@" ;;
+        proxy|--xproxy)     ___x_cmd_apk___xproxy       "$@" ;;
+        mirror|--xmirror)   ___x_cmd_apk___xmirror      "$@" ;;
+
+        add|update|upgrade)
+                            ___x_cmd_apk___exec "$op"   "$@" ;;
+        *)                  ___x_cmd_cmds apk   "$op"   "$@" ;;
     esac
 }
 
-___x_cmd_apk___nv(){
-    local X_help_cmd='x help -m apk nv'
-    help:arg:parse
-
-    { [ -t 1 ] && ___x_cmd_is_interactive; } \
-        || {
-            x ccmd 1d -- ___x_cmd_apk___lsraw
-            return 0
-        }
-
-    local software
-    software="$(x ccmd 1d -- ___x_cmd_apk___lsraw | x pick --width 40 --col 10)"
-    [ -n "$software" ] || {
-        apk:info "Exit because no software is selected."
-        return 0
-    }
-
-    local id
-    x ui select id "What to do NEXT"                        \
-        "x apk install $software"                           \
-        "EXIT"     || return
-
-    case "$id" in
-        1)      x apk install "$software" ;;
-        2)      return 0 ;;
-    esac
+___x_cmd_apk___exec(){
+    apk:info "running command  →  x sudo apk $*"
+    ___x_cmd_apk___xproxy run x sudo apk "$@"
 }
 
 ___x_cmd_apk___lsraw(){
-    ___x_cmd_cmds apk list
-}
+    apk:info "running command  →  apk list"
+    ___x_cmd_cmds apk list | ___x_cmd_cmds awk '{
+        l = $1
+        sub("\-[^-]*$", "", l)
+        sub("\-[^-]*$", "", l)
 
-___x_cmd_apk___install(){
-    local X_help_cmd='x help -m apk nv'
-    help:arg:parse
-
-    if [ $# -eq 0 ]; then
-        ___x_cmd_apk___nv
-        return 0
-    fi
-
-    # Using x sudo
-    x sudo apk add "$@"
+        if (arr[l] != 1) print l
+        arr[l] = 1
+    }' | ___x_cmd_cmds sort -u
 }
