...

diff --git a/mod/apk/lib/main b/mod/apk/lib/main
--- a/mod/apk/lib/main
+++ b/mod/apk/lib/main
@@ -34,10 +34,24 @@ ___x_cmd_apk___exec(){
 }
 
 ___x_cmd_apk___lsraw(){
+    local x_=; ___x_cmd_apk___lsraw_ || return 1
+    ___x_cmd_cmds_cat "$x_"
+}
+
+
+___x_cmd_apk___lsraw_(){
     local apkfp=;   apkfp="$(___x_cmd_cmds ls -1 /var/cache/apk/APKINDEX.* 2>/dev/null | head -n 1)"
     local cachefp=; cachefp="$___X_CMD_ROOT_DATA/apk/cache/lsname"
     x ensurefp "$cachefp"
 
     [ "$cachefp" -nt "$apkfp" ] || ___x_cmd_apk___repo_lsname > "$cachefp"
-    ___x_cmd_cmds_cat "$cachefp"
+    local l=;
+    <"$cachefp" read -r l
+
+    [ -n "$l" ] || {
+        x rmrf "$cachefp"
+        dnf:error "list software fail, please try again."
+        return 1
+    }
+    x_="$cachefp"
 }
diff --git a/mod/dnf/lib/main b/mod/dnf/lib/main
--- a/mod/dnf/lib/main
+++ b/mod/dnf/lib/main
@@ -38,10 +38,24 @@ ___x_cmd_dnf___exec(){
 
 
 ___x_cmd_dnf___lsraw(){
-    local dnffp=;   dnffp="$(___x_cmd_cmds ls -1 /var/cache/dnf/*.solv 2>/dev/null | head -n 1)"
+    local x_=; ___x_cmd_dnf___lsraw_ || return 1
+    ___x_cmd_cmds_cat "$x_"
+}
+
+
+___x_cmd_dnf___lsraw_(){
+    local dnffp=;   dnffp="/var/cache/dnf/updates.solv"
     local cachefp=; cachefp="$___X_CMD_ROOT_DATA/dnf/cache/lsname"
     x ensurefp "$cachefp"
 
     [ "$cachefp" -nt "$dnffp" ] || ___x_cmd_dnf___repo_lsname > "$cachefp"
-    ___x_cmd_cmds_cat "$cachefp"
+    local l=;
+    <"$cachefp" read -r l
+
+    [ -n "$l" ] || {
+        x rmrf "$cachefp"
+        dnf:error "list software fail, please try again."
+        return 1
+    }
+    x_="$cachefp"
 }
