...

diff --git a/mod/git/lib/sync b/mod/git/lib/sync
--- a/mod/git/lib/sync
+++ b/mod/git/lib/sync
@@ -42,6 +42,11 @@ ___x_cmd_git_sync_pull(){
 }
 
 ___x_cmd_git_sync_push(){
+    # ! ___x_cmd_git_is_empty || {
+    #     git:warn "___x_cmd_git_sync_push abort: Git directory is empty."
+    #     return 1
+    # }
+
     local name; for name in "$@"; do
         ___x_cmd_git_sync_push___one "$name";
     done
@@ -50,13 +55,8 @@ ___x_cmd_git_sync_push(){
 ___x_cmd_git_sync_push___one(){
     local name="${1:?Provide name or url}"
 
-    ___x_cmd_git_is_empty || {
-        git:warn "___x_cmd_git_sync_push abort: Git directory is empty."
-        return 1
-    }
-
     if ! ___x_cmd___git_origin push -u "$name" --all; then
-        x:warn "Push In Force: ·git push -u -f $name --all"
+        x:warn "Push In Force: git push -u -f $name --all"
         ___x_cmd___git_origin push -u -f "$name" --all
     fi
 
