...

diff --git a/mod/advise/lib/gen_advise b/mod/advise/lib/gen_advise
--- a/mod/advise/lib/gen_advise
+++ b/mod/advise/lib/gen_advise
@@ -61,7 +61,7 @@ ___x_cmd_advise_gen_advise__parse_adv_data(){
         case "$datafile" in
             *.yml)
                     advise:debug "Generate $mod_name data/${tagfile%.yml*}.jso from adv/data/$tagfile"
-                    < "$datafile" x yml y2j | ___x_cmd_advise_gen_advise__merge_awk > "$res_data/${tagfile%.yml*}.jso"
+                    < "$datafile" x scotty yml y2j | ___x_cmd_advise_gen_advise__merge_awk > "$res_data/${tagfile%.yml*}.jso"
                     ;;
             *)      x cp "$datafile" "$res_data/$tagfile" ;;
         esac
@@ -97,7 +97,7 @@ ___x_cmd_advise_gen_advise(){
     ___x_cmd_advise_gen_advise__parse_adv_data "$mod_name" "$mod_path"
 
     # parse adv/index.yml
-    < "$index_yml" x yml y2j | {
+    < "$index_yml" x scotty yml y2j | {
         local content;      content="$(cat)"
         printf "%s\n" "$content"
 
@@ -150,7 +150,7 @@ ___x_cmd_advise___install_xcmd_dir_()(
     ____x_cmd_advise___install_y2j advise.yml > "$folder/advise.t.jso" || return
     [ ! -f advise.util ] || x cp advise.util "$folder"
 
-    find _ -type f -name '*advise.yml' 2>/dev/null | while read -r line; do
+    find _ lib data -type f -name '*advise.yml' 2>/dev/null | while read -r line; do
         dst="$folder/${line%.yml}.t.jso"
         x ensurefp "$dst"
         ____x_cmd_advise___install_y2j "$line" > "$dst" || return
@@ -160,8 +160,8 @@ ___x_cmd_advise___install_xcmd_dir_()(
 ____x_cmd_advise___install_y2j(){
     [ -f "$1" ] || return
     local tmp="$___X_CMD_ROOT_TMP/advise/tmp.jso";          x ensurefp "$tmp"
-    x yml y2j "$1" > "$tmp" || {
-        x:error "Failed $1 yml y2j"
+    x scotty yml y2j "$1" > "$tmp" || {
+        x:error "Failed $1 yml to json"
         return 1
     }
     < "$tmp" ___x_cmd_advise_gen_advise__merge_awk
diff --git a/mod/pkg/lib/mutate/download b/mod/pkg/lib/mutate/download
--- a/mod/pkg/lib/mutate/download
+++ b/mod/pkg/lib/mutate/download
@@ -55,14 +55,17 @@ ___x_cmd_pkg_download(){
         pkg:warn "File corrupted. Download the $ball again."
         x rmrf "$ball"
     fi
+    (
     while read -r url; do
         # TODO: ___x_cmd_httpget support 302
         # ___x_cmd_httpget "$url" "$ball" || {
         pkg:info "Download $name $version from $url to $ball"
         # TODO: x curl
+        trap 'x pkg uninstall $name $version 2>/dev/null; printf "\r\n";  pkg:error "Download interrupted"; return 1;' INT
         head=$(curl -I "$url" | awk 'NR==1{ print $2}' )
         if [ "$head" -eq "200" ] || [ "$head" -eq "304" ] || [ "$head" -eq "302" ] || [ "$head" -eq "301" ]; then
-            if ! curl --progress-bar --location --retry-max-time 10 --retry 0 "$url" --output "$ball" ; then
+            curl --progress-bar --location --retry-max-time 10 --retry 0 "$url" --output "$ball"
+            if [ "$?" != 0 ]; then
                 pkg:warn "Fail to download from $url"
                 x rmrf "$ball"
                 return 1
@@ -76,12 +79,12 @@ ___x_cmd_pkg_download(){
 
         ! ___x_cmd_pkg_download___check_hashsum "$ball" "$md5" "$sha1" "$sha256" "$sha512" || return 0
         pkg:warn "File corrupted."
-        # x rmrf "$ball"
+        x rmrf "$ball"
         return 1
     done <<A
 $url_list
 A
-
+    )
 }
 
 ___x_cmd_pkg_download_file___from_static_build_and_deflate(){
diff --git a/mod/solo/lib/exec b/mod/solo/lib/exec
--- a/mod/solo/lib/exec
+++ b/mod/solo/lib/exec
@@ -1,19 +1,146 @@
 # shellcheck shell=dash
 
+xrc:mod:lib    solo        __exec/inplace     __exec/ws
+
+___X_CMD_SOLO_WORKSPACE_ROOT=$___X_CMD_ROOT_DATA/solo/ws
+
 ___x_cmd_solo___exec(){
-    local solo_workpath="${___X_CMD_ROOT_DATA}/solo/link${1}"
+    local x_engine
+    local x_setup
+    local x_mode
 
-    local solo_entrypoint="$solo_workpath/X"
+    local filepath="$1"; shift
 
-    [ -e "$solo_entrypoint" ] || {
-        solo:error "Please init before exec"
-        return 1
-    }
+    ___x_cmd_solo_parse_ "$filepath"
+    ___x_cmd_solo___exec_engine_detect_from_fileext_ "$filepath" || x_=source
+    x_engine="$x_"
 
-    [ "$solo_entrypoint" -ot "$1" ] || {
-        solo:error "Please init again before exec for solo script is changed"
-        return 1
-    }
+    if [ source = "$engine" ]; then
+        x source "$filepath" "$@"
+        return
+    fi
 
-    . "$solo_workpath/X"
+    (
+        ___x_cmd_solo___exec___mode_ "$filepath"
+        local running_filepath="$x_"
+
+        x "$engine" load
+
+        local ___x_cmd_solo_oldpwd="$PWD"
+        cd "${x_%/*}}"
+        ___x_cmd_solo___exec_setup "$x_setup" || return
+        [ -z "$___x_cmd_solo_oldpwd" ] || command cd "$___x_cmd_solo_oldpwd"
+
+        local ___x_cmd_errcode=0; x "$x_engine" "${___X_CMD_ENGINE_SUBCMD_NAME:-__enginerun}" "$running_filepath" "$@" || ___x_cmd_errcode=$?
+        return $___x_cmd_errcode
+    )
 }
+
+___x_cmd_solo___exec___mode_(){
+    x abspath_ "$1"
+
+    case "$x_mode" in
+        inplace)    x_="$x_"; return ;;
+        ws)         "$@" ;;
+        *)          [ -n "$x_setup" ] || x_="$x_"; return  ;;
+    esac
+
+    local filename="${x_##*/}"
+    local dirname="${x_%/*}"
+    wspath="${___X_CMD_SOLO_WORKSPACE_ROOT}/$dirname"
+    command cp "$PWD/$filename" "$wspath/$filename"
+    x_="$wspath/$filename"
+}
+
+___x_cmd_solo___exec_setup(){
+    local setupcode="$1"; shift
+    if [ -f "${wspath}/.x-cmd/.setup.fail" ]; then
+        x ui yesno "setup fail last time. retry?" || return 1
+        x rmrf "$wspath/.x-cmd"
+        ___x_cmd_solo___exec_setup_main "$@"
+    elif [ ! -f "${wspath}/.x-cmd/.setup.ok" ]; then
+        ___x_cmd_solo___exec_setup_main "$@" || {
+            x:error "Fail to setup workspace"
+            return 1
+        }
+    fi
+}
+
+___x_cmd_solo___exec_setup_main(){
+    local setupcode="$1"; shift
+
+    x abspath_ "$1"
+    local filename="${x_##*/}"
+    local dirname="${x_%/*}"
+    wspath="${___X_CMD_SOLO_WORKSPACE_ROOT}/$dirname"
+    command mkdir -p "${wspath}/.x-cmd"
+    command cp "$dirname/$filename" "${wspath}/$filename"
+
+    printf "%s\n%s\n%s\n" \
+        "# x-cmd.engine: source" \
+        "# x-cmd.end" "$setupcode" >"${wspath}/.x-cmd/setup"
+
+    local ___x_cmd_solot_oldpwd="$PWD"
+    cd "${wspath}"
+    x ws setup || {
+        touch "${wspath}/.x-cmd/.setup.fail"
+        cd "$___x_cmd_solot_oldpwd"
+        x:error "Fail to setup workspace"
+        return 1
+    }
+
+    touch "${wspath}/.x-cmd/.setup.ok"
+    cd $___x_cmd_solot_oldpwd
+}
+
+___x_cmd_solo___exec_engine_detect_from_fileext_(){
+    local filepath="${1:?filepath}"; shift
+    local ext="${filepath##*.}"
+    x_=
+    case "$ext" in
+        "$filepath")    return 126      ;;
+        py)             x_=python       ;;
+        pl)             x_=perl         ;;
+        rb)             x_=ruby         ;;
+        js)             x_=node         ;;
+        ts)             x_=ts           ;;
+        raku|rakumod)   x_=raku         ;;
+
+        bash)           x_=bash         ;;
+        zsh)            x_=zsh          ;;
+        fish)           x_=fish         ;;
+        ksh)            x_=ksh          ;;
+        sh)             x_=sh           ;;
+
+        java)           x_=java         ;;      # No File Header for this.
+        jar)            x_=jar          ;;      # No File Header for this.
+        groovy)         x_=groovy       ;;
+        kts)            x_=kotlin       ;;      # No File Header for this.
+
+        txt)            x_=bat          ;;
+        yml|yaml)       x_=yml          ;;
+        json|jso)       x_=ja           ;;
+        toml)           x_=bat          ;;
+
+        *)              return 126      ;;
+    esac
+}
+
+
+# ___x_cmd_solo___exec(){
+#     local solo_workpath="${___X_CMD_ROOT_DATA}/solo/link${1}"
+
+#     local solo_entrypoint="$solo_workpath/X"
+
+#     [ -e "$solo_entrypoint" ] || {
+#         solo:error "Please init before exec"
+#         return 1
+#     }
+
+#     [ "$solo_entrypoint" -ot "$1" ] || {
+#         solo:error "Please init again before exec for solo script is changed"
+#         return 1
+#     }
+
+#     . "$solo_workpath/X"
+# }
