...

diff --git a/mod/advise/lib/gen_advise b/mod/advise/lib/gen_advise
--- a/mod/advise/lib/gen_advise
+++ b/mod/advise/lib/gen_advise
@@ -1,12 +1,14 @@
 # shellcheck shell=sh disable=SC3043,2120,2181,1091,2016,2034,2012
 # ___X_CMD_ADVISE_GEN_ADVISE_INDEX_FIELDS='useparam
 
-___X_CMD_ADVISE_ERREXIT="${___X_CMD_UNSEENCHAR_001}${___X_CMD_UNSEENCHAR_002}${___X_CMD_UNSEENCHAR_003}"
+___X_CMD_ADVISE_GEN_ADV_ERREXIT="${___X_CMD_UNSEENCHAR_001}${___X_CMD_UNSEENCHAR_002}${___X_CMD_UNSEENCHAR_003}"
 # useparam,name,synopsis,desc,exec,tldr,other,setup,tip,demo,subcmd,option,flag,[0-9]+,n
 
 ___x_cmd_advise_gen_advise__useparam()(
-    local mod_name="${1:?Provide mod name}"
-    local mod_path="${2:?Provide mod path}"
+    local mod_name="$1"
+    local mod_path="$2"
+    [ -n "$mod_name" ] || M="Please provide mod name" arg:ret:64
+    [ -d "$mod_path" ] || M="Unexisted directory of path. [path=$mod_path]" arg:ret:64
     xrc:mod "$mod_name/latest" || return 1
     local main_func; main_func="$___X_CMD_XRC_SET_MAIN"
     if [ -z "$main_func" ]; then
@@ -18,63 +20,108 @@ ___x_cmd_advise_gen_advise__useparam()(
         return 1
     }
 
-    advise:debug "useparam: X_CMD_ADVISE_FUNC_NAME=$main_func $main_func _x_cmd_advise_json"
+    advise:debug "Useparam - X_CMD_ADVISE_FUNC_NAME=$main_func $main_func _x_cmd_advise_json"
     X_CMD_ADVISE_FUNC_NAME="$main_func" "$main_func" _x_cmd_advise_json
 )
 
 ___x_cmd_advise_gen_advise__exec()(
-    local mod_path="${1:?Provide mod path}"; shift
+    local mod_path="$1"
+    arg:1:nonempty
+    shift
     x cd "$mod_path" || return 1
+    log:sub:init  -i gen_advise advise 'Executing'
     local cmd; printf "%s\n" "$*" | x jo env .\* cmd=. -- '
-    advise:warn "Executing: $cmd"
+    advise:warn "cmd - $cmd"
     ___x_cmd_evex "$cmd" 2>/dev/null || {
-        advise:error "Fail to exec: $cmd"
-        printf "%s\n" "$___X_CMD_ADVISE_ERREXIT"
+        advise:error "Fail to exec - $cmd"
+        printf "%s\n" "$___X_CMD_ADVISE_GEN_ADV_ERREXIT"
         exit 1
     }
 '
+    log:sub:fini
 )
+
+___x_cmd_advise_gen_advise__parse_adv_data(){
+    local mod_name="$1"
+    local mod_path="$2"
+    [ -n "$mod_name" ] || M="Please provide mod name" arg:ret:64
+    [ -d "$mod_path" ] || M="Unexisted directory of path. [path=$mod_path]" arg:ret:64
+    local adv_data="$mod_path/adv/data"
+    local res_data="$mod_path/res/data"
+    [ -d "$adv_data" ] || return
+    x mkdirp "$res_data"
+
+    find "$adv_data" | while read -r datafile; do
+        tagfile="${datafile#*"$adv_data/"}"
+        [ "$tagfile" != "$datafile" ] || continue
+        [ -f "$datafile" ] || {
+            x mkdirp "$res_data/$tagfile"
+            continue
+        }
+        case "$datafile" in
+            *.yml)
+                    advise:debug "Generate $mod_name res/data/${tagfile%.yml*}.jso from adv/data/$tagfile"
+                    < "$datafile" x yml y2j | ___x_cmd_advise_gen_advise__merge_awk > "$res_data/${tagfile%.yml*}.jso"
+                    ;;
+            *)      cp -r "$datafile" "$res_data/$tagfile" ;;
+        esac
+    done
+}
 
 ___x_cmd_advise_gen_advise__merge_awk(){
     command awk \
-    -v X_CMD_ADVISE_ERREXIT="$___X_CMD_ADVISE_ERREXIT" \
+    -v X_CMD_ADVISE_ERREXIT="$___X_CMD_ADVISE_GEN_ADV_ERREXIT" \
     -f "$___X_CMD_ROOT_MOD/awk/lib/default.awk" \
     -f "$___X_CMD_ROOT_MOD/awk/lib/j/json.awk"  \
     -f "$___X_CMD_ROOT_MOD/awk/lib/j/jiter.awk" \
     -f "$___X_CMD_ROOT_MOD/awk/lib/j/jcp.awk"   \
-    -f "$___X_CMD_ROOT_MOD/advise/lib/awk/build_merge.awk"
+    -f "$___X_CMD_ROOT_MOD/advise/lib/awk/gen.advise/build_merge.awk"
 }
 
+___x_cmd_advise_gen_advise___alreadylatest()(
+    arg:1:nonempty
+    x cd "$1" 2>/dev/null || exit 1
+    # check git last update
+    [ "$(git status -s | wc -l)" -eq 0 ] || return 1
+
+    local _expiration=86400 # 1-Day
+    local _fileage
+
+    # check files update.
+    [ -d res ] || return 1
+    find res -type f | while read -r adv_file; do
+        find adv lib latest -type f 2>/dev/null | x is newest "$adv_file" || return 1
+        _fileage="$(x fileage "$adv_file")"
+        advise:debug "{ filepath: $1/$adv_file, fileage: $_fileage, expiration: $_expiration }"
+        [ "$_fileage" -lt "$_expiration" ] || return 1
+    done
+)
+
 ___x_cmd_advise_gen_advise(){
-    local mod_name="${1:?Provide mod name}"
-    local mod_path="${2:?Provide mod path}"
+    arg:init advise
+    local mod_name="$1"
+    local mod_path="$2"
+    [ -n "$mod_name" ] || M="Please provide mod name" arg:ret:64
+    [ -d "$mod_path" ] || M="Unexisted directory of path. [path=$mod_path]" arg:ret:64
+
     local adv_dir="$mod_path/adv"
     local index_yml="$adv_dir/index.yml"
 
-    if [ ! -f "$index_yml" ]; then
-        advise:error "Not found $adv_dir/index.yml"
-        return 1
-    fi
+    [ -f "$index_yml" ] || M="Not found $adv_dir/index.yml" arg:ret:64
+
+    # ! ___x_cmd_advise_gen_advise___alreadylatest "$mod_path" || {
+    #     advise:info "Skip building advise.jso because it is the latest"
+    #     return 0
+    # }
+
     local resource;         resource="$mod_path/res";
     x rmrf "$resource";     x mkdirp "$resource"
 
     # parse adv/data dir
-    if [ -d "$adv_dir/data" ]; then
-        (
-            local res_data="$resource/data"; local datafile
-            x mkdirp "$res_data"
-            cd "$adv_dir/data" || exit
-            ls | while read -r datafile; do
-                case "$datafile" in
-                    *.yml)  < "$datafile" x y2j | ___x_cmd_advise_gen_advise__merge_awk > "$res_data/${datafile%.yml*}.jso" ;;
-                    *)      cp -r "$datafile" "$res_data/$datafile" ;;
-                esac
-            done
-        )
-    fi
+    ___x_cmd_advise_gen_advise__parse_adv_data "$mod_name" "$mod_path"
 
     # parse adv/index.yml
-    < "$index_yml" x y2j | {
+    < "$index_yml" x yml y2j | {
         local content;      content="$(cat)"
         printf "%s\n" "$content"
 
@@ -83,13 +130,13 @@ ___x_cmd_advise_gen_advise(){
             [ -z "$setup" ] || ___x_cmd_advise_gen_advise__exec "$mod_path" "$setup" || return 1
 
             find "$adv_dir" -maxdepth 1 -name '*.json' | while read -r jsonfile; do
-                advise:debug "cat $jsonfile"
+                advise:debug "Merge $jsonfile"
                 cat "$jsonfile"; printf "\n"
             done
 
             if [ "$useparam" = "true" ]; then
                 ___x_cmd_advise_gen_advise__useparam "$mod_name" "$mod_path"
-                [ "$?" = 0 ] || printf "%s\n" "$___X_CMD_ADVISE_ERREXIT"
+                [ "$?" = 0 ] || printf "%s\n" "$___X_CMD_ADVISE_GEN_ADV_ERREXIT"
             else printf "%s\n" "{}"    ; fi
         }
     } | ___x_cmd_advise_gen_advise__merge_awk > "$resource/advise.jso"
diff --git a/mod/advise/lib/man b/mod/advise/lib/man
--- a/mod/advise/lib/man
+++ b/mod/advise/lib/man
@@ -1,4 +1,4 @@
-# shellcheck shell=bash disable=SC2166,2012,2034,2207,1090
+# shellcheck shell=bash disable=SC2166,2012,2034,2207,1090,2076
 ___x_cmd_advise_man(){
     local op="$1"; [ "$#" -le 0 ] || shift
     case "$op" in
@@ -7,99 +7,139 @@ ___x_cmd_advise_man(){
         which)          ___x_cmd_advise_man_which "$@"      ;;
         load)           ___x_cmd_advise_man_load "$@"       ;;
         rm)             ___x_cmd_advise_man_rm "$@"         ;;
-        ""|-h|--help)   ___x_cmd_advise_gen_help "$___X_CMD_ROOT_MOD/advise/res/advise.jso" man ;;
+        ""|-h|--help)   ___x_cmd_advise_help man ;;
         *)              ___x_cmd_advise_man_load "$@"       ;;
     esac
 }
 
-___X_CMD_ADVISE_MAN_SRC_FOLDER="$___X_CMD_ROOT_TMP/advise/src"
-___X_CMD_ADVISE_MAN_COMPLETIONS_FOLDER="$___X_CMD_ROOT_TMP/advise/completions"
+___X_CMD_ADVISE_MAN_PKG="$___X_CMD_ROOT_SHARED/advise"
+
+___X_CMD_ADVISE_MAN_XCMD_FOLDER="$___X_CMD_ROOT_DATA/advise/xcmd"
+___X_CMD_ADVISE_MAN_COMPLETIONS_FOLDER="$___X_CMD_ROOT_DATA/advise/completions"
+___X_CMD_ADVISE_MAN_XCMD_PKG="$___X_CMD_ADVISE_MAN_PKG/all.tgz"
+___X_CMD_ADVISE_MAN_COMPLETIONS_PKG="$___X_CMD_ADVISE_MAN_PKG/$___X_CMD_CUR_SHELL-completions.7z"
+
+___x_cmd_is_suitable_advise_completion_env(){
+    ___x_cmd_is_suitable_advise_env || return 1
+    # bash >= 4.2
+    [ -z "$BASH_VERSION" ] || [ "${BASH_VERSINFO[0]}" -gt 4 ] || [ "${BASH_VERSINFO[0]}" -eq 4 -a "${BASH_VERSINFO[1]}" -ge 2 ] || return 1
+}
+
 if [[ "$BASH_VERSION" =~ (^5.*|^4.[2-3]) ]]; then  ___X_CMD_ADVISE_MAN_COMPLETIONS_FOLDER_CUR_SHELL="$___X_CMD_ADVISE_MAN_COMPLETIONS_FOLDER/bash-completions/share/bash-completion/completions"
 elif [ -n "$ZSH_VERSION" ];then ___X_CMD_ADVISE_MAN_COMPLETIONS_FOLDER_CUR_SHELL="$___X_CMD_ADVISE_MAN_COMPLETIONS_FOLDER/zsh-completions/src"
 fi
 
 ___x_cmd_advise_man_xcmd_exists(){
-    [ -d "$___X_CMD_ADVISE_MAN_SRC_FOLDER" ]
+    [ -d "$___X_CMD_ADVISE_MAN_XCMD_FOLDER" ]
 }
 ___x_cmd_advise_man_completion_exists(){
     [ -d "$___X_CMD_ADVISE_MAN_COMPLETIONS_FOLDER/$___X_CMD_CUR_SHELL-completions" ]
 }
+___x_cmd_advise_man_pkg_whether_not_update(){
+    # local _expiration=60 # Dev
+    local _expiration=259200 # 3-Day
+    local _fileage=
+    [ -f "$1" ] || return 1
+    _fileage="$( x fileage "$1" )"
+    # advise:warn --filepath "$1" --fileage "$_fileage" --expiration "$_expiration"
+    [ "$_fileage" -lt "$_expiration" ]
+}
 
+# Section: advise man install
 ___x_cmd_advise_man_completion_update(){
-    # bash >= 4.2
-    [ -z "$BASH_VERSION" ] || [ "${BASH_VERSINFO[0]}" -gt 4 ] || [ "${BASH_VERSINFO[0]}" -eq 4 -a "${BASH_VERSINFO[1]}" -ge 2 ] || return 1
-    local CACHE_COMPLETIONS="$___X_CMD_ROOT_TMP/advise/$___X_CMD_CUR_SHELL-completions.7z"
-    local folder="$___X_CMD_ADVISE_MAN_COMPLETIONS_FOLDER/$___X_CMD_CUR_SHELL-completions"
-    ___x_cmd_httpget_gitx static-build "$___X_CMD_CUR_SHELL"-completions main "$___X_CMD_CUR_SHELL-completions.7z" "$CACHE_COMPLETIONS" || {
-        advise:error "Fail to update $___X_CMD_CUR_SHELL-completions.7z from static-build/${___X_CMD_CUR_SHELL}-completions."
+    ___x_cmd_is_suitable_advise_completion_env || return 1
+    x rmrf "$___X_CMD_ADVISE_MAN_COMPLETIONS_PKG"
+    ___x_cmd_advise_man_completion_unzip
+}
+
+___x_cmd_advise_man_completion_download(){
+    ___x_cmd_is_suitable_advise_completion_env || return 1
+    advise:info "Download $___X_CMD_CUR_SHELL-completions.7z from static-build/${___X_CMD_CUR_SHELL}-completions"
+    ___x_cmd_httpget_gitx static-build "$___X_CMD_CUR_SHELL"-completions main "$___X_CMD_CUR_SHELL-completions.7z" "$___X_CMD_ADVISE_MAN_COMPLETIONS_PKG" || {
+        advise:error "Fail to download $___X_CMD_CUR_SHELL-completions.7z from static-build/${___X_CMD_CUR_SHELL}-completions"
         return 1
     }
+}
 
-    { x rmrf "$folder";   x mkdirp "$folder"; } 1>/dev/null 2>&1
-    ! x uz "$CACHE_COMPLETIONS" "$folder" || advise:info "Decompress: advise/$___X_CMD_CUR_SHELL-completions.7z to $folder"
-    x rmrf "$CACHE_COMPLETIONS"
+___x_cmd_advise_man_completion_unzip(){
+    ___x_cmd_is_suitable_advise_completion_env || return 1
+    [ -f "$___X_CMD_ADVISE_MAN_COMPLETIONS_PKG" ] || ___x_cmd_advise_man_completion_download || return 1
+    local folder="$___X_CMD_ADVISE_MAN_COMPLETIONS_FOLDER/$___X_CMD_CUR_SHELL-completions"
+    x rmrf "$folder"; x mkdirp "$folder"
+    ! x uz "$___X_CMD_ADVISE_MAN_COMPLETIONS_PKG" "$folder" || advise:debug "Decompress advise/$___X_CMD_CUR_SHELL-completions.7z to $folder"
 }
 
 ___x_cmd_advise_man_xcmd_update(){
-    local CACHE="$___X_CMD_ROOT_TMP/advise/all.tgz"
-    ___x_cmd_httpget_gitx x-cmd advise main "dist/all.tgz" "$CACHE" - || {
-        advise:error "Fail to update from x-cmd/advise."
+    x rmrf "$___X_CMD_ADVISE_MAN_XCMD_PKG"
+    ___x_cmd_advise_man_xcmd_unzip
+}
+
+___x_cmd_advise_man_xcmd_download(){
+    advise:info "Download all.tgz from x-cmd/advise"
+    ___x_cmd_httpget_gitx x-cmd advise main "dist/all.tgz" "$___X_CMD_ADVISE_MAN_XCMD_PKG" - || {
+        advise:error "Fail to download all.tgz from x-cmd/advise"
         return 1
     }
-
-    { x rmrf "$___X_CMD_ADVISE_MAN_SRC_FOLDER";   x mkdirp "$___X_CMD_ADVISE_MAN_SRC_FOLDER"; } 1>/dev/null 2>&1
-    ! x uz "$CACHE" "$___X_CMD_ADVISE_MAN_SRC_FOLDER" || advise:info "Decompress: advise/all.tgz to $___X_CMD_ADVISE_MAN_SRC_FOLDER"
-    x rmrf "$CACHE"
 }
+
+___x_cmd_advise_man_xcmd_unzip(){
+    [ -f "$___X_CMD_ADVISE_MAN_XCMD_PKG" ] || ___x_cmd_advise_man_xcmd_download || return 1
+    x rmrf "$___X_CMD_ADVISE_MAN_XCMD_FOLDER";   x mkdirp "$___X_CMD_ADVISE_MAN_XCMD_FOLDER"
+    ! x uz "$___X_CMD_ADVISE_MAN_XCMD_PKG" "$___X_CMD_ADVISE_MAN_XCMD_FOLDER" || advise:debug "Decompress advise/all.tgz to $___X_CMD_ADVISE_MAN_XCMD_FOLDER"
+}
+
+# EndSection
 
 ___x_cmd_advise_man_update(){
     case "$1" in
         x-cmd)          ___x_cmd_advise_man_xcmd_update ;;
         completion)     ___x_cmd_advise_man_completion_update ;;
+        x.advise.jso)   ___x_cmd_advise_man_gen_x_advise_force ;;
         all)            ___x_cmd_advise_man_xcmd_update
-                        ___x_cmd_advise_man_completion_update ;;
-        *)              ___x_cmd_advise_gen_help "$___X_CMD_ROOT_MOD/advise/res/advise.jso" man update
+                        ___x_cmd_advise_man_completion_update
+                        ___x_cmd_advise_man_gen_x_advise_force ;;
+        *)              ___x_cmd_advise_help man update
     esac
 }
 
 ___x_cmd_advise_man_ls(){
-    ___x_cmd_advise_man_xcmd_exists || ___x_cmd_advise_man_xcmd_update || return
+    ___x_cmd_advise_man_xcmd_exists || ___x_cmd_advise_man_xcmd_unzip || return
     case "$1" in
-        x-cmd)              local line; ls "$___X_CMD_ADVISE_MAN_SRC_FOLDER" | while read -r line; do
+        x-cmd)              local line; ls "$___X_CMD_ADVISE_MAN_XCMD_FOLDER" | while read -r line; do
                                 [ "$line" = "LICENSE" ] || printf "%s\n" "$line"
                             done ;;
-        npx)                ls "$___X_CMD_ADVISE_MAN_SRC_FOLDER/npx/_" ;;
-        pipx)               ls "$___X_CMD_ADVISE_MAN_SRC_FOLDER/pipx/_" ;;
-        docker)             ls "$___X_CMD_ADVISE_MAN_SRC_FOLDER/docker/_" ;;
-        completion)         if ___x_cmd_advise_man_completion_exists || ___x_cmd_advise_man_completion_update; then
+        npx)                ls "$___X_CMD_ADVISE_MAN_XCMD_FOLDER/npx/_" ;;
+        pipx)               ls "$___X_CMD_ADVISE_MAN_XCMD_FOLDER/pipx/_" ;;
+        docker)             ls "$___X_CMD_ADVISE_MAN_XCMD_FOLDER/docker/_" ;;
+        completion)         if ___x_cmd_advise_man_completion_exists || ___x_cmd_advise_man_completion_unzip; then
                                 ls "$___X_CMD_ADVISE_MAN_COMPLETIONS_FOLDER_CUR_SHELL"
                             fi ;;
-        -h|--help)          ___x_cmd_advise_gen_help "$___X_CMD_ROOT_MOD/advise/res/advise.jso" man ls ;;
+        -h|--help)          ___x_cmd_advise_help man ls ;;
         *)                  ___x_cmd_advise_man_ls x-cmd ;;
     esac
 }
 
 ___x_cmd_advise_man_xcmd_which(){
     if [[ "$1" =~ "-h|--help" ]]; then
-        ___x_cmd_advise_gen_help "$___X_CMD_ROOT_MOD/advise/res/advise.jso" man which x-cmd
+        ___x_cmd_advise_help man which x-cmd
         return 0
-    elif ___x_cmd_advise_man_xcmd_exists || ___x_cmd_advise_man_xcmd_update; then
-        local file; local IFS=" "; for file in "$1/advise.t.json" "npx/_/$1/advise.t.json" "pipx/_/$1/advise.t.json"; do
-            file="$___X_CMD_ADVISE_MAN_SRC_FOLDER/$file"
+    elif ___x_cmd_advise_man_xcmd_exists || ___x_cmd_advise_man_xcmd_unzip; then
+        local file; local IFS=" "; for file in "$1/advise.t.jso" "npx/_/$1/advise.t.jso" "pipx/_/$1/advise.t.jso"; do
+            file="$___X_CMD_ADVISE_MAN_XCMD_FOLDER/$file"
             [ -f "$file" ] || continue
             printf "%s\n" "$file"
             return 0
         done
     fi
-    printf "%s\n" "$___X_CMD_ADVISE_MAN_SRC_FOLDER"
+    printf "%s\n" "$___X_CMD_ADVISE_MAN_XCMD_FOLDER"
     return 1
 }
 
 ___x_cmd_advise_man_completion_which(){
     if [[ "$1" =~ "-h|--help" ]]; then
-        ___x_cmd_advise_gen_help "$___X_CMD_ROOT_MOD/advise/res/advise.jso" man which completion
+        ___x_cmd_advise_help man which completion
         return 0
-    elif ___x_cmd_advise_man_completion_exists || ___x_cmd_advise_man_completion_update; then
+    elif ___x_cmd_advise_man_completion_exists || ___x_cmd_advise_man_completion_unzip; then
         local file="$___X_CMD_ADVISE_MAN_COMPLETIONS_FOLDER_CUR_SHELL/$1"
         if [ -f "$file" ]; then printf "%s\n" "$file"
         else
@@ -113,7 +153,7 @@ ___x_cmd_advise_man_which(){
     case "$1" in
         x-cmd)          shift; ___x_cmd_advise_man_xcmd_which "$@" ;;
         completion)     shift; ___x_cmd_advise_man_completion_which "$@" ;;
-        *)              ___x_cmd_advise_gen_help "$___X_CMD_ROOT_MOD/advise/res/advise.jso" man which
+        *)              ___x_cmd_advise_help man which
     esac
 }
 
@@ -125,6 +165,7 @@ ___x_cmd_advise_man_xcmd_load_one(){
 }
 
 ___x_cmd_advise_man_xcmd_load_all(){
+    advise:debug "Load x-cmd/advise from $___X_CMD_ADVISE_MAN_XCMD_FOLDER"
     eval "$(___x_cmd_advise_man_ls x-cmd | command awk '
         {                           code = code " " $1;                                         }
         (NR % 50 == 0){             print "___x_cmd_advise_man_xcmd_load_one" code;      code = ""   }
@@ -133,55 +174,78 @@ ___x_cmd_advise_man_xcmd_load_all(){
 }
 
 ___x_cmd_advise_man_xcmd_load(){
-    if [[ "$1" =~ "-h|--help" ]]; then   ___x_cmd_advise_gen_help "$___X_CMD_ROOT_MOD/advise/res/advise.jso" man load x-cmd
-    elif [ "$#" -ge 1 ]; then            ___x_cmd_advise_man_xcmd_load_one "$@"
+    if [[ "$1" =~ "-h|--help" ]]; then
+        ___x_cmd_advise_help man load x-cmd
+        return 1
+    fi
+
+    ___x_cmd_advise_man_pkg_whether_not_update "$___X_CMD_ADVISE_MAN_XCMD_PKG" || ___x_cmd_advise_man_xcmd_update
+    if [ "$#" -ge 1 ]; then ___x_cmd_advise_man_xcmd_load_one "$@"
     else ___x_cmd_advise_man_xcmd_load_all
     fi
 }
 
 ___x_cmd_advise_man_completion_load(){
-    if ___x_cmd_advise_man_completion_exists || ___x_cmd_advise_man_completion_update; then
+    ___x_cmd_advise_man_pkg_whether_not_update "$___X_CMD_ADVISE_MAN_COMPLETIONS_PKG" || ___x_cmd_advise_man_completion_update
+    if ___x_cmd_advise_man_completion_exists || ___x_cmd_advise_man_completion_unzip; then
         local filename="$___X_CMD_ADVISE_MAN_COMPLETIONS_FOLDER/$___X_CMD_CUR_SHELL-completions/completions.sh"
         if [ -f "$filename" ]; then
-            advise:debug "source $___X_CMD_CUR_SHELL completions from $filename"
+            advise:debug "Load $___X_CMD_CUR_SHELL completions from $filename"
             .  "$filename"
         fi
     fi
+}
+
+___x_cmd_advise_man_x_load(){
+    advise:debug "Load x advise of $___X_CMD_ADVISE_MAN_CACHE_X_ADVISE_JSO"
+    ___x_cmd_advise_man_gen_x_advise
+    ___x_cmd_advise init x "$___X_CMD_ADVISE_MAN_CACHE_X_ADVISE_JSO"
 }
 
 ___x_cmd_advise_man_load(){
     case "$1" in
         x-cmd)          shift; ___x_cmd_advise_man_xcmd_load "$@" ;;
         completion)     ___x_cmd_advise_man_completion_load ;;
-        all)            ___x_cmd_advise_man_xcmd_load
-                        ___x_cmd_advise_man_completion_load ;;
-        *)              ___x_cmd_advise_gen_help "$___X_CMD_ROOT_MOD/advise/res/advise.jso" man load ;;
+        all)            ___x_cmd_advise_man_completion_load
+                        ___x_cmd_advise_man_xcmd_load
+                        ___x_cmd_advise_man_x_load ;;
+        *)              ___x_cmd_advise_help man load ;;
     esac
 }
 
 ___x_cmd_advise_man_rm(){
+    local filepath=
     case "$1" in
-        x-cmd)      if [[ "$2" =~ "-h|--help" ]]; then
-                        ___x_cmd_advise_gen_help "$___X_CMD_ROOT_MOD/advise/res/advise.jso" man rm x-cmd
-                    elif ___x_cmd_advise_man_xcmd_exists; then
-                        advise:warn "Remove $___X_CMD_ADVISE_MAN_SRC_FOLDER/$2"
-                        rm -rf "$___X_CMD_ADVISE_MAN_SRC_FOLDER/$2"
-                    fi ;;
-        completion) if [[ "$2" =~ "-h|--help" ]]; then
-                        ___x_cmd_advise_gen_help "$___X_CMD_ROOT_MOD/advise/res/advise.jso" man rm completion
-                    elif ___x_cmd_advise_man_completion_exists; then
-                        advise:warn "$___X_CMD_ADVISE_MAN_COMPLETIONS_FOLDER/$___X_CMD_CUR_SHELL-completions"
-                        rm -rf "$___X_CMD_ADVISE_MAN_COMPLETIONS_FOLDER/$___X_CMD_CUR_SHELL-completions"
-                    fi ;;
-        *)          ___x_cmd_advise_gen_help "$___X_CMD_ROOT_MOD/advise/res/advise.jso" man rm ;;
+        x-cmd)
+            if [[ "$2" =~ "-h|--help" ]]; then
+                ___x_cmd_advise_help man rm x-cmd
+            elif ___x_cmd_advise_man_xcmd_exists; then
+                filepath="$___X_CMD_ADVISE_MAN_XCMD_FOLDER/$2"
+                [ -d "$filepath" ] || return
+                advise:warn "Remove $filepath"
+                x rmrf "$filepath"
+            fi ;;
+        completion)
+            if [[ "$2" =~ "-h|--help" ]]; then
+                ___x_cmd_advise_help man rm completion
+            elif ___x_cmd_advise_man_completion_exists; then
+                filepath="$___X_CMD_ADVISE_MAN_COMPLETIONS_FOLDER/$___X_CMD_CUR_SHELL-completions/src/$2"
+                [ -f "$filepath" ] || return
+                advise:warn "Remove $filepath"
+                x rmrf "$filepath"
+            fi ;;
+        *)  ___x_cmd_advise_help man rm ;;
     esac
 }
 
 ___x_cmd_advise_man_xcmd_completer() {
     # Interesting ... Passing
-    ___ADVISE_RUN_CMD_FOLDER="$___X_CMD_ADVISE_MAN_SRC_FOLDER" ___advise_run ""
+    ___X_CMD_ADVISE_RUN_CMD_FOLDER="$___X_CMD_ADVISE_MAN_XCMD_FOLDER" ___x_cmd_advise_run ""
 }
 
 ## Section man advise
-___x_cmd_advise_man__list(){ local IFS="$___X_CMD_UNSEENCHAR_NEWLINE"; candidate_exec_arr=( $(___x_cmd_advise_man_ls $1 ) ); }
+___x_cmd_advise_man__list(){
+    local IFS="$___X_CMD_ADVISE_IFS_INIT"
+    candidate_exec_arr=( $(___x_cmd_advise_man_ls "$1" ) )
+}
 ## EndSection
diff --git a/mod/advise/lib/util b/mod/advise/lib/util
--- a/mod/advise/lib/util
+++ b/mod/advise/lib/util
@@ -1,42 +1,44 @@
 # shellcheck shell=bash
-___X_CMD_ADVISE_IFS_INIT="$(printf " \t")$___X_CMD_UNSEENCHAR_NEWLINE"
-___advise_completer() {
+___X_CMD_ADVISE_IFS_INIT="$___X_CMD_UNSEENCHAR_NEWLINE"
+___x_cmd_advise_completer() {
     # Interesting ... Passing
-    ___ADVISE_RUN_CMD_FOLDER= ___advise_run ""
+    ___X_CMD_ADVISE_RUN_CMD_FOLDER="" ___x_cmd_advise_run ""
 }
 
-___advise_update(){
-    local func="${1:?Provide function name}"
-    local tmp_filepath=${TMPDIR%/}/.x-cmd/advise_auto_json/$func
+___x_cmd_advise_update(){
+    local func="$1"
+    arg:init advise
+    [ -n "$func" ] || M="Provide function name" arg:ret:64
+    local tmp_filepath="$___X_CMD_ADVISE_TMPDIR/$func"
 
     if [ -f "$tmp_filepath" ] && [ -z "$(find "$tmp_filepath" -mtime -1)" ]; then
-        rm -rf "$tmp_filepath"
-        ___advise_main "$func"
+        x rmrf "$tmp_filepath"
+        ___x_cmd_advise_main "$func"
     fi
 }
 
-___advise_main(){
-    local func="${1:?Provide function name}"
+___x_cmd_advise_main(){
+    local func="${1}"
+    arg:init advise
+    [ -n "$func" ] || M="Provide function name" arg:ret:64
     local filepath="${2}"
     local alias_name="${3}"
-    local advise_json_dir="$___X_CMD_ADVISE_TMPDIR"
-    local tmp_filepath
-    tmp_filepath=${advise_json_dir}/$func
+    local tmp_filepath="$___X_CMD_ADVISE_TMPDIR/$func"
 
-    x mkdirp "$advise_json_dir"
+    x mkdirp "$___X_CMD_ADVISE_TMPDIR"
 
     if [ "-" = "$filepath" ]; then
         filepath=$tmp_filepath
         cat >"$filepath"
     elif [ ! -f "$filepath" ]; then
-        # ___advise_update "$func"
+        # ___x_cmd_advise_update "$func"
         filepath=$tmp_filepath
         if [ ! -f "$filepath" ]; then
             local content
             advise:debug "Start generating advise for $func"
             content="$(___X_CMD_META_MODE=1 X_CMD_ADVISE_FUNC_NAME=$func "$func" _x_cmd_advise_json)"
             if [ ! $? -eq 0 ]; then
-                advise:error "___advise_main: X_CMD_ADVISE_FUNC_NAME=$func $func _x_cmd_advise_json: Failed to generate advise json"
+                advise:error "Failed to generate advise json - 'X_CMD_ADVISE_FUNC_NAME=$func $func _x_cmd_advise_json'"
                 return 1
             fi
             printf "%s" "$content" >"$filepath"
@@ -52,8 +54,8 @@ ___advise_main(){
         comp_word="$func"
     else
         eval "
-            ___advise_completer_$alias_name(){
-                ___ADVISE_RUN_CMD_FOLDER= ___advise_run $func
+            ___x_cmd_advise_completer_$alias_name(){
+                ___X_CMD_ADVISE_RUN_CMD_FOLDER= ___x_cmd_advise_run $func
             }"
         comp_word="$alias_name"
         alias_name="_$alias_name"
@@ -61,18 +63,19 @@ ___advise_main(){
 
     if [ -z "$ZSH_VERSION" ];then
         if [[ ! "$BASH_VERSION" =~ (^3.*|^4.[0-3]) ]]; then
-            complete -o nosort -F "___advise_completer$alias_name" "$comp_word"
+            complete -o nosort -F "___x_cmd_advise_completer$alias_name" "$comp_word"
         else
-            complete -F "___advise_completer$alias_name" "$comp_word"
+            complete -F "___x_cmd_advise_completer$alias_name" "$comp_word"
         fi
     else
-        compdef "___advise_completer$alias_name" "$comp_word"
+        compdef "___x_cmd_advise_completer$alias_name" "$comp_word"
     fi
 }
 
-___advise_get_result_from_awk(){
-    local filepath="${1:?Provide filepath}"
-
+___x_cmd_advise_get_result_from_awk(){
+    arg:init advise
+    arg:1:nonempty
+    local filepath="$1"
     local IFS="$___X_CMD_UNSEENCHAR_002"
     local s="${COMP_WORDS[*]}"
     s="${s#*"$IFS"}"
@@ -83,25 +86,28 @@ ___advise_get_result_from_awk(){
     case "$cur_1" in
         *@|*:)
             if [ "${COMP_LINE% }" != "${COMP_LINE}" ]; then
-                s="${s%$cur_1$IFS$cur}"
+                s="${s%"$cur_1""$IFS""$cur"}"
                 s="${s}${cur_1}$cur"
             fi
             ;;
         *)
     esac
-    ___x_cmd_advise__get_result_form_awk "$s"
+    ___x_cmd_advise_get_result_from_awk_ "$s"
 }
 
-___x_cmd_advise__get_result_form_awk(){
+___x_cmd_advise_get_result_from_awk_(){
+    local IFS="$___X_CMD_UNSEENCHAR_002"
     {
         printf "%s\n" "$*"
         cat "$filepath"
-    } | command awk \
+    } | ___X_CMD_ADVISE_DEV_MOD="$___X_CMD_ADVISE_DEV_MOD" \
+        command awk \
         -v ZSHVERSION="$ZSH_VERSION" \
         -v ADVISE_NO_COLOR="$NO_COLOR" \
         -v ___X_CMD_ROOT_MOD="$___X_CMD_ROOT_MOD" \
-        -v WHICHNET="$___X_CMD_WHICHNET" \
+        -v WEBSRC_REGION="$___X_CMD_WEBSRC_REGION" \
         -f "$___X_CMD_ROOT_MOD/awk/lib/default.awk" \
+        -f "$___X_CMD_ROOT_MOD/awk/lib/arr.awk" \
         -f "$___X_CMD_ROOT_MOD/awk/lib/sh.awk" \
         -f "$___X_CMD_ROOT_MOD/awk/lib/fs.awk" \
         -f "$___X_CMD_ROOT_MOD/awk/lib/j/json.awk" \
@@ -109,32 +115,31 @@ ___x_cmd_advise__get_result_form_awk(){
         -f "$___X_CMD_ROOT_MOD/awk/lib/j/jqparse.awk" \
         -f "$___X_CMD_ROOT_MOD/awk/lib/j/jop.awk" \
         -f "$___X_CMD_ROOT_MOD/awk/lib/j/jcp.awk" \
-        -f "$___X_CMD_ROOT_MOD/advise/lib/awk/util.awk" \
         -f "$___X_CMD_ROOT_MOD/advise/lib/awk/advise.obj.awk" \
-        -f "$___X_CMD_ROOT_MOD/advise/lib/awk/advise.complete.awk" \
-        -f "$___X_CMD_ROOT_MOD/advise/lib/awk/advise.parse_argument.awk" \
-        -f "$___X_CMD_ROOT_MOD/advise/lib/awk/advise.main.awk"
+        -f "$___X_CMD_ROOT_MOD/advise/lib/awk/advise.share.awk" \
+        -f "$___X_CMD_ROOT_MOD/advise/lib/awk/advise/advise.util.awk" \
+        -f "$___X_CMD_ROOT_MOD/advise/lib/awk/advise/advise.complete.awk" \
+        -f "$___X_CMD_ROOT_MOD/advise/lib/awk/advise/advise.parse_argument.awk" \
+        -f "$___X_CMD_ROOT_MOD/advise/lib/awk/advise/advise.main.awk"
 }
 
-___advise_run_filepath_(){
+___x_cmd_advise_run_filepath_(){
     case "$1" in
-        /*) ___ADVISE_RUN_FILEPATH_="$1" ;;
-        -)  ___ADVISE_RUN_FILEPATH_=/dev/stdin ;;
-        *)  ___ADVISE_RUN_FILEPATH_="$___ADVISE_RUN_CMD_FOLDER/$1"
-            [ ! -f "$___ADVISE_RUN_FILEPATH_" ] || return 0
-            ___ADVISE_RUN_FILEPATH_="$___ADVISE_RUN_CMD_FOLDER/$1/advise.json"
-            [ ! -f "$___ADVISE_RUN_FILEPATH_" ] || return 0
-            ___ADVISE_RUN_FILEPATH_="$___ADVISE_RUN_CMD_FOLDER/$1/advise.t.json"
-            [ ! -f "$___ADVISE_RUN_FILEPATH_" ] || return 0
-            ___ADVISE_RUN_FILEPATH_="$(___x_cmd_advise_man_which x-cmd "$1")"
+        /*) ___X_CMD_ADVISE_RUN_FILEPATH_="$1" ;;
+        -)  ___X_CMD_ADVISE_RUN_FILEPATH_=/dev/stdin ;;
+        *)  for file in "$1" "$1/advise.t.jso" "$1/advise.json"; do
+                ___X_CMD_ADVISE_RUN_FILEPATH_="$___X_CMD_ADVISE_RUN_CMD_FOLDER/$file"
+                [ ! -f "$___X_CMD_ADVISE_RUN_FILEPATH_" ] || return 0
+            done
+            ___X_CMD_ADVISE_RUN_FILEPATH_="$(___x_cmd_advise_man_which x-cmd "$1")"
             ;;
     esac
-    [ ! -f "$___ADVISE_RUN_FILEPATH_" ] || return 0
+    [ ! -f "$___X_CMD_ADVISE_RUN_FILEPATH_" ] || return 0
     return 1
 }
 
 if [ -n "$BASH_VERSION" ]; then
-__ltrim_bash_completions(){
+___x_cmd_advise___ltrim_bash_completions(){
     local cur="$1"; shift
     local prefix_word; local i; while [ "$#" -ge 1 ]; do
         i=${#COMPREPLY[*]}
@@ -153,20 +158,20 @@ fi
 
 ___x_cmd_advise_init(){
     case "$1" in
-        -h|--help)      ___x_cmd_advise_gen_help "$___X_CMD_ROOT_MOD/advise/res/advise.jso" "init|new" ;;
-        *)              ___advise_main "$@"
+        -h|--help)      ___x_cmd_advise_help "init|new" ;;
+        *)              ___x_cmd_advise_main "$@"
     esac
 }
 ___x_cmd_advise_ls(){
     case "$1" in
-        -h|--help)      ___x_cmd_advise_gen_help "$___X_CMD_ROOT_MOD/advise/res/advise.jso" ls ;;
+        -h|--help)      ___x_cmd_advise_help ls ;;
         *)              [ ! -d "$___X_CMD_ADVISE_TMPDIR" ] || ls "$___X_CMD_ADVISE_TMPDIR"
     esac
 }
 
 ___x_cmd_advise_rm(){
     case "$1" in
-        -h|--help)      ___x_cmd_advise_gen_help "$___X_CMD_ROOT_MOD/advise/res/advise.jso" rm ;;
+        -h|--help)      ___x_cmd_advise_help rm ;;
         "")             x rmrf "$___X_CMD_ADVISE_TMPDIR" ;;
         *)              local filepath="$___X_CMD_ADVISE_TMPDIR/$1"
                         [ -f "$filepath" ] || return 1
@@ -176,7 +181,7 @@ ___x_cmd_advise_rm(){
 
 ___x_cmd_advise_which(){
     case "$1" in
-        -h|--help)      ___x_cmd_advise_gen_help "$___X_CMD_ROOT_MOD/advise/res/advise.jso" which ;;
+        -h|--help)      ___x_cmd_advise_help which ;;
         "")             printf "%s" "$___X_CMD_ADVISE_TMPDIR" ;;
         *)              local filepath="$___X_CMD_ADVISE_TMPDIR/$1"
                         [ -f "$filepath" ] || return 1
@@ -186,7 +191,7 @@ ___x_cmd_advise_which(){
 
 ___x_cmd_advise_cat(){
     case "$1" in
-        -h|--help)      ___x_cmd_advise_gen_help "$___X_CMD_ROOT_MOD/advise/res/advise.jso" cat ;;
+        -h|--help)      ___x_cmd_advise_help cat ;;
         *)              local filepath="$___X_CMD_ADVISE_TMPDIR/$1"
                         [ -f "$filepath" ] || return 1
                         < "$filepath" x jo
diff --git a/mod/env/lib/config b/mod/env/lib/config
--- a/mod/env/lib/config
+++ b/mod/env/lib/config
@@ -1,6 +1,6 @@
 # shellcheck    shell=sh            disable=SC3043      # xrc
 
-___X_CMD_ENV_VERSION_CONFIG_PATH="$___X_CMD_ROOT/.boot/env"
+___X_CMD_ENV_VERSION_CONFIG_PATH="$___X_CMD_ROOT_DATA/env/version"
 xrc path
 
 ___x_cmd_env_config_load(){
@@ -31,11 +31,16 @@ ___x_cmd_env_config___write(){
     local tgt="${2:-"$___X_CMD_ENV_VERSION_CONFIG_PATH"}"
 
     if ! x touch "$tgt"; then
-        env:error "Couldn't create file: ${tgt}"
+        env:error "Couldn't create file - '${tgt}'"
         return 1
     fi
 
-    printf "%s\n" "$configstr" > "$tgt"
+    printf "%s\n" "$configstr" > "$tgt" || {
+        env:error "Couldn't write to file - '${tgt}'"
+        return 1
+    }
+
+    env:info "Config file saved to $tgt"
 }
 
 ___x_cmd_env___configstr_set_(){
diff --git a/mod/env/lib/exec b/mod/env/lib/exec
--- a/mod/env/lib/exec
+++ b/mod/env/lib/exec
@@ -1,11 +1,17 @@
 # shellcheck    shell=sh            disable=SC3043      # xrc
 
 ___x_cmd_env_exec(){
-    if ___x_cmd_env_exec___execuatable "$@"; then
-        ___x_cmd_env_exec___set_and_run_and_unset "$@"
-    else
-        ___x_cmd_env_exec___set "$@"
+    case "$1" in
+        -h|--help)  x help -g "$___X_CMD_ROOT_MOD/env/res/advise.jso" exec ; return 1 ;;
+    esac
+
+    if ! ___x_cmd_env_exec___execuatable "$@"; then
+        env:error "No executable command found. Please use '--' to separate command and arguments."
+        env:error "Example 'x env exec node=v18.12.0 -- node helloworld.js'"
+        return 1
     fi
+
+    ___x_cmd_env_exec___set_and_run_and_unset "$@"
 }
 
 ___x_cmd_env_exec___execuatable(){
@@ -18,6 +24,7 @@ ___x_cmd_env_exec___execuatable(){
     return 1
 }
 
+# WHY？
 ___x_cmd_env_exec___set(){
     while [ $# -gt 0 ]; do
         case "$1" in
@@ -53,7 +60,7 @@ ___x_cmd_env_exec___set_and_run_and_unset(){
             *=*)
                 ___x_cmd_env_exec___set_and_run_and_unset_recover_ "${1%=*}"
                 if ! ___x_cmd_pkg install "${1%=*}" "${1#*=}"; then
-                    env:error "Cannot install package: ${1%=*} ${1#*=}"
+                    env:error "Cannot install package - '${1%=*} ${1#*=}'"
                     return 1
                 fi
                 ___x_cmd_pkg activate "${1%=*}" "${1#*=}"
diff --git a/mod/env/lib/main b/mod/env/lib/main
--- a/mod/env/lib/main
+++ b/mod/env/lib/main
@@ -19,14 +19,11 @@ ___x_cmd_env___pasre_pkg_version(){
 
 # use = try + save-config
 ___x_cmd_env_use(){
-    local ___X_CMD_ENV_LSENV_VERSION
-    local ___X_CMD_ENV_LSENV_CANDIDATE
-    local ___X_CMD_ENV_LSENV_FINAL_COMMAND
-    [ $# -gt 0 ] || ___x_cmd_env_lsenv_app
-    [ "$___X_CMD_ENV_LSENV_FINAL_COMMAND" = "ENTER" ] || return 1
-    if [ -n "$___X_CMD_ENV_LSENV_CANDIDATE" ] && [ -n "$___X_CMD_ENV_LSENV_VERSION" ]; then
-        set -- "$___X_CMD_ENV_LSENV_CANDIDATE=$___X_CMD_ENV_LSENV_VERSION"
-    fi
+    local ___X_CMD_ENV___PARSE_VERSION
+    local ___X_CMD_ENV___PARSE_PKG
+    local ___X_CMD_ENV_LSENV_APP_CANDIDATE
+    [ $# -gt 0 ] || ___x_cmd_env_lsenv_app || return 1
+    [ -z "$___X_CMD_ENV_LSENV_APP_CANDIDATE" ] || set -- "$___X_CMD_ENV_LSENV_APP_CANDIDATE"
 
     x:trace env/use
     if ! ___x_cmd_env_try "$@" ; then
@@ -44,7 +41,7 @@ ___x_cmd_env_use(){
         fi
 
         script_path="$(___x_cmd_pkg___get_script_path "$___X_CMD_ENV___PARSE_PKG" "$___X_CMD_ENV___PARSE_VERSION" "" activate)"
-        env:debug "script_path: ""$script_path" "___X_CMD_ENV___PARSE_PKG: " "$___X_CMD_ENV___PARSE_PKG" "___X_CMD_ENV___PARSE_VERSION: " "$___X_CMD_ENV___PARSE_VERSION"
+        env:debug "{ script_path: ""$script_path", "___X_CMD_ENV___PARSE_PKG: " "$___X_CMD_ENV___PARSE_PKG", "___X_CMD_ENV___PARSE_VERSION: " "$___X_CMD_ENV___PARSE_VERSION }"
         code="$code $___X_CMD_ENV___PARSE_PKG=$___X_CMD_ENV___PARSE_VERSION=$script_path"
     done
 
@@ -55,7 +52,7 @@ ___x_cmd_env_use(){
 ___x_cmd_env_unuse(){
     x:trace env/unuse
     ___x_cmd_env_untry "$@" || {
-        env:error "Cannot untry " "$@"
+        env:error "Cannot untry $@"
         return 1
     }
 
@@ -72,21 +69,25 @@ ___x_cmd_env_unuse(){
 
 # try = install + activate
 ___x_cmd_env_try(){
+    case "$1" in
+        -h|--help) x help -g "$___X_CMD_ROOT_MOD/env/res/advise.jso" try ; return 1 ;;
+    esac
+
     x:trace env/try
     local ___X_CMD_ENV___PARSE_PKG
     local ___X_CMD_ENV___PARSE_VERSION
 
-    local code="___x_cmd_env___configstr_set_ \"\$___X_CMD_ENV_VERSION_CONFIG\""
+    local code
     local i; for i in "$@"; do
         ___x_cmd_env___pasre_pkg_version "$i"
         if [ -z "$___X_CMD_ENV___PARSE_VERSION" ]; then
-            env:warn "Not found $___X_CMD_ENV___PARSE_PKG version."
+            env:warn "Not found $___X_CMD_ENV___PARSE_PKG version"
             continue
         fi
 
         env:debug "Prepare $___X_CMD_ENV___PARSE_PKG $___X_CMD_ENV___PARSE_VERSION"
         if ! ___x_cmd_pkg install "$___X_CMD_ENV___PARSE_PKG" "$___X_CMD_ENV___PARSE_VERSION"; then
-            env:error "Cannot install package: $___X_CMD_ENV___PARSE_PKG $___X_CMD_ENV___PARSE_VERSION"
+            env:error "Cannot install package - '$___X_CMD_ENV___PARSE_PKG $___X_CMD_ENV___PARSE_VERSION'"
             return 1
         fi
 
@@ -109,7 +110,8 @@ ___x_cmd_env_try(){
         code="$code $___X_CMD_ENV___PARSE_PKG=$___X_CMD_ENV___PARSE_VERSION"
     done
 
-    local ___X_CMD_ENV___CONFIGSTR_SET_;    eval "$code"
+    local ___X_CMD_ENV___CONFIGSTR_SET_;    eval "___x_cmd_env___configstr_set_ \"\$___X_CMD_ENV_VERSION_CONFIG\" $code"
+    env:info "Success to set $code in this session "
     ___X_CMD_ENV_VERSION_CONFIG="$___X_CMD_ENV___CONFIGSTR_SET_"
 }
 
@@ -130,5 +132,6 @@ ___x_cmd_env_untry(){
     done
 
     local ___X_CMD_ENV___CONFIGSTR_SET_;    eval "$code"
+    env:info "Success to unset $* in this session "
     ___X_CMD_ENV_VERSION_CONFIG="$___X_CMD_ENV___CONFIGSTR_SET_"
 }
diff --git a/mod/gcode/lib/project/apply/index b/mod/gcode/lib/project/apply/index
--- a/mod/gcode/lib/project/apply/index
+++ b/mod/gcode/lib/project/apply/index
@@ -2,7 +2,7 @@
 
 # x gcode project apply a.yml lijunhao=edwinjhlee zhengyuhang=mnnna
 # x gcode project apply .x-cmd/apply/gitcode-project.yml  lijunhao=edwinjhlee
-
+# http://localhost:4000/13.7/ee/api/projects.html
 ___x_cmd_gcode_project_apply(){
     param:void
     if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then { ___x_cmd_gcode_project_apply__help; return 0; }
@@ -20,10 +20,10 @@ ___x_cmd_gcode_project_apply(){
             esac' |
              {
                 x jo env . content=. owner_project=.project  apply_member=.member
-                [ -n "$owner_project" ] || { gcode_log error "Not found apply configure project main key" >/dev/stderr; return 1; }
+                [ -n "$owner_project" ] || { gcode:error "Not found apply configure project main key" >/dev/stderr; return 1; }
                 ___x_cmd_gcode_project_apply__replace "$@"
                 printf "%s\n" "$content"
-                gcode_log info "Getting project info ..."
+                gcode:info "Getting project info ..."
                 ___x_cmd_gcode_project_apply__member_info
                 ___x_cmd_gcode_project_apply__project_info
             }
@@ -39,23 +39,24 @@ ___x_cmd_gcode_project_apply(){
                 -f "$___X_CMD_ROOT_MOD/gcode/lib/project/apply/apply.awk"
         }
     )"; then
-        # gcode_log debug "apply code: $code"
+        # gcode:debug "apply code: $code"
         # [ -n "$code" ] || {
-        #     printf "%s\n" ""; gcode_log info "Repo apply no changes required"
+        #     printf "%s\n" ""; gcode:info "Repo apply no changes required"
         #     return 0
         # }
-        # gcode_log info "Handling project by info ..."
+        # gcode:info "Handling project by info ..."
         # if [ -n "$___X_CMD_GH_DRY_RUN" ]; then      printf "%s\n" "$code";
         # else                                        eval "$code";
         # fi
         echo "$code"
     else
         code=$?
-        gcode_log error "Exit=$code. Fail to apply: $filepath" >/dev/stderr
+        gcode:error "Exit=$code. Fail to apply: $filepath" >/dev/stderr
     fi
 }
 
 # shellcheck disable=SC2154
+# http://localhost:4000/13.7/ee/api/members.html#get-a-member-of-a-group-or-project
 ___x_cmd_gcode_project_apply__member_info(){
     [ -n "$apply_member" ] || { printf "\n"; return 0; }
 
@@ -63,6 +64,7 @@ ___x_cmd_gcode_project_apply__member_info(){
     # cat "$(x wsroot)"/.x-cmd/project_member.json | x ja t "\t" ; printf "\n"
 }
 
+# http://localhost:4000/13.7/ee/api/projects.html#get-single-project
 ___x_cmd_gcode_project_apply__project_info(){
     NO_CACHE=1  x gcode project info --json "$owner_project" | x ja t "\t" ; printf "\n"
     # cat "$(x wsroot)"/.x-cmd/project_info.json | x ja t "\t" ; printf "\n"
diff --git a/mod/gcode/lib/utils b/mod/gcode/lib/utils
--- a/mod/gcode/lib/utils
+++ b/mod/gcode/lib/utils
@@ -2,60 +2,123 @@
 # shellcheck disable=SC2039,3043
 # shellcheck disable=SC2046
 
+# Section: Help
+_____x_cmd_gcode_help__token_setting(){
+    printf "\n%s %s \n%s\n" \
+        "$(___x_cmd_ui yellow 'Run command to add|repleace token:')" \
+        "$(___x_cmd_ui bold cyan "\`x gcode token <token>\`")"   \
+        "$(___x_cmd_ui 'https://gitcode.net/-/profile/personal_access_tokens')"
+}
+
+_____x_cmd_gcode_help(){
+    command -v ___x_cmd_advise_gen_help >/dev/null || xrc:mod advise/lib/gen_help
+    ___x_cmd_advise_gen_help "$___X_CMD_ROOT_MOD/gcode/res/advise.jso" "$@"
+}
+
+# EndSection
+
 # Section: HTTP header & body & request
 ___x_cmd_gcode_resp_header(){
    cat "$___X_CMD_GCODE_TMP/.____x_cmd_gcode_curl_header"
 }
 
-# TODO:HTTP CODE
-______x_cmd_gcode_resp_header_code(){
+___x_cmd_gcode_resp_code(){
     ___x_cmd_gcode_resp_header  | awk '$1 ~/HTTP\/1.1$/ {print ($2+0);exit(0)}'
 }
 
 ___x_cmd_gcode_curl(){
     local op="$1"
-    local url="\"https://gitcode.net/api/v4$2\""
+    local _curl_url="\"${___X_CMD_GCODE_DOMAIN:-"https://gitcode.net"}/api/v4${2}\""
+    local _content_type="\"Content-Type: application/json\""
+    local _authorization
+    _authorization="\"PRIVATE-TOKEN: $(___x_cmd_gcode_token)\""
     local gcode_header="$___X_CMD_GCODE_TMP/.____x_cmd_gcode_curl_header"
-    local Type="\"Content-Type: application/json\""
-    local Authorization
-    Authorization="\"PRIVATE-TOKEN: $(___x_cmd_gcode_token)\""
+    local ___X_CMD_GCODE_SHOW_HTTP_CODE=1
     shift 2
     local req
     case "$op" in
         get)
-            gcode_log debug           "eval x curl -D  $gcode_header   -X GET -s -H  $Type  -H  $Authorization  $(eval "printf '%s ' $(x curl gencode -G $([ $# -eq 0 ] || printf "%s== " "$@"))")  $url"
-            x ccmd 3m --            eval x curl -D "$gcode_header"  -X GET -s -H "$Type" -H "$Authorization" $(eval "printf '%s ' $(x curl gencode -G $([ $# -eq 0 ] || printf "%s== " "$@"))") "$url"
-            ___x_cmd_gcode_http_error  eval x curl -D "$gcode_header"  -X GET -s -H "$Type" -H "$Authorization" $(eval "printf '%s ' $(x curl gencode -G $([ $# -eq 0 ] || printf "%s== " "$@"))") "$url"
+            gcode:debug   "x curl -D  $gcode_header   -X GET -s -H  $_content_type  -H  $_authorization  $(eval "printf '%s ' $(x curl gencode $(___x_cmd_gcode_curl___use_query_data "$@"))")  $_curl_url"
+            if [ -n "$NO_CACHE" ]; then
+                eval       x curl -D "$gcode_header"  -X GET -s -H "$_content_type" -H "$_authorization" $(eval "printf '%s ' $(x curl gencode $(___x_cmd_gcode_curl___use_query_data "$@"))") "$_curl_url"
+            else
+                x ccmd 10s --         eval x curl -D "$gcode_header"  -X GET -s -H "$_content_type" -H "$_authorization" $(eval "printf '%s ' $(x curl gencode $(___x_cmd_gcode_curl___use_query_data "$@"))") "$_curl_url"
+            fi
+            ___x_cmd_gcode_http_error eval x curl -D "$gcode_header"  -X GET -s -H "$_content_type" -H "$_authorization" $(eval "printf '%s ' $(x curl gencode $(___x_cmd_gcode_curl___use_query_data "$@"))") "$_curl_url"
             return
             ;;
-        post)
-            req="POST";;
-        put)
-            req="PUT";;
-        patch)
-            req="PATCH";;
-        delete)
-            req="DELETE";;
+        upload)
+            local __file_path="${1?:"Please provide upload filepath"}"; shift;
+            [ -f "$__file_path" ] || {
+                gcode:error "Upload Failure: Not found target file. Please check file exist: $__file_path"
+                return 1
+            }
+            gcode:debug "x curl --progress-bar -D  $gcode_header   -X  ${___X_CMD_GCODE_UPLOAD_REQ_METHOD:-"POST"}  -H  $_authorization  --form  file=@${__file_path}    $(x curl gencode "$@")   $_curl_url"
+            eval         x curl --progress-bar -D "$gcode_header"  -X "${___X_CMD_GCODE_UPLOAD_REQ_METHOD:-"POST"}" -H "$_authorization" --form  file=@"${__file_path}" "$(x curl gencode "$@")" "$_curl_url"
+            ___x_cmd_gcode_http_error; return
+        ;;
+        post)           req="POST"      ;;
+        put)            req="PUT"       ;;
+        patch)          req="PATCH"     ;;
+        delete)         req="DELETE"    ;;
     esac
-    gcode_log debug "eval x curl -D $gcode_header -X $req    -s -H $Type -H $Authorization $(x curl gencode "$@") $url"
-
-    eval x curl -D "$gcode_header" -X "$req"    -s -H "$Type" -H "$Authorization" "$(x curl gencode "$@")" "$url"
+    gcode:debug "x curl -D  $gcode_header  -X  $req  -s -H  $_content_type  -H  $_authorization   $(x curl gencode "$@")   $_curl_url"
+    eval         x curl -D "$gcode_header" -X "$req" -s -H "$_content_type" -H "$_authorization" "$(x curl gencode "$@")" "$_curl_url"
+    ___x_cmd_gcode_http_error
 }
 
 ___x_cmd_gcode_http_error(){
     local http_resp_code
-    http_resp_code=$(______x_cmd_gcode_resp_header_code)
-    if [ -n "$http_resp_code" ] && [ "$http_resp_code" -ge 200 ] && [ "$http_resp_code" -le 303 ]; then
+    http_resp_code=$(___x_cmd_gcode_resp_code)
+    if [ -n "$http_resp_code" ] && [ "$http_resp_code" -ge 100 ] && [ "$http_resp_code" -le 303 ]; then
         return 0
     else
-        [ $# -eq 0 ] || x ccmd invalidate "$@" >/dev/null
-        gcode_log error "HTTP Code Is $http_resp_code"
+        [ $# -eq 0 ] || {
+            gcode:debug "---! Cache Clear !---"
+            x ccmd invalidate "$@" 1>/dev/null 2>&1
+        }
+        [ -z "$___X_CMD_GCODE_SHOW_HTTP_CODE" ] || {
+            gcode:error "HTTP Code is $http_resp_code"
+            if command -v unset 1>/dev/null; then
+                unset ___X_CMD_GCODE_SHOW_HTTP_CODE
+            fi
+        }
         return 1
     fi
+}
+
+# shellcheck disable=SC2154
+___x_cmd_gcode_curl___use_query_data(){
+    [ $# -gt 0 ] || return
+    local name
+    printf "%s " "-G"
+    for name in "$@";
+    do
+        if [ "$name" = "p" ];then  [ -z "$p" ] || printf "%s " "path==$p";
+        else                                      printf "%s " "$name==" ;
+        fi
+    done
+}
+
+___x_cmd_gcode____handle_resp(){
+    [ -z "$gcode_resp_body" ] || printf "%s" "$gcode_resp_body"
+    [ -z "$gcode_resp_err" ]  || printf "  \033[31m-\033[0m \033[1mErrorMsg: \033[31m%s\033[0m\n" "$gcode_resp_err" >&2
 }
 # EndSection
 
 # Section: pagination
+___gcode_ui_mutual() {
+    local tmp="$1"
+    shift 1
+    if [ -n "$json" ] || [ -n "$ENFORCE_JSON" ] ; then
+        ENFORCE_JSON=1 "$@"
+    else
+        # run ui table
+        eval "$tmp"
+    fi
+    return
+}
+
 ___x_cmd_gcode_get_multi() {
     if [ -n "$page" ] || [ -n "$per_page" ]; then
         ___x_cmd_gcode_curl get "$@" page per_page
@@ -131,10 +194,11 @@ _____x_cmd_gcode_next_url(){
 
 # Section: Parameter Utilities
 alias ___x_cmd_gcode_param_init_owner_project='
-    local owner_project
+    local owner_project=""
     ___x_cmd_gcode_param_normalize_repo  || return
 '
 
+# shellcheck disable=SC2154,SC2034
 ___x_cmd_gcode_param_normalize_repo(){
     local op="$project"
     [ -z "$op" ] && op="$1"
@@ -148,7 +212,9 @@ ___x_cmd_gcode_param_normalize_repo(){
     *)
         ___x_cmd_gcode_current_owner 1>/dev/null
         if [ -z "$___X_CMD_GCODE_DEFAULT_OWNER" ]; then
-            printf "No owner provided. Default owner not set.\n" >&2
+            gcode:error "No owner provided. Default owner not set."
+            gcode:warn "Check your current token setting.$(_____x_cmd_gcode_help__token_setting)"
+            return 1
         fi
         owner_project="$(printf "%s" "$___X_CMD_GCODE_DEFAULT_OWNER/$op")"
         ;;
@@ -164,21 +230,9 @@ _____x_cmd_git_repo(){
     repo="${repo%.*}"
     printf "%s" "$repo"
 }
-
-___gcode_ui_mutual() {
-    local tmp="$1"
-    shift 1
-    if [ -n "$json" ] || [ -n "$ENFORCE_JSON" ] ; then
-        ENFORCE_JSON=1 "$@"
-    else
-        # run ui table
-        eval "$tmp"
-    fi
-    return
-}
 # EndSection
 
-# Section: gcode member access
+# Section: Resolve gitcode member access
 _____x_cmd_gcode_member_util(){
     case $access_level in
         owner)
diff --git a/mod/gh/lib/action/artifact b/mod/gh/lib/action/artifact
--- a/mod/gh/lib/action/artifact
+++ b/mod/gh/lib/action/artifact
@@ -1,15 +1,17 @@
 # shellcheck shell=sh disable=SC2039,3043,SC2154
 ___x_cmd_gh_action_artifact() {
-    param:subcmd  ___x_cmd_gh_action_artifact              \
+    param:subcmd  ___x_cmd_gh_action_artifact                           \
         "ls|l"               "List artifacts for a repository"          \
         "info|i"             "Get workflow run artifacts info"          \
         "rm"                 "Delete an artifact"                       \
-        "download|install"   "Download an artifact"
+        "download|install"   "Download an artifact"                     \
+        app                  "Interactive UI show artifact by owner"
     param:subcmd:try
     param:run
     ___x_cmd_gh_action_artifact _param_help_doc
     return 1
 }
+___x_cmd_gh_action_art(){ param:void; ___x_cmd_gh_action_artifact "$@"; }
 
 # Section: List
 # https://docs.github.com/en/rest/actions/artifacts#list-artifacts-for-a-repository
@@ -18,7 +20,7 @@ ___x_cmd_gh_action_artifact_ls(){
     param:scope ___x_cmd_github
     param:dsl <<A
 options:
-    --repo      "Provide owner name and repo name.(default:the current user repo)"      <>:RepoName
+    --repo|-r   "<ownerPath>/<RepoPath> (default ownerPath: current user)"              <>:RepoName
 
     --name      "Filters artifacts by exact match on their name field"                  <>=""
     --page      "Page number of the results to fetch."                                  <>:Numbers="1"
@@ -34,10 +36,60 @@ A
         eval "$___ls_tmp"
     else
         ___X_CMD_UI_STATIC=1 ___ui_table_json Artifact_ID=.id name=.name Size=.size_in_bytes Expired=.expired Created=.created_at -- \
-            "$___ls_tmp | x jo q0 .artifacts | ___x_cmd_resp___handle_table_pipe_data"
+            "$___ls_tmp | x jo q0 .artifacts"
     fi
 }
 
+# EndSection
+
+# Section: app
+___x_cmd_gh_action_artifact_app(){
+    param:scope ___x_cmd_github
+    param:dsl <<A
+type:
+    run_status = Success Failure
+options:
+    --repo|-r           "Provide owner name and repo name.(default:the current user repo)"      <>:RepoName
+
+    --branch            "Returns workflow runs associated with a branch."                       <>=""
+    --actor             "returns someone workflow runs."                                        <>:Username=""
+    --event             "Returns workflow run triggered by the event you specify."              <>=""
+    --sta|--status      "Returns workflow runs with the check run status."                      <>=""
+    --created           "Returns workflow runs created within the given date-time range."       <>=""
+    --check_suite_id    "Returns workflow runs with the check_suite_id that you specify."       <>=""
+    --exclude_pull_requests  "Not pull requests are omitted from the response "
+
+    --page              "Page number of the results to fetch."                                  <>="1"
+    --per_page          "Results per page (max 100)"                                            <>="30"
+A
+    param:run
+
+    ___x_cmd_gh_param_init_owner_repo
+
+    local ___gh_error_msg="get githubaction info list fail"
+    local ___X_CMD_TUI_TABLE_FINAL_COMMAND
+    local ___X_CMD_TUI_TABLE_CUR_LINE
+    local ___X_CMD_TUI_TABLE_CUR_ITEM
+    local ___X_CMD_GH_TUI_TABLE_REQUSET_DATA='___x_cmd_gh_curl get /repos/${owner_repo}/actions/artifacts name per_page page'
+    ___x_cmd_gh_tui_app "action.artifact.app.awk"
+
+   ___x_cmd_gh_action_artifact_app_status_handler
+}
+
+___x_cmd_gh_action_artifact_app_status_handler(){
+
+    local artifact_id
+    artifact_id="${___X_CMD_TUI_TABLE_CUR_LINE##*Artifact_ID: }"
+    artifact_id=${artifact_id%%
+Name:*}
+    case "$___X_CMD_TUI_TABLE_FINAL_COMMAND" in
+            "ENTER")        printf "%s\n" "$___X_CMD_TUI_TABLE_FINAL_COMMAND"  ;;
+            "i")            ___x_cmd_gh_action_artifact_info              --repo "${repo}"   $artifact_id            ;;
+            "d")            ___x_cmd_gh_action_artifact_rm                --repo "${repo}"   $artifact_id            ;;
+            "a")            ___x_cmd_gh_action_artifact_download          --repo "${repo}"   $artifact_id            ;;
+            *)              return
+    esac
+}
 # EndSection
 
 # Section: Info
@@ -47,28 +99,29 @@ ___x_cmd_gh_action_artifact_info(){
     param:dsl <<A
 options:
     #1          "artifact id"                                                           <>:Number
-    --repo      "Provide owner name and repo name.(default:the current user repo)"      <>:RepoName
+    --repo|-r   "<ownerPath>/<RepoPath> (default ownerPath: current user)"              <>:RepoName
     --json|-j   "output json data"
 A
     param:run
     ___x_cmd_gh_param_init_owner_repo
-    ___x_cmd_gh_curl get "/repos/${owner_repo}/actions/artifacts/${1##*/}" | ___x_cmd_gh_action_artifact_info_status_handler "${owner_repo}" "${1##*/}"
+    ___x_cmd_gh_curl get "/repos/${owner_repo}/actions/artifacts/${1##*/}" | ___x_cmd_gh_action_artifact_info____ui_handler "${owner_repo}" "${1##*/}"
 
 }
 
-___x_cmd_gh_action_artifact_info_status_handler(){
+___x_cmd_gh_action_artifact_info____ui_handler(){
     if [ -n "$json" ] || [ -n "$ENFORCE_JSON" ]; then
         cat
         ___x_cmd_gh_http_error
         return
     fi
     (
-        x jo env . id=.id name=.name size_in_bytes=.size_in_bytes expired=.expired created_at=.created_at expires_at=.expires_at gh_resp_err=.message
+        x jo env . id=.id name=.name size_in_bytes=.size_in_bytes expired=.expired created_at=.created_at expires_at=.expires_at \
+            gh_resp_msg=.message gh_resp_err=.errors
         if [ -n "$name" ]; then
-            ___x_cmd_ui_tf true  "Get $1 $id artifact info successfully" "Name: $name" "Size_Bytes: $size_in_bytes" "Expired: $expired" \
+            ___x_cmd_ui_tf true "Get $1 $id artifact info successfully:" "Name: $name" "Size_Bytes: $size_in_bytes" "Expired: $expired" \
                 "Created_At: $created_at" "Expires_At: $expires_at"
         else
-            ___x_cmd_ui_tf false "Couldn't find any data by $*"
+            ___x_cmd_ui_tf false "Couldn't find any data by $* :" >&2
             ___x_cmd_gh____handle_resp
             return 1
         fi
@@ -84,18 +137,19 @@ ___x_cmd_gh_action_artifact_rm(){
     param:dsl       <<A
 options:
     #1          "artifact id"                                                           <>:Number
-    --repo      "Provide owner name and repo name.(default:the current user repo)"      <>:RepoName
+    --repo|-r   "<ownerPath>/<RepoPath> (default ownerPath: current user)"              <>:RepoName
     --yes|-y    "Ignore remove prompt interception"
 A
     param:run
     ___x_cmd_gh_param_init_owner_repo
     [ "$yes" = "true" ] || ___x_cmd_ui_yesno "Are you sure ${owner_repo} to remove artifact: $(___x_cmd_ui bold red "${1##*/}") ?" || return 1
-    ___x_cmd_gh_curl delete  "/repos/${owner_repo}/actions/artifacts/${1##*/}" | (
-            x jo env . gh_resp_err=.message
+    ___x_cmd_gh_curl del  "/repos/${owner_repo}/actions/artifacts/${1##*/}" | (
+            [ -z "$___X_CMD_GH_IN_TEST_ENV" ] || { command cat; return; }
+            x jo env . gh_resp_msg=.message gh_resp_err=.errors
             if ___x_cmd_gh_http_error; then
-                ___x_cmd_ui_tf true  "Remove ${owner_repo} ${1##*/} artifact successfully"
+                ___x_cmd_ui_tf true  "Remove ${owner_repo} ${1##*/} artifact successfully:"
             else
-                ___x_cmd_ui_tf false "Remove ${owner_repo} ${1##*/} artifact failure"
+                ___x_cmd_ui_tf false "Remove ${owner_repo} ${1##*/} artifact failure:" >&2
                 ___x_cmd_gh____handle_resp
                 return 1
             fi
@@ -110,9 +164,9 @@ ___x_cmd_gh_action_artifact_download(){
     param:scope ___x_cmd_github
     param:dsl <<A
 options:
-    #1                      "artifact id"                                                           <>:Number
-    --repo                  "Provide owner name and repo name.(default:the current user repo)"      <>:RepoName
-    --output|-o             "Download to specified output folder"                                   <>=""
+    #1            "artifact id"                                                  <>:Number
+    --repo|-r     "<ownerPath>/<RepoPath> (default ownerPath: current user)"     <>:RepoName
+    --output|-o   "Download to specified output folder"                          <>=""
 A
     param:run
     ___x_cmd_gh_param_init_owner_repo
@@ -123,12 +177,12 @@ A
     local gh_output="${gh_output_dir}/${1##*/}.zip"
     x mkdirp "$gh_output_dir"
 
-    if ! ___x_cmd_gh_curl download "/repos/${owner_repo}/actions/artifacts/${1##*/}/ZIP" "${gh_output}"; then
-        [ "$(___x_cmd_gh_resp_code)" != 404 ] || gh:warn "Possible the artifact has been expired. please the $1 from \`x action artifact ls\`"
+    if ! ___x_cmd_gh_curl download "/repos/${owner_repo}/actions/artifacts/${1##*/}/zip" "${gh_output}"; then
+        [ "$(___x_cmd_gh_resp_code)" != 404 ] || gh:warn "Possible the artifact has been expired. please check the artifact $1 by \`x action artifact ls\`"
         x rmrf "$gh_output"
         return 1
     else
-        ___x_cmd_ui_tf true  "Download ${owner_repo} ${1##*/} artifact successfully" "Path: $gh_output"
+        ___x_cmd_ui_tf true  "Download ${owner_repo} ${1##*/} artifact successfully:" "Path: $gh_output"
     fi
 }
 # EndSection
diff --git a/mod/gh/lib/action/workflow b/mod/gh/lib/action/workflow
--- a/mod/gh/lib/action/workflow
+++ b/mod/gh/lib/action/workflow
@@ -3,6 +3,7 @@
 
 ___x_cmd_gh_action_workflow() {
     param:subcmd  ___x_cmd_gh_action_workflow          \
+        "app"                    "Interactive UI show repo by owner"                     \
         "ls|l"                   "lists the workflow in a repository."                    \
         "view|v"                 "View the summary of a workflow"                         \
         "dispatch|run"           "Run a workflow by creating a workflow_dispatch event"   \
@@ -13,6 +14,7 @@ ___x_cmd_gh_action_workflow() {
     ___x_cmd_gh_action_workflow _param_help_doc
     return 1
 }
+___x_cmd_gh_action_wf(){ param:void; ___x_cmd_gh_action_workflow "$@"; }
 
 # Section: List
 # shellcheck disable=SC2154
@@ -21,7 +23,7 @@ ___x_cmd_gh_action_workflow_ls() {
     param:scope ___x_cmd_github
     param:dsl <<A
 options:
-    --repo      "Provide owner name and repo name.(default:the current user repo)"      <>:RepoName
+    --repo|-r   "<ownerPath>/<RepoPath> (default ownerPath: current user)"              <>:RepoName
 
     --per_page  "Results per page (max 100)"                                            <>:Per_page="30"
     --page      "Page number of the results to fetch."                                  <>:Numbers="1"
@@ -35,8 +37,49 @@ A
         eval "$___workflow_ls_tmp"
     else
         ___X_CMD_UI_STATIC=1 ___ui_table_json Workflow_ID=.id name=.name path=.path state=.state -- \
-            "$___workflow_ls_tmp | x jo q0 .workflows | ___x_cmd_resp___handle_table_pipe_data"
+            "$___workflow_ls_tmp | x jo q0 .workflows"
     fi
+}
+# EndSection
+
+# Section: App
+___x_cmd_gh_action_workflow_app() {
+    param:scope ___x_cmd_github
+    param:dsl <<A
+options:
+    --repo|-r      "Provide owner name and repo name.(default:the current user repo)"   <>:RepoName
+
+    --per_page  "Results per page (max 100)"                                            <>:Per_page="30"
+    --page      "Page number of the results to fetch."                                  <>:Numbers="1"
+A
+    param:run
+    ___x_cmd_gh_param_init_owner_repo
+    local ___workflow_ls_tmp="___x_cmd_gh_curl get /repos/${owner_repo}/actions/workflows per_page page"
+
+    local ___gh_error_msg="get workflow list fail"
+    local ___X_CMD_TUI_TABLE_FINAL_COMMAND
+    local ___X_CMD_TUI_TABLE_CUR_LINE
+    local ___X_CMD_TUI_TABLE_CUR_ITEM
+    local ___X_CMD_GH_TUI_TABLE_REQUSET_DATA='___x_cmd_gh_curl get /repos/${owner_repo}/actions/workflows per_page page'
+    local ___X_CMD_GH_TUI_ACTION_WORKFLOW_REQUSET_DATA='___x_cmd_gh_action_workflow_view --repo $owner_repo '
+    ___x_cmd_gh_tui_app "action.workflow.app.awk"
+
+    ___x_cmd_gh_action_workflow_app_status_handler
+}
+    ___x_cmd_gh_action_workflow_app_status_handler(){
+
+    local workflow_id
+    workflow_id="${___X_CMD_TUI_TABLE_CUR_LINE##*Id: }"
+    workflow_id=${workflow_id%%
+Name:*}
+
+    case "$___X_CMD_TUI_TABLE_FINAL_COMMAND" in
+            "ENTER")        printf "%s\n" "$___X_CMD_TUI_TABLE_FINAL_COMMAND"  ;;
+            "i")            ___x_cmd_gh_action_workflow_dispatch      --repo "${repo}"          "$workflow_id"             ;;
+            "d")            ___x_cmd_gh_action_workflow_disable       --repo "${repo}"          "$workflow_id"             ;;
+            "e")            ___x_cmd_gh_action_workflow_enable        --repo "${repo}"          "$workflow_id"             ;;
+            *)              return
+    esac
 }
 # EndSection
 
@@ -50,7 +93,7 @@ type:
     run_status = Success Failure
 options:
     #1                 "The ID of the workflow"                                             <>:Number
-    --repo              "Provide repo name.(default:the current user repo)"                 <>:RepoName
+    --repo|-r          "<ownerPath>/<RepoPath> (default ownerPath: current user)"           <>:RepoName
 
     --branch            "Returns workflow runs associated with a branch."                   <>=""
     --actor             "returns someone workflow runs."                                    <>:Username=""
@@ -74,7 +117,7 @@ A
         eval "$___workflow_view_tmp"
     else
         ___X_CMD_UI_STATIC=1 ___ui_table_json Runs_ID=.id commit=.head_commit.message name=.name conclusion=.conclusion branch=.head_branch -- \
-            "$___workflow_view_tmp | x jo q0 .workflow_runs | ___x_cmd_resp___handle_table_pipe_data"
+            "$___workflow_view_tmp | x jo q0 .workflow_runs"
     fi
 }
 
@@ -86,18 +129,19 @@ ___x_cmd_gh_action_workflow_disable() {
     param:scope ___x_cmd_github
     param:dsl <<A
 options:
-    --repo          "Provide owner name and repo name.(default:the current user repo)"  <>:RepoName
+    --repo|-r       "<ownerPath>/<RepoPath> (default ownerPath: current user)"          <>:RepoName
     #1              "The ID of the workflow"                                            <>:Number
 A
     param:run
 
     ___x_cmd_gh_param_init_owner_repo
     ___x_cmd_gh_curl put  "/repos/${owner_repo}/actions/workflows/${1##*/}/disable" | (
-            x jo env . gh_resp_err=.message
+            [ -z "$___X_CMD_GH_IN_TEST_ENV" ] || { command cat; return; }
+            x jo env . gh_resp_msg=.message gh_resp_err=.errors
             if ___x_cmd_gh_http_error; then
-                ___x_cmd_ui_tf  true "Disabled ${1##*/} successfully"
+                ___x_cmd_ui_tf  true "Disabled ${1##*/} successfully:"
             else
-                ___x_cmd_ui_tf  false "Disabled ${1##*/} failure"
+                ___x_cmd_ui_tf  false "Disabled ${1##*/} failure:" >&2
                 ___x_cmd_gh____handle_resp
                 return 1
             fi
@@ -111,18 +155,19 @@ ___x_cmd_gh_action_workflow_enable() {
     param:scope ___x_cmd_github
     param:dsl <<A
 options:
-    --repo          "Provide owner name and repo name.(default:the current user repo)"  <>:RepoName
-    #1              "The ID of the workflow"                                            <>:Number
+    --repo|-r   "<ownerPath>/<RepoPath> (default ownerPath: current user)"      <>:RepoName
+    #1          "The ID of the workflow"                                        <>:Number
 A
     param:run
     ___x_cmd_gh_param_init_owner_repo
 
     ___x_cmd_gh_curl put  "/repos/${owner_repo}/actions/workflows/${1##*/}/enable" | (
-            x jo env . gh_resp_err=.message
+            [ -z "$___X_CMD_GH_IN_TEST_ENV" ] || { command cat; return; }
+            x jo env . gh_resp_msg=.message gh_resp_err=.errors
             if ___x_cmd_gh_http_error; then
-                ___x_cmd_ui_tf  true "Enable ${1##*/} successfully"
+                ___x_cmd_ui_tf  true "Enable ${1##*/} successfully:"
             else
-                ___x_cmd_ui_tf false "Enable ${1##*/} failure"
+                ___x_cmd_ui_tf false "Enable ${1##*/} failure:" >&2
                 ___x_cmd_gh____handle_resp
                 return 1
             fi
@@ -137,23 +182,24 @@ ___x_cmd_gh_action_workflow_dispatch() {
     param:scope ___x_cmd_github
     param:dsl <<A
 options:
-    --repo          "Provide owner name and repo name.(default:the current user repo)"                  <>:RepoName
-    --ref           "The git reference for the workflow."                                               <>="main"
-    --inputs        "Input keys and values configured in the workflow file.(json)(stdin -)"             <>=""
-    #1              "The ID of the workflow"                                                            <>:Number
+    --repo|-r       "<ownerPath>/<RepoPath> (default ownerPath: current user)"                <>:RepoName
+    --ref           "The git reference for the workflow."                                     <>="main"
+    --inputs        "Input keys and values configured in the workflow file.(json)(stdin -)"   <>=""
+    #1              "The ID of the workflow"                                                  <>:Number
 A
     param:run
     ___x_cmd_gh_param_init_owner_repo
-    local gen_gh_json
+    local gen_gh_json=""
     [ "$inputs" != '-' ] || inputs="$(command cat)"
     gen_gh_json="$(param:option2json -repo)"
     gh:debug "$gen_gh_json"
     ___x_cmd_gh_curl post "/repos/${owner_repo}/actions/workflows/${1##*/}/dispatches" gen_gh_json | (
-            x jo env . gh_resp_err=.message
+            [ -z "$___X_CMD_GH_IN_TEST_ENV" ] || { command cat; return; }
+            x jo env . gh_resp_msg=.message gh_resp_err=.errors
             if ___x_cmd_gh_http_error; then
-                ___x_cmd_ui_tf  true "Created workflow_dispatch event for ${1##*/} at $ref"
+                ___x_cmd_ui_tf  true "Created workflow_dispatch event for ${1##*/} at ${ref}:"
             else
-                ___x_cmd_ui_tf false "Created workflow_dispatch event failure"
+                ___x_cmd_ui_tf false "Created workflow_dispatch event failure:" >&2
                 ___x_cmd_gh____handle_resp
                 return 1
             fi
diff --git a/mod/gh/lib/awk/app/table b/mod/gh/lib/awk/app/table
--- a/mod/gh/lib/awk/app/table
+++ b/mod/gh/lib/awk/app/table
@@ -1,14 +1,15 @@
 # shellcheck shell=sh
 ___x_cmd_gh_tui_app_processer(){
     case "$1" in
-        data:request:*)     ___x_cmd_gh_tui_app_datarequest "${1#*data:request:}" ;;
         data:total_count)   printf "data:total_count:%s\n" "$(___x_cmd_gh_resp_header "total_count")" ;;
+        data:request:workflow_view:*)  ___x_cmd_gh_action_workflow_app_datarequest "${1#*data:request:workflow_view:}";;
+        data:request:*)     ___x_cmd_gh_tui_app_datarequest "${1#*data:request:}"  ;;
     esac
 }
 
 ___x_cmd_gh_tui_app_datarequest(){
     local signal; local page; local start; local content
-    signal="${1#*data:request:}"
+    signal="$1"
     page=$(( (signal-1)/per_page  + 1 ))
     start=$(( (page-1)*per_page  + 1 ))
 
@@ -20,6 +21,16 @@ ___x_cmd_gh_tui_app_datarequest(){
     printf "data:start:%s\n%s\n" "$start" "$content"
 }
 
+___x_cmd_gh_action_workflow_app_datarequest(){
+    local content
+    content="$( eval "$___X_CMD_GH_TUI_ACTION_WORKFLOW_REQUSET_DATA" "$1")" || {
+        [ -n "$___gh_error_msg" ] || ___gh_error_msg="Failed to get data"
+        printf "errexit:%s\n" "$___gh_error_msg"
+        return 1
+    }
+    printf "data:Runs_ID:%s\n%s\n" "$1" "$content"
+}
+
 ___x_cmd_gh_get_multi___get_data(){
     ___x_cmd_gh_curl get "$@" page per_page
 }
@@ -28,19 +39,20 @@ ___x_cmd_gh_tui_app(){
     ___x_cmd_tui_app_processer(){ ___x_cmd_gh_tui_app_processer "$@"; }
     local filename=${1:?Provide a file name}
     x tui app \
-        -f "$___X_CMD_ROOT_MOD/awk/lib/j/json.awk"                       \
-        -f "$___X_CMD_ROOT_MOD/awk/lib/j/jiter.awk"                      \
-        -f "$___X_CMD_ROOT_MOD/awk/lib/j/jqparse.awk"                    \
-        -f "$___X_CMD_ROOT_MOD/awk/lib/j/jop.awk"                        \
-        -f "$___X_CMD_ROOT_MOD/advise/lib/awk/util.awk"                  \
-        -f "$___X_CMD_ROOT_MOD/advise/lib/awk/advise.obj.awk"            \
-        -f "$___X_CMD_ROOT_MOD/advise/lib/awk/advise.complete.awk"       \
-        -f "$___X_CMD_ROOT_MOD/advise/lib/awk/advise.parse_argument.awk" \
+        -f "$___X_CMD_ROOT_MOD/awk/lib/j/json.awk"  \
+        -f "$___X_CMD_ROOT_MOD/awk/lib/j/jiter.awk" \
+        -f "$___X_CMD_ROOT_MOD/awk/lib/j/jop.awk"   \
+        -f "$___X_CMD_ROOT_MOD/awk/lib/j/jcp.awk"   \
+        -f "$___X_CMD_ROOT_MOD/advise/lib/awk/advise.obj.awk"                   \
+        -f "$___X_CMD_ROOT_MOD/advise/lib/awk/advise.share.awk"                 \
+        -f "$___X_CMD_ROOT_MOD/advise/lib/awk/advise/advise.util.awk"           \
+        -f "$___X_CMD_ROOT_MOD/advise/lib/awk/advise/advise.complete.awk"       \
+        -f "$___X_CMD_ROOT_MOD/advise/lib/awk/advise/advise.parse_argument.awk" \
         -f "$___X_CMD_ROOT_MOD/tui/lib/comp/lineedit.awk"                \
         -f "$___X_CMD_ROOT_MOD/tui/lib/comp/textbox.awk"                 \
         -f "$___X_CMD_ROOT_MOD/tui/lib/comp/statusline.awk"              \
         -f "$___X_CMD_ROOT_MOD/tui/lib/comp/table.awk"                   \
-        -f "$___X_CMD_ROOT_MOD/gh/lib/awk/app/share.awk"               \
+        -f "$___X_CMD_ROOT_MOD/tui/lib/eg.comp/table.comp.awk"           \
         -f "$___X_CMD_ROOT_MOD/gh/lib/awk/app/$filename"
     unset -f ___x_cmd_tui_app_processer
 }
diff --git a/mod/gh/lib/org/apply b/mod/gh/lib/org/apply
--- a/mod/gh/lib/org/apply
+++ b/mod/gh/lib/org/apply
@@ -7,11 +7,12 @@ ___x_cmd_gh_org_apply(){
     param:void
     if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then { ___x_cmd_gh_org_apply__help; return 0; }
     fi
-    ___x_cmd_gh_current_owner 1>/dev/null || return 1
+    ___x_cmd_gh_config_get owner 1>/dev/null || return 1
 
-    local filepath="${1:?Provide filepath}"; shift
+    [ -n "$1" ] || M='accepts 1 arg(apply file path), received empty' arg:ret:64
+    local filepath="$1"; shift
 
-    local code; if code="$(
+    local code=""; if code="$(
         {
             case "$filepath" in
                 -)              cat | x y2j ;;
@@ -40,7 +41,7 @@ ___x_cmd_gh_org_apply(){
                 -f "$___X_CMD_ROOT_MOD/gh/lib/org/apply.awk"
         }
     )"; then
-        gh:debug "apply code: $code"
+        gh:debug "apply code - $code"
         [ -n "$code" ] || {
             printf "%s\n" ""; gh:info "Org apply no changes required"
             return 0
@@ -52,7 +53,7 @@ ___x_cmd_gh_org_apply(){
         echo "$code"
     else
         code=$?
-        gh:error "Exit=$code. Fail to apply: $filepath" >/dev/stderr
+        gh:error "Exit=$code. Fail to apply - $filepath"
     fi
 }
 
diff --git a/mod/gh/lib/repo/apply/index b/mod/gh/lib/repo/apply/index
--- a/mod/gh/lib/repo/apply/index
+++ b/mod/gh/lib/repo/apply/index
@@ -1,15 +1,16 @@
 # shellcheck shell=sh disable=SC3043,2002,SC2154
 
-# x gt repo apply a.yml lijunhao=edwinjhlee zhengyuhang=mnnna
-# x gt repo apply .x-cmd/gitee-repo.yml  lijunhao=edwinjhlee
+# x gh repo apply a.yml lijunhao=edwinjhlee zhengyuhang=mnnna
+# x gh repo apply .x-cmd/gitee-repo.yml  lijunhao=edwinjhlee
 
 ___x_cmd_gh_repo_apply(){
     param:void
     if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then { _____x_cmd_gh_help repo apply; return 0; }
     fi
-    ___x_cmd_gh_current_owner 1>/dev/null || return 1
+    ___x_cmd_gh_config_get owner 1>/dev/null || return 1
 
-    local filepath="${1:?Provide filepath}"; shift
+    [ -n "$1" ] || M='accepts 1 arg(apply file path), received empty' arg:ret:64
+    local filepath="$1"; shift
     local _errexit="${___X_CMD_UNSEENCHAR_001}${___X_CMD_UNSEENCHAR_002}${___X_CMD_UNSEENCHAR_003}"
 
     local code; if code="$(
@@ -38,7 +39,7 @@ ___x_cmd_gh_repo_apply(){
                 -f "$___X_CMD_ROOT_MOD/gh/lib/repo/apply/apply.awk"
         }
     )"; then
-        gh:debug "apply code: $code"
+        gh:debug "apply code - $code"
         [ -n "$code" ] || {
             printf "%s\n" ""; gh:info "Repo apply no changes required"
             return 0
@@ -50,7 +51,7 @@ ___x_cmd_gh_repo_apply(){
         # echo "$code"
     else
         code=$?
-        gh:error "Exit=$code. Fail to apply: $filepath" >/dev/stderr
+        gh:error "Exit=$code. Fail to apply $filepath" >/dev/stderr
     fi
 }
 
@@ -65,6 +66,7 @@ ___x_cmd_gh_repo_apply___parse_data(){
                         -f "$___X_CMD_ROOT_MOD/awk/lib/default.awk" \
                         -f "$___X_CMD_ROOT_MOD/awk/lib/re.awk"  \
                         -f "$___X_CMD_ROOT_MOD/awk/lib/fs.awk" \
+                        -f "$___X_CMD_ROOT_MOD/awk/lib/arr.awk" \
                         -f "$___X_CMD_ROOT_MOD/awk/lib/log.awk" \
                         -f "$___X_CMD_ROOT_MOD/awk/lib/j/json.awk"  \
                         -f "$___X_CMD_ROOT_MOD/awk/lib/j/jiter.awk" \
diff --git a/mod/gh/lib/repo/release/index b/mod/gh/lib/repo/release/index
--- a/mod/gh/lib/repo/release/index
+++ b/mod/gh/lib/repo/release/index
@@ -3,34 +3,19 @@
 
 ___x_cmd_gh_repo_release(){
     param:subcmd ___x_cmd_gh_repo_release           \
-        "ls|l"              "list repo release"                 \
+        "ls|l"              "List repo release"                 \
         "info|i"            "Show detailed information of repo" \
-        latest              "get latest release"                \
-        "create|c"          "create repo release"               \
-        "edit|ed"           "update release information"        \
-        rm                  "Remove repo release"
+        latest              "Get latest release"                \
+        "create|c"          "Create repo release"               \
+        "edit|ed"           "Update release information"        \
+        rm                  "Remove repo release"               \
+        "attachment|asset"  "release attachment management"
     param:subcmd:try
     param:run
-        # attachment  "Attachment management"         \
-
 
     ___x_cmd_gh_repo_release _param_help_doc
     return 1
 }
-
-# Assume pr and owner_repo are environments
-___x_cmd_gh_repo_release_init_owner_repo_and_release_main(){
-    local release_id="${release##*/}"
-    owner_repo="${release%"$release_id"}"
-    ___x_cmd_gt_param_normalize_repo "$owner_repo"
-    release="$release_id"
-}
-
-alias ___x_cmd_gh_repo_release_init_owner_repo_and_release="
-    [ -n $release ]     || local release
-    [ -n $owner_repo ]  || local owner_repo
-    ___x_cmd_gh_repo_release_init_owner_repo_and_release_main || return
-"
 
 # Section: List
 # https://docs.github.com/en/rest/releases/releases#list-releases
@@ -40,7 +25,7 @@ ___x_cmd_gh_repo_release_ls() {
 type:
     direction = asc  desc
 options:
-    --repo          "Provide owner name and repo name.(default:the current user repo)"  <>:RepoName
+    --repo|-r       "<ownerPath>/<RepoPath> (default ownerPath: current user)"          <>:RepoName
     --direction     "direction(asc,desc)"                                               <>:direction="asc"
 
     --per_page      "Results per page"                                                  <>="30"
@@ -51,7 +36,7 @@ options:
 
     ___x_cmd_gh_param_init_owner_repo
 
-    ___X_CMD_UI_STATIC=1 ___gh_ui_mutual '___ui_table_json Id=.id Name=.name TagName=.tag_name Branch=.target_commitish Prerelease=.prerelease Url=.html_url -- $@' \
+    ___X_CMD_UI_STATIC=1 ___gh_ui_mutual '___ui_table_json Release_Id=.id Name=.name TagName=.tag_name Branch=.target_commitish Prerelease=.prerelease -- $@' \
         ___x_cmd_gh_curl get "/repos/${owner_repo}/releases" page per_page direction
 }
 # EndSection
@@ -62,14 +47,13 @@ ___x_cmd_gh_repo_release_info() {
     param:scope     ___x_cmd_github
     param:dsl    '
 options:
-    --repo    "Provide owner name and repo name.(default:the current user repo)"    <>:RepoName
-    #1        "Release ID"                                                          <>:number
-    --json|-j "output json"
+    #1              "Release ID"                                                        <>:number
+    --repo|-r       "<ownerPath>/<RepoPath> (default ownerPath: current user)"          <>:RepoName
+    --json|-j       "output json"
 '
     param:run
     ___x_cmd_gh_param_init_owner_repo
-    ___x_cmd_gh_repo_release_init_owner_repo_and_release
-    ___x_cmd_gh_curl get "/repos/${owner_repo}/releases/${1}" | _____x_cmd_gh_release_ui_utils Info
+    ___x_cmd_gh_curl get "/repos/${owner_repo}/releases/${1##*/}" | ___x_cmd_gh_release____ui_handler Info
 }
 # EndSection
 
@@ -79,13 +63,13 @@ ___x_cmd_gh_repo_release_latest() {
     param:scope     ___x_cmd_github
     param:dsl    '
 options:
-    --repo      "Provide owner name and repo name.(default:the current user repo)"  <>:RepoName
+    --repo|-r   "<ownerPath>/<RepoPath> (default ownerPath: current user)"  <>:RepoName
     --json|-j   "output json data"
 '
     param:run
 
     ___x_cmd_gh_param_init_owner_repo
-    ___x_cmd_gh_curl get "/repos/${owner_repo}/releases/latest" | _____x_cmd_gh_release_ui_utils Latest
+    ___x_cmd_gh_curl get "/repos/${owner_repo}/releases/latest" | ___x_cmd_gh_release____ui_handler Latest
 }
 # EndSection
 
@@ -97,7 +81,7 @@ ___x_cmd_gh_repo_release_create() {
     param:dsl    '
 options:
     --tag               "Please provide tag name"                                           <>
-    --repo              "Provide owner name and repo name.(default:the current user repo)"  <>:RepoName
+    --repo|-r           "<ownerPath>/<RepoPath> (default ownerPath: current user)"          <>:RepoName
     --name              "Release name"                                                      <>=""
     --body              "Release Description"                                               <>=""
     --target_commitish  "Default is main"                                                   <>:name="main"
@@ -109,10 +93,10 @@ options:
     param:run
     ___x_cmd_gh_param_init_owner_repo
 
-    local gen_gh_json
+    local gen_gh_json=""
     gen_gh_json="$(param:option2json -tag tag_name=tag)"
     gh:debug "$gen_gh_json"
-    ___x_cmd_gh_curl post "/repos/${owner_repo}/releases" "gen_gh_json" | _____x_cmd_gh_release_ui_utils Creating
+    ___x_cmd_gh_curl post "/repos/${owner_repo}/releases" "gen_gh_json" | ___x_cmd_gh_release____ui_handler Creating
 }
 # EndSection
 
@@ -123,7 +107,7 @@ ___x_cmd_gh_repo_release_edit() {
     param:dsl    '
 options:
     #1                      "Release ID"                                                            <>:number
-    --repo                  "Provide owner name and repo name.(default:the current user repo)"      <>:RepoName
+    --repo|-r               "<ownerPath>/<RepoPath> (default ownerPath: current user)"              <>:RepoName
     --tag_name              "The name of the tag."                                                  <>=""
     --target_commitish      "Is release version"                                                    <>=""
     --name                  "The name of the release."                                              <>=""
@@ -135,12 +119,11 @@ options:
 '
     param:run
     ___x_cmd_gh_param_init_owner_repo
-    ___x_cmd_gh_repo_release_init_owner_repo_and_release
-    local gen_gh_json
+    local gen_gh_json=""
     gen_gh_json="$(param:option2json -repo)"
     gh:debug "$gen_gh_json"
 
-    ___x_cmd_gh_curl patch "/repos/${owner_repo}/releases/${1}" "gen_gh_json" | _____x_cmd_gh_release_ui_utils Edit
+    ___x_cmd_gh_curl patch "/repos/${owner_repo}/releases/${1##*/}" "gen_gh_json" | ___x_cmd_gh_release____ui_handler Edit
 }
 # EndSection
 
@@ -152,87 +135,29 @@ ___x_cmd_gh_repo_release_rm() {
     param:dsl    '
 options:
     #1           "Release ID"                                                            <>:number
-    --repo       "Provide owner name and repo name.(default:the current user repo)"      <>:RepoName
+    --repo|-r    "<ownerPath>/<RepoPath> (default ownerPath: current user)"              <>:RepoName
     --yes|-y    "Ignore remove prompt interception"
 '
     param:run
-
     ___x_cmd_gh_param_init_owner_repo
 
-    [ "$yes" = "true" ] || ___x_cmd_ui_yesno "Are you sure you want to delete version  $(___x_cmd_ui bold red "$1") in the $owner_repo ?" || return
-    ___x_cmd_gh_curl delete "/repos/${owner_repo}/releases/$1"| (
-        x jo env . gh_resp_err=.message
-        if ___x_cmd_gh_http_error; then
-            ___x_cmd_ui_tf  true "successfully remove repo release"
-        else
-            ___x_cmd_ui_tf false "delete repo release failure: $1."
-            ___x_cmd_gh____handle_resp
-            return 1
-        fi
-    )
+    [ "$yes" = "true" ] || ___x_cmd_ui_yesno "Are you sure you want to delete release $(___x_cmd_ui bold red "$1") on $owner_repo repo ?" || return
+    ___x_cmd_gh_curl del "/repos/${owner_repo}/releases/${1##*/}" | (
+            [ -z "$___X_CMD_GH_IN_TEST_ENV" ] || { command cat; return; }
+            x jo env . gh_resp_msg=.message gh_resp_err=.errors
+            if ___x_cmd_gh_http_error; then
+                ___x_cmd_ui_tf  true "Remove ${owner_repo} ${1##*/} release successfully:"
+            else
+                ___x_cmd_ui_tf false "Remove ${owner_repo} ${1##*/} release failure:" >&2
+                ___x_cmd_gh____handle_resp
+                return 1
+            fi
+        )
 }
 # EndSection
 
-# TODO:
-# Section: Attachment
-
-___x_cmd_gh_repo_release_attachment(){
-    param:subcmd ___x_cmd_gh_repo_release_attachment    \
-        "create|c"          "upload attachment"                 \
-        rm                  "delete attachment"                 \
-        "ls|l"              "list release's attachment"
-    param:subcmd:try
-    param:run
-
-
-    ___x_cmd_gh_repo_release_attachment _param_help_doc
-    return 1
-}
-
-___x_cmd_gh_repo_release_attachment_ls() {
-
-
-    param:scope     ___x_cmd_github
-    param:dsl    '
-options:
-    #1        "Release ID"                <>:number
-'
-    param:run
-    local release="${1:?release id must be specified}"
-    ___x_cmd_gh_repo_release_init_owner_repo_and_release
-}
-
-# Provide multiple files
-___x_cmd_gh_repo_release_attachment_create() {
-
-    param:scope     ___x_cmd_github
-    param:dsl    '
-options:
-    #1        "Release ID"                <>:number
-'
-    param:run
-    local release="${1:?release id must be specified}"
-    ___x_cmd_gh_repo_release_init_owner_repo_and_release
-}
-
-# Delete the file in attachment list
-___x_cmd_gh_repo_release_attachment_rm() {
-
-
-    param:scope     ___x_cmd_github
-    param:dsl    '
-options:
-    #1        "Release ID"                <>:number
-'
-    param:run
-    local release="${1:?release id must be specified}"
-    ___x_cmd_gh_repo_release_init_owner_repo_and_release
-}
-
-# EndSection
-
-# Section: release utils
-_____x_cmd_gh_release_ui_utils(){
+# Section: release UI
+___x_cmd_gh_release____ui_handler(){
     if [ -n "$ENFORCE_JSON" ] || [ -n "$json" ]; then
         cat
         ___x_cmd_gh_http_error
@@ -241,23 +166,24 @@ _____x_cmd_gh_release_ui_utils(){
     (
         case "$1" in
             Creating|Edit)
-                _msg="$1 repo release success."
-                _error_msg="$1 repo release Fail."
+                _inf_msg="$1 repo release successfully"
+                _err_msg="$1 repo release failure"
                 ;;
             Latest)
-                _msg="Successfully obtained the latest release information of the repo."
-                _error_msg="Failed to get the latest release information of repo."
+                _inf_msg="Successfully obtained the latest release information of the repo"
+                _err_msg="Failed to get the latest release information of repo"
                 ;;
             Info)
-                _msg="Successfully get repo release info."
-                _error_msg="Get repo release info failure."
+                _inf_msg="Get repo release info successfully"
+                _err_msg="Get repo release info failure"
                 ;;
         esac
-        x jo env . id=.id name=.name tag_name=.tag_name branch=.target_commitish html_url=.html_url author=.author.login gh_resp_err=.message
+        x jo env . id=.id name=.name tag_name=.tag_name branch=.target_commitish html_url=.html_url author=.author.login \
+            gh_resp_msg=.message gh_resp_err=.errors
         if [ -n "$id" ]; then
-            ___x_cmd_ui_tf true "$_msg" "Id: $id" ${name+"Name: $name"} ${tag_name+"TagName: $tag_name"}  ${branch+"TargetCommitish: $branch"} ${author+"Author: $author"} ${html_url+"Url: $html_url"}
+            ___x_cmd_ui_tf  true "${_inf_msg}:" "Release_Id: $id" ${name:+"Name: $name"} ${tag_name+"TagName: $tag_name"}  ${branch:+"TargetCommitish: $branch"} ${author:+"Author: $author"} ${html_url:+"Url: $html_url"}
         else
-            ___x_cmd_ui_tf false "$_error_msg"
+            ___x_cmd_ui_tf false "${_err_msg}:" >&2
             ___x_cmd_gh____handle_resp
             return 1
         fi
@@ -271,14 +197,27 @@ ___x_cmd_gh_repo_get_release_by_tag() {
     param:dsl    '
 options:
     #1              "tag name"                                                          <>
-    --repo          "Provide owner name and repo name.(default:the current user repo)"  <>:RepoName
+    --repo|-r       "<ownerPath>/<RepoPath> (default ownerPath: current user)"          <>:RepoName
 
     --json|-j       "output json data"
 '
     param:run
     ___x_cmd_gh_param_init_owner_repo
 
-    ___x_cmd_gh_curl get "/repos/${owner_repo}/releases/tags/${1}"
+    ___x_cmd_gh_curl get "/repos/${owner_repo}/releases/tags/${1##*/}"
 }
 # EndSection
 
+# Assume pr and owner_repo are environments
+# ___x_cmd_gh_repo_release_init_owner_repo_and_release_main(){
+#     local release_id="${release##*/}"
+#     owner_repo="${release%"$release_id"}"
+#     ___x_cmd_gh_param_normalize_repo "$owner_repo"
+#     release="$release_id"
+# }
+
+# alias ___x_cmd_gh_repo_release_init_owner_repo_and_release="
+#     [ -n $release ]     || local release
+#     [ -n $owner_repo ]  || local owner_repo
+#     ___x_cmd_gh_repo_release_init_owner_repo_and_release_main || return
+# "
diff --git a/mod/gh/lib/utils b/mod/gh/lib/utils
--- a/mod/gh/lib/utils
+++ b/mod/gh/lib/utils
@@ -2,8 +2,6 @@
 # shellcheck disable=SC2039,3043
 # shellcheck disable=SC2046
 
-# x curl -L -D  /Users/qbb/.x-cmd.root/tmp/h/qbbdeMBP/r/DEFAULT/gh/.____x_cmd_gh_curl_header   -X GET -H  "Accept:application/vnd.github.v3+json"  -H  "Authorization:token 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"   "https://api.github.com/repos/x-cmd/theme/actions/runs/3787465408/logs"
-
 # Section: Help
 _____x_cmd_gh_help__token_setting(){
     printf "\n%s %s \n%s\n" \
@@ -30,51 +28,62 @@ ___x_cmd_gh_resp_code(){
 
 ___x_cmd_gh_curl(){
     local op="$1"
-    local _curl_url="\"https://api.github.com$2\""
-    local _accept="\"Accept:application/vnd.github.v3+json\""
-    local _authorization
-    _authorization="\"Authorization:token $(___x_cmd_gh_token)\""
-    local gh_header="$___X_CMD_GH_TMP/.____x_cmd_gh_curl_header"
+    local _api_url="$2"
     shift 2
-    local req
+    local ___X_CMD_API_GH_HEADER="-s -H \"Accept:application/vnd.github.v3+json\" -D \"$___X_CMD_GH_TMP/.____x_cmd_gh_curl_header\""
+
+    local _curl_host_tmp=""
+    local ___X_CMD_API_GH_TOKEN=""
+    ___x_cmd_gh_config___var  ___X_CMD_API_GH_TOKEN=token _curl_host_tmp=host 2>/dev/null
+    local ___X_CMD_API_GH_HOST="${___X_CMD_API_GH_HOST:-"$_curl_host_tmp"}"
+
+    local ___X_CMD_GH_SHOW_HTTP_CODE=1
     case "$op" in
-        get)
-            gh:debug  "x curl -D  $gh_header   -X GET -s -H  $_accept  -H  $_authorization  $(eval "printf '%s ' $(x curl gencode -G $([ $# -eq 0 ] || printf "%s== " "$@"))")  $_curl_url"
-            if [ -z "$NO_CACHE" ]; then
-                x ccmd 10s --            eval x curl -D "$gh_header"  -X GET -s -H "$_accept" -H "$_authorization" $(eval "printf '%s ' $(x curl gencode $(___x_cmd_gh_curl___use_query_data "$@"))") "$_curl_url"
-                ___x_cmd_gh_http_error   eval x curl -D "$gh_header"  -X GET -s -H "$_accept" -H "$_authorization" $(eval "printf '%s ' $(x curl gencode $(___x_cmd_gh_curl___use_query_data "$@"))") "$_curl_url"
+         get)
+            if [ -n "$NO_CACHE" ]; then
+                ___x_cmd_api_gh get "$_api_url" $(eval "printf '%s ' $(x curl gencode $(___x_cmd_gh_curl___use_query_data "$@"))")
             else
-                eval x curl -D "$gh_header"  -X GET -s -H "$_accept" -H "$_authorization" $(eval "printf '%s ' $(x curl gencode $(___x_cmd_gh_curl___use_query_data "$@"))") "$_curl_url"
+                x ccmd 10s --        eval "___X_CMD_API_GH_HOST=$___X_CMD_API_GH_HOST ___X_CMD_API_GH_TOKEN=$___X_CMD_API_GH_TOKEN ___x_cmd_api_gh get $_api_url $(eval "printf '%s ' $(x curl gencode $(___x_cmd_gh_curl___use_query_data "$@"))")"
             fi
-            return
+            ___x_cmd_gh_http_error   eval "___X_CMD_API_GH_HOST=$___X_CMD_API_GH_HOST ___X_CMD_API_GH_TOKEN=$___X_CMD_API_GH_TOKEN ___x_cmd_api_gh get $_api_url $(eval "printf '%s ' $(x curl gencode $(___x_cmd_gh_curl___use_query_data "$@"))")"
+            ;;
+        post|put|patch|del)
+            ___x_cmd_api_gh "$op" "$_api_url" "$(x curl gencode "$@")"
+            ___x_cmd_gh_http_error
             ;;
         download)
             local __out="${1?:"Please provide output dir"}"
             x mkdirp "${__out%/*}"
-            gh:debug "x curl -L -D  $gh_header   -X GET -H  $_accept  -H  $_authorization    -o  $__out   $_curl_url"
-            eval      x curl -L -D "$gh_header"  -X GET -H "$_accept" -H "$_authorization"   -o "$__out" "$_curl_url"
+            ___X_CMD_API_GH_HEADER="--progress-bar -H \"Accept:application/vnd.github.v3+json\" -D \"$___X_CMD_GH_TMP/.____x_cmd_gh_curl_header\""
+            ___x_cmd_api_gh "${___X_CMD_GH_DOWNLOAD_REQ_METHOD:-"get"}" "$_api_url" -o "\"$__out\""
             if ! ___x_cmd_gh_http_error; then
-                local gh_resp_err
-                gh_resp_err="$(command cat "$__out" 2>/dev/null | x jo .message)"
-                ___x_cmd_ui_tf false "Download Failure"
-                ___x_cmd_gh____handle_resp
-                return 1
+                (
+                    command cat "$__out" 2>/dev/null | x jo env . gh_resp_msg=.message gh_resp_err=.errors
+                    ___x_cmd_ui_tf false "Download Failure" >&2
+                    ___x_cmd_gh____handle_resp
+                    return 1
+                )
             fi
-            return
             ;;
-        post)           req="POST"      ;;
-        put)            req="PUT"       ;;
-        patch)          req="PATCH"     ;;
-        delete)         req="DELETE"    ;;
+        upload)
+            local __file_type="\"Content-Type: ${file_type:-"octet-stream"}\""
+            ___X_CMD_API_GH_HEADER="--progress-bar -H \"Accept:application/vnd.github.v3+json\" -D \"$___X_CMD_GH_TMP/.____x_cmd_gh_curl_header\" -H ${__file_type}"
+            local __file_path="${1?:"Please provide upload filepath"}"; shift;
+            [ -f "$__file_path" ] || {
+                gh:error "Upload Failure: Not found target file. Please check file exist: $__file_path"
+                return 1
+            }
+            gh:info "Uploading file..."
+            ___x_cmd_api_gh "${___X_CMD_GH_UPLOAD_REQ_METHOD:-"post"}" "$_api_url" -T "\"$__file_path\""
+            ___x_cmd_gh_http_error
+            ;;
     esac
-    gh:debug "x curl -D  $gh_header  -X  $req   -s -H  $_accept  -H $_authorization    $(x curl gencode "$@")   $_curl_url"
-    eval      x curl -D "$gh_header" -X "$req"  -s -H "$_accept" -H "$_authorization" "$(x curl gencode "$@")" "$_curl_url"
 }
 
 # shellcheck disable=SC2154
 ___x_cmd_gh_curl___use_query_data(){
     [ $# -gt 0 ] || return
-    local name
+    local name=""
     printf "%s " "-G"
     for name in "$@";
     do
@@ -85,44 +94,35 @@ ___x_cmd_gh_curl___use_query_data(){
 }
 
 ___x_cmd_gh_http_error(){
-    local http_resp_code
+    local http_resp_code=""
     http_resp_code=$(___x_cmd_gh_resp_code)
     if [ -n "$http_resp_code" ] && [ "$http_resp_code" -ge 200 ] && [ "$http_resp_code" -le 303 ]; then
         return 0
     else
         [ $# -eq 0 ] || {
-            gh:debug "---! Cache Clear !---"
+            gh:debug "Cache Clear"
             x ccmd invalidate "$@" 1>/dev/null 2>&1
         }
-        gh:error "HTTP Code is $http_resp_code"
+        [ -z "$___X_CMD_GH_SHOW_HTTP_CODE" ] || {
+            gh:error "HTTP Code is $http_resp_code"
+            if command -v unset 1>/dev/null; then
+                unset ___X_CMD_GH_SHOW_HTTP_CODE
+            fi
+        }
         return 1
     fi
 }
 
+___x_cmd_gh____printf_error(){
+    if ! ___x_cmd_is_interative_tty || [ ! -t 2 ] || [ -n "$NO_COLOR" ]; then
+        printf "  - ErrorMsg: %s\n" "$1" >&2
+    else
+        printf "  \033[31m-\033[0m \033[1mErrorMsg: \033[31m%s\033[0m\n" "$1" >&2
+    fi
+}
 ___x_cmd_gh____handle_resp(){
-    if  [ -n "$gh_resp_body" ]; then
-        printf "%s\n" "$gh_resp_body" | x jo
-    elif [ -n "$gh_resp_err" ]; then
-        printf "  \033[31m-\033[0m \033[1mErrorMsg: \033[31m%s\033[0m\n" "$gh_resp_err"
-    fi
-}
-
-___x_cmd_resp___handle_table_pipe_data(){
-    if ___x_cmd_gh_http_error;then
-        printf "%s" "$(cat)"
-    fi
-    return
-}
-
-___x_cmd_gh____handle_no_content(){
-    x jo env . gh_resp=. gh_resp_err=.message
-
-    [ -z "$gh_resp" ] || {
-        gh:debug "gh_resp_body: $gh_resp"
-        ___x_cmd_gh____handle_resp
-        return 1
-    }
-    ___x_cmd_gh_http_error
+    [ -z "$gh_resp_msg" ] || ___x_cmd_gh____printf_error "$gh_resp_msg"
+    [ -z "$gh_resp_err" ] || ___x_cmd_gh____printf_error "$gh_resp_err"
 }
 # EndSection
 
@@ -138,7 +138,7 @@ ___gh_ui_mutual() {
     fi
     local ___gh_exit_code="$?"
     [ "$___gh_exit_code" -eq 0 ] || {
-        ___x_cmd_ui_tf false "${___gh_error_msg:-"Couldn't find any data"}" ;
+        ___x_cmd_ui_tf false "${___gh_error_msg:-"Couldn't find any data"}:" >&2
         return "$___gh_exit_code"
     }
 }
@@ -161,7 +161,7 @@ ___x_cmd_gh_get_multi() {
 ___x_cmd_gh_get_multi___ui_table(){
     ___x_cmd_gh_curl get "$@" page per_page
     printf "\n"
-    local next_url
+    local next_url=""
     _____x_cmd_gh_next_url
     [ -n "$next_url" ] || return
 
@@ -173,12 +173,12 @@ ___x_cmd_gh_get_multi___ui_table(){
 }
 
 ___x_cmd_gh_get_multi___json_prt(){
-    local tmp
+    local tmp=""
     tmp=$(mktemp)
     ___x_cmd_gh_curl get "$@" page per_page > "$tmp"
     printf "\n" >> "$tmp"
 
-    local next_url
+    local next_url=""
     _____x_cmd_gh_next_url
     if [ -z "$next_url" ]; then
         cat "$tmp"
@@ -228,34 +228,41 @@ ___x_cmd_gh_param_normalize_repo() {
     [ -z "$op" ] && op="$1"
     case "$op" in
     */*)
-        owner_repo="$(printf "%s" "$op")"
+        owner_repo="$op"
         ;;
     "")
-        owner_repo="$(_____x_cmd_git_repo)"
+        if [ -n "$___X_CMD_GH_CURRENT_repo" ]; then
+            if [ "${___X_CMD_GH_CURRENT_repo##*/}" != "${___X_CMD_GH_CURRENT_repo}" ];then
+                owner_repo="$___X_CMD_GH_CURRENT_repo"
+            elif [ -n "$___X_CMD_GH_CURRENT_owner" ]; then
+                owner_repo="${___X_CMD_GH_CURRENT_owner}/${___X_CMD_GH_CURRENT_repo}"
+            else
+                if ! owner_repo="$(___x_cmd_gh_config_get owner)/${___X_CMD_GH_CURRENT_repo}"; then
+                    gh:error "No owner provided. Default owner not set."
+                    gh:warn -h "$(x str ml wrap "$(_____x_cmd_gh_help__token_setting)" '    ')" -m "Can retry setup token to update owner.${___X_CMD_UNSEENCHAR_NEWLINE}Or check your current token setting."
+                    return 1
+                fi
+            fi
+        else
+            owner_repo="$(_____x_cmd_git_repo)"
+        fi
         ;;
     *)
-        ___x_cmd_gh_current_owner 1>/dev/null 2>&1
-        if [ -z "$___X_CMD_GITHUB_DEFAULT_OWNER" ]; then
-            gh:error "No owner provided. Default owner not set."
-            gh:warn "Check your current token setting.$(_____x_cmd_gh_help__token_setting)"
-            return 1
+        if [ -z "$___X_CMD_GH_CURRENT_owner" ]; then
+            local ___X_CMD_GH_CURRENT_owner
+            if ! ___X_CMD_GH_CURRENT_owner="$(___x_cmd_gh_config_get owner)"; then
+                gh:error "No owner provided. Default owner not set."
+                gh:warn -h "$(x str ml wrap "$(_____x_cmd_gh_help__token_setting)" '    ')" -m "Can retry setup token to update owner.${___X_CMD_UNSEENCHAR_NEWLINE}Or check your current token setting."
+                return 1
+            fi
         fi
-        owner_repo="$(printf "%s" "$___X_CMD_GITHUB_DEFAULT_OWNER/$op")"
+        owner_repo="${___X_CMD_GH_CURRENT_owner}/${op}"
         ;;
     esac
 }
 
 ___x_cmd_gh_default() {
     param_default "$@" 2>/dev/null || return 1
-}
-
-_____x_cmd_git_repo() {
-    local repo
-    repo="$(git config --get remote.origin.url 2>/dev/null)"
-    repo="${repo##*".com:"}"
-    repo="${repo##*".com/"}"
-    repo="${repo%.*}"
-    printf "%s" "$repo"
 }
 
 _____x_cmd_git_branch() {
diff --git a/mod/gl/lib/project/apply/index b/mod/gl/lib/project/apply/index
--- a/mod/gl/lib/project/apply/index
+++ b/mod/gl/lib/project/apply/index
@@ -20,10 +20,10 @@ ___x_cmd_gl_project_apply(){
             esac' |
              {
                 x jo env . content=. owner_project=.project  apply_member=.member
-                [ -n "$owner_project" ] || { gl_log error "Not found apply configure project main key" >/dev/stderr; return 1; }
+                [ -n "$owner_project" ] || { gl:error "Not found apply configure project main key" >/dev/stderr; return 1; }
                 ___x_cmd_gl_project_apply__replace "$@"
                 printf "%s\n" "$content"
-                gl_log info "Getting project info ..."
+                gl:info "Getting project info ..."
                 ___x_cmd_gl_project_apply__member_info
                 ___x_cmd_gl_project_apply__project_info
             }
@@ -39,19 +39,19 @@ ___x_cmd_gl_project_apply(){
                 -f "$___X_CMD_ROOT_MOD/gl/lib/project/apply/apply.awk"
         }
     )"; then
-        # gl_log debug "apply code: $code"
+        # gl:debug "apply code: $code"
         # [ -n "$code" ] || {
-        #     printf "%s\n" ""; gl_log info "Repo apply no changes required"
+        #     printf "%s\n" ""; gl:info "Repo apply no changes required"
         #     return 0
         # }
-        # gl_log info "Handling project by info ..."
+        # gl:info "Handling project by info ..."
         # if [ -n "$___X_CMD_GH_DRY_RUN" ]; then      printf "%s\n" "$code";
         # else                                        eval "$code";
         # fi
         echo "$code"
     else
         code=$?
-        gl_log error "Exit=$code. Fail to apply: $filepath" >/dev/stderr
+        gl:error "Exit=$code. Fail to apply: $filepath" >/dev/stderr
     fi
 }
 
diff --git a/mod/gl/lib/utils b/mod/gl/lib/utils
--- a/mod/gl/lib/utils
+++ b/mod/gl/lib/utils
@@ -2,56 +2,107 @@
 # shellcheck disable=SC2039,3043
 # shellcheck disable=SC2046
 
+# Section: Help
+_____x_cmd_gl_help__token_setting(){
+    printf "\n%s %s \n%s\n" \
+        "$(___x_cmd_ui yellow 'Run command to add|repleace token:')" \
+        "$(___x_cmd_ui bold cyan "\`x gl token <token>\`")"   \
+        "$(___x_cmd_ui 'https://gitlab.com/-/profile/personal_access_tokens')"
+}
+
+_____x_cmd_gl_help(){
+    command -v ___x_cmd_advise_gen_help >/dev/null || xrc:mod advise/lib/gen_help
+    ___x_cmd_advise_gen_help "$___X_CMD_ROOT_MOD/gl/res/advise.jso" "$@"
+}
+
+# EndSection
+
 # Section: HTTP header & body & request
 ___x_cmd_gl_resp_header(){
    cat "$___X_CMD_GL_TMP/.____x_cmd_gl_curl_header"
 }
 
-# TODO:HTTP CODE
-______x_cmd_gl_resp_header_code(){
+___x_cmd_gl_resp_code(){
     ___x_cmd_gl_resp_header  | awk '$1 ~/HTTP\/2$/ {print ($2+0);exit(0)}'
 }
 
 ___x_cmd_gl_curl(){
     local op="$1"
-    local url="\"https://gitlab.com/api/v4$2\""
+    local _curl_url="\"${___X_CMD_GL_DOMAIN:-"https://gitlab.com"}/api/v4${2}\""
+    local _content_type="\"Content-Type: application/json\""
+    local _authorization
+    _authorization="\"PRIVATE-TOKEN: $(___x_cmd_gl_token)\""
     local gl_header="$___X_CMD_GL_TMP/.____x_cmd_gl_curl_header"
-    local Type="\"Content-Type: application/json\""
-    local Authorization
-    Authorization="\"PRIVATE-TOKEN: $(___x_cmd_gl_token)\""
+    local ___X_CMD_GL_SHOW_HTTP_CODE=1
     shift 2
     local req
     case "$op" in
         get)
-            gl_log debug           "eval x curl -D  $gl_header   -X GET -s -H  $Type  -H  $Authorization  $(eval "printf '%s ' $(x curl gencode -G $([ $# -eq 0 ] || printf "%s== " "$@"))")  $url"
-            x ccmd 3m --            eval x curl -D "$gl_header"  -X GET -s -H "$Type" -H "$Authorization" $(eval "printf '%s ' $(x curl gencode -G $([ $# -eq 0 ] || printf "%s== " "$@"))") "$url"
-            ___x_cmd_gl_http_error  eval x curl -D "$gl_header"  -X GET -s -H "$Type" -H "$Authorization" $(eval "printf '%s ' $(x curl gencode -G $([ $# -eq 0 ] || printf "%s== " "$@"))") "$url"
+            gl:debug   "x curl -D  $gl_header   -X GET -s -H  $_content_type  -H  $_authorization  $(eval "printf '%s ' $(x curl gencode $(___x_cmd_gl_curl___use_query_data "$@"))")  $_curl_url"
+            if [ -n "$NO_CACHE" ]; then
+                eval    x curl -D "$gl_header"  -X GET -s -H "$_content_type" -H "$_authorization" $(eval "printf '%s ' $(x curl gencode $(___x_cmd_gl_curl___use_query_data "$@"))") "$_curl_url"
+            else
+                x ccmd 10s --      eval x curl -D "$gl_header"  -X GET -s -H "$_content_type" -H "$_authorization" $(eval "printf '%s ' $(x curl gencode $(___x_cmd_gl_curl___use_query_data "$@"))") "$_curl_url"
+            fi
+            ___x_cmd_gl_http_error eval x curl -D "$gl_header"  -X GET -s -H "$_content_type" -H "$_authorization" $(eval "printf '%s ' $(x curl gencode $(___x_cmd_gl_curl___use_query_data "$@"))") "$_curl_url"
             return
             ;;
-        post)
-            req="POST";;
-        put)
-            req="PUT";;
-        patch)
-            req="PATCH";;
-        delete)
-            req="DELETE";;
+        upload)
+            local __file_path="${1?:"Please provide upload filepath"}"; shift;
+            [ -f "$__file_path" ] || {
+                gl:error "Upload Failure: Not found target file. Please check file exist: $__file_path"
+                return 1
+            }
+            gl:debug "x curl -L -D  $gl_header   -X  ${___X_CMD_GL_UPLOAD_REQ_METHOD:-"POST"}  -H  $_authorization  --form  file=@${__file_path}    $(x curl gencode "$@")   $_curl_url"
+            eval      x curl -L -D "$gl_header"  -X "${___X_CMD_GL_UPLOAD_REQ_METHOD:-"POST"}" -H "$_authorization" --form  file=@"${__file_path}" "$(x curl gencode "$@")" "$_curl_url"
+            ___x_cmd_gl_http_error; return
+        ;;
+        post)           req="POST"      ;;
+        put)            req="PUT"       ;;
+        patch)          req="PATCH"     ;;
+        delete)         req="DELETE"    ;;
     esac
-    gl_log debug "eval x curl -D $gl_header -X $req    -s -H $Type -H $Authorization $(x curl gencode "$@") $url"
-
-    eval x curl -D "$gl_header" -X "$req"    -s -H "$Type" -H "$Authorization" "$(x curl gencode "$@")" "$url"
+    gl:debug "x curl -D  $gl_header  -X  $req  -s -H  $_content_type  -H  $_authorization   $(x curl gencode "$@")   $_curl_url"
+    eval      x curl -D "$gl_header" -X "$req" -s -H "$_content_type" -H "$_authorization" "$(x curl gencode "$@")" "$_curl_url"
+    ___x_cmd_gl_http_error
 }
 
 ___x_cmd_gl_http_error(){
     local http_resp_code
-    http_resp_code=$(______x_cmd_gl_resp_header_code)
+    http_resp_code=$(___x_cmd_gl_resp_code)
     if [ -n "$http_resp_code" ] && [ "$http_resp_code" -ge 200 ] && [ "$http_resp_code" -le 303 ]; then
         return 0
     else
-        [ $# -eq 0 ] || x ccmd invalidate "$@" >/dev/null
-        gl_log error "HTTP Code Is $http_resp_code"
+        [ $# -eq 0 ] || {
+            gl:debug "---! Cache Clear !---"
+            x ccmd invalidate "$@" 1>/dev/null 2>&1
+        }
+        [ -z "$___X_CMD_GL_SHOW_HTTP_CODE" ] || {
+            gl:error "HTTP Code is $http_resp_code"
+            if command -v unset 1>/dev/null; then
+                unset ___X_CMD_GL_SHOW_HTTP_CODE
+            fi
+        }
         return 1
     fi
+}
+
+# shellcheck disable=SC2154
+___x_cmd_gl_curl___use_query_data(){
+    [ $# -gt 0 ] || return
+    local name
+    printf "%s " "-G"
+    for name in "$@";
+    do
+        if [ "$name" = "p" ];then  [ -z "$p" ] || printf "%s " "path==$p";
+        else                                      printf "%s " "$name==" ;
+        fi
+    done
+}
+
+___x_cmd_gl____handle_resp(){
+    [ -z "$gl_resp_body" ] || printf "%s" "$gl_resp_body"
+    [ -z "$gl_resp_err" ]  || printf "  \033[31m-\033[0m \033[1mErrorMsg: \033[31m%s\033[0m\n" "$gl_resp_err" >&2
 }
 # EndSection
 
@@ -131,10 +182,11 @@ _____x_cmd_gl_next_url(){
 
 # Section: Parameter Utilities
 alias ___x_cmd_gl_param_init_owner_project='
-    local owner_project
+    local owner_project=""
     ___x_cmd_gl_param_normalize_repo  || return
 '
 
+# shellcheck disable=SC2154,SC2034
 ___x_cmd_gl_param_normalize_repo(){
     local op="$project"
 
@@ -151,7 +203,9 @@ ___x_cmd_gl_param_normalize_repo(){
         [ -z "$owner_project" ] || return
         ___x_cmd_gl_current_owner 1>/dev/null
         if [ -z "$___X_CMD_GL_DEFAULT_OWNER" ]; then
-            printf "No owner provided. Default owner not set.\n" >&2
+            gl:error "No owner provided. Default owner not set."
+            gl:warn "Check your current token setting.$(_____x_cmd_gl_help__token_setting)"
+            return 1
         fi
         owner_project="$(printf "%s" "$___X_CMD_GL_DEFAULT_OWNER/$op")"
         ;;
diff --git a/mod/gt/lib/org/apply b/mod/gt/lib/org/apply
--- a/mod/gt/lib/org/apply
+++ b/mod/gt/lib/org/apply
@@ -7,9 +7,10 @@ ___x_cmd_gt_org_apply(){
     param:void
     if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then _____x_cmd_gt_help org apply; return 0;
     fi
-    ___x_cmd_gt_current_owner 1>/dev/null || return 1
+    ___x_cmd_gt_config_get owner 1>/dev/null || return 1
 
-    local filepath="${1:?Provide filepath}"; shift
+    [ -n "$1" ] || M='accepts 1 arg(apply file path), received empty' arg:ret:64
+    local filepath="$1"; shift
 
     local code; if code="$(
         {
@@ -35,7 +36,7 @@ ___x_cmd_gt_org_apply(){
                 -f "$___X_CMD_ROOT_MOD/gt/lib/org/apply.awk"
         }
     )"; then
-        gt:debug "apply code: $code"
+        gt:debug "apply code $code"
         [ -n "$code" ] || {
             printf "%s\n" ""; gt:info "Org apply no changes required"
             return 0
@@ -47,7 +48,7 @@ ___x_cmd_gt_org_apply(){
         # echo "$code"
     else
         code=$?
-        gt:error "Exit=$code. Fail to apply: $filepath" >/dev/stderr
+        gt:error "Exit=$code. Fail to apply $filepath" >/dev/stderr
     fi
 }
 
diff --git a/mod/gt/lib/repo/apply b/mod/gt/lib/repo/apply
--- a/mod/gt/lib/repo/apply
+++ b/mod/gt/lib/repo/apply
@@ -7,9 +7,10 @@ ___x_cmd_gt_repo_apply(){
     param:void
     if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then _____x_cmd_gt_help repo apply; return 0;
     fi
-    ___x_cmd_gt_current_owner 1>/dev/null || return 1
+    ___x_cmd_gt_config_get owner 1>/dev/null || return 1
 
-    local filepath="${1:?Provide filepath}"; shift
+    [ -n "$1" ] || M='accepts 1 arg(apply file path), received empty' arg:ret:64
+    local filepath="$1"; shift
     local _errexit="${___X_CMD_UNSEENCHAR_001}${___X_CMD_UNSEENCHAR_002}${___X_CMD_UNSEENCHAR_003}"
 
     local code; if code="$(
@@ -41,7 +42,7 @@ ___x_cmd_gt_repo_apply(){
                 -f "$___X_CMD_ROOT_MOD/gt/lib/repo/apply.awk"
         }
     )"; then
-        gt:debug "apply code: $code"
+        gt:debug "apply code $code"
         [ -n "$code" ] || {
             printf "%s\n" ""; gt:info "Repo apply no changes required"
             return 0
@@ -53,7 +54,7 @@ ___x_cmd_gt_repo_apply(){
         # echo "$code"
     else
         code=$?
-        gt:error "Exit=$code. Fail to apply: $filepath" >/dev/stderr
+        gt:error "Exit=$code. Fail to apply $filepath" >/dev/stderr
     fi
 }
 
@@ -69,6 +70,7 @@ ___x_cmd_gt_repo_apply___parse_data(){
                         -f "$___X_CMD_ROOT_MOD/awk/lib/default.awk" \
                         -f "$___X_CMD_ROOT_MOD/awk/lib/re.awk"  \
                         -f "$___X_CMD_ROOT_MOD/awk/lib/fs.awk" \
+                        -f "$___X_CMD_ROOT_MOD/awk/lib/arr.awk" \
                         -f "$___X_CMD_ROOT_MOD/awk/lib/log.awk" \
                         -f "$___X_CMD_ROOT_MOD/awk/lib/j/json.awk"  \
                         -f "$___X_CMD_ROOT_MOD/awk/lib/j/jiter.awk" \
diff --git a/mod/gt/lib/token b/mod/gt/lib/token
--- a/mod/gt/lib/token
+++ b/mod/gt/lib/token
@@ -1,41 +1,50 @@
 # shellcheck shell=sh
-# shellcheck disable=SC2039,3043
+# shellcheck disable=SC2039,SC3043,SC2154
 
-# Synchronized token in the x-bash user profile.
-
-# shellcheck disable=SC2120
 ___x_cmd_gt_token(){
-    param:void
-    if [ "$1" = "--help" ] || [ "$1" = "-h" ]; then _____x_cmd_gt_help token; return 0
-    fi
+    param:scope     ___x_cmd_gt
+    param:dsl       '
+options:
+    #1          "access token. empty output current token"     <>=""
+    --host      "config request host"                          <>="https://gitee.com/api/v5"
+    --profile   "config profile name. empty use default"       <>=""
+    --config    "config file path. empty use default"          <>=""
+    '
+    param:run
+    [ -z "$profile" ] || local ___X_CMD_GT_CURRENT_profile="$profile"
+    [ -z "$config"  ] || local ___X_CMD_GT_CURRENT_config="$config"
 
-    local O="${O:-___x_cmd_gt_GITEE_DEFAULT}"
-    if [ $# -eq 0 ]; then
-        ___x_cmd_gt_config_get "oauth_token"  || {
+    if [ -z "$1" ]; then
+        ___x_cmd_gt_config_get token 2>/dev/null || {
             gt:error "Can't find any token"
-            gt:warn "Please check your token.$(_____x_cmd_gt_help__token_setting)"
+            gt:warn -m "Please check your token.$(_____x_cmd_gt_help__token_setting)"
             return 1
         }
         return 0
     else
         [ $# -lt 2 ] || gt:warn "Multiple tokens cannot be set at the same time, Set only the first token"
-        local tmp_token
-        tmp_token="$(___x_cmd_gt_config_get "oauth_token")"
+        local tmp_token=
+        local tmp_host=
+        ___x_cmd_gt_config___var    tmp_token=token tmp_host=host 2>/dev/null
 
-        if [ "$1" = "$tmp_token" ];then
+        if [ "$1" = "$tmp_token" ]; then
             gt:info "Consistent with the original token"
-            return 0
+            ! ___x_cmd_gt_config_get owner 1>/dev/null 2>&1 || [ "$host" != "$tmp_host" ] || return 0
         fi
 
-        ___x_cmd_gt_config_set "oauth_token" "$1" 1>/dev/null
-        ___X_CMD_GITEE_DEFAULT_OWNER=
-        if ! NO_CACHE=1 ___x_cmd_gt_current_owner 1>/dev/null 2>&1; then
-            [ -z "$tmp_token" ] || ___x_cmd_gt_config_set "oauth_token" "$tmp_token" 1>/dev/null
-            gt:error "set default token $1 fail, Please check if it is a valid token.$(_____x_cmd_gt_help__token_setting)"
+        ___x_cmd_gt_config_set "$1" "" "$host"
+        local ___X_CMD_GT_CURRENT_owner=
+        x jo env . ___X_CMD_GT_CURRENT_owner=.login <<A
+            $(___x_cmd_gt_curl get "/user")
+A
+        if [ -z "$___X_CMD_GT_CURRENT_owner" ]; then
+            # reback
+            [ -z "$tmp_token" ] || ___x_cmd_gt_config_set "$tmp_token" "" "$tmp_host" 2>/dev/null
+            gt:error "Fail to update current owner with this token"
             return 1
         fi
-        ___x_cmd_gt_config_set "user" "$___X_CMD_GITEE_DEFAULT_OWNER" 1>/dev/null
-        ___x_cmd_ui_tf true "set default token successfully, The default user is $___X_CMD_GITEE_DEFAULT_OWNER"
+        ___x_cmd_gt_config_set "" "$___X_CMD_GT_CURRENT_owner" "$host"
+        ___x_cmd_ui_tf true "Setup token successfully, The owner is $___X_CMD_GT_CURRENT_owner:"
         return 0
     fi
 }
diff --git a/mod/gt/lib/utils b/mod/gt/lib/utils
--- a/mod/gt/lib/utils
+++ b/mod/gt/lib/utils
@@ -6,7 +6,7 @@ _____x_cmd_gt_help__token_setting(){
     printf "\n%s %s \n%s\n" \
         "$(___x_cmd_ui yellow 'Run command to add|repleace token:')" \
         "$(___x_cmd_ui bold cyan "\`x gt token <token>\`")"   \
-        "$(___x_cmd_ui 'https://gitee.com/profile/personal_access_tokens')"
+        "$(___x_cmd_ui 'https://gitee.com/profile/personal_access_tokens')" >&2
 }
 
 _____x_cmd_gt_help(){
@@ -42,37 +42,39 @@ ___x_cmd_gt_resp_code(){
         }'
 }
 
-# NOTE: To gitee v8 api. the url prefix not save status
 # shellcheck disable=SC2046
 ___x_cmd_gt_curl(){
     local op="$1"
-    local _curl_url="\"$2\""
-    local _content_type='"Content-Type:application/json;charset=UTF-8"'
-    local _authorization
-    _authorization="\"Authorization:token $(___x_cmd_gt_token)\""
-    local gt_header="$___X_CMD_GT_TMP/.____x_cmd_gt_curl_header"
+    local _api_url="$2"
     shift 2
-    ___x_cmd_gt_curl___record_log "$@"
+    local ___X_CMD_API_GT_HEADER="-s -H \"Content-Type:application/json;charset=UTF-8\" -D \"$___X_CMD_GT_TMP/.____x_cmd_gt_curl_header\""
+
+    local _curl_host_tmp=""
+    local ___X_CMD_API_GT_TOKEN=""
+    ___x_cmd_gt_config___var  ___X_CMD_API_GT_TOKEN=token _curl_host_tmp=host 2>/dev/null
+    local ___X_CMD_API_GT_HOST="${___X_CMD_API_GT_HOST:-"$_curl_host_tmp"}"
+
+    local ___X_CMD_GT_SHOW_HTTP_CODE=1
     case "$op" in
         get)
-            if [ -z "$NO_CACHE" ]; then
-                x ccmd 10s --           eval x curl -D "$gt_header" -X GET -s -H "$_content_type" -H "$_authorization" $(eval "printf '%s ' $(x curl gencode $(___x_cmd_gt_curl___use_query_data "$@"))") "$_curl_url"
-                ___x_cmd_gt_curl_error  eval x curl -D "$gt_header" -X GET -s -H "$_content_type" -H "$_authorization" $(eval "printf '%s ' $(x curl gencode $(___x_cmd_gt_curl___use_query_data "$@"))") "$_curl_url"
+            if [ -n "$NO_CACHE" ]; then
+                ___x_cmd_api_gt get "$_api_url" $(eval "printf '%s ' $(x curl gencode $(___x_cmd_gt_curl___use_query_data "$@"))")
             else
-                eval x curl -D "$gt_header" -X GET -s -H "$_content_type" -H "$_authorization" $(eval "printf '%s ' $(x curl gencode $(___x_cmd_gt_curl___use_query_data "$@"))") "$_curl_url"
+                x ccmd 10s --        eval "___X_CMD_API_GT_HOST=$___X_CMD_API_GT_HOST ___X_CMD_API_GT_TOKEN=$___X_CMD_API_GT_TOKEN ___x_cmd_api_gt get $_api_url $(eval "printf '%s ' $(x curl gencode $(___x_cmd_gt_curl___use_query_data "$@"))")"
             fi
+            ___x_cmd_gt_http_error   eval "___X_CMD_API_GT_HOST=$___X_CMD_API_GT_HOST ___X_CMD_API_GT_TOKEN=$___X_CMD_API_GT_TOKEN ___x_cmd_api_gt get $_api_url $(eval "printf '%s ' $(x curl gencode $(___x_cmd_gt_curl___use_query_data "$@"))")"
             ;;
-        post)   eval x curl -D "$gt_header" -X POST   -s -H "$_content_type" -H "$_authorization" "$(x curl gencode "$@")" "$_curl_url"    ;;
-        put)    eval x curl -D "$gt_header" -X PUT    -s -H "$_content_type" -H "$_authorization" "$(x curl gencode "$@")" "$_curl_url"    ;;
-        patch)  eval x curl -D "$gt_header" -X PATCH  -s -H "$_content_type" -H "$_authorization" "$(x curl gencode "$@")" "$_curl_url"    ;;
-        delete) eval x curl -D "$gt_header" -X DELETE -s -H "$_content_type" -H "$_authorization" "$(x curl gencode "$@")" "$_curl_url"    ;;
+        post|put|patch|del)
+            ___x_cmd_api_gt "$op" "$_api_url" "$(x curl gencode "$@")"
+            ___x_cmd_gt_http_error
+        ;;
     esac
 }
 
 # shellcheck disable=SC2154
 ___x_cmd_gt_curl___use_query_data(){
     [ $# -gt 0 ] || return
-    local name
+    local name=""
     printf "%s " "-G"
     for name in "$@";
     do
@@ -82,47 +84,36 @@ ___x_cmd_gt_curl___use_query_data(){
     done
 }
 
-# shellcheck disable=SC2046
-___x_cmd_gt_curl___record_log(){
-    [ -z "$op" ] || {
-        case "$op" in
-            get) gt:debug "x curl -D $gt_header -X GET -s -H $_content_type -H $_authorization $(eval "printf '%s ' $(x curl gencode $(___x_cmd_gt_curl___use_query_data "$@"))") $_curl_url" ;;
-            *)   gt:debug "x curl -D $gt_header -X $op"
-                 gt:debug "-s -H $_content_type -H $_authorization $(x curl gencode "$@") $_curl_url" ;;
-        esac
-    }
-}
-
-___x_cmd_gt_curl_error(){
-    local _http_resp_code
+___x_cmd_gt_http_error(){
+    local _http_resp_code=""
     _http_resp_code="$(___x_cmd_gt_resp_code)"
     if [ -n "$_http_resp_code" ] && [ "$_http_resp_code" -ge 200 ] && [ "$_http_resp_code" -le 303 ]; then
         return 0
     else
         [ $# -eq 0 ] || {
-            gt:debug "---! Cache Clear !---"
+            gt:debug "Cache Clear"
             x ccmd invalidate "$@" 1>/dev/null 2>&1
         }
-        gt:error "HTTP Code is $_http_resp_code"
+        [ -z "$___X_CMD_GT_SHOW_HTTP_CODE" ] || {
+            gt:error "HTTP Code is $_http_resp_code"
+            if command -v unset 1>/dev/null; then
+                unset ___X_CMD_GT_SHOW_HTTP_CODE
+            fi
+        }
         return 1
     fi
 }
 
-___x_cmd_gt____handle_resp(){
-    [ -z "$gt_resp_body" ] || {
-        printf "%s\n" "$gt_resp_body" | x jo
-    }
+___x_cmd_gt____printf_error(){
+    if ! ___x_cmd_is_interative_tty || [ ! -t 2 ] || [ -n "$NO_COLOR" ]; then
+        printf "  - ErrorMsg: %s\n" "$1" >&2
+    else
+        printf "  \033[31m-\033[0m \033[1mErrorMsg: \033[31m%s\033[0m\n" "$1" >&2
+    fi
 }
-
-___x_cmd_gt____handle_no_content(){
-    local gt_resp_body=""
-    x jo env . gt_resp_body=.
-
-    [ -z "$gt_resp_body" ] || {
-        gt:debug "gt_resp_body: $gt_resp_body"
-        return 1
-    }
-    ___x_cmd_gt_curl_error
+___x_cmd_gt____handle_resp(){
+    [ -z "$gt_resp_body" ] || printf "%s" "$gt_resp_body"
+    [ -z "$gt_resp_err" ]  || ___x_cmd_gt____printf_error "$gt_resp_err"
 }
 
 # EndSection
@@ -141,7 +132,7 @@ ___gt_ui_mutual(){
 
     local ___gt_exit_code="$?"
     [ "$___gt_exit_code" -eq 0 ] || {
-        ___x_cmd_ui_tf false "${___gt_error_msg:-"Couldn't find any data"}" ;
+        ___x_cmd_ui_tf false "${___gt_error_msg:-"Couldn't find any data"}:" >&2
         return "$___gt_exit_code"
     }
 }
@@ -160,13 +151,13 @@ ___x_cmd_gt_get_multi() {
     else
         ___x_cmd_gt_get_multi___ui_table "$@"
     fi
-    ___x_cmd_gt_curl_error
+    ___x_cmd_gt_http_error
 }
 
 ___x_cmd_gt_get_multi___ui_table(){
     ___x_cmd_gt_curl get "$@" page per_page
     printf "\n"
-    local next_url
+    local next_url=""
     _____x_cmd_gt_next_url
     [ -n "$next_url" ] || return
 
@@ -178,12 +169,12 @@ ___x_cmd_gt_get_multi___ui_table(){
 }
 
 ___x_cmd_gt_get_multi___json_prt(){
-    local tmp
+    local tmp=""
     tmp=$(mktemp)
     ___x_cmd_gt_curl get "$@" page per_page >> "$tmp"
     printf "\n" >> "$tmp"
 
-    local next_url
+    local next_url=""
     _____x_cmd_gt_next_url
     if [ -z "$next_url" ] && [ -n "$tmp" ];then
         cat "$tmp"
@@ -245,25 +236,37 @@ ___x_cmd_gt_param_normalize_repo(){
     [ -z "$op" ] && op="$1"
     case "$op" in
     */*)
-        owner_repo="$(printf "%s" "$op")"
+        owner_repo="$op"
         ;;
     "")
-        owner_repo="$(_____x_cmd_git_repo)"
+        if [ -n "$___X_CMD_GT_CURRENT_repo" ]; then
+            if [ "${___X_CMD_GT_CURRENT_repo##*/}" != "${___X_CMD_GT_CURRENT_repo}" ];then
+                owner_repo="$___X_CMD_GT_CURRENT_repo"
+            elif [ -n "$___X_CMD_GT_CURRENT_owner" ]; then
+                owner_repo="${___X_CMD_GT_CURRENT_owner}/${___X_CMD_GT_CURRENT_repo}"
+            else
+                if ! owner_repo="$(___x_cmd_gt_config_get owner)/${___X_CMD_GT_CURRENT_repo}"; then
+                    gt:error "No owner provided. Default owner not set."
+                    gt:warn -h "$(x str ml wrap "$(_____x_cmd_gt_help__token_setting)" '    ')" -m "Can retry setup token to update owner.${___X_CMD_UNSEENCHAR_NEWLINE}Or check your current token setting."
+                    return 1
+                fi
+            fi
+        else
+            owner_repo="$(_____x_cmd_git_repo)"
+        fi
         ;;
     *)
-        ___x_cmd_gt_current_owner 1>/dev/null
-        if [ -z "$___X_CMD_GITEE_DEFAULT_OWNER" ]; then
-            gt:error "No owner provided. Default owner not set."
-            gt:warn "Check your current token setting.$(_____x_cmd_gt_help__token_setting)"
-            return 1
+        if [ -z "$___X_CMD_GT_CURRENT_owner" ]; then
+            local ___X_CMD_GT_CURRENT_owner
+            if ! ___X_CMD_GT_CURRENT_owner="$(___x_cmd_gt_config_get owner)"; then
+                gt:error "No owner provided. Default owner not set."
+                gt:warn -h "$(x str ml wrap "$(_____x_cmd_gt_help__token_setting)" '    ')" -m "Can retry setup token to update owner.${___X_CMD_UNSEENCHAR_NEWLINE}Or check your current token setting."
+                return 1
+            fi
         fi
-        owner_repo="$(printf "%s" "$___X_CMD_GITEE_DEFAULT_OWNER/$op")"
+        owner_repo="${___X_CMD_GT_CURRENT_owner}/${op}"
         ;;
     esac
-}
-
-___x_cmd_gt_default(){
-    param_default "$@" 2>/dev/null || return 1
 }
 
 # EndSection
diff --git a/mod/job/lib/failfast/fini b/mod/job/lib/failfast/fini
--- a/mod/job/lib/failfast/fini
+++ b/mod/job/lib/failfast/fini
@@ -1,4 +1,4 @@
-
+# shellcheck shell=sh disable=SC3043
 # Section: framework init fini
 
 ___x_cmd_job_failfast_fini___interrupt(){
@@ -19,8 +19,11 @@ ___x_cmd_job_failfast_fini()(
     local IFS="
 "
 
+    local ___X_CMD_JOB_OFFER_LOG; read -r ___X_CMD_JOB_OFFER_LOG;
+    log:sub:init -i fini job "log_dir=${___X_CMD_JOB_OFFER_LOG}"
+
     local ___X_CMD_PIDOFSUBSHELL_OF_UPSTREAM;   read -r ___X_CMD_PIDOFSUBSHELL_OF_UPSTREAM
-    job:debug "UPSTREAM PID is: $___X_CMD_PIDOFSUBSHELL_OF_UPSTREAM"
+    job:debug "upstream_pid=$___X_CMD_PIDOFSUBSHELL_OF_UPSTREAM"
 
     trap '' INT  # Ignore SIGINT
 
@@ -31,6 +34,8 @@ ___x_cmd_job_failfast_fini()(
     local waiting_usr1=
 
     local idx; local pid; local code;  local srccode
+    local failed_job_idx
+
     local line; while read -r line; do
         case "$line" in
             pid:*/*)
@@ -38,7 +43,7 @@ ___x_cmd_job_failfast_fini()(
                 pid="${line##*/}"
                 x ldict put ___X_CMD_JOB_FAILFAST "$idx" "$pid"
                 if [ -n "$___X_CMD_JOB_FAILFAST_INTERRUPTED" ]; then
-                    job:warn "Job[$idx] Reject new job but process already interrupted: sending kill signal to $pid"           # TODO: change to debug
+                    job:warn "JOB[$idx] Reject new job but process already interrupted: sending kill signal to pid=$pid"           # TODO: change to debug
                     kill "$pid"  2>/dev/null
                 fi
                 ;;
@@ -46,7 +51,7 @@ ___x_cmd_job_failfast_fini()(
                 job_count="$((job_count + 1))"
                 line="${line#start:}";      idx="${line%%/*}"
                 srccode="${line#*/}"
-                job:debug "Job[$idx] Starting: $srccode"
+                job:debug "JOB[$idx] Starting cmd=$srccode"
                 ;;
 
             exit:*/*/*)
@@ -55,12 +60,12 @@ ___x_cmd_job_failfast_fini()(
                 x ldict rm ___X_CMD_JOB_FAILFAST "$idx"
 
                 if [ "$code" -eq 0 ]; then
-                    : $((job_count_succ++))
-                    job:info "Job[$idx] [${job_count_succ}:${job_count_fail}/${job_count}] Success: $srccode"
+                    job_count_succ=$((job_count_succ+1))
+                    job:info "JOB[$idx] |${job_count_succ}:${job_count_fail}/${job_count}|PASS| $srccode"
 
                     ### request-usr1
                     if [ -n "$waiting_usr1" ]; then
-                        job:debug "Sending USR1 to notify decrease count: $pid"
+                        job:debug "Sending USR1 to notify decrease count Pid[$pid]"
                         kill "$waiting_usr1" 2>/dev/null
                         waiting_usr1=
                     else
@@ -70,13 +75,15 @@ ___x_cmd_job_failfast_fini()(
                 else
                     job_count_fail=$((job_count_fail+1))
 
-                    job:error "Job[$idx] [${job_count_succ}:${job_count_fail}/${job_count}] Fail Fast: $job_count_fail [code=$code] $srccode"
+                    job:error "JOB[$idx] |${job_count_succ}:${job_count_fail}/${job_count}|FAIL| $job_count_fail with code=$code cmd=$srccode"
 
                     [ "$job_count_fail" -eq 1 ] || continue
+                    failed_job_idx=$idx
+
                     exit_code=$code
 
-                    job:debug "Fail Fast: sending errexit signal to upstream signal $___X_CMD_PIDOFSUBSHELL_OF_UPSTREAM"
-                    kill -s USR2 "$___X_CMD_PIDOFSUBSHELL_OF_UPSTREAM" 2>/dev/null
+                    job:info "JOB[$idx] FAIL, send errexit signal to UPSTREAM(${___X_CMD_PIDOFSUBSHELL_OF_UPSTREAM})"
+                    kill -s USR2 "${___X_CMD_PIDOFSUBSHELL_OF_UPSTREAM}" 2>/dev/null
 
                     ___x_cmd_job_failfast_fini___interrupt
                 fi
@@ -90,7 +97,7 @@ ___x_cmd_job_failfast_fini()(
                 # request-usr1
                 job:debug "Recv request-usr1.: $job_worker_count"
                 if [ "$job_worker_count" -gt 0 ]; then
-                    job:debug "Sending USR1 to notify decrease count: $pid"
+                    job:debug "Sending USR1 to notify decrease count pid=$pid"
                     kill "${line#*:}" 2>/dev/null
                     job_worker_count="$((job_worker_count-1))"
                     waiting_usr1=
@@ -100,16 +107,22 @@ ___x_cmd_job_failfast_fini()(
                 # request-usr1
                 ;;
             *)
-                job:warn "Not expected: $line"
+                job:warn "Unexpeted Line=$line"
                 ;;
         esac
     done
 
     case "$exit_code" in
-        0)          job:info    "Total: $job_count jobs succeed."  ;;
-        130)        job:warn    "Abort because intterrupted after jobs run: $job_count" ;;
-        *)          job:error   "Total: $job_count_fail" ;;
+        0)          job:info    "All $job_count job(s) PASS"  ;;
+        130)        job:warn    "Abort because intterrupted after ${job_count} job(s) started" ;;
+        *)          job:error   "${job_count_fail} of ${job_count} job(s) FAIL" ;;
     esac
+
+    if [ -n "$failed_job_idx" ]; then
+        job:warn "Output Log failed job ${idx} begin"
+        command cat "${___X_CMD_JOB_OFFER_LOG}/${idx}" 2>/dev/null
+        job:warn "Output Log failed job ${idx} end"
+    fi
 
     return "$exit_code"
 )
diff --git a/mod/job/lib/log b/mod/job/lib/log
--- a/mod/job/lib/log
+++ b/mod/job/lib/log
@@ -1,4 +1,4 @@
-
+# shellcheck shell=sh disable=SC3043,2317,2012
 ___x_cmd_job_log(){
     local op="$1"
     case "$op" in
@@ -7,6 +7,8 @@ ___x_cmd_job_log(){
         cat)        shift; ___x_cmd_job_log_cat "$@" ;;
         out)        shift; ___x_cmd_job_log_out "$@" ;;
         err)        shift; ___x_cmd_job_log_err "$@" ;;
+        app)        shift; ___x_cmd_job_log_app ;;
+        *)          ___x_cmd_job_log_app "$op" "$@" ;;
     esac
 }
 
@@ -53,3 +55,50 @@ ___x_cmd_job_log_save(){
 
     x cp -r "$logdir" "$fp"
 }
+
+# Section: job log app
+___x_cmd_job_log_app(){
+    local logfile;
+    local ___X_CMD_TUI_NAVI_FINAL_COMMAND
+    local ___X_CMD_TUI_CURRENT_NAVI_POSITION
+    while ___x_cmd_job_log_app_; do
+        [ "$___X_CMD_TUI_NAVI_FINAL_COMMAND" = "ENTER" ] || break
+        less -r "$logfile" 2>/dev/null || break
+    done
+}
+
+___x_cmd_job_log_app_(){
+    ___x_cmd_tui_app_processer(){ ___x_cmd_job_log_app_processer "$@"; }
+    x tui app \
+        -v JOB_LOG_FILE_BASEPATH="$___X_CMD_LOG_STORE_DEFAULT/job/DEFAULT" \
+        -v ___X_CMD_TUI_CURRENT_NAVI_POSITION="${___X_CMD_TUI_CURRENT_NAVI_POSITION}" \
+        -f "$___X_CMD_ROOT_MOD/tui/lib/comp/lineedit.awk"     \
+        -f "$___X_CMD_ROOT_MOD/tui/lib/comp/gsel.awk"         \
+        -f "$___X_CMD_ROOT_MOD/tui/lib/comp/lsel.awk"         \
+        -f "$___X_CMD_ROOT_MOD/tui/lib/comp/textbox.awk"      \
+        -f "$___X_CMD_ROOT_MOD/tui/lib/comp/statusline.awk"   \
+        -f "$___X_CMD_ROOT_MOD/tui/lib/comp/navi.awk"         \
+        -f "$___X_CMD_ROOT_MOD/awk/lib/j/json.awk"            \
+        -f "$___X_CMD_ROOT_MOD/tui/lib/eg.comp/navi.comp.awk" \
+        -f "$___X_CMD_ROOT_MOD/job/lib/app/log.awk"
+}
+
+___x_cmd_job_log_app_processer(){
+    local args; local item
+    local content
+    case "$1" in
+        data:request:*)
+            args="${1#*data:request:}"
+            item="${args##* }"
+            args="${args% *}"
+            content="$( eval "___x_cmd_job_log_ls_ $args" 2>/dev/null )" || {
+                printf "errexit:job log error exit:%s" "$args"
+                return
+            }
+            printf "data:item:%s\n" "$item"
+            printf "%s\n" "$content"
+            ;;
+    esac
+}
+
+# EndSection
diff --git a/mod/pkg/lib/mutate/download b/mod/pkg/lib/mutate/download
--- a/mod/pkg/lib/mutate/download
+++ b/mod/pkg/lib/mutate/download
@@ -23,20 +23,28 @@ ___x_cmd_pkg_download(){
     fi
 
     local url_list
-    url_list="$(___x_cmd_pkg___list "$name" "$version" "$osarch" "url.${___X_CMD_WHICHNET:-_}" )"
+    url_list="$(___x_cmd_pkg___list "$name" "$version" "$osarch" "url.${___X_CMD_WEBSRC_REGION:-internet}" )"
     if [ -z "$url_list" ]; then
-        pkg:error "Not found url."
+        pkg:error "Not found url"
         return 1
     fi
 
     local file_suffix md5 sha1 sha256 sha512
     ___x_cmd_pkg___attr "$name" "$version" "$osarch" "md5,sha1,sha256,sha512,file_suffix"
     local url
-    local ball="$___X_CMD_PKG_DOWNLOAD_PATH/$name/$version.$file_suffix"
+
+    ___x_cmd_pkg___attr "$name" "$version" "$osarch" "unpack_way"
+    if [ "$unpack_way" = "non_unpack" ]; then
+        local os="${osarch%/*}";  local arch="${osarch#*/}"
+        local ball="$___X_CMD_PKG_DOWNLOAD_PATH/$name/$name.$os.$arch"
+    else
+        local ball="$___X_CMD_PKG_DOWNLOAD_PATH/$name/$version.$file_suffix"
+    fi
+
     mkdir -p "$___X_CMD_PKG_DOWNLOAD_PATH/$name" || {
             pkg:error "Create $___X_CMD_PKG_DOWNLOAD_PATH/$name failed" ; return 1
         }
-    pkg:debug "Download $name $version url_list: $url_list ball: $ball"
+    pkg:debug "{ Download name: $name, version: $version, url_list: $url_list, ball: $ball }"
 
 
     if [ -f "$ball" ]; then
@@ -50,7 +58,7 @@ ___x_cmd_pkg_download(){
         # ___x_cmd_httpget "$url" "$ball" || {
         pkg:info "Download $name $version from $url to $ball"
         # TODO: x curl
-        if ! curl --progress-bar --location --retry-max-time 10 --retry 0 "$url" --output "$ball" 2>/dev/null; then
+        if ! curl --progress-bar --location --retry-max-time 10 --retry 0 "$url" --output "$ball" ; then
             pkg:warn "Fail to download from $url"
             x rmrf $ball
             return 1
@@ -75,7 +83,7 @@ ___x_cmd_pkg_download_file___from_static_build_and_deflate(){
     local app="${2:-${repo}}"
     local version="${3:?Provide version}"
 
-    pkg:debug "Download static-build. repo: $repo app: $app"
+    pkg:debug "{ Download static-build repo: $repo, app: $app }"
 
     local target="$___X_CMD_PKG_INSTALL_PATH/$app/$version"
     x mkdirp "$target" || return 1
@@ -89,7 +97,7 @@ ___x_cmd_pkg_download_file___from_static_build_and_deflate(){
 
     # Rely
     if [ ! -f "$target/$exe" ]; then
-        pkg:info "Downloading: $repo/$app/$version/$exe.7z to $target"
+        pkg:info "Downloading - '$repo/$app/$version/$exe.7z to $target'"
         if ! ___x_cmd_httpget_gitx static-build "${repo}" main "$app/$version/$exe.7z" "$target/$exe.7z"; then
             pkg:warn "Download failure: $repo/main $app/$version/$exe.7z. Perhaps platform unsupported."
             x rmrf "$target"
@@ -104,7 +112,6 @@ ___x_cmd_pkg_download_file___from_static_build_and_deflate(){
                 size=${size% *}
                 size=$(printf "%s" $size)   # Notice: Intentionary let it unquoted.
 
-                xrc p7zip
                 if [ "$size" -gt 20 ]; then
                     p7zd x "$exe.7z" 1>/dev/null 2>/dev/null
                 else
@@ -116,14 +123,14 @@ ___x_cmd_pkg_download_file___from_static_build_and_deflate(){
                     for i in $(seq "$size"); do
                         # suffix="$(printf "%03s" "$i")" # Not work in gnu bash
                         suffix="$(printf "%3s" "$i" | tr " " 0)"
-                        pkg:info "Downloading: $repo/$app/$version/$exe.7z.$suffix to $target"
+                        pkg:info "Downloading - '$repo/$app/$version/$exe.7z.$suffix to $target'"
                         if ! ___x_cmd_httpget_gitx static-build "${repo}" main "$app/$version/$exe.7z.$suffix" "$target/$exe.7z.$suffix"; then
                             pkg:warn "Download failure in $exe.7z.$suffix" >&2
                             return 1
                         fi
                     done
 
-                    pkg:info "Using p7zd to decompress: $target/$exe.7z.001"
+                    pkg:info "Using p7zd to decompress - '$target/$exe.7z.001'"
                     cat "$target/$exe".7z.0* > "$exe.7z"
                     p7zd x "$exe.7z" 1>/dev/null 2>/dev/null || {
                         pkg:error "p7zd unzip $exe.7z failed"
@@ -133,7 +140,7 @@ ___x_cmd_pkg_download_file___from_static_build_and_deflate(){
                 if chmod +x "$exe"; then
                     pkg:info "Finish file decompress and chmod."
                 else
-                    pkg:error "chmod: Operation not permitted "
+                    pkg:error "chmod - Operation not permitted "
                 fi
             }
         )
diff --git a/mod/tea/lib/config b/mod/tea/lib/config
--- a/mod/tea/lib/config
+++ b/mod/tea/lib/config
@@ -9,7 +9,6 @@ ___x_cmd_tea_config(){
     param:subcmd:try
     param:run
 
-    tea_log warn "Subcmd Not Found."
     ___x_cmd_tea_config _param_help_doc
     return 1
 }
@@ -17,26 +16,26 @@ ___x_cmd_tea_config(){
 # Section: config which
 ___x_cmd_tea_config_which() {
     param:void
-    printf "%s\n" "${___X_CMD_TEA_CFG}/___x_cmd_tea_TEA_DEFAULT"
+    printf "%s\n" "${___X_CMD_TEA_CFG}/___x_cmd_tea_GITEA_DEFAULT"
 }
 # EndSection
 
 # Section get and set
 # shellcheck disable=SC2154
 ___x_cmd_tea_config_get() {
-    param:scope     ___x_cmd_gitea
+    param:scope     ___x_cmd_tea
     param:dsl       '
 options:
     --host        "host name"                               <>="gitea.com"
     #1            "The name of the configuration to get"    <>:ConfigName
 '
     param:run
-    [ -e  "${___X_CMD_TEA_CFG}/___x_cmd_tea_TEA_DEFAULT" ] || return 1
-    ___x_cmd_git_config_get "${___X_CMD_TEA_CFG}/___x_cmd_tea_TEA_DEFAULT" "$host" "$1"
+    [ -e  "${___X_CMD_TEA_CFG}/___x_cmd_tea_GITEA_DEFAULT" ] || return 1
+    ___x_cmd_git_config_get "${___X_CMD_TEA_CFG}/___x_cmd_tea_GITEA_DEFAULT" "$host" "$1"
 }
 
 ___x_cmd_tea_config_set() {
-    param:scope     ___x_cmd_gitea
+    param:scope     ___x_cmd_tea
     param:dsl       '
 options:
     --host    "host name"                           <>="gitea.com"
@@ -44,9 +43,9 @@ options:
     #2        "Please provide configuration val"    <>
 '
     param:run
-    local ___teacode_path="${___X_CMD_TEA_CFG}/___x_cmd_tea_TEA_DEFAULT"
+    local ___teacode_path="${___X_CMD_TEA_CFG}/___x_cmd_tea_GITEA_DEFAULT"
     [ -e  "$___teacode_path" ] || mkdir -p "$___X_CMD_TEA_CFG"
     ___x_cmd_git_config_set "$___teacode_path" "$host" "$1" "$2" && return 0
-    tea_log error "tea config set Fail"
+    tea:error "tea config set Fail"
 }
 # EndSection
diff --git a/mod/tea/lib/current b/mod/tea/lib/current
--- a/mod/tea/lib/current
+++ b/mod/tea/lib/current
@@ -11,7 +11,6 @@ ___x_cmd_tea_current(){
     param:subcmd:try
     param:run
 
-    tea_log warn "Subcmd Not Found."
     ___x_cmd_tea_current _param_help_doc
     return 1
 }
@@ -22,7 +21,7 @@ ___x_cmd_tea_current_owner() {
 
     if [ -n "$1" ]; then
         ___X_CMD_TEA_DEFAULT_OWNER="$1"
-        if ___x_cmd_tea_config_set  "user" "$___X_CMD_TEA_DEFAULT_OWNER" 1>/dev/null 2>&1;then
+        if ___x_cmd_tea_config_set  "user" "$___X_CMD_TEA_DEFAULT_OWNER" 1>/dev/null 2>&1; then
             ___x_cmd_ui_tf true "Manually change the owner to $___X_CMD_TEA_DEFAULT_OWNER"
         fi
         return
@@ -31,7 +30,7 @@ ___x_cmd_tea_current_owner() {
         $(___x_cmd_tea_curl get "/user")
 A
         if [ -z "$___X_CMD_TEA_DEFAULT_OWNER" ];then
-            tea_log error "get current owner fail."
+            tea:error "get current owner fail."
             return 1
         fi
         ___x_cmd_tea_config_set  "user" "$___X_CMD_TEA_DEFAULT_OWNER" 1>/dev/null 2>&1
@@ -67,6 +66,8 @@ ___x_cmd_tea_current_owner_type() {
 ___x_cmd_tea_owner_type_query() {
     param:void
     local owner="${1:?Provide owner name}"
+    [ "${owner##*/}" = "${owner}" ] || { printf "%s" "repo"; return 0; }
+    local types
     for types in "org" "user"
     do
         if  ___x_cmd_tea_${types}_info "$owner" 1>/dev/null 2>&1;then
@@ -76,4 +77,3 @@ ___x_cmd_tea_owner_type_query() {
     done
     return 1
 }
-
diff --git a/mod/tea/lib/utils b/mod/tea/lib/utils
--- a/mod/tea/lib/utils
+++ b/mod/tea/lib/utils
@@ -2,80 +2,123 @@
 # shellcheck disable=SC2039,3043
 # shellcheck disable=SC2046
 
+# Section: Help
+_____x_cmd_tea_help__token_setting(){
+    printf "\n%s %s \n%s\n" \
+        "$(___x_cmd_ui yellow 'Run command to add|repleace token:')" \
+        "$(___x_cmd_ui bold cyan "\`x tea token <token>\`")"   \
+        "$(___x_cmd_ui "${___X_CMD_TEA_DOMAIN:-"https://gitea.com"}/user/settings/applications")"
+}
+
+_____x_cmd_tea_help(){
+    command -v ___x_cmd_advise_gen_help >/dev/null || xrc:mod advise/lib/gen_help
+    ___x_cmd_advise_gen_help "$___X_CMD_ROOT_MOD/tea/res/advise.jso" "$@"
+}
+# EndSection
+
 # Section: HTTP header & body & request
 ___x_cmd_tea_resp_header() {
     cat "$___X_CMD_TEA_TMP/.____x_cmd_tea_curl_header"
 }
 
-______x_cmd_tea_resp_header_code(){
+___x_cmd_tea_resp_code(){
     ___x_cmd_tea_resp_header  | awk '$1 ~/HTTP\/2$/ {print ($2+0);exit(0)}'
 }
 
 # https://gitea.com/api/v1/user
 # https://codeberg.org/api/v1/user
-# Token: https://gitea.com/user/settings/applications
 ___x_cmd_tea_curl(){
     local op="$1"
-    local url="\"${___X_CMD_TEA_REF:-"https://gitea.com"}/api/v1$2\""
-    local tea_header="$___X_CMD_ROOT_TMP/tea/.____x_cmd_tea_curl_header"
-    local Accept="\"Accept:application/json\""
-    local Content="\"Content-Type:application/json\""
-    local Authorization
-    Authorization="\"Authorization:token $(___x_cmd_tea_token)\""
+    local _curl_url="\"${___X_CMD_TEA_DOMAIN:-"https://gitea.com"}/api/v1$2\""
+    local _accept="\"Accept:application/json\""
+    local _content="\"Content-Type:application/json\""
+    local _authorization
+    _authorization="\"Authorization:token $(___x_cmd_tea_token)\""
+    local tea_header="$___X_CMD_TEA_TMP/.____x_cmd_tea_curl_header"
+    local ___X_CMD_TEA_SHOW_HTTP_CODE=1
     shift 2
     local req
     case "$op" in
         get)
-            tea_log debug           "eval x curl -D  $tea_header   -X GET -s -H  $Accept  -H  $Authorization  $(eval "printf '%s ' $(x curl gencode -G $([ $# -eq 0 ] || printf "%s== " "$@"))")  $url"
-            x ccmd 3m --             eval x curl -D "$tea_header"  -X GET -s -H "$Accept" -H "$Authorization" $(eval "printf '%s ' $(x curl gencode -G $([ $# -eq 0 ] || printf "%s== " "$@"))") "$url"
-            ___x_cmd_tea_http_error  eval x curl -D "$tea_header"  -X GET -s -H "$Accept" -H "$Authorization" $(eval "printf '%s ' $(x curl gencode -G $([ $# -eq 0 ] || printf "%s== " "$@"))") "$url"
+            tea:debug "x curl -D  $tea_header   -X GET -s -H  $_accept  -H $_content   -H  $_authorization  $(eval "printf '%s ' $(x curl gencode $(___x_cmd_tea_curl___use_query_data "$@"))")  $_curl_url"
+            if [ -n "$NO_CACHE" ]; then
+                eval   x curl -D "$tea_header"  -X GET -s -H "$_accept" -H "$_content" -H "$_authorization" $(eval "printf '%s ' $(x curl gencode $(___x_cmd_tea_curl___use_query_data "$@"))") "$_curl_url"
+            else
+                x ccmd 10s --        eval x curl -D "$tea_header"  -X GET -s -H "$_accept" -H "$_content" -H "$_authorization" $(eval "printf '%s ' $(x curl gencode $(___x_cmd_tea_curl___use_query_data "$@"))") "$_curl_url"
+            fi
+            ___x_cmd_tea_http_error  eval x curl -D "$tea_header"  -X GET -s -H "$_accept" -H "$_content" -H "$_authorization" $(eval "printf '%s ' $(x curl gencode $(___x_cmd_tea_curl___use_query_data "$@"))") "$_curl_url"
             return
             ;;
-        post)
-            req="POST";;
-        put)
-            req="PUT";;
-        patch)
-            req="PATCH";;
-        delete)
-            req="DELETE";;
-        download)
-            mkdir -p "${1%/*}"
-            tea_log debug "x curl -L -D  $tea_header   -X GET -H  $Accept  -H  $Authorization    -o  $1   $url"
-                    eval  x curl -L -D "$tea_header"  -X GET -H "$Accept" -H "$Authorization"   -o "$1" "$url"
-            ___x_cmd_tea_http_error
-            return
-            ;;
+        post)           req="POST"      ;;
+        put)            req="PUT"       ;;
+        patch)          req="PATCH"     ;;
+        delete)         req="DELETE"    ;;
     esac
-    tea_log debug "eval x curl -D $tea_header -X $req    -s  -H $Accept -H $Content -H $Authorization $(x curl gencode "$@") $url"
+    tea:debug "x curl -D  $tea_header  -X  $req  -s -H  $_accept  -H  $_content  -H  $_authorization   $(x curl gencode "$@")   $_curl_url"
+    eval       x curl -D "$tea_header" -X "$req" -s -H "$_accept" -H "$_content" -H "$_authorization" "$(x curl gencode "$@")" "$_curl_url"
+    ___x_cmd_tea_http_error
+}
 
-    eval x curl -D "$tea_header" -X "$req"  -s -H "$Accept" -H "$Content"  -H "$Authorization" "$(x curl gencode "$@")" "$url"
-
-
+___x_cmd_tea_curl___use_query_data(){
+    [ $# -gt 0 ] || return
+    local name
+    printf "%s " "-G"
+    for name in "$@";
+    do
+        if [ "$name" = "p" ];then  [ -z "$p" ] || printf "%s " "path==$p";
+        else                                      printf "%s " "$name==" ;
+        fi
+    done
 }
 
 ___x_cmd_tea_http_error(){
     local http_resp_code
-    http_resp_code=$(______x_cmd_tea_resp_header_code)
+    http_resp_code=$(___x_cmd_tea_resp_code)
     if [ -n "$http_resp_code" ] && [ "$http_resp_code" -ge 200 ] && [ "$http_resp_code" -le 303 ]; then
         return 0
     else
-        [ $# -eq 0 ] || x ccmd invalidate "$@" >/dev/null
-        tea_log error "HTTP Code Is $http_resp_code"
+        [ $# -eq 0 ] || {
+            tea:debug "---! Cache Clear !---"
+            x ccmd invalidate "$@" 1>/dev/null 2>&1
+        }
+        [ -z "$___X_CMD_TEA_SHOW_HTTP_CODE" ] || {
+            tea:error "HTTP Code is $http_resp_code"
+            if command -v unset 1>/dev/null; then
+                unset ___X_CMD_TEA_SHOW_HTTP_CODE
+            fi
+        }
         return 1
     fi
 }
+
+___x_cmd_tea____handle_resp(){
+    [ -z "$tea_resp_body" ] || printf "%s" "$tea_resp_body"
+    [ -z "$tea_resp_err" ]  || printf "  \033[31m-\033[0m \033[1mErrorMsg: \033[31m%s\033[0m\n" "$tea_resp_err" >&2
+}
+
+___x_cmd_tea____handle_no_content(){
+    local tea_resp_body
+    local tea_resp_err
+    x jo env . tea_resp_body=. tea_resp_err=.message
+
+    [ -z "$gh_resp_body" ] || {
+        tea:debug "tea_resp_body: $tea_resp_body"
+        ___x_cmd_tea____handle_resp
+        return 1
+    }
+    ___x_cmd_gh_http_error
+}
 # EndSection
 
-# Section: pagination
+# Section: Resolve pagination
 ___x_cmd_tea_get_multi() {
-    if [ -n "$page" ] || [ -n "$per_page" ]; then
-        ___x_cmd_tea_curl get "$@" page per_page
+    if [ -n "$page" ] || [ -n "$limit" ]; then
+        ___x_cmd_tea_curl get "$@" page limit
         return
     fi
 
     local page=1
-    local per_page=100
+    local limit=100
     if [ -n "$json" ] || [ -n "$ENFORCE_JSON" ]; then
         ___x_cmd_tea_get_multi___json_prt "$@"
     else
@@ -84,7 +127,7 @@ ___x_cmd_tea_get_multi() {
 
 }
 ___x_cmd_tea_get_multi___ui_table(){
-    ___x_cmd_tea_curl get "$@" page per_page
+    ___x_cmd_tea_curl get "$@" page limit
     printf "\n"
     local next_url
     _____x_cmd_tea_next_url
@@ -100,7 +143,7 @@ ___x_cmd_tea_get_multi___ui_table(){
 ___x_cmd_tea_get_multi___json_prt(){
     local tmp
     tmp=$(mktemp)
-    ___x_cmd_tea_curl get "$@" page per_page > "$tmp"
+    ___x_cmd_tea_curl get "$@" page limit > "$tmp"
     printf "\n" >> "$tmp"
 
     local next_url
@@ -161,7 +204,8 @@ ___x_cmd_tea_param_normalize_repo() {
     *)
         ___x_cmd_tea_current_owner 1>/dev/null 2>&1
         if [ -z "$___X_CMD_TEA_DEFAULT_OWNER" ]; then
-            printf "No owner provided. Default owner not set.\n" >&2
+            tea:error "No owner provided. Default owner not set."
+            tea:warn "Check your current token setting.$(_____x_cmd_tea_help__token_setting)"
             return 1
         fi
         owner_repo="$(printf "%s" "$___X_CMD_TEA_DEFAULT_OWNER/$op")"
@@ -194,7 +238,11 @@ ___tea_ui_mutual() {
         # run ui table
         eval "$tmp"
     fi
-    return
+    local ___tea_exit_code="$?"
+    [ "$___tea_exit_code" -eq 0 ] || {
+        ___x_cmd_ui_tf false "${___tea_error_msg:-"Couldn't find any data"}" ;
+        return "$___tea_exit_code"
+    }
 }
 
 _____x_cmd_tea_advise() {
@@ -208,4 +256,3 @@ _____x_cmd_tea_advise_parse() {
     esac
 }
 # EndSection
-
diff --git a/mod/theme/latest b/mod/theme/latest
--- a/mod/theme/latest
+++ b/mod/theme/latest
@@ -2,49 +2,31 @@
 
 xrc param/latest
 
-# Section: main
 ___x_cmd_theme_control(){
-    param:advise theme
-    local zinit
-    local unplugin
-    local font
-    [ -z "$ZSH_VERSION" ]       || zinit="zinit    \"init the zsh environment\""
-    [ -z "$ZSH_VERSION" ]       || unplugin="unplugin    \"unset zsh plugins\""
-    [ -n "$SSH_CONNECTION" ]    || [ -f "/.dockerenv" ] || font="font    \"install powerline font\""
-    param:dsl <<A
-subcommands:
-    ls          "list all theme"
-    app         "open theme preview client to choose theme"
-    use         "use theme when starting the shell"
-    try         "try theme"
-    ${zinit}
-    ${unplugin}
-    ${font}
-    unset       "unset the theme"
-A
-    param:run
-
-    if [ -z "$PARAM_SUBCMD" ]; then
-        ___x_cmd_theme_control_app "$@"
-        return
-    fi
-
-    "___x_cmd_theme_control_${PARAM_SUBCMD}" "$@"
+    local op="$1"
+    case "$op" in
+        ls|use|try|font|zinit|unset)    shift; "___x_cmd_theme_control_$op" "$@"   ;;
+        -h|--help)                      _____x_cmd_theme_help                      ;;
+        *)                              ___x_cmd_theme_control_app "$@"            ;;
+    esac
 }
 
-# Section: ls which
+# Section: ls and which
 ___x_cmd_theme_control_ls() {
-    param:void
-
-    # check and update theme source
+    local op="$1"
+    case "$op" in
+        --no-cache)                 shift; local ___X_CMD_THEME_ASSET_NO_CACHE=1  ;;
+        -h|--help)                  _____x_cmd_theme_help ls; return              ;;
+    esac
     local _tgzfilepath
-    ___x_cmd_theme___which_tgz___tgzfilepath || return 1
-    if [ "$___X_CMD_HTTPGET_AGE" -lt 3600 ]; then
-        x rmrf "$___X_CMD_ROOT_DATA/theme/tgz"
+    ___x_cmd_theme___which_tgz___tgzfilepath   || return 1
+    if [ -n "$___X_CMD_THEME_ASSET_NO_CACHE" ] || [ "$___X_CMD_HTTPGET_AGE" -lt 86400 ]; then # 1-Day
+        x rmrf "${___X_CMD_ROOT_DATA}/theme/tgz"
     fi
 
     local filepath
-    ___x_cmd_theme___which___filepath index.yml && awk 'op==1{ if ($0 ~ /^-/) exit(0); if($2 != "") print $2; };  op==0{  if ($2 == "all") op=1; }' <"$filepath"
+    ___x_cmd_theme___which___filepath index.yml && \
+        awk 'op==1{ if ($0 ~ /^-/) exit(0); if($2 != "") print $2; };  op==0{  if ($2 == "all") op=1; }' <"$filepath"
 }
 
 ___x_cmd_theme___which___filepath(){
@@ -59,9 +41,8 @@ ___x_cmd_theme___which___filepath(){
 
         local _src_code
         if ! tar xf "$_tgzfilepath" -C "$tmp_style_dir" "$filename" 2>/dev/null; then
-            printf "\033[31m%s\033[33m%s\n%s \033[1;36m%s\033[0m\n" \
-                "[x-cmd]: Not found theme in cache." " Check the theme name is exist." \
-                "Or you can try run command to update cache." "\`x theme ls\`"
+            x log :theme error "Not found theme in cache sources. Check the theme name is exist."
+            x log :theme info  "Can try run command to update theme sources." "${___X_CMD_UNSEENCHAR_033}[36m\`x theme ls --no-cache\`${___X_CMD_UNSEENCHAR_033}[0m"
             return 1
         fi
     fi
@@ -69,17 +50,16 @@ ___x_cmd_theme___which___filepath(){
 }
 
 ___x_cmd_theme___which_tgz___tgzfilepath(){
-    _tgzfilepath="$___X_CMD_ROOT_DATA/theme/theme.tgz"
-    if ! ___x_cmd_httpget_gitx x-cmd theme main "dist/theme.tgz" "$_tgzfilepath" 3600; then # 1-Hour
+    _tgzfilepath="${___X_CMD_ROOT_SHARED}/theme/theme.tgz"
+    local _expiration=86400 # 1-Day
+    [ -z "$___X_CMD_THEME_ASSET_NO_CACHE" ] || _expiration='-'
+
+    if ! x httpget gitx x-cmd theme main "dist/theme.tgz" "$_tgzfilepath" "$_expiration"; then
         if [ ! -f "$cache" ]; then
-            x:error "Unaviable theme.tgz. Unable to fetch theme.tgz."
+            x log :theme error "Unavailable theme.tgz. Unable to fetch theme.tgz."
             return 1
         fi
-        # return 0
     fi
-    # if [ -n "$___X_CMD_HTTPGET_UPDATED" ]; then
-    #     x rmrf "$___X_CMD_ROOT_DATA/theme/tgz"
-    # fi
 }
 
 # EndSection
@@ -87,46 +67,33 @@ ___x_cmd_theme___which_tgz___tgzfilepath(){
 # Section: use
 xrc:mod:lib theme   lib   style
 
-___x_cmd_theme_control_use(){
-    param:dsl <<A
-advise:
-    #1          xrc theme/latest && candidate_exec_arr=( \\\$(___x_cmd_theme_control_ls) )
-options:
-    #1          "return theme list name"
-A
-    param:run
-
-    local name="${1:-ys}"
-    [ -z "$1" ] || shift
-    # TODO: replace xrc load control to ___X_CMD_ROOT
-    ___x_cmd_theme_control_try_inner "$name" "$*" && \
-        x boot rc add "x-theme" "xrc theme && ___x_cmd_theme_control_try_inner $name $*"
+___x_cmd_theme_control_use_default(){
+    [ ! -f "${___X_CMD_ROOT_CFG}/theme/default" ] || . "${___X_CMD_ROOT_CFG}/theme/default"
 }
 
-___x_cmd_theme_control_unset(){
-    param:void
-    local ___X_CMD_ROOT_RC="$___X_CMD_ROOT/.boot/rc"
-    if [ ! -f "$___X_CMD_ROOT_RC" ]; then
-        printf "\033[1;31m%s\033[0m\n" "[x-cmd] theme: Not found the configuration file, unset failed"
-        return 1
-    fi
-    x boot rc del x-theme
-    [ -z "$(command -v _____x_cmd_theme_unset_hook)" ] || _____x_cmd_theme_unset_hook
-    printf "\033[32m%s \033[1;33m%s\033[0m \n" "Unset the theme successfully!" "Now you can restart your terminal."
+___x_cmd_theme_control_use(){
+    local name="${1:-ys}"
+    case "$1" in
+        --help|-h)    _____x_cmd_theme_help use; return ;;
+        "")           ;;
+        *)            shift ;;
+    esac
+
+    x ensurefp "${___X_CMD_ROOT_CFG}/theme/default"
+    ___x_cmd_theme_control_try_inner "$name" "$*" && \
+        printf "%s\n" "___x_cmd_theme_control_try_inner $name $*" >"${___X_CMD_ROOT_CFG}/theme/default" && \
+        x boot rc add "x-theme" "xrc theme && ___x_cmd_theme_control_use_default"
 }
 # EndSection
 
 # Section: try
 ___x_cmd_theme_control_try(){
-    param:dsl <<A
-advise:
-    #1          xrc theme/latest && candidate_exec_arr=( \\\$(___x_cmd_theme_control_ls) )
-options:
-    #1          "return theme list name"
-A
-    param:run
+    case "$1" in
+        --help|-h)    _____x_cmd_theme_help try; return ;;
+    esac
 
-    ___x_cmd_theme_control_try_inner "$1"
+    [ -n "$1" ] || x log :theme error "Pealse provide theme name. e.g 'x theme try ys'"
+    ___x_cmd_theme_control_try_inner "${1}"
 }
 
 ___x_cmd_theme_control_try_inner(){
@@ -135,8 +102,9 @@ ___x_cmd_theme_control_try_inner(){
     case "$name" in
         ys|"")          ___x_cmd_theme_load_format "$___X_CMD_ROOT_MOD/theme/lib/ys" ;;
         */*)            ___x_cmd_theme_load_format "$(xrc which "$name")" ;;
-        *)      local filepath; ___x_cmd_theme___which___filepath "style/$name" && \
-                        ___x_cmd_theme_load_format "$filepath"
+        *)              local filepath; ___x_cmd_theme___which___filepath "style/$name" && \
+                            ___x_cmd_theme_load_format "$filepath" || return 1
+                        ;;
     esac
     ___X_CMD_THEME_NAME="$name"
     [ -z "$(command -v _____x_cmd_theme_register_hook)" ] || _____x_cmd_theme_register_hook
@@ -145,38 +113,33 @@ ___x_cmd_theme_control_try_inner(){
 
 # Section: zsh
 ___x_cmd_theme_control_zinit(){
-    param:void
+    case "$1" in
+        --help|-h)    _____x_cmd_theme_help zinit; return ;;
+    esac
+
     # load theme
     [ -n "$(command -v ___x_cmd_theme_prompt_format)" ] || ___x_cmd_theme_control_use ""
     # load zsh plugins
     if [ -z "$ZSH_AUTOSUGGEST_COMPLETIONS_PTY_NAME" ] || [ -z "$ZSH_HIGHLIGHT_REVISION" ]; then
-        # TODO: wait x pkg ls output empty
-        if ! x pkg ls i | grep "zsh-plugin" >/dev/null; then
-            x pkg install zsh-plugin
-        fi
+        x pkg install zsh-plugin || return
         ZSH_PLUGIN="zsh-syntax-highlighting,zsh-autosuggestions" x pkg activate zsh-plugin
         x boot rc add "x-zsh-plugin" \
             "[ -n \"\$ZSH_VERSION\" ] && ZSH_PLUGIN=\"zsh-syntax-highlighting,zsh-autosuggestions\" x pkg activate zsh-plugin"
+        x log :theme "ZSH plugin \"syntax-highlighting\" and \"autosuggestions\" initialized"
     fi
     # load font
     [ -n "$SSH_CONNECTION" ] || [ -f "/.dockerenv" ] || ___x_cmd_theme_control_font
-    printf "%s\n" "[x-cmd]: Successfully initialized."
-}
-
-___x_cmd_theme_control_unplugin(){
-    param:void
-    if x boot rc del "x-zsh-plugin"; then
-        printf "\033[32m%s \033[1;33m%s\033[0m \n" "Unset ZSH plugins successfully!" "Now you can restart your terminal."
-    else
-        printf "\033[31m%s\033[0m \n" "Unset ZSH plugins failed."
-        return 1
-    fi
+    x log :theme "Successfully initialized"
 }
 # EndSection
 
-# Section: font app
+# Section: font
+# shellcheck disable=2120
 ___x_cmd_theme_control_font() {
-    param:void
+    case "$1" in
+        --help|-h)    _____x_cmd_theme_help font; return ;;
+    esac
+
     local _font_dir
     local _font_name='Fira Code Retina Nerd Font Complete.ttf'
     if [ "$(uname)" = "Darwin" ]; then
@@ -188,27 +151,43 @@ ___x_cmd_theme_control_font() {
         mkdir -p "$_font_dir"
     fi
     if [ -f "$_font_dir/$_font_name" ]; then
-        printf "%s\n" "[x-cmd]: font already installed: $_font_dir"
+        x log :theme "Font already installed to $_font_dir"
     else
         local cache="$_font_dir/nerdfont.tgz"
         local expiration=""
-        if ! ___x_cmd_httpget_gitx x-cmd theme main "font/nerdfont.tgz" "$cache" "$expiration"; then
-            printf "\033[31m%s\033[0m\n" "[x-cmd]: nerdfont install failed"
+        if ! x httpget gitx x-cmd theme main "font/nerdfont.tgz" "$cache" "$expiration"; then
+            x log :theme error "Nerdfont install failed"
             return 1
         fi
 
         tar -zxf "$cache" -C "$_font_dir" || return 1
 
         if command -v fc-cache >/dev/null; then
-            printf "%s\n" "[x-cmd]: Resetting font cache, this may take a moment..."
+            x log :theme "Resetting font cache, this may take a moment..."
             command fc-cache -f "$_font_dir"
         fi
     fi
 }
+# EndSection
 
+# Section: unset
+___x_cmd_theme_control_unset(){
+    case "$1" in
+        --help|-h)  _____x_cmd_theme_help unset ; return ;;
+        zplugin)    x boot rc del "x-zsh-plugin"
+                    x log :theme "Unset ZSH plugins successfully." "${___X_CMD_UNSEENCHAR_033}[1;33mNow you can restart your terminal.${___X_CMD_UNSEENCHAR_033}[0m"
+                    return ;;
+        all)        x boot rc del "x-zsh-plugin";;
+    esac
+    x boot rc del x-theme
 
+    [ -z "$(command -v _____x_cmd_theme_unset_hook)" ] || _____x_cmd_theme_unset_hook
+    x log :theme "Unset the theme ${1:+"and ZSH plugin "}successfully." "${___X_CMD_UNSEENCHAR_033}[1;33mNow you can restart your terminal.${___X_CMD_UNSEENCHAR_033}[0m"
+}
+# EndSection
+
+# Section: app
 ___x_cmd_theme_control_app(){
-    param:void
     if ___x_cmd_theme___which___filepath index.yml; then
         xrc theme/lib/app
         local ___X_CMD_THEME_FINAL_COMMAND
@@ -222,6 +201,12 @@ ___x_cmd_theme_control_app(){
 
 # EndSection
 
+# Section: help
+# shellcheck disable=2120
+_____x_cmd_theme_help(){
+    command -v ___x_cmd_advise_gen_help >/dev/null || xrc:mod advise/lib/gen_help
+    ___x_cmd_advise_gen_help "$___X_CMD_ROOT_MOD/theme/res/advise.jso" "$@"
+}
+# EndSection
+
 xrc setmain ___x_cmd_theme_control
-
-
diff --git a/mod/ui/lib/truefalse b/mod/ui/lib/truefalse
--- a/mod/ui/lib/truefalse
+++ b/mod/ui/lib/truefalse
@@ -1,35 +1,47 @@
 # shellcheck shell=sh disable=SC3043
 
 # author:       Li Junhao           l@x-cmd.com
+
 ___x_cmd_ui_tf(){
-    ___x_cmd_ui_tf__draw_awk "$@"
+    arg:init x 'x ui -h'
+    arg:1:nonempty
+    local op="$1"
+    local text="$2"
+    [ -n "$text" ] || M="Please provide text" arg:ret:64
+    shift 2
+    case "$op" in
+        true|success)               ___x_cmd_ui_tf__draw "- ✓" "$(___x_cmd_ui_style green )" "$text"  ;; # "✔"
+        false|error|failure)        ___x_cmd_ui_tf__draw "- X" "$(___x_cmd_ui_style error)" "$text" ;;
+        skipped|*)                  ___x_cmd_ui_tf__draw "-" "$(___x_cmd_ui_style yellow)" "$text" ;;
+    esac
+
+    local arg= ; for arg in "$@"; do
+        ___X_CMD_UI_TF_INDENT="${___X_CMD_UI_TF_INDENT}  " ___x_cmd_ui_tf skipped "$arg"
+    done
 }
 
-___x_cmd_ui_tf__draw_awk(){
-    local ui_status="${1:?Provide status}"; shift
-    { local arg; for arg in "$@"; do printf "%s\n" "$arg"; done ;} | \
-    NO_COLOR="$NO_COLOR" \
-    ___X_CMD_UI_TF_STATUS="$ui_status" \
-    ___X_CMD_UI_TF_LEVEL="$___X_CMD_UI_TF_LEVEL" \
-    awk "$( xrc cat awk/lib/str.awk awk/lib/ui/ui.awk )"'
-BEGIN{
-    status = ENVIRON["___X_CMD_UI_TF_STATUS"]
-    level  = ENVIRON["___X_CMD_UI_TF_LEVEL"]
-    if (ENVIRON["NO_COLOR"] == 1) UI_FG_GREEN = UI_FG_RED = UI_FG_YELLOW = UI_TEXT_BOLD = UI_END = ""
-    if (status ~ "^true|success$")                          { icon = "✓";  color = UI_FG_GREEN;           }
-    else if (status ~ "^false|error|failure$")              { icon = "X";   color = UI_FG_RED UI_TEXT_BOLD; }
-    else if (status ~ "^skipped$")                          { icon = "-";   color = UI_FG_YELLOW;           }
-    else                                                    { icon = "?";   color = UI_FG_YELLOW;           }
-}
-function view(level, color, icon, text){ print str_rep( " ", level*2 ) color icon UI_END " " text;  }
-NR==1{ view(level, color, icon, $0); next; }
-{ view(level+1, UI_FG_YELLOW, "-", $0); }
-'
-}
+___x_cmd_ui_tf__draw(){
+    local icon="$1"
+    local NO_COLOR="$NO_COLOR"
+    { [ -t 1 ] && ___x_cmd_is_interative_tty ;} || NO_COLOR=1
 
+    [ "$NO_COLOR" = 1 ] || {
+        local c_s="${2}"
+        local c_e; c_e="$(___x_cmd_ui_style end)"
+    }
+    shift 2
+    printf "${___X_CMD_UI_TF_INDENT}${c_s}%s$c_e %s\n" "$icon" "$*"
+}
 
 # ___x_cmd_ui_tf "false" "Sorry, your..."
 # ___x_cmd_ui_tf "?" "Type, dddddd..."
 # ___x_cmd_ui_tf "true" "Created, repository Markdown is 123456 light \n weight and easy-to-use syntax for styling all forms of writing on the GitHub platform."
 
-# ui tf "false" "Creating repo success" "repo_id:202213232" "url:url" "repo_owner:repo_owner"
+# x ui tf "false" "Creating repo success"
+# ___X_CMD_UI_TF_INDENT="  " x ui tf skipped "repo_id: 202213232"
+# ___X_CMD_UI_TF_INDENT="  " x ui tf skipped "url: url"
+# ___X_CMD_UI_TF_INDENT="  " x ui tf skipped "repo_owner: repo_owner"
+
+# x ui tf true "msg" "Id: Id" "Name: name" "Path: dir" "Url: url" "Visibility: visibility"
+
+# . ./.x-cmd/dev/truefalse/a
