...

diff --git a/mod/advise/lib/gen_advise b/mod/advise/lib/gen_advise
--- a/mod/advise/lib/gen_advise
+++ b/mod/advise/lib/gen_advise
@@ -2,9 +2,7 @@
 # ___X_CMD_ADVISE_GEN_ADVISE_INDEX_FIELDS='useparam
 
 ___X_CMD_ADVISE_ERREXIT="${___X_CMD_UNSEENCHAR_001}${___X_CMD_UNSEENCHAR_002}${___X_CMD_UNSEENCHAR_003}"
-___x_cmd_advise_gen_advise__index_fields(){
-    printf "%s\n" "useparam,name,synopsis,desc,tldr,other,setup,group,tip"
-}
+# useparam,name,synopsis,desc,exec,tldr,other,setup,tip,demo,subcmd,option,flag,[0-9]+,n
 
 ___x_cmd_advise_gen_advise__useparam()(
     local mod_name="${1:?Provide mod name}"
@@ -29,7 +27,7 @@ ___x_cmd_advise_gen_advise__exec()(
     x cd "$mod_path" || return 1
     local cmd; printf "%s\n" "$*" | x jo env .\* cmd=. -- '
     advise:warn "Executing: $cmd"
-    ___x_cmd_evex "$cmd" 2>/dev/null 1>&2 || {
+    ___x_cmd_evex "$cmd" 2>/dev/null || {
         advise:error "Fail to exec: $cmd"
         printf "%s\n" "$___X_CMD_ADVISE_ERREXIT"
         exit 1
@@ -40,15 +38,11 @@ ___x_cmd_advise_gen_advise__exec()(
 ___x_cmd_advise_gen_advise(){
     local mod_name="${1:?Provide mod name}"
     local mod_path="${2:?Provide mod path}"
-    local index_yml="$mod_path/adv/index.yml"
-
-    # if [ -f "$mod_path/advise.jso" ]; then
-    #     advise:warn "Skip generate $mod_name/res/advise.jso because $mod_name/advise.jso already exists"
-    #     return 0
-    # fi
+    local adv_dir="$mod_path/adv"
+    local index_yml="$adv_dir/index.yml"
 
     if [ ! -f "$index_yml" ]; then
-        advise:error "Not found $mod_name/adv/index.yml"
+        advise:error "Not found $adv_dir/index.yml"
         return 1
     fi
 
@@ -57,10 +51,14 @@ ___x_cmd_advise_gen_advise(){
         local content;      content="$(cat)"
         printf "%s\n" "$content"
 
-        local useparam;     local setup
+        local useparam;     local setup;    local jsonfile
         printf "%s\n" "$content" | { x jo env . "useparam=.<useparam>" "setup=.<setup>"
             [ -z "$setup" ] || ___x_cmd_advise_gen_advise__exec "$mod_path" "$setup" || return 1
-            [ ! -f "$mod_path/advise.jso" ] || { cat "$mod_path/advise.jso"; printf "\n"; }
+
+            find "$adv_dir" -name '*.json' -maxdepth 1 | while read -r jsonfile; do
+                advise:debug "cat $jsonfile"
+                cat "$jsonfile"; printf "\n"
+            done
 
             if [ "$useparam" = "true" ]; then
                 ___x_cmd_advise_gen_advise__useparam "$mod_name" "$mod_path"
@@ -69,15 +67,13 @@ ___x_cmd_advise_gen_advise(){
         }
     } | command awk \
         -v X_CMD_ADVISE_ERREXIT="$___X_CMD_ADVISE_ERREXIT" \
-        -v INDEX_FIELDS="$( ___x_cmd_advise_gen_advise__index_fields )" \
         -f "$___X_CMD_ROOT_MOD/awk/lib/default.awk" \
-        -f "$___X_CMD_ROOT_MOD/awk/lib/j/json.awk" \
+        -f "$___X_CMD_ROOT_MOD/awk/lib/j/json.awk"  \
         -f "$___X_CMD_ROOT_MOD/awk/lib/j/jiter.awk" \
-        -f "$___X_CMD_ROOT_MOD/awk/lib/j/jcp.awk" \
+        -f "$___X_CMD_ROOT_MOD/awk/lib/j/jcp.awk"   \
         -f "$___X_CMD_ROOT_MOD/advise/lib/awk/build_merge.awk" > "$resource/advise.jso"
     local exit_code="$?"
 
-    [ ! -f "$mod_path/advise.jso" ] || x rmrf "$mod_path/advise.jso"
     if [ "$exit_code" -eq 0 ]; then
         advise:info "Success generate $mod_name res/advise.jso"
         return 0
diff --git a/mod/log/latest b/mod/log/latest
--- a/mod/log/latest
+++ b/mod/log/latest
@@ -231,9 +231,8 @@ ___X_CMD_LOG_C_TF="${___X_CMD_LOG_C_TF:-""}"
 
 ___X_CMD_LOG__TIMESTAMP_FORMAT=      # "+%H:%M:%S"      # Enable Timestamp.
 
-___X_CMD_LOG_C_MSG="${___X_CMD_LOG_C_MSG:-""}"
 ___X_CMD_LOG_C_DEBUG="${___X_CMD_LOG_C_DEBUG:-"\\033[2;35m"}"
-___X_CMD_LOG_C_INFO="${___X_CMD_LOG_C_INFO:-"\\033[1;36m"}"
+___X_CMD_LOG_C_INFO="${___X_CMD_LOG_C_INFO:-"\\033[32m"}"
 ___X_CMD_LOG_C_WARN="${___X_CMD_LOG_C_WARN:-"\\033[1;33m"}"
 ___X_CMD_LOG_C_ERROR="${___X_CMD_LOG_C_ERROR:-"\\033[1;31m"}"
 
@@ -242,11 +241,11 @@ ___X_CMD_LOG_C_TIMESTAMP_END="${___X_CMD_LOG_C_WARN:-"]"}"
 
 ___x_cmd_log_pr(){
     case "${2:?Provide level}" in
-        debug)      eval "test -z \"\$___X_CMD_LOG_DEBUG\" -a 1 -lt \"\${___X_CMD_LOG__${1#:}:-2}\"" || { local O="${1#:}"; shift 2; L=DBG C="$___X_CMD_LOG_C_DEBUG"  ___x_cmd_log_0 "$@"; } ;;
-        info)       eval "test -z \"\$___X_CMD_LOG_DEBUG\" -a 2 -lt \"\${___X_CMD_LOG__${1#:}:-2}\"" || { local O="${1#:}"; shift 2; L=INF C="$___X_CMD_LOG_C_INFO"   ___x_cmd_log_0 "$@"; } ;;
-        warn)       eval "test -z \"\$___X_CMD_LOG_DEBUG\" -a 3 -lt \"\${___X_CMD_LOG__${1#:}:-2}\"" || { local O="${1#:}"; shift 2; L=WRN C="$___X_CMD_LOG_C_WARN"   ___x_cmd_log_0 "$@"; } ;;
-        error)      eval "test -z \"\$___X_CMD_LOG_DEBUG\" -a 4 -lt \"\${___X_CMD_LOG__${1#:}:-2}\"" || { local O="${1#:}"; shift 2; L=ERR C="$___X_CMD_LOG_C_ERROR"  ___x_cmd_log_0 "$@"; } ;;
-        *)          eval "test -z \"\$___X_CMD_LOG_DEBUG\" -a 3 -lt \"\${___X_CMD_LOG__${1#:}:-2}\"" || { local O="${1#:}"; shift 1; L=INF C="$___X_CMD_LOG_C_INFO"   ___x_cmd_log_0 "$@"; } ;;
+        debug)      eval "test -z \"\$___X_CMD_LOG_DEBUG\" -a 1 -lt \"\${___X_CMD_LOG__${1#:}:-2}\"" || { local O="${1#:}"; shift 2; L=DBG C="$___X_CMD_LOG_C_DEBUG"                   ___x_cmd_log_0 "$@"; } ;;
+        info)       eval "test -z \"\$___X_CMD_LOG_DEBUG\" -a 2 -lt \"\${___X_CMD_LOG__${1#:}:-2}\"" || { local O="${1#:}"; shift 2; L=INF C="$___X_CMD_LOG_C_INFO"  C_MSG="\\033[0m"  ___x_cmd_log_0 "$@"; } ;;
+        warn)       eval "test -z \"\$___X_CMD_LOG_DEBUG\" -a 3 -lt \"\${___X_CMD_LOG__${1#:}:-2}\"" || { local O="${1#:}"; shift 2; L=WRN C="$___X_CMD_LOG_C_WARN"  C_BG="\\033[7m"   ___x_cmd_log_0 "$@"; } ;;
+        error)      eval "test -z \"\$___X_CMD_LOG_DEBUG\" -a 4 -lt \"\${___X_CMD_LOG__${1#:}:-2}\"" || { local O="${1#:}"; shift 2; L=ERR C="$___X_CMD_LOG_C_ERROR" C_BG="\\033[7m"   ___x_cmd_log_0 "$@"; } ;;
+        *)          eval "test -z \"\$___X_CMD_LOG_DEBUG\" -a 3 -lt \"\${___X_CMD_LOG__${1#:}:-2}\"" || { local O="${1#:}"; shift 1; L=INF C="$___X_CMD_LOG_C_INFO"  C_MSG="\\033[0m"  ___x_cmd_log_0 "$@"; } ;;
     esac
 }
 
@@ -255,15 +254,15 @@ ___x_cmd_log_pr_debug(){
 }
 
 ___x_cmd_log_pr_info(){
-    L=INF C="$___X_CMD_LOG_C_INFO"  ___x_cmd_log_0 "$@"
+    L=INF C="$___X_CMD_LOG_C_INFO"  C_MSG="\\033[0m"  ___x_cmd_log_0 "$@"
 }
 
 ___x_cmd_log_pr_warn(){
-    L=WRN C="$___X_CMD_LOG_C_WARN"  ___x_cmd_log_0 "$@"
+    L=WRN C="$___X_CMD_LOG_C_WARN"  C_BG="\\033[7m"   ___x_cmd_log_0 "$@"
 }
 
 ___x_cmd_log_pr_error(){
-    L=ERR C="$___X_CMD_LOG_C_ERROR"  ___x_cmd_log_0 "$@"
+    L=ERR C="$___X_CMD_LOG_C_ERROR" C_BG="\\033[7m"   ___x_cmd_log_0 "$@"
 }
 
 ___x_cmd_log_0(){
@@ -280,10 +279,9 @@ ___x_cmd_log_0(){
         fi
 
         if [ $# -gt 0 ]; then
-            [ "$L" != "INF" ] || local ___X_CMD_LOG_C_MSG="\\033[1m"
-            printf "${timestamp}${C}[%s] <%s> $track: \033[0m${___X_CMD_LOG_C_MSG:-"$C"}%s\033[0m\n" "$L" "$O" "$*"
+            printf "${timestamp}${C}${C_BG}[%s]\033[0m${C} <%s> $track: ${C_MSG}%s\033[0m\n" "$L" "$O" "$*"
         else
-            printf "${timestamp}${C}[%s] <%s> $track: " "$L" "$O"
+            printf "${timestamp}${C}${C_BG}[%s]\033[0m${C} <%s> $track: ${C_MSG}" "$L" "$O"
             cat | awk 'NR==1{ print($0) }; NR>=2{ print("> " $0); }; END{ printf("%s", "\033[0m"); }'
         fi
     else
