...

diff --git a/mod/advise/lib/gen_advise b/mod/advise/lib/gen_advise
--- a/mod/advise/lib/gen_advise
+++ b/mod/advise/lib/gen_advise
@@ -127,3 +127,43 @@ ___x_cmd_advise_gen_advise(){
         return 1
     fi
 }
+
+# Section: x-cmd-advise test
+___x_cmd_advise___install_xcmd_dir(){
+    local dir="${1:-$PWD}"
+    local name="$2";
+    [ -n "$name" ] || name="$(basename "$dir")"
+    ___x_cmd_advise___install_xcmd_dir_ "$name" "$dir"
+    ___x_cmd_advise_man_xcmd_load_one "$name"
+}
+
+___x_cmd_advise___install_xcmd_dir_()(
+    local name="$1"
+    local dir="${2:-$PWD}"
+    [ -n "$name" ] || M='Provide command name' N=advise log:ret:64
+    [ -d "$dir" ] || M='Provide x-cmd-advise directory' N=advise log:ret:64
+    cd "$dir" || return
+
+    local folder="${3:-"$___X_CMD_ADVISE_MAN_XCMD_FOLDER"}/$name";
+    x rmrf "$folder"
+    x mkdirp "$folder"
+    ____x_cmd_advise___install_y2j advise.yml > "$folder/advise.t.jso" || return
+
+    find _ -type f -name '*advise.yml' 2>/dev/null | while read -r line; do
+        dst="$folder/${line%.yml}.t.jso"
+        x ensurefp "$dst"
+        ____x_cmd_advise___install_y2j "$line" > "$dst" || return
+    done
+)
+
+____x_cmd_advise___install_y2j(){
+    [ -f "$1" ] || return
+    local tmp="$___X_CMD_ROOT_TMP/advise/tmp.jso";          x ensurefp "$tmp"
+    x yml y2j "$1" > "$tmp" || {
+        x:error "Failed $1 yml y2j"
+        return 1
+    }
+    < "$tmp" ___x_cmd_advise_gen_advise__merge_awk
+}
+
+# EndSection
diff --git a/mod/gh/lib/repo/collaborator/invitation b/mod/gh/lib/repo/collaborator/invitation
--- a/mod/gh/lib/repo/collaborator/invitation
+++ b/mod/gh/lib/repo/collaborator/invitation
@@ -5,10 +5,10 @@ ___x_cmd_gh_repo_collaborator_invitation() {
     param:scope  ___x_cmd_github
     param:subcmd ___x_cmd_gh_repo_collaborator_invitation    \
         "ls|l"         "List invitation for repo or current user"   \
-        "edit|ed"      "Edit invitation permission"                 \
-        "accept"       "Accept invitation"                          \
-        "decline"      "Decline invitation"                         \
-        rm             "Delete a repository invitation"
+        "edit|ed"      "Edit repository invitation permission"      \
+        accept         "Accept invitation for user"                 \
+        rm             "Decline invitation for user"                \
+        cancel         "Cancel the invitation by the repository"
 
     param:subcmd:try
     param:run
@@ -32,7 +32,7 @@ options:
 '
     param:run
     local _url="/user/repository_invitations"
-    [ -n "$repo" ] || {
+    [ -z "$repo" ] || {
         ___x_cmd_gh_param_init_owner_repo
         _url="/repos/${owner_repo}/invitations"
     }
@@ -41,8 +41,8 @@ options:
         ___x_cmd_gh_get_multi "$_url"
     else
         ___x_cmd_gh_get_multi "$_url" | \
-            x jo 2c             .id  .repository.full_name  .inviter.login  .invitee.login  .permissions | \
-            x csv header --add   ID   Repo                   Inviter         Invitee         Permission  | \
+            x jo 2c             .id  .repository.full_name  .inviter.login  .invitee.login  .permissions .expired | \
+            x csv header --add   ID   Repo                   Inviter         Invitee         Permission   Is_Expired| \
             x csv static_tab
     fi
 }
@@ -80,13 +80,13 @@ options:
     param:run
     local __id=
     for __id in "$@"; do
-    ___x_cmd_gh_curl patch "/user/repository_invitations/${1##*/}" | (
+    ___x_cmd_gh_curl patch "/user/repository_invitations/${__id##*/}" | (
             [ -z "$___X_CMD_GH_IN_TEST" ] || { command cat; return; }
             x jo env . gh_resp_msg=.message gh_resp_err=.errors
             if ___x_cmd_gh_http_error; then
-                ___x_cmd_ui_tf  true "[Success]: Accept ${1##*/} interception"
+                ___x_cmd_ui_tf  true "[Success]: Accept ${__id##*/} interception"
             else
-                ___x_cmd_ui_tf false "Accept ${1##*/} interception failure:" >&2
+                ___x_cmd_ui_tf false "Accept ${__id##*/} interception failure:" >&2
                 ___x_cmd_gh____handle_resp
                 return 1
             fi
@@ -97,7 +97,7 @@ options:
 
 # Section: Decline
 # https://docs.github.com/en/rest/collaborators/invitations#decline-a-repository-invitation
-___x_cmd_gh_repo_collaborator_invitation_decline() {
+___x_cmd_gh_repo_collaborator_invitation_rm() {
     param:scope ___x_cmd_github
     param:dsl '
 options:
@@ -105,16 +105,16 @@ options:
     --yes|-y    "Ignore remove prompt interception"
 '
     param:run
-    local __id=
+    local __id=""
     for __id in "$@"; do
         [ "$yes" = "true" ] || ___x_cmd_ui_yesno "Are you sure decline interception: $(___x_cmd_ui bold red "$__id") ?" || continue
-        ___x_cmd_gh_curl del "/user/repository_invitations/${1##*/}" | (
+        ___x_cmd_gh_curl del "/user/repository_invitations/${__id##*/}" | (
             [ -z "$___X_CMD_GH_IN_TEST" ] || { command cat; return; }
             x jo env . gh_resp_msg=.message gh_resp_err=.errors
             if ___x_cmd_gh_http_error; then
-                ___x_cmd_ui_tf  true "[Success]: Decline ${1##*/} interception"
+                ___x_cmd_ui_tf  true "[Success]: Decline ${__id##*/} interception"
             else
-                ___x_cmd_ui_tf false "Decline ${1##*/} interception failure:" >&2
+                ___x_cmd_ui_tf false "Decline ${__id##*/} interception failure:" >&2
                 ___x_cmd_gh____handle_resp
                 return 1
             fi
@@ -125,7 +125,7 @@ options:
 
 # Section: Remove
 # https://docs.github.com/en/rest/collaborators/invitations#delete-a-repository-invitation
-___x_cmd_gh_repo_collaborator_invitation_rm() {
+___x_cmd_gh_repo_collaborator_invitation_cancel() {
     param:scope ___x_cmd_github
     param:dsl '
 options:
@@ -138,7 +138,7 @@ options:
     ___x_cmd_gh_param_init_owner_repo
     local __id=
     for __id in "$@"; do
-        [ "$yes" = "true" ] || ___x_cmd_ui_yesno "Are you sure $owner_repo to remove interception: $(___x_cmd_ui bold red "$username") ?" || continue
+        [ "$yes" = "true" ] || ___x_cmd_ui_yesno "Are you sure $owner_repo to remove interception: $(___x_cmd_ui bold red "$__id") ?" || continue
         ___x_cmd_gh_curl del "/repos/$owner_repo/invitations/${__id##*/}"| (
                 [ -z "$___X_CMD_GH_IN_TEST" ] || { command cat; return; }
                 x jo env . gh_resp_msg=.message gh_resp_err=.errors
diff --git a/mod/gl/lib/utils b/mod/gl/lib/utils
--- a/mod/gl/lib/utils
+++ b/mod/gl/lib/utils
@@ -7,7 +7,7 @@ _____x_cmd_gl_help__token_setting(){
     printf "\n%s %s \n%s\n" \
         "$(___x_cmd_ui yellow 'Run command to add|repleace token:')" \
         "$(___x_cmd_ui bold cyan "\`x gl token <token>\`")"   \
-        "$(___x_cmd_ui 'https://gitlab.com/-/profile/personal_access_tokens')"
+        "$(___x_cmd_ui "$(___x_cmd_gl___get_web_host)/-/profile/personal_access_tokens")"
 }
 
 _____x_cmd_gl_help(){
@@ -22,68 +22,46 @@ ___x_cmd_gl_resp_header(){
 }
 
 ___x_cmd_gl_resp_code(){
-    ___x_cmd_gl_resp_header  | awk '$1 ~/HTTP\/2$/ {print ($2+0);exit(0)}'
+    ___x_cmd_gl_resp_header | _____x_cmd_gx_get_resp_code_by_header
 }
 
 ___x_cmd_gl_curl(){
     local op="$1"
-    local _curl_url="\"${___X_CMD_GL_DOMAIN:-"https://gitlab.com"}/api/v4${2}\""
-    local _content_type="\"Content-Type: application/json\""
-    local _authorization
-    _authorization="\"PRIVATE-TOKEN: $(___x_cmd_gl_token)\""
-    local gl_header="$___X_CMD_GL_TMP/.____x_cmd_gl_curl_header"
-    local ___X_CMD_GL_SHOW_HTTP_CODE=1
+    local _api_url="$2"
     shift 2
-    local req
+    local ___X_CMD_API_GL_HEADER="-s -H \"Content-Type: application/json\" -D \"$___X_CMD_GL_TMP/.____x_cmd_gl_curl_header\""
+
+    local _curl_host_tmp=""
+    local ___X_CMD_API_GL_TOKEN=""
+    ___x_cmd_gl_config___var  ___X_CMD_API_GL_TOKEN=token _curl_host_tmp=host 2>/dev/null
+    local ___X_CMD_API_GL_HOST="${___X_CMD_API_GODE_HOST:-"$_curl_host_tmp"}"
+
+    local ___X_CMD_GL_SHOW_HTTP_CODE=1
     case "$op" in
         get)
-            gl:debug   "x curl -D  $gl_header   -X GET -s -H  $_content_type  -H  $_authorization  $(eval "printf '%s ' $(x curl gencode $(___x_cmd_gl_curl___use_query_data "$@"))")  $_curl_url"
             if [ -n "$NO_CACHE" ]; then
-                eval    x curl -D "$gl_header"  -X GET -s -H "$_content_type" -H "$_authorization" $(eval "printf '%s ' $(x curl gencode $(___x_cmd_gl_curl___use_query_data "$@"))") "$_curl_url"
+                ___x_cmd_api_gl get "$_api_url" $(eval "printf '%s ' $(x curl gencode $(___x_cmd_gl_curl___use_query_data "$@"))")
             else
-                x ccmd 10s --      eval x curl -D "$gl_header"  -X GET -s -H "$_content_type" -H "$_authorization" $(eval "printf '%s ' $(x curl gencode $(___x_cmd_gl_curl___use_query_data "$@"))") "$_curl_url"
+                x ccmd 10s --        eval "___X_CMD_API_GL_HOST=$___X_CMD_API_GL_HOST ___X_CMD_API_GL_TOKEN=$___X_CMD_API_GL_TOKEN ___x_cmd_api_gl get \"$_api_url\" $(eval "printf '%s ' $(x curl gencode $(___x_cmd_gl_curl___use_query_data "$@"))")"
             fi
-            ___x_cmd_gl_http_error eval x curl -D "$gl_header"  -X GET -s -H "$_content_type" -H "$_authorization" $(eval "printf '%s ' $(x curl gencode $(___x_cmd_gl_curl___use_query_data "$@"))") "$_curl_url"
-            return
+            ___x_cmd_gl_http_error   eval "___X_CMD_API_GL_HOST=$___X_CMD_API_GL_HOST ___X_CMD_API_GL_TOKEN=$___X_CMD_API_GL_TOKEN ___x_cmd_api_gl get \"$_api_url\" $(eval "printf '%s ' $(x curl gencode $(___x_cmd_gl_curl___use_query_data "$@"))")"
+            ;;
+        post|put|patch|del)
+            ___x_cmd_api_gl "$op" "$_api_url" "$(x curl gencode "$@")"
+            ___x_cmd_gl_http_error
             ;;
         upload)
-            local __file_path="${1?:"Please provide upload filepath"}"; shift;
+            [ -n "$1" ] || M='Please provide upload filepath' arg:ret:64
+            local __file_path="$1";  shift;
             [ -f "$__file_path" ] || {
                 gl:error "Upload Failure: Not found target file. Please check file exist: $__file_path"
                 return 1
             }
-            gl:debug "x curl -L -D  $gl_header   -X  ${___X_CMD_GL_UPLOAD_REQ_METHOD:-"POST"}  -H  $_authorization  --form  file=@${__file_path}    $(x curl gencode "$@")   $_curl_url"
-            eval      x curl -L -D "$gl_header"  -X "${___X_CMD_GL_UPLOAD_REQ_METHOD:-"POST"}" -H "$_authorization" --form  file=@"${__file_path}" "$(x curl gencode "$@")" "$_curl_url"
-            ___x_cmd_gl_http_error; return
+            ___X_CMD_API_GL_HEADER="-L -# -D \"$___X_CMD_GL_TMP/.____x_cmd_gl_curl_header\""
+            ___x_cmd_api_gl "${___X_CMD_GL_UPLOAD_REQ_METHOD:-"post"}" "$_api_url" --form file=@\""${__file_path}"\" "$(x curl gencode "$@")"
+            ___x_cmd_gl_http_error
         ;;
-        post)           req="POST"      ;;
-        put)            req="PUT"       ;;
-        patch)          req="PATCH"     ;;
-        delete)         req="DELETE"    ;;
     esac
-    gl:debug "x curl -D  $gl_header  -X  $req  -s -H  $_content_type  -H  $_authorization   $(x curl gencode "$@")   $_curl_url"
-    eval      x curl -D "$gl_header" -X "$req" -s -H "$_content_type" -H "$_authorization" "$(x curl gencode "$@")" "$_curl_url"
-    ___x_cmd_gl_http_error
-}
-
-___x_cmd_gl_http_error(){
-    local http_resp_code
-    http_resp_code=$(___x_cmd_gl_resp_code)
-    if [ -n "$http_resp_code" ] && [ "$http_resp_code" -ge 200 ] && [ "$http_resp_code" -le 303 ]; then
-        return 0
-    else
-        [ $# -eq 0 ] || {
-            gl:debug "---! Cache Clear !---"
-            x ccmd invalidate "$@" 1>/dev/null 2>&1
-        }
-        [ -z "$___X_CMD_GL_SHOW_HTTP_CODE" ] || {
-            gl:error "HTTP Code is $http_resp_code"
-            if command -v unset 1>/dev/null; then
-                unset ___X_CMD_GL_SHOW_HTTP_CODE
-            fi
-        }
-        return 1
-    fi
 }
 
 # shellcheck disable=SC2154
@@ -99,9 +77,36 @@ ___x_cmd_gl_curl___use_query_data(){
     done
 }
 
+___x_cmd_gl_http_error(){
+    local http_resp_code
+    http_resp_code=$(___x_cmd_gl_resp_code)
+    if [ -n "$http_resp_code" ] && [ "$http_resp_code" -ge 200 ] && [ "$http_resp_code" -le 303 ]; then
+        return 0
+    else
+        [ $# -eq 0 ] || {
+            gl:debug "Cache Clear"
+            x ccmd invalidate "$@" 1>/dev/null 2>&1
+        }
+        [ -z "$___X_CMD_GL_SHOW_HTTP_CODE" ] || {
+            gl:error "HTTP Code is $http_resp_code"
+            if command -v unset 1>/dev/null; then
+                unset ___X_CMD_GL_SHOW_HTTP_CODE
+            fi
+        }
+        return 1
+    fi
+}
+
+___x_cmd_gl____printf_error(){
+    if ! ___x_cmd_is_interative_tty || [ ! -t 2 ] || [ -n "$NO_COLOR" ]; then
+        printf "  - ErrorMsg: %s\n" "$1" >&2
+    else
+        printf "  \033[31m-\033[0m \033[1mErrorMsg: \033[31m%s\033[0m\n" "$1" >&2
+    fi
+}
 ___x_cmd_gl____handle_resp(){
-    [ -z "$gl_resp_body" ] || printf "%s" "$gl_resp_body"
-    [ -z "$gl_resp_err" ]  || printf "  \033[31m-\033[0m \033[1mErrorMsg: \033[31m%s\033[0m\n" "$gl_resp_err" >&2
+    [ -z "$gl_resp_err" ] || ___x_cmd_gl____printf_error "$gl_resp_err"
+    [ -z "$gl_resp_msg" ] || ___x_cmd_gl____printf_error "$gl_resp_msg"
 }
 # EndSection
 
@@ -114,6 +119,7 @@ ___x_cmd_gl_get_multi() {
 
     local page=1
     local per_page=100
+    local NO_CACHE=1
     if [ -n "$json" ] || [ -n "$ENFORCE_JSON" ]; then
         ___x_cmd_gl_get_multi___json_prt "$@"
     else
@@ -145,8 +151,8 @@ ___x_cmd_gl_get_multi___json_prt(){
     local next_url
     _____x_cmd_gl_next_url
     if [ -z "$next_url" ]; then
-        cat "$tmp"
-        rm "$tmp"
+        command cat "$tmp"
+        x rmrf "$tmp"
         return
     fi
 
@@ -155,16 +161,8 @@ ___x_cmd_gl_get_multi___json_prt(){
         printf "\n" >> "$tmp"
         _____x_cmd_gl_next_url
     done
-    < "$tmp" x jo q0 \*.\* . | awk 'BEGIN{ print "["}
-        END{ print "]"}
-        {
-            if ($0 == "") next
-            if ((NR != 1) && ( aaa == 0 )) print ","
-            if (($0 == "{") || ( $0 == "[")) aaa++
-            if (($0 == "}") || ( $0 == "]")) aaa--
-            print $0
-        }'
-    rm "$tmp"
+    < "$tmp" x jo q0 \*.\* . | ___x_cmd_gx_merge_multi_page_json_array
+    x rmrf "$tmp"
 }
 
 _____x_cmd_gl_next_url(){
@@ -172,7 +170,11 @@ _____x_cmd_gl_next_url(){
     next_url="${next_url#*'rel="prev", <'}"
     local tmp_url="${next_url%%'>; rel="next"'*}"
     if [ "$next_url" != "$tmp_url" ];then
-         next_url="${tmp_url#*'api/v4'*}"
+        local _split_host=""
+        if ! _split_host="$(___x_cmd_gl_config_get host 2>/dev/null)"; then
+            _split_host="https://gitlab.com/api/v4"
+        fi
+        next_url="${tmp_url#*"$_split_host"}"
     else
         next_url=""
     fi
@@ -180,62 +182,63 @@ _____x_cmd_gl_next_url(){
 # EndSection
 
 # Section: Parameter Utilities
-alias ___x_cmd_gl_param_init_owner_project='
-    local owner_project=""
+alias ___x_cmd_gl_param_init_owner_repo='
+    local owner_repo=""
     ___x_cmd_gl_param_normalize_repo  || return
 '
 
 # shellcheck disable=SC2154,SC2034
 ___x_cmd_gl_param_normalize_repo(){
-    local op="$project"
-
+    local op="$repo"
     [ -n "$op" ] || op="$1"
     case "$op" in
-    */*)
-        owner_project="$(printf "%s" "$op")"
-        ;;
-    "")
-        owner_project="$(_____x_cmd_git_repo)"
-        ;;
-    *)
-        owner_project="$(printf "%s" "${op}"  | awk '$0~"^[0-9]+$"{ print $0; }')"
-        [ -z "$owner_project" ] || return
-        ___x_cmd_gl_current_owner 1>/dev/null
-        if [ -z "$___X_CMD_GL_DEFAULT_OWNER" ]; then
-            gl:error "No owner provided. Default owner not set."
-            gl:warn "Check your current token setting.$(_____x_cmd_gl_help__token_setting)"
+        .id=*/*)
+            gl:error "No support .id=<owner_id>/<repo_name>. Please use .id=<repo_id>"
             return 1
-        fi
-        owner_project="$(printf "%s" "$___X_CMD_GL_DEFAULT_OWNER/$op")"
-        ;;
+            ;;
+        .id=*)
+            owner_repo="${op#*'.id='}"
+            return 0
+            ;;
+        */*)
+            owner_repo="$op"
+            ;;
+        "")
+            case "$___X_CMD_GL_CURRENT_repo" in
+                */*) owner_repo="$___X_CMD_GL_CURRENT_repo"     ;;
+                "")  owner_repo="$(___x_cmd_gx_get_owner_repo)" ;;
+                *)
+                    if [ -n "$___X_CMD_GL_CURRENT_owner" ]; then
+                        owner_repo="${___X_CMD_GL_CURRENT_owner}/${___X_CMD_GL_CURRENT_repo}"
+                    else
+                        owner_repo="$(___x_cmd_gl_config_get owner)/${___X_CMD_GL_CURRENT_repo}" || {
+                            gl:error "No owner provided. Default owner not set."
+                            gl:warn -h "$(x str ml wrap "$(_____x_cmd_gl_help__token_setting)" '    ')" -m "Can retry setup token to update owner.${___X_CMD_UNSEENCHAR_NEWLINE}Or check your current token setting."
+                            return 1
+                        }
+                    fi
+                ;;
+            esac
+            ;;
+        *)
+            if [ -z "$___X_CMD_GL_CURRENT_owner" ]; then
+                local ___X_CMD_GL_CURRENT_owner=""
+                if ! ___X_CMD_GL_CURRENT_owner="$(___x_cmd_gl_config_get owner)"; then
+                    gl:error "No owner provided. Default owner not set."
+                    gl:warn -h "$(x str ml wrap "$(_____x_cmd_gl_help__token_setting)" '    ')" -m "Can retry setup token to update owner.${___X_CMD_UNSEENCHAR_NEWLINE}Or check your current token setting."
+                    return 1
+                fi
+            fi
+            owner_repo="${___X_CMD_GL_CURRENT_owner}/${op}"
+            ;;
     esac
-    owner_project="$(printf "%s" "$owner_project" | sed s:'/':'%2F':g)"
+    owner_repo="$(printf "%s" "$owner_repo" | ___x_cmd_gl___url_path_encode)"
 }
 
-_____x_cmd_git_repo(){
-    local repo
-    repo="$(git config --get remote.origin.url 2>/dev/null)"
-    repo="${repo##*".com:"}"
-    repo="${repo##*".com/"}"
-    repo="${repo%.*}"
-    printf "%s" "$repo"
-}
-
-___gl_ui_mutual() {
-    local tmp="$1"
-    shift 1
-    if [ -n "$json" ] || [ -n "$ENFORCE_JSON" ] ; then
-        ENFORCE_JSON=1 "$@"
-    else
-        # run ui table
-        eval "$tmp"
-    fi
-    return
-}
 # EndSection
 
-# Section: gl member access
-_____x_cmd_gl_member_util(){
+# Section: gl utils
+___x_cmd_gl____transform_member_access(){
     case $access_level in
         owner)
             access_level=50;;
@@ -248,5 +251,29 @@ _____x_cmd_gl_member_util(){
         guest)
             access_level=10;;
     esac
+}
+
+# shellcheck disable=2016
+___x_cmd_gl___url_encode(){
+    [ -n "$1" ] || M='accepts 1 arg(target str), received empty' arg:ret:64
+    printf "%s\n" "$1" |  x cawk  \
+        -f "$___X_CMD_ROOT_MOD/awk/lib/ord.awk" \
+        -f "$___X_CMD_ROOT_MOD/awk/lib/url.awk" \
+        -f "$___X_CMD_ROOT_MOD/awk/lib/sh.awk"  \
+        '{ print urlencode( $0 ) }'
+}
+
+___x_cmd_gl___url_path_encode(){
+    sed s:'/':'%2F':g
+}
+
+# NOTE: remove prefix: _host_tmp="${_host_tmp#*'://'}";
+___x_cmd_gl___get_web_host(){
+    local _host_tmp=""
+    if _host_tmp="$(___x_cmd_gl_config_get host 2>/dev/null)"; then
+        printf "%s" "${_host_tmp%'/api/'*}"
+    else
+        printf "%s" "https://gitlab.com"
+    fi
 }
 # EndSection
diff --git a/mod/tea/lib/utils b/mod/tea/lib/utils
--- a/mod/tea/lib/utils
+++ b/mod/tea/lib/utils
@@ -7,7 +7,7 @@ _____x_cmd_tea_help__token_setting(){
     printf "\n%s %s \n%s\n" \
         "$(___x_cmd_ui yellow 'Run command to add|repleace token:')" \
         "$(___x_cmd_ui bold cyan "\`x tea token <token>\`")"   \
-        "$(___x_cmd_ui "${___X_CMD_TEA_DOMAIN:-"https://gitea.com"}/user/settings/applications")"
+        "$(___x_cmd_ui "$(___x_cmd_tea___get_web_host)/user/settings/applications")"
 }
 
 _____x_cmd_tea_help(){
@@ -21,41 +21,35 @@ ___x_cmd_tea_resp_header() {
 }
 
 ___x_cmd_tea_resp_code(){
-    ___x_cmd_tea_resp_header  | awk '$1 ~/HTTP\/2$/ {print ($2+0);exit(0)}'
+    ___x_cmd_tea_resp_header | _____x_cmd_gx_get_resp_code_by_header
 }
 
-# https://gitea.com/api/v1/user
-# https://codeberg.org/api/v1/user
 ___x_cmd_tea_curl(){
     local op="$1"
-    local _curl_url="\"${___X_CMD_TEA_DOMAIN:-"https://gitea.com"}/api/v1$2\""
-    local _accept="\"Accept:application/json\""
-    local _content="\"Content-Type:application/json\""
-    local _authorization
-    _authorization="\"Authorization:token $(___x_cmd_tea_token)\""
-    local tea_header="$___X_CMD_TEA_TMP/.____x_cmd_tea_curl_header"
-    local ___X_CMD_TEA_SHOW_HTTP_CODE=1
+    local _api_url="$2"
     shift 2
-    local req
+    local ___X_CMD_API_TEA_HEADER="-s -H \"accept: application/json\" -H \"Content-Type: application/json\" -D \"$___X_CMD_TEA_TMP/.____x_cmd_tea_curl_header\""
+
+    local _curl_host_tmp=""
+    local ___X_CMD_API_TEA_TOKEN=""
+    ___x_cmd_tea_config___var  ___X_CMD_API_TEA_TOKEN=token _curl_host_tmp=host 2>/dev/null
+    local ___X_CMD_API_TEA_HOST="${___X_CMD_API_GODE_HOST:-"$_curl_host_tmp"}"
+
+    local ___X_CMD_TEA_SHOW_HTTP_CODE=1
     case "$op" in
         get)
-            tea:debug "x curl -D  $tea_header   -X GET -s -H  $_accept  -H $_content   -H  $_authorization  $(eval "printf '%s ' $(x curl gencode $(___x_cmd_tea_curl___use_query_data "$@"))")  $_curl_url"
             if [ -n "$NO_CACHE" ]; then
-                eval   x curl -D "$tea_header"  -X GET -s -H "$_accept" -H "$_content" -H "$_authorization" $(eval "printf '%s ' $(x curl gencode $(___x_cmd_tea_curl___use_query_data "$@"))") "$_curl_url"
+                ___x_cmd_api_tea get "$_api_url" $(eval "printf '%s ' $(x curl gencode $(___x_cmd_tea_curl___use_query_data "$@"))")
             else
-                x ccmd 10s --        eval x curl -D "$tea_header"  -X GET -s -H "$_accept" -H "$_content" -H "$_authorization" $(eval "printf '%s ' $(x curl gencode $(___x_cmd_tea_curl___use_query_data "$@"))") "$_curl_url"
+                x ccmd 10s --        eval "___X_CMD_API_TEA_HOST=$___X_CMD_API_TEA_HOST ___X_CMD_API_TEA_TOKEN=$___X_CMD_API_TEA_TOKEN ___x_cmd_api_tea get \"$_api_url\" $(eval "printf '%s ' $(x curl gencode $(___x_cmd_tea_curl___use_query_data "$@"))")"
             fi
-            ___x_cmd_tea_http_error  eval x curl -D "$tea_header"  -X GET -s -H "$_accept" -H "$_content" -H "$_authorization" $(eval "printf '%s ' $(x curl gencode $(___x_cmd_tea_curl___use_query_data "$@"))") "$_curl_url"
-            return
+            ___x_cmd_tea_http_error   eval "___X_CMD_API_TEA_HOST=$___X_CMD_API_TEA_HOST ___X_CMD_API_TEA_TOKEN=$___X_CMD_API_TEA_TOKEN ___x_cmd_api_tea get \"$_api_url\" $(eval "printf '%s ' $(x curl gencode $(___x_cmd_tea_curl___use_query_data "$@"))")"
             ;;
-        post)           req="POST"      ;;
-        put)            req="PUT"       ;;
-        patch)          req="PATCH"     ;;
-        delete)         req="DELETE"    ;;
+        post|put|patch|del)
+            ___x_cmd_api_tea "$op" "$_api_url" "$(x curl gencode "$@")"
+            ___x_cmd_tea_http_error
+            ;;
     esac
-    tea:debug "x curl -D  $tea_header  -X  $req  -s -H  $_accept  -H  $_content  -H  $_authorization   $(x curl gencode "$@")   $_curl_url"
-    eval       x curl -D "$tea_header" -X "$req" -s -H "$_accept" -H "$_content" -H "$_authorization" "$(x curl gencode "$@")" "$_curl_url"
-    ___x_cmd_tea_http_error
 }
 
 ___x_cmd_tea_curl___use_query_data(){
@@ -77,7 +71,7 @@ ___x_cmd_tea_http_error(){
         return 0
     else
         [ $# -eq 0 ] || {
-            tea:debug "---! Cache Clear !---"
+            tea:debug "Cache Clear"
             x ccmd invalidate "$@" 1>/dev/null 2>&1
         }
         [ -z "$___X_CMD_TEA_SHOW_HTTP_CODE" ] || {
@@ -90,22 +84,17 @@ ___x_cmd_tea_http_error(){
     fi
 }
 
-___x_cmd_tea____handle_resp(){
-    [ -z "$tea_resp_body" ] || printf "%s" "$tea_resp_body"
-    [ -z "$tea_resp_err" ]  || printf "  \033[31m-\033[0m \033[1mErrorMsg: \033[31m%s\033[0m\n" "$tea_resp_err" >&2
+___x_cmd_tea____printf_error(){
+    if ! ___x_cmd_is_interative_tty || [ ! -t 2 ] || [ -n "$NO_COLOR" ]; then
+        printf "  - ErrorMsg: %s\n" "$1" >&2
+    else
+        printf "  \033[31m-\033[0m \033[1mErrorMsg: \033[31m'%s'\033[0m\n" "$1" >&2
+    fi
 }
 
-___x_cmd_tea____handle_no_content(){
-    local tea_resp_body
-    local tea_resp_err
-    x jo env . tea_resp_body=. tea_resp_err=.message
-
-    [ -z "$gh_resp_body" ] || {
-        tea:debug "tea_resp_body: $tea_resp_body"
-        ___x_cmd_tea____handle_resp
-        return 1
-    }
-    ___x_cmd_gh_http_error
+___x_cmd_tea____handle_resp(){
+    [ -z "$tea_resp_err" ] || [ "$tea_resp_err" = "null" ] || ___x_cmd_tea____printf_error "$tea_resp_err"
+    [ -z "$tea_resp_msg" ] || [ "$tea_resp_msg" = "null" ] || ___x_cmd_tea____printf_error "$tea_resp_msg"
 }
 # EndSection
 
@@ -118,6 +107,7 @@ ___x_cmd_tea_get_multi() {
 
     local page=1
     local limit=100
+    local NO_CACHE=1
     if [ -n "$json" ] || [ -n "$ENFORCE_JSON" ]; then
         ___x_cmd_tea_get_multi___json_prt "$@"
     else
@@ -133,7 +123,7 @@ ___x_cmd_tea_get_multi___ui_table(){
     [ -n "$next_url" ] || return
 
     while [ -n "$next_url" ]; do
-        ___x_cmd_tea_curl get "$next_url"
+        ___x_cmd_tea_curl get "$next_url" || return
         printf "\n"
         _____x_cmd_tea_next_url
     done
@@ -148,8 +138,8 @@ ___x_cmd_tea_get_multi___json_prt(){
     local next_url
     _____x_cmd_tea_next_url
     if [ -z "$next_url" ]; then
-        cat "$tmp"
-        rm "$tmp"
+        command cat "$tmp"
+        x rmrf "$tmp"
         return
     fi
 
@@ -158,16 +148,8 @@ ___x_cmd_tea_get_multi___json_prt(){
         printf "\n" >> "$tmp"
         _____x_cmd_tea_next_url
     done
-    < "$tmp" x jo q0 \*.\* . | awk 'BEGIN{ print "["}
-        END{ print "]"}
-        {
-            if ($0 == "") next
-            if ((NR != 1) && ( aaa == 0 )) print ","
-            if (($0 == "{") || ( $0 == "[")) aaa++
-            if (($0 == "}") || ( $0 == "]")) aaa--
-            print $0
-        }'
-    rm "$tmp"
+    < "$tmp" x jo q0 \*.\* . | ___x_cmd_gx_merge_multi_page_json_array
+    x rmrf "$tmp"
 }
 
 _____x_cmd_tea_next_url() {
@@ -175,7 +157,11 @@ _____x_cmd_tea_next_url() {
     next_url="${next_url#*'rel="prev", <'}"
     local tmp_url="${next_url%%'>; rel="next"'*}"
     if [ "$next_url" != "$tmp_url" ]; then
-        next_url="${tmp_url#*'.com'*}"
+        local _split_host=""
+        if ! _split_host="$(___x_cmd_tea_config_get host 2>/dev/null)"; then
+            _split_host="https://gitea.com/api/v1"
+        fi
+        next_url="${tmp_url#*"$_split_host"}"
     else
         next_url=""
     fi
@@ -183,75 +169,60 @@ _____x_cmd_tea_next_url() {
 
 # EndSection
 
-# Section 3: Parameter Utilities
+# Section: Parameter Utilities
 alias ___x_cmd_tea_param_init_owner_repo='
-    local owner_repo
+    local owner_repo=""
     ___x_cmd_tea_param_normalize_repo  || return
 '
 
-# shellcheck disable=SC2034
+# shellcheck disable=SC2154,SC2034
 ___x_cmd_tea_param_normalize_repo() {
     local op="$repo"
-    [ -z "$op" ] && op="$1"
+    [ -n "$op" ] || op="$1"
     case "$op" in
     */*)
-        owner_repo="$(printf "%s" "$op")"
+        owner_repo="$op"
         ;;
     "")
-        owner_repo="$(_____x_cmd_git_repo)"
+        case "$___X_CMD_TEA_CURRENT_repo" in
+            */*) owner_repo="$___X_CMD_TEA_CURRENT_repo"    ;;
+            "")  owner_repo="$(___x_cmd_gx_get_owner_repo)" ;;
+            *)
+                if [ -n "$___X_CMD_TEA_CURRENT_owner" ]; then
+                    owner_repo="${___X_CMD_TEA_CURRENT_owner}/${___X_CMD_TEA_CURRENT_repo}"
+                else
+                    owner_repo="$(___x_cmd_tea_config_get owner)/${___X_CMD_TEA_CURRENT_repo}" || {
+                        tea:error "No owner provided. Default owner not set."
+                        tea:warn -h "$(x str ml wrap "$(_____x_cmd_tea_help__token_setting)" '    ')" -m "Can retry setup token to update owner.${___X_CMD_UNSEENCHAR_NEWLINE}Or check your current token setting."
+                        return 1
+                    }
+                fi
+            ;;
+        esac
         ;;
     *)
-        ___x_cmd_tea_current_owner 1>/dev/null 2>&1
-        if [ -z "$___X_CMD_TEA_DEFAULT_OWNER" ]; then
-            tea:error "No owner provided. Default owner not set."
-            tea:warn "Check your current token setting.$(_____x_cmd_tea_help__token_setting)"
-            return 1
+        if [ -z "$___X_CMD_TEA_CURRENT_owner" ]; then
+            local ___X_CMD_TEA_CURRENT_owner=""
+            if ! ___X_CMD_TEA_CURRENT_owner="$(___x_cmd_tea_config_get owner)"; then
+                tea:error "No owner provided. Default owner not set."
+                tea:warn -h "$(x str ml wrap "$(_____x_cmd_tea_help__token_setting)" '    ')" -m "Can retry setup token to update owner.${___X_CMD_UNSEENCHAR_NEWLINE}Or check your current token setting."
+                return 1
+            fi
         fi
-        owner_repo="$(printf "%s" "$___X_CMD_TEA_DEFAULT_OWNER/$op")"
+        owner_repo="${___X_CMD_TEA_CURRENT_owner}/${op}"
         ;;
     esac
 }
+# EndSection
 
-___x_cmd_tea_default() {
-    param_default "$@" 2>/dev/null || return 1
-}
-
-_____x_cmd_git_repo() {
-    local repo
-    repo="$(git config --get remote.origin.url 2>/dev/null)"
-    repo="${repo##*".com:"}"
-    repo="${repo##*".com/"}"
-    repo="${repo%.*}"
-    printf "%s" "$repo"
-}
-_____x_cmd_git_branch() {
-    git symbolic-ref -q --short HEAD 2>/dev/null
-}
-
-___tea_ui_mutual() {
-    local tmp="$1"
-    shift 1
-    if [ -n "$json" ] || [ -n "$ENFORCE_JSON" ] ; then
-        ENFORCE_JSON=1 "$@"
+# Section: tea util
+# NOTE: remove prefix: _host_tmp="${_host_tmp#*'://'}";
+___x_cmd_tea___get_web_host(){
+    local _host_tmp=""
+    if _host_tmp="$(___x_cmd_tea_config_get host 2>/dev/null)"; then
+        printf "%s" "${_host_tmp%'/api/'*}"
     else
-        # run ui table
-        eval "$tmp"
+        printf "%s" "https://gitea.com"
     fi
-    local ___tea_exit_code="$?"
-    [ "$___tea_exit_code" -eq 0 ] || {
-        ___x_cmd_ui_tf false "${___tea_error_msg:-"Couldn't find any data"}" ;
-        return "$___tea_exit_code"
-    }
-}
-
-_____x_cmd_tea_advise() {
-    _____x_cmd_tea_advise_parse "$@" | x jo .\* .login | x ja '{printf("%s ", $0)}'
-}
-
-_____x_cmd_tea_advise_parse() {
-    local op="$1"
-    case "$op" in
-        orgls) x ccmd 1d -- x tea org ls 2>/dev/null;;
-    esac
 }
 # EndSection
