Updating main branch using x7 release -> 51fa410a0130006da548a2828ee0ccfb79abb3fe

diff --git a/mod/advise/lib/main b/mod/advise/lib/main
--- a/mod/advise/lib/main
+++ b/mod/advise/lib/main
@@ -28,9 +28,13 @@ ___x_cmd_advise___main(){
             xrc:mod:lib advise util.normal
             "___x_cmd_advise_${op}" "$@"
             ;;
+        addon)
+            xrc:mod:lib advise addon/_index
+            ___x_cmd_advise_addon "$@"
+            ;;
         man)
-                ___x_cmd_advise_"$op" "$@" ;;
-        *)      ___x_cmd_advise___entrance "$op" "$@"
+            ___x_cmd_advise_"$op" "$@" ;;
+        *)  ___x_cmd_advise___entrance "$op" "$@" ;;
     esac
 }
 
@@ -56,7 +60,7 @@ else
             complete)   xrc:mod:lib advise complete/_index
                         ___x_cmd_advise_complete    "$@"    ;;
             autoload)   ___x_cmd_advise_autoload    "$@"    ;;
-            *)          ___x_cmd_advise_init "$op"  "$@"    ;;    # TODO: open app.
+            *)          N=advise M="No such subcmd ==> $op" log:ret:64 ;;
         esac
     }
 
@@ -84,38 +88,50 @@ else
     }
 
     ___x_cmd_advise___rcload(){
-        if [ -z "$___X_CMD_ADVISE_LOADED" ] && ___x_cmd_is_suitable_advise_repl; then
+        if [ -z "${___X_CMD_ADVISE_LOADED}${___X_CMD_ADVISE_PREPARE_FAILED}" ] && ___x_cmd_is_suitable_advise_repl; then
             ___X_CMD_ADVISE_LOADED=1
 
-            ! ___x_cmd_advise_autoload___eq_never || return 0
-            ___x_cmd_advise___prepare || {
-                ___X_CMD_ADVISE_PREPARE_FAILED=1
-                return 1
-            }
+            if ! ___x_cmd_advise_autoload___eq_never; then
+                ___x_cmd_advise___prepare || {
+                    ___X_CMD_ADVISE_PREPARE_FAILED=1
+                    return 1
+                }
 
-            local x_=; ___x_cmd_advise_autoload_get_ || return 0
-            case "$x_" in
-                auto)
-                    if ___x_cmd_advise_autoload___ifothercompletionloaded; then
-                        ___x_cmd_advise_man_load x
-                    else
-                        if ___x_cmd_is_suitable_advise_completion_env && ___x_cmd_advise_man___folder_exist_completion; then
-                            ___x_cmd_advise_man_load completion
+                local x_=; ___x_cmd_advise_autoload_get_ || return 0
+                case "$x_" in
+                    auto)
+                        if ___x_cmd_advise_autoload___ifothercompletionloaded; then
+                            ___x_cmd_advise_man_load x
+                        else
+                            if ___x_cmd_is_suitable_advise_completion_env && ___x_cmd_advise_man___folder_exist_completion; then
+                                ___x_cmd_advise_man_load completion
+                            fi
+                            ___x_cmd_advise_man_load x-cmd
+                            ___x_cmd_advise_man_load x
                         fi
-                        ___x_cmd_advise_man_load x-cmd
+                        ;;
+                    all)
+                        ___x_cmd_advise_man_load all
+                        ;;
+                    x)
                         ___x_cmd_advise_man_load x
-                    fi
-                    ;;
-                all)
-                    ___x_cmd_advise_man_load all
-                    ;;
-                x)
-                    ___x_cmd_advise_man_load x
-                    ;;
-                *)
-                    advise:debug "Never load x-cmd advise"
-                    return 0 ;;
-            esac
+                        ;;
+                    *)
+                        advise:debug "Never load x-cmd advise"
+                esac
+            fi
+
+            if [ "$___X_CMD_SHELL" = bash ] || [ "$___X_CMD_SHELL" = zsh ]; then
+                local addon_codefp="$___X_CMD_ADVISE_ADDON_CHCHE/complete.$___X_CMD_SHELL"
+                if [ -f "$addon_codefp" ]; then
+                    advise:debug "Load addon completion from $addon_codefp"
+                    . "$addon_codefp" || {
+                        advise:error "Failed to load addon completion from $addon_codefp"
+                        return 1
+                    }
+                fi
+            fi
+
         fi
     }
 
diff --git a/mod/advise/lib/util b/mod/advise/lib/util
--- a/mod/advise/lib/util
+++ b/mod/advise/lib/util
@@ -32,7 +32,12 @@ ___x_cmd_advise_init(){
             ___x_cmd_cmds_cp "$op" "$filepath"
         }
     else
-        local x_=; ___x_cmd_advise___main __get_mod_advise_jso_ "$name" || N=advise M="advise init not found advise jso file of '$name'. [filepath=${op:-"$x_"}]" log:ret:64
+        local x_=; ___x_cmd_advise___main __get_mod_advise_jso_ "$name" || {
+            advise:debug "Not found [filepath=${op:-"$x_"}]"
+            advise:error "advise init not found advise jso file of '$name'"
+            return 64
+        }
+
         { [ -f "$filepath" ] && [ "$filepath" -nt "$x_" ] ; } || {
             advise:debug "Copy $x_ to $filepath"
             ___x_cmd_cmds_cp "$x_" "$filepath"
