Updating main branch using x7 release -> 308fee6188f44b684a3f2be241e17b1df47e26cf

diff --git a/mod/advise/lib/man b/mod/advise/lib/man
--- a/mod/advise/lib/man
+++ b/mod/advise/lib/man
@@ -13,16 +13,6 @@ ___x_cmd_advise_man(){
     esac
 }
 
-___x_cmd_is_suitable_advise_completion_env(){
-    ___x_cmd_is_suitable_advise_env || return 1
-    # bash >= 4.2
-    [ -z "$___X_CMD_ADVISE_SHELL_BASH_LT_4_2" ] || return 1
-}
-
-if [ -n "$BASH_VERSION" ] && ___x_cmd_is_suitable_advise_completion_env ; then  ___X_CMD_ADVISE_MAN_COMPLETIONS_FOLDER_SRC="$___X_CMD_ADVISE_MAN_COMPLETIONS_FOLDER/completions"
-elif [ -n "$ZSH_VERSION" ]; then ___X_CMD_ADVISE_MAN_COMPLETIONS_FOLDER_SRC="$___X_CMD_ADVISE_MAN_COMPLETIONS_FOLDER/src"
-fi
-
 ___x_cmd_advise_man___folder_exist_xcmd(){
     [ -d "$___X_CMD_ADVISE_MAN_XCMD_FOLDER" ]
 }
@@ -31,13 +21,12 @@ ___x_cmd_advise_man___folder_exist_completion(){
 }
 
 # Section: advise man install
-xrc websrc; ___x_cmd_websrc load
 ___x_cmd_advise_man___pkg_download_inner_url_(){
     local owner_repo="$1"
     local version="$2"
     local tar_name="$3"
     # [ -n "$___X_CMD_ADVISE_DEV_MOD" ] ||
-    if [ "$___X_CMD_WEBSRC_REGION" != cn ]; then
+    if ! ___x_cmd websrc is cn; then
         x_url="https://github.com/${owner_repo}/releases/download/${version}/${tar_name}"
     else
         x_url="https://oss.resource.x-cmd.com/releases/${owner_repo#*/}/${version}/${tar_name}"
@@ -118,7 +107,7 @@ ___x_cmd_advise_man___pkg_unzip_xcmd_unit(){
     ___X_CMD_ZUZ_QUIET=1 ___x_cmd uz "$___X_CMD_ADVISE_MAN_XCMD_PKG" "$___X_CMD_ADVISE_MAN_XCMD_FOLDER" || return $?
     advise:debug "Decompress advise/all.tar.xz to $___X_CMD_ADVISE_MAN_XCMD_FOLDER"
     ___x_cmd touch "$___X_CMD_ADVISE_MAN_XCMD_FOLDER/timefile"
-    ___x_cmd_advise___main --rm-bootcode
+    ___x_cmd_advise___main __rm_bootcode
 }
 
 # EndSection
@@ -129,10 +118,10 @@ ___x_cmd_advise_man_update(){
     case "$1" in
         x-cmd)          ___x_cmd_advise_man___pkg_unzip_xcmd --update       ;;
         completion)     ___x_cmd_advise_man___pkg_unzip_completion --update ;;
-        x.advise.jso)   ___x_cmd_advise_man_gen_x_advise_force              ;;
+        x.advise.jso)   ___x_cmd_advise___main gen_x_advise --force         ;;
         all)            ___x_cmd_advise_man___pkg_unzip_xcmd --update
                         ___x_cmd_advise_man___pkg_unzip_completion --update
-                        ___x_cmd_advise_man_gen_x_advise_force
+                        ___x_cmd_advise___main gen_x_advise --force
                         ;;
         *)              ___x_cmd_advise_man___pkg_check_update_completion
                         ___x_cmd_advise_man___pkg_check_update_xcmd
@@ -210,7 +199,10 @@ ___x_cmd_advise_man_which___completion(){
 ___x_cmd_advise_man_which(){
     local X_help_cmd='___x_cmd help -m advise man which'
     help:arg:parse
-    case "$1" in
+    local op="$1"
+    case "$op" in
+        xcmd_|completion_|completion_getfile_)
+                        shift; ___x_cmd_advise_man_which___"$op" "$@" ;;
         x-cmd)          shift; ___x_cmd_advise_man_which___xcmd "$@" ;;
         completion)     ___x_cmd_is_suitable_advise_completion_env || {
                             help:show:ret:64
@@ -254,7 +246,19 @@ ___x_cmd_advise_man_load___xcmd(){
 
 ___x_cmd_advise_man_load___completion(){
     ___x_cmd_is_suitable_advise_completion_env || return $?
-    ___x_cmd_advise_man___folder_exist_completion || ___x_cmd_advise_man___pkg_unzip_completion || return $?
+    ___x_cmd_advise_man___folder_exist_completion || {
+        [ -n "$___X_CMD_ADVISE_MAN_FORCED_LOAD" ] || {
+            if ! ___x_cmd_runmode_allow_chatty; then
+                advise:error "Not found completion folder"
+                return 1
+            else
+                ___x_cmd ui yesno "Not found completion folder, do you want to download it?" || return $?
+            fi
+        }
+
+        ___x_cmd_advise_man___pkg_unzip_completion || return $?
+    }
+
     if [ "$#" -ge 1 ]; then ___x_cmd_advise_man_load___completion_one "$@"
     else ___x_cmd_advise_man_load___completion_all
     fi
@@ -277,7 +281,7 @@ ___x_cmd_advise_man_load___completion_all(){
 
 ___x_cmd_advise_man_load___x(){
     advise:debug "Load x advise of $___X_CMD_ADVISE_MAN_CACHE_X_ADVISE_JSO"
-    ___x_cmd_advise_man_gen_x_advise
+    ___x_cmd_advise___main gen_x_advise
     ___x_cmd_advise_init x "$___X_CMD_ADVISE_MAN_CACHE_X_ADVISE_JSO"
     ___x_cmd_advise_init ___x_cmd "$___X_CMD_ADVISE_MAN_CACHE_X_ADVISE_JSO"
 }
@@ -294,9 +298,9 @@ ___x_cmd_advise_man_load(){
     help:arg:parse
     case "$1" in
         x-cmd)          shift; ___x_cmd_advise_man_load___xcmd "$@" ;;
-        completion)     ___x_cmd_advise_man_load___completion "$@" ;;
-        all)            ___x_cmd_advise_man_load___all ;;
-        x)              ___x_cmd_advise_man_load___x ;;
+        completion)     shift; ___x_cmd_advise_man_load___completion "$@" ;;
+        all)            shift; ___x_cmd_advise_man_load___all ;;
+        x)              shift; ___x_cmd_advise_man_load___x ;;
         *)              advise:error "Not such [option=$1]"
                         help:show:ret:64 ;;
     esac
@@ -321,7 +325,7 @@ ___x_cmd_advise_man_rm(){
         completion)
             shift; X_help_cmd='___x_cmd help -m advise man rm completion' help:arg:parse
             if ___x_cmd_advise_man___folder_exist_completion; then
-                if [ "$#" -eq 0 ]; then x_="$___X_CMD_ADVISE_MAN_COMPLETIONS_FOLDER_SRC"
+                if [ "$#" -eq 0 ]; then x_="$___X_CMD_ADVISE_MAN_COMPLETIONS_FOLDER"
                 else ___x_cmd_advise_man_which___completion_getfile_ "$1"
                 fi
                 [ -e "$x_" ] || return $?
diff --git a/mod/log/latest b/mod/log/latest
--- a/mod/log/latest
+++ b/mod/log/latest
@@ -3,10 +3,349 @@
 
 # license:      GPLv3
 
-xrc:mod:lib     log             main
+# Section: bootrc
+# shellcheck disable=SC2154
+
+## log store
+___X_CMD_LOG_STORE_DEFAULT="${___X_CMD_ROOT_LOG}/store"
+
+
+## main
+___x_cmd_log___return(){
+    [ -n "$N" ] || return 1
+    [ -n "$M" ] || return 1
+    ___x_cmd log :"${N#:}" error -m "$M"
+    return 1
+}
+
+# Ensure 130 is returned ...
+___x_cmd_log___return_auto(){
+    [ -n "$N" ] || return 1
+    [ -n "$M" ] || return 1
+    ___x_cmd_log_pr :"${N#:}" error -m "$M"
+
+    case "$E" in
+        130)        return 130   ;;
+        *)          return 1     ;;
+    esac
+}
+
+alias log:return='E="$?" ___x_cmd_log___return_auto || return'
+alias log:panic='E="$?" ___x_cmd_log___return_auto || return'
+
+alias log:exit='___x_cmd_log___return || exit'
+
+# NOTICE: delibrate using || and enforce ___x_cmd_log___return return non-zero exit code
+alias log:ret:1='___x_cmd_log___return || return 1 2>/dev/null || exit 1'
+alias log:ret:64='___x_cmd_log___return || return 64 2>/dev/null || exit 64'
+
+
+## exec
+alias log:exec="___x_cmd_log exec"
+
+## trace
+
+alias x:trace='{ local ___X_CMD_LOG_DEBUG="${___X_CMD_LOG_DEBUG}"; local ___X_CMD_LOG_TRACE_LINE_LOCAL="${___X_CMD_LOG_TRACE_LINE_LOCAL}"; } 2>/dev/null; ___x_cmd_log trace'
+alias log:trace='{ local ___X_CMD_LOG_DEBUG="${___X_CMD_LOG_DEBUG}"; local ___X_CMD_LOG_TRACE_LINE_LOCAL="${___X_CMD_LOG_TRACE_LINE_LOCAL}"; } 2>/dev/null; ___x_cmd_log trace'
+
+alias x:trace:evex="___x_cmd_log trace_evex"
+alias log:trace:evex="___x_cmd_log trace_evex"
+
+alias x:trace:time="___x_cmd_log trace_time"
+alias log:trace:time="___x_cmd_log trace_time"
+
+## sub
+
+alias log:sub:init="
+    local x_LOG_FLAT=\"\${x_LOG_FLAT}\" 2>/dev/null 1>&2;
+    local ___X_CMD_LOG_YML_INDENT=\"\${___X_CMD_LOG_YML_INDENT}\" 2>/dev/null 1>&2;
+    local ___X_CMD_LOG_YML_PID_LIST=\"\${___X_CMD_LOG_YML_PID_LIST}\" 2>/dev/null 1>&2;
+    ___x_cmd_log sub init"
+
+alias log:sub:fini="___x_cmd_log sub fini"
+alias log:sub:reset="___x_cmd_log sub reset"
+
+# EndSection
+
+# Section: printer
+
+# TODO: To move xrc_log
+___X_CMD_LOG_C_TF="${___X_CMD_LOG_C_TF:-""}"
+export ___X_CMD_LOG_C_TF
+
+___X_CMD_LOG__TIMESTAMP_FORMAT=      # "+%H:%M:%S"      # Enable Timestamp.
+
+export ___X_CMD_LOG_C_DEBUG="${___X_CMD_LOG_C_DEBUG:-"\\033[2;35m"}"
+export ___X_CMD_LOG_C_INFO="${___X_CMD_LOG_C_INFO:-"\\033[32m"}"
+export ___X_CMD_LOG_C_WARN="${___X_CMD_LOG_C_WARN:-"\\033[1;33m"}"
+export ___X_CMD_LOG_C_ERROR="${___X_CMD_LOG_C_ERROR:-"\\033[1;31m"}"
+
+___X_CMD_LOG_C_TIMESTAMP_BEGIN="${___X_CMD_LOG_C_WARN:-"["}"
+___X_CMD_LOG_C_TIMESTAMP_END="${___X_CMD_LOG_C_WARN:-"]"}"
+
+___x_cmd_log_pr(){
+    case "${2:?Provide level}" in
+        debug)      eval "test -z \"\$___X_CMD_LOG_DEBUG\" -a 1 -lt \"\${___X_CMD_LOG__${1#:}:-\${___X_CMD_LOG_LEVEL_DEFAULT}}\"" || { local O="${1#:}"; shift 2; L=D C="$___X_CMD_LOG_C_DEBUG"                   ___x_cmd_log_0 "$@"; } ;;
+        info)       eval "test -z \"\$___X_CMD_LOG_DEBUG\" -a 2 -lt \"\${___X_CMD_LOG__${1#:}:-\${___X_CMD_LOG_LEVEL_DEFAULT}}\"" || { local O="${1#:}"; shift 2; L=I C="$___X_CMD_LOG_C_INFO"  C_MSG="\\033[0m"  ___x_cmd_log_0 "$@"; } ;;
+        warn)       eval "test -z \"\$___X_CMD_LOG_DEBUG\" -a 3 -lt \"\${___X_CMD_LOG__${1#:}:-\${___X_CMD_LOG_LEVEL_DEFAULT}}\"" || { local O="${1#:}"; shift 2; L=W C="$___X_CMD_LOG_C_WARN"  C_BG="\\033[7m"   ___x_cmd_log_0 "$@"; } ;;
+        error)      eval "test -z \"\$___X_CMD_LOG_DEBUG\" -a 4 -lt \"\${___X_CMD_LOG__${1#:}:-\${___X_CMD_LOG_LEVEL_DEFAULT}}\"" || { local O="${1#:}"; shift 2; L=E C="$___X_CMD_LOG_C_ERROR" C_BG="\\033[7m"   ___x_cmd_log_0 "$@"; } ;;
+        *)          eval "test -z \"\$___X_CMD_LOG_DEBUG\" -a 3 -lt \"\${___X_CMD_LOG__${1#:}:-\${___X_CMD_LOG_LEVEL_DEFAULT}}\"" || { local O="${1#:}"; shift 1; L=I C="$___X_CMD_LOG_C_INFO"  C_MSG="\\033[0m"  ___x_cmd_log_0 "$@"; } ;;
+    esac
+}
+
+___x_cmd_log_pr_debug(){    L=D C="$___X_CMD_LOG_C_DEBUG"                   ___x_cmd_log_0 "$@" ;   }
+___x_cmd_log_pr_info(){     L=I C="$___X_CMD_LOG_C_INFO"  C_MSG="\\033[0m"  ___x_cmd_log_0 "$@" ;   }
+___x_cmd_log_pr_warn(){     L=W C="$___X_CMD_LOG_C_WARN"  C_BG="\\033[7m"   ___x_cmd_log_0 "$@" ;   }
+___x_cmd_log_pr_error(){    L=E C="$___X_CMD_LOG_C_ERROR" C_BG="\\033[7m"   ___x_cmd_log_0 "$@" ;   }
+
+
+### Printer for attribute
+
+___X_CMD_LOG_OUTFILE=""
+___x_cmd_log_0(){
+    if [ -z "$___X_CMD_LOG_OUTFILE" ]; then
+        ___x_cmd_log_0_ "$@"
+    else
+        ___x_cmd_log_0_ 2>"$___X_CMD_LOG_OUTFILE"
+    fi
+}
+
+___x_cmd_log_0_(){
+    local IFS=" "
+
+    # ${___X_CMD_TRACE_LINE_LOCAL+<${___X_CMD_TRACE_LINE_LOCAL#"$O"}>
+    local track="${___X_CMD_TRACE_LINE_LOCAL}"
+    [ -z "$track" ] || track="<${track#"$O/"}>"
+
+    local x_=""
+    case "$1" in
+        -*)         ___x_cmd_log_0_advanced_ "$@" ;;
+        *)          x_="$*" ;;
+    esac
+
+    local pid_list_str=""
+    [ -z "${___X_CMD_LOG_YML_PID_LIST}" ] || pid_list_str=" $___X_CMD_LOG_YML_PID_LIST"
+
+    local timestamp=""
+    [ -z "$___X_CMD_LOG__TIMESTAMP_FORMAT" ] || timestamp=" $(___x_cmd_cmds date "${___X_CMD_LOG__TIMESTAMP_FORMAT}")"
+
+    if [ -n "$___X_CMD_LOG_C_TF" ] || [ -t 2 ]; then
+        [ -z "$timestamp" ] || timestamp="${___X_CMD_LOG_C_TIMESTAMP_BEGIN}${timestamp}${___X_CMD_LOG_C_TIMESTAMP_END}"
+        printf  "%s${timestamp}%s ${C}${C_BG}%s\033[0m${C}|%s$track: ${C_MSG}%s\033[0m\n" \
+                "${___X_CMD_LOG_YML_INDENT}-" "${pid_list_str}" "$L" "$O" "$x_"
+    else
+        printf  "%s${timestamp}%s %s|%s: %s\n" \
+                "${___X_CMD_LOG_YML_INDENT}-" "${pid_list_str}" "$L" "$O" "$x_"
+    fi >&2
+}
+
+# x:error -c "$code" -t "error-tag" --time "$time" -e os,arch,abc
+# x:error -e "$error-tag" -m "error msg" -c "$code" --time "$time" -e os,arch,abc
+
+# Using outerr to record the
+# x log run :scotty -- cmd1 arg1 arg2 arg3
+# Using outerr to record, then make into the log stream
+
+
+___x_cmd_log_0_advanced_(){
+    local code=     # single line
+    local more=
+    local help=     # single line.
+
+    local sub=
+
+    local str_more="more:"
+    if [ -n "$___X_CMD_LOG_C_TF" ] || [ -t 2 ]; then
+        str_more="${___X_CMD_UNSEENCHAR_033}[36m${str_more}${___X_CMD_UNSEENCHAR_033}[0m"
+    fi
+
+    while [ $# -gt 0 ]; do
+        case "$1" in
+            -c)
+                    code="${2}"
+                    shift 2 || return $? ;;
+            -h)
+                    help="${2}"
+                    shift 2 || return $? ;;
+            --m:*)
+                    ___X_CMD_LOG_0_INDENT="${___X_CMD_LOG_YML_INDENT}    "\
+                        ___x_cmd_log_0_ml_ "${2}"
+                    more="${more}${___X_CMD_LOG_YML_INDENT}    ${1#--m:}: ${x_}
+"
+                    shift 2 || return $?
+                    x_=
+                    ;;
+            -m)     ___X_CMD_LOG_0_INDENT="${___X_CMD_LOG_YML_INDENT}  " \
+                    ___x_cmd_log_0_ml_ "$2"
+
+                    shift 2 || return $?
+                    ;;
+
+            --y:*)
+                    ___X_CMD_LOG_0_INDENT="${___X_CMD_LOG_YML_INDENT}    "\
+                        ___x_cmd_log_0_yml_ "${2}"
+                    more="${more}${___X_CMD_LOG_YML_INDENT}    ${1#--y:}: ${x_}
+"
+                    shift 2 || return $?
+                    x_=
+                    ;;
+            -y)     ___X_CMD_LOG_0_INDENT="${___X_CMD_LOG_YML_INDENT}  " \
+                    ___x_cmd_log_0_yml_ "$2"
+
+                    shift 2 || return $?
+                    ;;
+
+            -S)
+                    sub="S:"
+                    shift 1
+                    ;;
+            --)     break ;;
+            --*)
+                    more="${more}${___X_CMD_LOG_YML_INDENT}    ${1#--}: ${2}
+"
+                    shift 2 || return $?
+                    ;;
+            *)      break;;
+        esac
+    done
+
+    [ -z "$1" ] || x_="${x_}${1}"
+
+    [ -z "$help" ] || {
+        local str_help="help:"
+        if [ -n "$___X_CMD_LOG_C_TF" ] || [ -t 2 ]; then
+            str_help="${___X_CMD_UNSEENCHAR_033}[31m${str_help}${___X_CMD_UNSEENCHAR_033}[0m"
+        fi
+        x_="$x_
+${___X_CMD_LOG_YML_INDENT}  ${str_help} ${help}"
+    }
+
+    [ -z "$code" ] || {
+        local str_code="code:"
+        if [ -n "$___X_CMD_LOG_C_TF" ] || [ -t 2 ]; then
+            str_code="${___X_CMD_UNSEENCHAR_033}[36m${str_code}${___X_CMD_UNSEENCHAR_033}[0m"
+        fi
+        # TODO: If code not eq 0, use red color.
+        x_="$x_
+${___X_CMD_LOG_YML_INDENT}  ${str_code} ${code}"
+    }
+
+    [ -z "$more" ] || {
+        local str_more="more:"
+        if [ -n "$___X_CMD_LOG_C_TF" ] || [ -t 2 ]; then
+            str_more="${___X_CMD_UNSEENCHAR_033}[36m${str_more}${___X_CMD_UNSEENCHAR_033}[0m"
+        fi
+        # TODO: colorize key
+        x_="${x_}
+${___X_CMD_LOG_YML_INDENT}  ${str_more}
+${more%?}"
+    }
+
+    [ -z "$sub" ] || {
+        x_="${x_}
+${___X_CMD_LOG_YML_INDENT}  S:"
+    }
+}
+
+# Mode: multiple line mode
+___x_cmd_log_0_ml_(){
+    local indent="${___X_CMD_LOG_0_INDENT}  ";  x_="|"
+    local line; while IFS= read -r line; do
+        x_="${x_}
+${indent}${line}"
+    done <<A
+$1
+A
+}
+
+___x_cmd_log_0_yml_(){
+    local indent="${___X_CMD_LOG_0_INDENT}  ";  x_=""
+    local line; while IFS= read -r line; do
+        if [ -z "$x_" ]; then
+            x_="${line} "
+        else
+            x_="${x_}
+${indent}${line}"
+        fi
+    done <<A
+$1
+A
+}
+
+
+
+# EndSection
+
+# Section: util
+___x_cmd_log_level_code_to_level_name(){
+    case "${1:?Provide code}" in
+        1)      level_name=debug ;;
+        2)      level_name=info ;;
+        3)      level_name=warn ;;
+        4)      level_name=error ;;
+        5)      level_name=none ;;
+        *)      level_name=info ;;
+    esac
+}
+
+___X_CMD_LOG_LEVEL_DEFAULT=2
+___x_cmd_log_level_default(){
+    case "${1:?Provide name}" in
+        d|debug|1)  ___X_CMD_LOG_LEVEL_DEFAULT=1 ;;
+        i|info|2)   ___X_CMD_LOG_LEVEL_DEFAULT=2 ;;
+        w|warn|3)   ___X_CMD_LOG_LEVEL_DEFAULT=3 ;;
+        e|error|4)  ___X_CMD_LOG_LEVEL_DEFAULT=4 ;;
+        n|none|5)   ___X_CMD_LOG_LEVEL_DEFAULT=5 ;;
+        *)
+            ___x_cmd_log_pr x error "Fail to set default level for unknown [level name=$1]"
+            return 1
+    esac
+}
+
+___x_cmd_log_init(){
+    ___x_cmd_log_init_inner "$@" 1 2 3 4
+}
+
+___x_cmd_log_init_inner(){
+    local logger_name="${1:?Provide logger name}"
+    shift
+
+    local var="___X_CMD_LOG__$logger_name"
+
+    local code="
+$var=\${$var:-2}
+___X_CMD_LOG__0_$logger_name=
+
+${logger_name}_log(){     ___x_cmd_log_pr $logger_name \"\$@\";   }
+"
+
+    local level_name
+    local level_code; for level_code in "$@"; do
+        ___x_cmd_log_level_code_to_level_name "$level_code"
+        code="$code
+alias ${logger_name}:$level_name='test -z \"\$___X_CMD_LOG_DEBUG\" -a $level_code -lt \"\${___X_CMD_LOG__${logger_name}:-2}\" || O=${logger_name} ___x_cmd_log_pr_${level_name}'
+"
+    done
+
+    eval "$code"
+}
+
+# EndSection
+
+___x_cmd_log___main() {
+    case "$1" in
+        :*)         ___x_cmd_log_pr "$@" ;;
+        init)       shift;      ___x_cmd_log_init           "$@" ;;
+
+        *)          [ -n "$___X_CMD_LOG_OTHER_LOADED" ]     ||  xrc:mod log/lib/run
+                    ___x_cmd_log____other        "$@" ;;
+    esac
+}
 
 ___x_cmd_log(){
     ___x_cmd_log___main "$@"
 }
+
+___x_cmd_log_init log
 
 # xrc setmain ___x_cmd_log
diff --git a/mod/perl/lib/load b/mod/perl/lib/load
--- a/mod/perl/lib/load
+++ b/mod/perl/lib/load
@@ -24,13 +24,13 @@ ___x_cmd_perl_load(){
     }
 
     ___x_cmd_perl_load_checkenv_side || {
-        if x ui yesno "Your current perl environment is imcomplete without cpan or cpanm. Do you want to load x-cmd environment?"; then
+        # if x ui yesno "Your current perl environment is imcomplete without cpan or cpanm. Do you want to load x-cmd environment?"; then
             ___x_cmd_perl_load_env
             return
-        else
-            x:warn "Loading abort. Exit."
-            return 1
-        fi
+        # else
+        #     x:warn "Loading abort. Exit."
+        #     return 1
+        # fi
     }
 
     if [ -z "$installable" ]; then
@@ -38,7 +38,7 @@ ___x_cmd_perl_load(){
     else
         ___x_cmd_perl_load_checkinstallable || {
             x:warn "Current env is not installable"
-            ___x_cmd_python_load_env
+            ___x_cmd_perl_load_env
             return
         }
         ___X_CMD_PERL_LOADED=installable
@@ -63,12 +63,12 @@ ___x_cmd_perl_load_env(){
 
 
 ___x_cmd_perl_load_checkenv_core(){
-    x hascmd perl   || return
+    ___x_cmd_hascmd perl   || return
 }
 
 ___x_cmd_perl_load_checkenv_side(){
-    x hascmd cpan   || return
-    x hascmd cpanm  || return
+    ___x_cmd_hascmd cpan   || return
+    ___x_cmd_hascmd cpanm  || return
 }
 
 # TODO: Add yes and quiet in the future
diff --git a/mod/pkg/lib/sphere/snap b/mod/pkg/lib/sphere/snap
--- a/mod/pkg/lib/sphere/snap
+++ b/mod/pkg/lib/sphere/snap
@@ -7,7 +7,7 @@ xrc:mod:lib pkg     sphere/xbin
 ___x_cmd_pkg_sphere_snap(){
     local op="$1"
     case "$op" in
-        exec|remove_cache)
+        exec|ensure_execfp|gen_execfp)
                     shift; ___x_cmd_pkg_sphere_snap___"$op" "$@" ;;
         *)          ___x_cmd_pkg_sphere_snap___exec "$@" ;;
     esac
@@ -16,8 +16,7 @@ ___x_cmd_pkg_sphere_snap(){
 ___x_cmd_pkg_sphere_snap___exec(){
     local X_help_cmd='___x_cmd help -m pkg sphere snap'
     local sphere_name=; local osarch=
-    local name=; local version=
-    local bin_rpath=; local function_name=; local bin_path_name=
+    local name=; local version=; local sociality
     while [ "$#" -gt 0 ]; do
         case "$1" in
             --sphere)
@@ -39,14 +38,8 @@ ___x_cmd_pkg_sphere_snap___exec(){
             -n|--name)
                     name="$2";          [ -n "$2" ] || N=pkg M="Provide a package name" log:ret:1
                     shift 2 ;;
-            --function-name)
-                    function_name="$2"; [ -n "$2" ] || N=pkg M="Provide function name value" log:ret:1
-                    shift 2 ;;
-            --binpath-name)
-                    bin_path_name="$2"; [ -n "$2" ] || N=pkg M="Provide a variable name" log:ret:1
-                    shift 2 ;;
-            --binpath)
-                    bin_rpath="$2";     [ -n "$2" ] || N=pkg M="Provide relative path of bin name" log:ret:1
+            --sociality)
+                    sociality="$2";     [ -n "$2" ] || N=pkg M="Provide sociality value" log:ret:1
                     shift 2 ;;
             -h|--help)
                     help:show:ret:0 ;;
@@ -60,145 +53,81 @@ ___x_cmd_pkg_sphere_snap___exec(){
     local x_=
     local binname="$1";
     [ -n "$binname" ]   || N=pkg M="Provide a bin name" log:ret:1
+    shift
 
     [ -n "$name" ]      || {
-        x_=""; ___x_cmd_pkg_sphere_xbin_get_binmod_name_ "$binname" || return $?
-        name="$x_"
+        name="$binname"
+        # x_=""; ___x_cmd_pkg_sphere_xbin_get_binmod_name_ "$binname" || return $?
+        # name="$x_"
         [ -n "$name" ]  || N=pkg M="Not found package name for $binname" log:ret:1
     }
-    [ -n "$version" ]   || {
-        x_=""; ___x_cmd_pkg_default_version_ "$name" "$osarch" || return $?
-        version="$x_"
-        [ -n "$version" ] || N=pkg M="Not found $name version" log:ret:1
+
+    local binpath=
+    local execfile="${___X_CMD_ROOT_PKG_EXEC_BINPATH}/${binname}"
+    if [ -f "$execfile" ]; then
+        if read -r binpath <"$execfile" && [ -x "$binpath" ]; then
+            "$binpath" "$@"
+            return
+        fi
+    fi
+
+    ___x_cmd_pkg_sphere_snap___ensure_execfp \
+        --sphere "$sphere_name" --sphereroot "$___X_CMD_PKG_ROOT_SPHERE" \
+        --osarch "$osarch" "$name" "$version" "$sociality" || return $?
+
+    [ -f "$execfile" ] || {
+        pkg:error "Not found exec filepath for $binname"
+        return 1
     }
 
-    [ -n "$function_name" ] || {
-        local ___X_CMD_STR___DASH2UNDERLINE=; ___x_cmd_str___dash2underline "$binname"
-        function_name="___x_cmd_pkg_sphere_snap___function_${___X_CMD_STR___DASH2UNDERLINE}"
-    }
-    pkg:debug --binname "$binname" --pkgname "$name" --version "$version" --osarch "$osarch" --function_name "$function_name" --bin_path_name "$bin_path_name" "sphere snap"
-
-    ___x_cmd hascmd "$function_name" || {
-        ___x_cmd_pkg_sphere_snap___gen_function "$name" "$version" "$osarch" "$binname" "$bin_rpath" "$function_name" "$bin_path_name" || return $?
-    }
-
-    shift
-    "$function_name" "$@"
+    if read -r binpath <"$execfile" && [ -x "$binpath" ]; then
+        "$binpath" "$@"
+        return
+    fi
 }
 
-___x_cmd_pkg_sphere_snap___gen_function(){
-    local name="$1"
-    local version="$2"
-    local osarch="$3"
-    local binname=$4
-    local bin_rpath="$5"
-    local function_name="$6"
-    local bin_path_name="$7"
-
-    local bin_cachepath="$___X_CMD_PKG_ROOT_SPHERE/$sphere_name/.x-cmd/snap/$osarch/$name/$version/$binname/$function_name"
-    # TODO: Need to be removed in the future
-    ___x_cmd_pkg_update___check # ensure existense of "$___X_CMD_PKG_FP_UPDATED_DONE"
-    ___x_cmd depend run "$bin_cachepath" -- "$___X_CMD_PKG_FP_UPDATED_DONE" -- ___x_cmd_pkg_sphere_snap___gen_function_file
-    [ -f "$bin_cachepath" ] || return $?
-    pkg:debug "snap bin function cache path => $bin_cachepath"
-    . "$bin_cachepath"
-}
-___x_cmd_pkg_sphere_snap___gen_function_file(){
-    x_=; ___x_cmd_pkg_sphere_snap___xbin_path_ "$name" "$version" "$osarch" "$binname" "$bin_rpath" || return $?
-    local bin_path="$x_"
-
-    x_=; ___x_cmd_shq1_ "$___X_CMD_PKG_ROOT_SPHERE"
-    local sphere_root="$x_"
-
-    x_=; ___x_cmd_shq1_ "$bin_path"
-    bin_path="$x_"
-
-    local bin_code="
-$function_name(){
-    ___x_cmd_pkg_sphere_snap___ensurefp_and_exec ${bin_path} ${sphere_name} ${sphere_root} ${osarch} ${name} ${version} \"\$@\"
-}
-"
-
-    [ -z "$bin_path_name" ] || {
-        bin_code="$bin_path_name=${bin_path}
-${bin_code}"
-    }
-
-
-    ___x_cmd ensurefp "$bin_cachepath"
-    printf "%s\n" "$bin_code" > "$bin_cachepath"
-}
-
-___x_cmd_pkg_sphere_snap___ensurefp_and_exec(){
-    local bin_path="$1"
-    local sphere_name="$2"
-    local sphere_root="$3"
-    local osarch="$4"
-    local name="$5"
-    local version="$6"
-
-    [ -f "$bin_path" ] || {
-        ___x_cmd pkg sphere add --prebuild  \
-            --reason "snap,protect"   \
-            --sphere "$sphere_name" --sphereroot "$sphere_root" \
-            --osarch "$osarch" "$name" "$version" || return $?
-
-        [ -f "$bin_path" ] || N=pkg M="Not found pkg [name=$name] [version=$version] bin path" log:ret:1
-        ___x_cmd_cmds chmod +x "$bin_path" || N=pkg M="chmod $bin_path - Operation not permitted" log:ret:1
-    }
-
-    shift 6
-    "${bin_path}" "$@"
-}
-
-___x_cmd_pkg_sphere_snap___remove_cache(){
+___x_cmd_pkg_sphere_snap___ensure_execfp(){
     pkg:sphere:parse:args
-    local bin_cachedir="$___X_CMD_PKG_ROOT_SPHERE/$sphere_name/.x-cmd/snap/$osarch/$name/$version"
-    [ ! -d "$bin_cachedir" ] || {
-        pkg:debug "Removing snap cache => $bin_cachedir"
-        ___x_cmd rmrf "$bin_cachedir"
-    }
+    local sociality="$1"
+
+    ___x_cmd_pkg_sphere add --prebuild  \
+        --reason "snap,protect"   \
+        --sphere "$sphere_name" --sphereroot "$___X_CMD_PKG_ROOT_SPHERE" \
+        --osarch "$osarch" "$name" "$version" || return $?
+
+    ___x_cmd_pkg_sphere_snap___gen_execfp \
+        --sphere "$sphere_name" --sphereroot "$___X_CMD_PKG_ROOT_SPHERE" \
+        --osarch "$osarch" "$name" "$version" "$sociality"
 }
 
-___x_cmd_pkg_sphere_snap___xbin_path_(){
-    local name="$1"
-    local version="$2"
-    local osarch="$3"
-    local binname=$4
-    local bin_rpath="$5"
-
-    [ -n "$bin_rpath" ] || {
-        x_=""; ___x_cmd_pkg_sphere_snap___xbin_relative_path_ "$name" "$version" "$osarch" "$binname" || return $?
-        bin_rpath="$x_"
-    }
+___x_cmd_pkg_sphere_snap___gen_execfp(){
+    pkg:sphere:parse:args
+    local sociality="$1"
 
     local x_treename=; ___x_cmd_pkg_treename_ "$name" "$version" "$osarch" || return $?
-    local install_path="$___X_CMD_PKG_ROOT_SPHERE/$sphere_name/$x_treename/$name/$version"
-    local bin_path="$install_path/$bin_rpath"
-    [ -f "$bin_path" ] || ___x_cmd_pkg_sphere_add --prebuild --reason "snap" --sphere "$sphere_name" --sphereroot "$___X_CMD_PKG_ROOT_SPHERE" --osarch "$osarch" "$name" "$version" || return $?
-    [ -f "$bin_path" ] || N=pkg M="Not found pkg [name=$name] [version=$version] bin path" log:ret:1
-    ___x_cmd_cmds chmod +x "$bin_path" || N=pkg M="chmod $bin_path - Operation not permitted" log:ret:1
-    x_="$bin_path"
+    local tgt="$___X_CMD_PKG_ROOT_SPHERE/$sphere_name/$x_treename/$name/$version"
+
+    local path_list; path_list="$( ___x_cmd_pkg_sphere_link list_all_path_expand "$name" "$version" "$osarch" "$tgt" bin "$sociality" )" || return $?
+    [ -n "$path_list" ] || {
+        pkg:warn "Not found path list for $name $version"
+        return 1
+    }
+
+    local execdir="$___X_CMD_ROOT_PKG_EXEC_BINPATH"
+    ___x_cmd mkdirp "$execdir"
+
+    local bin_path=
+    local bin_name=
+    while read -r bin_path; do
+        bin_name="${bin_path##*/}"
+        printf "%s\n" "$bin_path" > "$execdir/$bin_name"
+        pkg:info "Generate the exec file for $bin_name"
+        ___x_cmd_cmds chmod +x "$bin_path" || {
+            pkg:error "Cannot use chmod on $bin_path"
+            return 1
+        }
+    done <<A
+$path_list
+A
 }
 
-___x_cmd_pkg_sphere_snap___xbin_relative_path_(){
-    local name="$1"
-    local version="$2"
-    local osarch="$3"
-    local binname=$4
-    local datalist; datalist="$( ___x_cmd_pkg___all_info --non-version "$name" "$version" "$osarch" )" || return $?
-    local bin_rpath; bin_rpath="$(
-    printf "%s\n\n" "$datalist" | ___x_cmd_cmds_awk \
-        -v BIN_MOD_NAME="$binname" \
-        -f "$___X_CMD_ROOT_MOD/awk/lib/core.awk" \
-        -f "$___X_CMD_ROOT_MOD/awk/lib/j/json.awk"      \
-        -f "$___X_CMD_ROOT_MOD/awk/lib/j/jqparse.awk"   \
-        -f "$___X_CMD_ROOT_MOD/pkg/lib/awk/util.awk"    \
-        -f "$___X_CMD_ROOT_MOD/pkg/lib/awk/pkg._.awk"   \
-        -f "$___X_CMD_ROOT_MOD/pkg/lib/awk/pkg.xbin.awk"
-    )"
-
-    # [ -n "$bin_rpath" ] || bin_rpath="bin/$binname"
-    [ -n "$bin_rpath" ] || N=pkg M="Not found bin path of [binname=$binname] from pkg [name=$name] [version=$version]" log:ret:1
-    x_="$bin_rpath"
-}
diff --git a/mod/x-cmd/latest b/mod/x-cmd/latest
--- a/mod/x-cmd/latest
+++ b/mod/x-cmd/latest
@@ -1,9 +1,215 @@
 # Author:       Li Junhao   l@x-cmd.com             # xrc
 # shellcheck    shell=sh    disable=SC3043,SC1091
 
-xrc:mod         x-cmd/lib/main
+# Section: util
+___x_cmd_wsroot(){
+    local x_; ___x_cmd wsroot_ "$@" || return
+    printf "%s\n" "$x_"
+}
 
-xrc set
+___x_cmd_wsroot_(){
+    if [ -z "$1" ]; then
+        [ -z "$___X_CMD_WS_CURRENT" ] || {
+            ___X_CMD_WSROOT_="$___X_CMD_WS_CURRENT"
+            x_="$___X_CMD_WS_CURRENT"
+            return 0
+        }
+        set -- .
+    fi
+
+    if [ "$1" = . ]; then
+        local cur="$PWD"
+    else
+        local x_=; ___x_cmd_abspath_ "${1}" || return
+        cur="$x_"
+    fi
+
+    while [ ! "$cur" = "" ]; do
+        if [ -d "$cur/.x-cmd" ]; then
+            ___X_CMD_WSROOT_="$cur"     # Deprecated...
+            x_="$cur"
+            return 0
+        fi
+        cur=${cur%/*}
+    done
+    return 1
+}
+
+___x_cmd_which_panic(){
+    local ___X_CMD_WHICH_ONE_RESULT
+    if ! ___x_cmd_which_one "$p"; then
+        printf "%s\n" "Fail to find path for $p" >&2
+        return 1
+    else
+        printf "%s\n" "$___X_CMD_WHICH_ONE_RESULT"
+    fi
+}
+
+___x_cmd_which(){
+    local p
+    for p in "$@"; do
+        ___x_cmd_which_panic || return 1
+    done
+}
+
+___x_cmd_validenvname(){
+    local IFS=_
+    [ "$*" = "${*#*=}" ] || return 1
+    eval "local ___x_cmd_validenvname$*___=" 2>/dev/null 1>&2 || return 1
+}
+
+___x_cmd_defaultassignvar(){
+    local name="$1"; shift
+    ___x_cmd_defaultassignvar_ "$name" x "$@"
+}
+
+___x_cmd_defaultassignvar_(){
+    local ___x_cmd_defaultassignvar_varname=${1}; shift
+    local x_
+    "$@"
+    eval "$___x_cmd_defaultassignvar_varname=\"\$x_\""
+}
+
+x_(){
+    ___x_cmd_defaultassignvar_ "$@"
+}
+
+# TODO: in other, just using
+# ___X_CMD_UNIXEPOCHSECOND
+___x_cmd_unixepochs_(){
+    x_="$EPOCHSECONDS"
+    [ -n "$x_" ] || x_="$(___x_cmd_cmds date +%s)"
+}
+
+# ___X_CMD_UNIXEPOCHMICROSECOND
+___x_cmd_unixepochms_(){
+    :
+}
+
+
+___x_cmd_wreadl(){
+    local e;
+    case "$1" in
+        \"*\")      while read -r e; do    eval printf '"%s\n"' "$1" ; done ;;
+        *)          while read -r e; do    "$@" ;                      done
+    esac
+}
+
+___x_cmd_reval(){
+    local ___X_CMD_REVAL_CODE
+    while read -r ___X_CMD_REVAL_CODE; do
+        eval "$___X_CMD_REVAL_CODE"      # Notice: If read encountering EOF, return 1
+        [ $# -eq 0 ] || "$@"
+    done
+}
+
+___x_cmd_pipestr(){
+    local data="$1";    shift
+    "$@" <<A
+$data
+A
+}
+# EndSection
+
+# Section: set
+___x_cmd_set_xready_init(){
+    ___X_CMD_SET_XREADY_LEVEL=$((___X_CMD_SET_XREADY_LEVEL+1))
+    [ "$___X_CMD_SET_XREADY_LEVEL" -eq 1 ] || return 0
+
+    case "$-" in
+        *e*)
+            set +o errexit
+            ___X_CMD_SET_XREADY___FLAG_ERREXIT=1 ;;
+    esac
+
+    case "$SHELLOPTS" in
+        *pipefail*)
+            set +o pipefail
+            ___X_CMD_SET_XREADY___FLAG_PIPEFAIL=1 ;;
+    esac
+}
+
+___x_cmd_set_xready_fini(){
+    ___X_CMD_SET_XREADY_LEVEL=$((___X_CMD_SET_XREADY_LEVEL-1))
+    [ "$___X_CMD_SET_XREADY_LEVEL" -eq 0 ] || return 0
+
+    [ -z "$___X_CMD_SET_XREADY___FLAG_ERREXIT" ] || {
+        set -o errexit
+        ___X_CMD_SET_XREADY___FLAG_ERREXIT=
+    }
+
+    [ -z "$___X_CMD_SET_XREADY___FLAG_PIPEFAIL" ] || {
+        set -o pipefail
+        ___X_CMD_SET_XREADY___FLAG_PIPEFAIL=
+    }
+}
+# EndSection
+
+# Section: ___x_cmd_main
+___X_CMD_ENGINE_SUBCMD_NAME=__enginerun
+
+___x_cmd_main(){
+    [ $# -gt 0 ]    ||      set -- --help
+
+    local op="$1";          shift
+    case "$op" in
+        log)                ___x_cmd_log                    "$@" ;;        # For efficiency
+        help|--help|-h)     ___x_cmd helpapp                "$@" ;;
+
+        :)                  ___x_cmd ddgo                   "$@" ;;
+
+        *)
+            if command -v "___x_cmd_${op}" 2>/dev/null 1>&2; then
+                "___x_cmd_${op}" "$@" ;         return
+            fi
+
+            [ ! -f "$___X_CMD_ROOT_MOD/x-cmd/lib/lwmod/$op" ] || {
+                . "$___X_CMD_ROOT_MOD/x-cmd/lib/lwmod/$op"
+                "___x_cmd_${op}" "$@" ;         return
+            }
+
+            [ ! -f "$___X_CMD_ROOT_MOD/${op}/latest" ] || {
+                ___x_cmd_loadedmod_put "$op" "___x_cmd_${op}"
+                xrc:mod "$op/latest"
+                "___x_cmd_${op}" "$@" ;         return
+            }
+
+            [ -n "$___X_CMD___OTHERWISE_LOADED" ] || xrc:mod    x-cmd/lib/__otherwise
+            ___x_cmd_main___otherwise "$op" "$@"
+            ;;
+    esac
+}
+
+___x_cmd_source(){
+    local ___x_cmd___source_run_filepath="${1:?filepath}";        shift
+    . "$___x_cmd___source_run_filepath" "$@"
+}
+
+# subshell rc
+___x_cmd_ssrc(){
+    ( ___x_cmd_source "$@" )
+}
+
+___x_cmd_pipevar(){
+    local varname="$1"; shift
+    [ $# -gt 0 ] || {
+        eval 'printf "%s\n" "$'"$varname"'"'
+        return
+    }
+    eval '
+    "$@" <<A
+$'"$varname"'
+A
+'
+}
+
+# TODO: It will be removed.
+___x_cmd_which_one(){
+    ___x_cmd whichone "$@"
+}
+
+# EndSection
+
 ___x_cmd(){
     ___x_cmd_set_xready_init
     local IFS=" $___X_CMD_UNSEENCHAR_NEWLINE"
@@ -16,13 +222,7 @@ ___x_cmd(){
 x(){
     ___x_cmd "$@"
 }
-
 # alias x=___x_cmd
 
-if ___x_cmd_is_suitable_advise_repl; then
-    command -v ___x_cmd_advise >/dev/null || xrc advise/latest
-fi
-
-xrc:mod:lib     x-cmd  replhook/index
-___x_cmd_definelazyloader ___x_cmd_a       alias/latest
-___x_cmd_definelazyloader ___x_cmd_ua      alias/latest
+# ___x_cmd_definelazyloader ___x_cmd_a       alias/latest
+# ___x_cmd_definelazyloader ___x_cmd_ua      alias/latest
diff --git a/mod/xrc/lib/util b/mod/xrc/lib/util
--- a/mod/xrc/lib/util
+++ b/mod/xrc/lib/util
@@ -1,92 +1,175 @@
 # shellcheck shell=dash
 
-___x_cmd_abspath_(){
-    local target_path="${1:?Please provide path}"
-
-    case "$target_path" in
-        \~/*)        target_path="$HOME/${target_path#*/}" ;;
-    esac
-
-    case "$target_path" in
-        /)          x_=/ ;;
-        .)          x_="$PWD" ;;
-        \~)         x_="$HOME" ;;
-        *)
-                    target_path="${target_path%/}"
-                    local basename="${target_path##*/}"
-                    if [ "$basename" = "$target_path" ]; then
-                        x_="$PWD/$target_path"
-                    else
-                        local x___ORIGIN_PWD="$PWD"
-                        ___x_cmd_cd0 "${target_path%"$basename"}" || return $?
-                        case "$basename" in
-                            \.)     x_="$PWD" ;;
-                            \.\.)   ___x_cmd_cd0 .. || return 1
-                                    x_="$PWD" ;;
-                            *)      x_="${PWD%/}/$basename"
-                        esac
-                        x_="$x_"
-                        ___x_cmd_cd0 "$x___ORIGIN_PWD" || return $?
-                    fi
-    esac
+# Section: functions to be removed.
+# TODO: Removed.
+___x_cmd_evex(){
+    if [ "$#" -lt 2 ]; then
+        eval "${1:-:}"
+    else
+        "$@"
+    fi
 }
 
-___x_cmd_abspath(){
+# TODO: Removed.
+___x_cmd_eval(){
+    if [ "$#" -lt 2 ]; then
+        eval "${1:-:}"
+    else
+        # "$@"
+        local ___x_cmd_evex_op="$1"; shift
+        eval "$___x_cmd_evex_op" "\"\$@\""
+    fi
+}
+
+
+# TODO: remove this function in the future. Put it in str module ...
+case "$___X_CMD_SHELL" in
+    dash|"")
+        ___x_cmd_str___dash2underline(){
+            local part=; local x_="$1"
+            while [ -n "$x_" ]; do
+                part="${x_%%-*}"
+                [ "$part" != "$x_" ] || break
+                x_="${part}_${x_#*-}"
+            done
+            ___X_CMD_STR___DASH2UNDERLINE="$x_"
+        }
+        ;;
+    *)
+        ___x_cmd_str___dash2underline(){
+            ___X_CMD_STR___DASH2UNDERLINE="${1//-/_}"
+        }
+        ;;
+esac
+# EndSection
+
+# Section: whichbin hascmd hasbin
+___x_cmd_hascmd(){
+    command -v "${1:?Provide command name}" 1>/dev/null 2>/dev/null
+}
+
+___x_cmd_hasbin(){
     local x_
-    ___x_cmd_abspath_ "$@" || return $?
-    printf "%s\n" "$x_"
+    ___x_cmd_whichbin_ "$1"
 }
 
-___X_CMD_LOCATEFOLDER_MODE=-e
-___x_cmd_locatefolder_(){
-    local cur="${1:?Provide starting path}"
-    x_=; ___x_cmd_abspath_ "$cur" || return $?
-    cur="$x_"; x_=""
 
-    local relative_filepath="${2:?Provide relative filepath}"
-    while [ ! "$cur" = "" ]; do
-        # shellcheck disable=SC1009,SC1072,SC1073
-        if [ "$___X_CMD_SEARCH_PATH_TYPE" "$cur/$relative_filepath" ]; then
-            x_="$cur"
+if [ -z "$MSYS" ]; then
+___x_cmd_whichbin___check_(){
+    local fp="$1/$2"
+    [ -f "$fp" ] || return 1
+    if [ -x "$fp" ]; then
+        x_="$fp"
+    else
+        x_=
+        return 1
+    fi
+}
+
+else
+___x_cmd_whichbin___check_(){
+    local fp="$1/$2"
+    [ -f "$fp" ] || return 1
+    if [ -x "$fp" ]; then
+        x_="$fp"
+    elif [ -x "$fp.exe" ]; then
+        x_="$fp.exe"
+    else
+        x_=
+        return 1
+    fi
+}
+
+fi
+
+if [ -z "$ZSH_VERSION" ]; then
+    ___x_cmd_whichbin_(){
+        local exe="$1"
+        local IFS=:; local p; for p in $PATH; do
+            ___x_cmd_whichbin___check_ "$p" "$exe" || continue
             return 0
-        fi
-        cur=${cur%/*}
-    done
-    return 1
-}
-
-___x_cmd_locatefolder(){
-    local x_
-    ___x_cmd_locatefolder_ || return $?
-    printf "%s\n" "$x_"
-}
-
-# Section: Deprecated: ___x_cmd_search_path_
-___X_CMD_SEARCH_PATH_TYPE="-e"
-___x_cmd_search_path_(){
-    local cur="${1:?Provide starting path}"
-    local x_=; ___x_cmd_abspath_ "$cur" || return $?
-    cur="$x_"
-
-    local relative_filepath="${2:?Provide relative filepath}"
-    while [ ! "$cur" = "" ]; do
-        # shellcheck disable=SC1009,SC1072,SC1073
-        if [ "$___X_CMD_SEARCH_PATH_TYPE" "$cur/$relative_filepath" ]; then
-            ___X_CMD_SEARCH_PATH_RESULT="$cur"
+        done
+        return 1
+    }
+else
+    ___x_cmd_whichbin_(){
+        local exe="$1"
+        local IFS=" ";
+        local p; while read -r p; do
+            ___x_cmd_whichbin___check_ "$p" "$exe" || continue
             return 0
-        fi
-        cur=${cur%/*}
-    done
-    return 1
+        done <<A
+${PATH//:/
 }
+A
+        return 1
+    }
 
-___x_cmd_search_path(){
-    local ___X_CMD_SEARCH_PATH_RESULT
-    ___x_cmd_search_path_ "$@" && printf "%s" "$___X_CMD_SEARCH_PATH_RESULT"
+fi
+# EndSection
+
+# Section: Original INNER facility
+___X_CMD_INNER_PATH="$PATH"
+
+___x_cmd_inner_cd(){
+    ___x_cmd_cmds_cd "$@"
 }
 # EndSection
 
+# Section: cd0 and ___x_cmd_cmds_cd
+___x_cmd_cd0(){
+    local OLDPWD0="$OLDPWD"
+    ___x_cmd_cmds_cd "$1" 2>/dev/null || {
+        x:error "cd cannot be performed to the directory[$1], it might not exist"
+        return 1
+    }
+    OLDPWD="$OLDPWD0"
+}
 
+if [ -n "${ZSH_VERSION}${BASH_VERSION}" ]; then
+# `command cd` will not execute buildin command `cd` in zsh, refer: https://linux.die.net/man/1/zshbuiltins
+___x_cmd_cmds_cd(){
+    builtin cd "$@" || return $?
+}
+
+else
+___x_cmd_cmds_cd(){
+    command cd "$@" || return $?
+}
+fi
+# EndSection
+
+# Section: cmds
+# cmds is short for cmdshim
+___x_cmd_cmds(){
+    [ $# -gt 0 ] || N=x M="___x_cmd_cmds expect at least one argument" log:ret:64
+
+    local op="$1";  shift
+    case "$op" in
+        cd|mv|cp|mkdir|rm|touch|awk|ls|cat|sleep|ln)
+                            ___x_cmd_cmds_"$op"         "$@" ;;
+        --)                 ___x_cmd_cmds_run           "$@" ;;
+        *)                  ___x_cmd_cmds_run "$op"     "$@" ;;
+    esac
+}
+
+___x_cmd_cmds_run(){
+    local x_
+    ___x_cmd_whichbin_ "$1" || return 127   # just like command return
+    shift
+    "$x_" "$@"
+}
+
+[ -f "${___X_CMD_ROOT_DATA}/cmdshim/code" ] || {
+    . "$___X_CMD_ROOT_MOD/x-cmd/lib/lwmod/cmdshim"
+    ___x_cmd_cmdshim___init
+} || return $?
+
+. "${___X_CMD_ROOT_DATA}/cmdshim/code"
+
+# EndSection
+
+# Section: is interactive control
 # ___X_CMD_IS_INTERACTIVE_FORCE=
 ___X_CMD_IS_INTERACTIVE_ENABLE=1
 
@@ -151,215 +234,38 @@ ___x_cmd_is_suitable_advise_env(){
 ___x_cmd_is_suitable_advise_repl(){
     ___x_cmd_is_suitable_advise_env && ___x_cmd_is_repl
 }
-
-
-
-___x_cmd_readlink_recursive(){
-    local ___X_CMD_READLINK_RECURSIVE_
-    ___x_cmd_readlink_recursive_ "$@"
-    printf "%s\n" "$___X_CMD_READLINK_RECURSIVE_"
-}
-
-___x_cmd_definelazyloader(){
-    local funcname="${1:?Provide function name}"
-    local respath="${2:?Provide resource path}"
-    eval "$funcname(){
-        if [ \"\$___X_CMD_DEFINELAZYLOADER\" = \"$funcname\" ]; then
-            printf \"No such function [%s] in [%s]\\n\" \"$funcname\" \"$respath\"
-            return 1
-        fi
-
-        if ! xrc $respath; then
-            printf \"Fail to xrc: %s\\n\" \"$respath\"
-            return 1
-        fi
-
-        local ___X_CMD_DEFINELAZYLOADER=$funcname
-        $funcname \"\$@\"
-    }"
-}
-
-# VAR   SEP    IT
-___x_cmd_trimutil(){
-    eval "
-[ -z \"\$${O}\" ] && return 1
-IT=\"\${${O}%%${SEP:-
-}*}\"
-if [ \"\${IT}\" = \"\${$O}\" ]; then
-    $O=\"\"
-else
-    $O=\"\${${O}#*${SEP:-
-}}\"
-fi
-return 0
-"
-}
-
-___x_cmd_isplit(){
-    SEP="${SEP:-
-}"
-    [ -n "$V" ] || return 1
-    e="${V%%"${SEP}"*}"
-    if [ "${e}" = "${V}" ]; then     V=
-    else                             V="${V#*"${SEP}"}"
-    fi
-}
-
-# x iter "$data" ','
-___x_cmd_spliter(){
-    local ___X_CMD_ITER_DATA="${1:?Provide sep}";
-    local ___X_CMD_ITER_SEP="${2:?Provide sep}";
-    ___X_CMD_ITER_SEP="${___X_CMD_ITER_SEP:-
-}"
-    shift 2
-
-    local e
-    case "$1" in
-        \"*\")
-            while true; do
-                e="${___X_CMD_ITER_DATA%%"${___X_CMD_ITER_SEP}"*}"
-                eval "printf \"%s\n\" \"$1\""
-                [ "$e" != "$___X_CMD_ITER_DATA" ] || break
-                ___X_CMD_ITER_DATA="${___X_CMD_ITER_DATA#*"$___X_CMD_ITER_SEP"}"
-            done
-
-            ;;
-        *)
-            while true; do
-                e="${___X_CMD_ITER_DATA%%"${___X_CMD_ITER_SEP}"*}"
-                "$@"
-                [ "$e" != "$___X_CMD_ITER_DATA" ] || break
-                ___X_CMD_ITER_DATA="${___X_CMD_ITER_DATA#*"$___X_CMD_ITER_SEP"}"
-            done
-    esac
-}
-
-___x_cmd_pidofsubshell_quick_(){
-    if [ -n "$BASHPID" ]; then
-        x_="$BASHPID"
-        return
-    fi
-
-    if [ -n "$ZSH_VERSION" ]; then
-        x_="${sysparams[pid]}"
-        return
-    fi
-
-    x_=
-}
-
-___x_cmd_pidofsubshell(){
-    local x_
-    ___x_cmd_pidofsubshell_quick_
-    if [ -z "$x_" ]; then   sh -c 'printf "%s\n" "$PPID"'
-    else                    printf "%s\n" "$x_"
-    fi
-}
-
-___x_cmd_pidofsubshell_(){
-    ___x_cmd_pidofsubshell_quick_
-    [ -n "$x_" ] || x_=$(sh -c 'printf "%s\n" "$PPID"')
-}
-
-# Deprecated: Should never use it.
-# To prevent dash inline environment problem: just for dash
-if [ "$___X_CMD_SHELL" = dash ]; then   alias ___x_cmd_shift1='[ $# -gt 0 ] && shift ; '
-else                                    alias ___x_cmd_shift1="shift ; "
-fi
-
-# Section: q1 q2
-case "$___X_CMD_SHELL" in
-    bash|zsh)
-___x_cmd_q1(){
-    printf "'%s'" "${1//\'/\\\'}"
-}
-
-___x_cmd_q2(){
-    printf "\"%s\"" "${1//\"/\\\"}"
-}
-    ;;
-    *)
-___x_cmd_q1(){
-    ___x_cmd_cmds_awk '
-BEGIN{ RS="\001"; S="'\''"; }
-{
-    gsub(S, "\\" S, $0)
-    printf(S "%s" S, $0)
-}' <<A
-$1
-A
-}
-
-___x_cmd_q2(){
-    ___x_cmd_cmds_awk '
-BEGIN{ RS="\001"; S="\""; }
-{
-    gsub(S, "\\" S, $0)
-    printf(S "%s" S, $0)
-}' <<A
-$1
-A
-}
-    ;;
-esac
 # EndSection
 
-# TODO: Removed.
-___x_cmd_evex(){
-    if [ "$#" -lt 2 ]; then
-        eval "${1:-:}"
-    else
-        "$@"
-    fi
-}
+# Section: functions that must be loaded: ___x_cmd_abspath_   ___x_cmd_shq1_
+___x_cmd_abspath_(){
+    local target_path="${1:?Please provide path}"
 
-# TODO: Removed.
-___x_cmd_eval(){
-    if [ "$#" -lt 2 ]; then
-        eval "${1:-:}"
-    else
-        # "$@"
-        local ___x_cmd_evex_op="$1"; shift
-        eval "$___x_cmd_evex_op" "\"\$@\""
-    fi
-}
+    case "$target_path" in
+        \~/*)        target_path="$HOME/${target_path#*/}" ;;
+    esac
 
-# ___x_cmd_abspath(){
-#     cd "${1:?Provide Path}" && ___X_CMD_ABSPATH="$PWD" && cd "$OLDPWD" || return
-# }
-
-# castract %c% '' %b%
-# V=
-# V=v.1.1
-# ___x_cmd_caxt v12.1.3     v %c1 . %c2 . %c3
-___x_cmd_caxt(){
-    local data="$1"; shift
-    local elem
-    local var
-    while [ "$#" -gt 2 ]; do
-        case "$1" in
-            %*) var="${1#%}"
-                elem="${data%%$2*}"
-                [ "$elem" != "$data" ] || return 1
-                eval "$var=\"\$elem\""
-                data="${data#"$elem"$2}"
-                shift 2
-                ;;
-
-            *)  elem="${data#$1}";
-                [ "$elem" != "$data" ] || return 1
-                data="$elem"
-                shift
-                ;;
-        esac
-    done
-
-    if [ "$#" -eq 1 ]; then
-        case "$1" in
-            %*) var="${1#%}"
-                eval "$var=\"\$data\""
-        esac
-    fi
+    case "$target_path" in
+        /)          x_=/ ;;
+        .)          x_="$PWD" ;;
+        \~)         x_="$HOME" ;;
+        *)
+                    target_path="${target_path%/}"
+                    local basename="${target_path##*/}"
+                    if [ "$basename" = "$target_path" ]; then
+                        x_="$PWD/$target_path"
+                    else
+                        local x___ORIGIN_PWD="$PWD"
+                        ___x_cmd_cd0 "${target_path%"$basename"}" || return $?
+                        case "$basename" in
+                            \.)     x_="$PWD" ;;
+                            \.\.)   ___x_cmd_cd0 .. || return 1
+                                    x_="$PWD" ;;
+                            *)      x_="${PWD%/}/$basename"
+                        esac
+                        x_="$x_"
+                        ___x_cmd_cd0 "$x___ORIGIN_PWD" || return $?
+                    fi
+    esac
 }
 
 ___x_cmd_shq1_(){
@@ -387,120 +293,114 @@ ___x_cmd_shq1_(){
 
     x_="$r"
 }
+# EndSection
 
-# This is very important... Widely used in docker and git intercept
-___x_cmd_cmdstr(){
-    local varname="$1";     shift
-
-    local t; eval t="\"\${$varname}\""
-    local i; local x_=
-    for i in "$@"; do
-        x_=; ___x_cmd_shq1_ "$i"
-        t="$t $x_"
-    done
-
-    eval "$varname"=\"\$t\"
+# Section: exitcode exception handle
+___x_cmd_ex_init(){
+    ___X_CMD_EX_EXIT_LOGGER=${1:-ex}
+    ___X_CMD_EX_EXIT_CODE="${2:-0}"
 }
 
-# x joinifs_ : a b c
-___x_cmd_joinifs_(){
-    local IFS="${1:?Provide sep}"
-    x_="$*"
+___x_cmd_ex_err_int(){
+    [ -z "$M" ] ||  ___x_cmd_log_pr :"$___X_CMD_EX_EXIT_LOGGER" "[recv SIGINT] ${M}"
 }
 
-case "$___X_CMD_SHELL" in
-    dash|"")
-        ___x_cmd_str___dash2underline(){
-            local part=; local x_="$1"
-            while [ -n "$x_" ]; do
-                part="${x_%%-*}"
-                [ "$part" != "$x_" ] || break
-                x_="${part}_${x_#*-}"
-            done
-            ___X_CMD_STR___DASH2UNDERLINE="$x_"
+___x_cmd_ex_err_msg(){
+    [ -z "$M" ] ||  ___x_cmd_log_pr :"$___X_CMD_EX_EXIT_LOGGER" "[EXIT=$___X_CMD_EX_EXIT_CODE] ${M}"
+}
+
+___x_cmd_ex_if_int(){
+    [ "$___X_CMD_EX_EXIT_CODE" -ne 130 ] || { ___x_cmd_ex_err_int; return 130; }
+}
+
+___x_cmd_ex_if_err(){
+    [ "$___X_CMD_EX_EXIT_CODE" -eq 0 ]   || { ___x_cmd_ex_err_msg; return "$___X_CMD_EX_EXIT_CODE"; }
+}
+
+alias ex:init='local ___X_CMD_EX_EXIT_CODE; local ___X_CMD_EX_EXIT_LOGGER; ___x_cmd_ex_init'
+alias ex:save='___X_CMD_EX_EXIT_CODE=$?'
+alias ex:ret:if-int='___x_cmd_ex_if_int || return 130'
+alias ex:ret:if-err='___x_cmd_ex_if_err || return $?'
+# EndSection
+
+# Section: runmode
+
+# No human interfere
+
+___X_CMD_RUNMODE="${___X_CMD_RUNMODE:-"$___X_CMD_RUNMODE_AUTO"}"
+
+___X_CMD_RUNMODE_AUTO=0
+
+# ___X_CMD_RUNMODE_AI=1
+# ___X_CMD_RUNMODE_HUMANAI=5
+
+___X_CMD_RUNMODE_MANUAL=5
+
+___X_CMD_RUNMODE_CHATTY=9
+
+# To prevent hang in script
+___x_cmd_runmode_is_auto(){     [ "${___X_CMD_RUNMODE:-0}" -le 0 ]; }
+___x_cmd_runmode_is_manual(){   [ "${___X_CMD_RUNMODE:-0}" -ge 5 ]; }
+___x_cmd_runmode_is_chatty(){   [ "${___X_CMD_RUNMODE:-0}" -ge 9 ]; }
+
+# If there
+___X_CMD_DEVTTY_FP=/dev/tty
+
+___x_cmd_runmode_is_interatable(){
+    # [ -n "$___X_CMD_DEVTTY_FP" ]
+    # [ -e "$___X_CMD_DEVTTY_FP" ]
+    [ -e "$___X_CMD_DEVTTY_FP" ] # && [ -w "$___X_CMD_DEVTTY_FP" ]
+}
+
+___x_cmd_runmode_allow_auto(){     [ "${___X_CMD_RUNMODE:-0}" -le 0 ]; }
+___x_cmd_runmode_allow_manual(){   [ "${___X_CMD_RUNMODE:-0}" -ge 5 ] && ___x_cmd_runmode_is_interatable; }
+___x_cmd_runmode_allow_chatty(){   [ "${___X_CMD_RUNMODE:-0}" -ge 9 ] && ___x_cmd_runmode_is_interatable; }
+
+
+    # {
+    #     [ -e /dev/tty ] || return 1
+    #     [ ! -t 0 ]
+    # }
+
+
+# EndSection
+
+# Section: compat: syncfs tab
+___x_cmd_compat_syncfs(){
+    # gitbash: -f
+    # For centos-7.9
+    # This function mostly used in /dev/tty. In some environment, there is no /dev/tty.
+    if ___x_cmd_cmds sync -f "$___X_CMD_ROOT/X" 2>/dev/null; then
+        ___x_cmd_compat_syncfs(){
+            [ -e "$1" ]     || return 0
+            ___x_cmd_cmds sync -f "$@"
         }
-        ;;
-    *)
-        ___x_cmd_str___dash2underline(){
-            ___X_CMD_STR___DASH2UNDERLINE="${1//-/_}"
+    else
+        ___x_cmd_compat_syncfs(){
+            [ -e "$1" ]     || return 0
+            ___x_cmd_cmds sync "$@"
         }
-        ;;
-esac
-
-
-___x_cmd_storerat_(){
-    x_=""
-
-    [ "$___X_CMD_SHELL" = zsh ] || {
-        x_="$("$@")"
-        return
-    }
-    # "$@" | x_="$(command cat)" # Don't use ___x_cmd_cmds_cat here. ZSH bug.
-    local IFS=" "
-    local line; local _exitcode=0
-    {
-        trap 'printf "\nX_CMD_STORE_EXITCODE:%s\n" "130"' INT
-        "$@"
-        printf "\nX_CMD_STORE_EXITCODE:%s\n" "$?"
-    } | while read -r line; do
-        case "$line" in
-            X_CMD_STORE_EXITCODE:*)     _exitcode="${line#*:}" ;;
-            *)                          x_="${x_}${line}
-"
-        esac
-    done
-
-    ___x_cmd str trim_ "$x_"
-    return "$_exitcode"
+    fi && ___x_cmd_compat_syncfs "$@"
 }
 
-___x_cmd_storecat_(){
-    x_=""
-    [ "$___X_CMD_SHELL" = zsh ] || {
-        x_="$("$@")"
-        return
-    }
-
-    # In zsh trap exit is local
-    local fdir="$___X_CMD_ROOT_TMP/storeex/$$"
-    local _exitcode=0
-    trap 'command rm -f $fdir' EXIT
-    ___x_cmd ensurefp "$fdir"
-    "$@" >"$fdir"
-    _exitcode="$?"
-    # ___x_cmd_rat_ "$fdir"
-    x_="$(command cat "$fdir")"
-
-    # "$@" | x_="$(command cat)"  # Don't use ___x_cmd_cmds_cat here. ZSH bug.
-    return "$_exitcode"
+## Deprecated, just in case.
+___x_cmd_tab(){
+    x:warn "tab module is renamed to cutt"
+    ___x_cmd cutt "$@"
 }
+# EndSection
 
-___x_cmd_storeread_(){
-    x_=""
-    [ "$___X_CMD_SHELL" = zsh ] || {
-        x_="$("$@")"
-        return
-    }
+# Section: pkgfasboot
+___x_cmd_pkgbootfast(){
+    local sphere_name=X
+    if [ ! -f "$___X_CMD_ROOT_DATA/pkg/sphere/$sphere_name/.x-cmd/link/env.rc" ]; then
+        ___x_cmd pkg sphere fastboot init --sphere "$sphere_name" || return $?
+    fi
 
-    "$@" | read -r x_
-}
+    . "$___X_CMD_ROOT_DATA/pkg/sphere/$sphere_name/.x-cmd/link/env.rc"
 
-___x_cmd_fifo_pipe(){
-    local evalcode="$1";    shift
-    local tmpfifo
-
-    # x date vlid is also ok.
-    # timestamp will be better ...
-    tmpfifo="$___X_CMD_ROOT_DATA/$$/$(___x_cmd rand int 1 9999)"
-    ___x_cmd_cmds mkfifo "$tmpfifo"
-
-    (
-        trap 'rm "$tmpfifo" 2>/dev/null 1>/dev/null' EXIT
-        eval "$evalcode" > "$tmpfifo"
-    ) &
-
-    {
-        ___x_cmd_cmds rm "$tmpfifo"
-        "$@"
-    } <"$tmpfifo"
+    # local p=""
+    # while read -r p; do
+    #     PATH="$p:$PATH"
+    # done <"$___X_CMD_ROOT_DATA/pkg/boot/fast/path.list"
 }
