...

diff --git a/mod/boot/latest b/mod/boot/latest
--- a/mod/boot/latest
+++ b/mod/boot/latest
@@ -8,7 +8,7 @@ xrc:mod:lib boot    mod rc chrun ch alterdefault
 
 ___x_cmd_boot(){
     if [ ! -d "$___X_CMD_BOOT_DATA" ] && ! mkdir -p "$___X_CMD_BOOT_DATA"; then
-        printf "boot abort for mkdir fails: %s\n" "$___X_CMD_BOOT_DATA" >/dev/stderr
+        printf "boot abort for mkdir fails: %s\n" "$___X_CMD_BOOT_DATA" >&2
         return 1
     fi
 
diff --git a/mod/env/lib/main b/mod/env/lib/main
--- a/mod/env/lib/main
+++ b/mod/env/lib/main
@@ -3,11 +3,6 @@
 ___x_cmd_env___pasre_pkg_version_set(){
     [ -n "$1" ] || M='Please provide package and its version in form of <pkg>=<-|<version>>' N=env log:ret:1
     case "${1}" in
-        *=-)
-            ___X_CMD_ENV___PARSE_PKG="${1%=-}"
-            ___x_cmd_env_prev_ "${1%=-}"
-            ___X_CMD_ENV___PARSE_VERSION="$___X_CMD_ENV_PREV"
-            ;;
         *=*)
             ___X_CMD_ENV___PARSE_PKG="${1%=*}"
             ___X_CMD_ENV___PARSE_VERSION="${1#*=}"
@@ -37,7 +32,7 @@ ___x_cmd_env___pasre_pkg_version_unset(){
 # Section: use
 # use = download + populate + link + linkenv + boot + save config
 ___x_cmd_env_use(){
-    local X_help_cmd='___x_cmd_env_help use';   help:arg-null:parse
+    local X_help_cmd='x help -m env use';   help:arg-null:parse
     local dir_path
     case "$1" in
         --ws) shift; dir_path="${1}"; shift ;;
@@ -47,9 +42,6 @@ ___x_cmd_env_use(){
             ;;
     esac
 
-    local ___X_CMD_ENV_LSENV_APP_CANDIDATE
-    [ $# -gt 0 ] || ___x_cmd_env_lsenv_app || return 1
-    [ -z "$___X_CMD_ENV_LSENV_APP_CANDIDATE" ] || set -- "$___X_CMD_ENV_LSENV_APP_CANDIDATE"
 
     x:trace env/use
 
@@ -70,13 +62,13 @@ ___x_cmd_env_use(){
             return 1
         fi
 
-        if ! [ -d "$___X_CMD_PKG_POPULATE_PATH/$___X_CMD_ENV___PARSE_PKG/$___X_CMD_ENV___PARSE_VERSION" ]; then
-            env:debug "Step 2/4: Populating $___X_CMD_ENV___PARSE_PKG $___X_CMD_ENV___PARSE_VERSION"
-            if ! ___x_cmd_pkg populate "$___X_CMD_ENV___PARSE_PKG" "$___X_CMD_ENV___PARSE_VERSION" ; then
-                env:error "Cannot populate package - '$___X_CMD_ENV___PARSE_PKG $___X_CMD_ENV___PARSE_VERSION'"
-                return 1
-            fi
+
+        env:debug "Step 2/4: Populating $___X_CMD_ENV___PARSE_PKG $___X_CMD_ENV___PARSE_VERSION"
+        if ! ___x_cmd_pkg populate "$___X_CMD_ENV___PARSE_PKG" "$___X_CMD_ENV___PARSE_VERSION" ; then
+            env:error "Cannot populate package - '$___X_CMD_ENV___PARSE_PKG $___X_CMD_ENV___PARSE_VERSION'"
+            return 1
         fi
+
 
         env:debug "Step 3/4: Linking $___X_CMD_ENV___PARSE_PKG $___X_CMD_ENV___PARSE_VERSION"
         if ! ___x_cmd_pkg link "$___X_CMD_ENV___PARSE_PKG" "$___X_CMD_ENV___PARSE_VERSION" "$dir_path" ; then
@@ -85,7 +77,7 @@ ___x_cmd_env_use(){
         fi
 
         env:debug "Step 4/4: Booting $___X_CMD_ENV___PARSE_PKG $___X_CMD_ENV___PARSE_VERSION"
-        ___x_cmd_env_boot "--tip" "${___X_CMD_ENV___PARSE_PKG}=${___X_CMD_ENV___PARSE_VERSION}"  || return 1
+        ___x_cmd_env_boot "${___X_CMD_ENV___PARSE_PKG}=${___X_CMD_ENV___PARSE_VERSION}"  || return 1
         code="$code $___X_CMD_ENV___PARSE_PKG=$___X_CMD_ENV___PARSE_VERSION"
     done
 
@@ -122,7 +114,7 @@ ___x_cmd_env_use___save_config(){
 
 # Section: unuse
 ___x_cmd_env_unuse(){
-    local X_help_cmd='___x_cmd_env_help unuse';   help:arg-null:parse
+    local X_help_cmd='x help -m env unuse';   help:arg-null:parse
 
     local dir_path
     case "$1" in
@@ -139,6 +131,7 @@ ___x_cmd_env_unuse(){
             env:error "Cannot unuse $j"
             return 1
         }
+        ___x_cmd_pkg_unboot "$___X_CMD_ENV___PARSE_PKG" "$___X_CMD_ENV___PARSE_VERSION" "$dir_path" || return
     done
 
     local unuse_tmp; unuse_tmp="$(cat "$___X_CMD_ENV_VERSION_CONFIG_PATH")$___X_CMD_UNSEENCHAR_NEWLINE"
@@ -156,7 +149,7 @@ ___x_cmd_env_unuse(){
 # Section: try
 # try = download + populate + linkenv + boot
 ___x_cmd_env_try(){
-    local X_help_cmd='___x_cmd_env_help try';   help:arg-null:parse
+    local X_help_cmd='x help -m env try';   help:arg-null:parse
 
     local dir_path
     case "$1" in
@@ -197,7 +190,7 @@ ___x_cmd_env_try(){
         }
 
         env:debug "Step 4/4: Booting $___X_CMD_ENV___PARSE_PKG $___X_CMD_ENV___PARSE_VERSION"
-        ___x_cmd_env_boot "--tip" "${___X_CMD_ENV___PARSE_PKG}=${___X_CMD_ENV___PARSE_VERSION}" || return 1
+        ___x_cmd_env_boot "${___X_CMD_ENV___PARSE_PKG}=${___X_CMD_ENV___PARSE_VERSION}" || return 1
         code="$code $___X_CMD_ENV___PARSE_PKG=$___X_CMD_ENV___PARSE_VERSION"
     done
 
@@ -209,19 +202,18 @@ ___x_cmd_env_try(){
 
 # Section: untry
 ___x_cmd_env_untry(){
-    local X_help_cmd='___x_cmd_env_help untry';   help:arg-null:parse
-
+    local X_help_cmd='x help -m env untry';   help:arg-null:parse
 
     x:trace env/untry
     local ___X_CMD_ENV___PARSE_PKG
     local ___X_CMD_ENV___PARSE_VERSION
-    local ___X_CMD_ENV_PREV
 
     local code="___x_cmd_env___configstr_set_ \"\$___X_CMD_ENV_VERSION_CONFIG\""
 
     local i; for i in "$@"; do
         ___x_cmd_env___pasre_pkg_version_set "$i"
-        ___x_cmd_pkg rmpath "$___X_CMD_ENV___PARSE_PKG" "$___X_CMD_ENV___PARSE_VERSION"
+        ___x_cmd_pkg rmpath "$___X_CMD_ENV___PARSE_PKG" "$___X_CMD_ENV___PARSE_VERSION" || return
+        ___x_cmd_pkg_unboot "$___X_CMD_ENV___PARSE_PKG" "$___X_CMD_ENV___PARSE_VERSION" || return
         code="$code $___X_CMD_ENV___PARSE_PKG="
     done
 
@@ -246,4 +238,3 @@ ___x_cmd_env_appoint_candidate(){
         x env try "$name=$version"
     fi
 }
-
