...

diff --git a/mod/gh/lib/awk/app/table b/mod/gh/lib/awk/app/table
--- a/mod/gh/lib/awk/app/table
+++ b/mod/gh/lib/awk/app/table
@@ -14,8 +14,8 @@ ___x_cmd_gh_tui_app_datarequest(){
     start=$(( (page-1)*per_page  + 1 ))
 
     content="$( eval "$___X_CMD_GH_TUI_TABLE_REQUSET_DATA" )" || {
-        [ -n "$___gh_error_msg" ] || ___gh_error_msg="Failed to get data"
-        printf "errexit:%s\n" "$___gh_error_msg"
+        echo $content >> aaa
+        printf "errexit:%s\n" "${___gh_error_msg:-"Failed to get data"}"
         return 1
     }
     printf "data:start:%s\n%s\n" "$start" "$content"
@@ -24,8 +24,7 @@ ___x_cmd_gh_tui_app_datarequest(){
 ___x_cmd_gh_action_workflow_app_datarequest(){
     local content
     content="$( eval "$___X_CMD_GH_TUI_ACTION_WORKFLOW_REQUSET_DATA" "$1")" || {
-        [ -n "$___gh_error_msg" ] || ___gh_error_msg="Failed to get data"
-        printf "errexit:%s\n" "$___gh_error_msg"
+        printf "errexit:%s\n" "${___gh_error_msg:-"Failed to get data"}"
         return 1
     }
     printf "data:Runs_ID:%s\n%s\n" "$1" "$content"
@@ -36,12 +35,43 @@ ___x_cmd_gh_get_multi___get_data(){
 }
 
 ___x_cmd_gh_tui_app(){
+    ___X_CMD_SHBIN_CODE='
+        xrc gh ;
+        "$@"
+    ' ___x_cmd_antizshbin ___x_cmd_gh_tui_app___ "$@"
+}
+
+___x_cmd_gh_tui_app___(){
     ___x_cmd_tui_app_processer(){ ___x_cmd_gh_tui_app_processer "$@"; }
-    local filename=${1:?Provide a file name}
+    local ___gh_error_msg=
+    local hook_end=
+    local hook_begin=
+    local ___X_CMD_GH_TUI_TABLE_REQUSET_DATA="$___X_CMD_GH_TUI_TABLE_REQUSET_DATA"
+
+    while [ "$#" -gt 0 ]; do
+        case "$1" in
+            --begin)        hook_begin="$2";                            shift 2 ;;
+            --end)          hook_end="$2";                              shift 2 ;;
+            --error-msg)    ___gh_error_msg="$2";                       shift 2 ;;
+            --request-code) ___X_CMD_GH_TUI_TABLE_REQUSET_DATA="$2";    shift 2 ;;
+            --*)
+                            if [ -n "$2" ]; then
+                                # eval gh:info "${1#--}=\$2"
+                                eval "local ${1#--}=\$2 >/dev/null 2>&1"
+                            fi
+                            shift 2 ;;
+            *)              break ;;
+        esac
+    done
+
+    local fp="$___X_CMD_ROOT_MOD/gh/lib/awk/app/${1:?Provide a file name}"
+    [ -f "$fp" ] || return
     local _exitcode=0
     x tui bigapp --clear-on-exit \
-        -f "$___X_CMD_ROOT_MOD/tui/lib/eg.comp/table.comp.awk" \
-        -f "$___X_CMD_ROOT_MOD/gh/lib/awk/app/$filename"
+        ${hook_begin:+"--end"}  ${hook_begin:+"$hook_begin"}    \
+        ${hook_end:+"--end"}    ${hook_end:+"$hook_end"}        \
+        -f "$___X_CMD_ROOT_MOD/tui/lib/eg.comp/table.comp.awk"  \
+        -f "$fp"
     _exitcode="$?"
     unset -f ___x_cmd_tui_app_processer
     return "$_exitcode"
diff --git a/mod/pkg/lib/info/info b/mod/pkg/lib/info/info
--- a/mod/pkg/lib/info/info
+++ b/mod/pkg/lib/info/info
@@ -4,44 +4,45 @@ xrc:mod:lib pkg     sphere/xbin
 ___x_cmd_pkg_info(){
     local name="$1";     [ -n "$name" ]   || N=pkg M="Provide a package name" log:ret:1
 
-    local osarch="$3";   [ -n "$osarch" ] || {
-        ___x_cmd_pkg_osarch_ || return 1
-        osarch="$___X_CMD_PKG_OSARCH"
-    }
-
-    local version="$2"; [ -n "$version" ] || {
-        local x_=""; ___x_cmd_pkg_default_version_ "$name" "$osarch" || return
-        [ -n "$x_" ] || N=pkg M="Not found $name version" log:ret:1
-        version="$x_"
-    }
-
-    local pkg_real_name=
+    local x_=;  local pkg_real_name=
     pkg_real_name="$( ___x_cmd_pkg_locate "$name" )"
-
     [ -n "$pkg_real_name" ] || {
-        local x_=; ___x_cmd_pkg_sphere_xbin_get_binmod_name_ "$name" 2>/dev/null
+        x_=; ___x_cmd_pkg_sphere_xbin_get_binmod_name_ "$name" 2>/dev/null
         [ -z "$x_" ] || pkg_real_name="$( ___x_cmd_pkg_locate "$x_" )"
     }
 
     # TODO: If there is not such package, search the binary provided and return the package name.
-    [ -n "$pkg_real_name" ] || {
-
-        pkg_real_name="$( ___x_cmd_pkg___recorrect_name "$name" )" ||  N=pkg M="Not found $name" log:ret:1
-
-        if [ -t 1 ] && ___x_cmd_is_interactive; then
-            pkg_real_name="$(printf "%s" "$pkg_real_name" | x pick --ask "Not found $name. Do you mean the following pkg?" --row 6)"
+    if [ -z "$pkg_real_name" ]; then
+        pkg:error "Not found $name"
+        if [ ! -t 1 ] || ! ___x_cmd_is_interactive; then
+            return 1
         else
-             N=pkg M="Not found $name" log:ret:1
+            local namelist=
+            namelist="$( ___x_cmd_pkg___recorrect_name "$name" )"
+            [ -n "$namelist" ] || return 1
+
+            x_=; ___x_cmd_storeread_  x pick --ask "Do you mean the following pkg?" --row 6 printf "%s" "$namelist"
+            [ -n "$x_" ] ||  return 1
+
+            name="$x_"
+            pkg_real_name="$( ___x_cmd_pkg_locate "$name" )"
         fi
+    fi
 
-        [ -n "$pkg_real_name" ] ||  N=pkg M="Not found $1" log:ret:1
-        pkg_real_name="$( ___x_cmd_pkg_locate "$pkg_real_name" )"
-
-    }
 
     local filepath="${___X_CMD_PKG_METADATA_PATH}/${pkg_real_name}/info.tt.json"
+    [ -f "$filepath" ] || N=pkg M="Not found [file=$filepath]" log:ret:1
 
-    [ -f "$filepath" ] || N=pkg M="Not found file: $filepath" log:ret:1
+    local version="$2"; [ -n "$version" ] || {
+        x_=""; ___x_cmd_pkg_default_version_ "$name" "$osarch"
+        [ -n "$x_" ] || N=pkg M="Not found $name version" log:ret:1
+        version="$x_"
+    }
+
+    local osarch="$3";   [ -n "$osarch" ] || {
+        ___x_cmd_pkg_osarch_ || return 1
+        osarch="$___X_CMD_PKG_OSARCH"
+    }
 
     < "$filepath" x cawk  \
         -E version,osarch,___X_CMD_WEBSRC_REGION,pkg_real_name \
