...

diff --git a/mod/hashdir/lib/main b/mod/hashdir/lib/main
--- a/mod/hashdir/lib/main
+++ b/mod/hashdir/lib/main
@@ -1,17 +1,15 @@
 # shellcheck shell=dash
 ___x_cmd_hashdir___main(){
     [ $# -gt 0 ] || {
-        x help -m hashdir 1>&2
-        return 1
+        ___x_cmd help -m hashdir 1>&2
+        return 64
     }
 
     local op="$1";  shift
     case "$op" in
         --md5|--sha1|--sha256|--sha384|--sha512)    ___x_cmd_hashdir_cal "${op#--}"     "$@" ;;     # This is the main function
-        md5|sha1|sha256|sha384|sha512)              ___x_cmd_hashdir_cal "${op}"        "$@" ;;     # Deprecated
-        --cal)                                      ___x_cmd_hashdir_cal "$@" ;;                    # This is a inner function
-        -h|--help)                                  x help -m hashdir 1>&2
-                                                    return 1  ;;
+        --cal)                                      ___x_cmd_hashdir_cal "$@"   ;;                    # This is a inner function
+        -h|--help)                                  ___x_cmd help -m hashdir    ;;
 
         *)                                          ___x_cmd_hashdir_cal md5 "$op" "$@" ;;
     esac
@@ -22,7 +20,7 @@ ___x_cmd_hashdir_cal(){
     case "$HASH" in
         md5|sha1|sha256|sha384|sha512)
             while [ $# -gt 0 ]; do
-                ___x_cmd_hashdir_cal_main "$1" | x "$HASH"
+                ___x_cmd_hashdir_cal_main "$1" | ___x_cmd "$HASH"
                 shift
             done
             ;;
@@ -32,18 +30,25 @@ ___x_cmd_hashdir_cal(){
 }
 
 ___x_cmd_hashdir_cal_main(){(
-    x cd "${1:?Provide diretory}" || {
-        x:error "Cannot cd into directory: $1"
+    local dir="${1:?Provide diretory}"
+    ___x_cmd cd "$dir" || {
+        x:error "Cannot cd into directory: $dir"
         return 1
     }
 
-    command find . | LC_ALL=C command sort | while read -r line; do
+    ___x_cmd_cmds find . | LC_ALL=C ___x_cmd_cmds sort | while read -r line; do
         [ "$line" != "." ] || continue
         if [ -d "$line" ]; then
             printf "%s\n" "${line#./}"
         else
-            x log :hashdir debug "Calculating HASH[$HASH] of $line"
-            printf "%s %s\n" "$(x "$HASH" "$line")" "${line#./}"
+            # ___x_cmd log :hashdir debug "Calculating HASH[$HASH] of $line"
+            printf "%s %s\n" "$(___x_cmd "$HASH" "$line")" "${line#./}"
         fi
-    done
+    done | {
+        if ! ___x_cmd_is_interactive; then
+            ___x_cmd_cmds cat
+        else
+            ___x_cmd ui rotate --clear --raw -n 3 --prompt-running "Calculating the [hash=$HASH] value of the [directory=$PWD]..."
+        fi
+    }
 )}
