...

diff --git a/mod/pkg/lib/inner/_smoke b/mod/pkg/lib/inner/_smoke
--- a/mod/pkg/lib/inner/_smoke
+++ b/mod/pkg/lib/inner/_smoke
@@ -1,7 +1,9 @@
 # shellcheck    shell=dash disable=SC2010
-___x_cmd_pkg__smoke() (
+___x_cmd_pkg__smoke()(
+    ___x_cmd_pkg_osarch_ || return
     local candidate; candidate="$1"
     local version="${2:-$(___x_cmd_pkg_default_version "$candidate")}"
+    local sphere_name="X"
 
     pkg:info "Smoke testing candidate=$candidate version=$version"
 
@@ -12,11 +14,16 @@ ___x_cmd_pkg__smoke() (
     fi
 
     pkg:info "Step2 => Checking the install path of $candidate $version"
-    local bin_path=; local bin_name=; local cur= local tgt=; local sphere_version=
-    ___x_cmd_pkg___attr "$candidate" "$version" "$osarch" "sphere_version"
-    sphere_version="${sphere_version:-"X"}"
-    tgt="$___X_CMD_PKG_ROOT_SPHERE/$sphere_version/populate/$candidate/$version"
-    ___x_cmd_pkg___list_all_bin_path "$candidate" "$version" "" "$tgt"| while read -r bin_path; do
+    local bin_path=; local bin_name=; local cur=; local tgt=;
+    local x_treename=; ___x_cmd_pkg_treename_ "$candidate" "$version" "$___X_CMD_PKG_OSARCH" || return
+    tgt="$___X_CMD_PKG_ROOT_SPHERE/$sphere_name/$x_treename/$candidate/$version"
+    ___x_cmd_pkg_sphere_link___list_all_bin_path "$candidate" "$version" "$___X_CMD_PKG_OSARCH" "$tgt"| while read -r bin_path; do
+        [ -n "$bin_path" ] || continue
+        [ -f "$bin_path" ] || {
+            pkg:error "Not found $bin_path for $candidate $version bin link"
+            return 1
+        }
+
         bin_name="${bin_path##*/}"
         unset -f "$bin_name" 2>/dev/null || true
         unalias "$bin_name" 2>/dev/null || true
@@ -26,7 +33,7 @@ ___x_cmd_pkg__smoke() (
             return 12
         fi
 
-        local expected_prefix="$___X_CMD_PKG_POPULATE_PATH/$candidate"
+        local expected_prefix="$___X_CMD_PKG_ROOT_SPHERE/$sphere_name/$x_treename/$candidate"
         if [  "${cur#"$expected_prefix"}" = "$cur" ] || ! ( printf "%s" "$cur" | grep -q "$version") ; then
             pkg:error "Smoke FAIL. $candidate $version is not installed in $expected_prefix or $cur does not contain $version"
             return 12
diff --git a/mod/pkg/lib/mutate/download b/mod/pkg/lib/mutate/download
--- a/mod/pkg/lib/mutate/download
+++ b/mod/pkg/lib/mutate/download
@@ -13,6 +13,7 @@ ___x_cmd_pkg_download(){
             return
             ;;
     esac
+    ___x_cmd_pkg_prepare "$@" || return
     ___x_cmd_pkg___download "$@"
 }
 
@@ -29,8 +30,9 @@ ___x_cmd_pkg___download(){
         return 1
     }
 
-    local download_file_ext; local md5 ; local sha1 ; local sha256; local sha512 ; local unpack
-    ___x_cmd_pkg___attr "$name" "$version" "$osarch" "md5,sha1,sha256,sha512,download_file_ext,unpack"
+    local download_file_ext=; local md5= ; local sha1= ; local sha256=; local sha512=;
+    local unpack=; local npm=; local npmurl_cn=; local npmurl_internet=; local url_cn=; local url_internet=
+    ___x_cmd_pkg___attr "$name" "$version" "$osarch" "md5,sha1,sha256,sha512,download_file_ext,unpack,npm,url.${___X_CMD_WEBSRC_REGION:-internet},npmurl.${___X_CMD_WEBSRC_REGION:-internet}" || return
     [ -n "$unpack" ] || {
         pkg:debug "Skip download"
         return 0
@@ -39,19 +41,31 @@ ___x_cmd_pkg___download(){
     if [ "$unpack" = "none" ] && [ -z "$download_file_ext" ]; then
         local ball="$___X_CMD_PKG_DOWNLOAD_PATH/$name/$name.${os}.${arch}"
     else
-        local ball="$___X_CMD_PKG_DOWNLOAD_PATH/$name/${version}_${os}_${arch}.$download_file_ext"
+        if [ "$___X_CMD_WEBSRC_REGION" = "cn" ] && [ "$npm" = "yes" ];then
+            local ball="$___X_CMD_PKG_DOWNLOAD_PATH/$name/${version}_${os}_${arch}.tgz"
+        else
+            local ball="$___X_CMD_PKG_DOWNLOAD_PATH/$name/${version}_${os}_${arch}.$download_file_ext"
+        fi
     fi
+
 
     x mkdirp "$___X_CMD_PKG_DOWNLOAD_PATH/$name" || {
         pkg:error "Create $___X_CMD_PKG_DOWNLOAD_PATH/$name failed" ; return 1
     }
 
-    ( bgsingleton_name="${name}_${version}_${os}_${arch}" x bgsingleton run --wait ___x_cmd_pkg_download___inner_ )
+    ( x fslock run "pkg_download_${name}_${version}_${os}_${arch}" ___x_cmd_pkg_download___inner_ "$name" "$version" "$osarch" "$ball" )
+
     [ -f "$ball" ]
 }
 
+# ___X_CMD_PKG_DOWNLOAD_SOURCE=
+# http://
+# github
+# npmmirror
+# npm
+
 ___x_cmd_pkg_download___inner_(){
-    pkg:debug --Download name "$name" --version "$version" --url_list "$url_list" --ball "$ball"
+    pkg:debug --Download name "$name" --version "$version" --ball "$ball"
     if [ -f "$ball" ]; then
         if ___x_cmd_pkg_download___check_hashsum "$ball" "$md5" "$sha1" "$sha256" "$sha512"; then
             pkg:info "File already downloaded: $ball"
@@ -62,47 +76,67 @@ ___x_cmd_pkg_download___inner_(){
         x rmrf "$ball"
     fi
 
-    local url_list; url_list="$(___x_cmd_pkg___list "$name" "$version" "$osarch" "url.${___X_CMD_WEBSRC_REGION:-internet}" )" || return
+    local url_strategy=npm
+    if [ -n "$___X_CMD_GHACTION_INSIDE" ]; then
+        url_strategy=github
+    else
+        case "$___X_CMD_PKG_DOWNLOAD_SOURCE" in
+            github)     url_strategy=github  ;;
+            npm)        url_strategy=npm     ;;
+            *)          ;; # inner
+        esac
+    fi
 
-    if [ -z "$url_list" ]; then
+    local url=
+    if [ "$url_strategy" = npm ] && [ "$npm" = yes ]; then
+        eval url="\$npmurl_${___X_CMD_WEBSRC_REGION:-internet}"
+    else
+        eval url="\$url_${___X_CMD_WEBSRC_REGION:-internet}"
+    fi
+
+    if [ -z "$url" ]; then
         pkg:error "Not found url for $name $version"
         pkg:error "Please use 'x pkg ll' or 'x pkg ls all <candidate>' to check available candidate and version"
         return 1
     fi
 
-    (
-    while read -r url; do
-        pkg:info \
-            -m "download $name=$version, thanks to the courtesy of ${url%/"${url#*//*/}"}" \
-            --url "$url" --destination "$ball" --name "$name" --version "$version"
+    pkg:info \
+        -m "download $name=$version, thanks to the courtesy of ${url%/"${url#*//*/}"}" \
+        --url "$url" --destination "$ball" --name "$name" --version "$version"
 
-        x curl -I "$url" | {
-            trap 'x pkg remove $name $version 2>/dev/null; printf "\r\n";  pkg:error "Download interrupted"; return 1;' INT
-            read -r head;
-            head="${head#* }"; head="${head%% *}"
-            case "$head" in
-                2??|3??)
-                    if ! x curl --progress-bar --location --retry-max-time 10 --retry 0 "$url" --output "$ball"; then
-                        pkg:warn "Fail to download from $url"
-                        x rmrf "$ball"
-                        return 1
-                    fi
-                    ;;
-                *)
-                    pkg:error "resource invalid: $url "
+    x curl -I "$url" | {
+        trap 'x pkg remove $name $version 2>/dev/null; printf "\r\n";  pkg:error "Download interrupted"; return 1 || exit 1;' INT
+        read -r head;
+        head="${head#* }"; head="${head%% *}"
+        case "$head" in
+            2??|3??)
+                if ! x curl --progress-bar --location --retry-max-time 10 --retry 0 "$url" --output "$ball"; then
+                    pkg:warn "Fail to download from $url"
+                    x rmrf "$ball"
                     return 1
-                    ;;
-            esac
-        }
+                fi
+                ;;
+            *)
+                printf "\r"
+                pkg:error "resource invalid => $url"
+                return 1
+                ;;
+        esac
+    }
 
-        ! ___x_cmd_pkg_download___check_hashsum "$ball" "$md5" "$sha1" "$sha256" "$sha512" || return 0
-        pkg:error "File corrupted."
-        x rmrf "$ball"
-        return 1
-    done <<A
-$url_list
-A
-    )
+    if [ "$url_strategy" = npm ] && [ "$npm" = yes ]; then
+        local npm_package="$___X_CMD_PKG_DOWNLOAD_PATH/$name/package"
+        x uz "$ball"  "$___X_CMD_PKG_DOWNLOAD_PATH/$name" || M='Unzip npm package failed' N=pkg log:ret:1
+        x mv "$npm_package/bin/"* "$___X_CMD_PKG_DOWNLOAD_PATH/$name/" ||  M='Move npm package failed' N=pkg log:ret:1
+        x rmrf "$ball" "$npm_package" || M='Remove npm package failed' N=pkg log:ret:1
+        ball="$___X_CMD_PKG_DOWNLOAD_PATH/$name/${version}_${os}_${arch}.$download_file_ext"
+    fi
+
+    ! ___x_cmd_pkg_download___check_hashsum "$ball" "$md5" "$sha1" "$sha256" "$sha512" || return 0
+    pkg:error "File corrupted."
+    x rmrf "$ball"
+    return 1
+
 }
 
 ___x_cmd_pkg_download___check_hashsum(){
diff --git a/mod/pkg/lib/util b/mod/pkg/lib/util
--- a/mod/pkg/lib/util
+++ b/mod/pkg/lib/util
@@ -1,23 +1,51 @@
-# shellcheck    shell=sh            disable=SC3043      # xrc
+# shellcheck    shell=dash            disable=SC3043      # xrc
 
 # Section: attr
 # ___x_cmd_pkg___attr   hook.install,hook.setup
+
+# TODO: Using file caching data
 ___x_cmd_pkg___attr(){
-    eval "$(___x_cmd_pkg___attr_code "$@")"
+    local x_=; ___x_cmd_pkg___attr_code_getrc_ "$@" || return
+    . "$x_"
 }
 
-___x_cmd_pkg___attr_code(){
-    local QUERY="${4:?Provide pat}"
-    ___x_cmd_pkg___all_info "$@" |  LC_ALL="$___X_CMD_AWK_LANGUAGE" command awk \
-        -v QUERY="$QUERY" \
-        -f "$___X_CMD_ROOT_MOD/awk/lib/core.awk" \
-        -f "$___X_CMD_ROOT_MOD/awk/lib/sh.awk" \
-        -f "$___X_CMD_ROOT_MOD/awk/lib/j/json.awk"   \
-        -f "$___X_CMD_ROOT_MOD/awk/lib/j/jqparse.awk" \
-        -f "$___X_CMD_ROOT_MOD/pkg/lib/awk/util.awk" \
-        -f "$___X_CMD_ROOT_MOD/pkg/lib/awk/pkg._.awk" \
-        -f "$___X_CMD_ROOT_MOD/pkg/lib/awk/pkg.attr.awk"
+___x_cmd_pkg___attr_code_getrc_(){
+    local name="$1";    [ -n "$name" ] || N=pkg M="Provide a package name" log:ret:1
+    local version="${2:-$(___x_cmd_pkg_default_version "$name" "$osarch")}"
+    [ -n "$version" ] || N=pkg M="Not found $name version" log:ret:1
+    local osarch="$3"
+    [ -n "$osarch" ] || {
+        ___x_cmd_pkg_osarch_ || return
+        osarch="$___X_CMD_PKG_OSARCH"
+    } || N=pkg M="Not found osarch" log:ret:1
+    local QUERY="$4";   [ -n "$QUERY" ] || N=pkg M="Provide package attr" log:ret:1
+
+    local metafp="$___X_CMD_PKG_METADATA_PATH/$name/meta.tt.json"
+    local versionfp="$___X_CMD_PKG_METADATA_PATH/$name/version.tt.json"
+    local str="$___X_CMD_PKG_METADATA_PATH/$osarch/$___X_CMD_WEBSRC_REGION/$name/$version/${QUERY}"
+    local envfp="${___X_CMD_ROOT_CACHE}/pkg/attr/$str"
+    pkg:debug "attr envfp => $envfp"
+    { [ "$envfp" -nt "$metafp" ] && [ "$envfp" -nt "$versionfp" ]; } || {
+        x ensurefp "$envfp"
+        {
+            ___x_cmd_pkg___all_info "$name" "$version" "$osarch" |
+            LC_ALL="$___X_CMD_AWK_LANGUAGE" command awk \
+                -v QUERY="$QUERY" \
+                -f "$___X_CMD_ROOT_MOD/awk/lib/core.awk" \
+                -f "$___X_CMD_ROOT_MOD/awk/lib/sh.awk" \
+                -f "$___X_CMD_ROOT_MOD/awk/lib/j/json.awk"   \
+                -f "$___X_CMD_ROOT_MOD/awk/lib/j/jqparse.awk" \
+                -f "$___X_CMD_ROOT_MOD/pkg/lib/awk/util.awk" \
+                -f "$___X_CMD_ROOT_MOD/pkg/lib/awk/pkg._.awk" \
+                -f "$___X_CMD_ROOT_MOD/pkg/lib/awk/pkg.attr.awk" \
+                || printf "\n%s\n" "pkg:error \"Not found $name package data\"; false;"
+        } > "$envfp"
+    }
+
+    [ -f "$envfp" ] || return
+    x_="$envfp"
 }
+
 # EndSection
 
 # Section: script
@@ -38,20 +66,54 @@ ___x_cmd_pkg___get_script_path(){
 
 # Section: osarch
 ___x_cmd_pkg_osarch_(){
-    x_=
     if [ -z "$___X_CMD_PKG_OSARCH" ]; then
         ___X_CMD_PKG_OSARCH="$(___x_cmd_os name)/$(___x_cmd_os arch)" || return 1
         [ -n "$___X_CMD_PKG_OSARCH" ] || return 1
     fi
-
-    x_="$___X_CMD_PKG_OSARCH"
 }
 
 ___x_cmd_pkg_osarch(){
-    local x_=
     ___x_cmd_pkg_osarch_ || return
-    printf "%s\n" "$x_"
+    printf "%s\n" "$___X_CMD_PKG_OSARCH"
 }
+
+# EndSection
+
+# Section: tree name
+___x_cmd_pkg_treename_(){
+    local name="$1";    local version="$2";     local osarch="$3"
+    [ -n "$osarch" ] || {
+        ___x_cmd_pkg_osarch_ || return
+        osarch="$___X_CMD_PKG_OSARCH"
+    } || N=pkg M="Not found osarch" log:ret:1
+
+    local tree=; ___x_cmd_pkg___attr "$name" "$version" "$osarch" "tree" || return
+    ___x_cmd_pkg_treename_get_form_tree_ "$osarch" "$tree"
+}
+
+___x_cmd_pkg_treename_get_form_tree_(){
+    local osarch="$1"
+    local tree="$2"
+    [ -z "$tree" ]|| {
+        x_treename="tree.$tree"
+        return
+    }
+
+    [ -n "$osarch" ] || {
+        ___x_cmd_pkg_osarch_ || return
+        osarch="$___X_CMD_PKG_OSARCH"
+    } || N=pkg M="Not found osarch" log:ret:1
+
+    # default
+    local os="${osarch%%/*}"
+    local arch="${osarch#*/}"
+    case "$os" in
+        linux)  x_treename="tree.${os}.${arch}.glib"    ;;
+        win)    x_treename="tree.${os}.${arch}.msys"    ;;
+        *)      x_treename="tree.${os}.${arch}.0"       ;;
+    esac
+}
+
 # EndSection
 
 # Section: get raw text from all.7z
@@ -65,14 +127,13 @@ ___x_cmd_pkg___all_info(){
     case "$1" in
         --non-version) local version_json=--non-version; shift ;;
     esac
-    if [ -n "$1" ]; then
-        local name="$1"
-    else
-        pkg:error Provide pkg name
-        return 1
-    fi
+    local name="$1";    [ -n "$name" ] || N=pkg M="Provide a package name" log:ret:1
     local version="${2:-""}"
-    local osarch="${3:-${___X_CMD_PKG_OSARCH:-$(___x_cmd_pkg_osarch)}}"
+    local osarch="$3"
+    [ -n "$osarch" ] || {
+        ___x_cmd_pkg_osarch_ || return
+        osarch="$___X_CMD_PKG_OSARCH"
+    } || N=pkg M="Not found osarch" log:ret:1
 
     if [ "$name" = "$CUSTOMIZE_PKG_NAME" ]; then
         name="$CUSTOMIZE_PKG_PATH"
@@ -81,7 +142,7 @@ ___x_cmd_pkg___all_info(){
         [ -n "$name" ] || N=pkg M="Not found $1 meta.tt.json" log:ret:1
     fi
 
-    pkg:debug  --name "$name"  --version "$version" --osarch "$osarch"  --___X_CMD_PKG_METADATA_PATH "$___X_CMD_PKG_METADATA_PATH" --___X_CMD_WEBSRC_REGION "$___X_CMD_WEBSRC_REGION" "all info"
+    # pkg:debug --name "$name"  --version "$version" --osarch "$osarch"  --___X_CMD_PKG_METADATA_PATH "$___X_CMD_PKG_METADATA_PATH" --___X_CMD_WEBSRC_REGION "$___X_CMD_WEBSRC_REGION" "all info"
     printf "%s\n%s\n%s\n%s\n%s\n" "$name" "$version" "$osarch" "$___X_CMD_PKG_METADATA_PATH" "$___X_CMD_WEBSRC_REGION"
 
     cat "$___X_CMD_PKG_METADATA_PATH/$name/meta.tt.json" 2>/dev/null || N=pkg M="Not found $name meta.tt.json" log:ret:1
@@ -133,20 +194,8 @@ ___x_cmd_pkg_default_version(){
         -f "$___X_CMD_ROOT_MOD/pkg/lib/awk/pkg.default_version.awk"
 }
 
-___x_cmd_pkg___link(){
-    local expr="${4:?Provide EXPR, like bin}"
 
-    ___x_cmd_pkg___all_info  --non-version "$@" | LC_ALL="$___X_CMD_AWK_LANGUAGE" ___x_cmd_awk___inner \
-        -v EXPR="$expr" \
-        -f "$___X_CMD_ROOT_MOD/awk/lib/core.awk" \
-        -f "$___X_CMD_ROOT_MOD/awk/lib/j/json.awk"   \
-        -f "$___X_CMD_ROOT_MOD/awk/lib/j/jqparse.awk" \
-        -f "$___X_CMD_ROOT_MOD/pkg/lib/awk/util.awk" \
-        -f "$___X_CMD_ROOT_MOD/pkg/lib/awk/pkg._.awk" \
-        -f "$___X_CMD_ROOT_MOD/pkg/lib/awk/pkg.link.awk"
-}
-
-___x_cmd_pkg___get_linkenv(){
+___x_cmd_pkg___get_dep_name(){
     local expr="${4:?Provide EXPR, like path}"
 
     ___x_cmd_pkg___all_info --non-version "$@" | LC_ALL="$___X_CMD_AWK_LANGUAGE" ___x_cmd_awk___inner \
@@ -167,10 +216,23 @@ ___x_cmd_pkg___is_support(){
     return 1
 }
 
-___x_cmd_pkg___has_candidate(){
-    [ "$#" -eq 1 ] || return
-    [ -d "$___X_CMD_PKG_POPULATE_PATH/$1" ]
+___x_cmd_pkg_migrate(){
+    local add_safelist=
+    while [ "$#" -gt 0 ]; do
+        case "$1" in
+            --safelist)
+                    add_safelist=1
+                    shift
+                    ;;
+            *)      break ;;
+        esac
+    done
+
+    sphere:parse:args
+    ___x_cmd_pkg_download "$name" "$version" "$osarch" || return
+    ___x_cmd_pkg_populate "$name" "$version" "$osarch" "$sphere_name" "$___X_CMD_PKG_ROOT_SPHERE" || return
+    [ -z "$add_safelist" ] || ___x_cmd_pkg_safelist add "$name" "$version" "$osarch" "$sphere_name" "$___X_CMD_PKG_ROOT_SPHERE"
 }
-
-
-
+___x_cmd_pkg_install(){
+    ___x_cmd_pkg_migrate "$@"
+}
diff --git a/mod/theme/lib/control b/mod/theme/lib/control
--- a/mod/theme/lib/control
+++ b/mod/theme/lib/control
@@ -24,7 +24,7 @@ ___x_cmd_theme_control_try_main(){
     esac
 
     case "$1" in
-        --vscode|--gnome|--iterm|--apple|--kde|--ide|--windows|--konsole|--default)
+        --default|--vscode|--gnome|--iterm|--apple|--kde|--ide|--windows|--konsole)
             termtype="${1#--}"
             shift
             ;;
@@ -56,7 +56,7 @@ ___x_cmd_theme_control_try_inner(){
     local name=; eval name=\"\$___X_CMD_THEME_NAME_"${___X_CMD_THEME_TERM_VENDOR}"\" 2>/dev/null
 
     name="${name:-$___X_CMD_THEME_NAME_default}"
-    [ -n "$name" ] || return
+    [ -n "$name" ] || return 0
 
     ___x_cmd_theme_feature_reload
 
@@ -73,38 +73,51 @@ ___x_cmd_theme_control_unuse(){
     [ $# -ne 0 ] || set -- --default
 
     case "$1" in
-        --vscode|--gnome|--iterm|--apple|--kde|--ide|--windows|--konsole|--default)
+        --default|--vscode|--gnome|--iterm|--apple|--kde|--ide|--windows|--konsole)
             ___x_cmd_theme_control_untry "$1"
             ___x_cmd_theme_control___rcfile_modify "${1#--}" ""
             # x boot rc del x-theme
-            # TODO: off featurn transient
             theme:info "Unuse the theme successfully. ${___X_CMD_UNSEENCHAR_033}[1;33mNow you can restart your terminal.${___X_CMD_UNSEENCHAR_033}[0m"
             ;;
 
         all)
             x boot rc del "x-theme"
             x boot rc del "x-zsh-plugin"
+            x rmrf "${___X_CMD_ROOT_CFG}/theme/default"
+            ___x_cmd_theme_control_untry_all
+            theme:info "Unuse the theme successfully. ${___X_CMD_UNSEENCHAR_033}[1;33mNow you can restart your terminal.${___X_CMD_UNSEENCHAR_033}[0m"
             ;;
         *)
-            theme:error -h 'x theme unset [all]' "Invalid argument"
+            theme:error -h 'x theme unuse --help' "Invalid argument"
             return 1
             ;;
     esac
+}
+
+___x_cmd_theme_control_untry_all(){
+    local IFS=" "; local i; for i in default vscode gnome iterm apple kde ide windows konsole; do
+        eval export ___X_CMD_THEME_NAME_"$i"=
+    done
+    ___x_cmd_theme_feature_off
+    ___x_cmd_theme_control_try_inner
 }
 
 ___x_cmd_theme_control_untry(){
     local X_help_cmd=; X_help_cmd='x help -m theme untry' help:arg:parse
     local termtype=default
     case "$1" in
-        --vscode|--gnome|--iterm|--apple|--kde|--ide|--windows|--konsole|--default)
+        --default|--vscode|--gnome|--iterm|--apple|--kde|--ide|--windows|--konsole)
             termtype="${1#--}"
             shift
             ;;
     esac
 
     eval export ___X_CMD_THEME_NAME_"$termtype"=
-    local x_=; x_="$(grep "export ___X_CMD_THEME_NAME_default=" < "${___X_CMD_ROOT_CFG}/theme/default")"
-    eval "$x_"
+    [ ! -f "${___X_CMD_ROOT_CFG}/theme/default" ] || {
+        local x_=; x_="$(grep "export ___X_CMD_THEME_NAME_default=" < "${___X_CMD_ROOT_CFG}/theme/default")"
+        eval "$x_"
+        ___x_cmd_unexport ___X_CMD_THEME_NAME_default
+    }
     ___x_cmd_theme_feature_off
     ___x_cmd_theme_control_try_inner
 }
@@ -119,12 +132,20 @@ ___x_cmd_theme_control___rcfile_modify(){(
 
     eval export ___X_CMD_THEME_NAME_"$termtype"="$name"
 
-    >"${___X_CMD_ROOT_CFG}/theme/default" \
-    printf "%s\n" \
-        "export ___X_CMD_THEME_NAME_default=${___X_CMD_THEME_NAME_default}"  \
-        "export ___X_CMD_THEME_NAME_vscode=${___X_CMD_THEME_NAME_vscode}"    \
-        "export ___X_CMD_THEME_NAME_gnome=${___X_CMD_THEME_NAME_gnome}"      \
-        "export ___X_CMD_THEME_NAME_iterm=${___X_CMD_THEME_NAME_iterm}"      \
-        "export ___X_CMD_THEME_NAME_apple=${___X_CMD_THEME_NAME_apple}"      \
-        "[ -n \"\$___X_CMD_THEME_DISABLE\" ] || ___x_cmd_theme_control_try_inner"
+    if [ -z "${___X_CMD_THEME_NAME_default}${___X_CMD_THEME_NAME_vscode}${___X_CMD_THEME_NAME_gnome}${___X_CMD_THEME_NAME_iterm}${___X_CMD_THEME_NAME_apple}${___X_CMD_THEME_NAME_kde}${___X_CMD_THEME_NAME_ide}${___X_CMD_THEME_NAME_windows}${___X_CMD_THEME_NAME_konsole}" ]; then
+        x rmrf "${___X_CMD_ROOT_CFG}/theme/default"
+    else
+        >"${___X_CMD_ROOT_CFG}/theme/default" \
+        printf "%s\n" \
+            "export ___X_CMD_THEME_NAME_default=${___X_CMD_THEME_NAME_default}"     \
+            "export ___X_CMD_THEME_NAME_windows=${___X_CMD_THEME_NAME_windows}"     \
+            "export ___X_CMD_THEME_NAME_konsole=${___X_CMD_THEME_NAME_konsole}"     \
+            "export ___X_CMD_THEME_NAME_vscode=${___X_CMD_THEME_NAME_vscode}"       \
+            "export ___X_CMD_THEME_NAME_apple=${___X_CMD_THEME_NAME_apple}"         \
+            "export ___X_CMD_THEME_NAME_iterm=${___X_CMD_THEME_NAME_iterm}"         \
+            "export ___X_CMD_THEME_NAME_gnome=${___X_CMD_THEME_NAME_gnome}"         \
+            "export ___X_CMD_THEME_NAME_kde=${___X_CMD_THEME_NAME_kde}"             \
+            "export ___X_CMD_THEME_NAME_ide=${___X_CMD_THEME_NAME_ide}"             \
+            "[ -n \"\$___X_CMD_THEME_DISABLE\" ] || ___x_cmd_theme_control_try_inner"
+    fi
 )}
diff --git a/mod/user/lib/main b/mod/user/lib/main
--- a/mod/user/lib/main
+++ b/mod/user/lib/main
@@ -10,9 +10,62 @@ ___x_cmd_user___main(){
 
     local op="$1"; shift
     case "$op" in
-        add|ls|rm|current|passwd)
+        add|ls|rm|current|passwd|isroot|id|in)
             ___x_cmd_user_"$op" "$@" ;;
         -h|--help)
             x help -m user ;;
     esac
+}
+
+
+___X_CMD_USER_ID=
+
+___x_cmd_user_id_(){
+    x_=
+    [ -n "$___X_CMD_USER_ID" ] || {
+        ___X_CMD_USER_ID="$UID"
+        [ -z "$UID" ] || {
+            [ -n "$USER" ] || {
+                x:error "Unexpected error ==> USER is not set"
+                return 2
+            }
+            ___X_CMD_USER_ID="$(id -u "$USER")" || {
+                x:error "Unexpected error ==> command fail" --cmd "id -u \"\$USER\"" --user "$USER"
+                return 2
+            }
+        }
+        [ -n "$___X_CMD_USER_ID" ] || return 1
+    }
+    x_="${___X_CMD_USER_ID}"
+}
+
+___x_cmd_user_id(){
+    local x_
+    ___x_cmd_user_id_ || return
+    printf "%s\n" "$x_"
+}
+
+ # Optimization: UID GROUPS [ -w / ]
+___x_cmd_user_isroot(){
+    local x_
+    ___x_cmd_user_id_ || return
+    [ "$x_" -eq 0 ]
+}
+
+# TODO: in --one-of
+___x_cmd_user_in(){
+    local a; a=" $(id -Gn) " || {
+        sudo:error "fail to judge current user is sudo user" --user "$USER" --cmd "id -Gn"
+        return 2
+    }
+
+    [ $# -gt 0 ]    ||  M="expect more than 1 argument" N=user log:ret:64
+
+    while [ $# -gt 0 ]; do
+        # work only in linux. in macos, the sudo group name is admin. This can also be redefined.
+        case " $a " in
+            *" $1 "*)     continue      ;;
+            *)            return 1      ;;
+        esac
+    done
 }
